City.new(:country_id => "2", :name => "Umm al Qaywayn", :aliases => "Um al Quweim,Umm al Qaiwain,Umm al Qawain,Umm al Qaywayn,Yumul al Quwain,am alqywyn,Ø£Ù Ø§ÙÙÙÙÙÙ,Umm al Qaywayn", :latitude => "25.56528", :longitude => "55.55333").save
City.new(:country_id => "2", :name => "Ra's al Khaymah", :aliases => "Julfa,Khaimah,Ra's al Khaymah,Ras al Khaima,Ras al Khaimah,Raâs al Khaymah,RÄs al Khaima,ras alkhymt,Ø±Ø£Ø³ Ø§ÙØ®ÙÙØ©,Raâs al Khaymah", :latitude => "25.79111", :longitude => "55.94278").save
City.new(:country_id => "2", :name => "Khawr Fakkan", :aliases => "Fakkan,FakkÄn,Khawr Fakkan,Khawr FakkÄn,Khawr al Fakkan,Khawr al FakkÄn,Khor Fakhan,Khor Fakkan,Khor FakkÄn,Khor al Fakhan,Khor al Fakkan,Khor al FÄkhÄn,Khorfakan,Port Khor Fakkan,Khawr FakkÄn", :latitude => "25.33917", :longitude => "56.35611").save
City.new(:country_id => "2", :name => "Dubai", :aliases => "Dabei,Dibai,Dibay,Doubayi,Dubae,Dubai,Dubai emiraat,Dubaj,Dubajo,Dubajus,Dubay,Dubayy,DubaÃ¯,DÃºbÃ¦,Fort Dabei,dby,dbyy,di bai,dobai,du bai,duba'i,dubai,dubi,tupay,ÐÑÐ±Ð°Ð¸,ÐÑÐ±Ð°Ð¹,×××××,Ø¯Ø¨Ø¦Û,Ø¯Ø¨Ù,Ø¯Ø¨Û,à¤¦à¥à¤¬à¤,à®¤à¯à®ªà®¾à®¯à¯,à¸à¸¹à¹à¸,ããã¤,ææ,è¿ªæ,ëë°ì´,Dubai", :latitude => "25.25222", :longitude => "55.28").save
City.new(:country_id => "2", :name => "Diba", :aliases => "Daba,Daba al-Hisn,DabÄ,DabÄ al-á¸¤iá¹£n,Diba,Diba al Hisn,Dibah,Dibba,Dibba Al'-Khisn,Dibbah,DibÄ,DibÄ al á¸¨iÅn,DÄ«bÄ al á¸¨iÅn,Hisn Diba,Husn Dibba,ÐÐ¸Ð±Ð±Ð° ÐÐ»Ñ-Ð¥Ð¸ÑÐ½,á¸¨iÅn DibÄ,DibÄ", :latitude => "25.61667", :longitude => "56.26667").save
City.new(:country_id => "2", :name => "Sharjah", :aliases => "Al Sharjah,Ash 'Mariqah,Ash Shariqa,Ash Shariqah,Ash ShÄriqa,Ash ShÄriqah,Ash âMariqah,Ash-Shariqah' emiraat,Ash-ShÄriqah' emiraat,Sarjo,Schardscha,Shardzha,Sharga,Sharijah,Shariqah,Sharja,Sharjah,Sharzha,ShÄrijah,ShÄriqah,ShÄrja,alsharqt,carja,sharjh,sharqt,sharuja,xia er jia,ÅarÄµo,Ð¨Ð°ÑÐ´Ð¶Ð°,Ð¨Ð°ÑÐ¶Ð°,×©××¨×'×,Ø§ÙØ´Ø§Ø±ÙØ©,Ø´Ø§Ø±Ø¬Ù,Ø´Ø§Ø±ÙØ©,à®à®¾à®°à¯à®à®¾,ã·ã£ã¼ã«ã¸ã£,å¤å°è¿¦,Sharjah", :latitude => "25.36222", :longitude => "55.39111").save
City.new(:country_id => "2", :name => "Ar Ruways", :aliases => "Ar Ru'ays,Ar Ruways,Ar Ruâays,Ruwais,Ar Ruways", :latitude => "24.11028", :longitude => "52.73056").save
City.new(:country_id => "2", :name => "Al Fujayrah", :aliases => "Al Fujayrah,Al-Fudjayra,Al-Fujayrah' emiraat,Fudschaira,Fudzhejra,Fujaira,Fujairah,Fujajro,Fujayrah,FuÄµajro,alfjyrt,fjyrt,fu ji la,fujaira,Ð¤ÑÐ´Ð¶ÐµÐ¹ÑÐ°,Ø§ÙÙØ¬ÙØ±Ø©,ÙØ¬ÙØ±Ø©,ãã¸ã£ã¤ã©,å¯åæ,Al Fujayrah", :latitude => "25.12306", :longitude => "56.3375").save
City.new(:country_id => "2", :name => "Al `Ayn", :aliases => "Al Ain,Al Ajn,Al `Ayn,Al âAyn,Al'-Ajn,Al-Ain,Al-Ayn,ÐÐ»Ñ-ÐÐ¹Ð½,Ø§ÙØ¹ÙÙ,Al âAyn", :latitude => "24.19167", :longitude => "55.76056").save
City.new(:country_id => "2", :name => "`Ajman", :aliases => "Ajman,Al Ajman,`Ujman,`UjmÄn,`AjmÄn", :latitude => "25.41111", :longitude => "55.43504").save
City.new(:country_id => "2", :name => "Adh Dhayd", :aliases => "Adh Dhaid,Adh Dhayd,Al Daid,Al-Dhayd,Dayd,Dhaid,Dhayd,Duhayd,Ihaid,á¸ayd,Adh Dhayd", :latitude => "25.28222", :longitude => "55.89028").save
City.new(:country_id => "2", :name => "Abu Dhabi", :aliases => "AEbu Saby,Abu Dabi,Abu Dabis,Abu Dhabi,Abu Dhabi emiraat,Abu Zabi,Abu Zaby,Abu Zabye,Abu Zabyo,Abu á¸abi,Abu-Dabi,Abu-Dabio,Abud Dhabi,AbÃº DabÃ­,AbÃº DhabÃ­,AbÃº ZabÃ­,AbÅ« ZÌ§aby,AbÅ« ZÌ§abye,AbÅ« ZÌ§abyo,AbÅ« ZÌ§abÄ«,Ampou Ntampi,Emirato de Abu Dabi,a bu zha bi,abudabi,abwzby,Ãbu Saby,ÎÎ¼ÏÎ¿Ï ÎÏÎ±Î¼ÏÎ¹,ÎÎ¼ÏÎ¿Ï ÎÏÎ¬Î¼ÏÎ¹,ÐÐ±Ñ ÐÐ°Ð±Ð¸,ÐÐ±Ñ-ÐÐ°Ð±Ð¸,ÐÐ±Ñ-ÐÐ°Ð±Ñ,××× ××××,Ø£Ø¨ÙØ¸Ø¨Ù,ã¢ããã,é¿å¸ææ¯,ìë¶ë¤ë¹,Abu Dhabi", :latitude => "24.46667", :longitude => "54.36667").save
