City.new(:country_id => "3", :name => "Taloqan", :aliases => "Khanabad,Taikhan,Taleqan,Talikan,Talikhan,Taliqan,Talkan,Taloqan,Talugan,Talukan,Taluqan,Tologan,TÄleqÄn,TÄloqÄn,TÄluqÄn,TÄlÄ«qÄn,talqan,Ð¢Ð°Ð»Ð¸ÐºÐ°Ð½,ØªØ§ÙÙØ§Ù,Taloqan", :latitude => "36.73605", :longitude => "69.53451").save
City.new(:country_id => "3", :name => "Shindand", :aliases => "Asfazar,AsfazÄr,Sabzavar,SabzavÄr,Sabzawar,Sabzevar,SabzevÄr,Shindand,ShÄ«ndand,ShÄ«ná¸aná¸,Sindand,Å Ä«ndand,Ð¨Ð¸Ð½Ð´Ð°Ð½Ð´,Ø´ÙÙØ¯ÙØ¯,Ø´ÛÙØ¯ÙØ¯,Ø´ÛÙÚÙÚ,ShÄ«ná¸aná¸", :latitude => "33.30294", :longitude => "62.1474").save
City.new(:country_id => "3", :name => "Shibirghan", :aliases => "Seberghan,Sebeá¹ghÄn,Shahr-e Sheberghan,Shahr-e SheberghÄn,Shayurgan,Shebergan,Sheberghan,SheberghÄn,Sheberkhan,Shefrogan,Shibarghan,ShibarghÄn,Shibergan,Shibirghan,ShibirghÄn,Ð¨ÐµÐ±ÐµÑÐ³Ð°Ð½,Ø´Ø¨Ø±ØºØ§Ù,Ø´Ø¨Ø±ØºÙ,ShibirghÄn", :latitude => "36.66757", :longitude => "65.7529").save
City.new(:country_id => "3", :name => "Shahrak", :aliases => "Bati Dara,Kala Shaharak,Kala Shahrak,Kala ShahÄrak,Markaz-e Shahrak,Qal`eh Shaharak,Qal`eh-ye Bati Darrah,Qala Bati Dara,Qala BatÄ« Dara,Qala Shaharak,Qala ShahÄrak,Qala Sharak,Qalâeh ShahÄrak,Qalâeh-ye Bati Darrah,Sahrak,Shahrag,Shahrak,Shakhrak,Sharak,ShÄhrag,ShÄhrak,Wala Shahrak,Å ahrak,Ø´ÙØ±Ú©,Shahrak", :latitude => "34.10738", :longitude => "64.3052").save
City.new(:country_id => "3", :name => "Sar-e Pul", :aliases => "Sar-e Pol,Sar-e Pul,Sar-i-Pul,Sari-Pul',Ð¡Ð°ÑÐ¸-ÐÑÐ»Ñ,Ø³Ø± Ù¾Ù,Sar-e Pul", :latitude => "36.21544", :longitude => "65.93249").save
City.new(:country_id => "3", :name => "Sang-e Charak", :aliases => ",Sang-e ChÄrak", :latitude => "35.84972", :longitude => "66.43694").save
City.new(:country_id => "3", :name => "Aibak", :aliases => "Aibak,Aybak,AÄ«bak,Eybak,Haibak,Samagan,Samangan,SamangÄn,Äybak,Ð¡Ð°Ð¼Ð°Ð½Ð³Ð°Ð½,Ø¢ÛØ¨Ú©,Ø§ÛØ¨Ú©,Ø³ÙÙÚ¯Ø§Ù,AÄ«bak", :latitude => "36.26468", :longitude => "68.01551").save
City.new(:country_id => "3", :name => "Rustaq", :aliases => "Rostaq,RostÄq,Rustak,Rustaq,RustÄq,Ø±Ø³ØªØ§Ù,á¹ustÄq,RustÄq", :latitude => "37.12604", :longitude => "69.83045").save
City.new(:country_id => "3", :name => "Qarqin", :aliases => "Karkin,Karkin Bazar,Kkhanika,Qarkin,Qarqin,QarqÄ«n,Quarkin,ÐÑÐ°Ð½Ð¸ÐºÐ°,ÙØ±ÙÛÙ,QarqÄ«n", :latitude => "37.41853", :longitude => "66.04358").save
City.new(:country_id => "3", :name => "Qarawul", :aliases => "Hazrat Imam,Hazrat Imam Saiyid,Hazrat ImÄm,Karaul,Qaravol,Qarawul,QarÄvol,QarÄwul,Qaá¹Äwul,ÙØ±Ø§ÙÙ,QarÄwul", :latitude => "37.22019", :longitude => "68.78041").save
City.new(:country_id => "3", :name => "Qala i Naw", :aliases => "Kala Nao,Kalai-Naw,Kalayi-Nau,Qal'eh Now,Qal`a-i-Naw,Qal`ah-ye Now,Qal`eh Nau,Qal`eh-ye Now,Qala Nau,Qala Naw,Qala-e-Nau,Qala-i-Nau,Qalaenaw,Qalâa-i-Naw,Qalâah-ye Now,Qalâeh Nau,Qalâeh-ye Now,Qalâeh Now,Qula-i-nau,Shehr Qaleh,Shehr Qeleh,ÙÙØ¹Û ÙÙ,Qala i Naw", :latitude => "34.98735", :longitude => "63.12891").save
City.new(:country_id => "3", :name => "Pul-e Khumri", :aliases => "Pol-e Khomri,Pol-e KhomrÄ«,Pul-e Khumri,Pul-e KhumrÄ«,Pul-i-Khomri,Pul-i-Khumri,Pule Khumri,Pule Khumá¹i,Puli-Khumri,ÐÑÐ»Ð¸-Ð¥ÑÐ¼ÑÐ¸,Ù¾Ù Ø®ÙØ±Û,Pul-e KhumrÄ«", :latitude => "35.94458", :longitude => "68.71512").save
City.new(:country_id => "3", :name => "Paghman", :aliases => "Paghman,Paghman Palace,PaghmÄn,Pagman,ÐÐ°Ð³Ð¼Ð°Ð½,PaghmÄn", :latitude => "34.5875", :longitude => "68.95333").save
City.new(:country_id => "3", :name => "Nahrin", :aliases => "Nahrin,NahrÄ«n,Nakhrin,Narain,Narin,NarÄ«n,ÐÐ°ÑÑÐ¸Ð½,ÙÙØ±ÛÙ,NahrÄ«n", :latitude => "36.0649", :longitude => "69.13343").save
City.new(:country_id => "3", :name => "Maymana", :aliases => "Maimana,Maimanah,MaimÄna,Maymana,MaÄ«manah,Mejmene,Meymaneh,Mimana,mai ma na,mymnh,ÐÐµÐ¹Ð¼ÐµÐ½Ðµ,ÙÛÙÙÙ,è¿é©¬çº³,Maymana", :latitude => "35.92139", :longitude => "64.78361").save
City.new(:country_id => "3", :name => "Mehtar Lam", :aliases => "Laghman,Mehtar Lam,Mehtar LÄm,Mekhtarlam,Metarlam,Mir Talam Saheb Ziarat,Mitarlam,Miterlam,MÄ«r TalÄm ÅÄá¸©eb ZÄ«Ärat,Nawar Lam,NÄwar Lam,ÐÐ¸ÑÐ°ÑÐ»Ð°Ð¼,ÙÙØªØ± ÙØ§Ù,Mehtar LÄm", :latitude => "34.67139", :longitude => "70.20944").save
City.new(:country_id => "3", :name => "Mazar-e Sharif", :aliases => "Masar-e Scharif,Mazar-e Sarif,Mazar-e Sharif,Mazar-e Å arif,Mazar-e-Sharif,Mazar-i Szarif,Mazar-i-Sharif,Mazare Srif,Mazari Sharif,Mazari-Sharif,MazÄr-e SharÄ«f,MazÄr-e Å arÄ«f,MazÄr-i-SharÄ«f,MazÄre SÌrÄ«f,majaleu-isyalipeu,mazarisharifu,mzar shryf,ÐÐ°Ð·Ð°ÑÐ¸-Ð¨Ð°ÑÐ¸Ñ,ÙØ²Ø§Ø± Ø´Ø±ÙÙ,ÙØ²Ø§Ø± Ø´Ø±ÛÙ,ãã¶ã¼ãªã·ã£ãªã¼ã,ë§ìë¥´ì´ì¤ë¦¬í,MazÄr-e SharÄ«f", :latitude => "36.70904", :longitude => "67.11087").save
City.new(:country_id => "3", :name => "Lashkar Gah", :aliases => "Bist,Bost,Bust,Lashkar Gah,Lashkar GÄh,Lashkargah Bust,Lashkargakh,Laskargah,LasÌ²hÌ²kargÄh Busá¹¯,LaÅ¡kargÄh,Nawab City,ÙØ´ÙØ± Ú¯Ø§Ù,ÙÚÚ©Ø±Ú¯Ø§Ù Ø¨Ø³Ù¼,Lashkar GÄh", :latitude => "31.59382", :longitude => "64.37161").save
City.new(:country_id => "3", :name => "Kushk", :aliases => "Kushk,Kusk,KusÌk,KÅ«shk,ÐÑÑÐº,Ú©Ø´Ú©,Kushk", :latitude => "33.29565", :longitude => "61.95221").save
City.new(:country_id => "3", :name => "Kunduz", :aliases => "Kondoz,Konduz,KondÅ«z,Kundus,Kunduz,KundÅ«z,Qonduz,QondÅ«z,Qunduz,Quná¸Å«z,Shahr-e Qondoz,kndwz,kndz,kundo~uzu zhou,kundujeu ju,ÐÑÐ½Ð´ÑÐ·,ÙÙØ¯Ø²,ÙÙØ¯Ø²,Ú©ÙØ¯ÙØ²,ã¯ã³ãã¥ãºå·,ì¿¤ëì¦ ì£¼,Kunduz", :latitude => "36.72896", :longitude => "68.857").save
City.new(:country_id => "3", :name => "Khost", :aliases => "Khost,Khowst,KhÅst,Matun,MatÅ«n,khwst,Ð¥Ð¾ÑÑ,Ø®ÙØ³Øª,ÙØªÙÙ,KhÅst", :latitude => "33.33951", :longitude => "69.92041").save
City.new(:country_id => "3", :name => "Tashqurghan", :aliases => "Kholm,Khulm,Tashkurgan,Tashkurghan,Tashqorghan,Tashqurghan,TÄshkurghÄn,TÄshqorghÄn,TÄshqurghÄn,Ð¢Ð°ÑÐºÑÑÐ³Ð°Ð½,ØªØ§Ø´ÙØ±ØºØ§Ù,TÄshqurghÄn", :latitude => "36.69736", :longitude => "67.69826").save
City.new(:country_id => "3", :name => "Khash", :aliases => "Khas,Khash,KhÄsh,KhÄsÌ,Ø®Ø§Ø´,KhÄsh", :latitude => "31.52919", :longitude => "62.79055").save
City.new(:country_id => "3", :name => "Khanabad", :aliases => "Khanabad,KhÄnÄbÄd,Ð¥Ð°Ð½Ð°Ð±Ð°Ð´,Ø®Ø§Ù Ø¢Ø¨Ø§Ø¯,Khanabad", :latitude => "36.6825", :longitude => "69.11556").save
City.new(:country_id => "3", :name => "Karukh", :aliases => "Karokh,Karrukh,Karukh,Kaá¹ukh,Ú©Ø±Ø®,Karukh", :latitude => "34.48108", :longitude => "62.5863").save
City.new(:country_id => "3", :name => "Kandahar", :aliases => "Candahar,Kandagar,Kandahar,Kandaharo,KandahÄr,Kandhar,Qandahar,QandahÄr,Qaná¸ahÄá¹,kan da ha,kandaharu,qndhar,ÐÐ°Ð½Ð´Ð°Ð³Ð°Ñ,×§× ××××¨,ÙÙØ¯ÙØ§Ø±,ÙÙØ¯ÙØ§Ø±,ã«ã³ããã¼ã«,åå¤§å,KandahÄr", :latitude => "31.61332", :longitude => "65.71013").save
City.new(:country_id => "3", :name => "Kabul", :aliases => "Cabool,Caboul,Cabul,Cabul - kabl,Cabul - Ú©Ø§Ø¨Ù,CabÃºl,Caubul,Kabil,Kaboel,Kabol,Kaboul,Kabul,Kabula,Kabulas,Kabuli,Kabulo,Kabura,KabÃºl,KabÃ»l,Kampoul,Kobul,Kubha,KÃ¡bul,KÄbol,kabl,kabul,kabula,kabuli,kaburu,kabwl,kapul,ke bu er,khabul,ÎÎ±Î¼ÏÎ¿ÏÎ»,ÐÐ°Ð±ÑÐ»,ÐÐ¾Ð±ÑÐ»,ÕÕ¡Õ¢Õ¸ÖÕ¬,×§××××,ÙØ§Ø¨Ù,ÙØ§Ø¨ÙÙ,Ú©Ø§Ø¨Ù,à¤à¤¾à¤¬à¥à¤²,à¦à¦¾à¦¬à§à¦²,à®à®¾à®ªà¯à®²à¯,à¸à¸²à¸à¸¹à¸¥,à½à¼à½à½´à½¢,á¥ááá£áá,á«á¡á,ã«ãã¼ã«,ã«ã¼ãã«,åå¸å°,ì¹´ë¶,Kabul", :latitude => "34.52813", :longitude => "69.17233").save
City.new(:country_id => "3", :name => "Jalalabad", :aliases => "Djelalabad,Dschalalabad,Dzalalabad,Dzhalalabad,Dzhelalabad,DÅ¼alalabad,Jalakot,Jalal-Kut,Jalalabad,Jalalkoat,Jalalkot,JalÄlkot,JalÄlÄbÄd,Jelalabad,Tarun City,jalalabada,jlal abad,ÐÐ¶Ð°Ð»Ð°Ð»Ð°Ð±Ð°Ð´,Ø¬ÙØ§Ù Ø¢Ø¨Ø§Ø¯,Ø¬ÙØ§ÙâØ¢Ø¨Ø§Ø¯,à¦à¦¾à¦²à¦¾à¦²à¦¾à¦¬à¦¾à¦¦,JalÄlÄbÄd", :latitude => "34.42647", :longitude => "70.45153").save
City.new(:country_id => "3", :name => "Jabal os Saraj", :aliases => "Djabal-ul-Seradj,Dzhabal'-Ussaradzh,Dzhabalâ-Ussaradzh,Jabal Saraj,Jabal os Saraj,Jabal os SarÄj,Jabal us Siraj,Jabal us SirÄj,Jabal-us-Sirai,Jabalussaraj,Jabalussaá¹Äj,Jabl-us-Seraj,Jabl-us-Siraj,Jabul Saraj,Jibal-as-Seraj,Parwan,jbl alsraj,Ø¬Ø¨Ù Ø§ÙØ³Ø±Ø§Ø¬,Jabal os Saraj", :latitude => "35.11833", :longitude => "69.23778").save
City.new(:country_id => "3", :name => "Herat", :aliases => "Gerat,Herat,HerÄt,HÃ©rat,Kherat,Shahr-e Herat,Shahr-e HerÄt,he la te,herato,hrat,ÐÐµÑÐ°Ñ,Ð¥ÐµÑÐ°Ñ,ÙØ±Ø§Øª,ãã©ã¼ã,èµ«æç¹,HerÄt", :latitude => "34.34817", :longitude => "62.19967").save
City.new(:country_id => "3", :name => "Ghormach", :aliases => "Garmak,Ghormac,Ghormach,GhormÄch,Ghowrmach,GhowrmÄch,GhÅrmÄc,GhÅrmÄch,ghwrmch,ØºÙØ±ÙØ§Ú,ØºÙØ±ÙÚ,Ghormach", :latitude => "35.73062", :longitude => "63.78264").save
City.new(:country_id => "3", :name => "Ghazni", :aliases => "Gazni,Ghazni,GhaznÄ«,Shahr-e Ghazni,Shahr-e GhaznÄ«,gazni,gazuni,ghznt,ghznyn,ÐÐ°Ð·Ð½Ð¸,ØºØ²ÙØ©,ØºØ²ÙÛ,ØºØ²ÙÛÙ,ã¬ãºãã¼,Ghazni", :latitude => "33.55356", :longitude => "68.42689").save
City.new(:country_id => "3", :name => "Girishk", :aliases => "Gereshk,Geresk,GereÅ¡k,Girishk,Nahr-e Saraj,Nahr-e SarÄj,ÐÐµÑÐµÑÐº,Ú¯Ø±Ø´Ú©,Girishk", :latitude => "31.82089", :longitude => "64.57005").save
City.new(:country_id => "3", :name => "Gardez", :aliases => "Gardeyz,Gardez,Gardiz,GardÃªz,GardÄz,GardÄ«z,Gaá¹á¸Äz,ÐÐ°ÑÐ´ÐµÐ·,Ú¯Ø±Ø¯ÙØ²,Ú¯Ø±Ø¯ÛØ²,GardÄz", :latitude => "33.59744", :longitude => "69.22592").save
City.new(:country_id => "3", :name => "Fayzabad", :aliases => "Faizabad,FaizÄbÄd,Fajzabad,Faydz Abad,Fayá¸áº ÄbÄá¸,Fazelabad,FaÄ«áºÄbÄd,Feyzabad,FeyáºÄbÄd,fyd abad,Ð¤Ð°Ð¹Ð·Ð°Ð±Ð°Ð´,ÙÛØ¶ Ø¢Ø¨Ø§Ø¯,Fayzabad", :latitude => "37.11664", :longitude => "70.58002").save
City.new(:country_id => "3", :name => "Farah", :aliases => "Farah,Farakh,FarÄh,ÙØ±Ø§Ù,FarÄh", :latitude => "32.37451", :longitude => "62.11638").save
City.new(:country_id => "3", :name => "Islam Qal`ah", :aliases => "Eslam Qal`eh,Eslamqal`a,Eslamqalâa,EslÄm Qalâeh,Islam Kala,Islam Killa,Islam Qal`ah,Islam Qala,IslÄm Kala,IslÄm Qala,IslÄm Qalâah,Kafar Qal`eh,Kafir Kala,Kafir Qala,KÄfar Qalâeh,IslÄm Qalâah", :latitude => "34.66667", :longitude => "61.06667").save
City.new(:country_id => "3", :name => "Charikar", :aliases => "Caharikar,Carikar,Chaharikar,ChahÄrÄ«kÄr,Chairkar,Charekar,Charikar,ChÄirkÄr,ChÄrÄ«kÄr,CÄá¹ikÄá¹,ÄahÄrikÄr,Ð§Ð°ÑÐ¸ÐºÐ°Ñ,ÚØ§Ø±ÙÙØ§Ø±,Charikar", :latitude => "35.01361", :longitude => "69.17139").save
City.new(:country_id => "3", :name => "Baraki Barak", :aliases => "Baraki Barak,Baraki Burak,Barakibarak,BarakÄ« Barak,Barqi Barq,BarakÄ« Barak", :latitude => "33.9675", :longitude => "68.94861").save
City.new(:country_id => "3", :name => "Balkh", :aliases => "Bactra,Bactresh,Bakhtar,Balch,Balh,Balhika,Balkh,Bamik,Bazirabad,Bkahdi,BÄkhtar,Vazirabad,ba er he,blkh,ÐÐ°Ð»Ñ,ÐÐ°Ð·Ð¸ÑÐ°Ð±Ð°Ð´,Ø¨ÙØ®,å·´å°èµ«,Balkh", :latitude => "36.75635", :longitude => "66.8972").save
City.new(:country_id => "3", :name => "Baghlan", :aliases => "Baghlan,Baghlan - bghlan,Baghlan - Ø¨ØºÙØ§Ù,Baghlin,BaghlÄn,Baglan,Bagolaggo,Sana `Ati,Sana`ati,bghlan,ÅanÄ âAti,ÅanÄâatÄ«,ÐÐ°Ð³Ð»Ð°Ð½,Ø¨ØºÙØ§Ù,ØµÙØ§Ø¹ØªÛ,BaghlÄn", :latitude => "36.13068", :longitude => "68.70829").save
City.new(:country_id => "3", :name => "Art Khwajah", :aliases => "Art Khvajeh (1),Art Khwajah,At Khvajeh,At Khwaja,Ärt KhwÄjah,Ät KhvÄjeh,Ät KhwÄja,Äá¹t KhvÄjeh (1),Ø¢Ø±Øª Ø®ÙØ§Ø¬Ù,Ärt KhwÄjah", :latitude => "37.08571", :longitude => "69.47958").save
City.new(:country_id => "3", :name => "Asmar", :aliases => "Asma,Asmar,AsmÄr,asmar,ÄsmÄ,ÄsmÄr,Ø¢Ø³ÙØ§Ø±,Ø§Ø³ÙØ§Ø±,ÄsmÄr", :latitude => "35.03319", :longitude => "71.3577").save
City.new(:country_id => "3", :name => "Andkhoy", :aliases => "Andkhoi,Andkhoy,Andkhui,Andkhvoy,AndkhÅy,AndkhÅÄ«,AndkhÅ«i,Ankhoi,Ø§ÙØ¯Ø®ÙÛ,AndkhÅy", :latitude => "36.95293", :longitude => "65.12376").save
City.new(:country_id => "3", :name => "Markaz-e Woluswali-ye Achin", :aliases => "Achin,Achin-Ulusvali,Acin Oluswali,Markaz-e Woluswali-ye Achin,Markaz-e WoluswalÄ«-ye ÄchÄ«n,ÄchÄ«n,ÄÄÄ«n OluswÄli,Ø¢ÚÙÙ,Markaz-e WoluswalÄ«-ye ÄchÄ«n", :latitude => "34.12583", :longitude => "70.70778").save
City.new(:country_id => "3", :name => "Cool urhajo", :aliases => ",Cool Å±rhajÃ³", :latitude => "34.26545", :longitude => "67.34516").save
