City.new(:country_id => "6", :name => "Sarande", :aliases => "Agioi,Agioi Saranta,Ayii Saranda,Hagios Saranta,Porto Edda,Santa Quaranta,Santi Quaranta,Saranda,Sarande,SarandÃ«,Saranta,Zogaj,ÎÎ³Î¹Î¿Î¹ Î£Î±ÏÎ¬Î½ÏÎ±,Ð¡Ð°ÑÐ°Ð½Ð´Ð°,SarandÃ«", :latitude => "39.87556", :longitude => "20.00528").save
City.new(:country_id => "6", :name => "Kukes", :aliases => "Cucus,Kukes,Kukesi,Kuks,Kuksi,Kukuch,Kukus,KukÃ«s,KukÃ«si,ÐÑÐºÐµÑ,ÐÑÐºÑÑ,KukÃ«s", :latitude => "42.07694", :longitude => "20.42194").save
City.new(:country_id => "6", :name => "Korce", :aliases => "Corce,CorcÃ«,Coritsa,Coritza,Coriza,Corizza,Corriza,Ghiortsa Corcia,Gorica,Goritsa,Korca,Korce,Korcha,Korche,Korcza,Korica,Korice,Koritsa,Koritza,Korrca,Korrce,KorrÃ§a,KorrÃ§Ã«,Korytsa,KorÃ§a,KorÃ§Ã«,KÃ¶rice,ÐÐ¾ÑÑÐ°,KorÃ§Ã«", :latitude => "40.61861", :longitude => "20.78083").save
City.new(:country_id => "6", :name => "Gjirokaster", :aliases => "Agirocastro,Arghirocastru,Arghyrocastro,Argirocastro,Argirokastro,Argyrokastro,Argyrokastron,Aryirokastro,Aryirokastron,Ergheni,Ergiri,Ghinokastre,Girokastra,Girokastro,Gjinokaster,Gjinokastra,Gjinokastre,Gjinokastrer,GjinokastÃ«r,Gjirokaster,Gjirokastra,Gjirokastre,GjirokastrÃ«,GjirokastÃ«r,ji nuo ka si te,ÎÏÎ³ÏÏÏÎºÎ±ÏÏÏÎ¿,ÐÐ¸ÑÐ¾ÐºÐ°ÑÑÑÐ°,ÐÑÐ³Ð¸ÑÐ¾ÐºÐ°ÑÑÑÐ¾,ÐÐ¸ÑÐ¾ÐºÐ°ÑÑÑÐ°,ÐÐ¸ÑÐ¾ÐºÐ°ÑÑÑÐ¾,åè¯ºå¡æ¯ç¹,GjirokastÃ«r", :latitude => "40.07583", :longitude => "20.13889").save
City.new(:country_id => "6", :name => "Elbasan", :aliases => "Ehl'basan,Elbasan,Elbasani,Elbassan,Ð­Ð»ÑÐ±Ð°ÑÐ°Ð½,Elbasan", :latitude => "41.1125", :longitude => "20.08222").save
City.new(:country_id => "6", :name => "Burrel", :aliases => "Burela,Burele,Bureli,BurelÃ«,Burrel,Burrel',Burrele,Burreli,BurrelÃ«,ÐÑÑÑÐµÐ»Ñ,Burrel", :latitude => "41.61028", :longitude => "20.00889").save
City.new(:country_id => "6", :name => "Vlore", :aliases => "Au'lon,Auâlon,Avlon,Avlona,Avlonya,Vallona,Valona,Vl'ora,Vljora,Vlona,Vlone,VlonÃ«,Vlora,Vlore,VlorÃ«,VÄ¼ora,ÐÐ°Ð»Ð¾Ð½Ð°,ÐÐ»ÑÐ¾ÑÐ°,ÐÐ»ÑÑÐ°,VlorÃ«", :latitude => "40.46667", :longitude => "19.48972").save
City.new(:country_id => "6", :name => "Tirana", :aliases => "Tiran,Tirana,Tirane,Tirano,TiranÃ«,TirÄna,Tyrana,Tyranna,TÃ­rana,de la na,tilana,tirana,tyrana,tyrnh,Î¤Î¯ÏÎ±Î½Î±,Ð¢Ð¸ÑÐ°Ð½Ð°,Ð¢ÑÑÐ°Ð½Ð°,×××¨× ×,ØªÙØ±Ø§ÙØ§,ØªÙØ±Ø§ÙØ§,ãã£ã©ã,å°æé£,í°ë¼ë,Tirana", :latitude => "41.3275", :longitude => "19.81889").save
City.new(:country_id => "6", :name => "Shkoder", :aliases => "Iskodra,Scutari,Shkoder,Shkodra,ShkodÃ«r,Skadar,Skodra,Szkodra,sqwdr,Ä°Åkodra,Å kodra,Ð¡ÐºÐ°Ð´Ð°Ñ,Ð¨ÐºÐ¾Ð´ÐµÑ,Ð¨ÐºÐ¾Ð´ÑÐ°,×©×§×××¨,ShkodÃ«r", :latitude => "42.06828", :longitude => "19.51258").save
City.new(:country_id => "6", :name => "Patos Fshat", :aliases => "Patos Fshat,Patosi Fshat,Patos Fshat", :latitude => "40.64278", :longitude => "19.65083").save
City.new(:country_id => "6", :name => "Lushnje", :aliases => "Ljushna Cod a Gomares,Ljushnja,Ljusnje,LjuÅ¡nje,Lousnia,Lushne,Lushnja,Lushnje,LushnjÃ«,Lusnje,LuÅ¡nje,ÐÑÑÐ½Ñ,LushnjÃ«", :latitude => "40.94194", :longitude => "19.705").save
City.new(:country_id => "6", :name => "Lezhe", :aliases => "Alessio,Lesh,Leshe,Leshi,Lezh,Lezha,Lezhe,LezhÃ«,Lisi,Ljes,LjeÅ¡,Lyesh,ÐÐµÐ¶Ð°,LezhÃ«", :latitude => "41.78361", :longitude => "19.64361").save
City.new(:country_id => "6", :name => "Lac", :aliases => "Lac,Laci,Lak,Latsch,LaÃ§,LaÃ§i,ÐÐ°Ðº,LaÃ§", :latitude => "41.63556", :longitude => "19.71306").save
City.new(:country_id => "6", :name => "Kucove", :aliases => "Kuchova,Kucova,Kucove,KuÃ§ova,KuÃ§ovÃ«,Petrolia,Qyteti Stalin,Stalin,ÐÑÑÐ¾Ð²Ð°,KuÃ§ovÃ«", :latitude => "40.80028", :longitude => "19.91667").save
City.new(:country_id => "6", :name => "Kruje", :aliases => "Akcehisar,AkÃ§ehisar,Croia,Cruja,Krna,Kroia,Kroja,Kroya,KroÃ¯a,Krue,Krueja,Kruja,Kruje,KrujÃ«,ÐÑÑÐµ,KrujÃ«", :latitude => "41.50917", :longitude => "19.79278").save
City.new(:country_id => "6", :name => "Kavaje", :aliases => "Cavaia,Cavaja,Kavaia,Kavaj,Kavaja,Kavaje,KavajÃ«,KavaÃ¯a,ÐÐ°Ð²Ð°Ð¹Ðµ,ÐÐ°Ð²Ð°Ñ,KavajÃ«", :latitude => "41.18556", :longitude => "19.55694").save
City.new(:country_id => "6", :name => "Fier-Cifci", :aliases => ",Fier-ÃifÃ§i", :latitude => "40.71667", :longitude => "19.56667").save
City.new(:country_id => "6", :name => "Fier", :aliases => "Fearica,Fier,Fieri,Fjeri,fei xia er,Ð¤Ð¸ÐµÑÐ¸,éå¤ç¾,Fier", :latitude => "40.72389", :longitude => "19.55611").save
City.new(:country_id => "6", :name => "Durres", :aliases => "Drac,Drach,DraÄ,Duraso,Durazzo,Durehs,Dures,Duresi,Durres,Durresa,Durresi,Durrsi,DurrÃ«s,DurrÃ«si,Durts,Durus,Durz,DurÃ«si,Dyrrachio,Dyrrachium,Dyrrakhion,Dyrrhachium,Epidamnos,dou la si,do~urasu,dwrs,ÎÏÏÏÎ¬ÏÎ¹Î¿,ÐÑÐ°Ñ,ÐÑÑÑÐµÑ,ÐÑÑÑÑ,ÐÑÑÑÑ,×××¨×¡,ãã¥ã©ã¹,é½ææ¯,DurrÃ«s", :latitude => "41.32306", :longitude => "19.44139").save
City.new(:country_id => "6", :name => "Berat", :aliases => "Beligrad,Berat,Berati,Beration,Berta,Lezskigrad,Verati,Veration,berato,pei la te,ÐÐµÑÐ°Ñ,××¨××,ãã©ã,å¹æç¹,Berat", :latitude => "40.70583", :longitude => "19.95222").save
