City.new(:country_id => "7", :name => "Kapan", :aliases => "Ghap'an,Ghapâan,Kafan,Kafin,Kapan,Katan,Madan,Qafan,Zangezur,kapan,ÐÐ°Ð¿Ð°Ð½,Ô¿Õ¡ÕºÕ¡Õ¶,Ú©Ø§Ù¾Ø§Ù,Kapan", :latitude => "39.20111", :longitude => "46.415").save
City.new(:country_id => "7", :name => "Goris", :aliases => "Geryusy,Goris,ÐÐ¾ÑÐ¸Ñ,Ô³Õ¸ÖÕ«Õ½,Goris", :latitude => "39.50778", :longitude => "46.33861").save
City.new(:country_id => "7", :name => "Hats'avan", :aliases => "Acavan,Atsavan,Hats'avan,Hatsâavan,Sisian,ÐÑÐ°Ð²Ð°Ð½,Hatsâavan", :latitude => "39.46278", :longitude => "45.97306").save
City.new(:country_id => "7", :name => "Artashat", :aliases => "Artashat,Kamarl,Kamarlu,Kamarlyu,ÐÑÑÐ°ÑÐ°Ñ,Artashat", :latitude => "39.95389", :longitude => "44.55056").save
City.new(:country_id => "7", :name => "Ararat", :aliases => "Ararat,Davalinskiy Tsemzavod,ÐÑÐ°ÑÐ°Ñ,Ararat", :latitude => "39.83028", :longitude => "44.7025").save
City.new(:country_id => "7", :name => "Yerevan", :aliases => "Ayrivan,EREVAN,Ereban,Erehvan,Ereun,Erevan,Erevano,ErevÃ¡n,Erewan,Erivan,Eriwan,Erywan,ErywaÅ,Ierevan - Erevan,IerevÃ¡n - ÔµÖÕ¥Õ¾Õ¡Õ¶,Iravan,Jerevan,Jerevanas,JerevÃ¡n,Revan,Yerevan,Yervandavan,Yiriwan,YÃ¨rÃ¨van,ayrwan,ereban,erevani,iyerebhana,shhr ayrwan,ye li wen,yeleban,yerevana,yryfan,ÃrÃ®van,Ä°rÉvan,ÎÏÎµÎ²Î¬Î½,ÐÑÐµÐ²Ð°Ð½,ÐÐµÑÐµÐ²Ð°Ð½,ÐÐ ÐÐÐÐ,ÐÑÐµÐ²Ð°Ð½,ÐÑÑÐ²Ð°Ð½,ÔµÖÕ¥Õ¾Õ¡Õ¶,ÔµÖÖÕ¡Õ¶,××¨××××,Ø§ÛØ±ÙØ§Ù,Ø´ÙØ± Ø§ÛØ±ÙØ§Ù,ÙØ±ÙÙØ§Ù,à¤¯à¥à¤°à¥à¤µà¤¾à¤¨,à¦à¦¯à¦¼à§à¦°à§à¦­à¦¾à¦¨,áá ááááá,á¬á¬á«á,ã¨ã¬ãã³,èéæº«,ìë ë°,Yerevan", :latitude => "40.18111", :longitude => "44.51361").save
City.new(:country_id => "7", :name => "Ejmiatsin", :aliases => "Artemed,Avan Vardgesi,EHCHMIADZIN,Echmiadzin,Echmiatsin,Ecmiadzin,Eczmiadzyn,Ejmiatsin,Etchmiadzine,Etschmiadsin,EÄmiadzin,Iejmiatsin,Kaynepolis,Kayrak'aghak',Kayrakâaghakâ,Norak'aghak',Norakâaghakâ,Uch'k'ilisa,Uchâkâilisa,Uckilise,Vagarsapat,Vagarshapat,Vagharshapat,Valeroktista,Vardgesavan,achmyadzyn,echmiadzini,ehchmiadzin,ÃÃ§kilise,ÐÐ°Ð³Ð°ÑÑÐ°Ð¿Ð°Ñ,Ð­Ð§ÐÐÐÐÐÐÐ,Ð­ÑÐ¼Ð¸Ð°Ð´Ð·Ð¸Ð½,ÕÕ¡Õ²Õ¡ÖÕ·Õ¡ÕºÕ¡Õ¿,Ø§ÚÙÛØ§Ø¯Ø²ÛÙ,áá©áááá«ááá,Ejmiatsin", :latitude => "40.17278", :longitude => "44.2925").save
City.new(:country_id => "7", :name => "Spitak", :aliases => "Amamlu,Amamth,Spitak,Ð¡Ð¿Ð¸ÑÐ°Ðº,Spitak", :latitude => "40.83722", :longitude => "44.2675").save
City.new(:country_id => "7", :name => "Sevan", :aliases => "SEVAN,Sevan,Ssewan,Yelenovka,Ð¡ÐÐÐÐ,Sevan", :latitude => "40.555", :longitude => "44.95361").save
City.new(:country_id => "7", :name => "Masis", :aliases => "Hrazdan,Masis,Narimanlu,Razdan,Takhanshalu,Tokhanshalu,Ulukhanlu,Zangibasar,ÐÐ°ÑÐ¸Ñ,Masis", :latitude => "40.06722", :longitude => "44.43611").save
City.new(:country_id => "7", :name => "Vanadzor", :aliases => "Gharak'ilisa,Gharakâilisa,KIROVAKAN,Karakhs,Karakilis,Karaklis,Kirovakan,Kirowakan,Korovakan,Mets Karakilisa,Vanadzor,Vanajor,Wanadsor,Wanadzor,wanadzwr,ÐÐ°Ð½Ð°Ð´Ð·Ð¾Ñ,ÐÐÐ ÐÐÐÐÐÐ,ÕÕ¡Õ¶Õ¡Õ±Õ¸Ö,ÙØ§ÙØ§Ø¯Ø²ÙØ±,Vanadzor", :latitude => "40.81278", :longitude => "44.48833").save
City.new(:country_id => "7", :name => "Gavarr", :aliases => "Gavar,Gavarr,KAMO,Kamo,Kyavar,Nor Bayazet,Nor-Bajaset,Novo Bayazet,Novyi Bayaset,ÐÐÐÐ,Gavarr", :latitude => "40.35889", :longitude => "45.12667").save
City.new(:country_id => "7", :name => "Hrazdan", :aliases => "Akhta,Akhtala,Akhti,Hrazdan,Nerkin Akhta,Nizhne Akhti,Nizhniye Akhty,Nizhnyaya Akhta,Razdan,Ð Ð°Ð·Ð´Ð°Ð½,Hrazdan", :latitude => "40.50167", :longitude => "44.75472").save
City.new(:country_id => "7", :name => "Armavir", :aliases => "Armavir,Hoktemberyan,Oktember,Oktemberyan,Sardar-Abad,Sardarapat,ÐÐºÑÐµÐ¼Ð±ÐµÑ,Armavir", :latitude => "40.15222", :longitude => "44.03083").save
City.new(:country_id => "7", :name => "Gyumri", :aliases => "Alek'pol,Alek'sandrapol,Alek'sandrobol,Aleksandropol',Aleksandropolâ,Alekâpol,Alekâsandrapol,Alekâsandrobol,Alexandropol',Alexandropolâ,GJUMRI,Gimri,Giumri,Gjumri,Guemrue,Gumri,Gumru,Gumry,Gyumri,GÃ¼mrÃ¼,Kumayri,Kumri,Kyumayri,Kyumri,KÃ¼mri,Leninakan,gyumuri,gywmry,jiu mu li,ÐÐ®ÐÐ Ð,ÐÑÐ¼ÑÐ¸,ÐÑÑÐ¼ÑÐ¸,Ô³ÕµÕ¸ÖÕ´ÖÕ«,Ú¯ÛÙÙØ±Û,ã®ã¥ã ãª,ä¹å§é,Gyumri", :latitude => "40.78944", :longitude => "43.8475").save
City.new(:country_id => "7", :name => "Ashtarak", :aliases => "ASHTARAK,Achtarak,Aschtarak,Ashtarak,Ashtarakats' Gyugh,Ashtarakatsâ Gyugh,Astarak,AÅtarak,AÅ¡tarak,ashtarak,ÐÐ¨Ð¢ÐÐ ÐÐ,ÐÑÑÐ°ÑÐ°Ðº,Ô±Õ·Õ¿Õ¡ÖÕ¡Õ¯,Ø¢Ø´ØªØ§Ø±Ø§Ú©,Ashtarak", :latitude => "40.2975", :longitude => "44.36167").save
City.new(:country_id => "7", :name => "Abovyan", :aliases => "ABOVJAN,Abovyan,Elar,ÐÐÐÐÐ¯Ð,Abovyan", :latitude => "40.26917", :longitude => "44.62444").save
