City.new(:country_id => "9", :name => "Saurimo", :aliases => "Henrique de Carvalho,Saurimo,Saurimu,Vila Henrique de Carvalho,Ð¡Ð°ÑÑÐ¸Ð¼Ð¾,Saurimo", :latitude => "-9.65", :longitude => "20.4").save
City.new(:country_id => "9", :name => "Lucapa", :aliases => "Lucapa,Lukapa,ÐÑÐºÐ°Ð¿Ð°,Lucapa", :latitude => "-8.41667", :longitude => "20.75").save
City.new(:country_id => "9", :name => "Luau", :aliases => "Luao,Luau,Teixeira de Sousa,Teixera de Sousa,Texeira-de Susa,Vila Teixeira de Sousa,Vila Teixeira de Souza,Vila Teixera de Souza,Vila Texeira de Sousa,ÐÑÐ°Ñ,Luau", :latitude => "-10.7", :longitude => "22.23333").save
City.new(:country_id => "9", :name => "Uige", :aliases => "Carmona,Uige,Uije,Uizhe,UÃ­ge,Vila Marchel Carmona,Ð£Ð¸Ð¶Ðµ,UÃ­ge", :latitude => "-7.61667", :longitude => "15.05").save
City.new(:country_id => "9", :name => "Soio", :aliases => "Saint Antonio do Zaire,San Antonio,Santo Antoni,Santo Antonio do Zaire,Santo AntÃ³nio do Zaire,Santo-Antonio,Santo-AntÃ³nio,Sao Antonio,Sazaire,Soio,Soju,Soyo,SÃ£o AntÃ´nio,Ð¡Ð¾Ð¹Ñ,Soio", :latitude => "-6.1349", :longitude => "12.36894").save
City.new(:country_id => "9", :name => "N'zeto", :aliases => "Ambrisette,Ambrizete,Ambrizette,N'zeto,Nzeto,Nâzeto,ÐÐ·ÐµÑÐ¾,Nâzeto", :latitude => "-7.23333", :longitude => "12.86667").save
City.new(:country_id => "9", :name => "Mbanza Congo", :aliases => "Mbanza Congo,Mbanza Kongo,San Salvador,Sao Salvador,Sao Salvador do Congo,SÃ£o Salvador,SÃ£o Salvador do Congo,Mbanza Congo", :latitude => "-6.26703", :longitude => "14.2401").save
City.new(:country_id => "9", :name => "Malanje", :aliases => "Malandje,Malange,Malanje,Malanzhe,ÐÐ°Ð»Ð°Ð½Ð¶Ðµ,Malanje", :latitude => "-9.54472", :longitude => "16.34528").save
City.new(:country_id => "9", :name => "Luanda", :aliases => "Loanda,Louanta,Luanda,Sao Paolo de Loanda,Sao Paulo da Assuncao de Luanda,Sao Paulo de Loanda,Sao Paulo de Luanda,SÃ£o Paolo de Loanda,SÃ£o Paulo da AssunÃ§Ã£o de Luanda,SÃ£o Paulo de Loanda,SÃ£o Paulo de Luanda,luanda,luo an da,lwanda,ruanda,ÎÎ¿ÏÎ¬Î½ÏÎ±,ÐÑÐ°Ð½Ð´Ð°,×××× ××,ÙÙØ¢ÙØ¯Ø§,ááá³,ã«ã¢ã³ã,ç½å®è¾¾,ë£¨ìë¤,Luanda", :latitude => "-8.83833", :longitude => "13.23444").save
City.new(:country_id => "9", :name => "Caxito", :aliases => "Caxito,Kashito,Kaxito,ÐÐ°ÑÐ¸ÑÐ¾,Caxito", :latitude => "-8.58", :longitude => "13.66417").save
City.new(:country_id => "9", :name => "Cabinda", :aliases => "Cabinda,Kabinda,ÐÐ°Ð±Ð¸Ð½Ð´Ð°,Cabinda", :latitude => "-5.55", :longitude => "12.2").save
City.new(:country_id => "9", :name => "Sumbe", :aliases => "Angungescapolo,Ngunza,Nova Redonda,Nova Redondo,Novo Redondo,Sumbe,Ð¡ÑÐ¼Ð±Ðµ,Sumbe", :latitude => "-11.2", :longitude => "13.83333").save
City.new(:country_id => "9", :name => "Namibe", :aliases => "Mocamedes,Mossamedes,MoÃ§Ã¢medes,Namibe,ÐÐ°Ð¼Ð¸Ð±Ðµ,Namibe", :latitude => "-15.19611", :longitude => "12.15222").save
City.new(:country_id => "9", :name => "Menongue", :aliases => "Menonge,Serpa Pinto,Vila Serpa Pinto,ÐÐµÐ½Ð¾Ð½Ð³Ðµ,Menongue", :latitude => "-14.6585", :longitude => "17.69099").save
City.new(:country_id => "9", :name => "Luena", :aliases => "Luehna,Luena,Luene,Luso,Luzo,Vila Luso,Vila Luzo,Vila Luzu,Villa Luso,ÐÑÑÐ½Ð°,Luena", :latitude => "-11.78333", :longitude => "19.91667").save
City.new(:country_id => "9", :name => "Lubango", :aliases => "Lubango,Sa da Bandeira,SÃ¡ da Bandeira,ÐÑÐ±Ð°Ð½Ð³Ð¾,Lubango", :latitude => "-14.91667", :longitude => "13.5").save
City.new(:country_id => "9", :name => "Longonjo", :aliases => "Congonjo,Logonzhu,Longonjo,ÐÐ¾Ð³Ð¾Ð½Ð¶Ñ,Longonjo", :latitude => "-12.90667", :longitude => "15.25333").save
City.new(:country_id => "9", :name => "Lobito", :aliases => "Lobito,Lobitu,robito,ÐÐ¾Ð±Ð¸ÑÑ,ã­ãã,Lobito", :latitude => "-12.34806", :longitude => "13.54556").save
City.new(:country_id => "9", :name => "Kuito", :aliases => "Bie,Bihe,BihÃ©,BiÃ©,Kuito,Silva Porto,Vila Salva Porto,ÐÑÐ¸ÑÐ¾,Kuito", :latitude => "-12.38333", :longitude => "16.93333").save
City.new(:country_id => "9", :name => "Huambo", :aliases => "Huambo,Nova Lisboa,Uambo,Ð£Ð°Ð¼Ð±Ð¾,Huambo", :latitude => "-12.77611", :longitude => "15.73917").save
City.new(:country_id => "9", :name => "Catumbela", :aliases => "Asseiceira,Catumbela,Catumbella,Katumbela,ÐÐ°ÑÑÐ¼Ð±ÐµÐ»Ð°,Catumbela", :latitude => "-12.43139", :longitude => "13.54722").save
City.new(:country_id => "9", :name => "Catabola", :aliases => "Catabola,Katabola,Nova Sintra,ÐÐ°ÑÐ°Ð±Ð¾Ð»Ð°,Catabola", :latitude => "-12.15", :longitude => "17.28333").save
City.new(:country_id => "9", :name => "Camacupa", :aliases => "Camacupa,General Machado,General Machado Villa,General Mathado,Kamakupa,Machado,Vila General Machado,ÐÐ°Ð¼Ð°ÐºÑÐ¿Ð°,Camacupa", :latitude => "-12.01667", :longitude => "17.48333").save
City.new(:country_id => "9", :name => "Caluquembe", :aliases => "Caluquembe,Caluquembo,Caluquemo,Kalukembe,ÐÐ°Ð»ÑÐºÐµÐ¼Ð±Ðµ,Caluquembe", :latitude => "-13.78333", :longitude => "14.68333").save
City.new(:country_id => "9", :name => "Caala", :aliases => "Caala,Cahala,CaÃ¡la,Kaala,Kaale,Robert Williams,Roberto Williams,Vila Robert Williams,ÐÐ°Ð°Ð»Ðµ,CaÃ¡la", :latitude => "-12.8525", :longitude => "15.56056").save
City.new(:country_id => "9", :name => "Benguela", :aliases => "Bengela,Benguela,Benguella,Sao Felipe de Benguela,SÃ£o FÃ©lipe de Benguela,ben ji la,ÐÐµÐ½Ð³ÐµÐ»Ð°,æ¬åæ,Benguela", :latitude => "-12.57833", :longitude => "13.40722").save
