City.new(:country_id => "14", :name => "Wolfsberg", :aliases => "Wolfsberg,Wolfsberg", :latitude => "46.84056", :longitude => "14.84417").save
City.new(:country_id => "14", :name => "Wiener Neustadt", :aliases => "Becsujvaros,BÃ©csÃºjvÃ¡ros,Dunajsko Novo mesto,Viedenske Nove Mesto,ViedenskÃ© NovÃ© Mesto,Viner-Nojshtadt,Viner-Nojstadt,Wiener Neustadt,Wr. Neustadt,wynr nwystt,ÐÐ¸Ð½ÐµÑ-ÐÐ¾Ð¹ÑÑÐ°Ð´Ñ,ÐÑÐ½ÐµÑ-ÐÐ¾Ð¹ÑÑÐ°Ð´Ñ,××× ×¨ × ×××©××,ã¦ã£ã¼ãã¼ã»ãã¤ã·ã¥ã¿ãã,Wiener Neustadt", :latitude => "47.8", :longitude => "16.25").save
City.new(:country_id => "14", :name => "Vienna", :aliases => "Bec,Bech,Becs,BeÄ,Bienne,BÃ©cs,Dunaj,Vena,Viden,Viena,Vienna,Vienne,Vieno,Vin,Vinarborg,Vindobona,Viyana,VÃ­deÅ,VÃ­n,VÃ­narborg,Wenen,Wieden,WiedeÅ,Wien,bin,weiynna,ÎÎ¹Î­Î½Î½Î·,ÐÐµÑ,ÐÐµÐ½Ð°,ÐÐ¸ÐµÐ½Ð°,à¹à¸§à¸µà¸¢à¸à¸à¸²,áªá¨á,ë¹,Vienna", :latitude => "48.20849", :longitude => "16.37208").save
City.new(:country_id => "14", :name => "Wels", :aliases => "Ovilava,Vel's,Wels,wls,ÐÐµÐ»ÑÑ,×××¡,Wels", :latitude => "48.16667", :longitude => "14.03333").save
City.new(:country_id => "14", :name => "Weinzierl bei Krems", :aliases => "Weinzierl,Weinzierl bei Krems,Weinzierl bei Krems", :latitude => "48.4", :longitude => "15.6").save
City.new(:country_id => "14", :name => "Villach", :aliases => "Beljak,Fillakh,Villach,Villaco,firahha,pylk,Ð¤Ð¸Ð»Ð»Ð°Ñ,×¤×××,ãã£ã©ãã,Villach", :latitude => "46.61028", :longitude => "13.85583").save
City.new(:country_id => "14", :name => "Traun", :aliases => ",Traun", :latitude => "48.22107", :longitude => "14.23777").save
City.new(:country_id => "14", :name => "Traiskirchen", :aliases => ",Traiskirchen", :latitude => "48.01485", :longitude => "16.29324").save
City.new(:country_id => "14", :name => "Ternitz", :aliases => ",Ternitz", :latitude => "47.71565", :longitude => "16.03575").save
City.new(:country_id => "14", :name => "Steyr", :aliases => "Shtajr,Steyer,Steyr,Steyr Stadt,ashtayr,styyr,Ð¨ÑÐ°Ð¹Ñ,×©××××¨,Ø§Ø´ØªØ§ÛØ±,Steyr", :latitude => "48.04274", :longitude => "14.42127").save
City.new(:country_id => "14", :name => "Spittal an der Drau", :aliases => "Shpittal',Spital,Spittal,Spittal an der Drau,Ð¨Ð¿Ð¸ÑÑÐ°Ð»Ñ,Spittal an der Drau", :latitude => "46.8", :longitude => "13.5").save
City.new(:country_id => "14", :name => "Schwechat", :aliases => "Nova Schwechat,Schwechat,Shvekhat,Ð¨Ð²ÐµÑÐ°Ñ,Schwechat", :latitude => "48.13333", :longitude => "16.46667").save
City.new(:country_id => "14", :name => "Sankt Polten", :aliases => "Poelten,PÃ¶lten,Sankt Poelten,Sankt Polten,Sankt Polton,Sankt PÃ¶lten,Sankt PÃ¶lton,Sankt-Pjol'ten,St. Poeitn,St. Poelten,St. PÃ¶itn,St. PÃ¶lten,sheng pa er teng,snqt pltn,Ð¡Ð°Ð½ÐºÑ-ÐÑÐ»ÑÑÐµÐ½,×¡× ×§× ×¤×××,ã¶ã³ã¯ãã»ãã«ãã³,èå¸ç¾æ»,Sankt PÃ¶lten", :latitude => "48.2", :longitude => "15.63333").save
City.new(:country_id => "14", :name => "Salzburg", :aliases => "Lungsod ng Salzburg,Saizburg,Salcburk,Salisburgium,Salisburgo,Salisburgu,Salisburgum,Saltsmpournk,Salzborg,Salzbourg,Salzburg,Salzburgi liidumaa,Salzburgo,Salzbursko,SÃ¥izburg,Zal'cburg,Zalcburg,Zalcburga,Zalcburgas,jalcheubuleukeu,sa er ci bao,sa er si bao,salzbwrg,zarutsuburuku,zlzbwrg,Î£Î¬Î»ÏÏÎ¼ÏÎ¿ÏÏÎ³Îº,ÐÐ°Ð»ÑÐ±ÑÑÐ³,ÐÐ°Ð»ÑÑÐ±ÑÑÐ³,×××¦×××¨×,Ø³Ø§ÙØ²Ø¨ÙØ±Ú¯,ã¶ã«ããã«ã¯,è¨å°æ¯å ¡,è¨å°è¨å ¡,è©ç¾æ¯å ¡,ìì¸ ë¶ë¥´í¬,Salzburg", :latitude => "47.79941", :longitude => "13.04399").save
City.new(:country_id => "14", :name => "Saalfelden am Steinernen Meer", :aliases => "Saalfelden,Saalfelden am Steinernen Meer,Salfelden,Zal'fel'den-am-Shtajnernen-Meer,ÐÐ°Ð»ÑÑÐµÐ»ÑÐ´ÐµÐ½-Ð°Ð¼-Ð¨ÑÐ°Ð¹Ð½ÐµÑÐ½ÐµÐ½-ÐÐµÐµÑ,Saalfelden am Steinernen Meer", :latitude => "47.42681", :longitude => "12.848").save
City.new(:country_id => "14", :name => "Modling", :aliases => "Mjodling,Moedling,MÃ¶dling,mdlyng,ÐÑÐ´Ð»Ð¸Ð½Ð³,××××× ×,MÃ¶dling", :latitude => "48.08605", :longitude => "16.28921").save
City.new(:country_id => "14", :name => "Lustenau", :aliases => "Lustenau,ÐÑÑÑÐµÐ½Ð°Ñ,×××¡×× ××,Lustenau", :latitude => "47.42642", :longitude => "9.65851").save
City.new(:country_id => "14", :name => "Linz", :aliases => "Lentia,Linc,Linca,Lincas,Linec,Linz,lin ci,lyntz,lynz,rintsu,ÐÐ¸Ð½Ñ,××× ×¥,ÙÛÙØªØ²,ãªã³ã,æè¨,Linz", :latitude => "48.30639", :longitude => "14.28611").save
City.new(:country_id => "14", :name => "Leonding", :aliases => "Leonding,ÐÐµÐ¾Ð½Ð´Ð¸Ð½Ð³,×××× ××× ×,Leonding", :latitude => "48.27965", :longitude => "14.24901").save
City.new(:country_id => "14", :name => "Leoben", :aliases => "Leoben,ÐÐµÐ¾Ð±ÐµÐ½,×××××,Leoben", :latitude => "47.38333", :longitude => "15.1").save
City.new(:country_id => "14", :name => "Kufstein", :aliases => "Kuffstein,Kufshtajn,Kufsstein,Kufstein,ÐÑÑÑÑÐ°Ð¹Ð½,Kufstein", :latitude => "47.58333", :longitude => "12.16667").save
City.new(:country_id => "14", :name => "Krems an der Donau", :aliases => "Krems,Krems an der Donau,Krems-na-Dunae,qrms,ÐÑÐµÐ¼Ñ-Ð½Ð°-ÐÑÐ½Ð°Ðµ,×§×¨××¡,Krems an der Donau", :latitude => "48.40921", :longitude => "15.61415").save
City.new(:country_id => "14", :name => "Klosterneuburg", :aliases => "Klosterneuberg,Klosterneuburg,Klosternojburg,ÐÐ»Ð¾ÑÑÐµÑÐ½Ð¾Ð¹Ð±ÑÑÐ³,Klosterneuburg", :latitude => "48.30521", :longitude => "16.32522").save
City.new(:country_id => "14", :name => "Klagenfurt am Woerthersee", :aliases => "Celovec,Clagenfurtum,Klagenfurt,Klagenfurte,KlÄgenfurte,ke la gen fu,kuragenfuruto,qlgnpwrt,ÐÐ»Ð°Ð³ÐµÐ½ÑÑÑÑ,×§××× ×¤××¨×,ã¯ã©ã¼ã²ã³ãã«ã,åææ ¹ç¦,Klagenfurt am WÃ¶rthersee", :latitude => "46.62472", :longitude => "14.30528").save
City.new(:country_id => "14", :name => "Kapfenberg", :aliases => ",Kapfenberg", :latitude => "47.44458", :longitude => "15.29331").save
City.new(:country_id => "14", :name => "Innsbruck", :aliases => "Innsbruck,Insbruk,Insbruka,Pons Aeni,insuburukku,yin si bu lu ke,Ä°nnsbruck,ÐÐ½ÑÐ±ÑÑÐº,××× ×¡××¨××§,ã¤ã³ã¹ãã«ãã¯,å æ¯å¸é²å,Innsbruck", :latitude => "47.26266", :longitude => "11.39454").save
City.new(:country_id => "14", :name => "Hallein", :aliases => "Hallein,Khallajn,Ð¥Ð°Ð»Ð»Ð°Ð¹Ð½,××××××,Hallein", :latitude => "47.68333", :longitude => "13.1").save
City.new(:country_id => "14", :name => "Graz", :aliases => "Grac,Graca,Gradec,Graecia,Gratz,Graz,GrÃ¡z,GrÄca,Styrsky Hradec,ge la ci,ghrats,grats,gratsi,guratsu,Å tÃ½rskÃ½ Hradec,ÐÑÐ°Ñ,××¨××¥,ØºØ±Ø§ØªØ³,Ú¯Ø±Ø§ØªØ³,áá ááªá,ã°ã©ã¼ã,æ ¼æè¨,Graz", :latitude => "47.06667", :longitude => "15.45").save
City.new(:country_id => "14", :name => "Feldkirch", :aliases => "Fel'dkirkh,Feldkirch,pldqyrk,Ð¤ÐµÐ»ÑÐ´ÐºÐ¸ÑÑ,×¤×××§××¨×,Feldkirch", :latitude => "47.23306", :longitude => "9.6").save
City.new(:country_id => "14", :name => "Dornbirn", :aliases => "Dornbirn,dwrnbyrn,ÐÐ¾ÑÐ½Ð±Ð¸ÑÐ½,×××¨× ×××¨×,Dornbirn", :latitude => "47.41667", :longitude => "9.73306").save
City.new(:country_id => "14", :name => "Bregenz", :aliases => "Bregenc,Bregencja,Bregenz,Brigantium,brgnz,buregentsu,ÐÑÐµÐ³ÐµÐ½Ñ,××¨×× ×¥,ãã¬ã²ã³ã,Bregenz", :latitude => "47.50311", :longitude => "9.7471").save
City.new(:country_id => "14", :name => "Braunau am Inn", :aliases => "Braunau,Braunau am Inn,Braunau na In,Braunau na Innu,Braunau na Inu,Braunau-na-Inne,yin he pan bu lao nao,ÐÑÐ°ÑÐ½Ð°Ñ Ð½Ð° ÐÐ½,ÐÑÐ°ÑÐ½Ð°Ñ Ð½Ð° ÐÐ½Ñ,ÐÑÐ°ÑÐ½Ð°Ñ-Ð½Ð°-ÐÐ½Ð½Ðµ,××¨××× ×× ×× ×××,××¨××× ××-×× ×××,ãã©ã¦ãã¦ã»ã¢ã ã»ã¤ã³,å æ²³çå¸å³ç,Braunau am Inn", :latitude => "48.26667", :longitude => "13.03333").save
City.new(:country_id => "14", :name => "Baden", :aliases => "Baden,Baden bei Wien,ÐÐ°Ð´ÐµÐ½,××××,ãã¼ãã³ã»ãã¤ã»ã´ã£ã¼ã³,Baden", :latitude => "48.00543", :longitude => "16.23264").save
City.new(:country_id => "14", :name => "Amstetten", :aliases => ",Amstetten", :latitude => "48.1229", :longitude => "14.87206").save
City.new(:country_id => "14", :name => "Linz-Wels-Steyr", :aliases => ",Linz-Wels-Steyr", :latitude => "48.15458", :longitude => "14.18369").save
