City.new(:country_id => "18", :name => "", :aliases => "Chankaendi,ChankÃ¤ndi,Hankendi,Khankendy,Stepanakert,XankÉndi,astpanakrt,stpnqrt,Ð¡ÑÐµÐ¿Ð°Ð½Ð°ÐºÐµÑÑ,×¡××¤× ×§×¨×,Ø§Ø³ØªÙ¾Ø§ÙØ§Ú©Ø±Øª,XankÇndi", :latitude => "39.8299", :longitude => "46.7597").save
City.new(:country_id => "18", :name => "Tel'mankend", :aliases => ",Telâmankend", :latitude => "39.89056", :longitude => "48.38583").save
City.new(:country_id => "18", :name => "Shushi", :aliases => "Shoushi,Shusha,Shushe,Shushi,Susa,Susi,Szusza,shwshy,swsh,ÅuÅa,Ð¨ÑÑÐ°,ÕÕ¸ÖÕ·Õ¥,ÕÕ¸ÖÕ·Õ«,×©××©×,Ø´ÙØ´Û,Shushi", :latitude => "39.75639", :longitude => "46.75111").save
City.new(:country_id => "18", :name => "Salyan", :aliases => "Sal'jan,Sal'yany,Salian,Salyan,Salâyany,Ssaljany,Ð¡Ð°Ð»ÑÑÐ½,Salyan", :latitude => "39.595", :longitude => "48.97917").save
City.new(:country_id => "18", :name => "Neftcala", :aliases => "Neftcala,Neftechala,NeftÃ§ala,Nephte Chala,Poselok Tresta,ÐÐµÑÑÐµÑÐ°Ð»Ð°,NeftÃ§ala", :latitude => "39.35861", :longitude => "49.24694").save
City.new(:country_id => "18", :name => "Naxcivan", :aliases => "Nachitschewan,Nakhchyvan,Nakhicevan,Nakhichevan',Nakhichevanâ,Nakhjavan,Naxcivan,NaxÃ§Ä±van,ÐÐ°ÑÐ¸ÑÐµÐ²Ð°Ð½Ñ,NaxÃ§Ä±van", :latitude => "39.20889", :longitude => "45.41222").save
City.new(:country_id => "18", :name => "", :aliases => "Lankaran,Lencoran,Lenkoran',LÃ¤nkÃ¤ran,ÐÐµÐ½ÐºÐ¾ÑÐ°Ð½Ñ,LÇnkÇran", :latitude => "38.72262", :longitude => "48.81466").save
City.new(:country_id => "18", :name => "Imisli", :aliases => "Emishti,Imishli,Imishly,Imisli,Ä°miÅli,ÐÐ¼Ð¸ÑÐ»Ð¸,Ä°miÅli", :latitude => "39.86972", :longitude => "48.06").save
City.new(:country_id => "18", :name => "Dzhalilabad", :aliases => "Astrahanka,Astrakhan-Bazar,Astrakhanka,Calilabad,CÉlilabad,Dzhalilabad,Jalilabad,JÃ¤lilabad,Dzhalilabad", :latitude => "39.20889", :longitude => "48.49722").save
City.new(:country_id => "18", :name => "Pushkino", :aliases => "Bilasuvar,BilÉsuvar,Pushkin,Pushkino,Pushkino", :latitude => "39.45833", :longitude => "48.545").save
City.new(:country_id => "18", :name => "Astara", :aliases => "Astara,Azerbaydzhanskaya Astara,ÐÑÑÐ°ÑÐ°,Astara", :latitude => "38.45611", :longitude => "48.87861").save
City.new(:country_id => "18", :name => "Zubovka", :aliases => "Ali Bairamly,Ali Bayramli,Ali-Bairamli,Ali-Bajramly,Ali-Bayramli,Ali-Bayramly,Aly-Bayramly,Arab Shakhverdi,Arab-Shakhberdy,Arab-Shakhverdy,Sirvan,Zubovka,Åirvan,Æli BayramlÄ±,ÐÐ»Ð¸-ÐÐ°Ð¹ÑÐ°Ð¼Ð»Ñ,Zubovka", :latitude => "39.93194", :longitude => "48.92028").save
City.new(:country_id => "18", :name => "Agdam", :aliases => "Agdam,Aghdam,AÄdam,ÐÐ³Ð´Ð°Ð¼,Ô±Õ²Õ¤Õ¡Õ´,AÄdam", :latitude => "39.99306", :longitude => "46.93056").save
City.new(:country_id => "18", :name => "Zaqatala", :aliases => "Sakataly,ZAKATALY,Zakatali,Zakatalsk,Zakataly,Zaqatala,ÐÐÐÐÐ¢ÐÐÐ«,Zaqatala", :latitude => "41.63361", :longitude => "46.64333").save
City.new(:country_id => "18", :name => "Zabrat", :aliases => "Sabrat,ZABRAT,Zabrat,ÐÐÐÐ ÐÐ¢,Zabrat", :latitude => "40.48722", :longitude => "49.9525").save
City.new(:country_id => "18", :name => "Yevlax", :aliases => "Avlakh,EVLAKH,Jewlach,Yevlakh,Yevlax,ÐÐÐÐÐ¥,Yevlax", :latitude => "40.61273", :longitude => "47.14233").save
City.new(:country_id => "18", :name => "Xanlar", :aliases => "Elenendorf,Gjojgjol',Khanlar,Kol-Yelendorf,Xanlar,Yelenendorf,ÐÑÐ¹Ð³ÑÐ»Ñ,Ð¥Ð°Ð½Ð»Ð°Ñ,Xanlar", :latitude => "40.58694", :longitude => "46.31583").save
City.new(:country_id => "18", :name => "Xacmaz", :aliases => "Chatschmas,KHACHMAS,Kegna Khachmas,Kekhna-Khachmaz,Khachmas,Khachmaz,KÃ«gna Khachmas,Xacmaz,XaÃ§maz,Ð¥ÐÐ§ÐÐÐ¡,XaÃ§maz", :latitude => "41.47083", :longitude => "48.80972").save
City.new(:country_id => "18", :name => "Ucar", :aliases => "UDZHARY,Ucar,Udshary,Udzhar,Udzhara,Udzhary,Ujar,Ð£ÐÐÐÐ Ð«,Ucar", :latitude => "40.51833", :longitude => "47.65417").save
City.new(:country_id => "18", :name => "Terter", :aliases => "Mir Bashir,Mirbashir,MirbÃ¤shir,TERTER,Tartar,Terter,TÇrtÇr,TÉrtÉr,Ð¢ÐÐ Ð¢ÐÐ ,ÕÕ«Ö Ô²Õ¡Õ·Õ«Ö,Terter", :latitude => "40.345", :longitude => "46.92889").save
City.new(:country_id => "18", :name => "Sumqayit", :aliases => "SUMGAIT,Sumgait,Sumgjajet,Sumqayit,Sumqayyt,SumqayÄ±t,Ð¡Ð£ÐÐÐÐÐ¢,Ð¡ÑÐ¼Ð³Ð°Ð¸Ñ,×¡××××××,SumqayÄ±t", :latitude => "40.58972", :longitude => "49.66861").save
City.new(:country_id => "18", :name => "Qaracuxur", :aliases => "GARACHUKHUR,Garachukhur,Imeni Kaganovicha,Kaganovich,Kaganovicha,Karachekhur,Karachukhur,Poselok Imeni Kaganovicha,PosÃ«lok Imeni Kaganovicha,Qaracuxur,QaraÃ§uxur,Serebovski,Serebrovskiy,ÐÐÐ ÐÐ§Ð£Ð¥Ð£Ð ,QaraÃ§uxur", :latitude => "40.39667", :longitude => "49.97361").save
City.new(:country_id => "18", :name => "Shamkhor", :aliases => "Anino,Annenfel'd,Annenfelâd,Annino,SHAMKIR,Samkir,Shamkhor,ÅÇmkir,ÅÉmkir,Ð¨ÐÐÐÐÐ ,Shamkhor", :latitude => "40.82972", :longitude => "46.01889").save
City.new(:country_id => "18", :name => "Samaxi", :aliases => "SHEMAKHA,Samaxi,Schemacha,Shamakhy,Shemakha,ÅamaxÄ±,Ð¨ÐÐÐÐ¥Ð,ÅamaxÄ±", :latitude => "40.63028", :longitude => "48.64139").save
City.new(:country_id => "18", :name => "Sheki", :aliases => "Nucha,Nukha,Nuxa,SHEKI,Saki,Shaki,Sheki,ShÃ¤ki,ÅÇki,ÅÉki,Ð¨ÐÐÐ,Sheki", :latitude => "41.19194", :longitude => "47.17056").save
City.new(:country_id => "18", :name => "Sabuncu", :aliases => "SABUNCHI,Sabunchi,Sabunchy,Sabuncu,SabunÃ§u,Ð¡ÐÐÐ£ÐÐ§Ð,SabunÃ§u", :latitude => "40.4425", :longitude => "49.94806").save
City.new(:country_id => "18", :name => "Sabirabad", :aliases => "Petropavlovka,Petropavlovskoye,SABIRABAD,Sabirabad,Ssabirabad,Ð¡ÐÐÐÐ ÐÐÐÐ,Sabirabad", :latitude => "40.01278", :longitude => "48.47889").save
City.new(:country_id => "18", :name => "Qusar", :aliases => "KUSARY,Kusary,Qusar,ÐÐ£Ð¡ÐÐ Ð«,Qusar", :latitude => "41.42639", :longitude => "48.43556").save
City.new(:country_id => "18", :name => "Quba", :aliases => "KUBA,Kuba,Kuwa,Quba,ÐÐ£ÐÐ,Quba", :latitude => "41.35972", :longitude => "48.5125").save
City.new(:country_id => "18", :name => "Aja Kabul", :aliases => "Adshikabul,Adzha-Kabul,Adzhikabul,Aja Kabul,Kasi-Mahomed,Kazi Mahomed,Kazi-Magomed,Kazi-Magomet,Qazimammad,QazÄ±mÇmmÇd,QazÄ±mÉmmÉd,ÐÐ°Ð·Ð¸-ÐÐ°Ð³Ð¾Ð¼ÐµÐ´,Aja Kabul", :latitude => "40.04333", :longitude => "48.93556").save
City.new(:country_id => "18", :name => "Qazax", :aliases => "Agkeynak,AgkÃ«ynak,KAZAKH,Kasach,Kasachisee,Kazakh,Qazakh,Qazax,ÐÐÐÐÐ¥,Qazax", :latitude => "41.09333", :longitude => "45.36611").save
City.new(:country_id => "18", :name => "Haci Zeynalabdin", :aliases => "Haci Zeynalabdin,HacÄ± Zeynalabdin,Nasoslu,Nasosnaya,Nasosnyy,Nassosny,HacÄ± Zeynalabdin", :latitude => "40.62333", :longitude => "49.55861").save
City.new(:country_id => "18", :name => "Mingelchaur", :aliases => "MINGECHAUR,Mengechaur,Min'nkatsebir,Mingacevir,Mingachevir,Mingaecevir,Mingechaur,Mingechaurges,Mingeczaur,Mingelchaur,MingÃ¤chevir,MingÃ¤Ã§evir,MingÇÃ§evir,MingÉÃ§evir,ming gai qia wu er,ÎÎ¹Î½Î³ÎºÎ±ÏÏÎµÎ²Î¯Ï,ÐÐÐÐÐÐ§ÐÐ£Ð ,ÐÐ¸Ð½Ð³ÐµÑÐ°ÑÑ,æçæ°ä¹å°,Mingelchaur", :latitude => "40.76395", :longitude => "47.05953").save
City.new(:country_id => "18", :name => "Mastaga", :aliases => "MASHTAGA,Mashtaga,Mashtaghy,Mashtagi,Mastaga,MaÅtaÄa,ÐÐÐ¨Ð¢ÐÐÐ,MaÅtaÄa", :latitude => "40.53278", :longitude => "50.00389").save
City.new(:country_id => "18", :name => "Mardakyany", :aliases => "MARDAKJAN,Mardakan,Mardakjan,Mardakyan,Mardakyany,MÇrdÇkan,MÉrdÉkan,ÐÐÐ ÐÐÐÐ¯Ð,Mardakyany", :latitude => "40.49222", :longitude => "50.13889").save
City.new(:country_id => "18", :name => "Lokbatan", :aliases => "LOKBATAN,Loekbatan,Lokbatan,LÃ¶kbatan,ÐÐÐÐÐÐ¢ÐÐ,LÃ¶kbatan", :latitude => "40.32722", :longitude => "49.73").save
City.new(:country_id => "18", :name => "Geoktschai", :aliases => "GEOKCHAJ,Gekchai,Geokchai,Geokchay,Geoktschai,Goeycay,Goycay,Goychay,GÃ¶ychay,GÃ¶yÃ§ay,ÐÐÐÐÐ§ÐÐ,Geoktschai", :latitude => "40.65306", :longitude => "47.74056").save
City.new(:country_id => "18", :name => "Hovsan", :aliases => "GOVSAN,Gousan,Gousany,Goussan,Govsan,Hoevsan,Hovsan,HÃ¶vsan,ÐÐÐÐ¡ÐÐ,HÃ¶vsan", :latitude => "40.37444", :longitude => "50.08528").save
City.new(:country_id => "18", :name => "Kirowabad", :aliases => "Elisavetpol,Elizavetpol',Elizavetpolâ,GJANDZHA,Gaencae,Gaendzjae,Ganca,Gandja,Gandza,Gandzha,Gandzhe,GandÅ¼a,Ganga,Ganja,GanÄa,Gence,Gendzakh,Gjandzha,Gyandzha,GÃ¤ncÃ¤,GÃ¤ndzjÃ¤,GÇncÇ,GÉncÉ,Kirovabad,Kirowabad,Yelizavetpol',Yelizavetpolâ,ganja,gnjh,gyanja,ÐÐ¯ÐÐÐÐ,ÐÑÐ½Ð´Ð¶Ð°,Ú¯ÙØ¬Ù,áááá¯á,ã®ã£ã³ã¸ã£,ê°ì,Kirowabad", :latitude => "40.68278", :longitude => "46.36056").save
City.new(:country_id => "18", :name => "Buzovna", :aliases => "BUZOVNA,Busovny,Busowny,Buzouvna,Buzovna,Buzovny,ÐÐ£ÐÐÐÐÐ,Buzovna", :latitude => "40.51611", :longitude => "50.11639").save
City.new(:country_id => "18", :name => "Biny Selo", :aliases => "BINA,Bina,Bina Staraya,Biny Selo,BinÇ,BinÉ,ÐÐÐÐ,Biny Selo", :latitude => "40.45389", :longitude => "50.07639").save
City.new(:country_id => "18", :name => "Barda", :aliases => "BARDA,Barda,BÃ¤rdÃ¤,BÇrdÇ,BÉrdÉ,ÐÐÐ ÐÐ,Barda", :latitude => "40.37444", :longitude => "47.12667").save
City.new(:country_id => "18", :name => "Baladzhary", :aliases => "Baku-Baladshary,Baladjary,Baladzhary,Bilacari,BilÉcÉri,Baladzhary", :latitude => "40.43139", :longitude => "49.80806").save
City.new(:country_id => "18", :name => "Baku", :aliases => "Bacu,Baki,Bako,Bakoe,Bakou,Baku,Baku - Baki,Bakue,Bakuu,Baky,BakÃ³,BakÃº,BakÃº - BakÄ±,BakÃ¼,BakÄ±,Boku,Mpakou,ba ku,bako,baku,bakw,ÎÏÎ±ÎºÎ¿Ï,ÐÐ°ÐºÑ,ÐÐ¾ÐºÑ,×××§×,Ø¨Ø§ÙÙ,Ø¨Ø§Ú©Ù,ááá¥á,á£á©,ãã¯ã¼,å·´åº,ë°ì¿ ,Baku", :latitude => "40.37767", :longitude => "49.89201").save
City.new(:country_id => "18", :name => "Amirdzhan", :aliases => "Amirabdzhan,Amiradzhan,Amiradzhany,Amircan,Amirdzhan,Æmircan,Amirdzhan", :latitude => "40.42639", :longitude => "49.98361").save
City.new(:country_id => "18", :name => "Agsu", :aliases => "AKHSU,Aghsu,Agsu,Akhsu,Aksu,AÄsu,ÐÐ¥Ð¡Ð£,AÄsu", :latitude => "40.56917", :longitude => "48.40083").save
City.new(:country_id => "18", :name => "Agdas", :aliases => "AGDASH,Agdas,Agdasch,Agdash,Aghdash,Akdash,AÄdaÅ,ÐÐÐÐÐ¨,AÄdaÅ", :latitude => "40.65", :longitude => "47.47611").save
City.new(:country_id => "18", :name => "Agdzhabedy", :aliases => "AGDZHABEDI,Agcabadi,Agdzhabedi,Agdzhabedy,Aghjabadi,AghjabÃ¤di,AÄcabÇdi,AÄcabÉdi,ÐÐÐÐÐÐÐÐÐ,Agdzhabedy", :latitude => "40.05278", :longitude => "47.46139").save
City.new(:country_id => "18", :name => "Bakixanov", :aliases => "Bakikhanov,Bakikhanova,Bakixanov,BakÄ±xanov,ÐÐ°ÐºÐ¸ÑÐ°Ð½Ð¾Ð²Ð°,BakÄ±xanov", :latitude => "40.42167", :longitude => "49.96444").save
