City.new(:country_id => "19", :name => "Zenica", :aliases => "Zenica,ÐÐµÐ½Ð¸ÑÐ°,Zenica", :latitude => "44.20139", :longitude => "17.90639").save
City.new(:country_id => "19", :name => "Visoko", :aliases => "Visokas,Visoko,bisoko,ÐÐ¸ÑÐ¾ÐºÐ¾,ãã½ã³,Visoko", :latitude => "43.98889", :longitude => "18.17806").save
City.new(:country_id => "19", :name => "Velika Kladusa", :aliases => "Velika Kladusa,Velika Kladusha,Velika KladuÅ¡a,ÐÐµÐ»Ð¸ÐºÐ° ÐÐ»Ð°Ð´ÑÑÐ°,Velika KladuÅ¡a", :latitude => "45.18944", :longitude => "15.81167").save
City.new(:country_id => "19", :name => "Tuzla", :aliases => "Donja Tuzla,Soli,Tuzla,Ð¢ÑÐ·Ð»Ð°,Tuzla", :latitude => "44.54278", :longitude => "18.66944").save
City.new(:country_id => "19", :name => "Trebinje", :aliases => "Trebigne,Trebin'e,Trebine,Trebinje,Ð¢ÑÐµÐ±Ð¸Ð½ÑÐµ,Ð¢ÑÐµÐ±Ð¸ÑÐµ,Trebinje", :latitude => "42.71194", :longitude => "18.34417").save
City.new(:country_id => "19", :name => "Travnik", :aliases => "Traunik,Travnik,travnik,Ð¢ÑÐ°Ð²Ð½Ð¸Ðº,Ð¢ÑÐ°ÑÐ½ÑÐº,Travnik", :latitude => "44.22667", :longitude => "17.67056").save
City.new(:country_id => "19", :name => "Sarajevo", :aliases => "Bosna-Sarai,Saraeva,Saraevo,Saragebo,Saragiebo,Saragievo,Sarajeva,Sarajevas,Sarajevo,Sarajewo,Saraxevo - Sarajevo,Saraybosna,Szarajevo,SzarajevÃ³,Vrh Bosna,sai la ye fu,salayebo,saraebo,saraevo,sarayewo,srayyfw,Î£Î±ÏÎ¬Î³ÎµÎ²Î¿,Î£Î±ÏÎ¬Î³Î¹ÎµÎ²Î¿,Î£Î±ÏÎ±Î³Î¹ÎµÎ²Î¿,Ð¡Ð°ÑÐ°ÐµÐ²Ð°,Ð¡Ð°ÑÐ°ÐµÐ²Ð¾,Ð¡Ð°ÑÐ°ÑÐµÐ²Ð¾,ÕÕ¡ÖÕ¡ÖÕ¸,×¡×¨×××××,Ø³Ø±Ø§ÙÙÙÙ,à¸à¸²à¸£à¸²à¹à¸¢à¹à¸§,á¡áá áááá,á³á«á¬á®,ãµã©ã¨ã,å¡æè¶ä½,ì¬ë¼ìë³´,Sarajevo", :latitude => "43.84864", :longitude => "18.35644").save
City.new(:country_id => "19", :name => "Prijedor", :aliases => "Priedora,Prijedor,ÐÑÐ¸ÐµÐ´Ð¾ÑÐ°,ÐÑÐ¸ÑÐµÐ´Ð¾Ñ,Prijedor", :latitude => "44.98139", :longitude => "16.71306").save
City.new(:country_id => "19", :name => "Mostar", :aliases => "Mostar,Mostara,mosutaru,ÐÐ¾ÑÑÐ°Ñ,×××¡×××¨,ã¢ã¹ã¿ã«,Mostar", :latitude => "43.34333", :longitude => "17.80806").save
City.new(:country_id => "19", :name => "Gradacac", :aliases => ",GradaÄac", :latitude => "44.88083", :longitude => "18.42694").save
City.new(:country_id => "19", :name => "Gracanica", :aliases => ",GraÄanica", :latitude => "44.70333", :longitude => "18.30972").save
City.new(:country_id => "19", :name => "Gorazde", :aliases => "Gorazde,Gorazhde,GoraÅ¾de,ÐÐ¾ÑÐ°Ð¶Ð´Ðµ,GoraÅ¾de", :latitude => "43.66694", :longitude => "18.97639").save
City.new(:country_id => "19", :name => "Doboj", :aliases => "Doboj,Doboj", :latitude => "44.73472", :longitude => "18.08778").save
City.new(:country_id => "19", :name => "Cazin", :aliases => "Cazin,Ð¦Ð°Ð·Ð¸Ð½,Cazin", :latitude => "44.96694", :longitude => "15.94306").save
City.new(:country_id => "19", :name => "Bugojno", :aliases => "Bugojne,Bugojno,ÐÑÐ³Ð¾Ð¹Ð½Ð¾,ÐÑÐ³Ð¾ÑÐ½Ð¾,Bugojno", :latitude => "44.05722", :longitude => "17.45083").save
City.new(:country_id => "19", :name => "Brcko", :aliases => "Brchko,ÐÑÑÐºÐ¾,BrÄko", :latitude => "44.87278", :longitude => "18.80833").save
City.new(:country_id => "19", :name => "Bosanska Krupa", :aliases => "Bosanska Krupa,Krupa,Krupa na Uni,ÐÐ¾ÑÐ°Ð½ÑÐºÐ° ÐÑÑÐ¿Ð°,Bosanska Krupa", :latitude => "44.8825", :longitude => "16.15139").save
City.new(:country_id => "19", :name => "Bijeljina", :aliases => "Beline,Bieline,Bijelina,Bijeljina,blnh,byylynh,ÐÐ¸ÐµÐ»Ð¸Ð½Ðµ,ÐÐ¸ÑÐµÑÐ¸Ð½Ð°,×××××× ×,Ø¨ÙÙÙ,Bijeljina", :latitude => "44.75694", :longitude => "19.21611").save
City.new(:country_id => "19", :name => "Bihac", :aliases => "Bihac,BihaÃ§,BihaÄ,Bikhach,ÐÐ¸ÑÐ°Ñ,ÐÐ¸ÑÐ°Ñ,BihaÄ", :latitude => "44.81694", :longitude => "15.87083").save
City.new(:country_id => "19", :name => "Banja Luka", :aliases => "Bana Luka,Bania Louka,Bania Luka,Banialuca,Banja Luka,Banja Luka - Bana Luka,Banja Luka - ÐÐ°ÑÐ° ÐÑÐºÐ°,Banja-Luka,Banja-Lukae,Banjaluko,Banya Luka,ba ni ya lu ka,banja luka,banya lwka,banyaluka,bnya lwka,ÎÏÎ¬Î½Î¹Î± ÎÎ¿ÏÎºÎ±,ÐÐ°Ð½Ñ ÐÑÐºÐ°,ÐÐ°Ð½Ñ-ÐÑÐºÃ¦,ÐÐ°Ð½Ñ-ÐÑÐºÐ°,ÐÐ°ÑÐ° ÐÑÐºÐ°,××× ×× ×××§×,Ø¨Ø§ÙÛØ§ ÙÙÚ©Ø§,Ø¨ÙÙØ§ ÙÙÙØ§,à¤¬à¤à¤à¤¾ à¤²à¥à¤à¤¾,ããã£ã»ã«ã«,å·´å°¼äºå¢å¡,ë°ëë£¨ì¹´,Banja Luka", :latitude => "44.77583", :longitude => "17.18556").save
City.new(:country_id => "19", :name => "Konjic", :aliases => "Konjic,Konjic", :latitude => "43.65194", :longitude => "17.96139").save
