City.new(:country_id => "24", :name => "Yambol", :aliases => "Iambol,Jambol,Jamboli,Yambol,Yampolis,Ð¯Ð¼Ð±Ð¾Ð»,Yambol", :latitude => "42.48333", :longitude => "26.5").save
City.new(:country_id => "24", :name => "Vratsa", :aliases => "Vraca,Vratca,Vratsa,Vrattsa,Vratza,Wraza,ÐÑÐ°ÑÐ°,Vratsa", :latitude => "43.21", :longitude => "23.5625").save
City.new(:country_id => "24", :name => "Vidin", :aliases => "Vidin,Vidine,Widin,wydyn,ÐÐ¸Ð´Ð¸Ð½,ÙÛØ¯ÛÙ,Vidin", :latitude => "43.99", :longitude => "22.8725").save
City.new(:country_id => "24", :name => "Velingrad", :aliases => "Velingrad,ÐÐµÐ»Ð¸Ð½Ð³ÑÐ°Ð´,Velingrad", :latitude => "42.02724", :longitude => "23.99569").save
City.new(:country_id => "24", :name => "Veliko Turnovo", :aliases => "Tarnovo,Tarnowo,Ternovo,Tirnovo,Trnova,Trnovo,Turnovo,TÄrnovo,TÄrnowo,TÅ­rnovo,Veliko T'rnovo,Veliko Tarnovo,Veliko TÄrnovo,Weliko Tarnowo,Weliko Tyrnowo,vu~erikotarunovu~o,ÐÐµÐ»Ð¸ÐºÐ¾ Ð¢ÑÑÐ½Ð¾Ð²Ð¾,ã´ã§ãªã³ã¿ã«ãã´ã©,Veliko TÅ­rnovo", :latitude => "43.08124", :longitude => "25.62904").save
City.new(:country_id => "24", :name => "Varna", :aliases => "Barna,Odessos,Odessus,Stalin,Varna,Warna,farna,varna,vu~aruna,wa er na,wrnh,ÎÎ¬ÏÎ½Î±,ÐÐ°ÑÐ½Ð°,××¨× ×,ÙØ§Ø±ÙØ§,ááá áá,ã´ã¡ã«ã,ç¦ç¾ç´,Varna", :latitude => "43.21667", :longitude => "27.91667").save
City.new(:country_id => "24", :name => "Turgovishte", :aliases => "Eski Djoumaia,Eski DjoumaÃ¯a,Eski Dschumaja,Eski Dzhumaya,Eski Dzuma,Eski Dzumaja,Eski Dzumaya,Eski DÅ¾uma,Eski DÅ¾umaja,Targovishte,Targowischte,Trgovishte,Turgovishhe,Turgovishte,Turgoviste,TÄrgowischte,TÅ­rgovishte,TÅ­rgoviÅ¡te,Ð¢ÑÑÐ³Ð¾Ð²Ð¸ÑÐµ,TÅ­rgovishte", :latitude => "43.25917", :longitude => "26.58917").save
City.new(:country_id => "24", :name => "Troyan", :aliases => "Troian,Trojan,TroÃ¯an,Ð¢ÑÐ¾ÑÐ½,Troyan", :latitude => "42.89427", :longitude => "24.71589").save
City.new(:country_id => "24", :name => "Tonchevtsi", :aliases => "Tonchevci,Tonchovtsi,Ð¢Ð¾Ð½ÑÐµÐ²ÑÐ¸,Tonchevtsi", :latitude => "42.9", :longitude => "25.31667").save
City.new(:country_id => "24", :name => "Dobrich", :aliases => "Bazargic,Dobric,Dobrich,Dobricz,Dobritch,Dobritj,Dobrits,Dobritsch,Dobritsj,DobritÅ¡,DobriÄ,Hacioglu Pazarcik,HacÄ±oÄlu PazarcÄ±k,Hadzi-Oghlu-Pazardzik,HadÅ¾i-Oghlu-PazardÅ¾ik,Khadzhioglu Bazardzhik,Khadzhioglu Pazardzhik,Tolbuhin,Tolbukhin,dobeulichi,ÐÐ¾Ð±ÑÐ¸Ñ,ëë¸ë¦¬ì¹,Dobrich", :latitude => "43.56667", :longitude => "27.83333").save
City.new(:country_id => "24", :name => "Svishtov", :aliases => "Novae,Novensis Moesia Civitas,Sistov,Sistova,Staklen,Steklen,Sveyestov,Svisclov,Svishhov,Svishtov,Svislova,Svistov,SviÅ¡lova,SviÅ¡tov,Swischtow,Ð¡Ð²Ð¸ÑÐ¾Ð²,Svishtov", :latitude => "43.62306", :longitude => "25.35389").save
City.new(:country_id => "24", :name => "Svilengrad", :aliases => "Mustafa-Pasha,Mustafapasa,MustafapaÅa,Slivengrad,Svilen,Svilengrad,Svilengrade,Swilengrad,Ð¡Ð²Ð¸Ð»ÐµÐ½Ð³ÑÐ°Ð´,Svilengrad", :latitude => "41.76667", :longitude => "26.2").save
City.new(:country_id => "24", :name => "Stara Zagora", :aliases => "Eski Zagra,Eski ZaÄra,Stara Sagora,Stara Zagora,Stara-Zagora,Ð¡ÑÐ°ÑÐ° ÐÐ°Ð³Ð¾ÑÐ°,Ð¡ÑÐ°ÑÐ°-ÐÐ°Ð³Ð¾ÑÐ°,Stara Zagora", :latitude => "42.43278", :longitude => "25.64194").save
City.new(:country_id => "24", :name => "Dupnitsa", :aliases => "Doupnitza,Dubnica,Dupnica,Dupnitsa,Dupnitza,Dupniza,Marek,Stanke Dimitrov,Stanke Dimitrovo,ÐÑÐ¿Ð½Ð¸ÑÐ°,Dupnitsa", :latitude => "42.26667", :longitude => "23.11667").save
City.new(:country_id => "24", :name => "Sofia", :aliases => "Safia,Serdica,Sofia,Sofie,Sofija,Sofio,Sofiya,Sofja,Sofya,SofÃ­a,Sophia,Sredets,Szofia,SzÃ³fia,SÃ²fia,SÃ³fia,Ulpia Serdica,sofia,sopia,suo fei ya,swfya,swpyh,Î£ÏÏÎ¹Î±,Ð¡Ð°ÑÑÑ,Ð¡Ð¾ÑÐ¸Ñ,Ð¡Ð¾ÑÐ¸ÑÐ°,Ð¡Ð¾ÑÑÑ,×¡××¤××,Ø³ÙÙÙÙÛ,ØµÙÙÙØ§,á¡áá¤áá,á¶áá«,ã½ãã£ã¢,ç´¢è²äº,ìí¼ì,Sofia", :latitude => "42.69751", :longitude => "23.32415").save
City.new(:country_id => "24", :name => "Smolyan", :aliases => "Paschmaklii,Pashmakla,Pashmakli,PashmaklÄ,Pasmakli,Pasmakly,PaÅ¡makli,Smolian,Smoljan,Smolyan,Ð¡Ð¼Ð¾Ð»ÑÐ½,Smolyan", :latitude => "41.58528", :longitude => "24.69194").save
City.new(:country_id => "24", :name => "Sliven", :aliases => "Islimiye,Islimje,Sliven,Slivno,Sliwen,aslmyh,Ð¡Ð»Ð¸Ð²ÐµÐ½,Ø§Ø³ÙÙÛÙ,Sliven", :latitude => "42.68583", :longitude => "26.32917").save
City.new(:country_id => "24", :name => "Silistra", :aliases => "Silistra,Ð¡Ð¸Ð»Ð¸ÑÑÑÐ°,Silistra", :latitude => "44.11667", :longitude => "27.26667").save
City.new(:country_id => "24", :name => "Shumen", :aliases => "Choumen,ChoumÃ¨n,Kolarovgrad,Schumen,Shoumen,Shumen,Shumla,Sjumen,Sumen,Sumla,Sumnu,shumen,Åumnu,Å umen,Å umla,Ð¨ÑÐ¼ÐµÐ½,Shumen", :latitude => "43.27064", :longitude => "26.92286").save
City.new(:country_id => "24", :name => "Sevlievo", :aliases => "Savlievo,Seljvi,Selvi,Sevelijevo,Sevlievo,Sevlijevo,Sewliewo,Ð¡ÐµÐ²Ð»Ð¸ÐµÐ²Ð¾,Sevlievo", :latitude => "43.02583", :longitude => "25.11361").save
City.new(:country_id => "24", :name => "Sandanski", :aliases => "Sandanski,Sveti Vrac,Sveti Vrach,Sveti VraÄ,Sveti-Vratch,SvÃ©ti-Vratch,Sweti Wratsch,Xanne Sandanski,Yane Sandanski,Ð¡Ð°Ð½Ð´Ð°Ð½ÑÐºÐ¸,Ð¡Ð²ÐµÑÐ¸ ÐÑÐ°Ñ,Sandanski", :latitude => "41.56667", :longitude => "23.28333").save
City.new(:country_id => "24", :name => "Samokov", :aliases => "Samakov,Samokov,Samokow,Samovkov,Ð¡Ð°Ð¼Ð¾ÐºÐ¾Ð²,Samokov", :latitude => "42.33333", :longitude => "23.55").save
City.new(:country_id => "24", :name => "Ruse", :aliases => "Roese,Rousse,RoussÃ©,Roustchouk,Ruschuk,Ruschuq,Rusciuk,Rusclink,Ruscuk,Ruse,Rushchuk,Rushtuk,Russe,Rustschuk,RusÃ§uk,Ruzo,RuÅ¡Äuk,Saray-Makhle,Sexaginta Prista,lu sai,Ð ÑÑÐµ,é²å¡,Ruse", :latitude => "43.85639", :longitude => "25.97083").save
City.new(:country_id => "24", :name => "Razgrad", :aliases => "Rasgrad,Razgrad,Ð Ð°Ð·Ð³ÑÐ°Ð´,Razgrad", :latitude => "43.53333", :longitude => "26.51667").save
City.new(:country_id => "24", :name => "Rakovski", :aliases => "General Niklaevo,General Nikolaevo,General Nikolaewo,Kalich,Kaliclii,KaliÄh,KaliÄlii,Kaluchlii,Kaluchliy,KalÅ­chlii,KalÅ­chliy,Rakovski,Ð Ð°ÐºÐ¾Ð²ÑÐºÐ¸,Rakovski", :latitude => "42.3", :longitude => "24.96667").save
City.new(:country_id => "24", :name => "Popovo", :aliases => "Popkioj,Popkioy,PopkiÃ¶j,Popovo,ÐÐ¾Ð¿Ð¾Ð²Ð¾,Popovo", :latitude => "43.35", :longitude => "26.23333").save
City.new(:country_id => "24", :name => "Plovdiv", :aliases => "Eumolpias,Filiba,Filibe,Filipopol,Filippopol,Filippopoli,Flavia,Julia,Philippopel,Philippopoli,Philippopolis,Philippoupole,Pinople,Plodin,Ploudin,Plovdin,Plovdiv,Plovdiva,Plowdiw,PlÃ³vdiv,Poulpoudeva,PÅowdiw,Sinople,Trimontium,Ulpia,Vinipoppolis,blwfdyf,pu luo fu di fu,purovudifu,Î¦Î¹Î»Î¹ÏÏÎ¿ÏÏÎ¿Î»Î·,ÐÐ»Ð¾Ð²Ð´Ð¸Ð²,Ø¨ÙÙÙØ¯ÙÙ,áááááááá,ãã­ã´ãã£ã,æ®ç½å¤«è¿ªå¤«,Plovdiv", :latitude => "42.15", :longitude => "24.75").save
City.new(:country_id => "24", :name => "Pleven", :aliases => "Pleven,Plevna,Plevne,Plewen,Plyeven,purevu~en,ÐÐ»ÐµÐ²ÐµÐ½,ãã¬ã´ã§ã³,Pleven", :latitude => "43.41667", :longitude => "24.61667").save
City.new(:country_id => "24", :name => "Petrich", :aliases => "Petric,Petrich,Petritch,Petritsch,PetriÄ,ÐÐµÑÑÐ¸Ñ,Petrich", :latitude => "41.4", :longitude => "23.21667").save
City.new(:country_id => "24", :name => "Peshtera", :aliases => "Momarsko,Pechtera,Pescera,Peschtera,Peshchera,Peshhera,Peshtera,Pestera,PeÅ¡tera,PeÅ¡Äera,ÐÐµÑÐµÑÐ°,Peshtera", :latitude => "42.03333", :longitude => "24.3").save
City.new(:country_id => "24", :name => "Pernik", :aliases => "Dimitrovo,Pernik,ÐÐµÑÐ½Ð¸Ðº,Pernik", :latitude => "42.6", :longitude => "23.03333").save
City.new(:country_id => "24", :name => "Pazardzhik", :aliases => "Pasardschik,Pasardshik,Pazardjik,Pazardzhik,Pazardzik,Pazardzjik,PazardÅ¼ik,PazardÅ¾ik,Tatar Bazardzik,Tatar BazardÅ¾ik,Tatar Pazardjik,Tatar Pazardzhik,Tatar Pazardzik,Tatar PazardÅ¾ik,Tatar-Bazardzhik,ÐÐ°Ð·Ð°ÑÐ´Ð¶Ð¸Ðº,Pazardzhik", :latitude => "42.2", :longitude => "24.33333").save
City.new(:country_id => "24", :name => "Panagyurishte", :aliases => "Otalkioj,OtalkiÃ¶j,Panaghiourichte,PanaghiourichtÃ©,Panaghurichte,Panagiuriste,Panagjurisce,Panagjurischte,Panagjurishhe,Panagjuriste,PanagjuriÅ¡te,PanagjuriÅ¡Äe,Panagyurishche,Panagyurishte,ÐÐ°Ð½Ð°Ð³ÑÑÐ¸ÑÐµ,Panagyurishte", :latitude => "42.5", :longitude => "24.18333").save
City.new(:country_id => "24", :name => "Nova Zagora", :aliases => "Eni Zagra,Ienizagra,Jeni Saghra,Jeni Zagra,Nova Zagora,Nowa Sagora,Yeni Sagra,Yeni Zagra,ÐÐ¾Ð²Ð° ÐÐ°Ð³Ð¾ÑÐ°,Nova Zagora", :latitude => "42.48333", :longitude => "26.01667").save
City.new(:country_id => "24", :name => "Montana", :aliases => "Ferdinand,Ferdinandovo,Golyama Kutlovitsa,Khristo Mikhaylov,Kutlovica,Mikhailovgrad,Mikhaylovgrad,Montana,Velika Kutlovica,ÐÐ¾Ð½ÑÐ°Ð½Ð°,Montana", :latitude => "43.4125", :longitude => "23.225").save
City.new(:country_id => "24", :name => "Lovech", :aliases => "Lovca,Lovcha,Lovec,Lovech,Lovetch,LoveÄ,LovÄa,Lowetsch,ÐÐ¾Ð²ÐµÑ,Lovech", :latitude => "43.13333", :longitude => "24.71667").save
City.new(:country_id => "24", :name => "Lom", :aliases => "Aligina Makhala,Dzhembek Makhala,Kalen Potok,Lom,Lom Palanka,Nikolaevo,Nikolaewo,ÐÐ¾Ð¼,Lom", :latitude => "43.81389", :longitude => "23.23611").save
City.new(:country_id => "24", :name => "Kyustendil", :aliases => "Keustendil,Kioustendil,KioustÃ©ndil,Kjustendil,Koestendil,Kostendil,Kustendil,Kyoustentil,Kyustendil,KÃ¶stendil,KÃ¼stendil,ÎÏÎ¿ÏÏÏÎµÎ½ÏÎ¯Î»,ÐÑÑÑÐµÐ½Ð´Ð¸Ð»,Kyustendil", :latitude => "42.28389", :longitude => "22.69111").save
City.new(:country_id => "24", :name => "Kurdzhali", :aliases => "Exrdzhali,Kardjali,Kardschali,Kardshali,Kardzhali,Kerdzhali,Kerjali,Kircaali,Kirdjalu,KirdjalÃ¼,Kirdzali,Kirdzalu,KirdÅ¾ali,KirdÅ¾alÃ¼,Kirjali,Krdjali,Kudjaly,Kurdzali,Kurdzhale,Kurdzhali,Kurdzhalii,Kurdzjali,Kyakyrdzhali,Kyrdzhali,KÄrdzhali,KÄ±rcaali,KÅ­rdzhale,KÅ­rdzhali,KÅ­rdzhalii,KÅ­rdÅ¾ali,ÐÑÑÐ´Ð¶Ð°Ð»Ð¸,ÐÑÑÐ´Ð¶Ð°Ð»Ð¸,KÅ­rdzhali", :latitude => "41.65", :longitude => "25.36667").save
City.new(:country_id => "24", :name => "Khaskovo", :aliases => "Chaskoi,Chaskovo,Chaskowo,ChaskÃ¶i,Haskioj,HaskiÃ¶j,Haskovo,Haskoy,HaskÃ¶y,Khaskovo,Ð¥Ð°ÑÐºÐ¾Ð²Ð¾,Khaskovo", :latitude => "41.94028", :longitude => "25.56944").save
City.new(:country_id => "24", :name => "Kharmanli", :aliases => "Charmanlii,Harmanli,Harmanlii,Harmanlu,Harmanly,HarmanlÃ¼,Hermanli,Kharmanli,Kharmanlii,Kharmanliy,Ð¥Ð°ÑÐ¼Ð°Ð½Ð»Ð¸,Kharmanli", :latitude => "41.93333", :longitude => "25.9").save
City.new(:country_id => "24", :name => "Kazanluk", :aliases => "Kasanlak,KasanlÄk,Kazanl'k,Kazanlak,Kazanlako,Kazanlek,Kazanlik,Kazanlk,Kazanluk,Kazanlyk,KazanlÄk,KazanlÄ±k,KazanlÅ­k,KazanÅyk,ÐÐ°Ð·Ð°Ð½Ð»ÑÐº,ÐÐ°Ð·Ð°Ð½Ð»ÑÐº,×§×××× ×××§,KazanlÅ­k", :latitude => "42.61667", :longitude => "25.4").save
City.new(:country_id => "24", :name => "Karnobat", :aliases => "Karnabat,Karnobat,Karnobatski prokhod,Poljanovgrad,Polyanovgrad,ÐÐ°ÑÐ½Ð¾Ð±Ð°Ñ,ÐÐ°ÑÐ½Ð¾Ð±Ð°ÑÑÐºÐ¸ Ð¿ÑÐ¾ÑÐ¾Ð´,Karnobat", :latitude => "42.65", :longitude => "26.98333").save
City.new(:country_id => "24", :name => "Karlovo", :aliases => "Grad Karlove,Karliova,Karlovo,Karlowo,KarlÄ±ova,KarÅowo,Levskigrad,ÐÐ°ÑÐ»Ð¾Ð²Ð¾,Karlovo", :latitude => "42.63333", :longitude => "24.8").save
City.new(:country_id => "24", :name => "Gotse Delchev", :aliases => "Goce Delchev,Gotse Delchev,Gotsi Delchev,Gotze Deltchev,Nevrekop,Nevrokop,Newrokop,ÐÐ¾ÑÐµ ÐÐµÐ»ÑÐµÐ²,Gotse Delchev", :latitude => "41.56667", :longitude => "23.73333").save
City.new(:country_id => "24", :name => "Gorna Oryakhovitsa", :aliases => "Gorna Orehovica,Gorna Orehovitsa,Gorna Orehovitza,Gorna Orekhovitsa,Gorna Oriahovica,Gorna Orjakhovica,Gorna Orjechovica,Gorna Oryakhovitsa,Gorna OrÃ©hovitza,Gorna-Orechowiza,Gorna-Oryekhovitsa,Gorno Oryakhovitsa,ÐÐ¾ÑÐ½Ð° ÐÑÑÑÐ¾Ð²Ð¸ÑÐ°,Gorna Oryakhovitsa", :latitude => "43.12778", :longitude => "25.70167").save
City.new(:country_id => "24", :name => "Gabrovo", :aliases => "Gabrova,Gabrovo,Gabrowo,gabrovo,gaburobo,jia bu luo wo,ÐÐ°Ð±ÑÐ¾Ð²Ð¾,ã¬ãã­ã,å å¸ç¾æ²,Gabrovo", :latitude => "42.87472", :longitude => "25.33417").save
City.new(:country_id => "24", :name => "Dimitrovgrad", :aliases => "Dimitrovgrad,ÐÐ¸Ð¼Ð¸ÑÑÐ¾Ð²Ð³ÑÐ°Ð´,Dimitrovgrad", :latitude => "42.05", :longitude => "25.6").save
City.new(:country_id => "24", :name => "Chirpan", :aliases => "Chirpan,Cirpan,Tchirpan,Tschirpan,Äirpan,Ð§Ð¸ÑÐ¿Ð°Ð½,Chirpan", :latitude => "42.2", :longitude => "25.33333").save
City.new(:country_id => "24", :name => "Cherven Bryag", :aliases => "Cerven-Breg,Cherven brjag,Cherven-Breg,Cherven-Bryeg,Cherveni Bryag,Cherveni-Bjerg,Tcherven Bryag,Tscherwen Breg,Äerven-BrÄg,Ð§ÐµÑÐ²ÐµÐ½ Ð±ÑÑÐ³,Cherven Bryag", :latitude => "43.26667", :longitude => "24.1").save
City.new(:country_id => "24", :name => "Burgas", :aliases => "Boergas,Bourgas,Bournkas,Burgas,Burgasa,Burgaz,Burghaz,Mpournkas,bu er jia si,burugasu,ÎÏÎ¿ÏÏÎ³ÎºÎ¬Ï,ÎÏÎ¿ÏÏÎ³ÎºÎ±Ï,ÎÏÎ¿ÏÏÎ³ÎºÎ±Ï,ÐÑÑÐ³Ð°Ñ,ãã«ã¬ã¹,å¸ç¾å æ¯,Burgas", :latitude => "42.50606", :longitude => "27.46781").save
City.new(:country_id => "24", :name => "Botevgrad", :aliases => "Botevgrad,Botewgrad,Orchanie,Orhanie,Orhanje,Orkhanie,ÐÐ¾ÑÐµÐ²Ð³ÑÐ°Ð´,Botevgrad", :latitude => "42.9", :longitude => "23.78333").save
City.new(:country_id => "24", :name => "Blagoevgrad", :aliases => "Blagoevgrad,Djumaja,Dzhumaya,Dzuma,Dzumaja,DÅ¾uma,DÅ¾umaja,Gorna Djoumaia,Gorna Djumaya,Gorna Dshumaja,Gorna Dzhumaja,Gorna Dzhumaya,Gorna Dzumaja,Gorna DÅ¾umaja,ÐÐ»Ð°Ð³Ð¾ÐµÐ²Ð³ÑÐ°Ð´,ÐÐ¾ÑÐ½Ð° ÐÐ¶ÑÐ¼Ð°Ñ,Blagoevgrad", :latitude => "42.01667", :longitude => "23.1").save
City.new(:country_id => "24", :name => "Berkovitsa", :aliases => "Berkovica,Berkovitsa,Berkovitsay,Berkovitza,Berkowiza,ÐÐµÑÐºÐ¾Ð²Ð¸ÑÐ°,Berkovitsa", :latitude => "43.23611", :longitude => "23.12583").save
City.new(:country_id => "24", :name => "Aytos", :aliases => "Aitos,Ajtos,Aytos,ÐÐ¹ÑÐ¾Ñ,Aytos", :latitude => "42.7", :longitude => "27.25").save
City.new(:country_id => "24", :name => "Asenovgrad", :aliases => "Asenovgrad,Assenovgrad,Assenovgrade,Assenowgrad,Stanimaka,ÐÑÐµÐ½Ð¾Ð²Ð³ÑÐ°Ð´,Asenovgrad", :latitude => "42.01667", :longitude => "24.86667").save
