City.new(:country_id => "37", :name => "Zhodzina", :aliases => "Schodsina,ZHODINO,Zhodino,Zhodzina,Zodino,Zodzina,Å»odino,ÐÐÐÐÐÐ,ÐÐ¾Ð´Ð·iÐ½Ð°,ÐÐ¾Ð´Ð·ÑÐ½Ð°,ÐÐ¾Ð´Ð¸Ð½Ð¾,Zhodzina", :latitude => "54.09833", :longitude => "28.3325").save
City.new(:country_id => "37", :name => "Zhlobin", :aliases => "Korpilovka,Zhlobin,Zlobin,ÐÐ»Ð¾Ð±Ð¸Ð½,Zhlobin", :latitude => "52.89222", :longitude => "30.02806").save
City.new(:country_id => "37", :name => "Vitsyebsk", :aliases => "Vicebsk,Vicebska,Vicebszk,Viciebsk,Vitebsk,Vitebskas,Vitsebsk,Vitsyebsk,Witebsk,Wizebsk,bichebseukeu,vu~ichepusuku,wei jie bu si ke,wytbsq,ÐÐ¸ÑÐµÐ±ÑÐº,ÐÑÑÐµÐ±ÑÑÐº,ÐÑÑÐµÐ±ÑÐº,×××××¡×§,ã´ã£ãã§ãã¹ã¯,ç»´æ·å¸æ¯å,ë¹ì³ì¤í¬,Vitsyebsk", :latitude => "55.1925", :longitude => "30.19444").save
City.new(:country_id => "37", :name => "Vilyeyka", :aliases => "Vilejka,Vileyka,Vilyeyka,Wilejka,ÐÐ¸Ð»ÐµÐ¹ÐºÐ°,Vilyeyka", :latitude => "54.4975", :longitude => "26.92111").save
City.new(:country_id => "37", :name => "Vawkavysk", :aliases => "VOLKOVYSK,Vawkavysk,Volkovysk,Wolkowysk,WoÅkowysk,ÐÐÐÐÐÐÐ«Ð¡Ð,Vawkavysk", :latitude => "53.15194", :longitude => "24.45556").save
City.new(:country_id => "37", :name => "Svyetlahorsk", :aliases => "SVETLOGORSK,Shatilki,Shatsilki,Svetlogorsk,Svyetlahorsk,Ð¡ÐÐÐ¢ÐÐÐÐÐ Ð¡Ð,Svyetlahorsk", :latitude => "52.62917", :longitude => "29.73389").save
City.new(:country_id => "37", :name => "Stowbtsy", :aliases => "Stolbcy,Stolbtsy,Stolpce,Stolptse,Stolptsy,Stolpze,Stowbtsy,StoÅpce,Ð¡ÑÐ¾Ð»Ð±ÑÑ,Stowbtsy", :latitude => "53.47861", :longitude => "26.7475").save
City.new(:country_id => "37", :name => "Smarhon'", :aliases => "Smarhon',Smarhonâ,Smorgon',Smorgone,Smorgonie,Smorgonâ,Ð¡Ð¼Ð¾ÑÐ³Ð¾Ð½Ñ,Smarhonâ", :latitude => "54.48361", :longitude => "26.4").save
City.new(:country_id => "37", :name => "Slutsk", :aliases => "SLUCK,Slucak,Sluck,Sluckas,Slutsk,Sluzk,SÅuck,slwzq,Ð¡ÐÐ£Ð¦Ð,Ð¡Ð»ÑÑÐ°Ðº,Ð¡Ð»ÑÑÐº,×¡×××¦×§,Slutsk", :latitude => "53.02722", :longitude => "27.56194").save
City.new(:country_id => "37", :name => "Slonim", :aliases => "SLONIM,Slonim,Slonimas,SÅonim,seullonim,suronimu,Ð¡ÐÐÐÐÐ,Ð¡Ð»Ð¾Ð½Ð¸Ð¼,Ð¡Ð»Ð¾Ð½ÑÐ¼,ã¹ã­ãã ,ì¬ë¡ë,Slonim", :latitude => "53.08667", :longitude => "25.32194").save
City.new(:country_id => "37", :name => "Shchuchyn", :aliases => "Shchuchin,Shchuchyn,Shhuchin,Szczuczyn,Ð©ÑÑÐ¸Ð½,Shchuchyn", :latitude => "53.60972", :longitude => "24.73778").save
City.new(:country_id => "37", :name => "Salihorsk", :aliases => "Chizhevichi,SOLIGORSK,Saligorsk,Salihorsk,Salyhorsk,Soligorsk,Soligorskas,Ð¡ÐÐÐÐÐÐ Ð¡Ð,Ð¡Ð°Ð»ÑÐ³Ð¾ÑÑÐº,Ð¡Ð¾Ð»Ð¸Ð³Ð¾ÑÑÐº,Salihorsk", :latitude => "52.8", :longitude => "27.53333").save
City.new(:country_id => "37", :name => "Rahachow", :aliases => "Rahachow,Rogachev,Rogatschew,Ð Ð¾Ð³Ð°ÑÐµÐ²,Rahachow", :latitude => "53.085", :longitude => "30.05").save
City.new(:country_id => "37", :name => "Rechytsa", :aliases => "Rechica,Rechitsa,Rechysta,Rechytsa,Ryechitsa,Ð ÐµÑÐ¸ÑÐ°,Rechytsa", :latitude => "52.36389", :longitude => "30.39472").save
City.new(:country_id => "37", :name => "Pruzhany", :aliases => "PRUZHANY,Pruzana,Pruzhana,Pruzhany,ÐÐ Ð£ÐÐÐÐ«,ÐÑÑÐ¶Ð°Ð½Ñ,Pruzhany", :latitude => "52.55667", :longitude => "24.46444").save
City.new(:country_id => "37", :name => "Polatsk", :aliases => "POLOCK,Podolsk,Polacak,Polack,Polatsk,Polazk,Poloc'k,Polock,Polockas,Polotsk,Polozk,Potolsk,PoÅock,ÐÐÐÐÐ¦Ð,ÐÐ¾Ð»Ð°ÑÐ°Ðº,ÐÐ¾Ð»Ð¾ÑÐº,ÐÐ¾Ð»Ð¾ÑÑÐº,Polatsk", :latitude => "55.48556", :longitude => "28.80417").save
City.new(:country_id => "37", :name => "Pinsk", :aliases => "PINSK,Pinsk,Pinskas,PiÅsk,pinseukeu,pinsuku,pynsq,ÐÐÐÐ¡Ð,ÐÐ¸Ð½ÑÐº,ÐÑÐ½ÑÐº,ÐÑÐ½ÑÑÐº,×¤×× ×¡×§,ãã³ã¹ã¯,íì¤í¬,Pinsk", :latitude => "52.12139", :longitude => "26.07278").save
City.new(:country_id => "37", :name => "Pastavy", :aliases => "POSTAVY,Pastavy,Postavy,Postawy,ÐÐÐ¡Ð¢ÐÐÐ«,Pastavy", :latitude => "55.11676", :longitude => "26.83263").save
City.new(:country_id => "37", :name => "Asipovichy", :aliases => "Asipovichy,OSIPOVICHI,Osipovichi,Ospipovichi,Ossipowitschi,Sipovichi,ÐÐ¡ÐÐÐÐÐÐ§Ð,Asipovichy", :latitude => "53.29333", :longitude => "28.64222").save
City.new(:country_id => "37", :name => "Orsha", :aliases => "ORSHA,Orsa,Orscha,Orsha,Orsza,OrÅa,OrÅ¡a,Vorsja,ao er sha,boleusya,vu~orusha,ÐÐ Ð¨Ð,ÐÑÑÐ°,ã´ã©ã«ã·ã£,å¥¥å°æ²,ë³´ë¥´ì¤,Orsha", :latitude => "54.51528", :longitude => "30.40528").save
City.new(:country_id => "37", :name => "Navapolatsk", :aliases => "Navapolack,Navapolatsk,NavapÃ³latsk,Nawapolazk,Novopolock,Novopolockas,Novopolotsk,Nowopolock,NowopoÅock,Polotskiy,ÐÐ°Ð²Ð°Ð¿Ð¾Ð»Ð°ÑÐº,ÐÐ¾Ð²Ð¾Ð¿Ð¾Ð»Ð¾ÑÐº,Navapolatsk", :latitude => "55.53333", :longitude => "28.65").save
City.new(:country_id => "37", :name => "Navahrudak", :aliases => "NOVOGRUDOK,Naugardukas,Navagradak,Navahradak,Navahrudak,Nawahradak,Novogroudok,Novogrudek,Novogrudok,Nowogrodek,NowogrÃ³dek,nbhrdq,xin ge lu duo ke,ÐÐÐÐÐÐ Ð£ÐÐÐ,ÐÐ°Ð²Ð°Ð³ÑÐ°Ð´Ð°Ðº,ÐÐ¾Ð²Ð¾Ð³ÑÑÐ´Ð¾Ðº,× ×××¨××§,æ°æ ¼é²å¤å,Navahrudak", :latitude => "53.6", :longitude => "25.83333").save
City.new(:country_id => "37", :name => "Minsk", :aliases => "Mensk,Minsc,Minscum,Minsk,Minsk - Minsk,Minsk - ÐÑÐ½ÑÐº,Minska,Minskas,Minsko,Minszk,MiÅsk,Myensk,Myenyesk,ming si ke,ming si ke shi,minseukeu,minsuku,mynsk,mynsq,ÎÎ¹Î½ÏÎº,ÐÐµÐ½ÑÐº,ÐÐ¸Ð½ÑÐº,ÐÑÐ½ÑÑÐº,××× ×¡×§,ÙÙÙØ³Ù,ÙÛÙØ³Ú©,áááá¡áá,ãã³ã¹ã¯,ææ¯å,ææ¯åå¸,ë¯¼ì¤í¬,Minsk", :latitude => "53.9", :longitude => "27.56667").save
City.new(:country_id => "37", :name => "Mazyr", :aliases => "MOZYR',Masyr,Mazir,Mazyr,Mozir,Mozyr,Mozyr',Mozyrâ,ÐÐÐÐ«Ð Ð¬,ÐÐ°Ð·ÑÑ,ÐÐ¾Ð·Ð¸Ñ,ÐÐ¾Ð·ÑÑÑ,Mazyr", :latitude => "52.05", :longitude => "29.26667").save
City.new(:country_id => "37", :name => "Masty", :aliases => "MOSTY,Masty,Mosty,ÐÐÐ¡Ð¢Ð«,Masty", :latitude => "53.40778", :longitude => "24.53278").save
City.new(:country_id => "37", :name => "Mar''ina Horka", :aliases => "Mar''ina Horka,Mar'ina Gorka,Maryina Gorka,Marâina Gorka,Marââina Horka,ÐÐ°ÑÑÐ¸Ð½Ð° ÐÐ¾ÑÐºÐ°,Marââina Horka", :latitude => "53.51667", :longitude => "28.15").save
City.new(:country_id => "37", :name => "Maladzyechna", :aliases => "Maladzyechna,Molodechno,Molodeczno,ÐÐ¾Ð»Ð¾Ð´ÐµÑÐ½Ð¾,Maladzyechna", :latitude => "54.31667", :longitude => "26.84972").save
City.new(:country_id => "37", :name => "Mahilyow", :aliases => "Magileu,Magileva,MagiÄ¼eva,Maguilov,Mahiliou,MahilioÅ­,Mahiljou,Mahiljov,Mahiljow,MahiljoÅ­,Mahilou,MahiloÅ­,Mahilyow,Mogil'ov,Mogilev,Mogilew,Mogiliavas,Mogiliovas,Mogiljov,Moguilev,Mohylew,ÐÐ°Ð³ÑÐ»ÑÑ,ÐÐ¾Ð³Ð¸Ð»ÐµÐ²,ÐÐ¾Ð³Ð¸Ð»ÑÐ¾Ð²,ÐÐ¾Ð³Ð¸Ð»ÑÐ²,ÐÐ¾Ð³Ð¸ÑÐµÐ²,Mahilyow", :latitude => "53.91389", :longitude => "30.33639").save
City.new(:country_id => "37", :name => "Lyepyel'", :aliases => "Lepel',Lepelâ,Lyepyel',Lyepyelâ,ÐÐµÐ¿ÐµÐ»Ñ,Lyepyelâ", :latitude => "54.88333", :longitude => "28.7").save
City.new(:country_id => "37", :name => "Luninyets", :aliases => "Luninec,Luninets,Luniniec,Luniniez,Luninyets,Åuniniec,ÐÑÐ½Ð¸Ð½ÐµÑ,ÐÑÐ½ÑÐ½ÐµÑ,Luninyets", :latitude => "52.25028", :longitude => "26.79944").save
City.new(:country_id => "37", :name => "Lida", :aliases => "LIDA,Lida,Lieda,Lyda,ÐÐÐÐ,ÐÐ¸Ð´Ð°,ÐÑÐ´Ð°,Lida", :latitude => "53.88333", :longitude => "25.29972").save
City.new(:country_id => "37", :name => "Krychaw", :aliases => "KRICHEV,Krichev,KrichÃ«v,Krychaw,Krytchev,ÐÐ ÐÐ§ÐÐ,Krychaw", :latitude => "53.69889", :longitude => "31.71417").save
City.new(:country_id => "37", :name => "Kobryn", :aliases => "KOBRIN,Kobrin,Kobryn,ÐÐÐÐ ÐÐ,ÐÐ¾Ð±ÑÑÐ½,Kobryn", :latitude => "52.21611", :longitude => "24.36639").save
City.new(:country_id => "37", :name => "Kalinkavichy", :aliases => "KALINKOVICHI,Kalinkavichy,Kalinkovichi,Kalinkowitschi,ÐÐÐÐÐÐÐÐÐÐ§Ð,Kalinkavichy", :latitude => "52.13333", :longitude => "29.32889").save
City.new(:country_id => "37", :name => "Ivatsevichy", :aliases => "Fol'vark Ivatseviche,Folâvark Ivatseviche,Ivacevichi,Ivantsevichi,Ivatsevichi,Ivatsevichy,Iwacewicze,Twacewicze,ÐÐ²Ð°ÑÑÐ²ÑÑÑ,ÐÐ²Ð°ÑÐµÐ²Ð¸ÑÐ¸,Ivatsevichy", :latitude => "52.70917", :longitude => "25.33889").save
City.new(:country_id => "37", :name => "Hrodna", :aliases => "GRODNO,Gardinas,Goradnia,Goradnja,Grodna,Grodno,Hrodna,furodona,hwrdnh,ÐÐ ÐÐÐÐ,ÐÐ¾ÑÐ°Ð´Ð½Ñ,ÐÑÐ¾Ð´Ð½Ð¾,×××¨×× ×,ãã­ãã,Hrodna", :latitude => "53.68139", :longitude => "23.81472").save
City.new(:country_id => "37", :name => "Horki", :aliases => "GORKI,Gorki,Horki,ÐÐÐ ÐÐ,Horki", :latitude => "54.28333", :longitude => "30.99111").save
City.new(:country_id => "37", :name => "Homyel'", :aliases => "GOMEL',Gomel,Gomel',Gomela,Gomelis,Gomelâ,GomeÄ¼a,Homel,Homiel,Homyel,Homyel',Homyelâ,homeri,homyel,hwml,ÐÐÐÐÐÐ¬,ÐÐ¾Ð¼ÐµÐ»,ÐÐ¾Ð¼ÐµÐ»Ñ,××××,ãã¡ãª,í¸ëª,Homyelâ", :latitude => "52.44167", :longitude => "30.98333").save
City.new(:country_id => "37", :name => "Hlybokaye", :aliases => "Glebokie,Glenboke,Glubokoe,Glubokoye,GlÄbokie,Hlybokaye,ÐÐ»ÑÐ±Ð¾ÐºÐ¾Ðµ,Hlybokaye", :latitude => "55.13333", :longitude => "27.68333").save
City.new(:country_id => "37", :name => "Dzyarzhynsk", :aliases => "DZERZHINSK,Dsjarschynsk,Dzerjinsk,Dzerzhinsk,Dzerzinskas,DzerÄµinsk,DzerÅ¾inskas,Dzierzynsk,DzierÅ¼ynsk,Dzjarzsinszk,Dzyarzhynsk,Kaiden,Kaydanovo,Kojdanau,Koydanava,Koydanovo,ÐÐÐÐ ÐÐÐÐ¡Ð,ÐÐ·ÐµÑÐ¶Ð¸Ð½ÑÐº,ÐÐ¾Ð¹Ð´Ð°Ð½Ð°Ñ,Dzyarzhynsk", :latitude => "53.685", :longitude => "27.14194").save
City.new(:country_id => "37", :name => "Dobrush", :aliases => "DOBRUSH,Dobrush,ÐÐÐÐ Ð£Ð¨,Dobrush", :latitude => "52.40944", :longitude => "31.32278").save
City.new(:country_id => "37", :name => "Bykhaw", :aliases => "BYKHOV,Bychow,Bykhaw,Bykhov,Star Bykhov,Staryy Bykhov,ÐÐ«Ð¥ÐÐ,Bykhaw", :latitude => "53.51833", :longitude => "30.24611").save
City.new(:country_id => "37", :name => "Byaroza", :aliases => "BEREZA,Bereza,Bereza Kartuska,Bereza-Kartuskaya,Bereza-Kartuzskaya,BerÃ«za,Byaroza,Kartuz-Bereza,ÐÐÐ ÐÐÐ,ÐÑÑÐ¾Ð·Ð°,Byaroza", :latitude => "52.53361", :longitude => "24.98389").save
City.new(:country_id => "37", :name => "Brest", :aliases => "BREST,Beras'ce,Berestja,Brest,Brest Litovsk,Brest-Litovsk,Brest-Litowsk,Brestas,Breszt,Brzesc,Brzesc nad Bugiem,Brzesc-Litewsk,Brzesc-Litewski,BrzeÅÄ,BrzeÅÄ nad Bugiem,BrzeÅÄ-Litewsk,BrzeÅÄ-Litewski,brst lytwbsq,bu lie si te,buresuto,ÐÐ ÐÐ¡Ð¢,ÐÐµÑÐ°ÑÑÑÐµ,ÐÐµÑÐµÑÑÑ,ÐÑÐµÑÑ,ÐÑÑÑÑ,××¨×¡× ××××××¡×§,ãã¬ã¹ã,å¸åæ¯ç¹,Brest", :latitude => "52.1", :longitude => "23.7").save
City.new(:country_id => "37", :name => "Barysaw", :aliases => "BORISOV,Barysaw,Borisov,Borissow,ÐÐÐ ÐÐ¡ÐÐ,Barysaw", :latitude => "54.22556", :longitude => "28.49139").save
City.new(:country_id => "37", :name => "Baranavichy", :aliases => "BARANOVICHI,Baranavichy,Baranavitsjy,Baranawitschy,Baranoviche,Baranovichi,Baranovichi - Baranavichy,Baranovichi - ÐÐ°ÑÐ°Ð½Ð°Ð²iÑÑ,Baranoviciai,Baranovitchi,Baranovitsi,BaranovitÅ¡i,BaranoviÄiai,Baranowicze,Baranowitschi,ÐÐÐ ÐÐÐÐÐÐ§Ð,ÐÐ°ÑÐ°Ð½Ð°Ð²ÑÑÑ,ÐÐ°ÑÐ°Ð½Ð¾Ð²Ð¸ÑÐ¸,Baranavichy", :latitude => "53.13333", :longitude => "26.03333").save
City.new(:country_id => "37", :name => "Babruysk", :aliases => "BOBRUJSK,Babroejsk,Babruisk,Babrujsk,Babruysk,Bobruisk,Bobruiskas,Bobrujsk,Bobruysk,bwbrwysq,ÐÐÐÐ Ð£ÐÐ¡Ð,ÐÐ°Ð±ÑÑÐ¹ÑÐº,ÐÐ¾Ð±ÑÑÐ¹ÑÐº,××××¨×××¡×§,Babruysk", :latitude => "53.15", :longitude => "29.23333").save
