City.new(:country_id => "56", :name => "Dvur Kralove nad Labem", :aliases => "Dvur Kralove,DvÅ­r KrÃ¡lovÃ©,Koniginhof an der Elbe,KÃ¶niginhof an der Elbe,DvÅ¯r KrÃ¡lovÃ© nad Labem", :latitude => "50.43172", :longitude => "15.81402").save
City.new(:country_id => "56", :name => "Znojmo", :aliases => "Znaim,Znain,Znaym,Znoimium,Znojmo,ÐÐ½Ð¾Ð¹Ð¼Ð¾,Znojmo", :latitude => "48.8555", :longitude => "16.0488").save
City.new(:country_id => "56", :name => "Zlin", :aliases => "Zlin,ZlÃ­n,ÎÎ»Î¹Î½,ÐÐ»Ð¸Ð½,ÐÑÐ»ÑÐ½,ZlÃ­n", :latitude => "49.22665", :longitude => "17.66633").save
City.new(:country_id => "56", :name => "Zlin", :aliases => "Gottvoldov,Gottwald,Gottwaldov,Zlin,ZlÃ­n,ÐÐ»Ð¸Ð½,ZlÃ­n", :latitude => "49.21667", :longitude => "17.66667").save
City.new(:country_id => "56", :name => "Zd'ar nad Sazavou Druhy", :aliases => "Saar Schloss,Zd'ar nad Sazavou Druhy,Å½ÄÃ¡r nad SÃ¡zavou Druhy,Å½ÄÃ¡r nad SÃ¡zavou Druhy", :latitude => "49.58726", :longitude => "15.93216").save
City.new(:country_id => "56", :name => "Zd'ar nad Sazavou", :aliases => "Mesto Zd'ar,Mesto Zd'ar a Zamek Zd'ar,MÄsto Å½Äar,MÄsto Å½ÄÃ¡r,MÄsto Å½ÄÃ¡r a ZÃ¡mek Å½ÄÃ¡r,Saar,Zd'ar,Å½ÄÃ¡r,Å½ÄÃ¡r nad SÃ¡zavou", :latitude => "49.56263", :longitude => "15.93924").save
City.new(:country_id => "56", :name => "Zatec", :aliases => "Saaz,Zatec,Zhatec,jatetsu,Å½atec,ÐÐ°ÑÐµÑ,ã¸ã£ãã,Å½atec", :latitude => "50.32717", :longitude => "13.54577").save
City.new(:country_id => "56", :name => "Vyskov", :aliases => "Vyshkov,Vyskov,VyÅ¡kov,Wischau,ÐÑÑÐºÐ¾Ð²,VyÅ¡kov", :latitude => "49.27747", :longitude => "16.99897").save
City.new(:country_id => "56", :name => "Vsetin", :aliases => "Vsetin,Wsetin,Wszetyn,ÐÑÐµÑÐ¸Ð½,VsetÃ­n", :latitude => "49.33871", :longitude => "17.99619").save
City.new(:country_id => "56", :name => "Varnsdorf", :aliases => "Warnsdorf,Varnsdorf", :latitude => "50.91154", :longitude => "14.61824").save
City.new(:country_id => "56", :name => "Valasske Mezirici", :aliases => "Mezirzhichi,Walachison Mesiritsch,Wallachisch Meseritsch,ÐÐµÐ·Ð¸ÑÐ¶Ð¸ÑÐ¸,ValaÅ¡skÃ© MeziÅÃ­ÄÃ­", :latitude => "49.47181", :longitude => "17.97113").save
City.new(:country_id => "56", :name => "Usti nad Orlici", :aliases => "Ustin Orl,Wildenschwert,Ãstin Orl,ÃstÃ­ nad OrlicÃ­", :latitude => "49.97387", :longitude => "16.39361").save
City.new(:country_id => "56", :name => "Usti nad Labem", :aliases => "Aussig,Aussig an der Elbe,Auszig,Usti,Usti nad Labem,Ustina Labe,usti,usti nad labom,Ãstina Labe,ÃstÃ­,ÃstÃ­ nad Labem,Ð£ÑÑÐ¸,Ð£ÑÑÐ¸ Ð½Ð°Ð´ ÐÐ°Ð±Ð¾Ð¼,ÃstÃ­ nad Labem", :latitude => "50.6607", :longitude => "14.03227").save
City.new(:country_id => "56", :name => "Uhersky Brod", :aliases => "Ungarisch Brod,Ungarisch-Brod,Vehersky Brod,UherskÃ½ Brod", :latitude => "49.02513", :longitude => "17.64715").save
City.new(:country_id => "56", :name => "Uherske Hradiste", :aliases => "Gradishte,Magyarhradis,Uherske Hradiste,UherskÃ© HradiÅ¡tÄ,Ungarisch Hradisch,Ungarisch-Hradisch,ÐÑÐ°Ð´Ð¸ÑÑÐµ,ã¦ãã«ã¹ã±ã¼ã»ãã©ã¸ã·ãã§,UherskÃ© HradiÅ¡tÄ", :latitude => "49.06975", :longitude => "17.45969").save
City.new(:country_id => "56", :name => "Trutnov", :aliases => "Trautenau,Trutnov,Ð¢ÑÑÑÐ½Ð¾Ð²,Trutnov", :latitude => "50.56101", :longitude => "15.9127").save
City.new(:country_id => "56", :name => "Trinec", :aliases => "Trshinec,Trzyniec,Ð¢ÑÑÐ¸Ð½ÐµÑ,TÅinec", :latitude => "49.67763", :longitude => "18.67078").save
City.new(:country_id => "56", :name => "Trebic", :aliases => "Trebic,Trebitsch,Trshebich,TÅebÃ­Ä,toshebichi,Ð¢ÑÑÐµÐ±Ð¸Ñ,ãã·ã§ãã¼ã,TÅebÃ­Ä", :latitude => "49.21492", :longitude => "15.88166").save
City.new(:country_id => "56", :name => "Teplice", :aliases => "Teplice,Teplice-Sanov,Teplice-Å anov,Teplitz,Teplitz-Schoenau,Teplitz-SchÃ¶nau,Ð¢ÐµÐ¿Ð»Ð¸ÑÐµ,Teplice", :latitude => "50.6404", :longitude => "13.82451").save
City.new(:country_id => "56", :name => "Tabor", :aliases => "Tabor,TÃ¡bor,tabor,taboru,Ð¢Ð°Ð±Ð¾Ñ,ã¿ã¼ãã«,TÃ¡bor", :latitude => "49.41441", :longitude => "14.6578").save
City.new(:country_id => "56", :name => "Svitavy", :aliases => "Svitave,Svitavy,Zwittau,Svitavy", :latitude => "49.75594", :longitude => "16.46829").save
City.new(:country_id => "56", :name => "Sumperk", :aliases => "Maehrisch-Schoenberg,MÃ¤hrisch-SchÃ¶nberg,Shumperk,Ð¨ÑÐ¼Ð¿ÐµÑÐº,Å umperk", :latitude => "49.96528", :longitude => "16.97061").save
City.new(:country_id => "56", :name => "Strakonice", :aliases => "Strakonice,Strakonitz,Ð¡ÑÑÐ°ÐºÐ¾Ð½Ð¸ÑÐµ,Strakonice", :latitude => "49.26141", :longitude => "13.90237").save
City.new(:country_id => "56", :name => "Stary Bohumin", :aliases => "Bogumin,Bohumin,BohumÃ­n,Oderberg,Stary Bohumin,StarÃ½ BohumÃ­n,StarÃ½ BohumÃ­n", :latitude => "49.9169", :longitude => "18.33619").save
City.new(:country_id => "56", :name => "Sokolov", :aliases => "Faiknov,Falkenau,Falkenau an der Eger,Falknov,Falknov nad Ohri,Falknov nad OhÅÃ­,Sokolov,Sokolov nad Ohri,Sokolov nad OhÅÃ­,sokollopeu,Ð¡Ð¾ÐºÐ¾Ð»Ð¾Ð²,ìì½ë¡í,Sokolov", :latitude => "50.1813", :longitude => "12.6401").save
City.new(:country_id => "56", :name => "Slany", :aliases => "Schlan,SlanÃ½", :latitude => "50.23046", :longitude => "14.08693").save
City.new(:country_id => "56", :name => "Roznov pod Radhostem", :aliases => "Roznau,Roznov,RoÅ¾nov,RoÅ¾nov pod RadhoÅ¡tÄm", :latitude => "49.45853", :longitude => "18.14302").save
City.new(:country_id => "56", :name => "Rakovnik", :aliases => "Rakonitz,RakovnÃ­k", :latitude => "50.1037", :longitude => "13.7334").save
City.new(:country_id => "56", :name => "Prostejov", :aliases => "Prosnitz,Prossnitz,Prostejov,ProstÄjov,Prosznitz,ÐÑÐ¾ÑÑÐµÐ¹Ð¾Ð²,ProstÄjov", :latitude => "49.47188", :longitude => "17.11184").save
City.new(:country_id => "56", :name => "Prosek", :aliases => ",Prosek", :latitude => "50.11667", :longitude => "14.5").save
City.new(:country_id => "56", :name => "Pribram", :aliases => "Pribram,Prshibram,Prsibram,PÅÃ­bram,ÐÑÑÐ¸Ð±ÑÐ°Ð¼,ÐÑÑÑÐ±ÑÐ°Ð¼,PÅÃ­bram", :latitude => "49.68988", :longitude => "14.01043").save
City.new(:country_id => "56", :name => "Prerov", :aliases => "Prerau,Prerov,PÅerov,ÐÑÐµÑÐ¾Ð²,PÅerov", :latitude => "49.45511", :longitude => "17.4509").save
City.new(:country_id => "56", :name => "Praha", :aliases => "%E3%83%97%E3%83%A9%E3%83%8F,Praag,Prag,Praga,Praga - Praha,Pragae,Prago,Prague,Praha,PrÃ g,PrÃ¡g,PrÃ¡ga,PrÃ¢g,PrÄga,bragh,bu la ge,peulaha,prag,praga,prak,prg,Î ÏÎ¬Î³Î±,ÐÑÐ°Ð³,ÐÑÐ°Ð³Ã¦,ÐÑÐ°Ð³Ð°,×¤×¨××,Ø¨Ø±Ø§Øº,Ù¾Ø±Ø§Ú¯,Ù¾Ø±Ø§Ú¯Ø§,Ü¦ÜªÜ,à¸à¸£à¸²à¸,à½à½´à¼à½£à¼à½à½º,áá áá¦á,áá«á,ãã©ã,å¸ææ ¼,íë¼í,Praha", :latitude => "50.08804", :longitude => "14.42076").save
City.new(:country_id => "56", :name => "Plzen", :aliases => "Pilsen,Pilsna,Pilzen,Pilzenas,Pilzno,Pl'zen',Plzen,Plzena,PlzeÅa,PlzeÅ,bylzn,peuljen,piruzen,Î Î¯Î»Î¶ÎµÎ½,Î Î¯Î»ÏÎµÎ½,ÐÐ¸Ð»Ð·ÐµÐ½,ÐÐ»Ð·ÐµÐ½,ÐÐ»Ð·ÐµÑ,ÐÐ»ÑÐ·ÐµÐ½Ñ,Ø¨ÙÙØ²Ù,ãã«ã¼ã³,íì  ,PlzeÅ", :latitude => "49.74747", :longitude => "13.37759").save
City.new(:country_id => "56", :name => "Pisek", :aliases => "Pisek,PÃ­sek,ÐÐ¸ÑÐµÐº,PÃ­sek", :latitude => "49.3088", :longitude => "14.1475").save
City.new(:country_id => "56", :name => "Pelhrimov", :aliases => "Pilgram,PelhÅimov", :latitude => "49.43134", :longitude => "15.22336").save
City.new(:country_id => "56", :name => "Pardubice", :aliases => "Pardubice,Pardubitz,Parntoumpitse,Î Î±ÏÎ½ÏÎ¿ÏÎ¼ÏÎ¯ÏÏÎµ,ÐÐ°ÑÐ´ÑÐ±Ð¸ÑÐµ,Pardubice", :latitude => "50.04075", :longitude => "15.77659").save
City.new(:country_id => "56", :name => "Otrokovice", :aliases => "Bahnak,BahÅÃ¡k,Otrokovice,Otrokovice-Kvitkovice,Otrokovice-KvÃ­tkovice,Otrokovice", :latitude => "49.21667", :longitude => "17.51667").save
City.new(:country_id => "56", :name => "Otrokovice", :aliases => "Kvitkovice,KvÃ­tkovice,Otrokovice", :latitude => "49.20934", :longitude => "17.53944").save
City.new(:country_id => "56", :name => "Ostrov", :aliases => "Ostrov nad Ohri,Ostrov nad OhÅÃ­,Schlackenwerth,Ostrov", :latitude => "50.30592", :longitude => "12.93907").save
City.new(:country_id => "56", :name => "Ostrava", :aliases => "Ostraba,Ostrava,Ostrawa,ao si te la wa,awstrafa,e si te la fa,oseuteulaba,osutoravu~a,ÎÏÏÏÎ¬Î²Î±,ÐÑÑÑÐ°Ð²Ð°,×××¡××¨××,Ø£ÙØ³ØªØ±Ø§ÙØ§,ãªã¹ãã©ã´ã¡,ä¿æ¯ç¹æç¼,å¥¥æ¯ç¹æç¦,ì¤ì¤í¸ë¼ë°,Ostrava", :latitude => "49.83465", :longitude => "18.28204").save
City.new(:country_id => "56", :name => "Orlova", :aliases => "Orlau,Orlova,Orlowa,OrÅowa,ÐÑÐ»Ð¾Ð²Ð°,OrlovÃ¡", :latitude => "49.84527", :longitude => "18.43011").save
City.new(:country_id => "56", :name => "Opava", :aliases => "Opava,Opawa,Oppavia,Troppau,ÐÐ¿Ð°Ð²Ð°,Opava", :latitude => "49.93866", :longitude => "17.90257").save
City.new(:country_id => "56", :name => "Olomouc", :aliases => "Olmuetz,OlmÃ¼tz,Olomouc,Olomouca,Olomoucas,Olomouch,Olomuc,Olomucium,Olomuniec,OÅomuniec,ao luo mu ke,awlwmwts,oromoutsu,ÐÐ»Ð¾Ð¼Ð¾ÑÑ,ÐÐ»Ð¾Ð¼ÑÑ,Ø£ÙÙÙÙÙØªØ³,ãªã­ã¢ã¦ã,å¥§æ´ç©å,Olomouc", :latitude => "49.59552", :longitude => "17.25175").save
City.new(:country_id => "56", :name => "Novy Jicin", :aliases => "Neutitschein,Novi-Jichin,Novy Jicin,NovÃ½ JiÄÃ­n,Nowy Jiczyn,xin yi qin,ÐÐ¾Ð²Ð¸-ÐÐ¸ÑÐ¸Ð½,æ°ä¼é¦,NovÃ½ JiÄÃ­n", :latitude => "49.59438", :longitude => "18.01028").save
City.new(:country_id => "56", :name => "Neratovice", :aliases => "Nerarovice,Neratowitz,Neratovice", :latitude => "50.25926", :longitude => "14.51759").save
City.new(:country_id => "56", :name => "Nachod", :aliases => ",NÃ¡chod", :latitude => "50.4167", :longitude => "16.16289").save
City.new(:country_id => "56", :name => "Most", :aliases => "Bruex,BrÃ¼x,Most,ÐÐ¾ÑÑ,Most", :latitude => "50.50301", :longitude => "13.63617").save
City.new(:country_id => "56", :name => "Modrany", :aliases => "Modran,Modrzhany,ModÅan,ÐÐ¾Ð´ÑÐ¶Ð°Ð½Ñ,ModÅany", :latitude => "50.01116", :longitude => "14.4096").save
City.new(:country_id => "56", :name => "Mlada Boleslav", :aliases => "Jungbunzlau,Mlada Boleslav,Mlada Boleslaz,Mlada-Boleslav,MladÃ¡ Boleslav,ÐÐ»Ð°Ð´Ð°-ÐÐ¾Ð»ÐµÑÐ»Ð°Ð²,MladÃ¡ Boleslav", :latitude => "50.41135", :longitude => "14.90318").save
City.new(:country_id => "56", :name => "Melnik", :aliases => "Mel'nik,Melnik,MÄlnÃ­k,mlnyk,ÐÐµÐ»ÑÐ½Ð¸Ðº,ÙÙÙÛÚ©,MÄlnÃ­k", :latitude => "50.3505", :longitude => "14.47411").save
City.new(:country_id => "56", :name => "Louny", :aliases => "Laun,Louny,Louny", :latitude => "50.35699", :longitude => "13.79667").save
City.new(:country_id => "56", :name => "Litvinov", :aliases => "Litvinov,LitvÃ­nov,Oberleutensdorf,ÐÐ¸ÑÐ²Ð¸Ð½Ð¾Ð²,LitvÃ­nov", :latitude => "50.6042", :longitude => "13.61812").save
City.new(:country_id => "56", :name => "Litomerice", :aliases => "Leitmeritz,Litomerice,Litomerzhice,LitomÄÅice,ÐÐ¸ÑÐ¾Ð¼ÐµÑÐ¶Ð¸ÑÐµ,LitomÄÅice", :latitude => "50.53348", :longitude => "14.1318").save
City.new(:country_id => "56", :name => "Liberec", :aliases => "Liberec,Liberecas,Reichenberg,lybyryts,ÐÐ¸Ð±ÐµÑÐµÑ,ÙÙØ¨ÙØ±ÙØªØ³,Liberec", :latitude => "50.76711", :longitude => "15.05619").save
City.new(:country_id => "56", :name => "Liben", :aliases => ",LibeÅ", :latitude => "50.10819", :longitude => "14.47457").save
City.new(:country_id => "56", :name => "Letnany", :aliases => "Letnan,LetÅan,LetÅany", :latitude => "50.13333", :longitude => "14.51667").save
City.new(:country_id => "56", :name => "Kutna Hora", :aliases => "Kutna Hora,Kutna-Gora,KutnÃ¡ Hora,Kuttenberg,gu te na huo la,ku te na huo la,kuteuna hola,ÐÑÑÐ½Ð°-ÐÐ¾ÑÐ°,å¤ç¹çº³éæ,åºç¹çº³éæ,ì¿ í¸ë í¸ë¼,KutnÃ¡ Hora", :latitude => "49.94839", :longitude => "15.26816").save
City.new(:country_id => "56", :name => "Kromeriz", :aliases => "Kremsier,Kromeriz,Kromerizas,KromeriÅ¾as,Kromnerzhizh,KromÄÅÃ­Å¾,ÐÑÐ¾Ð¼Ð½ÐµÑÐ¶Ð¸Ð¶,KromÄÅÃ­Å¾", :latitude => "49.29785", :longitude => "17.39312").save
City.new(:country_id => "56", :name => "Krnov", :aliases => "Jaegerndorf,JÃ¤gerndorf,Karniow,KarnÃ­ow,Krnov,ÐÑÐ½Ð¾Ð²,Krnov", :latitude => "50.08967", :longitude => "17.70385").save
City.new(:country_id => "56", :name => "Kralupy nad Vltavou", :aliases => "Kralup,Kralupy,Kralupy nad Vltavou", :latitude => "50.24107", :longitude => "14.31149").save
City.new(:country_id => "56", :name => "Koprivnice", :aliases => "Koprshivnicakh,Nesselsdorf,ÐÐ¾Ð¿ÑÑÐ¸Ð²Ð½Ð¸ÑÐ°Ñ,KopÅivnice", :latitude => "49.59947", :longitude => "18.1448").save
City.new(:country_id => "56", :name => "Kolin", :aliases => "Koeln an der Elbe,Kolin,KolÃ­n,KÃ¶ln an der Elbe,ÐÐ¾Ð»Ð¸Ð½,KolÃ­n", :latitude => "50.02814", :longitude => "15.20057").save
City.new(:country_id => "56", :name => "Klatovy", :aliases => "Klatovy,Klattau,ÐÐ»Ð°ÑÐ¾Ð²Ñ,Klatovy", :latitude => "49.39552", :longitude => "13.29505").save
City.new(:country_id => "56", :name => "Klasterec nad Ohri", :aliases => "Klosterle an der Eger,KlÃ¶sterle an der Eger,KlÃ¡Å¡terec nad OhÅÃ­", :latitude => "50.38445", :longitude => "13.17128").save
City.new(:country_id => "56", :name => "Kladno", :aliases => "Kladno,Klantno,ÎÎ»Î¬Î½ÏÎ½Î¿,ÐÐ»Ð°Ð´Ð½Ð¾,Kladno", :latitude => "50.14734", :longitude => "14.10285").save
City.new(:country_id => "56", :name => "Karvina", :aliases => "Freistadt,Frystat,Frysztat,FryÅ¡tÃ¡t,Karvina,Karvina 1,KarvinÃ¡ 1,ÐÐ°ÑÐ²Ð¸Ð½Ð°,KarvinÃ¡", :latitude => "49.854", :longitude => "18.54169").save
City.new(:country_id => "56", :name => "Karlovy Vary", :aliases => "Carlsbad,Karl Vary,Karloby Bary,Karlove Vari,Karlovi Varai,Karlovi Vari,Karlovy Vary,Karlsbad,kaleullobi bali,ÎÎ¬ÏÎ»Î¿Î²Ï ÎÎ¬ÏÏ,ÐÐ°ÑÐ»Ð¾Ð²Ðµ ÐÐ°ÑÐ¸,ÐÐ°ÑÐ»Ð¾Ð²Ð¸ ÐÐ°ÑÐ¸,ÐÐ°ÑÐ»Ð¾Ð²Ñ ÐÐ°ÑÑ,ÐÐ°ÑÐ»Ð¾Ð²Ñ ÐÐ°ÑÐ¸,×§×¨×××× ×××¨×,ã«ã«ã­ã´ã£ã»ã´ã¡ãª,ì¹´ë¥¼ë¡ë¹ ë°ë¦¬,Karlovy Vary", :latitude => "50.23271", :longitude => "12.87117").save
City.new(:country_id => "56", :name => "Kadan", :aliases => ",KadaÅ", :latitude => "50.38333", :longitude => "13.26667").save
City.new(:country_id => "56", :name => "Kadan", :aliases => "Kaaden,KadaÅ", :latitude => "50.37598", :longitude => "13.27131").save
City.new(:country_id => "56", :name => "Jirkov", :aliases => "Gorkau,GÃ¶rkau,Jirkov", :latitude => "50.49979", :longitude => "13.44769").save
City.new(:country_id => "56", :name => "Jindrichuv Hradec", :aliases => "Neuhaus,JindÅichÅ¯v Hradec", :latitude => "49.14404", :longitude => "15.00301").save
City.new(:country_id => "56", :name => "Jihlava", :aliases => "Iglau,Iglawa,IgÅawa,Jiglava,Jihlava,Jikhlava,ÐÐ¸ÑÐ»Ð°Ð²Ð°,ÐÐ¸Ð³Ð»Ð°Ð²Ð°,Jihlava", :latitude => "49.3961", :longitude => "15.59124").save
City.new(:country_id => "56", :name => "Jicin", :aliases => "Gitschin,Jichin,Jicin,Jitschin,JiÄÃ­n,Titschein,ÐÐ¸ÑÐ¸Ð½,JiÄÃ­n", :latitude => "50.43723", :longitude => "15.35162").save
City.new(:country_id => "56", :name => "Jablonec nad Nisou", :aliases => "Gablonz,Gablonz an der Neisse,Jablonec,Jablonec nad Nisou,Jablonec nad Nysa,Jablonec nad NysÄ,Jablonecas prie Nisos,yabeullonecheunateunisou,Ð¯Ð±Ð»Ð¾Ð½ÐµÑ,ì¼ë¸ë¡ë¤ì¸ ëí¸ëìì°,Jablonec nad Nisou", :latitude => "50.72431", :longitude => "15.17108").save
City.new(:country_id => "56", :name => "Hranice", :aliases => "Mahrisch Weisskirchen,MÃ¤hrisch Weisskirchen,Hranice", :latitude => "49.54796", :longitude => "17.73469").save
City.new(:country_id => "56", :name => "Hradec Kralove", :aliases => "Chrantek Kralobe,Gradec Kralove,Gradets Kralove,Hradec Kralove,Hradec KrÃ¡lovÃ©,Khradec Kralove,Koeniggraetz,KÃ¶niggrÃ¤tz,Î§ÏÎ¬Î½ÏÎµÎº ÎÏÎ¬Î»Î¿Î²Îµ,ÐÑÐ°Ð´ÐµÑ ÐÑÐ°Ð»Ð¾Ð²Ðµ,Ð¥ÑÐ°Ð´ÐµÑ ÐÑÐ°Ð»Ð¾Ð²Ðµ,Hradec KrÃ¡lovÃ©", :latitude => "50.20923", :longitude => "15.83277").save
City.new(:country_id => "56", :name => "Hodonin", :aliases => "Goding,Godonin,GÃ¶ding,Hodonin,HodonÃ­n,ÐÐ¾Ð´Ð¾Ð½Ð¸Ð½,HodonÃ­n", :latitude => "48.84893", :longitude => "17.13244").save
City.new(:country_id => "56", :name => "Havlickuv Brod", :aliases => "Deutsch Brod,Gavlichkuv-Brod,Havlickuv Brod,HavlÃ­ÄkÅ¯v Brod,Nemecky Brod,NÄmeckÃ½ Brod,ÐÐ°Ð²Ð»Ð¸ÑÐºÑÐ²-ÐÑÐ¾Ð´,HavlÃ­ÄkÅ¯v Brod", :latitude => "49.60785", :longitude => "15.58069").save
City.new(:country_id => "56", :name => "Havirov", :aliases => "Gavirsov,Gavirzhov,Havirov,HavÃ­Åov,Hawierzow,HawierzÃ³w,ÐÐ°Ð²Ð¸ÑÐ¶Ð¾Ð²,ÐÐ°Ð²ÑÑÑÐ¾Ð²,HavÃ­Åov", :latitude => "49.77984", :longitude => "18.43688").save
City.new(:country_id => "56", :name => "Frydek-Mistek", :aliases => "Friedeck,Friedek,Frydek,Frydek-Mistek,FrÃ½dek,FrÃ½dek-MÃ­stek,Mistek,ÐÐ¸ÑÑÐµÐº,FrÃ½dek-MÃ­stek", :latitude => "49.68333", :longitude => "18.35").save
City.new(:country_id => "56", :name => "Decin", :aliases => "Dechin,Decin,Decinas,DeÄinas,DÄÄÃ­n,Tetschen,ÐÐµÑÐ¸Ð½,DÄÄÃ­n", :latitude => "50.78215", :longitude => "14.21478").save
City.new(:country_id => "56", :name => "Chrudim", :aliases => ",Chrudim", :latitude => "49.95109", :longitude => "15.79558").save
City.new(:country_id => "56", :name => "Chomutov", :aliases => "Chomutov,Khomutov,Komotau,homutofu,Ð¥Ð¾Ð¼ÑÑÐ¾Ð²,ãã ãã,Chomutov", :latitude => "50.46048", :longitude => "13.41779").save
City.new(:country_id => "56", :name => "Cheb", :aliases => "Cheb,Chebas,Eger,Kheb,hepu,Ð¥ÐµÐ±,ãã,Cheb", :latitude => "50.07963", :longitude => "12.37392").save
City.new(:country_id => "56", :name => "Cesky Tesin", :aliases => "Ceski Tjesin,Cesky Tesin,Cheski-Teshin,Czeski Cieszyn,Teschen,Tesin,Tschechisch Teschen,ÄeskÃ½ TeÅ¡Ã­n,ÄeskÃ½ TÄÅ¡Ã­n,ÄeÅ¡ki TjeÅ¡in,Ð§ÐµÑÐºÐ¸-Ð¢ÐµÑÐ¸Ð½,ÄeskÃ½ TÄÅ¡Ã­n", :latitude => "49.74613", :longitude => "18.62613").save
City.new(:country_id => "56", :name => "Ceske Budejovice", :aliases => "Boehmisch Budweis,Budejovice,Budweis,BÃ¶hmisch Budweis,Ceske Budejovicai,Ceske Budejovice,Cheshke Budjejovice,Cheske Budejovice,Cheske-Budejovice,Czeskie Budziejowice,Tseske Mpountegiobitse,Äeske Budejovicai,ÄeskÃ© BudÄjovice,Î¤ÏÎ­ÏÎºÎµ ÎÏÎ¿ÏÎ½ÏÎµÎ³Î¹ÏÎ²Î¹ÏÏÎµ,Ð§ÐµÑÐºÐµ ÐÑÐ´ÐµÐ¹Ð¾Ð²Ð¸ÑÐµ,Ð§ÐµÑÐºÐµ-ÐÑÐ´ÐµÑÐ²Ð¸ÑÐµ,Ð§ÐµÑÐºÐµ ÐÑÐ´ÑÐµÑÐ¾Ð²Ð¸ÑÐµ,Ð§ÐµÑÐºÐµ ÐÑÑÐµÑÐ¾Ð²Ð¸ÑÐµ,ÄeskÃ© BudÄjovice", :latitude => "48.97447", :longitude => "14.47434").save
City.new(:country_id => "56", :name => "Ceska Trebova", :aliases => "Bohmisch-Trubau,BÃ¶hmisch-TrÃ¼bau,ÄeskÃ¡ TÅebovÃ¡", :latitude => "49.90436", :longitude => "16.44413").save
City.new(:country_id => "56", :name => "Ceska Lipa", :aliases => "Boehmisch-Leipa,BÃ¶hmisch-Leipa,Ceska Lipa,Cheska-Lipa,Lipa,ÄeskÃ¡ LÃ­pa,Ð§ÐµÑÐºÐ°-ÐÐ¸Ð¿Ð°,ÄeskÃ¡ LÃ­pa", :latitude => "50.68551", :longitude => "14.53764").save
City.new(:country_id => "56", :name => "Bruntal", :aliases => "Freudenthal,BruntÃ¡l", :latitude => "49.98844", :longitude => "17.4647").save
City.new(:country_id => "56", :name => "Brno", :aliases => "Berno,Brno,Bruenn,Bruna,Brunn,BrÃ¼nn,Burno,Mprno,beuleuno,brnw,bu er nuo,buruno,ÎÏÏÎ½Î¿,ÐÑÐ½Ð¾,ÐÑÑÐ½Ð¾,××¨× ×,Ø¨Ø±ÙÙ,ãã«ã,å¸ç¾è«¾,ë¸ë¥´ë¸,Brno", :latitude => "49.19522", :longitude => "16.60796").save
City.new(:country_id => "56", :name => "Breclav", :aliases => "Breclav,Brzheclav,BÅeclav,Lundenburg,bujetsurafu,ÐÑÐ¶ÐµÑÐ»Ð°Ð²,ãã¸ã§ãã©ã,BÅeclav", :latitude => "48.75897", :longitude => "16.88203").save
City.new(:country_id => "56", :name => "Branik", :aliases => ",BranÃ­k", :latitude => "50.03597", :longitude => "14.41235").save
City.new(:country_id => "56", :name => "Brandys nad Labem-Stara Boleslav", :aliases => ",BrandÃ½s nad Labem-StarÃ¡ Boleslav", :latitude => "50.18709", :longitude => "14.66326").save
City.new(:country_id => "56", :name => "Bohumin", :aliases => ",BohumÃ­n", :latitude => "49.90411", :longitude => "18.35755").save
City.new(:country_id => "56", :name => "Blansko", :aliases => "Blansko,ÐÐ»Ð°Ð½ÑÐºÐ¾,Blansko", :latitude => "49.36304", :longitude => "16.64446").save
City.new(:country_id => "56", :name => "Bilina Kyselka", :aliases => "Bilina Kyselka,BÃ­lina Kyselka,Sauerbrunn,BÃ­lina Kyselka", :latitude => "50.55", :longitude => "13.76667").save
City.new(:country_id => "56", :name => "Bilina", :aliases => "Bilin,BÃ­lina", :latitude => "50.54854", :longitude => "13.77535").save
City.new(:country_id => "56", :name => "Beroun", :aliases => "Beraun,Beroun", :latitude => "49.96382", :longitude => "14.072").save
City.new(:country_id => "56", :name => "Benesov", :aliases => "Beneschau,Benesov,BeneÅ¡ov,BeneÅ¡ov", :latitude => "49.78162", :longitude => "14.68697").save
City.new(:country_id => "56", :name => "Cerny Most", :aliases => ",ÄernÃ½ Most", :latitude => "50.10475", :longitude => "14.57974").save
