City.new(:country_id => "64", :name => "Viljandi", :aliases => "Felin,Fellin,VIL'JANDI,Vil'jandi,Vil'yandi,Vilande,Viljandi,Viljandis,Vilâyandi,Vylande,VylandÄ,Wiljandi,ÐÐÐÐ¬Ð¯ÐÐÐ,ÐÐ¸Ð»ÑÑÐ½Ð´Ð¸,×××××× ××,Viljandi", :latitude => "58.36389", :longitude => "25.59").save
City.new(:country_id => "64", :name => "Tartu", :aliases => "Derpt,Dorpat,TARTU,Tarbatum,Tartto,Tartu,Terbata,TÄrbata,Yur'yev,Yurev,taleutu,taruto~u,trtw,Ð¢ÐÐ Ð¢Ð£,Ð¢Ð°ÑÑÑ,××¨××,á¢áá á¢á£,ã¿ã«ãã¥,íë¥´í¬,Tartu", :latitude => "58.38062", :longitude => "26.72509").save
City.new(:country_id => "64", :name => "Tallinn", :aliases => "Castrum Danorum,Kallinn,Kolyvan,QUF,Raaveli,Reval,Revel',RÃ¤Ã¤veli,Talin,Talin - Tallinn,Talinas,Talino,Tallin,Tallina,Tallinn,Tallinna,TalÃ­n - Tallinn,TÃ llin,ta lin,tallin,talyn,tarin,thallin n,Î¤Î±Î»Î¯Î½,Î¤Î±Î»Î¹Î½,Î¤Î±Î»Î»Î¯Î½,Ð¢Ð°Ð»Ð¸Ð½,Ð¢Ð°Ð»Ð»Ð¸Ð½,Ð¢Ð°Ð»Ð»ÑÐ½,Ð¢Ð°Ð»ÑÐ½,ÕÕ¡Õ¬Õ¬Õ«Õ¶,×××××,ØªØ§ÙÙÙ,à¸à¸²à¸¥à¸¥à¸´à¸à¸à¹,á¢ááááá,á³áá,ã¿ãªã³,å¡æ,íë¦°,Tallinn", :latitude => "59.43696", :longitude => "24.75353").save
City.new(:country_id => "64", :name => "Sillamae", :aliases => "SILLAMJAEH,Silameje,SilamejÄ,Silamiaje,SilamiajÄ,Sillamae,Sillamaee,Sillamagi,Sillame,Sillamyae,SillamÃ¤e,SillamÄ,Suvilad,sillamjae,sillamjaeh,Ð¡ÐÐÐÐÐÐ¯Ð­,Ð¡Ð¸Ð»Ð»Ð°Ð¼ÑÐµ,Ð¡Ð¸Ð»Ð»Ð°Ð¼ÑÑ,SillamÃ¤e", :latitude => "59.39972", :longitude => "27.75472").save
City.new(:country_id => "64", :name => "Rakvere", :aliases => "RAKVERE,Rakvere,Rakvere_vald,Rakwere,Vezenberg,Wesenberg,Ð ÐÐÐÐÐ Ð,Rakvere", :latitude => "59.34639", :longitude => "26.35583").save
City.new(:country_id => "64", :name => "Parnu", :aliases => "PJARNU,Paernu,Parnawa,Parnu,Pernau,Pernava,Pernavia,Pernov,Piarnu,Pjarnu,Pyaonu,Pyarnu,PÃ¤rnu,PÄrnava,ÐÐ¯Ð ÐÐ£,ÐÑÑÐ½Ñ,áááá áá£,PÃ¤rnu", :latitude => "58.38588", :longitude => "24.49711").save
City.new(:country_id => "64", :name => "Narva", :aliases => "NARVA,Narva,Narwa,na er wa,narva,ÐÐÐ ÐÐ,ÐÐ°ÑÐ²Ð°,ááá áá,çº³å°ç¦,Narva", :latitude => "59.37722", :longitude => "28.19028").save
City.new(:country_id => "64", :name => "Maardu", :aliases => "Maardu,Mardu,MÄrdu,ÐÐ°Ð°ÑÐ´Ñ,Maardu", :latitude => "59.47667", :longitude => "25.025").save
City.new(:country_id => "64", :name => "Kohtla-Jarve", :aliases => "Jarve,KOKHTLA-JARVE,Kochtel,Kohtla Jerve,Kohtla JervÄ,Kohtla-Jaerve,Kohtla-Jaervi,Kohtla-Jarve,Kohtla-Jerve,Kohtla-JÃ¤rve,Kohtla-JÃ¤rvi,Kokhtla,Kokhtla-Jarve,Kokhtla-Yarve,Kotayarvi,Turpsal,Tyurpsal',Tyurpsalâ,TÃ¼rpsal,ÐÐÐ¥Ð¢ÐÐ-Ð¯Ð ÐÐ,ÐÐ¾ÑÑÐ»Ð°-Ð¯ÑÐ²Ðµ,ááá®á¢áá-ááá áá,Kohtla-JÃ¤rve", :latitude => "59.39861", :longitude => "27.27306").save
