City.new(:country_id => "65", :name => "Zifta", :aliases => "Zifta,ZiftÃ¡,ÐÐ¸ÑÑÐ°,ZiftÃ¡", :latitude => "30.71361", :longitude => "31.24389").save
City.new(:country_id => "65", :name => "Toukh", :aliases => "Toukh,Tukh,Tukh al Malaq,Tukh el-Malaq,TÃ»kh,TÃ»kh el-Malaq,Å¢Å«kh,Å¢Å«kh al Malaq,Ð¢ÑÑ,Toukh", :latitude => "30.34833", :longitude => "31.15806").save
City.new(:country_id => "65", :name => "Tanda", :aliases => "Tanda,Tanta,tnta,tnth,Å¢anÅ£Ä,Ð¢Ð°Ð½ÑÐ°,×× ××,×× ××,Ø·ÙØ·Ø§,á¹¬aná¹­a,Tanda", :latitude => "30.79111", :longitude => "30.99806").save
City.new(:country_id => "65", :name => "Tamiyah", :aliases => "Tamiya,Tamiyah,Tumyah,TÄmÄ«ya,Å¢Ämiyah,Å¢Ämiyah", :latitude => "29.48333", :longitude => "30.96667").save
City.new(:country_id => "65", :name => "Talkha", :aliases => "Talha,Talkha,á¹¬alkha,á¹¬alkha", :latitude => "31.05306", :longitude => "31.37389").save
City.new(:country_id => "65", :name => "Tala", :aliases => "Tala,Tale,Talla,TalÄ,Ð¢Ð°Ð»Ðµ,TalÄ", :latitude => "30.68194", :longitude => "30.9475").save
City.new(:country_id => "65", :name => "Tahta", :aliases => "Tahta,Takhta,Å¢ahÅ£Ä,Ð¢Ð°ÑÑÐ°,Å¢ahÅ£Ä", :latitude => "26.76806", :longitude => "31.49389").save
City.new(:country_id => "65", :name => "Sumusta as Sultani", :aliases => "Sumusta as Sultani,Sumusta el Sultani,SumusÅ£Ä as SulÅ£ÄnÄ«,Sumusá¹­a el Sulá¹­Ã¢ni,SumusÅ£Ä as SulÅ£ÄnÄ«", :latitude => "28.91667", :longitude => "30.85").save
City.new(:country_id => "65", :name => "Suhaj", :aliases => "Sawhaj,SawhÄj,Sohag,SohÄg,Souhag,Suhag,Suhaj,Suwhaj,SÅ«hÄg,SÅ«hÄj,SÅ«hÄj", :latitude => "26.55", :longitude => "31.7").save
City.new(:country_id => "65", :name => "Sidi Salim", :aliases => ",SÄ«dÄ« SÄlim", :latitude => "31.27194", :longitude => "30.78722").save
City.new(:country_id => "65", :name => "Shirbin", :aliases => "Sharbin,SharbÄ«n,Sherbin,Shirbin,ShirbÃ®n,ShirbÃ®n", :latitude => "31.19389", :longitude => "31.52444").save
City.new(:country_id => "65", :name => "Shibin al Qanatir", :aliases => "Shabin al Qanatir,Shabir al-Kanatir,ShabÄ«n al QanÄtir,Shibin al Qanatir,Shibin el-Qanatir,ShibÃ®n el-QanÃ¢á¹­ir,ShibÄ«n al QanÄÅ£ir,ShibÄ«n al QanÄÅ£ir", :latitude => "30.31278", :longitude => "31.32111").save
City.new(:country_id => "65", :name => "Samannud", :aliases => "Samannud,SamannÃ»d,SamannÅ«d,Samnud,SamnÅ«d,Sebennytos,SamannÅ«d", :latitude => "30.96278", :longitude => "31.24444").save
City.new(:country_id => "65", :name => "Samalut", :aliases => "Samalut,SamÄlÅ«Å£,SamÄlÅ«Å£", :latitude => "28.3", :longitude => "30.7").save
City.new(:country_id => "65", :name => "Rosetta", :aliases => "Bolbitine,Er-Rashid,Rachid,Rashid,RashÃ®d,RashÄ«d,Rosetta,Rosette,mdynt rshyd,ÙØ¯ÙÙØ© Ø±Ø´ÙØ¯,Rosetta", :latitude => "31.40444", :longitude => "30.41639").save
City.new(:country_id => "65", :name => "Quwaysina", :aliases => "Kuesnah,Quwaysina,QuwaysinÄ,Quweisna,QuwaysinÄ", :latitude => "30.56667", :longitude => "31.15").save
City.new(:country_id => "65", :name => "Qutur", :aliases => "Kotur,KotÃ»r,Qotur,Qutur,QuÅ£Å«r,Quá¹­Ã»r,QuÅ£Å«r", :latitude => "30.98333", :longitude => "30.95").save
City.new(:country_id => "65", :name => "Kousa", :aliases => "Apollinopolis Parva,Apollonopolis Parva,Kousa,Qus,QÅ«Å,Kousa", :latitude => "25.91667", :longitude => "32.75").save
City.new(:country_id => "65", :name => "Qina", :aliases => "Caene,Kena,Keneh,Qana,QanÄ,Qena,Qina,QinÄ,astan qna,qna,Ø§Ø³ØªØ§Ù ÙÙØ§,ÙÙØ§,QinÄ", :latitude => "26.17", :longitude => "32.72722").save
City.new(:country_id => "65", :name => "Qalyub", :aliases => "Kal'jub,Kalyub,KalyÃ»b,Qaliub,Qalyub,QalyÅ«b,ÐÐ°Ð»ÑÑÐ±,QalyÅ«b", :latitude => "30.18306", :longitude => "31.20528").save
City.new(:country_id => "65", :name => "Naj` Hammadi", :aliases => "Gebel el Hagif,Nag Hamadi,Nag Hamady,Nag Hammadi,Nag Hammadi-geschriften,Nag HammÃ¡dÃ­,Nag HammÃ¢di,Nag-Hamado,Nag` Hammadi,Naga Hamadi,Nagâ HammÄdi,Naj` Hammadi,Naj` al Hammadi,Najâ al á¸¨ammÄdÄ«,Najâ á¸¨ammÄdÄ«,na ge ma di,ãã°ã»ãããã£åæ¬,æ¿æçªç¬¬,Najâ á¸¨ammÄdÄ«", :latitude => "26.05139", :longitude => "32.23861").save
City.new(:country_id => "65", :name => "Minyat an Nasr", :aliases => "Minyat an Nasr,Minyat an NaÅr,Minyet el-Nasr,Minyet el-Naá¹£r,Minyat an NaÅr", :latitude => "31.13306", :longitude => "31.63361").save
City.new(:country_id => "65", :name => "Minuf", :aliases => "Manuf,ManÅ«f,Menouf,Menoufis,Menuf,Minuf,MinÅ«f,MinÅ«f", :latitude => "30.46667", :longitude => "30.93333").save
City.new(:country_id => "65", :name => "Matay", :aliases => "Matai,Matay,MatÃ¢i,MaÅ£Äy,Muttay,MaÅ£Äy", :latitude => "28.42222", :longitude => "30.75556").save
City.new(:country_id => "65", :name => "Mashtul as Suq", :aliases => "Mashtul as Suq,Mashtul el-Suq,MashtÃ»l el-SÃ»q,MashtÅ«l as SÅ«q,MashtÅ«l as SÅ«q", :latitude => "30.36056", :longitude => "31.3775").save
City.new(:country_id => "65", :name => "Marsa Matruh", :aliases => "Madara,Marsa Matruh,Marsa-Matrukh,MarsÃ¡ MaÅ£rÅ«á¸©,Matruh,MaÅ£rÅ«á¸©,Mersa Matrouh,Mersa Matruh,Mersa Maá¹­rÃ»á¸¥,Mhadara,Paraetonium,ÐÐ°ÑÑÐ°-ÐÐ°ÑÑÑÑ,MarsÃ¡ MaÅ£rÅ«á¸©", :latitude => "31.35", :longitude => "27.23333").save
City.new(:country_id => "65", :name => "Manfalut", :aliases => "Manfalut,ManfalÅ«Å£,Monfalut,ManfalÅ«Å£", :latitude => "27.31111", :longitude => "30.96944").save
City.new(:country_id => "65", :name => "Mallawi", :aliases => "Mallauri,Mallavi,Mallawi,MallawÄ«,ÐÐ°Ð»Ð»Ð°Ð²Ð¸,MallawÄ«", :latitude => "27.73194", :longitude => "30.84111").save
City.new(:country_id => "65", :name => "Madinat Sittah Uktubar", :aliases => "6 October City,Madinat Sittah Uktubar,MadÄ«nat Sittah UktÅ«bar,October 6,MadÄ«nat Sittah UktÅ«bar", :latitude => "29.81667", :longitude => "31.05").save
City.new(:country_id => "65", :name => "Kawm Umbu", :aliases => "Kawm Ombo,Kawm Umbu,Kawm UmbÅ«,Kom Ombo,Kom Ombo - kwm ambw,Kom Ombo - ÙÙÙ Ø£ÙØ¨Ù,Kum Ombu,KÃ´m Ombo,Omboi,Ombos,kom-ombo,ÐÐ¾Ð¼-ÐÐ¼Ð±Ð¾,ã³ã ã»ãªã³ã,Kawm UmbÅ«", :latitude => "24.47917", :longitude => "32.94361").save
City.new(:country_id => "65", :name => "Kawm Hamadah", :aliases => "Kawm Hamadah,Kawm á¸¨amÄdah,Kom Hamada,KÃ´m á¸¤amÃ¢da,Kawm á¸¨amÄdah", :latitude => "30.75583", :longitude => "30.69889").save
City.new(:country_id => "65", :name => "Kafr Saqr", :aliases => "Kafr Saqr,Kafr Åaqr,Kafr á¹¢aqr,Kafr Åaqr", :latitude => "30.79639", :longitude => "31.62611").save
City.new(:country_id => "65", :name => "Kafr az Zayyat", :aliases => "Kafr az Zayat,Kafr az Zayyat,Kafr az ZayyÄt,Kafr az ZayÄt,Kafr el-Zaiyat,Kafr el-ZaiyÃ¢t,Kafr el-Zayat,Kafr ez Zaiyat,Kafraz Zayyt,Kafr az ZayyÄt", :latitude => "30.82056", :longitude => "30.81583").save
City.new(:country_id => "65", :name => "Kafr ash Shaykh", :aliases => "Kafr al-Sheikh,Kafr ash Shaykh,Kafr el-Sheikh,Kafr-Sheikh,Kafr ash Shaykh", :latitude => "31.11139", :longitude => "30.93639").save
City.new(:country_id => "65", :name => "Kafr ad Dawwar", :aliases => "Kafr ad Dawwar,Kafr ad DawwÄr,Kafr al-Dawar,Kafr ed-Dauwar,Kafr ed-DauwÃ¢r,Kafr el Dawdar,Kafr el-Dauwar,Kafr el-DauwÃ¢r,Kafr ad DawwÄr", :latitude => "31.13385", :longitude => "30.12843").save
City.new(:country_id => "65", :name => "Juhaynah", :aliases => "Giheina,Jihaynah,Juhaynah,Juhaynah", :latitude => "26.67444", :longitude => "31.49167").save
City.new(:country_id => "65", :name => "Jirja", :aliases => "Girga,Jirja,JirjÄ,JirjÄ", :latitude => "26.34583", :longitude => "31.88611").save
City.new(:country_id => "65", :name => "`Izbat al Burj", :aliases => "Ezbet el-Burg,`Ezbet el-Burg,`Izbat al Burj,âEzbet el-Burg,âIzbat al Burj,âIzbat al Burj", :latitude => "31.50833", :longitude => "31.83472").save
City.new(:country_id => "65", :name => "Itsa", :aliases => ",IÅ£sÄ", :latitude => "29.23722", :longitude => "30.78556").save
City.new(:country_id => "65", :name => "Isna", :aliases => "Asna,AsnÄ,Ehsna,Esna,Esneh,Isna,IsnÄ,Latonpolis,Latopolia,Latopolis,LatÃ³npolis,asna,Ð­ÑÐ½Ð°,×××¡× ×,××¡× ×,Ø¥Ø³ÙØ§,IsnÄ", :latitude => "25.29306", :longitude => "32.55278").save
City.new(:country_id => "65", :name => "Idku", :aliases => "Edkou,Idku,IdkÅ«,ÐÐ´ÐºÑ,IdkÅ«", :latitude => "31.30782", :longitude => "30.29901").save
City.new(:country_id => "65", :name => "Ibshaway", :aliases => "Ibshawai,Ibshaway,IbshawÄy,IbshawÄy", :latitude => "29.35889", :longitude => "30.67833").save
City.new(:country_id => "65", :name => "Hilwan", :aliases => "Halwan,Helouan,Helouan-les-Bains,Helwan,Helwan Les Bains,Hilwan,Hulwan,HÃ©louan-les-Bains,Kheluan,Ð¥ÐµÐ»ÑÐ°Ð½,á¸¤elwÃ¢n,á¸¨alwÄn,á¸¨ulwÄn,Hilwan", :latitude => "29.85", :longitude => "31.33333").save
City.new(:country_id => "65", :name => "Hihya", :aliases => "Hehia,Hihya,HihyÄ,Rehia,HihyÄ", :latitude => "30.67", :longitude => "31.58722").save
City.new(:country_id => "65", :name => "Hawsh `Isa", :aliases => "Haush `Isa,Haush âIsÃ¡,Hawsh `Isa,Hosh `Isa,á¸¤Ã´sh âÃsa,á¸¨awsh âÄªsÃ¡,á¸¨awsh âÄªsÃ¡", :latitude => "30.91278", :longitude => "30.29056").save
City.new(:country_id => "65", :name => "Fuwah", :aliases => "Fouah,Fowa,Fuwa,Fuwah,Fuwah", :latitude => "31.2025", :longitude => "30.54722").save
City.new(:country_id => "65", :name => "Farshut", :aliases => "Farshut,Farshuut,FarshÅ«Å£,FarshÅ«Å£", :latitude => "26.055", :longitude => "32.16167").save
City.new(:country_id => "65", :name => "Fariskur", :aliases => "Faraskur,FaraskÃ»r,Fariskur,FÃ¢riskÃ»r,FÄriskÅ«r,FÄriskÅ«r", :latitude => "31.33083", :longitude => "31.71611").save
City.new(:country_id => "65", :name => "Faqus", :aliases => "Fakous,Fakus,Faqus,FÄqÅ«s,FÄqÅ«s", :latitude => "30.72972", :longitude => "31.79722").save
City.new(:country_id => "65", :name => "Damietta", :aliases => "Damiata,Damietta,Damiette,Dimyat,DimyÄá¹­,Dum'jat,Dumiat,Dumqat,Dumyat,DumyÃ¢á¹­,DumyÄÅ£,dmyat,ÐÑÐ¼ÑÑÑ,Ø¯ÙÙØ§Ø·,Damietta", :latitude => "31.41944", :longitude => "31.815").save
City.new(:country_id => "65", :name => "Diyarb Najm", :aliases => "Diarb Negm,Diyarb Najm,Diyarb Nigm,Diyarb Najm", :latitude => "30.75417", :longitude => "31.44056").save
City.new(:country_id => "65", :name => "Disuq", :aliases => "Dasuq,DasÅ«q,Dessouk,Disuk,Disuq,DisÅ«q,ÐÐ¸ÑÑÐº,DisÅ«q", :latitude => "31.12944", :longitude => "30.64639").save
City.new(:country_id => "65", :name => "Dishna", :aliases => "Dashna,DashnÄ,Dechna,Deshna,Dishna,DishnÄ,DishnÄ", :latitude => "26.12111", :longitude => "32.46528").save
City.new(:country_id => "65", :name => "Dikirnis", :aliases => "Dekernes,Dikinis,Dikirnis,ÐÐ¸ÐºÐ¸ÑÐ½Ð¸Ñ,Dikirnis", :latitude => "31.08833", :longitude => "31.59694").save
City.new(:country_id => "65", :name => "Dayrut", :aliases => "Dairut,Dairut el Mahatta,DairÃ»t,DairÃ»t el Maá¸¥aá¹­á¹­a,Dayrut,Dayrut al Mahattah,DayrÅ«Å£,DayrÅ«Å£ al Maá¸©aÅ£Å£ah,Deirout,Deirut,DayrÅ«Å£", :latitude => "27.55861", :longitude => "30.80778").save
City.new(:country_id => "65", :name => "Dayr Mawas", :aliases => "Dayr Mawas,Dayr MawÄs,Deir Mawas,Deir MawÄs,Dayr MawÄs", :latitude => "27.64139", :longitude => "30.84944").save
City.new(:country_id => "65", :name => "Damanhur", :aliases => "Bandar Damanhur,Bandar DamanhÅ«r,Damanhour,Damanhur,DamanhÃ»r,Damankhur,Hermopolis Parva,Hermupolis Parva,dmnhwr,ÐÐ°Ð¼Ð°Ð½ÑÑÑ,Ø¯ÙÙÙÙØ±,DamanhÃ»r", :latitude => "31.03333", :longitude => "30.46667").save
City.new(:country_id => "65", :name => "Bush", :aliases => ",BÅ«sh", :latitude => "29.15", :longitude => "31.13333").save
City.new(:country_id => "65", :name => "Port Said", :aliases => "Bor Sa`id,Bor SaâÄ«d,Bur Sa`id,Bursaid,BÅ«r SaâÄ«d,Madinat Bur Sa`id,Madinet Port Said,MadÃ®nat BÅ«r SaâÄ«d,MadÃ®net Port Said,Port Said,Port Saidas,Port SaÃ­d,Port-Said,Port-SaÃ¯d,Porto Said,Puerto Said,Puerto SaÃ­d,sai de gang,ÐÐ¾ÑÑ-Ð¡Ð°Ð¸Ð´,×¤××¨× ×¡×¢××,Ø¨ÙØ±Ø³Ø¹ÙØ¯,å¡å¾·æ¸¯,Port Said", :latitude => "31.28056", :longitude => "32.3075").save
City.new(:country_id => "65", :name => "Bur Safajah", :aliases => "Bur Safajah,BÅ«r SafÄjah,Port Safaga,Port SafÃ¢ga,Safaga,sfaja,Ð¡Ð°ÑÐ°Ð³Ð°,Ø³ÙØ§Ø¬Ø§,BÅ«r SafÄjah", :latitude => "26.73333", :longitude => "33.93333").save
City.new(:country_id => "65", :name => "Bilqas Qism Awwal", :aliases => "Balqas,BalqÄs,Bilqas,Bilqas Qism Auwal,Bilqas Qism Awwal,BilqÃ¢s,BilqÃ¢s Qism Auwal,BilqÄs Qism Awwal,BilqÄs Qism Awwal", :latitude => "31.21306", :longitude => "31.3575").save
City.new(:country_id => "65", :name => "Bilbays", :aliases => "Belbeis,Bilbays,Bilbeis,Bilbes,BilbÃªs,blbys,Ø¨ÙØ¨ÙØ³,Bilbays", :latitude => "30.41667", :longitude => "31.56667").save
City.new(:country_id => "65", :name => "Basyun", :aliases => "Basyun,BasyÃ»n,BasyÅ«n,BasyÅ«n", :latitude => "30.94028", :longitude => "30.81389").save
City.new(:country_id => "65", :name => "Bani Suwayf", :aliases => "Bani Suwayf,BanÄ« Suwayf,Beni Souef,Beni Sue,Beni Suef,Beni Suweif,BanÄ« Suwayf", :latitude => "29.06389", :longitude => "31.08889").save
City.new(:country_id => "65", :name => "Bani Mazar", :aliases => "Bani Mazar,BanÄ« MazÄr,Beni Mazar,Beni MazÃ¢r,BanÄ« MazÄr", :latitude => "28.50361", :longitude => "30.79917").save
City.new(:country_id => "65", :name => "Banha", :aliases => "Athribis,Bandar Banha,Bandar BanhÄ,Banha,BanhÄ,Bankha,Benha,Benna,ÐÐ°Ð½ÑÐ°,BanhÄ", :latitude => "30.46083", :longitude => "31.1875").save
City.new(:country_id => "65", :name => "Az Zaqaziq", :aliases => "As Zaqaziq,As ZaqÄzÄ«q,Az Zagazig,Az ZagÄzÄ«g,Az Zaqaziq,Az ZaqÄzÄ«q,Es Zaqiziq,Ez Zaqaziq,Ez ZaqÄzÄ«q,Zagazig,Zaqaziq,ZaqazÃ®q,alzqazyq,Ø§ÙØ²ÙØ§Ø²ÙÙ,Az ZaqÄzÄ«q", :latitude => "30.59139", :longitude => "31.51028").save
City.new(:country_id => "65", :name => "Awsim", :aliases => "Ausim,AusÃ®m,Awsim,AwsÄ«m,Letopolis,Letous Polis,Usiim,AwsÄ«m", :latitude => "30.1225", :longitude => "31.13361").save
City.new(:country_id => "65", :name => "At Tall al Kabir", :aliases => "At Tall al Kabir,At Tall al KabÄ«r,At Tell al Kebir,At Tell al KebÄ«r,El-Tell el-Kebir,El-Tell el-KebÃ®r,Et Tell el Kebir,Et Tell el KebÄ«r,Tel el Kebir,Tell el- Kebir,Tell el- KebÃ®r,At Tall al KabÄ«r", :latitude => "30.54556", :longitude => "31.77806").save
City.new(:country_id => "65", :name => "Asyut", :aliases => "As'jut,Assiout,Assiut,Assuit,Asyut,AsyÅ«Å£,Licopolis,Likupulis,Lycopolis,LÄ«kÅ«pÅ«lÄ«s,Siut,ÐÑÑÑÑ,AsyÅ«Å£", :latitude => "27.18278", :longitude => "31.18278").save
City.new(:country_id => "65", :name => "Aswan", :aliases => "Assouan,Assuan,Assuao,AssuÃ£o,Asuan,Asuan - aswan,Asuanas,Asuano,AsuÃ¡n,AsuÃ¡n - Ø£Ø³ÙØ§Ù,Aswan,AswÃ¢n,AswÄn,AsÅ­ano,Es-Suan,Syena,Syene,Syeue,asuwan,aswan,ÐÑÑÐ°Ð½,××¡×××,Ø£Ø³ÙØ§Ù,ã¢ã¹ã¯ã³,AswÄn", :latitude => "24.0875", :longitude => "32.89889").save
City.new(:country_id => "65", :name => "Suez", :aliases => "Al Qulzum,As Suways,Clysma,El Seweis,El Suweis,El-Qulzum,Es Suweis,Klysma,Souez,Suecas,Suehc,Suehckij,Sues,Suess,Sueveys,Suez,SuÃ«s,SÃºes,SÃ¼veyÅ,suejeu,suezu,swys,Î£Î¿ÏÎ­Î¶,Ð¡ÑÑÑ,Ð¡ÑÑÑÐºÐ¸Ð¹,Ø³ÙÙØ³,ã¹ã¨ãº,ììì¦,Suez", :latitude => "29.96667", :longitude => "32.55").save
City.new(:country_id => "65", :name => "As Saff", :aliases => "As Saff,AÅ Åaff,El-Saff,Es Saff,AÅ Åaff", :latitude => "29.56472", :longitude => "31.28111").save
City.new(:country_id => "65", :name => "Ash Shuhada'", :aliases => "Ash Shuhada',Ash ShuhadÄâ,El Shohada,El-Shuhada,Esh-Shuhada,Ash ShuhadÄâ", :latitude => "30.59361", :longitude => "30.90333").save
City.new(:country_id => "65", :name => "Ashmun", :aliases => ",AshmÅ«n", :latitude => "30.3", :longitude => "30.96667").save
City.new(:country_id => "65", :name => "Al Wasitah", :aliases => "Al Wasitah,Al WÄsiÅ£ah,El Wasta,El WÄsta,Wasta,Al WÄsiÅ£ah", :latitude => "29.33778", :longitude => "31.20556").save
City.new(:country_id => "65", :name => "Luxor", :aliases => "Al Uqsur,Al UqÅur,El Aqsur,El Kusur,El Qusur,El Uqsor,El-Aksur,Louksor,Louxor,Loxor,LoxÃ²r,Luksor,Luksoras,Luksoro,Luqsor,Luxor,Luxor- alaqsr,Luxor- Ø§ÙØ£ÙØµØ±,alaqsr,aqsr,le shu,luksori,ÐÑÐºÑÐ¾Ñ,Ø§ÙØµØ±,Ø§ÙØ£ÙØµØ±,Ø§ÙØ§ÙØµØ±,áá£á¥á¡áá á,æ¨è,Luxor", :latitude => "25.69893", :longitude => "32.6421").save
City.new(:country_id => "65", :name => "Al Qusiyah", :aliases => "Al Qusiyah,Al QÅ«ÅÄ«yah,Cusae,El Qusiya,El QÅ«sÄ«ya,Al QÅ«ÅÄ«yah", :latitude => "27.44444", :longitude => "30.81667").save
City.new(:country_id => "65", :name => "Al Qusayr", :aliases => "Al Qusayr,Al QuÅayr,Al'-Kusajra,Koseir,Leucus Limen,Qosier,Qosseir,Quseir,ÐÐ»Ñ-ÐÑÑÐ°Ð¹ÑÐ°,Al QuÅayr", :latitude => "26.1", :longitude => "34.28333").save
City.new(:country_id => "65", :name => "Al Qurayn", :aliases => "Al Qurayn,Al'-Ehl'-Kurajn,El-Qurein,ÐÐ»Ñ-Ð­Ð»Ñ-ÐÑÑÐ°Ð¹Ð½,Al Qurayn", :latitude => "30.61278", :longitude => "31.73361").save
City.new(:country_id => "65", :name => "Al Qanayat", :aliases => "Al Qanayat,Al QanÄyÄt,El-Qanayat,El-QanÃ¢yÃ¢t,Al QanÄyÄt", :latitude => "30.61917", :longitude => "31.46194").save
City.new(:country_id => "65", :name => "Al Qanatir al Khayriyah", :aliases => "Al Qanatir al Khayriyah,Al QanÄÅ£ir al KhayrÄ«yah,Barrage,Delta Barrage Station,Delta-Barrage,El-Qanatir el-Khairiya,El-QanÃ¢á¹­ir el-KhairÃ®ya,Al QanÄÅ£ir al KhayrÄ«yah", :latitude => "30.19806", :longitude => "31.13417").save
City.new(:country_id => "65", :name => "Cairo", :aliases => "Al Qahirah,Al QÄhirah,Caire,Cairo,Cairo - alqahrt,Cairo - Ø§ÙÙØ§ÙØ±Ø©,Cairu,Cairus,CaÃ¯ro,El Caire,El Cairo,El Kahira,El Kahirah,El-Qahira,El-QÃ¢hira,Il Cairo,Kaherah,Kahira,Kahirae,Kahire,KahirÃ¤,Kair,Kaira,Kairas,Kairo,KairÃ³,Kajro,KaÃ­rÃ³,KaÃ¯ro,KÃ¡hira,Le Caire,Lo Cayiro,Lungsod ng Cairo,Masr,Misr,QahirÉ,alqahrt,kai luo,kailo,kairo,keyro,khiro,qahrh,qhyr,Ãl Cairo,Ãl CÃ iro,ÎÎ¬Î¹ÏÎ¿,ÐÐ°Ð¸Ñ,ÐÐ°Ð¸ÑÐ¾,ÐÐ°Ð¹ÑÐ¾,ÐÐ°ÑÑ,×§×××¨,Ø§ÙÙØ§ÙØ±Ø©,ÙØ§ÙØ±Ù,ÙØ§Ú¾ÙØ±Û,ÙØ§ÛØ±Û,à®à¯à®¯à¯à®°à¯,à¹à¸à¹à¸£,à½à¼à½¡à½²à¼à½¢à½¼,á¥ááá á,á«á­á®,ã«ã¤ã­,å¼ç½,ì¹´ì´ë¡,Cairo", :latitude => "30.06263", :longitude => "31.24967").save
City.new(:country_id => "65", :name => "Al Minya", :aliases => "Al Minya,Al MinyÄ,Ehl'-Min'ja,El Minia,El-Minya,Minia,Minieh,Minya,Ð­Ð»Ñ-ÐÐ¸Ð½ÑÑ,Al MinyÄ", :latitude => "28.11944", :longitude => "30.74444").save
City.new(:country_id => "65", :name => "Al Matariyah", :aliases => "Al Matariyah,Al MaÅ£arÄ«yah,El Mataria,El-Matariya,El-Maá¹­arÃ®ya,Matarieh,Al MaÅ£arÄ«yah", :latitude => "31.18389", :longitude => "32.03056").save
City.new(:country_id => "65", :name => "Al Manzilah", :aliases => "Al Manzalah,Al Manzilah,El-Manzala,Al Manzilah", :latitude => "31.15833", :longitude => "31.93694").save
City.new(:country_id => "65", :name => "Al Mansurah", :aliases => "Al Mansurah,Al ManÅÅ«rah,Al-Mansura,Al-Mansurah,El Mansura,El-Mansura,El-Maná¹£Ã»ra,El-Masura,El-MasÃ»ra,Manoura,Mansoura,Mansourah,Mansura,Mansurah,MansÃ»ra,mnswrh,mnswrt,ÙÙØµÙØ±Ø©,ÙÙØµÙØ±Ù,Al ManÅÅ«rah", :latitude => "31.04306", :longitude => "31.37667").save
City.new(:country_id => "65", :name => "Al Manshah", :aliases => "Al Manshah,Al ManshÄh,El Manshah,El ManshÄh,Ptolemais Hernnon,PtolemaÃ®s Hernnon,Al ManshÄh", :latitude => "26.47778", :longitude => "31.80139").save
City.new(:country_id => "65", :name => "Al Mahallah al Kubra", :aliases => "Al Mahallah al Kubra,Al Maá¸©allah al KubrÃ¡,El Mahalla,El Mahalla el Kubra,El Mehalla el Kubra,El-Mahalla el-Kubra,El-Maá¸¥alla el-Kubra,Mahalla el Kubra,Mehalla el Kobra,almhlt alkbry,Ø§ÙÙØ­ÙØ© Ø§ÙÙØ¨Ø±Ù,Al Maá¸©allah al KubrÃ¡", :latitude => "30.97611", :longitude => "31.16694").save
City.new(:country_id => "65", :name => "Al Khankah", :aliases => "Al Khankah,Al KhÄnkah,El-Khanka,El-Khankah,El-KhÃ¢nka,El-KhÃ¢nkÃ¢h,Khanka,Al KhÄnkah", :latitude => "30.21806", :longitude => "31.35889").save
City.new(:country_id => "65", :name => "Al Jizah", :aliases => "Al Jizah,Al JÄ«zah,El Gizeh,El-Giza,El-GÃ®za,Ghizeh,Giza,Gizah,Gizeh,Gizo,Guize,GuizÃ©,GÃ­za,GÃ®za,aljyzt,giza,jyzh,ÐÐ¸Ð·Ð°,Ø§ÙØ¬ÙØ²Ø©,Ø¬ÛØ²Ù,ã®ã¼ã¶,Al JÄ«zah", :latitude => "30.00861", :longitude => "31.21222").save
City.new(:country_id => "65", :name => "Al Jamaliyah", :aliases => "Al Jamaliyah,Al JamÄlÄ«yah,El-Gamaliya,El-GamalÃ®ya,Al JamÄlÄ«yah", :latitude => "31.18111", :longitude => "31.86722").save
City.new(:country_id => "65", :name => "Ismailia", :aliases => "Al Isma`iliya,Al Isma`iliyah,Al IsmÄâÄ«lÄ«ya,Al IsmÄâÄ«lÄ«yah,Ismailia,Ismailieh,Ismailija,Ismailiya,Ismailiyah,IsmailÃ®ya,IsmaÃ¯lia,ÐÑÐ¼Ð°Ð¸Ð»Ð¸Ñ,ÙØ¯ÙÙØ© Ø§ÙØ¥Ø³ÙØ§Ø¹ÙÙÙØ©,Ismailia", :latitude => "30.60528", :longitude => "32.27722").save
City.new(:country_id => "65", :name => "Alexandria", :aliases => "Al Iskandariyah,Al IskandarÄ«yah,Alegsandiri,AlegsÃ ndiri,Alehandriya,Alejandria,AlejandrÃ­a,Aleksandri,Aleksandria,Aleksandrija,Aleksandrio,Aleksandrje,Aleksandryjo,Alesandria d'Egito,Alessandria,Alessandria d'Eggittu,Alessandria d'Egitto,Alexandreia,Alexandria,Alexandria Magna,Alexandrie,AlexandriÃ«,AlexandrÃ­a,AlexÃ ndria,AÅesandria d'Egito,Cathair Alastair,El Iskandariya,El IskandarÄ«ya,Gorad Aleksandryja,Iskandariah,Iskandariya,Iskandariyah,Iskenderiye,Iskindiriya,IskindirÃ®ya,Ol'oksandrija,alaksantriya,alaskndryt,alecanturiya,alegjandriya,alekajandriya,alekjendriya,alekjhandriya,aleksandria,aleksandriya,allegsandeulia,arekusandoria,askndryh,elekjhandriya,x lek san de riy,ya li shan da gang,ya li shan zhuo,Ä°sgÉndÉriyyÉ,Ä°skenderiye,ÎÎ»ÎµÎ¾Î¬Î½Î´ÏÎµÎ¹Î±,ÐÐ»ÐµÐºÑÐ°Ð½Ð´ÑÐ¸,ÐÐ»ÐµÐºÑÐ°Ð½Ð´ÑÐ¸Ñ,ÐÐ»ÐµÐºÑÐ°Ð½Ð´ÑÐ¸ÑÐ°,ÐÐ»ÐµÐºÑÐ°Ð½Ð´ÑÑÑ,ÐÐ¾ÑÐ°Ð´ ÐÐ»ÐµÐºÑÐ°Ð½Ð´ÑÑÑ,Ó¦Ð»ÑÓ§ÐºÑÐ°Ð½Ð´ÑÐ¸Ñ,Ô±Õ¬Õ¥ÖÕ½Õ¡Õ¶Õ¤ÖÕ«Õ¡,××××¡× ××¨××,×××¢×§×¡×× ××¨××¢,Ø¦ÛØ³Ú©ÛÙØ¯ÛØ±ÛÛÛ,Ø§Ø³ÙÙØ¯Ø±ÙÙ,Ø§Ø³Ú©ÙØ¯Ø±ÛÙ,Ø§Ø³Ú©ÙØ¯Ø±ÛÛ,Ø§ÙØ¥Ø³ÙÙØ¯Ø±ÙØ©,ÜÜ ÜÜ£Ü¢ÜÜªÜÜ,à¤à¤²à¥à¤à¥à¤à¥à¤à¤¡à¥à¤°à¤¿à¤¯à¤¾,à¤à¤²à¥à¤à¥à¤à¤¾à¤à¤¡à¥à¤°à¤¿à¤¯à¤¾,à¦à¦²à§à¦à¦à¦¾à¦¨à§à¦¦à§à¦°à¦¿à¦¯à¦¼à¦¾,à¦à¦²à§à¦à§à¦¸à¦¾à¦¨à§à¦¡à§à¦°à¦¿à¦¯à¦¼à¦¾,àªàª²à«àªà«àªàª¾àª¨à«àª¡à«àª°àª¿àª¯àª¾,à®à®²à¯à®à®¾à®¨à¯à®¤à¯à®°à®¿à®¯à®¾,à°à°²à±à°à±à°à°¾à°à°¡à±à°°à°¿à°¯à°¾,à²à²²à³à²à³à²¸à²¾à²à²¡à³à²°à²¿à²¯,à´à´²à´àµà´¸à´¾à´£àµà´àµà´°à´¿à´¯,à¸­à¹à¸¥à¹à¸à¸à¸²à¸à¹à¸à¸£à¸µà¸¢,à½¡à¼à½£à½²à¼à½§à¾²à½à¼à½,áááá¥á¡áááá áá,ã¢ã¬ã¯ãµã³ããªã¢,äºåå±±å¤§æ¸¯,äºæ­·å±±å,ìë ì°ëë¦¬ì,Alexandria", :latitude => "31.19806", :longitude => "29.91917").save
City.new(:country_id => "65", :name => "Al Ibrahimiyah", :aliases => "Al Ibrahimiyah,Al IbrÄhÄ«mÄ«yah,El-Ibrahimiya,El-IbrÃ¢hÃ®mÃ®ya,Ibrahimiya,Ibrahimiyyah,IbrÃ¢hÃ®mÃ®ya,Al IbrÄhÄ«mÄ«yah", :latitude => "30.71083", :longitude => "31.54028").save
City.new(:country_id => "65", :name => "Al Hawamidiyah", :aliases => "Al Hawamidiyah,Al á¸¨awÄmidÄ«yah,El-Hawamdiya,El-á¸¤awÃ¢mdÃ®ya,Hawamidyah,Al á¸¨awÄmidÄ«yah", :latitude => "29.9", :longitude => "31.25").save
City.new(:country_id => "65", :name => "Al Hamul", :aliases => "Al Hamul,Al á¸¨ÄmÅ«l,El-Hamul,El-á¸¤Ã¢mÃ»l,Al á¸¨ÄmÅ«l", :latitude => "31.31139", :longitude => "31.15583").save
City.new(:country_id => "65", :name => "Al Ghardaqah", :aliases => "Al Ghardaqah,Al-Ghardaqa,El-Ghardaqa,Hurgada,Hurghada,Khurgada,Urgada,alghrdqt,ghrdqh,hong jia da,Ð¥ÑÑÐ³Ð°Ð´Ð°,Ø§ÙØºØ±Ø¯ÙØ©,ØºØ±Ø¯ÙÙ,æ´ªå é,Al Ghardaqah", :latitude => "27.25738", :longitude => "33.81291").save
City.new(:country_id => "65", :name => "Al Fayyum", :aliases => "Al Fayyum,Al FayyÅ«m,Al'-Fajum,Al-Fayyum,Arsinoe,ArsinoÃ«,Crocodilopolis,El Faiyum,El FaiyÃ»m,El-Fayum,Faijum,Faium,Fajum,Fayoom,Fayoum,Fayum,Fayyoum,Fayyum,Madinat al-Fayyum,Madinet el Faiyum,MadÄ«net el FaiyÅ«m,Medinat Fayum,Medinat el-Fayoum,MÃ©dinat el-Fayoum,Shedit,alfywm,astan fywm,mhafzt alfywm,ÐÐ»Ñ-Ð¤Ð°ÑÐ¼,Ø§Ø³ØªØ§Ù ÙÛÙÙ,Ø§ÙÙÙÙÙ,ÙØ­Ø§ÙØ¸Ø© Ø§ÙÙÙÙÙ,Al FayyÅ«m", :latitude => "29.30778", :longitude => "30.84").save
City.new(:country_id => "65", :name => "Al Fashn", :aliases => "Al Fashn,El Fashn,Fashn,Al Fashn", :latitude => "28.82278", :longitude => "30.89778").save
City.new(:country_id => "65", :name => "Al Bawiti", :aliases => "Al Bawiti,Al BawÄ«Å£Ä«,Baviti,Bawiti,BawÄ«ti,El Bawiti,El BawÃ®ti,ÐÐ°Ð²Ð¸ÑÐ¸,Al BawÄ«Å£Ä«", :latitude => "28.35", :longitude => "28.86667").save
City.new(:country_id => "65", :name => "Al Balyana", :aliases => "Al Balyana,Al BalyanÄ,Balyana,El Balyana,Al BalyanÄ", :latitude => "26.23861", :longitude => "32.00306").save
City.new(:country_id => "65", :name => "Al Bajur", :aliases => "Al Bajur,Al BÄjÅ«r,El Baqur,El-Bagur,El-BÃ¢gÃ»r,Al BÄjÅ«r", :latitude => "30.43083", :longitude => "31.03444").save
City.new(:country_id => "65", :name => "Al Badari", :aliases => "Al Badari,Al BadÄrÄ«,El Badari,El BadÃ¢ri,Al BadÄrÄ«", :latitude => "26.99222", :longitude => "31.41528").save
City.new(:country_id => "65", :name => "Al `Ayyat", :aliases => "Al `Ayyat,Al âAyyÄÅ£,Ayat,El `Ayyat,El âAyyat,El-`Aiyat,El-âAiyaá¹­,Al âAyyÄÅ£", :latitude => "29.61972", :longitude => "31.2575").save
City.new(:country_id => "65", :name => "Al `Arish", :aliases => "Al `Arish,Al âArÄ«sh,City of Cut Noses,El-`Arish,El-âArÃ®sh,Rhinocolorum,Rhinocolura,Rhinocorura,Rhinokorura,Al âArÄ«sh", :latitude => "31.12611", :longitude => "33.80194").save
City.new(:country_id => "65", :name => "Akhmim", :aliases => "Akhmim,Akhmun,AkhmÃ»n,AkhmÄ«m,Ekhmin,Khemmis,Paloupolis,Panopolis,Panospolis,ÐÑÐ¼Ð¸Ð¼,AkhmÄ«m", :latitude => "26.56667", :longitude => "31.73333").save
City.new(:country_id => "65", :name => "Aja", :aliases => "Aga,Aja,AjÄ,ÐÐ¹Ð°,AjÄ", :latitude => "30.94167", :longitude => "31.29222").save
City.new(:country_id => "65", :name => "Ad Dilinjat", :aliases => "Ad Dilinjat,Ad DilinjÄt,Delingat,Ed Dilingat,Ed DilingÄt,El-Dilingat,El-DilingÃ¢t,Tayyibat al Ism,Å¢ayyibat al Ism,Ad DilinjÄt", :latitude => "30.82806", :longitude => "30.53417").save
City.new(:country_id => "65", :name => "Abu Tij", :aliases => "Abu Tig,Abu Tij,Abu TÃ®g,AbÅ« TÄ«j,AbÅ« TÄ«j", :latitude => "27.03333", :longitude => "31.31667").save
City.new(:country_id => "65", :name => "Abu Qurqas", :aliases => "Abu Gurgas,Abu Kerkae,Abu Kirkas,Abu Qurqas,Abu-Qirqas,AbÅ« QurqÄÅ,AbÅ« QurqÄÅ", :latitude => "27.93083", :longitude => "30.83639").save
City.new(:country_id => "65", :name => "Abu Kabir", :aliases => "Abu Kabir,Abu Kebir,Abu KebÃ®r,AbÅ« KabÄ«r,AbÅ« KabÄ«r", :latitude => "30.72528", :longitude => "31.66833").save
City.new(:country_id => "65", :name => "Abu al Matamir", :aliases => "Abu `elwet-Matamir,Abu al Matamir,Abu el Matamir,Abu el MatÄmÄ«r,AbÃ» âelwet-Maá¹­Ã¢mÃ®r,AbÅ« al MaÅ£ÄmÄ«r,AbÅ« al MaÅ£ÄmÄ«r", :latitude => "30.90833", :longitude => "30.1775").save
City.new(:country_id => "65", :name => "Abnub", :aliases => "Abnub,AbnÅ«b,AbnÅ«b", :latitude => "27.26667", :longitude => "31.15028").save
City.new(:country_id => "65", :name => "Idfu", :aliases => ",Idfu", :latitude => "24.98028", :longitude => "32.87472").save
City.new(:country_id => "65", :name => "Az Zarqa", :aliases => ",Az ZarqÄ", :latitude => "31.20833", :longitude => "31.63333").save
City.new(:country_id => "65", :name => "Emirate's Embassy", :aliases => ",Emirate's Embassy", :latitude => "30.0812", :longitude => "31.34537").save
City.new(:country_id => "65", :name => "Ain Sukhna", :aliases => "Ajn-Sukhna,ÐÐ¹Ð½-Ð¡ÑÑÐ½Ð°,Ain Sukhna", :latitude => "29.60018", :longitude => "32.31671").save
