City.new(:country_id => "81", :name => "Zugdidi", :aliases => "Sugdidi,ZUGDIDI,Zugdidi,Zugdidis,Zygdidi,zwgdydy,ÐÐ£ÐÐÐÐÐ,ÐÑÐ³Ð´Ð¸Ð´Ð¸,×××××××,áá£ááááá,Zugdidi", :latitude => "42.5088", :longitude => "41.87088").save
City.new(:country_id => "81", :name => "Zestap'oni", :aliases => "Dshugeli,Dzhugeli,Kvirily,Namaneva,Sestafoni,ZESTAFONI,Zestafoni,Zestap'oni,Zestapâoni,Zetaponi,Zistafoni,ÐÐÐ¡Ð¢ÐÐ¤ÐÐÐ,Zestapâoni", :latitude => "42.11", :longitude => "43.0525").save
City.new(:country_id => "81", :name => "Ts'khinvali", :aliases => "Ckhinvali,Stalinir,Staliniri,Stavinir,Ts'khinvali,Tsâkhinvali,Ð¦ÑÐ¸Ð½Ð²Ð°Ð»Ð¸,Tsâkhinvali", :latitude => "42.22764", :longitude => "43.96861").save
City.new(:country_id => "81", :name => "Tqvarch'eli", :aliases => "Tkuarchal,Tkvarcheli,Tkvarchely,Tkwartscheli,Ð¢ÐºÑÐ°ÑÑÐ°Ð»,Tqvarch'eli", :latitude => "42.84035", :longitude => "41.68007").save
City.new(:country_id => "81", :name => "T'elavi", :aliases => "T'elavi,TELAVI,Telav,Telavi,Telavis,Telawi,Telev,Thelavi,Tâelavi,telavi,Ð¢ÐÐÐÐÐ,Ð¢ÐµÐ»Ð°Ð²Ð¸,áááááá,Tâelavi", :latitude => "41.91978", :longitude => "45.47315").save
City.new(:country_id => "81", :name => "Tbilisi", :aliases => "Kalak,TBILISI,Tbilisi,Tbilisi - tbilisi,Tbilisi - áááááá¡á,Tbilisis,Tbilissi,Tbilsi,Tblisi,Thbilisi,Tiblisi,TiblÃ®sÃ®,Tiflis,Tiphlida,Tpilisi,TÃ­flis,di bi li si,tbilisi,tblysy,tbylysy,teubillisi,tflys,tobirishi,Î¤Î¹ÏÎ»Î¯Î´Î±,ÐÐ°Ð»Ð°Ðº,Ð¢ÐÐÐÐÐ¡Ð,Ð¢Ð±Ð¸Ð»Ð¸ÑÐ¸,Ð¢Ð±Ð¸Ð»Ð¸ÑÓ£,Ð¢Ð±ÑÐ»ÑÑÑ,××××××¡×,ØªØ¨ÙÙØ³Ù,ØªÙÙÛØ³,à¦¤à¦¿à¦¬à¦¿âà¦²à¦¿à¦¸à¦¿,áááááá¡á,áµá¥áá²,ãããªã·,ç¬¬æ¯å©æ¯,í¸ë¹ë¦¬ì,Tbilisi", :latitude => "41.69411", :longitude => "44.83368").save
City.new(:country_id => "81", :name => "Sokhumi", :aliases => "Akva,SUKHUMI,Sochumi,Sohumi,Sohumkale,Sokhumi,Soukhoumi,Ssuchum,Suchum,Suchumi,Suhhumi,Suhumi,Suhumo,Sujumi,Sukhum,Sukhumi,SuÄ¥umo,su hu mi,sufumi,suhumi,swhwmy,ÐÒÉÐ°,Ð¡Ð£Ð¥Ð£ÐÐ,Ð¡ÑÑÑÐ¼,Ð¡ÑÑÑÐ¼Ð¸,×¡×××××,ã¹ãã,èå¼ç±³,ìíë¯¸,Sokhumi", :latitude => "43.00697", :longitude => "40.9893").save
City.new(:country_id => "81", :name => "Senaki", :aliases => "Achal Senaki,Akhalsenaki,Micha-Zchakaja,Mikha Tskhakaya,Novo-Senaki,SENAKI,Senaki,Tskhakaya,Tskhakuya,Ð¡ÐÐÐÐÐ,á¡ááááá,Senaki", :latitude => "42.27042", :longitude => "42.0675").save
City.new(:country_id => "81", :name => "Samtredia", :aliases => "SAMTREDIA,Samtredia,Ssamtredia,Ð¡ÐÐÐ¢Ð ÐÐÐÐ,Samtredia", :latitude => "42.1537", :longitude => "42.33517").save
City.new(:country_id => "81", :name => "Rust'avi", :aliases => "RUSTAVI,Roustavi,Rust'avi,Rustavi,Rustavis,Rustawi,Rusthavi,Rustâavi,rustavi,rwstwwy,Ð Ð£Ð¡Ð¢ÐÐÐ,Ð ÑÑÑÐ°Ð²Ð¸,×¨××¡×ª×××,á á£á¡áááá,Rustâavi", :latitude => "41.54949", :longitude => "44.99323").save
City.new(:country_id => "81", :name => "P'ot'i", :aliases => "P'ot'i,Poti,Pâotâi,ÐÐ¾ÑÐ¸,á¤ááá,Pâotâi", :latitude => "42.14616", :longitude => "41.67197").save
City.new(:country_id => "81", :name => "Och'amch'ire", :aliases => "OCHAMCHIRA,Och'amch'ire,Ochamchira,Ochemchiri,Ochemchiry,Ochemechiri,Ochâamchâire,Otschemtschiri,ÐÐ§ÐÐÐ§ÐÐ Ð,Ochâamchâire", :latitude => "42.71232", :longitude => "41.46863").save
City.new(:country_id => "81", :name => "Marneuli", :aliases => "Borchalo,MARNEULI,Marneuli,Sarvan,Sarwan,ÐÐÐ ÐÐÐ£ÐÐ,Marneuli", :latitude => "41.47588", :longitude => "44.80894").save
City.new(:country_id => "81", :name => "K'ut'aisi", :aliases => "KUTAISI,Khuthaisi,Kutais,Kutaisi,Kutaisk,Kutaissi,Kutayis,KutayÄ±s,KutaÃ¯si,kutaishi,kutaisi,ÐÐ£Ð¢ÐÐÐ¡Ð,ÐÑÑÐ°Ð¸ÑÐ¸,ÐÑÑÐ°ÑÑÑ,×××ª×××¡×,×§×××××¡×,á¥á£áááá¡á,ã¯ã¿ã¤ã·,ì¿ íì´ì,K'ut'aisi", :latitude => "42.24961", :longitude => "42.69974").save
City.new(:country_id => "81", :name => "Kobuleti", :aliases => "K'obulet'i,Kobuleti,Kobulyety,ÐÐ¾Ð±ÑÐ»ÐµÑÐ¸,Kobuleti", :latitude => "41.82", :longitude => "41.77528").save
City.new(:country_id => "81", :name => "Khashuri", :aliases => "Chaschuri,KHASHURI,Khachuri,Khashuri,Khasuri,Mikhailovo,Mikhaylovo,Stalinissi,Ð¥ÐÐ¨Ð£Ð Ð,á®áá¨á£á á,Khashuri", :latitude => "41.99414", :longitude => "43.59994").save
City.new(:country_id => "81", :name => "Gori", :aliases => "GORI,Gori,Goris,ge li,goli,gori,gwry,ÐÐÐ Ð,ÐÐ¾ÑÐ¸,×××¨×,Ú¯ÙØ±Û,ááá á,ã´ãª,å¥é,ê³ ë¦¬,Gori", :latitude => "41.98422", :longitude => "44.11578").save
City.new(:country_id => "81", :name => "Bat'umi", :aliases => "BATUMI,Bat'umi,Bathumi,Batoemi,Batoumi,Batum,Batumi,Batumis,BatÃ»m,Batâumi,bato~umi,batumi,btwmy,ÐÐÐ¢Ð£ÐÐ,ÐÐ°ÑÑÐ¼Ð¸,×××××,××ª×××,áááá£áá,ããã¥ã,ë°í¬ë¯¸,Batâumi", :latitude => "41.64159", :longitude => "41.63593").save
City.new(:country_id => "81", :name => "Akhalts'ikhe", :aliases => "AKHALCIKHE,Achalziche,Achalzych,Akhalts'ikhe,Akhaltsikh,Akhaltsykha,Akhaltsykhe,Akhaltsâikhe,ÐÐ¥ÐÐÐ¦ÐÐ¥Ð,Akhaltsâikhe", :latitude => "41.63901", :longitude => "42.98262").save
City.new(:country_id => "81", :name => "Stantsiya Novyy Afon", :aliases => "Novyj Afon,Novyy Afon,Psirtskha,Psyrtskha,Stantsiya Akhali-Afoni,ÐÐ¾Ð²ÑÐ¹ ÐÑÐ¾Ð½,Stantsiya Novyy Afon", :latitude => "43.08056", :longitude => "40.83833").save
City.new(:country_id => "81", :name => "Tsqaltubo", :aliases => "CKHALTUBO,Tskaltubo,Tskhaltubo,Tsqaltubo,Ð¦Ð¥ÐÐÐ¢Ð£ÐÐ,Tsqaltubo", :latitude => "42.34129", :longitude => "42.5976").save
City.new(:country_id => "81", :name => "Meria", :aliases => ",Meria", :latitude => "41.69278", :longitude => "44.80154").save
