City.new(:country_id => "91", :name => "Voula", :aliases => "Voula,VoÃºla,Vule,ÎÎ¿ÏÎ»Î±,ÐÑÐ»Ðµ,VoÃºla", :latitude => "37.84221", :longitude => "23.77651").save
City.new(:country_id => "91", :name => "Volos", :aliases => "Bolos,Iolcus,Volo,Volos,VÃ³los,Wolos,wwlws,ÎÏÎ»Î¿Ï,ÐÐ¾Ð»Ð¾Ñ,×××××¡,VÃ³los", :latitude => "39.36667", :longitude => "22.94583").save
City.new(:country_id => "91", :name => "Viron", :aliases => "Byron,Viron,VÃ­ron,ÎÏÏÏÎ½,VÃ­ron", :latitude => "37.96667", :longitude => "23.75").save
City.new(:country_id => "91", :name => "Tripolis", :aliases => "Tripole,Tripole Arkadias,Tripoli,Tripolis,Tripolitza,Tripolizza,TrÃ­poli,TrÃ­polis,Î¤ÏÎ¯ÏÎ¿Î»Î·,Î¤ÏÎ¯ÏÎ¿Î»Î· ÎÏÎºÎ±Î´Î¯Î±Ï,Ð¢ÑÐ¸Ð¿Ð¾Ð»Ð¸,TrÃ­polis", :latitude => "37.50889", :longitude => "22.37944").save
City.new(:country_id => "91", :name => "Trikala", :aliases => "Nomos Trikalon,Tirhala,Trikala,Trikalon,Trikkaion,Trikkala,TrikkaÃ­on,TrikÃ¡lon,TrÃ­kala,TrÃ­kkala,TÄ±rhala,trhalh,ÎÎ¿Î¼ÏÏ Î¤ÏÎ¹ÎºÎ¬Î»ÏÎ½,Î¤ÏÎ¯ÎºÎ±Î»Î±,Ð¢ÑÐ¸ÐºÐ°Ð»Ð°,ØªØ±Ø­Ø§ÙÙ,TrÃ­kala", :latitude => "39.55528", :longitude => "21.7675").save
City.new(:country_id => "91", :name => "Thivai", :aliases => "Teba,Tebas,Tebo,Teboj,Theba,Thebae,Thebai,Theben,Thebes,Thiva,Thivai,ThÃ­va,ThÃ­vai,ThÄbai,ÎÎ®Î²Î±,ÎÎ®Î²Î±Î¹,ÎÎ·Î²Î±Î¹,ThÃ­vai", :latitude => "38.325", :longitude => "23.31889").save
City.new(:country_id => "91", :name => "Sparta", :aliases => "Esparta,Lacedaemon,Lacedemon,Lacedemonia,LacÃ©dÃ©mon,Lakedaimon,LakedaÃ­mon,Lakedemon,Sparte,Sparti,Sparto,SpartÄ,SpÃ¡rti,ÎÎ±ÎºÎµÎ´Î±Î¹Î¼ÏÎ½,Î£ÏÎ¬ÏÏÎ·,Î£ÏÎ±ÏÏÎ·,ÐÐ°ÐºÐµÐ´ÐµÐ¼Ð¾Ð½,Sparta", :latitude => "37.07333", :longitude => "22.42972").save
City.new(:country_id => "91", :name => "Salamis", :aliases => "Koulouri,KoÃºlouri,Salamina,Salamis,SalamÃ­s,Î£Î±Î»Î±Î¼Î¯Ï,Ð¡Ð°Ð»Ð°Ð¼Ð¸Ð½Ð°,SalamÃ­s", :latitude => "37.96427", :longitude => "23.49649").save
City.new(:country_id => "91", :name => "Rethymnon", :aliases => "Nomos Rethymnes,PLATANIAS RETHYMNO,Prefectura Rethimno,Prefettura di Rethymno,Resmo,Rethimno,Rethimnon,Rethymne,Rethymno,Rethymnon,Rethymnon prefektur,RethÃ½mne,Retimno,Retimo,Retino,RÃ©thimnon,RÃ©thymno,RÃ©thymnon,RÃ©tino,ÎÎ¿Î¼ÏÏ Î¡ÎµÎ¸ÏÎ¼Î½Î·Ï,Î ÎÎÎ¤ÎÎÎÎÎ£ Î¡ÎÎÎ¥ÎÎÎ,Î¡Î­Î¸ÏÎ¼Î½Î¿,Î¡Î­Î¸ÏÎ¼Î½Î¿Î½,Ð ÐµÑÐ¸Ð¼Ð½Ð¾,RÃ©thymnon", :latitude => "35.36472", :longitude => "24.47139").save
City.new(:country_id => "91", :name => "Preveza", :aliases => "Prebeza,Prevesa,Preveza,Preveze,Preweza,PrÃ©vÃ©za,prwzh,Î ÏÎ­Î²ÎµÎ¶Î±,Ù¾Ø±ÙØ²Ù,PrÃ©veza", :latitude => "38.95", :longitude => "20.75").save
City.new(:country_id => "91", :name => "Pyrgos", :aliases => "Pirgos,Pyrgos,PÃ­rgos,Î ÏÏÎ³Î¿Ï,ÐÐ¸ÑÐ³Ð¾Ñ,PÃ½rgos", :latitude => "37.67513", :longitude => "21.44102").save
City.new(:country_id => "91", :name => "Piraeus", :aliases => "El Pireo,El Pireu,Le Piree,Le PirÃ©e,Peiraeus,Peiraia,Peiraias,Peiraiefs,Peiraieus,Peiraievs,PeiraiÃ¡,PeiraiÃ¡s,PeiraiÃ©fs,Piraeus,Piraievs,PiraiÃ©vs,Piraus,Pire,Pireefs,Pirej,Pireja,Pirejas,Pireo,Pireu,Pireus,Pireusz,PirÃ¤us,PirÃ©efs,PirÄjas,bi lei ai fu si,byrayws,pireusu,Î ÎµÎ¹ÏÎ±Î¹Î¬Ï,Î ÎµÎ¹ÏÎ±Î¹ÎµÏÏ,ÐÐ¸ÑÐµÐ¹,ÐÐ¸ÑÐµÑ,ÐÑÑÐµÐ¹,×¤××¨×××¡,Ø¨ÙØ±Ø§ÙÙØ³,ãã¬ã¦ã¹,æ¯é·åå¤«æ¯,Piraeus", :latitude => "37.94745", :longitude => "23.63708").save
City.new(:country_id => "91", :name => "Petroupolis", :aliases => "Kipoupolis,KipoÃºpolis,Petroupolis,ÐÐµÑÑÐ¾ÑÐ¿Ð¾Ð»Ð¸Ñ,PetroÃºpolis", :latitude => "38.04187", :longitude => "23.68494").save
City.new(:country_id => "91", :name => "Peristerion", :aliases => "Peristeri,Peristeri Attikes,Peristerion,PeristÃ©ri,PeristÃ©rion,Î ÎµÏÎ¹ÏÏÎ­ÏÎ¹ ÎÏÏÎ¹ÎºÎ®Ï,Î ÎµÏÎ¹ÏÏÎ­ÏÎ¹Î¿Î½,ÐÐµÑÐ¸ÑÑÐµÑÐ¸Ð¾Ð½,PeristÃ©rion", :latitude => "38.01667", :longitude => "23.7").save
City.new(:country_id => "91", :name => "Perama", :aliases => "Perama,PÃ©rama,Î Î­ÏÎ±Î¼Î±,ÐÐµÑÐ°Ð¼Ð°,PÃ©rama", :latitude => "37.96775", :longitude => "23.5721").save
City.new(:country_id => "91", :name => "Patrai", :aliases => "Patra,Patrae,Patrai,Patras,Patrasse,Patrasso,Patres,PatrÃ¡s,PÃ¡tra,PÃ¡trai,PÃ¡tras,pa te lei,patora,ptrs,Î Î¬ÏÏÎ±,Î Î¬ÏÏÎ±Î¹,Î Î±ÏÏÎ±Î¹,ÐÐ°ÑÑÐ°,×¤××¨×¡,ããã©,å¸ç¹é·,PÃ¡trai", :latitude => "38.24444", :longitude => "21.73444").save
City.new(:country_id => "91", :name => "Palaio Faliro", :aliases => "Alt Phaleron,Old Faliron,Palaio Faliro,Palaion Faliron,Palaion Phaleron,PalaiÃ³ FÃ¡liro,PalaiÃ³n FÃ¡liron,Î Î±Î»Î±Î¹Ï Î¦Î¬Î»Î·ÏÎ¿Î½,Î Î±Î»Î±Î¹ÏÎ½ Î¦Î¬Î»Î·ÏÎ¿Î½,PalaiÃ³ FÃ¡liro", :latitude => "37.92066", :longitude => "23.70916").save
City.new(:country_id => "91", :name => "Nikaia", :aliases => "Nea Kokkinia,Neokokinis,Nikaia,NÃ©a KokkiniÃ¡,NÃ­kaia,ÎÎ¯ÎºÎ±Î¹Î±,NÃ­kaia", :latitude => "37.96667", :longitude => "23.65").save
City.new(:country_id => "91", :name => "Nea Smirni", :aliases => "Nea Smirni,Nea Smyrne,NÃ©a SmÃ­rni,ÎÎ­Î± Î£Î¼ÏÏÎ½Î·,NÃ©a SmÃ­rni", :latitude => "37.95", :longitude => "23.71667").save
City.new(:country_id => "91", :name => "Nea Liosia", :aliases => "Ilion,Kato Liosia,KÃ¡to LiÃ³sia,Nea Liosia,NÃ©a LiÃ³sia,NÃ©a LiÃ³sia", :latitude => "38.03333", :longitude => "23.7").save
City.new(:country_id => "91", :name => "Nea Ionia", :aliases => "Nea Ionia,NÃ©a IonÃ­a,Podharadhes,PodharÃ¡dhes,ÎÎ­Î± ÎÏÎ½Î¯Î±,NÃ©a IonÃ­a", :latitude => "38.03333", :longitude => "23.75").save
City.new(:country_id => "91", :name => "Nea Filadhelfia", :aliases => "Filadelfia,Nea Filadhelfia,NÃ©a FiladhÃ©lfia,Podhoniftis,PodhonÃ­ftis,NÃ©a FiladhÃ©lfia", :latitude => "38.03333", :longitude => "23.73333").save
City.new(:country_id => "91", :name => "Nea Erithraia", :aliases => "Nea Erithraia,Nea Erythraia,NÃ©a ErithraÃ­a,ÎÎ­Î± ÎÏÏÎ¸ÏÎ±Î¯Î±,NÃ©a ErithraÃ­a", :latitude => "38.1", :longitude => "23.81667").save
City.new(:country_id => "91", :name => "Nafpaktos", :aliases => "Epakhtos,Inebahti,InebahtÄ±,Lepanto,Nafpaktos,Naupaetus,Navpaktos,NÃ¡fpaktos,NÃ¡vpaktos,aynh bhty,Ø§ÛÙÙ Ø¨Ø­ØªÛ,NÃ¡fpaktos", :latitude => "38.39167", :longitude => "21.8275").save
City.new(:country_id => "91", :name => "Moskhaton", :aliases => ",MoskhÃ¡ton", :latitude => "37.95", :longitude => "23.66667").save
City.new(:country_id => "91", :name => "Mytilini", :aliases => "Kastro,Mitilini,MitilÃ­ni,Mitylene,Mytilene,Mytilini,MytilÃ­ni,ÎÏÏÎ¹Î»Î®Î½Î·,ÐÐ¸ÑÐ¸Ð»Ð¸Ð½Ð¸,MytilÃ­ni", :latitude => "39.11", :longitude => "26.55472").save
City.new(:country_id => "91", :name => "Melissia", :aliases => "Melissia,Melissija,MelÃ­ssia,ÎÎµÎ»Î¯ÏÏÎ¹Î±,ÐÐµÐ»Ð¸ÑÑÐ¸Ñ,MelÃ­ssia", :latitude => "38.05", :longitude => "23.83333").save
City.new(:country_id => "91", :name => "Megara", :aliases => "Megara,Megare,MÃ©gara,MÃ©gare,megala,ÎÎ­Î³Î±ÏÎ±,ÐÐµÐ³Ð°ÑÐ°,ë©ê°ë¼,MÃ©gara", :latitude => "38", :longitude => "23.34556").save
City.new(:country_id => "91", :name => "Levadeia", :aliases => "Levadhia,LevÃ¡dhia,Livadeia,LivadeiÃ¡,LevÃ¡deia", :latitude => "38.435", :longitude => "22.87389").save
City.new(:country_id => "91", :name => "Larisa", :aliases => "Larisa,Larissa,LÃ¡risa,LÃ¡rissa,Yenisehir,YeniÅehir,ÎÎ¬ÏÎ¹ÏÎ±,ÐÐ°ÑÐ¸ÑÐ°,LÃ¡risa", :latitude => "39.63722", :longitude => "22.42028").save
City.new(:country_id => "91", :name => "Lamia", :aliases => "Izdin,Lamia,Lamija,LamÃ­a,lamya,ÎÎ±Î¼Î¯Î±,ÐÐ°Ð¼Ð¸Ñ,ÙØ§ÙÙÙØ§,LamÃ­a", :latitude => "38.9", :longitude => "22.43333").save
City.new(:country_id => "91", :name => "Kos", :aliases => "Coo,Kos,Poli Kos,PÃ³li Kos,ÐÐ¾Ñ,Kos", :latitude => "36.89333", :longitude => "27.28889").save
City.new(:country_id => "91", :name => "Koropi", :aliases => "Koropi,Koropion,KoropÃ­,KoropÃ­on,ÎÎ¿ÏÎ¿ÏÎ¯Î¿Î½,ÎÎ¿ÏÏÏÎ¯Î¿Î½,KoropÃ­", :latitude => "37.89886", :longitude => "23.87181").save
City.new(:country_id => "91", :name => "Corinth", :aliases => "Corint,Corinth,Corinthe,Corinthus,Corintia,Corinto,Korinf,Korint,Korinth,Korinthe,Korinthos,Korintti,Korynt,KÃ³rinthos,ke lin si,korintosu,qwryntws,ÎÏÏÎ¹Î½Î¸Î¿Ï,ÐÐ¾ÑÐ¸Ð½Ñ,ÐÐ¾ÑÑÐ½Ñ³Ñ,×§××¨×× ×ª××¡,ã³ãªã³ãã¹,ç§ææ¯,Corinth", :latitude => "37.94068", :longitude => "22.95734").save
City.new(:country_id => "91", :name => "Kifisia", :aliases => "Kefissia,Kephisia,Kifissia,KÄfissia,ÎÎ·ÏÎ¹ÏÎ¹Î¬,KifisiÃ¡", :latitude => "38.07438", :longitude => "23.81106").save
City.new(:country_id => "91", :name => "Kholargos", :aliases => "Cholargos,Holargos,Kholargos,KholargÃ³s,Î§Î¿Î»Î±ÏÎ³ÏÏ,KholargÃ³s", :latitude => "38", :longitude => "23.8").save
City.new(:country_id => "91", :name => "Chios", :aliases => "Castro,Chios,Chora,ChÃ³ra,Hios,Kastro,Kastron,Khios,Khora,KhÃ­os,KhÃ³ra,Quios,QuÃ­os,Sakiz,SakÄ±z,Scio,Xios,XÃ­os,el Xiu,ÎÎ¬ÏÏÏÎ¿,ÎÎ±ÏÏÏÎ¿,Î§Î¯Î¿Ï,Î§ÏÏÎ±,Î§ÏÏÎ±,Ð¥Ð¸Ð¾Ñ,ChÃ­os", :latitude => "38.36778", :longitude => "26.13583").save
City.new(:country_id => "91", :name => "Chania", :aliases => "Candia,Canea,Chania,Chanion,Cydonia,CÃ ndia,Hania,HaniÃ ,Hanya,Khan'ja,Khania,KhaniÃ¡,Kreta,La Canea,La Canee,La CanÃ©e,Ä¤ania,Î§Î±Î½Î¯ÏÎ½,Î§Î±Î½Î¹Î¬,Ð¥Ð°Ð½ÑÑ,ChaniÃ¡", :latitude => "35.51222", :longitude => "24.01556").save
City.new(:country_id => "91", :name => "Chalkida", :aliases => "Calcide,Calcis,Chalcis,Chalkida,Chalkis,ChalkÃ­da,ChalkÃ­s,Euripos,Khalkida,Khalkis,KhalkÃ­s,klqys,Î§Î±Î»ÎºÎ¯Î´Î±,Î§Î±Î»ÎºÎ¯Ï,Ð¥Ð°Ð»ÐºÐ¸Ð´Ð°,×××§××¡,ChalkÃ­da", :latitude => "38.46361", :longitude => "23.59944").save
City.new(:country_id => "91", :name => "Khalandrion", :aliases => "Chalandrion,Khalandhrion,Khalandri,KhalÃ¡ndhrion,KhalÃ¡ndri,Î§Î±Î»Î¬Î½Î´ÏÎ¹Î¿Î½,KhalÃ¡ndrion", :latitude => "38.03058", :longitude => "23.79793").save
City.new(:country_id => "91", :name => "Keratsinion", :aliases => "Ayios Yeoryios,Ayios Yeoryios Keratsiniou,Hagios Georgios Keratsiniou,Keratsini,Keratsinion,Keratsiniou,KeratsinÃ­ou,KeratsÃ­ni,KeratsÃ­nion,Ãyios YeÃ³ryios,ÎÎµÏÎ±ÏÏÎ¯Î½Î¹Î¿Î½,KeratsÃ­nion", :latitude => "37.9625", :longitude => "23.61972").save
City.new(:country_id => "91", :name => "Karditsa", :aliases => "Kardhitsa,KardhÃ­tsa,Kardica,Karditsa,KardiÃ§a,ka er ji cha,ÎÎ±ÏÎ´Î¯ÏÏÎ±,ÐÐ°ÑÐ´Ð¸ÑÐ°,å¡å°å­£å¯,KardÃ­tsa", :latitude => "39.36556", :longitude => "21.92167").save
City.new(:country_id => "91", :name => "Kallithea", :aliases => "Kallifeja,Kallithea,KallithÃ©a,ÎÎ±Î»Î»Î¹Î¸Î­Î±,ÐÐ°Ð»Ð»Ð¸ÑÐµÑ,KallithÃ©a", :latitude => "37.95", :longitude => "23.7").save
City.new(:country_id => "91", :name => "Kalamata", :aliases => "Kalamae,Kalamai,Kalamata,Kalamatas,Kalamato,KalamÃ¡ta,Kalmata,KalÃ¡mai,kalamata,ÎÎ±Î»Î¬Î¼Î±Î¹,ÎÎ±Î»Î±Î¼Î¬ÏÎ±,ÐÐ°Ð»Ð°Ð¼Ð°ÑÐ°,ÙØ§ÙØ§ÙØ§ØªØ§,KalamÃ¡ta", :latitude => "37.03889", :longitude => "22.11417").save
City.new(:country_id => "91", :name => "Kalamaki", :aliases => "Kalamaki,Kalamakion,KalamÃ¡ki,KalamÃ¡kion,ÎÎ±Î»Î±Î¼Î¬ÎºÎ¹Î¿Î½,KalamÃ¡ki", :latitude => "37.91033", :longitude => "23.72361").save
City.new(:country_id => "91", :name => "Kaisariani", :aliases => "Kaisariane,Kaisariani,KaisarianÃ­,Kesariani,ÎÎ±Î¹ÏÎ±ÏÎ¹Î±Î½Î®,ÐÐµÑÐ°ÑÐ¸Ð°Ð½Ð¸,KaisarianÃ­", :latitude => "37.96667", :longitude => "23.8").save
City.new(:country_id => "91", :name => "Iraklion", :aliases => ",IrÃ¡klion", :latitude => "38.06667", :longitude => "23.76667").save
City.new(:country_id => "91", :name => "Irakleion", :aliases => "Candia,Candie,CandÃ­a,CÃ ndia,Erakleio,Erakleion,Heracleum,Heracliao,HeracliÃ£o,Herakleion,Heraklion,HerÃ¡kleion,HÃ©raklion,Iraclion,Irakleio,Irakleion,Iraklija,Iraklio,Iraklion,IrÃ¡kleio,IrÃ¡kleion,IrÃ¡klio,IrÃ¡klion,Kandiye,Khandax,Megalokastro,Megalokastron,hrqlywn,irakurion,yi la ke li weng,Ärakleion,ÎÏÎ¬ÎºÎ»ÎµÎ¹Î¿,ÐÑÐ°ÐºÐ»Ð¸Ð¾Ð½,××¨×§××××,ã¤ã©ã¯ãªãªã³,ä¼æåå©ç¿,IrÃ¡kleion", :latitude => "35.32787", :longitude => "25.14341").save
City.new(:country_id => "91", :name => "Ioannina", :aliases => "Giannina,Ioaa,Ioanina,Ioannina,IoÃ¡nnina,IoÃ¤a,Janina,Yanina,Yannina,Yanya,yue a ni na,ÎÏÎ¬Î½Î½Î¹Î½Î±,Ð¯Ð½Ð¸Ð½Ð°,çº¦é¿å°¼çº³,IoÃ¡nnina", :latitude => "39.6675", :longitude => "20.85083").save
City.new(:country_id => "91", :name => "Galatsion", :aliases => "Galatsi,Galatsion,GalÃ¡tsi,GalÃ¡tsion,ÎÎ±Î»Î¬ÏÏÎ¹Î¿Î½,GalÃ¡tsion", :latitude => "38.01667", :longitude => "23.75").save
City.new(:country_id => "91", :name => "Ellinikon", :aliases => "Ellenikon,Elliniko,Ellinikon,EllinikÃ³,EllinikÃ³n,ÎÎ»Î»Î·Î½Î¹ÎºÏÎ½,EllinikÃ³n", :latitude => "37.88333", :longitude => "23.73333").save
City.new(:country_id => "91", :name => "Elefsina", :aliases => "Elefis,Elefsina,Elefsis,ElefsÃ­na,ElefsÃ­s,Eleusis,Elevsis,ElevsÃ­s,Lepsina,ÎÎ»ÎµÏÏÎ¯Ï,ElefsÃ­na", :latitude => "38.04135", :longitude => "23.54295").save
City.new(:country_id => "91", :name => "Ayia Varvara", :aliases => "Agia Barbara,Ayia Varvara,AyÃ­a VarvÃ¡ra,ÎÎ³Î¯Î± ÎÎ±ÏÎ²Î¬ÏÎ±,AyÃ­a VarvÃ¡ra", :latitude => "37.98333", :longitude => "23.66667").save
City.new(:country_id => "91", :name => "Ayia Paraskevi", :aliases => "Agia Paraskeue,Ayia Paraskevi,AyÃ­a ParaskevÃ­,ÎÎ³Î¯Î± Î Î±ÏÎ±ÏÎºÎµÏÎ®,AyÃ­a ParaskevÃ­", :latitude => "38.01667", :longitude => "23.83333").save
City.new(:country_id => "91", :name => "Athens", :aliases => "Afina,Afini,Afiny,An Aithin,Ateena,Atehny,Aten,Atena,Atenai,Atenas,Atenas - Athena,Atenas - ÎÎ¸Î®Î½Î±,Atene,Atenes,Ateni,Ateno,Atenoj,Ateny,Athen,Athena,Athenae,Athenai,Athene,Athenes,Athens,Atheny,Athina,Athinai,Athinia,AthÃ¨nes,AthÃ©n,AthÃ©nes,AthÃ©ny,AthÃ­na,AthÃ­nai,Atina,AtÃ©ny,AtÄnas,AtÄnai,AÃ¾ena,Kota Athena,Lungsod ng Athina,Lungsod ng AthÃ­na,atene,atene si,ateni,athensa,athyna,atn,etens,xethens,ya dian,ÎÎ¸Î®Î½Î±,ÎÎ¸Î®Î½Î±Î¹,ÎÎ¸Î·Î½Î±,ÎÎ¸Î·Î½Î±Î¹,ÐÑÐ¸Ð½Ð°,ÐÑÑÐ½Ñ,ÐÑÐ¸Ð½Ñ,ÐÑÑÐ½Ð¸,ÐÑ³Ð¸Ð½Ñ,Ô±Õ©Õ¥Õ¶Ö,××ª×× ×,Ø¢ØªÙ,Ø£Ø«ÙÙØ§,Ø¦Ø§ÙÛÙØ§,ÜÜ¬ÜÜ¢Ü,à¤à¤¥à¥à¤¨à¥à¤¸,à®à®¤à¯à®©à¯à®¸à¯,à¹à¸­à¹à¸à¸à¸ªà¹,ááááá,ã¢ãã,éå¸,ìíë¤,ìíë¤ ì,Athens", :latitude => "37.97945", :longitude => "23.71622").save
City.new(:country_id => "91", :name => "Aspropirgos", :aliases => "Aspropirgos,Aspropyrgos,AsprÃ³pirgos,Kalivia,Kalivia Khasias,KalÃ­via,KalÃ­via KhasiÃ¡s,ÎÏÏÏÏÏÏÏÎ³Î¿Ï,AsprÃ³pirgos", :latitude => "38.06667", :longitude => "23.58333").save
City.new(:country_id => "91", :name => "Arta", :aliases => "Arta,arta,Ãrta,ÎÏÏÎ±,ÐÑÑÐ°,Ø¢Ø±ØªØ§,Ãrta", :latitude => "39.16056", :longitude => "20.98528").save
City.new(:country_id => "91", :name => "Argos", :aliases => "Argas,Argo,Argos,Ciutat d'Argos,a ge si,Ãrgos,ÎÏÎ³Î¿Ï,ÐÑÐ³Ð¾Ñ,××¨×××¡,é¿ææ¯,Ãrgos", :latitude => "37.63333", :longitude => "22.73333").save
City.new(:country_id => "91", :name => "Ano Liosia", :aliases => "Ano Liosia,Ãno LiÃ³sia,ÎÎ½Ï ÎÎ¹ÏÏÎ¹Î±,Ãno LiÃ³sia", :latitude => "38.08333", :longitude => "23.7").save
City.new(:country_id => "91", :name => "Amarousion", :aliases => "Amarousion,AmaroÃºsion,ÎÎ¼Î±ÏÎ¿ÏÏÎ¹Î¿Î½,AmaroÃºsion", :latitude => "38.05", :longitude => "23.8").save
City.new(:country_id => "91", :name => "Amalias", :aliases => "Amaliada,Amalias,AmaliÃ¡da,AmaliÃ¡s,ÎÎ¼Î±Î»Î¹Î¬Ï,AmaliÃ¡s", :latitude => "37.8", :longitude => "21.35").save
City.new(:country_id => "91", :name => "Akharnai", :aliases => "Acharnae,Acharnai,Acharne,Akharnai,AkharnaÃ­,Menidhi,Menidhion,Menidi,Menioi,MenÃ­dhi,MenÃ­dhion,MenÃ­oi,ÎÏÎ±ÏÎ½Î±Î¯,AkharnaÃ­", :latitude => "38.08333", :longitude => "23.73333").save
City.new(:country_id => "91", :name => "Aigion", :aliases => "Aegion,Aegium,Aighion,Aigio,Aigion,Aiyion,AÃ­gio,AÃ­gion,AÃ­yion,Egion,Ehjo,Vostitsa,Vostitza,Vostizza,VostÃ­tsa,ÎÎ¯Î³Î¹Î¿Î½,Ð­Ð¹Ð¾,AÃ­gion", :latitude => "38.24861", :longitude => "22.08194").save
City.new(:country_id => "91", :name => "Aigaleo", :aliases => "Aegaleo,Aigaleo,AigÃ¡leo,ÎÎ¹Î³Î¬Î»ÎµÏ,AigÃ¡leo", :latitude => "37.98333", :longitude => "23.68333").save
City.new(:country_id => "91", :name => "Agrinion", :aliases => "Agrinio,Agrinion,Agrinium,AgrÃ­nio,AgrÃ­nion,ÎÎ³ÏÎ¯Î½Î¹Î¿,ÎÎ³ÏÎ¯Î½Î¹Î¿Î½,ÐÐ³ÑÐ¸Ð½Ð¸Ð¾Ð½,AgrÃ­nion", :latitude => "38.62139", :longitude => "21.40778").save
City.new(:country_id => "91", :name => "Rodos", :aliases => "Rhodes,Rhodos,Rodas,Rodes,Rodhos,Rodi,Rodos,RÃ³dhos,Î¡ÏÎ´Î¿Ï,Ð Ð¾Ð´Ð¾Ñ,RÃ³dos", :latitude => "36.44083", :longitude => "28.2225").save
City.new(:country_id => "91", :name => "Giannitsa", :aliases => "Giannitsa,GiannitsÃ¡,Janica,Yannitsa,Yenitsa,YenitsÃ¡,Yiannitsa,YiannitsÃ¡,ÎÎ¹Î±Î½Î½Î¹ÏÏÎ¬,Ð¯Ð½Ð¸ÑÐ°,GiannitsÃ¡", :latitude => "40.79194", :longitude => "22.4075").save
City.new(:country_id => "91", :name => "Xanthi", :aliases => "Eskije,Ksanti,Xanthe,XanthÄ,ÎÎ¬Î½Î¸Î·,ÐÑÐ°Ð½ÑÐ¸,XÃ¡nthi", :latitude => "41.14139", :longitude => "24.88361").save
City.new(:country_id => "91", :name => "Veroia", :aliases => "Beroia,Verija,Verroia,VÃ©rroia,ÎÎ­ÏÎ¿Î¹Î±,ÐÐµÑÐ¸Ñ,VÃ©roia", :latitude => "40.52333", :longitude => "22.20361").save
City.new(:country_id => "91", :name => "Thessaloniki", :aliases => "Ftohomana,FtohomÃ¡na,I Protevoussa ton Prosfigon,I ProtÃ©voussa ton ProsfÃ­gon,Lungsod ng Thessaloniki,Lungsod ng ThessalonÃ­ki,Salonic,Salonica,Salonicco,Salonik,Salonika,Salonikai,Salonike,Saloniki,Salonique,SalonÃ­ki,Saluniccu,SalÃ³nica,Saruna,Selanik,Selun',SelÃ¢nik,Solun,SoluÅ,SolÃºn,SÄruna,THessalonika,Tesalonica,TesalÃ³nica,Tessalonica,TessalÃ²nica,Thessalonica,Thessalonike,Thessaloniki,Thessalonique,ThessalonÃ­ki,ThessalonÃ­kÄ,sai sa luo ni ji,salwnyk,slwnyqh,slwnyqy,tessaroniki,ÃessalÃ³nÃ­ka,ÎÎµÏÏÎ±Î»Î¿Î½Î¯ÎºÎ·,Î£Î±Î»Î¿Î½Î¯ÎºÎ·,Î£Î±Î»Î¿Î½Î¹ÎºÎ·,Ð¡Ð°Ð»Ð¾Ð½Ð¸ÐºÐ¸,Ð¡Ð°Ð»Ð¾Ð½ÑÐºÐ¸,Ð¡ÐµÐ»ÑÐ½Ñ,Ð¡Ð¾Ð»ÑÐ½,×¡××× ××§×,×¡××× ××§×,Ø³Ø§ÙÙÙÙÙ,ãããµã­ãã­,å¡è¨æ´å°¼åº,ThessalonÃ­ki", :latitude => "40.64028", :longitude => "22.94389").save
City.new(:country_id => "91", :name => "Sykeai", :aliases => "Sikeai,SikÃ©ai,Sykeai,SykÃ©ai,SykÃ©ai", :latitude => "40.64944", :longitude => "22.95083").save
City.new(:country_id => "91", :name => "Serres", :aliases => "Ser,Seres,Serez,Serra,Serrae,Serrai,Serres,SerrÃ¨s,Sjar,SÃ©rrai,SÃ©rres,Î£Î­ÏÏÎ±,Î£Î­ÏÏÎ±Î¹,Î£Î­ÏÏÎµÏ,Ð¡ÐµÑ,Ð¡ÑÑ,SÃ©rres", :latitude => "41.08556", :longitude => "23.54972").save
City.new(:country_id => "91", :name => "Ptolemais", :aliases => "Kailar,Kailaria,Kajlar,Kajljari,Kayilar,KayÄ±lar,KaÃ¯lÃ¡ria,Ptolemaida,Ptolemaidha,Ptolemais,Ptolemak,Ptolemaá¸¯da,Ptolemaá¸¯s,Î ÏÎ¿Î»ÎµÎ¼Î±ÎÎ´Î±,ÐÐ°Ð¹Ð»ÑÑÐ¸,ÐÐ°ÑÐ»Ð°Ñ,ÐÑÐ¾Ð»ÐµÐ¼Ð°Ð¸Ð´Ð°,Ptolemaá¸¯s", :latitude => "40.51472", :longitude => "21.67861").save
City.new(:country_id => "91", :name => "Polichni", :aliases => "Karaisin,KaraÃ¯sÃ­n,Polikhni,PolÃ­khni,ÐÐ¾Ð»Ð¸ÑÐ½Ð¸,PolÃ­chni", :latitude => "40.66671", :longitude => "22.94881").save
City.new(:country_id => "91", :name => "Pylaia", :aliases => "Kapoutsidhes,KapoutsÃ­dhes,Pilaia,PilaÃ­a,Pilea,Pylaia,PylaÃ­a,Strefa,StrÃ©fa,ÐÐ¸Ð»ÐµÐ°,PylaÃ­a", :latitude => "40.60056", :longitude => "22.9875").save
City.new(:country_id => "91", :name => "Peraia", :aliases => "Peraia,Î ÎµÏÎ±Î¯Î±,PeraÃ­a", :latitude => "40.50028", :longitude => "22.925").save
City.new(:country_id => "91", :name => "Panorama", :aliases => "Arsakli,ArsaklÃ­,Panorama,PanÃ³rama,Î Î±Î½ÏÏÎ±Î¼Î±,PanÃ³rama", :latitude => "40.58779", :longitude => "23.0315").save
City.new(:country_id => "91", :name => "Orestias", :aliases => "Nea Orestias,NÃ©a OrestiÃ¡s,Orestiada,Orestias,OrestiÃ¡da,OrestiÃ¡s,ÎÏÎµÏÏÎ¹Î¬Ï,OrestiÃ¡s", :latitude => "41.50306", :longitude => "26.52972").save
City.new(:country_id => "91", :name => "Oraiokastron", :aliases => "Dautbali,DaÃ¼tbalÃ­,Oraiokastro,Oraiokastron,OraiÃ³kastro,Oreorastron,Î©ÏÎ±Î¹ÏÎºÎ±ÏÏÏÎ¿Î½,OraiÃ³kastron", :latitude => "40.73083", :longitude => "22.91722").save
City.new(:country_id => "91", :name => "Naousa", :aliases => "Naousa,NÃ¡ousa,ÎÎ¬Î¿ÏÏÎ±,NÃ¡ousa", :latitude => "40.62944", :longitude => "22.06806").save
City.new(:country_id => "91", :name => "Menemeni", :aliases => "Menemeni,MenemÃ©ni,Nea Mainemeni,Nea Manemeni,NÃ©a MainemÃ©ni,MenemÃ©ni", :latitude => "40.65694", :longitude => "22.9").save
City.new(:country_id => "91", :name => "Kozani", :aliases => "Kozane,Kozani,Kozhani,KozÃ¡ni,ÎÎ¿Î¶Î¬Î½Î·,ÐÐ¾Ð¶Ð°Ð½Ð¸,ÐÐ¾Ð·Ð°Ð½Ð¸,KozÃ¡ni", :latitude => "40.30111", :longitude => "21.78639").save
City.new(:country_id => "91", :name => "Komotini", :aliases => "Gjumjurdzhina,Guemuelcine,Gumulcine,Gumuljina,GumuljÃ­na,GÃ¼mÃ¼lcine,Komotene,Komotina,Komotine,Komotini,KomotinÃ­,KomotinÄ,KomotÄnÄ,ÎÎ¿Î¼Î¿ÏÎ·Î½Î®,ÐÑÐ¼ÑÑÐ´Ð¶Ð¸Ð½Ð°,KomotinÃ­", :latitude => "41.12278", :longitude => "25.39639").save
City.new(:country_id => "91", :name => "Kilkis", :aliases => "Kilkis,KilkÃ­s,Kukush,Nomos Kilkis,Prefectura Kilkis,Prefektura Kukush,ÎÎ¹Î»ÎºÎ¯Ï,ÎÎ¿Î¼ÏÏ ÎÎ¹Î»ÎºÎ¯Ï,ÐÑÐºÑÑ,ÐÑÐµÑÐµÐºÑÑÑÐ° ÐÑÐºÑÑ,KilkÃ­s", :latitude => "40.99194", :longitude => "22.87083").save
City.new(:country_id => "91", :name => "Kavala", :aliases => "Cavala,Cavalla,Kabala,Kaballa,Kavala,Kavalla,KavÃ¡la,KavÃ¡lla,Kawala,Neapolis,ka wa la,qwlt,ÎÎ±Î²Î¬Î»Î±,ÐÐ°Ð²Ð°Ð»Ð°,ÙÙÙØ©,å¡ç¦æ,KavÃ¡la", :latitude => "40.93972", :longitude => "24.40194").save
City.new(:country_id => "91", :name => "Katerini", :aliases => "Aikaterini,AikaterÃ­ni,Katerina,Katerine,Katerini,ÎÎ±ÏÎµÏÎ¯Î½Î·,ÐÐ°ÑÐµÑÐ¸Ð½Ð¸,KaterÃ­ni", :latitude => "40.27194", :longitude => "22.5025").save
City.new(:country_id => "91", :name => "Kalamaria", :aliases => "Kalamaria,Kalamarija,KalamariÃ¡,Kalamarya,ÎÎ±Î»Î±Î¼Î±ÏÎ¹Î¬,ÐÐ°Ð»Ð°Ð¼Ð°ÑÐ¸Ñ,KalamariÃ¡", :latitude => "40.5825", :longitude => "22.95028").save
City.new(:country_id => "91", :name => "Florina", :aliases => "Florina,Follorina,Lerin,Phlorina,Plorina,lerin,Î¦Î»ÏÏÎ¹Î½Î±,ÐÐµÑÐ¸Ð½,FlÃ³rina", :latitude => "40.78197", :longitude => "21.40981").save
City.new(:country_id => "91", :name => "Edessa", :aliases => "Edessa,Edhessa,Voden,Vodena,VodenÃ¡,Ãdessa,Ãdhessa,ÎÎ´ÎµÏÏÎ±,ÐÐ¾Ð´ÐµÐ½,Ãdessa", :latitude => "40.80056", :longitude => "22.04722").save
City.new(:country_id => "91", :name => "Drama", :aliases => "Dhrama,DhrÃ¡ma,Drama,dhrama,drama,drmh,ÎÏÎ¬Î¼Î±,ÐÑÐ°Ð¼Ð°,××¨××,Ø°Ø±Ø§ÙØ§,DrÃ¡ma", :latitude => "41.15444", :longitude => "24.13944").save
City.new(:country_id => "91", :name => "Alexandroupolis", :aliases => "Alejandropolis,AlejandrÃ³polis,Aleksandrupolis,Alessandropoli,Alexandhroupolis,AlexandhroÃºpolis,Alexandropolis,Alexandroupole,Alexandroupoli,Alexandroupolis,AlexandroÃºpoli,Dedeagac,Dedeagach,DedeaÄaÃ§,DedÃ©agach,alyksandrwbwly,ÎÎ»ÎµÎ¾Î±Î½Î´ÏÎ¿ÏÏÎ¿Î»Î·,ÐÐ»ÐµÐºÑÐ°Ð½Ð´ÑÑÐ¿Ð¾Ð»Ð¸Ñ,ÐÐµÐ´ÐµÐ°Ð³Ð°Ñ,Ø£ÙÙÙØ³Ø§ÙØ¯Ø±ÙØ¨ÙÙÙ,AlexandroÃºpolis", :latitude => "40.8475", :longitude => "25.87444").save
City.new(:country_id => "91", :name => "Kerkyra", :aliases => "Corcyra,Corfou,Corfu,Kerkira,Kerkyra,Korfu,Krf,KÃ©rkira,KÃ©rkyra,kerkira,ÎÎ­ÏÎºÏÏÎ±,ÐÐ¾ÑÑÑ,ÐÑÑ,KÃ©rkyra", :latitude => "39.62", :longitude => "19.91972").save
City.new(:country_id => "91", :name => "Vrilissia", :aliases => ",Vrilissia", :latitude => "38.03381", :longitude => "23.82962").save
City.new(:country_id => "91", :name => "Alimos", :aliases => "Alimos,ÐÐ»Ð¸Ð¼Ð¾Ñ,Alimos", :latitude => "37.91667", :longitude => "23.71667").save
City.new(:country_id => "91", :name => "Mesolongi", :aliases => ",ÎÎµÏÎ¿Î»ÏÎ³Î³Î¹", :latitude => "38.37019", :longitude => "21.42952").save
City.new(:country_id => "91", :name => "Marousi", :aliases => "Amaroussion,amarousion,amaroussio,maroussi,Marousi", :latitude => "38.05404", :longitude => "23.806").save
