City.new(:country_id => "100", :name => "Zapresic", :aliases => "Zapresic,ZapreÅ¡iÄ,ZapreÅ¡iÄ", :latitude => "45.85639", :longitude => "15.80778").save
City.new(:country_id => "100", :name => "Zagreb", :aliases => "Agram,Andautonia,Zabrag,Zabreg,Zagabria,Zagrab,Zagrabia,Zagreb,Zagreba,Zagrebas,Zagrebi,Zagrebo,Zagrehb,Zagrep,Zagrzeb,Zahreb,Zankremp,ZÃ¡grÃ¡b,ZÃ¡hreb,ZÃ¡hÅeb,jagareba,jageulebeu,sa ge lei bu,sa kerb,zagrebi,zagurebu,zghrb,ÎÎ¬Î³ÎºÏÎµÎ¼Ï,ÐÐ°Ð³ÑÐµÐ±,ÐÐ°Ð³ÑÑÐ±,××××¨×,Ø²ØºØ±Ø¨,à¦à¦¾à¦à¦°à§à¦¬,à¸à¸²à¹à¸à¸£à¹à¸,áááá ááá,ááá¬á¥,ã¶ã°ã¬ã,è¨æ ¼åå¸,ìê·¸ë ë¸,Zagreb", :latitude => "45.81444", :longitude => "15.97798").save
City.new(:country_id => "100", :name => "Zadar", :aliases => "Zadar,Zadara,Zadaras,Zantar,Zara,ZÃ¡ra,jadaleu,zadaru,ÎÎ±Î½ÏÎ¬Ï,ÐÐ°Ð´Ð°Ñ,ã¶ãã«,ìë¤ë¥´,Zadar", :latitude => "44.11972", :longitude => "15.24222").save
City.new(:country_id => "100", :name => "Vukovar", :aliases => "Neo-Vukovar,Novi Vukovar,Ovukovar,Stari Vukovar,Ujvukovar,Valko,Valkovar,ValkÃ³,ValkÃ³vÃ¡r,Vetus-Vukovar,Vukovar,Vukovaras,VukovÃ¡r,Wukowar,vukovu~aru,ÃvukovÃ¡r,ÃjvukovÃ¡r,ÐÑÐºÐ¾Ð²Ð°Ñ,ã´ã³ã´ã¡ã«,Vukovar", :latitude => "45.34333", :longitude => "18.99972").save
City.new(:country_id => "100", :name => "Virovitica", :aliases => "Sesta,Veroce,Verocze,VerÃ¶cze,VerÅce,Virovitica,Virovitisa,Weretz,Werowititz,ÐÐ¸ÑÐ¾Ð²Ð¸ÑÐ¸ÑÐ°,Virovitica", :latitude => "45.83194", :longitude => "17.38389").save
City.new(:country_id => "100", :name => "Vinkovci", :aliases => "Cibalae,Vinkovce,Vinkovci,Vinkovcze,Winkowitz,Winkowzi,ÐÐ¸Ð½ÐºÐ¾Ð²ÑÐ¸,Vinkovci", :latitude => "45.28833", :longitude => "18.80472").save
City.new(:country_id => "100", :name => "Velika Gorica", :aliases => "Nagygorica,Nagygoricza,Velika Gorica,ÐÐµÐ»Ð¸ÐºÐ° ÐÐ¾ÑÐ¸ÑÐ°,Velika Gorica", :latitude => "45.7125", :longitude => "16.07556").save
City.new(:country_id => "100", :name => "Varazdin", :aliases => "Aqua Viva,Varasd,Varasdino,Varasdinum,Varazdin,Varazhdin,VaraÅ¾din,Waraschdin,Warasdin,ÐÐ°ÑÐ°Ð¶Ð´Ð¸Ð½,VaraÅ¾din", :latitude => "46.30444", :longitude => "16.33778").save
City.new(:country_id => "100", :name => "Split", :aliases => "Spalato,Spalatum,Split,Splita,Splitas,si pu li te,splyt,supurito,Î£ÏÎ»Î¹Ï,Ð¡Ð¿Ð»Ð¸Ñ,×¡×¤×××,ã¹ããªã,æ¯æ®å©ç¹,Split", :latitude => "43.50891", :longitude => "16.43915").save
City.new(:country_id => "100", :name => "Solin", :aliases => "Salona,Solin,Ð¡Ð¾Ð»Ð¸Ð½,Solin", :latitude => "43.55", :longitude => "16.5").save
City.new(:country_id => "100", :name => "Slavonski Brod", :aliases => "Brod,BrÃ³d,Marsonia,Slavonski Brod,Slavonski brod,Slawonisch Brod,Ð¡Ð»Ð°Ð²Ð¾Ð½ÑÐºÐ¸ ÐÑÐ¾Ð´,Ð¡Ð»Ð°Ð²Ð¾Ð½ÑÐºÐ¸ Ð±ÑÐ¾Ð´,Slavonski Brod", :latitude => "45.16028", :longitude => "18.01556").save
City.new(:country_id => "100", :name => "Pozega", :aliases => "Poschega,Poschegg,Posega,Pozega,Pozhega,Pozsega,Pozsegavar,PozsegavÃ¡r,PoÅ¾ega,Slavonska Pozega,Slavonska PoÅ¾ega,pwzhhghh,ÐÐ¾Ð¶ÐµÐ³Ð°,Ù¾ÙÚÙØºÙ,PoÅ¾ega", :latitude => "45.34028", :longitude => "17.68528").save
City.new(:country_id => "100", :name => "Sisak", :aliases => "Segesta,Sisak,Siscia,Sisseg,Sissek,Sziszek,Ð¡Ð¸ÑÐ°Ðº,Sisak", :latitude => "45.46611", :longitude => "16.37833").save
City.new(:country_id => "100", :name => "Sibenik", :aliases => "Sebenico,Shibenik,Sibenik,shibeniku,Å ibenik,Ð¨Ð¸Ð±ÐµÐ½Ð¸Ðº,ã·ããã¯,Å ibenik", :latitude => "43.72722", :longitude => "15.90583").save
City.new(:country_id => "100", :name => "Sesvete", :aliases => "Sesvete,Ð¡ÐµÑÐ²ÐµÑÐµ,Sesvete", :latitude => "45.83111", :longitude => "16.11639").save
City.new(:country_id => "100", :name => "Samobor", :aliases => "Samobor,Szamobor,Ð¡Ð°Ð¼Ð¾Ð±Ð¾Ñ,Samobor", :latitude => "45.80306", :longitude => "15.71806").save
City.new(:country_id => "100", :name => "Rijeka", :aliases => "Estado libre de Fiume,Fiume,Fkumen,Flumen Sancti Viti,Reka,Rieka,Rijeka,Rijeko,RÄka,Sankt Veit am Flaum,Sankt Veit am Pflaum,Slobodna Drzava Rijeka,Slobodna Drzhava Rijeka,Slobodna DrÅ¾ava Rijeka,Stato libero di Fiume,Vitipolis,rieka,Ð Ð¸ÐµÐºÐ°,Ð Ð¸ÑÐµÐºÐ°,Ð¡Ð»Ð¾Ð±Ð¾Ð´Ð½Ð° ÐÑÐ¶Ð°Ð²Ð° Ð Ð¸ÑÐµÐºÐ°,ãªã¨ã«,Rijeka", :latitude => "45.34306", :longitude => "14.40917").save
City.new(:country_id => "100", :name => "Pula", :aliases => "Pluj,Pola,PoÅa,Pula,Pulj,pu la,pura,ÐÑÐ»Ð°,ãã¼ã©,æ®æ,Pula", :latitude => "44.86833", :longitude => "13.84806").save
City.new(:country_id => "100", :name => "Osijek", :aliases => "Colonia Aelia Mursa,Esseg,Essegg,Essek,Eszek,EszÃ©k,Mursa,Mursia,Osek,Osiek,Osigiek,Osijek,Osijeka,Osijekas,Osik,oshieku,xo siyekh,ÎÏÎ¹Î³Î¹Î­Îº,ÐÑÐ¸ÐµÐº,ÐÑÐ¸ÑÐµÐº,à¹à¸­à¸à¸µà¹à¸¢à¸,ãªã·ã¨ã¯,Osijek", :latitude => "45.55111", :longitude => "18.69389").save
City.new(:country_id => "100", :name => "Koprivnica", :aliases => "Caprontza,Kapronca,Kaproncza,Kopreinitz,Koprivnica,Koprivnicza,Kopriwnitza,ÐÐ¾Ð¿ÑÐ¸Ð²Ð½Ð¸ÑÐ°,Koprivnica", :latitude => "46.16278", :longitude => "16.8275").save
City.new(:country_id => "100", :name => "Karlovac", :aliases => "Karlovac,Karlstadt,Karolyvaros,KarolyvÃ¡ros,KÃ¡rolyvÃ¡ros,ÐÐ°ÑÐ»Ð¾Ð²Ð°Ñ,Karlovac", :latitude => "45.48722", :longitude => "15.54778").save
City.new(:country_id => "100", :name => "Dubrovnik", :aliases => "Communitas Ragusina,Dubrava,Dubrounik,Dubrovacka Republika,DubrovaÄka Republika,Dubrovnik,Dubrovnikas,DubrovnÃ­k,Dubrownik,DÃ¹brÅvnik,Laus,Pearl of the Adriatic,Ragusa,Repubblica di Ragusa,Republic of Ragusa,Respublica Ragusina,do~uburovuniku,du bu luo fu ni ke,dwbrwbnyq,la perla del Adriatico,la perla del AdriÃ¡tico,ÐÑÐ±ÑÐ¾Ð²Ð½Ð¸Ðº,ÐÑÐ±ÑÐ¾ÑÐ½ÑÐº,××××¨××× ××§,ãã¥ãã­ã´ãã¯,æå¸ç¾å¤«å°¼å,Dubrovnik", :latitude => "42.64807", :longitude => "18.09216").save
City.new(:country_id => "100", :name => "Cakovec", :aliases => "Cakovec,Chakovec,Csakathurn,Csaktornya,CsÃ¡ktornya,Äakovec,Ð§Ð°ÐºÐ¾Ð²ÐµÑ,Äakovec", :latitude => "46.38444", :longitude => "16.43389").save
City.new(:country_id => "100", :name => "Bjelovar", :aliases => "Belavar,Bellovar,Belovar,BelovÃ¡r,Belowar,Bjelovar,BÃ©lavÃ¡r,ÐÐµÐ»Ð¾Ð²Ð°Ñ,Bjelovar", :latitude => "45.89861", :longitude => "16.84889").save
City.new(:country_id => "100", :name => "Zagreb - Centar", :aliases => ",Zagreb - Centar", :latitude => "45.81313", :longitude => "15.97753").save
