City.new(:country_id => "102", :name => "Torokszentmiklos", :aliases => "Toroksentmiklosh,Torokszenimiklos,Torokszentmiklos,TÃ¶rÃ¶kszenimiklÃ³s,TÃ¶rÃ¶kszentmiklÃ³s,Ð¢Ð¾ÑÐ¾ÐºÑÐµÐ½ÑÐ¼Ð¸ÐºÐ»Ð¾Ñ,TÃ¶rÃ¶kszentmiklÃ³s", :latitude => "47.18333", :longitude => "20.41667").save
City.new(:country_id => "102", :name => "Tiszaujvaros", :aliases => "Leninvaros,LeninvÃ¡ros,Tiszaszederken,Tiszaszederkeny,TiszaszederkÃ©ny,Tiszaujvaros,TiszaÃºjvÃ¡ros,TiszaÃºjvÃ¡ros", :latitude => "47.93333", :longitude => "21.08333").save
City.new(:country_id => "102", :name => "Szolnok", :aliases => "Sol'nok,Szolnok,Ð¡Ð¾Ð»ÑÐ½Ð¾Ðº,Szolnok", :latitude => "47.18333", :longitude => "20.2").save
City.new(:country_id => "102", :name => "Szentes", :aliases => ",Szentes", :latitude => "46.65", :longitude => "20.26667").save
City.new(:country_id => "102", :name => "Szeged", :aliases => "Algyo,AlgyÅ,Gyala,Gyalaret,GyÃ¡la,GyÃ¡larÃ©t,Kiskundorozsma,Seged,Segedin,Seghedin,Szegedin,Szeghed,Szoreg,SzÅreg,Tape,TÃ¡pÃ©,skdyn,Ð¡ÐµÐ³ÐµÐ´,Ø³Ú©Ø¯ÛÙ,Szeged", :latitude => "46.253", :longitude => "20.14824").save
City.new(:country_id => "102", :name => "Szarvas", :aliases => "Sarvas,Sarvash,SarvaÅ¡,Szarvas,sarwash,Ð¡Ð°ÑÐ²Ð°Ñ,ØµØ§Ø±ÙØ§Ø´,Szarvas", :latitude => "46.86667", :longitude => "20.55").save
City.new(:country_id => "102", :name => "Satoraljaujhely", :aliases => "Karolyfalva,KÃ¡rolyfalva,Nove Mesto Pod Siatrom,NovÃ© Mesto Pod Å iatrom,Rudabanyacska,RudabÃ¡nyÃ¡cska,Satoraijaujhely,Satoraljaujhely,Szephalom,SzÃ©phalom,SÃ¡toraljaÃºjhely,Ujhely,Ãjhely,SÃ¡toraljaÃºjhely", :latitude => "48.4", :longitude => "21.66667").save
City.new(:country_id => "102", :name => "Puspokladany", :aliases => "Puspokladany,PÃ¼spÃ¶kladÃ¡ny,PÃ¼spÃ¶kladÃ¡ny", :latitude => "47.31667", :longitude => "21.11667").save
City.new(:country_id => "102", :name => "Ozd", :aliases => "Bolyok,Center,Hodoscsepany,HodoscsÃ©pÃ¡ny,Ozd,Sajovarkony,SajÃ³vÃ¡rkony,Susa,Szentsimon,Uraj,Ãzd,ÐÐ·Ð´,Ãzd", :latitude => "48.21667", :longitude => "20.3").save
City.new(:country_id => "102", :name => "Oroshaza", :aliases => "Oroshaza,Oroshazi,Oroshkhaza,OroshÃ¡za,OroshÃ¡zi,ÐÑÐ¾ÑÑÐ°Ð·Ð°,OroshÃ¡za", :latitude => "46.56667", :longitude => "20.66667").save
City.new(:country_id => "102", :name => "Nyiregyhaza", :aliases => "N'ired'khaza,Nyirszollos,Nyirszolos,NyÃ­rszÅllÅs,NyÃ­rszÅlÅs,Oros,ÐÑÐ¸ÑÐµÐ´ÑÑÐ°Ð·Ð°,NyÃ­regyhÃ¡za", :latitude => "47.95539", :longitude => "21.71671").save
City.new(:country_id => "102", :name => "Miskolc", :aliases => "Bukkszentlaszlo,BÃ¼kkszentlÃ¡szlÃ³,Mishkol'c,Mishkolc,Miskolc,Miskolca,Miskolcz,Miskole,Miszkolc,MiÅ¡kolca,mi shen ke er ci,mishukorutsu,ÐÐ¸ÑÐºÐ¾Ð»Ñ,ÐÐ¸ÑÐºÐ¾Ð»ÑÑ,ãã·ã¥ã³ã«ã,ç±³ä»ç§å°è¨,Miskolc", :latitude => "48.1", :longitude => "20.78333").save
City.new(:country_id => "102", :name => "Mezotur", :aliases => "Mezoetur,Mezotur,MezÃ¶tÃºr,MezÅtÃºr,MezÅtÃºr", :latitude => "47", :longitude => "20.63333").save
City.new(:country_id => "102", :name => "Mezokovesd", :aliases => "Mezokovesd,MezÅkÃ¶vesd,MezÅkÃ¶vesd", :latitude => "47.81667", :longitude => "20.58333").save
City.new(:country_id => "102", :name => "Mateszalka", :aliases => "Mateszalka,MÃ¡tÃ©szalka,MÃ¡tÃ©szalka", :latitude => "47.95528", :longitude => "22.32348").save
City.new(:country_id => "102", :name => "Mako", :aliases => "Mako,MakÃ³,MakÃ³", :latitude => "46.21667", :longitude => "20.48333").save
City.new(:country_id => "102", :name => "Kisvarda", :aliases => "Kisvarda,KisvÃ¡rda,KisvÃ¡rda", :latitude => "48.21667", :longitude => "22.08333").save
City.new(:country_id => "102", :name => "Kazincbarcika", :aliases => "Kazincbarcika,Sajokazinc,SajÃ³kazinc,ÐÐ°Ð·Ð¸Ð½ÑÐ±Ð°ÑÑÐ¸ÐºÐ°,Kazincbarcika", :latitude => "48.25", :longitude => "20.63333").save
City.new(:country_id => "102", :name => "Karcag", :aliases => "Karcag,Karcage,ÐÐ°ÑÑÐ°Ð³Ðµ,Karcag", :latitude => "47.31667", :longitude => "20.93333").save
City.new(:country_id => "102", :name => "Hodmezovasarhely", :aliases => "Khodmezevasharkhej,Ð¥Ð¾Ð´Ð¼ÐµÐ·ÐµÐ²Ð°ÑÐ°ÑÑÐµÐ¹,HÃ³dmezÅvÃ¡sÃ¡rhely", :latitude => "46.41667", :longitude => "20.33333").save
City.new(:country_id => "102", :name => "Hajduszoboszlo", :aliases => "Hajduszoboszlo,HajdÃºszoboszlÃ³,Khajdusoboslo,Ð¥Ð°Ð¹Ð´ÑÑÐ¾Ð±Ð¾ÑÐ»Ð¾,HajdÃºszoboszlÃ³", :latitude => "47.45", :longitude => "21.4").save
City.new(:country_id => "102", :name => "Hajdunanas", :aliases => "Hajdunanas,HajdÃºnÃ¡nÃ¡s,HajdÃºnÃ¡nÃ¡s", :latitude => "47.85", :longitude => "21.43333").save
City.new(:country_id => "102", :name => "Hajduboszormeny", :aliases => "Hajduboszormeny,HajdÃºbÃ¶szÃ¶rmÃ©ny,HajdÃºbÃ¶szÃ¶rmÃ©ny", :latitude => "47.66667", :longitude => "21.51667").save
City.new(:country_id => "102", :name => "Gyula", :aliases => "D'jula,Giula,Gyula,Gyulavari,GyulavÃ¡ri,ÐÑÑÐ»Ð°,Gyula", :latitude => "46.65", :longitude => "21.28333").save
City.new(:country_id => "102", :name => "Gyomaendrod", :aliases => "Endrod,EndrÅd,Gyoma,Gyomaendrod,GyomaendrÅd,GyomaendrÅd", :latitude => "46.93333", :longitude => "20.83333").save
City.new(:country_id => "102", :name => "Eger", :aliases => "Eger,Egera,Ehger,Erlau,Jager,Szarvasko,SzarvaskÅ,agr,egeru,Ð­Ð³ÐµÑ,Ø§Ú¯Ø±,ã¨ã²ã«,Eger", :latitude => "47.90265", :longitude => "20.37329").save
City.new(:country_id => "102", :name => "Debrecen", :aliases => "Debrecen,Debrecena,Debreczyn,Debretin,DebreÅ£in,Ntempretsen,dbrzn,debeulechen,deburetsu~en,ÎÏÎ­Î¼ÏÏÎµÏÏÎµÎ½,ÐÐµÐ±ÑÐµÑÐµÐ½,×××¨×¦×,ããã¬ãã§ã³,ë°ë¸ë ì²¸,Debrecen", :latitude => "47.53333", :longitude => "21.63333").save
City.new(:country_id => "102", :name => "Csongrad", :aliases => "Csongrad,CsongrÃ¡d,CsongrÃ¡d", :latitude => "46.7", :longitude => "20.15").save
City.new(:country_id => "102", :name => "Berettyoujfalu", :aliases => "Berettyoujfalu,BerettyÃ³Ãºjfalu,BerettyÃ³Ãºjfalu", :latitude => "47.21667", :longitude => "21.55").save
City.new(:country_id => "102", :name => "Bekescsaba", :aliases => "Bekescsaba,Bekeshchaba,Bekesska Caba,BÃ©keÅ¡skÃ¡ Äaba,BÃ©kÃ©scsaba,Gerla,Mezomegyer,MezÅmegyer,Nagymajor,ÐÐµÐºÐµÑÑÐ°Ð±Ð°,BÃ©kÃ©scsaba", :latitude => "46.68333", :longitude => "21.1").save
City.new(:country_id => "102", :name => "Bekes", :aliases => "Bekes,Bekes megye,Bekesh,BÃ©kÃ©s,BÃ©kÃ©s megye,Comitatul Bekes,Comitatul BÃ©kÃ©s,ÐÐµÐºÐµÑ,BÃ©kÃ©s", :latitude => "46.76667", :longitude => "21.13333").save
City.new(:country_id => "102", :name => "Balmazujvaros", :aliases => "Balmazujvaros,BalmazÃºjvÃ¡ros,BalmazÃºjvÃ¡ros", :latitude => "47.61667", :longitude => "21.35").save
City.new(:country_id => "102", :name => "Abony", :aliases => ",Abony", :latitude => "47.18333", :longitude => "20").save
City.new(:country_id => "102", :name => "Zalaegerszeg", :aliases => "Zalaegerszeg,Zalaehgerseg,ÐÐ°Ð»Ð°ÑÐ³ÐµÑÑÐµÐ³,Zalaegerszeg", :latitude => "46.84", :longitude => "16.84389").save
City.new(:country_id => "102", :name => "Veszprem", :aliases => "Comitatul Veszprem,Comitatul VeszprÃ©m,Gyulafiratot,GyulafirÃ¡tÃ³t,Kadarta,KÃ¡dÃ¡rta,Vesprem,VesprÃ©m,Vessprem,VessprÃ©m,Veszprem,Veszprem megye,Veszprim,VeszprÃ©m,VeszprÃ©m megye,wei si pu lei mu zhou,ÐÐµÑÐ¿ÑÐµÐ¼,ç¶­æ¯æ®é·å§å·,VeszprÃ©m", :latitude => "47.09327", :longitude => "17.91149").save
City.new(:country_id => "102", :name => "Vecses", :aliases => ",VecsÃ©s", :latitude => "47.4", :longitude => "19.28333").save
City.new(:country_id => "102", :name => "Varpalota", :aliases => ",VÃ¡rpalota", :latitude => "47.2", :longitude => "18.13333").save
City.new(:country_id => "102", :name => "Vac", :aliases => "Vac,Vacz,VÃ¡c,VÃ¡cz,Waitzen,VÃ¡c", :latitude => "47.77591", :longitude => "19.13612").save
City.new(:country_id => "102", :name => "Tatabanya", :aliases => "Tataban'ja,Tatabanya,TatabÃ¡nya,Ð¢Ð°ÑÐ°Ð±Ð°Ð½ÑÑ,TatabÃ¡nya", :latitude => "47.56667", :longitude => "18.41667").save
City.new(:country_id => "102", :name => "Tata", :aliases => "Agostyan,Tata,Tatatovaros,TatatÃ³vÃ¡ros,ÃgostyÃ¡n,Tata", :latitude => "47.65", :longitude => "18.31667").save
City.new(:country_id => "102", :name => "Tapolca", :aliases => "Tapolca,Tapolcza,Tapolezai,Tapolca", :latitude => "46.88333", :longitude => "17.43333").save
City.new(:country_id => "102", :name => "Szombathely", :aliases => "Gyongyosherman,GyÃ¶ngyÃ¶shermÃ¡n,Hereny,HerÃ©ny,Kamon,KÃ¡mon,Olad,Perint,Sabaria,Savaria,Sombatkhej,Steinamanger,Szentkiraly,SzentkirÃ¡ly,Szombatehly,Szombathely,Szombatnely,Zanat,sonbatohei,Ð¡Ð¾Ð¼Ð±Ð°ÑÑÐµÐ¹,ã½ã³ãããã¤,Szombathely", :latitude => "47.23088", :longitude => "16.62155").save
City.new(:country_id => "102", :name => "Szigetszentmiklos", :aliases => "Sigetsentmiklosh,Szigentmiklos,Szigetsentmiklos,Szigetszentmiklos,SzigetszentmiklÃ³s,Ð¡Ð¸Ð³ÐµÑÑÐµÐ½ÑÐ¼Ð¸ÐºÐ»Ð¾Ñ,SzigetszentmiklÃ³s", :latitude => "47.35", :longitude => "19.05").save
City.new(:country_id => "102", :name => "Szentendre", :aliases => "Sankt Andrae,Sankt AndrÃ¤,Sentendre,Szentendre,Ð¡ÐµÐ½ÑÐµÐ½Ð´ÑÐµ,Szentendre", :latitude => "47.66943", :longitude => "19.07561").save
City.new(:country_id => "102", :name => "Szekszard", :aliases => "Seksar,Seksard,Szekszard,SzekszÃ¡rd,Ð¡ÐµÐºÑÐ°ÑÐ´,SzekszÃ¡rd", :latitude => "46.35", :longitude => "18.71667").save
City.new(:country_id => "102", :name => "Szekesfehervar", :aliases => "Alba Regia,Albareale,Sekeshfekhervar,Stuhlweissenburg,StuhlweiÃenburg,Szekesfehervar,SzÃ©kesfehÃ©rvÃ¡r,sai ke shen bai bao,sekeshufeheruvu~aru,Ð¡ÐµÐºÐµÑÑÐµÑÐµÑÐ²Ð°Ñ,ã»ã¼ã±ã·ã¥ãã§ãã¼ã«ã´ã¡ã¼ã«,å¡åä»ç½å ¡,SzÃ©kesfehÃ©rvÃ¡r", :latitude => "47.18995", :longitude => "18.41034").save
City.new(:country_id => "102", :name => "Szazhalombatta", :aliases => ",SzÃ¡zhalombatta", :latitude => "47.33333", :longitude => "18.93333").save
City.new(:country_id => "102", :name => "Sopron", :aliases => "OEdenburg,Scarabantia,Scarbantia,Shopron,Sopron,Szorpron,shopuron,swprwn,syopeulon,Ãdenburg,Ð¨Ð¾Ð¿ÑÐ¾Ð½,×©××¤×¨××,ã·ã§ãã­ã³,ì¼íë¡ ,Sopron", :latitude => "47.68333", :longitude => "16.6").save
City.new(:country_id => "102", :name => "Siofok", :aliases => "Balatonkiliti,Balatonujhely,BalatonÃºjhely,Shiofok,Siofok,SiÃ³fok,shiofoku,Ð¨Ð¸Ð¾ÑÐ¾Ðº,ã·ãªã¼ãã©ã¯,SiÃ³fok", :latitude => "46.9", :longitude => "18.05").save
City.new(:country_id => "102", :name => "Sarvar", :aliases => "Savar,SÃ¡rvÃ¡r", :latitude => "47.25395", :longitude => "16.93525").save
City.new(:country_id => "102", :name => "Salgotarjan", :aliases => "Baglyasalja,Shal'gotar'jan,Shalgo Tar'yan,Zagyvapalfalva,ZagyvapÃ¡lfalva,Ð¨Ð°Ð»ÑÐ³Ð¾ÑÐ°ÑÑÑÐ½,SalgÃ³tarjÃ¡n", :latitude => "48.09872", :longitude => "19.80303").save
City.new(:country_id => "102", :name => "Pecs", :aliases => "Cinquechiese,Fuenfkirchen,Funfkirchen,FÃ¼nfkirchen,Hird,Magyarurugy,MagyarÃ¼rÃ¼gy,Malom,Meced Sabolc,Mecek Sabolc,Mecsekalja,Mecsekszabolcs,MÃ¡lom,Nadapipad,Nadarpad,Nagyarpad,NagyÃ¡rpÃ¡d,Paetkostolie,Patacs,Peca,Pech,Pecs,Pecuh,Pecuy-,Pecz,PeÃ§uy-,PeÄuh,PÃ¤Å¥kostolie,PÃ©cs,PÄÄa,Quinque Ecclesiae,Racvaros,RÃ¡cvÃ¡ros,Somogy,Vasas,pechi,ÐÐµÑ,ãã¼ã,PÃ©cs", :latitude => "46.08333", :longitude => "18.23333").save
City.new(:country_id => "102", :name => "Paradsasvar", :aliases => "Paradsasvar,Paradshashvar,Ureghuta,Uveghuta,Ãreghuta,Ãveghuta,ÐÐ°ÑÐ°Ð´ÑÐ°ÑÐ²Ð°Ñ,ParÃ¡dsasvÃ¡r", :latitude => "47.9126", :longitude => "19.97709").save
City.new(:country_id => "102", :name => "Papa", :aliases => "Borsosgyor,BorsosgyÅr,Kettornyulak,KÃ©ttornyÃºlak,Papa,Papy,PÃ¡pa,Tapolcafo,TapolcafÅ,ÐÐ°Ð¿Ñ,PÃ¡pa", :latitude => "47.33333", :longitude => "17.46667").save
City.new(:country_id => "102", :name => "Paks", :aliases => "Dunakomlod,DunakÃ¶mlÅd,Paks,Paks", :latitude => "46.63333", :longitude => "18.86667").save
City.new(:country_id => "102", :name => "Oroszlany", :aliases => "Oroslane,Oroszlany,OroszlÃ¡ny,ÐÑÐ¾ÑÐ»Ð°Ð½Ðµ,OroszlÃ¡ny", :latitude => "47.48333", :longitude => "18.31667").save
City.new(:country_id => "102", :name => "Nagykoros", :aliases => ",NagykÅrÃ¶s", :latitude => "47.03333", :longitude => "19.78333").save
City.new(:country_id => "102", :name => "Nagykanizsa", :aliases => "Bagola,Bagolasanc,BagolasÃ¡nc,Bajcsa,Gross Kanischa,Grosz Kanischa,Kanije,Korpavar,KorpavÃ¡r,Miklosfa,MiklÃ³sfa,Nadkanizha,Nagykanizsa,Somogyszentmiklos,SomogyszentmiklÃ³s,qnyzhh,ÐÐ°Ð´ÐºÐ°Ð½Ð¸Ð¶Ð°,ÙÙÛÚÙ,Nagykanizsa", :latitude => "46.45347", :longitude => "16.99104").save
City.new(:country_id => "102", :name => "Mosonmagyarovar", :aliases => "Altenburg,Magyarovar,MagyarÃ³vÃ¡r,Moshonmad'jarovar,Moson,Mosonmagyarovar,MosonmagyarÃ³vÃ¡r,Ungarisch Altenburg,Wieselburg,moshonmajaruovu~aru,ÐÐ¾ÑÐ¾Ð½Ð¼Ð°Ð´ÑÑÑÐ¾Ð²Ð°Ñ,ã¢ã·ã§ã³ãã¸ã£ã«ãªã¼ã´ã¡ã¼ã«,MosonmagyarÃ³vÃ¡r", :latitude => "47.86667", :longitude => "17.28333").save
City.new(:country_id => "102", :name => "Monor", :aliases => ",Monor", :latitude => "47.35", :longitude => "19.45").save
City.new(:country_id => "102", :name => "Mohacs", :aliases => "Mohac,Mohacs,Mohacz,MohaÄ,MohÃ¡cs,Mokhach,ÐÐ¾ÑÐ°Ñ,MohÃ¡cs", :latitude => "45.99306", :longitude => "18.68306").save
City.new(:country_id => "102", :name => "Komlo", :aliases => ",KomlÃ³", :latitude => "46.19278", :longitude => "18.26494").save
City.new(:country_id => "102", :name => "Komarom", :aliases => "Komarom,Komaromujvaros,Komorn,KomÃ¡rom,KomÃ¡romÃºjvÃ¡ros,Szony,SzÅny,Ujszony,Ujvaros,komaromu,ÃjvÃ¡ros,ã³ãã¼ã­ã ,KomÃ¡rom", :latitude => "47.73333", :longitude => "18.11667").save
City.new(:country_id => "102", :name => "Kiskunhalas", :aliases => "Kishkunkhalash,Kiskunhalas,Kiskunhalos,ÐÐ¸ÑÐºÑÐ½ÑÐ°Ð»Ð°Ñ,Kiskunhalas", :latitude => "46.43139", :longitude => "19.4875").save
City.new(:country_id => "102", :name => "Kiskunfelegyhaza", :aliases => ",KiskunfÃ©legyhÃ¡za", :latitude => "46.71361", :longitude => "19.85222").save
City.new(:country_id => "102", :name => "Kiskoros", :aliases => "Kiskoros,KiskÅrÃ¶s,KiskÅrÃ¶s", :latitude => "46.62056", :longitude => "19.28861").save
City.new(:country_id => "102", :name => "Keszthely", :aliases => "Kestkhej,Keszthely,Keszthelyi,ÐÐµÑÑÑÐµÐ¹,Keszthely", :latitude => "46.76667", :longitude => "17.25").save
City.new(:country_id => "102", :name => "Kecskemet", :aliases => "Heteny,Hetenyegyhaza,HetÃ©ny,HetÃ©nyegyhÃ¡za,Kechkemet,Kecskemet,KecskemÃ©t,kai qi kai mei te,ÐÐµÑÐºÐµÐ¼ÐµÑ,å¯å¥å¯æ¢ç¹,KecskemÃ©t", :latitude => "46.90618", :longitude => "19.69128").save
City.new(:country_id => "102", :name => "Kaposvar", :aliases => "Kaposfured,KaposfÃ¼red,Kaposhvar,Kaposszentjakab,Kaposvar,KaposvÃ¡r,Toponar,ToponÃ¡r,Torocske,TÃ¶rÃ¶cske,kaposhuvu~aru,ÐÐ°Ð¿Ð¾ÑÐ²Ð°Ñ,ã«ãã·ã¥ã´ã¡ã¼ã«,KaposvÃ¡r", :latitude => "46.36667", :longitude => "17.8").save
City.new(:country_id => "102", :name => "Kalocsa", :aliases => "Kalocsa,Kalocsa", :latitude => "46.52639", :longitude => "18.98583").save
City.new(:country_id => "102", :name => "Jaszbereny", :aliases => "Jaszbereny,JÃ¡szberÃ©ny,JÃ¡szberÃ©ny", :latitude => "47.5", :longitude => "19.91667").save
City.new(:country_id => "102", :name => "Hatvan", :aliases => "Hatvan,Khatvan,htwn,Ð¥Ð°ÑÐ²Ð°Ð½,Ø­Ø·ÙÙ,Hatvan", :latitude => "47.66667", :longitude => "19.68333").save
City.new(:country_id => "102", :name => "Gyor", :aliases => "D'or,Gyirmot,GyirmÃ³t,Gyor,Gyorszentivan,GyÅr,GyÅrszentivÃ¡n,Menfocsanak,MÃ©nfÅcsanak,Pinnyed,PinnyÃ©d,Raab,jeru,ÐÑÐ¾Ñ,ã¸ã§ã¼ã«,GyÅr", :latitude => "47.68333", :longitude => "17.63512").save
City.new(:country_id => "102", :name => "Gyongyos", :aliases => "Gyongyos,GyÃ¶ngyÃ¶s,GyÃ¶ngyÃ¶s", :latitude => "47.78333", :longitude => "19.93333").save
City.new(:country_id => "102", :name => "Gyal", :aliases => ",GyÃ¡l", :latitude => "47.38333", :longitude => "19.23333").save
City.new(:country_id => "102", :name => "Godollo", :aliases => "Godollo,Godolo,Goedoello,GÃ¶dÃ¶llÅ,GÃ¶dÃ¶lÃ¶,GÃ¶dÃ¶llÅ", :latitude => "47.6", :longitude => "19.36667").save
City.new(:country_id => "102", :name => "God", :aliases => "Alsogod,AlsÃ³gÃ¶d,Felsogod,FelsÅgÃ¶d,God,GÃ¶d,GÃ¶d", :latitude => "47.7", :longitude => "19.13333").save
City.new(:country_id => "102", :name => "Fot", :aliases => ",FÃ³t", :latitude => "47.61667", :longitude => "19.2").save
City.new(:country_id => "102", :name => "Esztergom", :aliases => "Ehstergom,Esztergom,Gran,Ostrihom,Ostrzyhom,OstÅihom,Pilisszentlelek,PilisszentlÃ©lek,Strigonio,Strigoniu,Strigonium,ai si te gen,eseuteleugom,esuterugomu,Ð­ÑÑÐµÑÐ³Ð¾Ð¼,ã¨ã¹ãã«ã´ã ,è¾æ¯ç¹æ ¹,ìì¤íë¥´ê³°,Esztergom", :latitude => "47.8", :longitude => "18.75").save
City.new(:country_id => "102", :name => "Erd", :aliases => "Ehrd,Erd,Hamzsabeg,HamzsabÃ©g,Ãrd,Ð­ÑÐ´,Ãrd", :latitude => "47.36667", :longitude => "18.93333").save
City.new(:country_id => "102", :name => "Dunaujvaros", :aliases => "Dunapentele,Dunaujvaros,Dunaujvarosh,DunaÃºjvÃ¡ros,Stalinvaros,Sztalinvaros,SztÃ¡linvÃ¡ros,duo nao xin cheng,ÐÑÐ½Ð°ÑÐ¹Ð²Ð°ÑÐ¾Ñ,å¤çæ°å,DunaÃºjvÃ¡ros", :latitude => "46.98333", :longitude => "18.93333").save
City.new(:country_id => "102", :name => "Dunakeszi", :aliases => ",Dunakeszi", :latitude => "47.63333", :longitude => "19.13333").save
City.new(:country_id => "102", :name => "Dunaharaszti", :aliases => ",Dunaharaszti", :latitude => "47.35", :longitude => "19.08333").save
City.new(:country_id => "102", :name => "Dombovar", :aliases => "Dombovar,DombÃ³vÃ¡r,DombÃ³vÃ¡r", :latitude => "46.38333", :longitude => "18.11667").save
City.new(:country_id => "102", :name => "Dabas", :aliases => "Dabas,Gyon,GyÃ³n,Sari,SÃ¡ri,Dabas", :latitude => "47.18333", :longitude => "19.31667").save
City.new(:country_id => "102", :name => "Cegled", :aliases => "Cegled,CeglÃ©d,Czegled,Ð¦ÐµÐ³Ð»ÐµÐ´,CeglÃ©d", :latitude => "47.16667", :longitude => "19.8").save
City.new(:country_id => "102", :name => "Budapest", :aliases => "Aquincum,Boedapes,Boedapest,Boudapes,Boudapeste,BoudapÃ¨s,Budaipeist,Budapescht,Budapeshha,Budapesht,Budapesht osh,Budapest,Budapesta,Budapestas,Budapeste,Budapesti,Budapesto,Budapeszt,BudapeÅto,BudapeÅt,BudapeÅte,BudapeÅ¡t,BudapeÅ¡ta,BudapeÅ¡tas,BudapeÅ¡Å¥,BudapÃ¨st,BudapÃ©sht,Budimpeshta,Budimpesta,BudimpeÅ¡ta,BÃ¹dapest,BÃ¹dapeszt,BÃºdaipeist,BÃºdapest,Gorad Budapesht,bu da pei si,budapeseuteu,budapesrr,budapest,budapesta,budapesuto,bwdabst,bwdabyst,bwdapst,bwdpst,putapest,ÎÎ¿ÏÎ´Î±ÏÎ­ÏÏÎ·,ÐÑÐ´Ð°Ð¿ÐµÑÑ,ÐÑÐ´Ð°Ð¿ÐµÑÑ Ð¾Ñ,ÐÑÐ´Ð°Ð¿ÐµÑÐ°,ÐÑÐ´Ð¸Ð¼Ð¿ÐµÑÑÐ°,ÐÐ¾ÑÐ°Ð´ ÐÑÐ´Ð°Ð¿ÐµÑÑ,Ô²Õ¸ÖÕ¤Õ¡ÕºÕ¥Õ·Õ¿,×××××¤×¢×©×,××××¤×©×,Ø¨ÙØ¯Ø§Ø¨Ø³Øª,Ø¨ÙØ¯Ø§Ø¨ÙØ³Øª,Ø¨ÙØ¯Ø§Ù¾Ø³Øª,Ø¨ÙÚØ§Ù¾Ø³Ù¼,à¤¬à¥à¤¡à¤¾à¤ªà¥à¤¸à¥à¤,à¦¬à§à¦¦à¦¾à¦ªà§à¦¸à§à¦,àª¬à«àª¡àª¾àªªà«àª¸à«àª,à®ªà¯à®à®¾à®ªà¯à®¸à¯à®à¯,à²¬à³à²¡à²¾à²ªà³à²¸à³à²à³,à´¬àµà´¡à´¾à´ªàµà´¸àµà´±àµà´±àµ,à¸à¸¹à¸à¸²à¹à¸à¸ªà¸à¹,à½à½´à¼à½à¼à½à½ºà¼à½¦à½²à½à¼,áá°á¸ááááºáá¼á­á¯á·,áá£ááááá¨á¢á,á¡á³ááµáµ,ãããã¹ã,å¸è¾¾ä½©æ¯,ë¶ë¤íì¤í¸,Budapest", :latitude => "47.49801", :longitude => "19.03991").save
City.new(:country_id => "102", :name => "Budaors", :aliases => ",BudaÃ¶rs", :latitude => "47.46181", :longitude => "18.95845").save
City.new(:country_id => "102", :name => "Balassagyarmat", :aliases => "Balassagyarmat,Ipolyszog,IpolyszÃ¶g,Balassagyarmat", :latitude => "48.08333", :longitude => "19.3").save
City.new(:country_id => "102", :name => "Baja", :aliases => "Baja,Bajja,Baya,bayh,ÐÐ°Ð¹Ñ,Ø¨Ø§ÛÙ,Baja", :latitude => "46.18333", :longitude => "18.96667").save
City.new(:country_id => "102", :name => "Ajka", :aliases => "Ajka,Ajkarendek,Bakonygyepes,Csekut,CsÃ©kÃºt,Padrag,Padragkut,PadragkÃºt,Tosok,Tosokberend,TÃ³sok,TÃ³sokberÃ©nd,ÐÐ¹ÐºÐ°,Ajka", :latitude => "47.1", :longitude => "17.56667").save
City.new(:country_id => "102", :name => "Nagyvarad", :aliases => ",NagyvÃ¡rad", :latitude => "47.06053", :longitude => "21.92734").save
City.new(:country_id => "102", :name => "Budapest XII. keruelet", :aliases => ",Budapest XII. kerÃ¼let", :latitude => "47.49192", :longitude => "19.01493").save
City.new(:country_id => "102", :name => "Budapest XI. keruelet", :aliases => ",Budapest XI. kerÃ¼let", :latitude => "47.47603", :longitude => "19.03605").save
City.new(:country_id => "102", :name => "Budapest IX. keruelet", :aliases => ",Budapest IX. kerÃ¼let", :latitude => "47.48299", :longitude => "19.06591").save
City.new(:country_id => "102", :name => "Budapest VIII. keruelet", :aliases => ",Budapest VIII. kerÃ¼let", :latitude => "47.48919", :longitude => "19.07012").save
City.new(:country_id => "102", :name => "Budapest VII. keruelet", :aliases => ",Budapest VII. kerÃ¼let", :latitude => "47.50045", :longitude => "19.06875").save
City.new(:country_id => "102", :name => "Budapest VI. keruelet", :aliases => ",Budapest VI. kerÃ¼let", :latitude => "47.50369", :longitude => "19.06583").save
City.new(:country_id => "102", :name => "Budapest XIV. keruelet", :aliases => ",Budapest XIV. kerÃ¼let", :latitude => "47.5183", :longitude => "19.10789").save
City.new(:country_id => "102", :name => "Budapest XIII. keruelet", :aliases => ",Budapest XIII. kerÃ¼let", :latitude => "47.52978", :longitude => "19.08068").save
City.new(:country_id => "102", :name => "Budapest IV. keruelet", :aliases => ",Budapest IV. kerÃ¼let", :latitude => "47.56182", :longitude => "19.08909").save
City.new(:country_id => "102", :name => "Budapest XV. keruelet", :aliases => ",Budapest XV. kerÃ¼let", :latitude => "47.56263", :longitude => "19.11681").save
City.new(:country_id => "102", :name => "Budapest XVI. keruelet", :aliases => ",Budapest XVI. kerÃ¼let", :latitude => "47.51482", :longitude => "19.17028").save
City.new(:country_id => "102", :name => "Budapest X. keruelet", :aliases => ",Budapest X. kerÃ¼let", :latitude => "47.4791", :longitude => "19.15835").save
City.new(:country_id => "102", :name => "Budapest XIX. keruelet", :aliases => ",Budapest XIX. kerÃ¼let", :latitude => "47.45293", :longitude => "19.14943").save
City.new(:country_id => "102", :name => "Budapest XVIII. keruelet", :aliases => ",Budapest XVIII. kerÃ¼let", :latitude => "47.44417", :longitude => "19.17595").save
City.new(:country_id => "102", :name => "Budapest XXIII. keruelet", :aliases => ",Budapest XXIII. kerÃ¼let", :latitude => "47.39788", :longitude => "19.11492").save
City.new(:country_id => "102", :name => "Budapest XXII. keruelet", :aliases => ",Budapest XXII. kerÃ¼let", :latitude => "47.42698", :longitude => "19.04016").save
City.new(:country_id => "102", :name => "Budapest XXI. keruelet", :aliases => ",Budapest XXI. kerÃ¼let", :latitude => "47.43047", :longitude => "19.07098").save
City.new(:country_id => "102", :name => "Budapest XX. keruelet", :aliases => ",Budapest XX. kerÃ¼let", :latitude => "47.43674", :longitude => "19.10093").save
City.new(:country_id => "102", :name => "Budapest XVII. keruelet", :aliases => ",Budapest XVII. kerÃ¼let", :latitude => "47.47997", :longitude => "19.25388").save
City.new(:country_id => "102", :name => "Budapest III. keruelet", :aliases => ",Budapest III. kerÃ¼let", :latitude => "47.54157", :longitude => "19.04501").save
City.new(:country_id => "102", :name => "Budapest II. keruelet", :aliases => ",Budapest II. kerÃ¼let", :latitude => "47.51291", :longitude => "19.03184").save
City.new(:country_id => "102", :name => "Budapest I. keruelet", :aliases => ",Budapest I. kerÃ¼let", :latitude => "47.49705", :longitude => "19.03961").save
