City.new(:country_id => "105", :name => "Jerusalem", :aliases => "Adonai-jireh,Aelia Capitolina,Al Quds,Al-Kuds,Ariel,Baitulmuqaddis,Bayt al-Maqdis,Bayt al-Muqaddas,Cherusalen,CherusalÃ©n,Colonia Aelia Capitolina,Djeruzalem,El Kuds,El Quds esh Sherif,Erusagem,Erusalim,Gerusalemme,Girusalemmi,Hierosolyma,Hierousalem,HierousalÄm,Hierusalem,Iarusaileim,IarÃºsailÃ©im,Iebous,Iebus,Ierosolyma,Ierousalem,Ierusalem,Ierusalema,Ierusalim,Ir David,Ir Ha-Qdoosha,Ir Ha-Qodesh,Jeriwsalem,Jerozolima,Jerusalem,Jerusalemi,Jerusalemo,Jerusalemu,Jerusalen,Jerusalim,JerusalÃ©m,JerusalÃ©n,Jeruusalemm,Jeruzale,Jeruzalem,Jeruzaleme,Jeruzalemi,JeruzalÃ©m,JeruzalÄ,Jeruzsalem,JeruzsÃ¡lem,JeruzÄleme,JerÃºsalem,JerÃºsÃ¡láº¹ÌmÃ¹,Jorsala,Jorsalaborg,Jorsalir,JÃ©rusalem,JÃ³rsalaborg,JÃ³rsalir,Kouds,Kudues,KudÃ¼s,Lungsod ng Jerusalem,Moria,Morias,Salem,Shalem,Sion,Solyma,Ursalimmu,Urusalim,UruÅ¡alim,UrÅ¡alimmu,Xerusalen,XerusalÃ©n,Yerusalem,Yerushalayim,Yirushalayim,YirushalÄyim,Zion,al-Balat,al-Quds as-Sarif,al-Quds aÅ¡-Å arÄ«f,albla,alqds,alqds alshryf,aryyyl,awrshlym,byt almqds,erusaremu,haqodes,ierusalimi,jerusalema,lqds,mrya,mworiyah,mwryh,salem,salym,shywn,slm,wrshlm,wrshlym,ybws,ye lu sa leng,ye ru sa lem,yebws,yelusallem,yerusalama,yerwsalami,yerwsalayim,yerwselem,yrwslm,yrwslym,ziywon,zywn,ÎÏÎ¹Î·Î»,ÎÎµÎ²Î¿ÏÏ,ÎÎµÏÎ¿ÏÎ¿Î»ÏÎ¼Î±,ÎÎµÏÎ¿ÏÏÎ»ÏÎ¼Î±,ÎÎµÏÎ¿ÏÏÎ±Î»Î®Î¼,ÎÎµÏÎ¿ÏÏÎ±Î»Î·Î¼,ÎÏÏÎ¹Î±Ï,Î£Î±Î»Î·Î¼,Î£Î¹ÏÎ½,Î£Î¿Î»ÏÎ¼Î±,ÐÑÑÑÐ°Ð»Ð¸Ð¼,ÐÐµÑÑ¹ÑÐ°Ð»Ð¸Ð¼Ñ,ÐÐµÑÑÑÐ°Ð»Ð¸Ð¼,ÐÑÑÑÐ°Ð»ÑÐ¼,ÐÐµÑÑÑÐ°Ð»Ð¸Ð¼,ÐÐµÑÑÑÐ°Ð»Ð¸Ð¼,ÔµÖÕ¸ÖÕ½Õ¡Õ²Õ¥Õ´,×Ö²×¨Ö´××Öµ×,×Öµ××Ö´×Ö¸Ö¼× ×§Ö·×¤Ö´Ö¼×××Ö¹×Ö´×× Ö¸×,××¨×××,×Ö·×§Ö¹Ö¼×Ö¶×©×,×Ö°××Ö¼×¡,×Ö°×¨×Ö¼×©Ö°××Ö¶×,×Ö°×¨×Ö¼×©Ö¸××Ö·×Ö´×,×Ö°×¨×Ö¼×©Ö¸××Ö·×Ö´,×Ö°×¨×Ö¼×©Ö¸××Ö¸×Ö´,××××¡,××¨××©×××,××¨××©××,××Ö¹×¨Ö´×Ö¸Ö¼×,×××¨××,×¦Ö´×Ö¼×Ö¹×,×¦×××,×©Ö¸××Öµ×,×©××,Ø¥ÙÙÙØ§Ø¡,Ø§Ø±ÙØ¦ÙÙ,Ø§ÙØ¨ÙØ§,Ø§ÙÙØ¯Ø³,Ø§ÙÙØ¯Ø³ Ø§ÙØ´Ø±ÙÙ,Ø§ÙØ±Ø´ÙÛÙ,Ø¨ÙØª Ø§ÙÙÙØ¯Ø³,Ø¨ÛØª Ø§ÙÙÙØ¯Ø³,Ø³Ø§ÙÙÙ,ØµÙÙÙÙ,ÙÙØ¯Ø³,ÙØ±ÙÙØ§,ÙØ±Ø´ÙÙÙ,ÙØ¨ÙØ³,ÙÛØ±ÛØ³Ø§ÙÛÙ,ÜÜÜªÜ«Ü Ü¡,ÜÜªÜ«Ü Ü¡,Ü¨ÜÜÜÜ¢,à¤¯à¥à¤°à¥à¤¶à¤²à¤®,à¦à§à¦°à§à¦¸à¦¾à¦²à§à¦®,à¹à¸¢à¸£à¸¹à¸à¸²à¹à¸¥à¸¡,ááá á£á¡ááááá,á¥á¨á©á³áá,ã¨ã«ãµã¬ã ,è¶è·¯æå·,ìë£¨ì´ë ,Jerusalem", :latitude => "31.77902", :longitude => "35.2253").save
City.new(:country_id => "105", :name => "Zefat", :aliases => "Cfat,Safad,Safed,Sfat,Tsefat,Zefat,Ð¦ÑÐ°Ñ,áºefat,áºefat", :latitude => "32.96667", :longitude => "35.49444").save
City.new(:country_id => "105", :name => "Yavne", :aliases => "Javne,Kefar Yavne,Kfar Yavne,Kfar Yavneh,New Yavne,Yavne,Ð¯Ð²Ð½Ðµ,Yavne", :latitude => "31.87639", :longitude => "34.74").save
City.new(:country_id => "105", :name => "Yafo", :aliases => "Giaffa,Iope,IopÄ,Jaffa,Jafo,Joppa,Joppe,Yafa,Yafah,Yaffa,YÄfa,yafa,ypw,Ð¯ÑÐ¾,Ð¯ÑÑÐ°,××¤×,ÙØ§ÙØ§,ÛØ§ÙØ§,Yafo", :latitude => "32.05043", :longitude => "34.75224").save
City.new(:country_id => "105", :name => "Umm el Fahm", :aliases => "El Fahm,Umm al Fahm,Umm el Faham,Umm el Fahm,Umm el Faá¸¥m,Umm el Faá¸¥m", :latitude => "32.51583", :longitude => "35.1525").save
City.new(:country_id => "105", :name => "Tirat Karmel", :aliases => "At Tira,Tira,Tirah,Tirat Carmel,Tirat Hakarmel,Tirat Karmel,Tire,Tirat Karmel", :latitude => "32.76167", :longitude => "34.97194").save
City.new(:country_id => "105", :name => "Tiberias", :aliases => "Tabariya,Tabariyeh,Tabariyyah,TabarÄ«ya,Tevarya,TevaryÄ,Teverya,Tiberiada,Tiberiade,Tiberiades,Tiberiado,Tiberias,Tiberijada,TiberiÃ¡s,TiberÃ­ades,TibÃ©riade,Tiveriada,TiveriÃ¡da,Tubaria,Tverija,Tverya,Tyberiada,TÉverya,tbrya,tbryh,tbryt,Î¤Î¹Î²ÎµÏÎ¹Î¬Î´Î±,Î¤Î¹Î²ÎµÏÎ¹Î¬Ï,Ð¢Ð²ÐµÑÐ¸Ñ,×××¨××,Ø·Ø¨Ø±ÙØ§,Ø·Ø¨Ø±ÙØ©,á¹¬abariyyah,á¹¬Éá¸eryÄh,Tiberias", :latitude => "32.79556", :longitude => "35.52861").save
City.new(:country_id => "105", :name => "Tel Aviv", :aliases => "Lungsod ng Tel Aviv-Yafo,Tel Aviv,Tel Avivas,Tel Awiw,Tel'-Aviv,Tel-Aviv,Tel-Avivo,Tell Abib,Tell AbÄ«b,Tell Afif,te la wei fu,tel-avivi,teruabibu,tl abyb,Ð¢ÐµÐ» ÐÐ²Ð¸Ð²,Ð¢ÐµÐ»Ñ-ÐÐ²Ð¸Ð²,×ª× ××××,×ª× ××××-××¤×,ØªÙ Ø£Ø¨ÙØ¨,ØªÙâØ¢ÙÛÙ,ØªÛÙ Ø¦Ø§ÛÙÛ,Ü¬Ü  ÜÜÜÜ,ááá-ááááá,ãã«ã¢ãã,ç¹æç»´å¤«,Tel Aviv", :latitude => "32.06667", :longitude => "34.76667").save
City.new(:country_id => "105", :name => "maalot Tarshiha", :aliases => "Maalot-Tarshikha,Me`ona `Ironit,Tarchiha,Tarshihah,Teir Shiha,ÐÐ°Ð°Ð»Ð¾Ñ-Ð¢Ð°ÑÑÐ¸ÑÐ°,maalot TarshÄ«hÄ", :latitude => "33.01667", :longitude => "35.26667").save
City.new(:country_id => "105", :name => "Tamra", :aliases => "Tamra,Tamrah,Temarah,Ð¢Ð°Ð¼ÑÐ°,Tamra", :latitude => "32.84861", :longitude => "35.20472").save
City.new(:country_id => "105", :name => "Sederot", :aliases => "Sderot,SdÃ©rot,Sederot,Shederot,sdrwt,Åderot,Ð¡Ð´ÐµÑÐ¾Ñ,×©××¨××ª,Sederot", :latitude => "31.51667", :longitude => "34.58333").save
City.new(:country_id => "105", :name => "Sakhnin", :aliases => "Sahrin,Sakhnin,SakhnÄ«n,Saknin,SaknÄ«n,Sikhnin,Ð¡Ð°ÑÐ½Ð¸Ð½,SakhnÄ«n", :latitude => "32.86222", :longitude => "35.29333").save
City.new(:country_id => "105", :name => "Rishon LeZiyyon", :aliases => "Ayun Kara,Le Tsiyon,Le TsÄ«yÅn,Richon le Sion,Rischon leTzion,Rishon Le Zion,Rishon LeZion,Rishon LeZiyyon,Rishon Letsiyon,Rishon Lezion,Rishon Leáºiyyon,Rishon Lsiyon,Rishon le Siyon,Rishon le Ziyon,Rishon-le-Cion,Rison-Le-Ciono,RiÅon-Le-Ciono,`Uyun Qara,Ð Ð¸ÑÐ¾Ð½-Ð»Ðµ-Ð¦Ð¸Ð¾Ð½,×¨××©×× ××¦×××,âUyÅ«n QÄra,Rishon Leáºiyyon", :latitude => "31.96417", :longitude => "34.80444").save
City.new(:country_id => "105", :name => "Ramla", :aliases => "Er Ramle,Ramla,Ramle,ramla,rmlh,Ð Ð°Ð¼Ð»Ð°,×¨×××,Ramla", :latitude => "31.92528", :longitude => "34.86694").save
City.new(:country_id => "105", :name => "Ramat HaSharon", :aliases => "Ramat HaSharon,Ramat Hash Sharon,`Ir Shalom,âIr Shalom,Ramat HaSharon", :latitude => "32.14722", :longitude => "34.84167").save
City.new(:country_id => "105", :name => "Ramat Gan", :aliases => "Gan,Ramat Gan,Ramat-Gan,rmt gn,Ð Ð°Ð¼Ð°Ñ-ÐÐ°Ð½,×¨××ª ××,Ramat Gan", :latitude => "32.08056", :longitude => "34.81417").save
City.new(:country_id => "105", :name => "Qiryat Yam", :aliases => "Kir'jat-Jam,Kirjat Jam,Kiryat-Yam,Qiryat Yam,qryyt ym,ÐÐ¸ÑÑÑÑ-Ð¯Ð¼,×§×¨×××ª ××,Qiryat Yam", :latitude => "32.85083", :longitude => "35.07028").save
City.new(:country_id => "105", :name => "Qiryat Shemona", :aliases => "Al Khalisa,El Khalisa,Halasa,Halsa,Khalasah,Kir'jat-Shmona,Kiryat Shemoneh,Qiryat Shemona,Qiryat Shemonah,Qiryat Shmona,ÐÐ¸ÑÑÑÑ-Ð¨Ð¼Ð¾Ð½Ð°,Qiryat Shemona", :latitude => "33.20806", :longitude => "35.56861").save
City.new(:country_id => "105", :name => "Qiryat Motzkin", :aliases => "Kir'jat-Mockin,Qiryat Motskin,Qiryat Motsqin,Qiryat Motzkin,Qiryat Mozqin,Qiryat Moáºqin,ÐÐ¸ÑÑÑÑ-ÐÐ¾ÑÐºÐ¸Ð½,Qiryat Motzkin", :latitude => "32.83639", :longitude => "35.07528").save
City.new(:country_id => "105", :name => "Qiryat Gat", :aliases => "Gat,Kir'jat-Gat,Kirjat Gat,Kiryat Gat,Qastina Alef,Qiryat Gat,qryyt gt,ÐÐ¸ÑÑÑÑ-ÐÐ°Ñ,×§×¨×××ª ××ª,Qiryat Gat", :latitude => "31.6", :longitude => "34.76667").save
City.new(:country_id => "105", :name => "Qiryat Bialik", :aliases => "Kir'jat-Bjalik,Qiryat Bialik,Qiryat Bialiq,Qiryat-Beyaliq,ÐÐ¸ÑÑÑÑ-ÐÑÐ»Ð¸Ðº,Qiryat Bialik", :latitude => "32.8275", :longitude => "35.08583").save
City.new(:country_id => "105", :name => "Qiryat Ata", :aliases => "Kefar `Atah,Kefar `Atta,Kefar âAtah,Kefar âAá¹­á¹­a,Kefr Ata,Kir'jat-Ata,Kiryat-Ata,Kufritta,Qiryat Ata,Qiryat Atta,ÐÐ¸ÑÑÑÑ-ÐÑÐ°,Qiryat Ata", :latitude => "32.80056", :longitude => "35.10639").save
City.new(:country_id => "105", :name => "Qalansuwa", :aliases => "Qalansuwa,Qalansuwah,Qallansawah,Qalansuwa", :latitude => "32.28472", :longitude => "34.97972").save
City.new(:country_id => "105", :name => "Or Yehuda", :aliases => "Or Yehuda,Or Yehudah,Saqiya,Saqiyyah,SÄqiya,Or Yehuda", :latitude => "32.03111", :longitude => "34.84583").save
City.new(:country_id => "105", :name => "Ofaqim", :aliases => "Ofakim,Ofaqim,Ofiqim,Ofaqim", :latitude => "31.28333", :longitude => "34.61667").save
City.new(:country_id => "105", :name => "Netivot", :aliases => "Azata,Azzata,Netivot,ÐÐµÑÐ¸Ð²Ð¾Ñ,Netivot", :latitude => "31.41667", :longitude => "34.58333").save
City.new(:country_id => "105", :name => "Netanya", :aliases => "Lungsod ng Ntanya,Natania,Natanja,Natanya,Nathanya,Netan'ja,Netania,Netanja,Netanya,Ntanya,ntnyh,ÐÐµÑÐ°Ð½ÑÑ,× ×ª× ××,Netanya", :latitude => "32.33361", :longitude => "34.85778").save
City.new(:country_id => "105", :name => "Ness Ziona", :aliases => "Nahalat Reuven,Nes Siyona,Nes Tsiyona,Nes Tsiyonah,Nes Ziyona,Nes Ziyyona,Nes áºiyyona,Ness Siona,Ness Ziona,Neys-Siyona,Noss Ziona,NÄs TsÄ«yÅnÄ,NÄs ZÄ«yÅnÄ,Wadi Hunayn,Wadi Hunein,Wady Hanin,WÄdi Hunein,Ness Ziona", :latitude => "31.92933", :longitude => "34.79868").save
City.new(:country_id => "105", :name => "Nesher", :aliases => "Neixer,Nescher,Nesher,nsr,ÐÐµÑÐµÑ,× ×©×¨,Nesher", :latitude => "32.765", :longitude => "35.05").save
City.new(:country_id => "105", :name => "Nazareth", :aliases => "En Nasira,En NÄsira,Lungsod ng Nazaret,Naatsaret,Nasaret,Nasira,NasÄ±ra,Natseret,Natsrat,NatsÃ©ret,Natzaret,Nazara,Nazare,Nazaret,Nazaretas,Nazareth,Nazareto,NazarÃ©,Nazerat,Nazzerat,Naáºerat,Naáºáºerat,NÄtsrat,alnasrt,na sa lei,nacarettu,nasales,nasrt,nazare,nsrt,nzrt,ÎÎ±Î¶Î±ÏÎ­Ï,ÐÐ°Ð·Ð°ÑÐµÑ,× ×¦×¨×ª,Ø§ÙÙØ§ØµØ±Ø©,ÙØ§ØµØ±Ø©,Ü¢Ü¨ÜªÜ¬,à®¨à®¾à®à®°à¯à®¤à¯à®¤à¯,ãã¶ã¬,æ¿æå,ëì¬ë ,Nazareth", :latitude => "32.70361", :longitude => "35.29556").save
City.new(:country_id => "105", :name => "Nahariyya", :aliases => "Nagarija,Nahariya,Nahariyah,Nahariyya,ÐÐ°Ð³Ð°ÑÐ¸Ñ,Nahariyya", :latitude => "33.00583", :longitude => "35.09472").save
City.new(:country_id => "105", :name => "Migdal Ha`Emeq", :aliases => "Magidal,Migdal Ha`Emeq,Migdal Haemeqck,Migdal Hameq,Migdal HaâEmeq,Migdal' KhaEhmek,ÐÐ¸Ð³Ð´Ð°Ð»Ñ Ð¥Ð°Ð­Ð¼ÐµÐº,Migdal HaâEmeq", :latitude => "32.67139", :longitude => "35.24056").save
City.new(:country_id => "105", :name => "Mevo Betar", :aliases => "Mevo Beitar,Mevo Beiter,Mevo Betar,Mevo Beter,Mevoot Beitar,Mevoot Beiter,Mevoot Betar,Mevo Betar", :latitude => "31.71667", :longitude => "35.1").save
City.new(:country_id => "105", :name => "Maghar", :aliases => "El Mansura,Ma`ariyah,Maghar,MaghÄr,Maâariyah,Mughar,MaghÄr", :latitude => "32.88694", :longitude => "35.40694").save
City.new(:country_id => "105", :name => "Lod", :aliases => "Lida,Lidd,Lod,Lud,Ludd,Lydda,LÅ«d,alld,lwd,ÐÐ¾Ð´,×××,Ø§ÙÙØ¯,Lod", :latitude => "31.95139", :longitude => "34.89528").save
City.new(:country_id => "105", :name => "Kefar Sava", :aliases => "Kafr Saba,Kefar Saba,Kefar Sava,Kefar-Sava,KefÃ¡r Saba,ÐÐµÑÐ°Ñ-Ð¡Ð°Ð²Ð°,×××¨ ×¡××,Kefar Sava", :latitude => "32.175", :longitude => "34.90694").save
City.new(:country_id => "105", :name => "Karmi'el", :aliases => "Carmiel,Karmi'el,Karmiehl',Karmiâel,Qiryat Karmiel,ÐÐ°ÑÐ¼Ð¸ÑÐ»Ñ,Karmiâel", :latitude => "32.91722", :longitude => "35.30417").save
City.new(:country_id => "105", :name => "Kafr Qasim", :aliases => "Kafar Qasem,Kafar QÄsem,Kafer-Kassim,Kafr Qasim,Kafr QÄsim,Kasim,Kefar Qesem,Kufr Qasim,Kufr QÄsim,Kafr QÄsim", :latitude => "32.11417", :longitude => "34.97389").save
City.new(:country_id => "105", :name => "Kafr Manda", :aliases => "Kafar Manda,Kafer-Manda,Kafr Manda,Kafr MandÄ,Kefar Mandi,Kafr MandÄ", :latitude => "32.80722", :longitude => "35.26028").save
City.new(:country_id => "105", :name => "Kafr Kanna", :aliases => "Kafr Kanna,Kafr KannÄ,Kafr Qanah,Kafr KannÄ", :latitude => "32.75", :longitude => "35.34167").save
City.new(:country_id => "105", :name => "Judeida", :aliases => "Al Judeida,Judaydah,Judeida,Judeida", :latitude => "32.92556", :longitude => "35.155").save
City.new(:country_id => "105", :name => "Holon", :aliases => "Cholon,Holon,HÌ±olon,Jolon,JolÃ³n,Kholon,hwlwn,Ð¥Ð¾Ð»Ð¾Ð½,×××××,Ø­ÙÙÙÙ,HÌ±olon", :latitude => "32.01139", :longitude => "34.77222").save
City.new(:country_id => "105", :name => "Hod HaSharon", :aliases => "Hada Ramatayim,Hadar Ramataim,Hadar Ramatayim,Hod HaSharon,Ramatayim,hwd hsrwn,××× ××©×¨××,Hod HaSharon", :latitude => "32.15083", :longitude => "34.88833").save
City.new(:country_id => "105", :name => "Herzliyya", :aliases => "Gerclija,Herseliya,Hertseliyya,Hertsliyah,Hertzlija,Hervlia,Hervlia B,Herzlia B,Herzlija,Herzliya,Herzliyah,Herzliyya,Heráºliyya,Lungsod ng Herzliyya,Lungsod ng Heráºliyya,hrzlyh,ÐÐµÑÑÐ»Ð¸Ñ,××¨×¦×××,Herzliyya", :latitude => "32.16583", :longitude => "34.83667").save
City.new(:country_id => "105", :name => "Haifa", :aliases => "Caiffa,Haifa,Hajfa,Hajfo,Hayfa,HaÃ¯fa,Hefa,Heifa,HeifÄ,Heyfa,HÌ±efa,Khajfa,Lungsod ng Hefa,Lungsod ng á¸¤efa,hai fa,haifa,hyfa,hyph,ypw,Ä¤ajfo,Ð¥Ð°Ð¹ÑÐ°,×××¤×,××¤Ö¿×,Ø­ÙÙØ§,Ø­ÛÙØ§,á¸¤eyfa,ãã¤ãã¡,æµ·æ³,Haifa", :latitude => "32.81556", :longitude => "34.98917").save
City.new(:country_id => "105", :name => "Hadera", :aliases => "Chadera,El Khudeira,Hadera,Haderah,Hadeyra,Hedera,Hedora,Hudeira,HÄdÄrÄ,HÌ±adera,Khadera,Khederah,hdrh,Ð¥Ð°Ð´ÐµÑÐ°,×××¨×,HÌ±adera", :latitude => "32.43528", :longitude => "34.9175").save
City.new(:country_id => "105", :name => "Giv`at Shemu'el", :aliases => "Giv`at Shemu'el,Giv`at Shmuel,Givâat Shemuâel,Givâat Shmuel,Givâat Shemuâel", :latitude => "32.07528", :longitude => "34.84667").save
City.new(:country_id => "105", :name => "Giv`atayim", :aliases => "Gevataym,Giv`atayim,Givataim,Givâatayim,ÐÐ¸Ð²Ð°ÑÐ°Ð¸Ð¼,Givâatayim", :latitude => "32.06972", :longitude => "34.81167").save
City.new(:country_id => "105", :name => "Tirah", :aliases => "At Tira,Et Tira,Et Tire,Eá¹­ á¹¬Ä«ra,Tira,Tirah,TÄ«ra,Tirah", :latitude => "32.23278", :longitude => "34.95028").save
City.new(:country_id => "105", :name => "Et Taiyiba", :aliases => "At Taiyiba,E-Tayibe,El Taiyiba,Et Taiyiba,Et Taiyibe,Et Tayyibeh,Eá¹­ á¹¬aiyiba,Taibe,Taiyba,Taiyiba,Taiyibah,Taiyibe,Taiyibi,Taybah,Tayibe,Tayibeh,Tiva,TÄ«vÄ,á¹¬aiyibe,á¹¬ayibe,Eá¹­ á¹¬aiyiba", :latitude => "32.26472", :longitude => "35.00806").save
City.new(:country_id => "105", :name => "Er Reina", :aliases => "Ar Reina,Er Reina,Raynah,Reina,Reine,Er Reina", :latitude => "32.72361", :longitude => "35.3125").save
City.new(:country_id => "105", :name => "Elat", :aliases => "Ehjlat,Eilat,Ejlat,Ejlato,Elat,Elath,Etzion Geber,Lungsod ng Elat,Umm Rashrash,Umm RashrÄsh,Umrashash,ai la te,aylat,eirato,Ãilat,ÐÐ¸Ð»Ð°Ñ,ÐÐ¹Ð»Ð°Ñ,Ð­Ð¹Ð»Ð°Ñ,××××ª,Ø¥ÙÙØ§Øª,Ø§ÛÙØ§Øª,ã¨ã¤ã©ã¼ã,åæç¹,Elat", :latitude => "29.56111", :longitude => "34.95167").save
City.new(:country_id => "105", :name => "Dimona", :aliases => "Dimona,Domona,dymwnh,ÐÐ¸Ð¼Ð¾Ð½Ð°,××××× ×,Dimona", :latitude => "31.06667", :longitude => "35.03333").save
City.new(:country_id => "105", :name => "Daliyat el Karmil", :aliases => "Carmel City,Daliyah,Daliyat ad-Druz,Daliyat al-Karmil,Daliyat at Karmil,Daliyat el Karmil,DÄliyat el Karmil,Karmel',ÐÐ°ÑÐ¼ÐµÐ»Ñ,DÄliyat el Karmil", :latitude => "32.69361", :longitude => "35.04083").save
City.new(:country_id => "105", :name => "Bet Shemesh", :aliases => "Beit Semes,Beit ÅemeÅ,Beit-Shemesh,Bejt-Shemesh,Bet Schemesch,Bet Shemesh,Betxemeix,BetxÃ¨meix,Maabarat Hartuv,byt sms,ÐÐµÐ¹Ñ-Ð¨ÐµÐ¼ÐµÑ,×××ª ×©××©,Bet Shemesh", :latitude => "31.75", :longitude => "35").save
City.new(:country_id => "105", :name => "Bet She'an", :aliases => "Beisan,BeisÄn,Beit Shean,Beit-Shean,Beith Shean,Beith SheÄn,Bejt-Shean,Besan,Bet Sche'an,Bet She'an,Bet Shean,Bet Sheâan,Bet Szean,Beth Shan,BeÃ¯t ShÃ©an,BeÃ¯t-ShÃ©an,Scythopolis,Skythopolis,bysan,ÐÐµÐ¹Ñ-Ð¨ÐµÐ°Ð½,×××ª ×©××,Ø¨ÙØ³Ø§Ù,Bet Sheâan", :latitude => "32.5", :longitude => "35.5").save
City.new(:country_id => "105", :name => "Bene Beraq", :aliases => "Benai Beraq,Bene Beraq,Benei Beraq,Beney Beraq,Bene Beraq", :latitude => "32.09028", :longitude => "34.83972").save
City.new(:country_id => "105", :name => "Beersheba", :aliases => "B'er Sheva',B'eyr-Sheva',Be'er Seva,Be'er Sheva,Be'er Sheva`,Be'er Å eva,Be'er-Sheva',Be'Ã©r-Shevaâ,Beehr-Sheva,Beer Seva,Beer Sheba,Beer Sheva,Beer Sjeva,Beer Szewa,Beer Åeva,Beer Å eva,Beer-Sheva,Beerscheba,Beersheba,Beerxeba,Ber Seva,Ber Å eva,Bersabee,BersabÃ©e,Berseba,BersÃ©ba,BeÃ«r Sjeva,Bir el Saba,Bir es Sab`,Bir es Sabe,Bâer Shevaâ,Lungsod ng B'er Sheva',Lungsod ng Bâer Shevaâ,beeleusyeba,ÐÐµÐµÑ Ð¨ÐµÐ²Ð°,ÐÐµÑÑ-Ð¨ÐµÐ²Ð°,×××¨ ×©××¢,Ø¨Ø¦Ø± Ø§ÙØ³Ø¨Ø¹,ë² ìë¥´ì°ë°,Beersheba", :latitude => "31.25181", :longitude => "34.7913").save
City.new(:country_id => "105", :name => "Bat Yam", :aliases => "Bat Jam,Bat Yam,Bat-Jam,bt ym,ÐÐ°Ñ-Ð¯Ð¼,××ª ××,Bat Yam", :latitude => "32.02306", :longitude => "34.75028").save
City.new(:country_id => "105", :name => "Ashqelon", :aliases => "Al Majdal,Ashkelon,Ashqelon,Ashquelon,El Majdal,El Medjdel,Majdal,Majdal `Asqalan,Majdal âAsqalÄn,Migdal Ascalon,Migdal Ashqelon,Migdal Gad,Ê¼aseqelwon,ÐÑÐºÐµÐ»Ð¾Ð½,×Ö·×©Ö°××§Ö°××Ö¹×,Ashqelon", :latitude => "31.66667", :longitude => "34.58333").save
City.new(:country_id => "105", :name => "Ashdod", :aliases => "Aschdod,Asdod,Ashdod,Ashdod Yam,Ashdod on the Sea,Aszdod,AÅdod,Ukreir,ÐÑÐ´Ð¾Ð´,××©×××,Ashdod", :latitude => "31.81667", :longitude => "34.65").save
City.new(:country_id => "105", :name => "`Akko", :aliases => "Accho,Acre,Acre - ×¢××,Acri,Akka,Akkia,Akko,Akre,Antiocheia,Ptolemais,Saint Jean d'Acre,Saint Jean dâAcre,San Giovanni d'Acri,`Akka,`Akko,a ka,akko,ÎÎ½ÏÎ¹ÏÏÎµÎ¹Î±,ÐÐºÐºÐ¾,×¢××,Ø¹ÙØ§,âAkka,âAkko,ã¢ãã³,é¿å¡,âAkko", :latitude => "32.92361", :longitude => "35.07278").save
City.new(:country_id => "105", :name => "`Afula `Illit", :aliases => "Upper Afula,`Afula `Elit,`Afula `Illit,`Afulah `Ilith,`Afulla `Illit,âAfula âElit,âAfula âIllit,âAfulla âIllit,âAfÅ«lÄh âIlÄ«th,âAfula âIllit", :latitude => "32.63333", :longitude => "35.33333").save
City.new(:country_id => "105", :name => "Petah Tikva", :aliases => "Petakh-Tikva,ÐÐµÑÐ°Ñ-Ð¢Ð¸ÐºÐ²Ð°,Petah Tikva", :latitude => "32.09174", :longitude => "34.88503").save
City.new(:country_id => "105", :name => "Old City", :aliases => ",Old City", :latitude => "31.77667", :longitude => "35.23417").save
City.new(:country_id => "105", :name => "West Jerusalem", :aliases => "Jerusalem West,Vaestra Jerusalem,Vest-Jerusalem,Vestjerusalem,VÃ¤stra Jerusalem,West Jerusalem,Westjerusalem,West Jerusalem", :latitude => "31.78199", :longitude => "35.21961").save
