City.new(:country_id => "109", :name => "Zakhu", :aliases => "Zakho,Zakhu,Zaxo,ZÄkhÅ«,zakhw,ÐÐ°ÑÑ,Ø²Ø§Ø®Ù,Ø²Ø§Ø®Û,ZÄkhÅ«", :latitude => "37.14817", :longitude => "42.70008").save
City.new(:country_id => "109", :name => "Tozkhurmato", :aliases => "Khurmati,Touz Hourmato,Tozkhurmato,Tozkhurmatu,Tuz,Tuz Kermatli,Tuz Khurmatli,Tuzkhurmatu,Å¢Å«zkhÅ«rmÄtÅ«,Ø·ÙØ²Ø®ÙØ±ÙØ§ØªÙ,Tozkhurmato", :latitude => "34.89046", :longitude => "44.62994").save
City.new(:country_id => "109", :name => "Tikrit", :aliases => "Tekrit,Tikret,Tikrit,Tikritas,TikrÄ«t,ti ke li te,tikurito,tkryt,tykryt,Ð¢Ð¸ÐºÑÐ¸Ñ,×ª×××¨××ª,ØªÙØ±ÙØª,ØªÚ©Ø±ÛØª,ãã£ã¯ãªã¼ã,æåéç¹,TikrÄ«t", :latitude => "34.60712", :longitude => "43.67822").save
City.new(:country_id => "109", :name => "Qada' Talkif", :aliases => "Qada' Talkif,Qaá¸Äâ TalkÄ«f,Tall Kaif,Tall Kayf,Tall'-Kajf,Tel Kaif,Ð¢Ð°Ð»Ð»Ñ-ÐÐ°Ð¹Ñ,ÙØ¶Ø§Ø¡ ØªÙÙÙÙ,Qaá¸Äâ TalkÄ«f", :latitude => "36.48944", :longitude => "43.11917").save
City.new(:country_id => "109", :name => "Sinah", :aliases => "Sina,Sinah,Sine,SÃ®ne,SÄ«nah,SÄ«nÄ,Ø³ÙÙØ©,Ø³ÙÙÛ,SÄ«nah", :latitude => "36.80902", :longitude => "43.03886").save
City.new(:country_id => "109", :name => "Samarra'", :aliases => "Saimarreh,Samarra,Samarra',Samarrah,SÄmarrah,SÄmarrÄâ,Ø³Ø§ÙØ±Ø§Ø¡,SÄmarrÄâ", :latitude => "34.20096", :longitude => "43.87562").save
City.new(:country_id => "109", :name => "Saddat al Hindiyah", :aliases => "Al Hindiyah,Al HindÄ«yah,Hindiya,HindÄ«ya,Nahiyat Saddat al Hindiyah,NÄá¸©Ä«yat Saddat al HindÄ«yah,Qaryat Saddat al Hindiyah,Qaryat Saddat al HindÄ«yah,Saddat al Hindiyah,Saddat al HindÄ«yah,Saddat al HindÄ«yah", :latitude => "32.71472", :longitude => "44.28028").save
City.new(:country_id => "109", :name => "Rawanduz", :aliases => "Ravanduz,Rawandiz,Rawandoz,Rawanduz,Rawndoz,RawÄndiz,Revandis,Rewandus,Roandiz,Roanduz,Rowanduz,RowandÅ«z,Ruwan Duz,Ruwandiz,Ruwanduz,RuwÄndiz,RuwÄndÅ«z,RÄwandÅ«z,Ð Ð°Ð²Ð°Ð½Ð´ÑÐ·,Ø±Ø§ÙÙØ¯ÙØ²,RÄwandÅ«z", :latitude => "36.61578", :longitude => "44.52752").save
City.new(:country_id => "109", :name => "Rawah", :aliases => "Rawa,Rawah,RÄwah,Ø±Ø§ÙØ©,RÄwah", :latitude => "34.48164", :longitude => "41.9093").save
City.new(:country_id => "109", :name => "Qada' al Hamdaniyah", :aliases => "Al Hamdaniya,Al Hamdaniyah,Qada' al Hamdaniyah,Qarah Qosh,Qarah Qush,Qarah QÅsh,Qarah QÅ«sh,Qaraqosh,Qaraqush,Qaá¸Äâ al á¸¨amdÄnÄ«yah,ÙØ¶Ø§Ø¡ Ø§ÙØ­ÙØ¯Ø§ÙÙØ©,Qaá¸Äâ al á¸¨amdÄnÄ«yah", :latitude => "36.27146", :longitude => "43.37373").save
City.new(:country_id => "109", :name => "Mandali", :aliases => "Mandali,MandalÄ«,Mendali,Mendeli,MendÃ©li,ÐÐ°Ð½Ð´Ð°Ð»Ð¸,ÙÙØ¯ÙÙ,MandalÄ«", :latitude => "33.74986", :longitude => "45.5541").save
City.new(:country_id => "109", :name => "Kuysanjaq", :aliases => "Koi Sanjaq,Kou Senaq,Kou Senjaq,Koy Senjaq,Koye,Koysinjaq,Kuysanjaq,KÅ«ysanjaq,ÙÙÙØ³ÙØ¬Ù,ÙÛÙÛ,KÅ«ysanjaq", :latitude => "36.08616", :longitude => "44.62941").save
City.new(:country_id => "109", :name => "Kifri", :aliases => "Kiffri,KiffrÄ«,Kifri,KifrÄ«,Kufri,KufrÄ«,Salahie,Salahiya,Salahiyeh,Sallahiya,Sallahiyah,SalÄhÄ«ya,Zeng Abad,Zeng ÄbÄd,ÐÐ¸ÑÑÐ¸,ÙÙØ±Ù,KifrÄ«", :latitude => "34.69587", :longitude => "44.9661").save
City.new(:country_id => "109", :name => "Kirkuk", :aliases => "Karkh Slukh,Karkuk,KarkÅ«k,Kerkouk,Kerkuek,Kerkuk,KerkÃ»k,KerkÃ¼k,Kirkoek,Kirkouk,Kirkuk,KirkÅ«k,kileukukeu,kirukuku,krkwk,ÐÐ¸ÑÐºÑÐº,ÙØ±ÙÙÙ,ÙÙâØ±ÙÙÙÙ,ÙÛØ±ÙÙÙ,Ú©Ø±Ú©ÙÚ©,ã­ã«ã¯ã¼ã¯,í¤ë¥´ì¿ í¬,Kirkuk", :latitude => "35.46806", :longitude => "44.39222").save
City.new(:country_id => "109", :name => "Karbala'", :aliases => "Karbala,Karbala',Karbalaa,KarbalÄâ,Karbila,Kerbala,Kerbela,Meshed Hussain,Meshed Hussein,Nainawa,Shathi'ul-Furat,Vilojati Karbalo,al-Ghadiriya,karubara,karubara xian,krbla,ktrbala,ÐÐ¸Ð»Ð¾ÑÑÐ¸ ÐÐ°ÑÐ±Ð°Ð»Ð¾,ÐÐ°ÑÐ±Ð°Ð»Ð°,ÐÐµÑÐ±Ð°Ð»Ð°,ÐÐµÑÐ±ÐµÐ»Ð°,××¨×××,×××× ××¨×××,ÙØ©Ø±Ø¨Ø§ÙØ§,ÙØ±Ø¨ÙØ§Ø¡,ÙØ­Ø§ÙØ¸Ø© ÙØ±Ø¨ÙØ§Ø¡,Ú©Ø±Ø¨ÙØ§,ã«ã«ãã©ã¼,ã«ã«ãã©ã¼ç,KarbalÄâ", :latitude => "32.61144", :longitude => "44.00847").save
City.new(:country_id => "109", :name => "Arbil", :aliases => "(Erbil),Arba`ilu,Arbaâilu,Arbeel,Arbela,Arbil,Arbil Governorate,ArbÄla,ArbÄ«l,Erbil,Hawler,HawlÄr,Hewler,HewlÃªr,Irbil,IrbÄ«l,Viloati Arbil,ai er bi lei sheng,arbyl,arubiru xian,mhafzt arbyl,ÐÑÐ±Ð¸Ð»,ÐÐ¸Ð»Ð¾ÑÑÐ¸ ÐÑÐ±Ó£Ð»,×××× ××¨×××,Ø£Ø±Ø¨ÙÙ,Ø¥Ø±Ø¨ÙÙ,Ø§Ø±Ø¨ÛÙ,ÙØ­Ø§ÙØ¸Ø© Ø£Ø±Ø¨ÙÙ,ÙÛÙÙÛØ±,ã¢ã«ãã¼ã«ç,åç¾æ¯åç,ArbÄ«l", :latitude => "36.19257", :longitude => "44.01062").save
City.new(:country_id => "109", :name => "Hit", :aliases => "Hit,HÄ«t,ÙÙØª,HÄ«t", :latitude => "33.64159", :longitude => "42.82509").save
City.new(:country_id => "109", :name => "Halabjah", :aliases => "Alabja,Halabdscha,Halabia,Halabja,Halebdja,Halebja,Halebjeh,Halepce,HalepÃ§e,Helepce,HelepÃ§e,Khalabdzha,hlbchh,hlbjt,Ð¥Ð°Ð»Ð°Ð±Ð´Ð¶Ð°,Ø­ÙØ¨Ø¬Ø©,Ø­ÙØ¨ÚÙ,á¸¨alabjah", :latitude => "35.17778", :longitude => "45.98611").save
City.new(:country_id => "109", :name => "Hadithah", :aliases => "Al Hadithah,Al á¸¨adÄ«thah,Haditha,Hadithah,Khadita,Ð¥Ð°Ð´Ð¸ÑÐ°,á¸¨adÄ«thah,á¸¨adÄ«thah", :latitude => "34.13972", :longitude => "42.37806").save
City.new(:country_id => "109", :name => "Chamchamal", :aliases => "Chamchamal,ChamchamÄl,Chemchemal,ChemchemÄl,Shamshamal,ShamshamÄl,ÚÙÚÙØ§Ù,ChamchamÄl", :latitude => "35.53653", :longitude => "44.83167").save
City.new(:country_id => "109", :name => "Bayji", :aliases => "Baiji,Bajdzhi,Bayji,BayjÄ«,ÐÐ°Ð¹Ð´Ð¶Ð¸,Ø¨ÙØ¬Ù,BayjÄ«", :latitude => "34.93114", :longitude => "43.487").save
City.new(:country_id => "109", :name => "Ba`qubah", :aliases => "Ba'quba,Ba`qubah,Bakouba,Bakuba,Baquba,Baqubah,Baqubeh,BaâqÅ«bah,BaâqÅ«ba,ba gu bai,ÐÐ°ÐºÑÐ±Ð°,Ø¨Ø¹ÙÙØ¨Ø©,å·´å¤æ,BaâqÅ«bah", :latitude => "33.74846", :longitude => "44.65545").save
City.new(:country_id => "109", :name => "Paynjuwayn", :aliases => "Banjuwayn,Banjwin,BanjwÄ«n,Pandjvin,Panjvin,Panjwin,PanjwÄ«n,Paynjuwayn,Pencwen,Pendjevin,Pendjevine,Pendsevine,Penjevin,Penjvin,PenjvÄ«n,Penjwen,Penjwin,PÃªncwÃªn,Ø¨ÙØ¬ÙÙÙ,Ù¾ÙØ¬ÙÛÙ,Ù¾ÙÙØ¬ÙÛÙ,Ù¾ÛÙØ¬ÙÛÙ,Paynjuwayn", :latitude => "35.6183", :longitude => "45.9541").save
City.new(:country_id => "109", :name => "Balad", :aliases => "Balad,Balada,Belad,Beled,ÐÐ°Ð»Ð°Ð´Ð°,Ø¨ÙØ¯,Balad", :latitude => "34.01638", :longitude => "44.14531").save
City.new(:country_id => "109", :name => "Baghdad", :aliases => "Bagda,Bagdad,Bagdadas,Bagdado,Bagdat,Bagdate,Bagdatum,Bagdod,BagdÃ¡,BagdÃ¡d,Baghdad,BaghdÄd,BaÄdad,BaÄdat,Bexda,Lungsod ng Baghdad,ba ge da,bagadada,bageudadeu,bagudado,bgdd,bghdad,paktat,ÎÎ±Î³Î´Î¬ÏÎ·,ÐÐ°Ð³Ð´Ð°Ð´,ÐÐ°ÒÐ´Ð¾Ð´,Ô²Õ¡Õ²Õ¤Õ¡Õ¤,×××××,Ø¨ØºØ¯Ø§Ø¯,ÜÜÜÜ,à¤¬à¤à¤¦à¤¾à¤¦,à®ªà®¾à®à¯à®¤à®¾à®¤à¯,à½à¼à½à¼à½,á£áá³áµ,ãã°ãã¼ã,å·´æ ¼è¾¾,ë°ê·¸ë¤ë,Baghdad", :latitude => "33.34058", :longitude => "44.40088").save
City.new(:country_id => "109", :name => "Az Zubayr", :aliases => "Az Zubair,Az Zubayr,Az Zuhair,El Zubair,Zobier,Zubair,Ø§ÙØ²Ø¨ÙØ±,Az Zubayr", :latitude => "30.39447", :longitude => "47.70114").save
City.new(:country_id => "109", :name => "As Suwayrah", :aliases => "As Suwayrah,AÅ Åuwayrah,Jazira,JazÄ«ra,Jumeiseh,Juweimiseh,Sewairah,Suvajra,Suwaira,Suweireh,Suweiri,Ð¡ÑÐ²Ð°Ð¹ÑÐ°,AÅ Åuwayrah", :latitude => "32.92556", :longitude => "44.77583").save
City.new(:country_id => "109", :name => "As Sulaymaniyah", :aliases => "Al-Sulaimaniya,As Sulaymaniyah,As SulaymÄnÄ«yah,As-Sulaymaniyah,Silemani,SilÃªmanÃ®,Sleimani,SleimÄni,Slemani,SlÄmÄnÄ«,Souleymaniah,Sueleymaniye,Sulaimania,Sulaimanieh,Sulaimaniya,Sulajmanijja,Sulaymaniyah,SulaymÄnÄ«yah,Suleimania,Suleimaniya,Sulejmanija,SÃ¼leymaniye,shhr slymanyh,slymanyh,Ð¡ÑÐ»ÐµÐ¹Ð¼Ð°Ð½Ð¸Ñ,Ø§ÙØ³ÙÙÙØ§ÙÙØ©,Ø³ÙÛÙØ§ÙÛÙ,Ø³ÙÛÙØ§ÙÛ,Ø´ÙØ± Ø³ÙÛÙØ§ÙÛÙ,As SulaymÄnÄ«yah", :latitude => "35.56113", :longitude => "45.43749").save
City.new(:country_id => "109", :name => "As Samawah", :aliases => "As Samawah,As SamÄwah,SAMAWA,Samava,Samawa,Samawah,SamÄwah,Ð¡Ð°Ð¼Ð°Ð²Ð°,Ø§ÙØ³ÙØ§ÙÙ,As SamÄwah", :latitude => "31.33198", :longitude => "45.2944").save
City.new(:country_id => "109", :name => "Nahiyat ash Shinafiyah", :aliases => "Ash Shinafiyah,Ash ShinÄfÄ«yah,Chinafiyah,Nahiyat ash Shinafiyah,NÄá¸©iyat ash ShinÄfÄ«yah,Shannafiuah,Shenafiya,ShenÄfiya,Shinafie,Shinafiya,Shinafiyeh,ShinÄfiya,Ø§ÙØ´ÙØ§ÙÙØ©,ÙØ§Ø­ÙØ© Ø§ÙØ´ÙØ§ÙÙØ©,NÄá¸©iyat ash ShinÄfÄ«yah", :latitude => "31.58737", :longitude => "44.66016").save
City.new(:country_id => "109", :name => "Ash Shatrah", :aliases => "Ash Shatrah,Ash ShaÅ£rah,Shatra,Shatrat al Muntafiq,Shatreh,Shatret el Muntefiq,Shattra,Shattrah el Muntifik,Ø§ÙØ´Ø·Ø±Ø©,Ash ShaÅ£rah", :latitude => "31.41171", :longitude => "46.17418").save
City.new(:country_id => "109", :name => "Ash Shamiyah", :aliases => "Ash Shamiya,Ash Shamiyah,Ash ShÄmÄ«ya,Ash ShÄmÄ«yah,Shamiya,Ummal Barur,Ø§ÙØ´Ø§ÙÙØ©,Ash ShÄmÄ«yah", :latitude => "31.96362", :longitude => "44.59904").save
City.new(:country_id => "109", :name => "Ar Rutbah", :aliases => "Al Rutbah,Ar Rutbah,Ar RuÅ£bah,Rutba,Rutbah,Ø§ÙØ±Ø·Ø¨Ø©,Ar RuÅ£bah", :latitude => "33.03807", :longitude => "40.28482").save
City.new(:country_id => "109", :name => "Ar Rumaythah", :aliases => "Al-Rumitha,Ar Rumaythah,Rumaith,Rumaitha,Rumaithah,Rumeitheh,Rumetha,Ubaiyidh,Ø§ÙØ±ÙÙØ«Ø©,Ar Rumaythah", :latitude => "31.52629", :longitude => "45.20246").save
City.new(:country_id => "109", :name => "Ar Ramadi", :aliases => "Al-Rumadi,Ar Ramadi,Ar RamÄdÄ«,Ramadi,Ramadie,Ramadieh,Ramadiyah,Rumadiya,Rumadiyeh,RumÄdÄ«ya,RumÄdÄ«yeh,alrmady,rmady,Ð Ð°Ð¼Ð°Ð´Ð¸,Ø§ÙØ±ÙØ§Ø¯Ù,Ø±ÙØ§Ø¯Û,Ar RamÄdÄ«", :latitude => "33.42257", :longitude => "43.30584").save
City.new(:country_id => "109", :name => "An Nasiriyah", :aliases => "Al-Nasiriya,An Nasiriya,An Nasiriyah,An NÄsirÄ«ya,An NÄÅirÄ«yah,An-Nasiriya,Muntafik,Muntifik,Nasirija,Nasirijja,Nasiriya,Nasiriyah,Nasiriyeh,Nasiriyya,Nasrie,Nasriye,NÄsirÄ«yah,alnasryt,nashiriya,ÐÐ°ÑÐ¸ÑÐ¸Ñ,Ø§ÙÙØ§ØµØ±ÙØ©,Ø§ÙÙØ§ØµØ±ÙÙ,ãã¼ã·ãªã¼ã¤,An NÄÅirÄ«yah", :latitude => "31.05205", :longitude => "46.26102").save
City.new(:country_id => "109", :name => "An Najaf al Ashraf", :aliases => "Al Najaf al Ashraf,An Najaf,An Najaf al Ashraf,An-Najaf,Ehn-Nadzhaf,Meshed 'Ali,Meshed âAli,Nadjaf,Nadschaf,Nadzaf,Nadzhaf,NadÅ¼af,Nagaf,Najaf,Najaf - njf,Najaf - ÙØ¬Ù,Nayaf,NaÄaf,Nedjef,Neshed Ali,alnjf,na jie fu,najafu,ng'p,njf,ÐÐ°Ð´Ð¶Ð°Ñ,ÐÐ°ÑÐ°Ñ,Ð­Ð½-ÐÐ°Ð´Ð¶Ð°Ñ,× ×'×£,Ø§ÙÙØ¬Ù,Ø§ÙÙØ¬Ù Ø§ÙØ§Ø´Ø±Ù,ÙØ¬Ù,ãã¸ã£ã,ç´æ°å¤«,An Najaf al Ashraf", :latitude => "31.99854", :longitude => "44.33976").save
City.new(:country_id => "109", :name => "`Anat al Qadimah", :aliases => "Ana,Anah,`Anah,`Anat al Qadimah,Ø¹ÙØ© Ø§ÙÙØ¯ÙÙØ©,âAnat al QadÄ«mah,âÄnah,âAnat al QadÄ«mah", :latitude => "34.46589", :longitude => "41.9331").save
City.new(:country_id => "109", :name => "Al Qasim", :aliases => "Al Qasim,Al QÄsim,Al'-Kasim,Imam Qasim,Qasim,QÄsim,ÐÐ»Ñ-ÐÐ°ÑÐ¸Ð¼,Ø§ÙÙØ§Ø³Ù,Al QÄsim", :latitude => "32.29799", :longitude => "44.68281").save
City.new(:country_id => "109", :name => "Al Musayyib", :aliases => "Al Musaiyib,Al Musayyib,Al'-Ehl'-Musajibe,Mosayab,Musaiyib,Musayyib,MusaÄ«yib,Museyib,ÐÐ»Ñ-Ð­Ð»Ñ-ÐÑÑÐ°Ð¹Ð¸Ð±Ðµ,Ø§ÙÙØ³ÙØ¨,Al Musayyib", :latitude => "32.78332", :longitude => "44.28251").save
City.new(:country_id => "109", :name => "Al Mishkhab", :aliases => "Al Faysaliyah,Al FayÅalÄ«yah,Al Mishkhab,Al MishkhÄb,Faisailiya,Ø§ÙÙØ´Ø®Ø§Ø¨,Al MishkhÄb", :latitude => "31.80416", :longitude => "44.49107").save
City.new(:country_id => "109", :name => "Al Miqdadiyah", :aliases => "Al Miqdadiyah,Al MiqdÄdÄ«yah,Muqdadiyah,Shahraban,Shahroban,ShahrÄbÄn,Al MiqdÄdÄ«yah", :latitude => "33.97861", :longitude => "44.93694").save
City.new(:country_id => "109", :name => "Al Mawsil al Jadidah", :aliases => "Al Mawsil al Jadidah,Al MawÅil al JadÄ«dah,Ø§ÙÙÙØµÙ Ø§ÙØ¬Ø¯ÙØ¯Ø©,Al MawÅil al JadÄ«dah", :latitude => "36.33464", :longitude => "43.09777").save
City.new(:country_id => "109", :name => "Mosul", :aliases => "Al Mawsil,Al MawÅil,Al Musil,Al MÅ«Åil,Mosoel,Mossoul,Mossul,Mosul,Mosula,Moussoul,Musil,Musul,MÃ»sil,mosul,mosuru,mwsl,mwswl,ÐÐ¾ÑÑÐ»,×××¡××,ÙÙØµÙ,ã¢ã¼ã¹ã«,ëª¨ì ,Mosul", :latitude => "36.335", :longitude => "43.11889").save
City.new(:country_id => "109", :name => "Al Majar al Kabir", :aliases => "Al Majar al Kabir,Al Majar al KabÄ«r,Al Majarr al Kabir,Al Majarr al KabÄ«r,Al Mijar al Kabir,Al Mijar al KabÄ«r,Majar al Kabir,Majar al KabÄ«r,Ø§ÙÙØ¬Ø± Ø§ÙÙØ¨ÙØ±,Al Majar al KabÄ«r", :latitude => "31.58607", :longitude => "47.169").save
City.new(:country_id => "109", :name => "Al Kut", :aliases => "Al Koet,Al Kut,Al KÅ«t,Kut,Kut al Imara,Kut al ImÄra,Kut al `Amarah,Kut-al-Almarah,Kut-al-AlmÄrah,Kut-al-Imarah,KÅ«t,KÅ«t al âAmÄrah,KÅ«t-al-ImÄrah,kwt,ÐÑÑ,Ø§ÙÙÙØª,ÙÙØª,Al KÅ«t", :latitude => "32.5147", :longitude => "45.81902").save
City.new(:country_id => "109", :name => "Khalis", :aliases => "Al Khalis,Al KhÄliÅ,Al'-Khalisa,Diltawah,DiltÄwah,Khalis,KhÄliÅ,ÐÐ»Ñ-Ð¥Ð°Ð»Ð¸ÑÐ°,Ø®Ø§ÙØµ,KhÄliÅ", :latitude => "33.81996", :longitude => "44.52637").save
City.new(:country_id => "109", :name => "`Ali al Gharbi", :aliases => "Ali Gharbi,Ali el Gharbi,Imam Ali Gherbi,ImÄm Ali Gherbi,`Ali al Gharbi,Ø¹ÙÙ Ø§ÙØºØ±Ø¨Ù,âAlÄ« al GharbÄ«,âAlÄ« al GharbÄ«", :latitude => "32.46326", :longitude => "46.68637").save
City.new(:country_id => "109", :name => "Al Hindiyah", :aliases => "Al Hindiyah,Al HindÄ«yah,Hindiya,HindÄ«ya,Qada' al Hindiyah,Qaá¸Äâ al HindÄ«yah,Tuwairij,Tuwairji,TuwairÄ«j,Tuwayrij,Å¢uwayrÄ«j,Al HindÄ«yah", :latitude => "32.54333", :longitude => "44.2225").save
City.new(:country_id => "109", :name => "Al Hillah", :aliases => "Al Hilla,Al Hillah,Al á¸¨illah,Al'-Khilla,Al-Hella,Hilah,Hilla,Hille,HillÃ©,ÐÐ»Ñ-Ð¥Ð¸Ð»Ð»Ð°,Ø§ÙØ­ÙØ©,Al á¸¨illah", :latitude => "32.48014", :longitude => "44.43526").save
City.new(:country_id => "109", :name => "Al Hayy", :aliases => "Al Hai,Al Hay,Al Hayy,Al á¸¨ayy,Al'-Khaja,Kut al Hai,ÐÐ»Ñ-Ð¥Ð°Ñ,Ø§ÙØ­Ù,Al á¸¨ayy", :latitude => "32.17349", :longitude => "46.0433").save
City.new(:country_id => "109", :name => "Al Harithah", :aliases => "Al Harithah,Al HÄrithah,Al'-Kharrisa,Hartha,Harthah,ÐÐ»Ñ-Ð¥Ð°ÑÑÐ¸ÑÐ°,Al HÄrithah", :latitude => "30.71861", :longitude => "47.72083").save
City.new(:country_id => "109", :name => "Nahiyat Ghammas", :aliases => "Al Ghammas,Al GhammÄs,Ghammas,GhammÄs,Nahiyat Ghammas,NÄá¸©iyat GhammÄs,ØºÙØ§Ø³,ÙØ§Ø­ÙØ© ØºÙØ§Ø³,NÄá¸©iyat GhammÄs", :latitude => "31.74311", :longitude => "44.6196").save
City.new(:country_id => "109", :name => "Nahiyat al Fuhud", :aliases => "Al Fuhud,Al FuhÅ«d,Fuhud,FuhÅ«d,NÄá¸©iyat al FuhÅ«d", :latitude => "30.96972", :longitude => "46.72278").save
City.new(:country_id => "109", :name => "Al Faw", :aliases => "Al Faw,Al FÄw,Al'-Fau,Fao,Fao Terminal,Fava,ÐÐ»Ñ-Ð¤Ð°Ñ,Ø§ÙÙØ§Ù,Al FÄw", :latitude => "29.97763", :longitude => "48.47412").save
City.new(:country_id => "109", :name => "Al Fallujah", :aliases => "Al Falludza,Al FalludÅ¼a,Al Falluja,Al Fallujah,Al FallÅ«ja,Al FallÅ«jah,Al Falooja,Falloujah,Falludscha,Falluja,Fallujah,FallÅ«jah,Faludza,Faludzha,Faluga,Faluya,FaluÄa,Feludja,Feluja,faruja,fei lu jie,Ð¤Ð°Ð»ÑÐ´Ð¶Ð°,Ð¤Ð°Ð»ÑÑÐ°,Ø§ÙÙÙÙØ¬Ø©,ãã¡ã«ã¼ã¸ã£,è´¹å¢æ°,Al FallÅ«jah", :latitude => "33.3538", :longitude => "43.77951").save
City.new(:country_id => "109", :name => "Al Basrah", :aliases => "Al Basrah,Al BaÅrah,Al-Basra,Bacora,Basora,Basra,Basrah,Bassora,Bassorah,Bassra,BaÃ§orÃ¡,Busra,Busrah,Bussora,BÃ ssora,ba shi la,ba si la,basura,bsrh,bsrt,bzrh,ÐÐ°ÑÑÐ°,××¦×¨×,Ø§ÙØ¨ØµØ±Ø©,Ø¨ØµØ±Ø©,Ø¨ØµØ±Ù,ÜÜ¨ÜªÜ,ãã¹ã©,å·´å£«æ,å·´æ¯æ,Al BaÅrah", :latitude => "30.53488", :longitude => "47.78885").save
City.new(:country_id => "109", :name => "Al `Aziziyah", :aliases => "Al `Aziziya,Al `Aziziyah,Al âAziziya,Al âAzÄ«zÄ«yah,Al-Azizya,Al-AzÄ«zya,Azizie,Aziziya,Aziziyah,AzizÄ«ya,AzÄ«zÄ«yah,`Aziziyeh,Ø§ÙØ¹Ø²ÙØ²ÙØ©,âAziziyeh,Al âAzÄ«zÄ«yah", :latitude => "32.90583", :longitude => "45.06163").save
City.new(:country_id => "109", :name => "Al `Amarah", :aliases => "Al `Amarah,Al âAmÄrah,Amara,Amarah,Amare,AmarÃ©,`Amara,Ø§ÙØ¹ÙØ§Ø±Ù,âAmÄra,Al âAmÄrah", :latitude => "31.84064", :longitude => "47.1396").save
City.new(:country_id => "109", :name => "`Afak", :aliases => "Afag,Afak,Afaq,Sok el Afej,`Afak,ÐÑÐ°Ðº,Ø¹ÙÙ,âAfak,âAfak", :latitude => "32.06898", :longitude => "45.25055").save
City.new(:country_id => "109", :name => "Ad Dujayl", :aliases => "Ad Dujayl,Al Ibrahimiyah,Al IbrÄhÄ«mÄ«yah,Doujail,DoujaÃ¯l,Dudschail,Dudzail,DudÅ¾ail,Dujail,Dujayl,Nahiya Sumaika,Nahiya SumaÄ«ka,Nahiyat ad Dujayl,NÄá¸©iyat ad Dujayl,Sumaicha,Sumaichah,Sumaika,Sumaikcheh,Sumaykah,SumaÄ«ka,Sumeicha,Sumeikeh,Sumekche,Summeicha,Suneiki,do~ujairu,ãã¥ã¸ã£ã¤ã«,Ad Dujayl", :latitude => "33.84667", :longitude => "44.23444").save
City.new(:country_id => "109", :name => "Ad Diwaniyah", :aliases => "Ad Diwania,Ad Diwaniya,Ad Diwaniyah,Ad DÄ«wÄnÄ«ya,Ad DÄ«wÄnÄ«yah,Al-Diwaniya,Divanija,Diwanie,Diwaniya,Diwaniyan,Diwaniyeh,DÄ«wanÄ«ya,Hiska,ÐÐ¸Ð²Ð°Ð½Ð¸Ñ,Ø§ÙØ¯ÙÙØ§ÙÙØ©,Ad DÄ«wÄnÄ«yah", :latitude => "31.99051", :longitude => "44.93063").save
City.new(:country_id => "109", :name => "Abu Ghurayb", :aliases => "Abou Ghraib,Abu Ghraib,Abu Ghraib - abw ghryb,Abu Ghraib - Ø£Ø¨Ù ØºØ±ÙØ¨,Abu Ghraib Farms,Abu Ghuraib,Abu Ghurayb,Abu-Grejb,AbÅ« Ghraib Farms,AbÅ« Ghurayb,Mazari` Abi Gharib,Mazari` Abi Ghurayb,MazÄriâ AbÄ« Ghurayb,MazÄrÄ±â AbÄ« GharÄ«b,abw ghryb,ÐÐ±Ñ-ÐÑÐµÐ¹Ð±,××× ××¨×××,Ø§Ø¨Ù ØºØ±ÛØ¨,AbÅ« Ghurayb", :latitude => "33.30833", :longitude => "44.185").save
City.new(:country_id => "109", :name => "Al Basrat al Qadimah", :aliases => "Al Basrah al Qadimah,Al Basrat al Qadimah,Al BaÅrah al QadÄ«mah,Al BaÅrat al QadÄ«mah,Ø§ÙØ¨ØµØ±Ø© Ø§ÙÙØ¯ÙÙØ©,Al BaÅrat al QadÄ«mah", :latitude => "30.49721", :longitude => "47.81491").save
City.new(:country_id => "109", :name => "Sinjar", :aliases => "Sinjar,SinjÄr,Sncar,snjar,Ø³ÙØ¬Ø§Ø±,SinjÄr", :latitude => "36.32092", :longitude => "41.87542").save
