City.new(:country_id => "110", :name => "Azadshahr", :aliases => "Azad Shahr,Azadshahr,ÄzÄdshahr,Ø¢Ø²Ø§Ø¯Ø´ÙØ±,ÄzÄdshahr", :latitude => "34.79088", :longitude => "48.57073").save
City.new(:country_id => "110", :name => "Kahriz", :aliases => "Kahriz,KahrÄ«z,Ú©ÙØ±ÛØ²,KahrÄ«z", :latitude => "34.3838", :longitude => "47.0553").save
City.new(:country_id => "110", :name => "Nurabad", :aliases => "Nurabad,NÅ«rÄbÄd,nwr abad,ÐÑÑÐ°Ð±Ð°Ð´,ÙÙØ± Ø¢Ø¨Ø§Ø¯,NÅ«rÄbÄd", :latitude => "34.0734", :longitude => "47.9725").save
City.new(:country_id => "110", :name => "Istgah-e Garmsar", :aliases => "Istgah-e Garmsar,Istgah-e Rah Ahan Garmsar,Istgah-e Rah Ahan-e Garmsar,aystgah grmsar,ystgahi garmsar,ystgahi rah ahan garmsar,ystgahi rahahani garmsar,ÄªstgÄh-e GarmsÄr,ÄªstgÄh-e RÄh Ähan GarmsÄr,ÄªstgÄh-e RÄh Ähan-e GarmsÄr,Ø§ÙØ³ØªÚ¯Ø§Ù Ú¯Ø±ÙØ³Ø§Ø±,ÙØ³ØªÚ¯Ø§ÙÙ Ø±Ø§Ù Ø¢ÙÙÙ Ú¯ÙØ±ÙØ³Ø§Ø±,ÙØ³ØªÚ¯Ø§ÙÙ Ø±Ø§ÙØ§ÙÙÙÙ Ú¯ÙØ±ÙØ³Ø§Ø±,ÙØ³ØªÚ¯Ø§ÙÙ Ú¯ÙØ±ÙØ³Ø§Ø±,ÄªstgÄh-e GarmsÄr", :latitude => "35.23455", :longitude => "52.30942").save
City.new(:country_id => "110", :name => "Qarchak", :aliases => "Qarchak,Qareh Chak,qarih chak,ÙØ±ÚÙ,ÙÙØ±ÙÙ ÚÙÙ,Qarchak", :latitude => "35.43944", :longitude => "51.56889").save
City.new(:country_id => "110", :name => "Khorram Darreh", :aliases => "Khorram Darreh,khrm drh,Ø®Ø±Ù Ø¯Ø±ÙÙ,Khorram Darreh", :latitude => "36.213", :longitude => "49.196").save
City.new(:country_id => "110", :name => "Shah Pasand", :aliases => "Azad Shahr,Shah Pasand,ShÄh Pasand,ÄzÄd Shahr,Ø¢Ø²Ø§Ø¯ Ø´ÙØ±,Ø´Ø§Ù Ù¾Ø³ÙØ¯,ShÄh Pasand", :latitude => "37.08701", :longitude => "55.17397").save
City.new(:country_id => "110", :name => "Zarand", :aliases => "Zarand,Ø²Ø±ÙØ¯,Zarand", :latitude => "30.81271", :longitude => "56.56399").save
City.new(:country_id => "110", :name => "Zanjan", :aliases => "Zanjan,ZanjÄn,Zendzhan,Zenjan,ZenjÄn,znjan,ÐÐµÐ½Ð´Ð¶Ð°Ð½,Ø²ÙØ¬Ø§Ù,ZanjÄn", :latitude => "36.6736", :longitude => "48.4787").save
City.new(:country_id => "110", :name => "Yazd", :aliases => "Jazd,Jazdo,Jezd,Yazd,Yezd,iazdi,yazd,yizd,yzd,ÐÐµÐ·Ð´,Ð¯Ð·Ð´,×××,ÙÙØ²Ø¯,ÙÙØ²Ø¯,ÛØ²Ø¯,ááááá,Yazd", :latitude => "31.89722", :longitude => "54.3675").save
City.new(:country_id => "110", :name => "Varamin", :aliases => "Varamin,VarÄmÄ«n,Veramin,VerÄmin,varamin,ÐÐ°ÑÐ°Ð¼Ð¸Ð½,ÙØ±Ø§ÙÙÙ,VarÄmÄ«n", :latitude => "35.3242", :longitude => "51.6457").save
City.new(:country_id => "110", :name => "Torbat-e Heydariyeh", :aliases => "Torbat-e Heydariyeh,Torbat-e á¸¨eydarÄ«yeh,Torbat-e-Heydari,Turbat-i-Haidari,Turbet-i-Haidari,ØªØ±Ø¨Øª Ø­ÛØ¯Ø±ÛÙ,Torbat-e á¸¨eydarÄ«yeh", :latitude => "35.27401", :longitude => "59.21949").save
City.new(:country_id => "110", :name => "Tonekabon", :aliases => "Shahsavar,ShahsavÄr,Shahsawar,ShahsawÄr,Tonekabon,TonekÄbon,shahsawar,tunikabun,Ð¢Ð¾Ð½ÐµÐºÐ°Ð±Ð¾Ð½,ØªÙÙÙÙØ§Ø¨ÙÙ,Ø´ÙÙØ³ÙÙØ§Ø±,TonekÄbon", :latitude => "36.80861", :longitude => "50.88194").save
City.new(:country_id => "110", :name => "Tehran", :aliases => "Taekhran,Tahran,Techerane,Teera,Teerao,TeerÃ£,TeerÃ£o,Tegeran,Teheran,Teheran - thran,Teherana,Teheranas,Teherano,TeherÃ¡n,TeherÃ¡n - ØªÙØ±Ø§Ù,TeherÄna,Tehran,Tehrano,Tekheran,TÃ©hÃ©ran,de hei lan,teharan,teharana,tehelan,teheran,tehran,teirani,thran,thrn,thrwn,tihiran,tihran,Î¤ÎµÏÎµÏÎ¬Î½Î·,Ð¢Ã¦ÑÑÐ°Ð½,Ð¢ÐµÐ³ÐµÑÐ°Ð½,Ð¢ÐµÑÐµÑÐ°Ð½,Ð¢ÐµÒ³ÑÐ¾Ð½,Ô¹Õ¥Õ°ÖÕ¡Õ¶,×××¨××,×××¨×,ØªÙØ±Ø§Ù,ØªÙØ±ÙÙ,ØªÙÙØ±Ø§Ù,ØªÙÙÙØ±ÙÙ,ØªÛØ±Ø§Ù,Ø·ÙØ±Ø§Ù,ÜÜÜªÜ¢,à¤¤à¥à¤¹à¤°à¤¾à¤¨,à¦¤à§à¦¹à¦°à¦¾à¦¨,à®à¯à®¹à¯à®°à®¾à®©à¯,à¹à¸à¸«à¸°à¸£à¸²à¸,à½à½ºà¼à½§à½ºà¼à½¢à½,áááá ááá,á´áá«á,ããã©ã³,å¾·é»å°,íí¤ë,TehrÄn", :latitude => "35.69439", :longitude => "51.42151").save
City.new(:country_id => "110", :name => "Hashtpar", :aliases => "Gashpar,Hashtpar,Hashtpar-e Tavalesh,Otak Saray,Otaq Sarai,Otaq Saray,OtÄq Sarai,OÅ£Äq SarÄy,Talesh,TÄlesh,ÙØ´ØªÙ¾Ø±,Hashtpar", :latitude => "37.8008", :longitude => "48.9037").save
City.new(:country_id => "110", :name => "Takestan", :aliases => "Seyadahan,SeyÄdahan,Siadehan,Siahdehan,Siakh-Degen,Siakhdekhan,SÄ«ahdehÄn,SÄ«Ädehan,Takestan,Takistan,TÄkestÄn,TÄkistÄn,siadahan,syadihan,syahdihan,takstan,ØªØ§ÙØ³ØªØ§Ù,Ø³ÙØ§Ø¯ÙÙÙÙ,Ø³ÙÙÙØ¯ÙÙØ§Ù,Ø³ÙÙØ§Ø¯ÙÙÙÙ,TÄkestÄn", :latitude => "36.0696", :longitude => "49.6959").save
City.new(:country_id => "110", :name => "Takab", :aliases => "Takab,Takan Tepe,TakÄb,ØªÚ©Ø§Ø¨,TakÄb", :latitude => "36.4009", :longitude => "47.1133").save
City.new(:country_id => "110", :name => "Taft", :aliases => "Taft,taft,Ð¢Ð°ÑÑ,ØªÙÙØª,Taft", :latitude => "31.7475", :longitude => "54.20417").save
City.new(:country_id => "110", :name => "Tabriz", :aliases => "Tabriz,TabrÃ­z,TabrÄ«z,Taebris,Tauris,Tebriz,TÃ¤bris,TÉbriz,da bu li shi,tabryz,taburizu,tbryz,Ð¢ÐµÐ±ÑÐ¸Ð·,ØªØ¨Ø±ÙØ²,ØªØ¨Ø±ÛØ²,ØªÙØ¨Ø±ÙØ²,ã¿ããªã¼ãº,å¤§ä¸éå£«,TabrÄ«z", :latitude => "38.08", :longitude => "46.2919").save
City.new(:country_id => "110", :name => "Tabas", :aliases => "Golshan,Gulshan,Tabas,tbs,Å¢abas,Ð¢Ð°Ð±Ð°Ñ,Ø·Ø¨Ø³,Å¢abas", :latitude => "33.59586", :longitude => "56.92437").save
City.new(:country_id => "110", :name => "Sonqor", :aliases => "Sanghur,SanghÅ«r,Sonqor,Sunqur,SÅ«nqÅ«r,Ø³ÙÙØ±,Sonqor", :latitude => "34.7837", :longitude => "47.6004").save
City.new(:country_id => "110", :name => "Sirjan", :aliases => "Sa`idabad,SaâÄ«dÄbÄd,Sirdschan,Sirjan,SÄ«rjÄn,Ø³ÛØ±Ø¬Ø§Ù,SÄ«rjÄn", :latitude => "29.452", :longitude => "55.6814").save
City.new(:country_id => "110", :name => "Shushtar", :aliases => "Shooshtar,Shushtar,Shushtehr,Shustar,ShÅ«shtar,ShÅ«star,Ð¨ÑÑÑÑÑ,Ø´ÙØ´ØªØ±,ShÅ«shtar", :latitude => "32.0455", :longitude => "48.8567").save
City.new(:country_id => "110", :name => "Shush", :aliases => "Shoosh,Shush,ShÅ«sh,Susa,Suse,Susy,Suza,Suzo,Suzy,SÃºsy,SÅ«sa,susa,Ð¡ÑÐ·Ñ,Ø´ÙØ´,ã¹ã¼ãµ,ShÅ«sh", :latitude => "32.1942", :longitude => "48.2436").save
City.new(:country_id => "110", :name => "Shiraz", :aliases => "Chimaz,Chiraz,Schiras,Shiraz,ShÄ«rÄz,Siraz,SirÃ¢z,Ð¨Ð¸ÑÐ°Ð·,Ø´ÛØ±Ø§Ø²,ShÄ«rÄz", :latitude => "29.6036", :longitude => "52.5388").save
City.new(:country_id => "110", :name => "Shahr-e Kord", :aliases => "Sahr-e Kord,Shahr Kord,Shahr Kurd,Shahr-e Kord,Shakhre-Kord,sahri kurd,Ð¨Ð°ÑÑÐµ-ÐÐ¾ÑÐ´,Ø³ÙÙØ±Ù ÙÙØ±Ø¯,Ø´ÙØ± ÙØ±Ø¯,Ø´ÙÙØ±Ù ÙÙØ±Ø¯,Shahr-e Kord", :latitude => "32.32556", :longitude => "50.86444").save
City.new(:country_id => "110", :name => "Shahr-e Babak", :aliases => "Shahr Babak,Shahr BÄbak,Shahr-e Babak,Shahr-e BÄbak,Shahr-i-Babak,Shahr-i-BÄbak,Ø´ÙØ± Ø¨Ø§Ø¨Ú©,Shahr-e BÄbak", :latitude => "30.1165", :longitude => "55.1186").save
City.new(:country_id => "110", :name => "Shadegan", :aliases => "Fallabiyeh,Fallahiyeh,Fallehiyeh,FallÄbÄ«yeh,FallÄá¸©Ä«yeh,Shadegan,Shadeganskie,Shadgan,ShÄdegÄn,ShÄdgÄn,Ð¨Ð°Ð´ÐµÐ³Ð°Ð½ÑÐºÐ¸Ðµ,Ø´Ø§Ø¯Ú¯Ø§Ù,ShÄdegÄn", :latitude => "30.64972", :longitude => "48.66472").save
City.new(:country_id => "110", :name => "Semnan", :aliases => "Samnan,SamnÄn,Semnan,SemnÄn,samnan,smnan,Ð¡ÐµÐ¼Ð½Ð°Ð½,Ø³ÙÙØ§Ù,Ø³ÙÙÙØ§Ù,SemnÄn", :latitude => "35.57291", :longitude => "53.39714").save
City.new(:country_id => "110", :name => "Semirom", :aliases => ",SemÄ«rom", :latitude => "31.41667", :longitude => "51.56667").save
City.new(:country_id => "110", :name => "Saveh", :aliases => "Sava,Saveh,SÄveh,sawih,Ð¡Ð°Ð²Ð°,Ø³Ø§ÙÙÙ,SÄveh", :latitude => "35.0213", :longitude => "50.3566").save
City.new(:country_id => "110", :name => "Shari-i-Tajan", :aliases => "Sari,Sari i Iran,Sariyo,Shahr-i-Tajan,Shari-i-Tajan,SÃ¡ri,SÄrÄ«,sa li shi,sari,iran,sary,Î£Î¬ÏÎ¹,Ð¡Ð°ÑÐ¸,Ø³Ø§Ø±Ù,Ø³Ø§Ø±Û,ãµãªã¼ãã¤ã©ã³,è©éå¸,Shari-i-Tajan", :latitude => "36.56297", :longitude => "53.05652").save
City.new(:country_id => "110", :name => "Saqqez", :aliases => "Saghez,Sakezo,Sakiz,SakÄ«z,Saqqez,Saqqez (2),Saqqiz,Seqiz,saghiz,sakyz,saqiz,sqz,sqz (1),sqz (2),Ø³ÙØ²,Ø³ÙÙØ² (1),Ø³ÙÙØ² (Ù¢),Ø³ÙØºÙØ²,Ø³ÙÙÙÙØ²,Ø³ÙÙÙØ²,Saqqez", :latitude => "36.24992", :longitude => "46.2735").save
City.new(:country_id => "110", :name => "Sanandaj", :aliases => "Sanandadsch,Sanandadz,SanandadÅ¼,Sanandaj,Senendedzh,Senna,Senneh,Sinandij,Sine,Sinneh,sanandaj,sina,sinih,Ð¡Ð°Ð½Ð°Ð½Ð´Ð°Ò·,Ð¡ÐµÐ½ÐµÐ½Ð´ÐµÐ´Ð¶,Ø³ÙÙØ¯Ø¬,Ø³ÙÙÙÙØ¯ÙØ¬,Ø³ÙÙÙÙ,Ø³ÙÙÙÙÙ,Sanandaj", :latitude => "35.3144", :longitude => "46.9923").save
City.new(:country_id => "110", :name => "Salmas", :aliases => "Dilmagan,Dilman,DÄ«lmagÄn,DÄ«lman,Salmas,SalmÄs,Shahpoor,Shahpur,Shapur,ShÄhpÅ«r,Ð¡Ð°Ð»Ð¼Ð°Ñ,Ø³ÙÙØ§Ø³,SalmÄs", :latitude => "38.1973", :longitude => "44.7653").save
City.new(:country_id => "110", :name => "Shahin Dezh", :aliases => "Sa'in Dezh,Sa'in Qal`eh,Sahin Dazh,Sain Kaleh,Shahin Dezh,ShÄhÄ«n Dezh,SÄÄ«n Kaleh,shahyn dzh,ÅÄâÄ«n Dezh,ÅÄâÄ«n Qalâeh,Ø´Ø§ÙÛÙ Ø¯Ú,ShÄhÄ«n Dezh", :latitude => "36.6793", :longitude => "46.5669").save
City.new(:country_id => "110", :name => "Sabzevar", :aliases => "Sabzawar,SabzawÄr,Sabzevar,SabzevÄr,Sebzevar,Ð¡ÐµÐ±Ð·ÐµÐ²Ð°Ñ,Ø³Ø¨Ø²ÙØ§Ø±,SabzevÄr", :latitude => "36.2126", :longitude => "57.68191").save
City.new(:country_id => "110", :name => "Rudsar", :aliases => "Rud-i-Sar,Rudsar,RÅ«d-i-Sar,RÅ«dsar,Ø±ÙØ¯Ø³Ø±,RÅ«dsar", :latitude => "37.13761", :longitude => "50.288").save
City.new(:country_id => "110", :name => "Robat Karim", :aliases => "Robat Karim,RobÄÅ£ KarÄ«m,Shahriar,Shahryar,ShahryÄr,rbat krym,shahryar,Ø±Ø¨Ø§Ø· ÙØ±ÙÙ,Ø´ÙÙØ±ÙØ§Ø±,RobÄÅ£ KarÄ«m", :latitude => "35.4846", :longitude => "51.0829").save
City.new(:country_id => "110", :name => "Ravar", :aliases => "Ravar,RÄvar,rawr,Ø±Ø§ÙØ±,RÄvar", :latitude => "31.26562", :longitude => "56.80545").save
City.new(:country_id => "110", :name => "Rasht", :aliases => "Rashjt,Rasht,Rast,RaÅ¡t,Resht,Reszt,la shen te,Ð ÐµÑÑ,Ø±Ø´Øª,æä»ç¹,Rasht", :latitude => "37.28077", :longitude => "49.58319").save
City.new(:country_id => "110", :name => "Ramshir", :aliases => "Khalafabad,KhalafÄbÄd,Khalas Abad,Ram Shahr,Ramshir,RÄmshÄ«r,Ø±Ø§ÙØ´ÛØ±,RÄmshÄ«r", :latitude => "30.8946", :longitude => "49.4092").save
City.new(:country_id => "110", :name => "Ramhormoz", :aliases => "Ram Hormuz,Ramhormoz,Ramuz,RÄm Hormuz,RÄmhormoz,RÄmuz,Ø±Ø§ÙÙØ±ÙØ²,RÄmhormoz", :latitude => "31.27997", :longitude => "49.60351").save
City.new(:country_id => "110", :name => "Rafsanjan", :aliases => "Bahramabad,BahrÄmÄbÄd,Rafsandzhane,Rafsanjan,RafsanjÄn,Rafsinjan,RafsinjÄn,Ð Ð°ÑÑÐ°Ð½Ð´Ð¶Ð°Ð½Ðµ,Ø±ÙØ³ÙØ¬Ø§Ù,RafsanjÄn", :latitude => "30.4067", :longitude => "55.9939").save
City.new(:country_id => "110", :name => "Quchan", :aliases => "Gochan,Quchan,QÅ«chÄn,ÙÙÚØ§Ù,QÅ«chÄn", :latitude => "37.106", :longitude => "58.50955").save
City.new(:country_id => "110", :name => "Qorveh", :aliases => "Qorveh,Qurve,Qurveh,qrwh,ÙØ±ÙÙ,Qorveh", :latitude => "35.1664", :longitude => "47.8045").save
City.new(:country_id => "110", :name => "Qom", :aliases => "Ghom,Kum,Qom,Qum,ghum,komu,qm,ÐÑÐ¼,ÒÑÐ¼,ØºÙÙ,ÙÙ,ã³ã ,Qom", :latitude => "34.6401", :longitude => "50.8764").save
City.new(:country_id => "110", :name => "Qeshm", :aliases => "Bandar-e Qeshm,Gheshm,Keshm,Qeshm,Qishm,bandari qishm,qshm,ÐÐµÑÐ¼,Ø¨ÙÙØ¯ÙØ±Ù ÙÙØ´Ù,ÙØ´Ù,Qeshm", :latitude => "26.9581", :longitude => "56.2719").save
City.new(:country_id => "110", :name => "Qazvin", :aliases => "Kazvin,Kazwin,Qazvin,QazvÄ«n,kaza~tsuvu~in,qzwyn,ÐÐ°Ð·Ð²Ð¸Ð½,ÙØ²ÙÙÙ,ÙØ²ÙÛÙ,ã«ã¶ãã´ã£ã¼ã³,QazvÄ«n", :latitude => "36.2797", :longitude => "50.0049").save
City.new(:country_id => "110", :name => "Qarah Zia' od Din", :aliases => "Ghareh Ziya' Oddin,Ghareh Ziyaâ Oddin,Qara Zia ud Din,Qara ZÄ«a ud DÄ«n,Qarah Zia' od Din,Qarah áºÄ«Ä' od DÄ«n,Qaraziadin,Qareh Zeya ed Din,Qareh ZeyÄ ed DÄ«n,Qareh Zia' od Din,Qareh Ziya 'Eddin,Qareh ZÄ«yÄ âEddÄ«n,Qareh áºÄ«Ä' od DÄ«n,ÙØ±Ù Ø¶ÛØ§Ø¡ Ø§ÙØ¯ÛÙ,Qarah áºÄ«Ä' od DÄ«n", :latitude => "38.8915", :longitude => "45.0255").save
City.new(:country_id => "110", :name => "Farrokh Shahr", :aliases => "Farrokh Shahr,Qahferokh,Qahofrokh,Qatarokh,Qehfarukh,qatarukh,ÙØ±Ø® Ø´ÙØ±,ÙØ±ÙØ® Ø´ÙØ±,ÙÙÙØ±Ø®,ÙÙØªÙØ±ÙØ®,ÙÙÙÙÙØ±ÙØ®,ÙÙÙÙÙØ±ÙØ®,Farrokh Shahr", :latitude => "32.27174", :longitude => "50.98008").save
City.new(:country_id => "110", :name => "Qayen", :aliases => "Qa'en,Qain,Qayen,QaÄ«n,QÄyen,QÄâen,Shahr-e Qayen,Shahr-e QÄyen,ÙØ§ÛÙ,QÄyen", :latitude => "33.72654", :longitude => "59.18439").save
City.new(:country_id => "110", :name => "Sarpol-e Zahab", :aliases => "Pol-e Zahab,Pol-e Zohab,Pol-e ZÌahÄb,Pol-e ZÌohÄb,Sar-e Pol-e Zahab,Sar-e Pol-e ZÌahÄb,Sar-i-Pul Zuhab,Sar-Ä«-PÅ«l ZÅ«hÄb,Sari-Pul,Sarpol,Sarpol-e Zahab,Sarpol-e ZÌahÄb,SarÄ«-PÅ«l,Ø³Ø± Ù¾Ù Ø°ÙØ§Ø¨,Sarpol-e ZÌahÄb", :latitude => "34.46109", :longitude => "45.86264").save
City.new(:country_id => "110", :name => "Pishva", :aliases => "Emamzadeh Ja`far,EmÄmzÄdeh Jaâfar,Pichva,Pishva,Pishvah,Pishyan,PÄ«chvÄ,PÄ«shvah,PÄ«shvÄ,PÄ«shyÄn,pychwa,pyshwa,pyshwah,pyshyan,Ø§ÙÙØ§ÙØ²Ø§Ø¯ÙÙ Ø¬ÙØ¹ÙÙØ±,Ù¾ÙØ´ÙØ§,Ù¾ÙØ´ÙÙÙ,Ù¾ÙØ´ÙØ§Ù,Ù¾ÙÚÙØ§,PÄ«shvÄ", :latitude => "35.308", :longitude => "51.7267").save
City.new(:country_id => "110", :name => "Piranshahr", :aliases => "Khaneh,KhÄneh,Piran Shahr,Piranshahr,PÄ«rÄn Shahr,PÄ«rÄnshahr,pyranshhr,Ù¾ÛØ±Ø§ÙØ´ÙØ±,PÄ«rÄnshahr", :latitude => "36.701", :longitude => "45.1413").save
City.new(:country_id => "110", :name => "Paveh", :aliases => "Paveh,Pawah,Paweh,PÄveh,PÄweh,Ù¾Ø§ÙÙ,PÄveh", :latitude => "35.0434", :longitude => "46.3565").save
City.new(:country_id => "110", :name => "Parsabad", :aliases => "Farsabad,FÄrsÄbÄd,Parsabad,PÄrsÄbÄd,fars abad,pars abad,ÐÐ°ÑÑÐ°Ð±Ð°Ð´,ÙØ§Ø±Ø³ Ø¢Ø¨Ø§Ø¯,Ù¾Ø§Ø±Ø³ Ø¢Ø¨Ø§Ø¯,PÄrsÄbÄd", :latitude => "39.6482", :longitude => "47.9174").save
City.new(:country_id => "110", :name => "Oshnaviyeh", :aliases => "Ashnooyeh,Oshnaviyeh,OshnavÄ«yeh,Oshnovieh,Oshnoviyeh,OshnovÄ«eh,OshnovÄ«yeh,Oshnuje,Ushnu,Ushnuiyeh,UshnÅ«,UshnÅ«Ä«yeh,ÐÑÐ½ÑÐ¹Ðµ,Ø§Ø´ÙÙÛÙ,Ø§Ø´ÙÙÛÙÙ,OshnavÄ«yeh", :latitude => "37.0397", :longitude => "45.0983").save
City.new(:country_id => "110", :name => "Orumiyeh", :aliases => "Orumieh,Orumiyeh,OrÅ«mÄ«yeh,Reza'iyeh,Rezaeyeh,Rezaiyye,RezÃ¢iyye,RezÄâÄ«yeh,Rizaiyeh,RizÄiyeh,Urmia,Urmija,Urmiye,UrmiyÉ,UrmÃ­a,Urumija,Urumiyeh,UrÅ«miyeh,arwmyh,arwmyt,shhrstan arwmyh,Ð£ÑÐ¼Ð¸Ñ,Ð£ÑÑÐ¼Ð¸Ñ,×××¨×××,Ø£Ø±ÙÙÙØ©,Ø§Ø±ÙÙÛÙ,Ø§Ø±ÙÙÛÙÙ,Ø´ÙØ±Ø³ØªØ§Ù Ø§Ø±ÙÙÛÙ,ÜÜÜªÜ¡ÜÜ,OrÅ«mÄ«yeh", :latitude => "37.55274", :longitude => "45.07605").save
City.new(:country_id => "110", :name => "Omidiyeh", :aliases => "Omidiyeh,Omidiyeh Sherkat-e Naft,OmÄ«dÄ«yeh,OmÄ«dÄ«yeh Sherkat-e Naft,Sherkat-e Naft,OmÄ«dÄ«yeh", :latitude => "30.75972", :longitude => "49.705").save
City.new(:country_id => "110", :name => "Nurabad", :aliases => "Nurabad,NÅ«rÄbÄd,ÙÙØ± Ø¢Ø¨Ø§Ø¯,NÅ«rÄbÄd", :latitude => "30.11405", :longitude => "51.52174").save
City.new(:country_id => "110", :name => "Neyshabur", :aliases => "Nejsaburo,NejÅaburo,Neyshabur,NeyshÄbÅ«r,Nichapur,Nisabur,Nischapur,Nishabur,Nishapur,Nishopur,NiÅabur,NÄ«shÄbÅ«r,NÄ«shÄpÅ«r,nishapu,nysabwr,nyshapwr,ÐÐ¸ÑÐ°Ð¿ÑÑ,ÐÐ¸ÑÐ¾Ð¿ÑÑ,ÙÙØ³Ø§Ø¨ÙØ±,ÙÛØ´Ø§Ø¨ÙØ±,ÙÛØ´Ø§Ù¾ÙØ±,ãã·ã£ãã¼,NeyshÄbÅ«r", :latitude => "36.21329", :longitude => "58.79576").save
City.new(:country_id => "110", :name => "Neyriz", :aliases => "Neyriz,NeyrÄ«z,Niriz,NÄ«rÄ«z,ÙÛØ±ÛØ²,NeyrÄ«z", :latitude => "29.1988", :longitude => "54.3278").save
City.new(:country_id => "110", :name => "Neka'", :aliases => "Naranj Bagh,Neka,Neka',NekÄ,NekÄâ,Nika,NÄranj BÄgh,NÄ«kÄ,naranj bagh,nika,nyka,ÐÐµÐºÐ°,ÙØ§Ø±ÙÙØ¬ Ø¨Ø§Øº,ÙÙØ§Ø¡,ÙÙÙØ§,ÙÙÙØ§,NekÄâ", :latitude => "36.65143", :longitude => "53.29593").save
City.new(:country_id => "110", :name => "Nazarabad", :aliases => "Nazarabad,Nazarabad-e Bozorg,NazÌ§arÄbÄd,NazÌ§arÄbÄd-e Bozorg,nazarabadi buzurg,ÙØ¸Ø± Ø¢Ø¨Ø§Ø¯,ÙÙØ¸ÙØ±Ø§Ø¨Ø§Ø¯Ù Ø¨ÙØ²ÙØ±Ú¯,NazÌ§arÄbÄd", :latitude => "35.9521", :longitude => "50.6075").save
City.new(:country_id => "110", :name => "Naqadeh", :aliases => "Nagadeh,Naghadeh,Naghdeh,Nakhuda,Naqadeh,NÄkhuda,ÙÙØ¯Ù,Naqadeh", :latitude => "36.9553", :longitude => "45.388").save
City.new(:country_id => "110", :name => "Nahavand", :aliases => "Antiocheia,Nagavande,Nahavand,NahÄvand,Nehavend,NehÄvend,Nihavand,NÄ«hÄvand,nahawand,nihavu~ando,nihawind,nyhawand,ÎÎ½ÏÎ¹ÏÏÎµÎ¹Î±,ÐÐ°Ð³Ð°Ð²Ð°Ð½Ð´Ðµ,ÙÙØ§ÙÙØ¯,ÙÙÙØ§ÙÙÙØ¯,ÙÙÙØ§ÙÙÙØ¯,ÙÙÙØ§ÙÙÙØ¯,ããã¼ã´ã¡ã³ã,NahÄvand", :latitude => "34.1885", :longitude => "48.377").save
City.new(:country_id => "110", :name => "Minab", :aliases => "Minab,MÄ«nÄb,mynab,ÐÐ¸Ð½Ð°Ð±,ÙÙÙØ§Ø¨,MÄ«nÄb", :latitude => "27.1467", :longitude => "57.0801").save
City.new(:country_id => "110", :name => "Miandowab", :aliases => "Meyandoab,MeyÄndoÄb,Miandoab,Miandow Ab,Miandowab,Mianduab,Miyandoab,Miyanduab,MiyÄndÅ«Äb,MÄ«yÄndoÄb,MÄ«Ändow Äb,MÄ«ÄndowÄb,MÄ«ÄndoÄb,MÄ«ÄndÅ«Äb,ÐÐ¸Ð°Ð½Ð´Ð¾Ð°Ð±,ÙÛØ§ÙØ¯ÙØ¢Ø¨,MÄ«ÄndowÄb", :latitude => "36.9694", :longitude => "46.1027").save
City.new(:country_id => "110", :name => "Meybod", :aliases => "Maibud,Meybod,mibud,ÙÙØ¨Ø¯,ÙÙÙØ¨ÙØ¯,Meybod", :latitude => "32.24828", :longitude => "53.95039").save
City.new(:country_id => "110", :name => "Mehriz", :aliases => "Mehriz,MehrÄ«z,mihryz,ÙÙÙØ±ÙØ²,MehrÄ«z", :latitude => "31.58389", :longitude => "54.42806").save
City.new(:country_id => "110", :name => "Masjed Soleyman", :aliases => "Masjed Soleiman,Masjed Soleyman,Masjed SoleymÄn,Masjed-e Soleyman,Masjed-e SoleymÄn,Masjid-i-Sulaiman,ÙØ³Ø¬Ø¯ Ø³ÙÛÙØ§Ù,Masjed SoleymÄn", :latitude => "31.9364", :longitude => "49.3039").save
City.new(:country_id => "110", :name => "Bardsir", :aliases => "Bardesir,BardesÄ«r,Bardsir,BardsÄ«r,Deh-e Now-e Mashiz,Deh-e Now-e MashÄ«z,Mashiz,MashÄ«z,Mshiz,Qal`eh-ye Mashiz,Qalâeh-ye MashÄ«z,Ø¨Ø±Ø¯Ø³ÛØ±,BardsÄ«r", :latitude => "29.9275", :longitude => "56.5722").save
City.new(:country_id => "110", :name => "Mashhad", :aliases => "Maschhad,Mashad,Mashado,Mashhad,MaÅhado,MaÅ¡had,Meshed,Mesheda,Meshkhed,Meszhed,MeÅhed,MeÅ¡heda,ma shen ha de,mashuhado,mshd,mshhd,ÐÐ°ÑÒ³Ð°Ð´,ÐÐµÑÑÐµÐ´,××©××,ÙØ´ÙØ¯,ãã·ã¥ãã,é¦¬ä»åå¾·,Mashhad", :latitude => "36.297", :longitude => "59.6062").save
City.new(:country_id => "110", :name => "Marand", :aliases => "Marand,Morand,mrnd,murand,ÐÐ°ÑÐ°Ð½Ð´,ÙØ±ÙØ¯,ÙÙØ±ÙÙØ¯,ÙÙØ±ÙÙØ¯,Marand", :latitude => "38.4329", :longitude => "45.7749").save
City.new(:country_id => "110", :name => "Malayer", :aliases => "Daulatabad,DaÅ«latÄbÄd,Dowlatabad,DowlatÄbÄd,Malayer,MalÄyer,dawlat abad,dulat abad,malayir,Ø¯ÙÙÙÙØª Ø¢Ø¨Ø§Ø¯,Ø¯ÙÙÙÙØª Ø¢Ø¨Ø§Ø¯,ÙÙØ§ÛØ±,ÙÙÙØ§ÙÙØ±,MalÄyer", :latitude => "34.2969", :longitude => "48.8235").save
City.new(:country_id => "110", :name => "Malard", :aliases => "Malar,Malard,MalÄr,MalÄrd,Melard,MelÄrd,malar,milard,mlard,ÙÙØ§Ø±Ø¯,ÙÙÙØ§Ø±,ÙÙÙØ§Ø±Ø¯,MalÄrd", :latitude => "35.6659", :longitude => "50.9767").save
City.new(:country_id => "110", :name => "Mahabad", :aliases => "Mahabad,MahÄbÄd,Makhabad,Mehabad,MehÄbÄd,Saujbulagh,SÄÅ«jbulÄgh,mah abad,mhabad,mih abad,ÐÐ°ÑÐ°Ð±Ð°Ð´,ÙÙØ§Ø¨Ø§Ø¯,ÙÙÙ Ø¢Ø¨Ø§Ø¯,ÙÙÙ Ø¢Ø¨Ø§Ø¯,MahÄbÄd", :latitude => "36.7631", :longitude => "45.7222").save
City.new(:country_id => "110", :name => "Langerud", :aliases => "Langarood,Langarud,LangarÅ«d,Langerud,LangerÅ«d,Shahr-e Langarud,Shahr-e LangarÅ«d,ÙÙÚ¯Ø±ÙØ¯,LangerÅ«d", :latitude => "37.19701", :longitude => "50.15351").save
City.new(:country_id => "110", :name => "Kuhdasht", :aliases => "Kuh-i-Dasht,Kuhdasht,KÅ«h-Ä«-Dasht,KÅ«hdasht,kwhdasht,kwhdsht,ÙÙÙØ¯ÙØ´Øª,Ú©ÙÙØ¯Ø´Øª,KÅ«hdasht", :latitude => "33.535", :longitude => "47.6061").save
City.new(:country_id => "110", :name => "Kish", :aliases => "Kish,KÄ«sh,kysh,ÐÐ¸Ñ,ÙÙØ´,KÄ«sh", :latitude => "26.55778", :longitude => "54.01944").save
City.new(:country_id => "110", :name => "Khvoy", :aliases => "Khoi,Khowy,Khoy,Khvoy,Ø®ÙÛ,Khvoy", :latitude => "38.5503", :longitude => "44.9521").save
City.new(:country_id => "110", :name => "Khvansar", :aliases => "Khansar,Khavansar,Khonsar,Khunsar,Khvansar,Khvonsar,KhvonsÄr,KhvÄnsÄr,KhÅ«nsÄr,Shahr-e Khvonsar,Shahr-e KhvonsÄr,Ø®ÙØ§ÙØ³Ø§Ø±,KhvÄnsÄr", :latitude => "33.22052", :longitude => "50.31497").save
City.new(:country_id => "110", :name => "Khorramshahr", :aliases => "Al-Muhammarah,Chorramschahr,Khorram Shahr Abadan,Khorram Shahr ÄbÄdÄn,Khorramchahre,Khorramshahr,Khorremshekhr,Khunin Shahr,Khurramshahr,KhÅ«nÄ«n Shahr,Mohammerah,Muhammerah,khrmshhr,Ð¥Ð¾ÑÑÐµÐ¼ÑÐµÑÑ,Ø®Ø±ÙØ´ÙØ±,Ø®Ø±ÙÙØ´ÙØ±,Khorramshahr", :latitude => "30.4397", :longitude => "48.1664").save
City.new(:country_id => "110", :name => "Khorramabad", :aliases => "Khorramabad,KhorramÄbÄd,Khur Ramabad,Khur RamÄbÄd,Khurramobod,khuram abad,Ð¥ÑÑÑÐ°Ð¼Ð¾Ð±Ð¾Ð´,Ø®Ø±Ù Ø¢Ø¨Ø§Ø¯,Ø®Ø±ÙÙ Ø¢Ø¨Ø§Ø¯,Ø®ÙØ±ÙÙÙ Ø¢Ø¨Ø§Ø¯,KhorramÄbÄd", :latitude => "33.48778", :longitude => "48.35583").save
City.new(:country_id => "110", :name => "Khomeyn", :aliases => "Khomein,Khomeyn,KhomeÄ«n,Khowmeyn,Khumain,KhÅ«maÄ«n,khumin,khwmayn,Ø®ÙÙÙ,Ø®ÙÙÙÙÙ,Ø®ÙÙÙÙÙ,Ø®ÙÙÙÙÙÙ,Khomeyn", :latitude => "33.64226", :longitude => "50.0789").save
City.new(:country_id => "110", :name => "Herowabad", :aliases => "Harau,Harowabad,Herau,Herauabad,Heroabad,Herow,Herowabad,HerowÄbÄd,HeroÄbÄd,Hirabad,HirÄbÄd,Khalkhal,KhalkhÄl,haruabad,hiru,hiru abad,hrw abad,khalkhal,Ø®ÙÙØ®Ø§Ù,ÙØ±Ù Ø¢Ø¨Ø§Ø¯,ÙÙØ±ÙÙÙØ¨ÙØ¯,ÙÙØ±Ù Ø¢Ø¨Ø§Ø¯,ÙÙØ±ÙÙ,HerowÄbÄd", :latitude => "37.6189", :longitude => "48.5258").save
City.new(:country_id => "110", :name => "Kermanshah", :aliases => "Bahtaran,Bakhtaran,BÄkhtarÄn,Kermansah,Kermansaho,Kermanschah,Kermanshah,Kermanshahan,Kermanshakh,KermanÅaho,KermanÅah,KermÃ¢nsÃ¢h,KermÄnschÄh,KermÄnshÄh,KermÄnshÄhÄn,Kirmansan,KirmanÅan,Province de Kermanshah,Provincia de Kermanshah,Provinco Kermansah,Provinco KermanÅah,ProvÃ­ncia de Kermanshah,Qahremanshahr,QahremÄnshahr,astan krmanshah,ke er man sha han sheng,kerumansha zhou,krmanshah,mhafzt krmanshah,ÐÐµÑÐ¼Ð°Ð½ÑÐ°Ñ,ÐÐ¸ÑÐ¼Ð¾Ð½ÑÐ¾Ò³,Ð£ÑÑÐ¾Ð½Ð¸ ÐÐ¸ÑÐ¼Ð¾Ð½ÑÐ¾Ò³,Ø§Ø³ØªØ§Ù Ú©Ø±ÙØ§ÙØ´Ø§Ù,ÙØ­Ø§ÙØ¸Ø© Ú©Ø±ÙØ§ÙØ´Ø§Ù,Ú©Ø±ÙØ§ÙØ´Ø§Ù,ã±ã«ãã¼ã³ã·ã£ã¼å·,åç¾æ¼æ²æ±ç,KermÄnshÄh", :latitude => "34.31417", :longitude => "47.065").save
City.new(:country_id => "110", :name => "Kerman", :aliases => "Carmana,Kerman,KermÃ¡n,KermÄn,Kirman,Kirmon,keruman,ÐÐµÑÐ¼Ð°Ð½,ÐÐ¸ÑÐ¼Ð¾Ð½,Ú©Ø±ÙØ§Ù,ã±ã«ãã¼ã³,KermÄn", :latitude => "30.29368", :longitude => "57.08123").save
City.new(:country_id => "110", :name => "Kazerun", :aliases => "Kasrun,Kazarun,Kazeroun,Kazerun,Kazeruna,KÄzarÅ«n,KÄzerÅ«n,ÐÐ°Ð·ÐµÑÑÐ½Ð°,ÙØ§Ø²Ø±ÙÙ,KÄzerÅ«n", :latitude => "29.61949", :longitude => "51.65415").save
City.new(:country_id => "110", :name => "Kashmar", :aliases => "Kashmar,Khashmar,KÄshmar,Soultanabad,Torshiz,TorshÄ«z,Turshiz,TurshÄ«z,Ú©Ø§Ø´ÙØ±,KÄshmar", :latitude => "35.23831", :longitude => "58.46558").save
City.new(:country_id => "110", :name => "Kashan", :aliases => "Kachan,Kashan,kashan,ÐÐ°ÑÐ°Ð½,Ú©Ø§Ø´Ø§Ù,ã«ã¼ã·ã£ã¼ã³,KÄshÄn", :latitude => "33.98308", :longitude => "51.43644").save
City.new(:country_id => "110", :name => "Karaj", :aliases => "Heredi,Karadj,Karadje,Karadsch,Karaj,Karej,Keredi,Leredi,Qasabeh-e Karaj,QaÅabeh-e Karaj,karadj,karadji,karij,krj,qasabihi karaj,ÐÐ°ÑÐ°Ð¹,ÙÙØµÙØ¨ÙÙÙ ÙÙØ±ÙØ¬,ÙØ±Ø¬,ÙÙØ±ÙØ¯Ø¬,ÙÙØ±ÙØ¯Ø¬Ù,ÙÙØ±ÙØ¬,Ú©Ø±Ø¬,Karaj", :latitude => "35.8355", :longitude => "51.0103").save
City.new(:country_id => "110", :name => "Kangavar", :aliases => "Kangavar,KangÄvar,Ú©ÙÚ¯Ø§ÙØ±,KangÄvar", :latitude => "34.5043", :longitude => "47.9653").save
City.new(:country_id => "110", :name => "Kamyaran", :aliases => "Kamyaran,KÄmyÄrÄn,Ú©Ø§ÙÛØ§Ø±Ø§Ù,KÄmyÄrÄn", :latitude => "34.7956", :longitude => "46.9355").save
City.new(:country_id => "110", :name => "Kalaleh", :aliases => "Kalalah,Kalaleh,KalÄlah,KalÄleh,kalalah,ÙÙØ§ÙÙ,ÙÙÙØ§ÙÙÙ,KalÄleh", :latitude => "37.38071", :longitude => "55.49164").save
City.new(:country_id => "110", :name => "Juybar", :aliases => "Baghlu,BÄghlÅ«,Juybar,JÅ«ybÄr,baghlw,jwybar,Ø¨Ø§ØºÙÙ,Ø¬ÙÙØ¨Ø§Ø±,JÅ«ybÄr", :latitude => "36.64115", :longitude => "52.91244").save
City.new(:country_id => "110", :name => "Javanrud", :aliases => "Juanru,JÅ«ÄnrÅ«,Qal`a Juanrud,Qal`a JÅ«anrÅ«d,Qal`eh Juanrud,Qal`eh JÅ«ÄnrÅ«d,Qal`eh-ye Javanrud,Qal`eh-ye JavÄnrÅ«d,JavÄnrÅ«d", :latitude => "34.79611", :longitude => "46.51722").save
City.new(:country_id => "110", :name => "Ilam", :aliases => "Elam,ElÄm,Ilam,aylam,ylam,ÄªlÄm,ÐÐ»Ð°Ð¼,Ø§ÙØ§Ù,Ø§ÙÙØ§Ù,Ø§ÛÙØ§Ù,ÙÙØ§Ù,ÄªlÄm", :latitude => "33.6374", :longitude => "46.4227").save
City.new(:country_id => "110", :name => "Harsin", :aliases => "Harsin,HarsÄ«n,ÙØ±Ø³ÛÙ,HarsÄ«n", :latitude => "34.2721", :longitude => "47.5861").save
City.new(:country_id => "110", :name => "Hamadan", :aliases => "Ecbatana,Hamadan,HamadÄn,Hamedan,HamedÄn,Khamadan,hamadan,hamidan,Ð¥Ð°Ð¼Ð°Ð´Ð°Ð½,ÙÙØ¯Ø§Ù,ÙÙÙÙØ¯Ø§Ù,ÙÙÙÙØ¯Ø§Ù,HamadÄn", :latitude => "34.79922", :longitude => "48.51456").save
City.new(:country_id => "110", :name => "Gorgan", :aliases => "Asterabad,AsterÄbÄd,Girkanija,Gorgan,GorgÄn,Gurgan,Gurgon,GÅ«rgÄn,Hirkanio,aastir abad,gwrgan,ÐÐ¸ÑÐºÐ°Ð½Ð¸Ñ,ÐÑÑÐ³Ð¾Ð½,Ø§ÙØ³ØªÙØ± Ø¢Ø¨Ø§Ø¯,Ú¯Ø±Ú¯Ø§Ù,Ú¯ÙØ±Ú¯Ø§Ù,GorgÄn", :latitude => "36.83866", :longitude => "54.43475").save
City.new(:country_id => "110", :name => "Gonbad-e Qabus", :aliases => "Dashte Gorgan,Gonbad Qabus,Gonbad Qavoos,Gonbad QÄbÅ«s,Gonbad-e Kavus,Gonbad-e KÄvÅ«s,Gonbad-e Qabus,Gonbad-e QÄbÅ«s,Gunbad-i-Kawas,Gunbad-i-Kawus,Gunbad-i-KÄwÄs,Gunbad-i-KÄwÅ«s,Gunbad-i-Qabus,Gunbad-i-QÄbÅ«s,dashti gurgan,gunbad qabws,gunbad qawus,gunbadi kawws,Ø¯ÙØ´ØªÙ Ú¯ÙØ±Ú¯ÙÙ,Ú¯ÙØ¨Ø¯ ÙØ§Ø¨ÙØ³,Ú¯ÙÙØ¨ÙØ¯ ÙØ§Ø¨ÙØ³,Ú¯ÙÙØ¨ÙØ¯ ÙÙÙÙÙØ³,Ú¯ÙÙØ¨ÙØ¯Ù ÙØ§ÙÙØ³,Gonbad-e QÄbÅ«s", :latitude => "37.25004", :longitude => "55.16721").save
City.new(:country_id => "110", :name => "Gonabad", :aliases => "Gonabad,GonÄbÄd,Gunabad,GÅ«nÄbÄd,Juymand,JÅ«ymand,Ú¯ÙØ§Ø¨Ø§Ø¯,GonÄbÄd", :latitude => "34.35286", :longitude => "58.68365").save
City.new(:country_id => "110", :name => "Golpayegan", :aliases => "Golpayagan,Golpayegan,GolpÄyagÄn,GolpÄyegÄn,Gulpaigan,GulpÄÄ«gÄn,Shahr-e Golpayegan,Shahr-e GolpÄyegÄn,Ú¯ÙÙ¾Ø§ÛÚ¯Ø§Ù,GolpÄyegÄn", :latitude => "33.4537", :longitude => "50.28836").save
City.new(:country_id => "110", :name => "Gerash", :aliases => "Gerash,GerÄsh,Girash,GirÄsh,Ú¯Ø±Ø§Ø´,GerÄsh", :latitude => "27.6652", :longitude => "54.1371").save
City.new(:country_id => "110", :name => "Bandar-e Ganaveh", :aliases => "Bandar-e Ganaveh,Bandar-e GanÄveh,Bandar-e Genaveh,Bandar-e GenÄveh,Bandar-e-Gonaveh,Bandar-e-GonÄveh,Ganaveh,GanÄveh,Genaveh,GenÄveh,Gonaveh,GonÄveh,Kenareh,KenÃ¢reh,bandari ginawih,bndri gnawh,ganawih,ginawih,gunawih,Ø¨ÙØ¯Ø±Ù Ú¯ÙØ§ÙÙ,Ø¨ÙÙØ¯ÙØ±Ù Ú¯ÙÙØ§ÙÙÙ,Ú¯ÙÙØ§ÙÙÙ,Ú¯ÙÙØ§ÙÙÙ,Ú¯ÙÙØ§ÙÙÙ,Bandar-e GanÄveh", :latitude => "29.5791", :longitude => "50.517").save
City.new(:country_id => "110", :name => "Firuzabad", :aliases => "Firuzabad,FÄ«rÅ«zÄbÄd,ÙÛØ±ÙØ² Ø¢Ø¨Ø§Ø¯,FÄ«rÅ«zÄbÄd", :latitude => "28.8438", :longitude => "52.5707").save
City.new(:country_id => "110", :name => "Fereydun Kenar", :aliases => "Faridun Kinar,Fereidun Kenar,Fereydun Kenar,FereydÅ«n KenÄr,FÄridÅ«n KinÄr,Qasabeh,QaÅabeh,frydwn knar,qasabih,ÙØ±ÙØ¯ÙÙ ÙÙØ§Ø±,ÙÙØµÙØ¨ÙÙ,FereydÅ«n KenÄr", :latitude => "36.68642", :longitude => "52.52255").save
City.new(:country_id => "110", :name => "Fasa", :aliases => "Fasa,Fassa,FasÄ,ÙØ³Ø§,FasÄ", :latitude => "28.9383", :longitude => "53.6482").save
City.new(:country_id => "110", :name => "Farsan", :aliases => "Farsa,Farsan,Farsian,Farsun,FarsÅ«n,FÄrsÄ,FÄrsÄn,FÄrsÄ«Än,farsan,farswn,ÙØ§Ø±Ø³Ø§,ÙØ§Ø±Ø³Ø§Ù,ÙØ§Ø±Ø³ÙØ§Ù,ÙÙØ±Ø³ÙÙ,FÄrsÄn", :latitude => "32.25694", :longitude => "50.56096").save
City.new(:country_id => "110", :name => "Esfarayen", :aliases => "Esfarayen,EsfarÄyen,Meyanabad,MeyanÄbÄd,Mianabad,Miyanabad,MÄ«yÄnÄbÄd,MÄ«ÄnÄbÄd,Ø§Ø³ÙØ±Ø§ÛÙ,EsfarÄyen", :latitude => "37.07645", :longitude => "57.51009").save
City.new(:country_id => "110", :name => "Shahrud", :aliases => "Emamshahr,EmÄmshahr,Shahrud,Sharud,ShÄhrÅ«d,ShÄrÅ«d,aimamshahr,shahrwd,sharwd,Ø§ÙÙØ§ÙØ´ÙÙØ±,Ø´Ø§Ø±ÙØ¯,Ø´Ø§ÙØ±ÙØ¯,ShÄhrÅ«d", :latitude => "36.41819", :longitude => "54.97628").save
City.new(:country_id => "110", :name => "Do Gonbadan", :aliases => "Do Gonbadan,Do GonbadÄn,Dow Gonbadan,Dow GonbadÄn,Du Gunbadan,Du GunbadÄn,Gachsaran,GachsÄrÄn,du gunbadan,gchsaran,Ø¯ÙÙ Ú¯ÙÙØ¨ÙØ¯Ø§Ù,Ú¯ÚØ³Ø§Ø±Ø§Ù,Do GonbadÄn", :latitude => "30.3586", :longitude => "50.7981").save
City.new(:country_id => "110", :name => "Delijan", :aliases => "Dalijan,DalijÄn,Delijan,DelÄ«jÄn,Dilijan,DilÄ«jÄn,dlyjan,Ø¯ÙÙØ¬Ø§Ù,DelÄ«jÄn", :latitude => "33.9905", :longitude => "50.6838").save
City.new(:country_id => "110", :name => "Dehloran", :aliases => "Deh Lovan,Deh LovÄn,Deh Luran,Deh LÅ«rÄn,Dehloran,DehlorÄn,Dekhlorana,dhlran,dih lwran,dihluran,ÐÐµÑÐ»Ð¾ÑÐ°Ð½Ð°,Ø¯Ù ÙÙØ§Ù,Ø¯ÙÙØ±Ø§Ù,Ø¯ÙÙ ÙÙØ±Ø§Ù,Ø¯ÙÙ ÙÙÙØ§Ù,Ø¯ÙÙÙÙØ±Ø§Ù,DehlorÄn", :latitude => "32.6941", :longitude => "47.2679").save
City.new(:country_id => "110", :name => "Dehdasht", :aliases => "Dehdasht,Dehdast,Kuhgiluyeh,dihdast,Ø¯ÙØ¯Ø´Øª,Ø¯ÙÙØ¯ÙØ³Øª,Dehdasht", :latitude => "30.7949", :longitude => "50.56458").save
City.new(:country_id => "110", :name => "Susangerd", :aliases => "Dasht-e Azadegan,Dasht-e ÄzÄdegÄn,Dasht-i-Mishan,Dasht-i-MishÄn,Dashte' Mishan,Dashteâ Mishan,Khafajiyah,Khafajiyaz,Khafajiyeh,Susangerd,Susangird,Susangurd,SÅ«sangerd,SÅ«sangird,SÅ«sangurd,Ø³ÙØ³ÙÚ¯Ø±Ø¯,SÅ«sangerd", :latitude => "31.5608", :longitude => "48.1831").save
City.new(:country_id => "110", :name => "Darab", :aliases => "Darab,DÄrÄb,DÄrÄb", :latitude => "28.75194", :longitude => "54.54444").save
City.new(:country_id => "110", :name => "Damghan", :aliases => "Damghan,DÄmghÄn,damghan,Ø¯Ø§ÙØºØ§Ù,DÄmghÄn", :latitude => "36.1683", :longitude => "54.348").save
City.new(:country_id => "110", :name => "Damavand", :aliases => "Damavand,DamÄvand,Demavend,DemÄvend,Qasabeh-e Damavand,QaÅabeh-e DamÄvand,damawand,dimawind,qasabihi damawand,ÐÐ°Ð¼Ð°Ð²Ð°Ð½Ð´,Ø¯ÙÙØ§ÙÙÙØ¯,Ø¯ÙÙØ§ÙÙÙØ¯,ÙÙØµÙØ¨ÙÙÙ Ø¯ÙÙØ§ÙÙÙØ¯,DamÄvand", :latitude => "35.71778", :longitude => "52.065").save
City.new(:country_id => "110", :name => "Chenaran", :aliases => "Chanaran,ChanÄrÄn,Chenaran,ChenÄrÄn,Chinaran,ChinÄrÄn,ÚÙØ§Ø±Ø§Ù,ChenÄrÄn", :latitude => "36.64546", :longitude => "59.12123").save
City.new(:country_id => "110", :name => "Chalus", :aliases => "Chalus,ChÄlÅ«s,chalws,Ð§Ð°Ð»ÑÑ,ÚØ§ÙÙØ³,ChÄlÅ«s", :latitude => "36.655", :longitude => "51.4204").save
City.new(:country_id => "110", :name => "Bandar Bushehr", :aliases => "Abu Shehr,Abuschehr,Bandar Abu Shehr,Bandar Bushehr,Bandar BÅ«shehr,Bandar-e Bushehr,Bandar-e BÅ«shehr,Bouchehr,Buschehr,Buschir,Busehr,Bushehr,Busher,Bushir,Bushire,BÅ«shehr,bndr bwshhr,bwshhr,bwshihr,ÐÑÑÐµÑ,ÐÑÑÐ¸Ñ,ÐÓ¯ÑÐµÒ³Ñ,ÐÓ¯ÑÐ¸Ò³Ñ,Ø¨ÙØ¯Ø± Ø¨ÙØ´ÙØ±,Ø¨ÙØ´ÙØ±,Ø¨ÙØ´ÙÙØ±,Bandar BÅ«shehr", :latitude => "28.9684", :longitude => "50.8385").save
City.new(:country_id => "110", :name => "Bukan", :aliases => "Bokan,Bowkan,BowkÄn,Bukan,BÅ«kÄn,ÐÑÐºÐ°Ð½,Ø¨ÙÚ©Ø§Ù,BÅ«kÄn", :latitude => "36.521", :longitude => "46.2089").save
City.new(:country_id => "110", :name => "Borujerd", :aliases => "Borudzherd,Borujerd,BorÅ«jerd,Burujird,BÅ«rÅ«jÄ«rd,brwjrd,bwrwjyrd,ÐÐ¾ÑÑÐ´Ð¶ÐµÑÐ´,Ø¨Ø±ÙØ¬Ø±Ø¯,Ø¨ÙØ±ÙØ¬ÙØ±Ø¯,BorÅ«jerd", :latitude => "33.8973", :longitude => "48.7516").save
City.new(:country_id => "110", :name => "Borujen", :aliases => "Amrujan,AmrÅ«jÄn,Beroojen,Borujan,Borujen,BorÅ«jen,BorÅ«jÄn,Burujan,BurÅ«jÄn,Urujan,UrÅ«jÄn,aamrwjan,birujin,burwjan,Ø§ÙÙØ±ÙØ¬Ø§Ù,Ø¨Ø±ÙØ¬Ù,Ø¨ÙØ±ÙØ¬Ø§Ù,Ø¨ÙØ±ÙÙØ¬ÙÙ,BorÅ«jen", :latitude => "31.96523", :longitude => "51.2873").save
City.new(:country_id => "110", :name => "Borazjan", :aliases => "Borazdjan,Borazjan,Borazjun,BorÄzjÄn,BorÄzjÅ«n,burazdjan,burazjwn,Ø¨Ø±Ø§Ø²Ø¬Ø§Ù,Ø¨ÙØ±Ø§Ø²Ø¬ÙÙ,Ø¨ÙØ±ÙØ²Ø¯Ø¬ÙÙ,BorÄzjÄn", :latitude => "29.2666", :longitude => "51.2159").save
City.new(:country_id => "110", :name => "Bojnurd", :aliases => "Bodzhnurd,Bojnourd,Bojnurd,BojnÅ«rd,Bujnurd,BujnÅ«rd,ÐÐ¾Ð´Ð¶Ð½ÑÑÐ´,Ø¨Ø¬ÙÙØ±Ø¯,BojnÅ«rd", :latitude => "37.47473", :longitude => "57.32903").save
City.new(:country_id => "110", :name => "Birjand", :aliases => "Birdjand,Birdzhend,Birjand,BÄ«rjand,shhrstan byrjnd,ÐÐ¸ÑÐ´Ð¶ÐµÐ½Ð´,ÐÓ£ÑÒ·Ð°Ð½Ð´,Ø¨ÙØ±Ø¬ÙØ¯,Ø´ÙØ±Ø³ØªØ§Ù Ø¨ÛØ±Ø¬ÙØ¯,BÄ«rjand", :latitude => "32.86628", :longitude => "59.22114").save
City.new(:country_id => "110", :name => "Bijar", :aliases => "Bidzhar,Bijar,BÄ«jÄr,byjar,ÐÐ¸Ð´Ð¶Ð°Ñ,Ø¨ÙØ¬Ø§Ø±,BÄ«jÄr", :latitude => "35.8668", :longitude => "47.60506").save
City.new(:country_id => "110", :name => "Bonab", :aliases => "Benab,BenÄb,Binab,BinÄb,Bonab,BonÄb,Bunab,bnab,bunab,ÐÐ¾Ð½Ð°Ð±,Ø¨ÙØ§Ø¨,Ø¨ÙÙØ§Ø¨,Ø¨ÙÙØ§Ø¨,BonÄb", :latitude => "37.3404", :longitude => "46.0561").save
City.new(:country_id => "110", :name => "Behshahr", :aliases => "Ashraf,Behshahr,Bekhshekhr,aashraf,ÐÐµÑÑÐµÑÑ,Ø§ÙØ´Ø±ÙÙ,Ø¨ÙØ´ÙØ±,Behshahr", :latitude => "36.69276", :longitude => "53.54598").save
City.new(:country_id => "110", :name => "Behbahan", :aliases => "Behbahan,BehbahÄn,Behbehan,BehbehÄn,Ø¨ÙØ¨ÙØ§Ù,BehbahÄn", :latitude => "30.5959", :longitude => "50.2417").save
City.new(:country_id => "110", :name => "Baneh", :aliases => "Bane,Baneh,Bani,BÄneh,banh,bani,banih,ÐÐ°Ð½Ð¸,Ø¨Ø§ÙÙ,Ø¨Ø§ÙÙÙ,Ø¨ÙÙÙ,BÄneh", :latitude => "35.9975", :longitude => "45.8853").save
City.new(:country_id => "110", :name => "Bandar-e Lengeh", :aliases => "Bandar Langeh,Bandar-e Lengeh,Bandar-e-Langeh,Lengeh,Linja,Linjah,bandar langih,lingih,Ø¨ÙØ¯Ø± ÙÙÚ¯Ù,Ø¨ÙÙØ¯ÙØ± ÙÙÙÚ¯ÙÙ,ÙÙÙÚ¯ÙÙ,Bandar-e Lengeh", :latitude => "26.55792", :longitude => "54.88067").save
City.new(:country_id => "110", :name => "Bandar-e-Emam Khomeyni", :aliases => "Bandar Chahpour,Bandar Khomani,Bandar Khomeini,Bandar Khoumeini,Bandar Shahpoor,Bandar Shahpur,Bandar ShÄhpÅ«r,Bandar-e Khomeyni,Bandar-e KhomeynÄ«,Bandar-e Shahpur,Bandar-e ShÄhpÅ«r,Bandar-e-Emam Khomeyni,Bandar-e-EmÄm KhomeynÄ«,Bandar-e-Shahpour,Imam Khomeyni,Bandar-e-EmÄm KhomeynÄ«", :latitude => "30.43556", :longitude => "49.10556").save
City.new(:country_id => "110", :name => "Bandar-e Anzali", :aliases => "Bandar Anzali,Bandar Pahlavi,Bandar Pahlevi,Bandar-e Anzali,Bandar-e AnzalÄ«,Bandar-e Pahlavi,Bandar-e PahlavÄ«,Enceli,Enzeli,Pahlavi,PahlavÄ«,Pahlevi,PahlevÄ«,Pehlevi,Ø¨ÙØ¯Ø± Ø§ÙØ²ÙÛ,Bandar-e AnzalÄ«", :latitude => "37.4727", :longitude => "49.4622").save
City.new(:country_id => "110", :name => "Bandar 'Abbas", :aliases => "Bandar Abbas,Bandar Abbas - Ø¨ÙØ¯Ø± Ø¹Ø¨Ø§Ø³,Bandar `Abbas,Bandar `Abbasi,Bandar âAbbÄs,Bandar âAbbÄsÄ«,Bandar-Abbos,Bandar-e `Abbas,Bandar-e âAbbÄs,Bender-Abbas,Cambarao,CambarÃ£o,Gombroon,Gumrun,Port Comorao,Port ComorÃ£o,a ba si gang,gumbrun,ÐÐ°Ð½Ð´Ð°Ñ-ÐÐ±Ð±Ð¾Ñ,ÐÐµÐ½Ð´ÐµÑ-ÐÐ±Ð±Ð°Ñ,Ø¨ÙØ¯Ø± Ø¹Ø¨Ø§Ø³,Ø¨ÙÙØ¯ÙØ± Ø¹ÙØ¨ÙØ§Ø³Û,Ø¨ÙÙØ¯ÙØ±Ù Ø¹ÙØ¨ÙØ§Ø³,Ú¯ÙÙØ¨Ø±ÙÙÙ,ãã³ãã¬ã»ã¢ããã¼ã¹,é¿å·´æ¯æ¸¯,Bandar âAbbÄs", :latitude => "27.1865", :longitude => "56.2808").save
City.new(:country_id => "110", :name => "Bam", :aliases => "Bam,bamu,bm,ÐÐ°Ð¼,Ø¨Ù,ãã ,Bam", :latitude => "29.106", :longitude => "58.357").save
City.new(:country_id => "110", :name => "Bahar", :aliases => "Bahar,BahÄr,Bakhar,bahar,ÐÐ°ÑÐ°Ñ,Ø¨ÙØ§Ø±,Ø¨ÙÙØ§Ø±,BahÄr", :latitude => "34.9072", :longitude => "48.4414").save
City.new(:country_id => "110", :name => "Bafq", :aliases => "Bafk,Bafq,BÄfq,bafq,ÐÐ°ÑÐº,Ø¨Ø§ÙÙ,BÄfq", :latitude => "31.61283", :longitude => "55.41067").save
City.new(:country_id => "110", :name => "Babolsar", :aliases => "Babolsar,Babul Sar,BÄbolsar,BÄbul Sar,Mashhad-i-Sar,Mashhadsar,Meshed-i-Sar,bablsr,mashhadsar,Ø¨Ø§Ø¨ÙØ³Ø±,ÙÙØ´ÙÙØ¯Ø³ÙØ±,BÄbolsar", :latitude => "36.70251", :longitude => "52.6576").save
City.new(:country_id => "110", :name => "Babol", :aliases => "Babol,Babol',Babul,Balfrush,Barfarush,Barfrush,Barfurush,BÄbol,BÄbul,BÄrfurush,babl,ÐÐ°Ð±Ð¾Ð»Ñ,Ø¨Ø§Ø¨Ù,BÄbol", :latitude => "36.55132", :longitude => "52.67895").save
City.new(:country_id => "110", :name => "Azna", :aliases => "Azna,AznÄ,azna,Ø§Ø²ÙØ§,AznÄ", :latitude => "33.6095", :longitude => "48.9307").save
City.new(:country_id => "110", :name => "Hashtrud", :aliases => "Azaran,Hashtrud,HashtrÅ«d,Sar Eskand,Sar Eskand Khan,Sar Eskand KhÄn,Sar Eskandar,Saraskand,SarÄskand,ÄzÌarÄn,ÙØ´ØªØ±ÙØ¯,HashtrÅ«d", :latitude => "37.4779", :longitude => "47.0508").save
City.new(:country_id => "110", :name => "Astara", :aliases => "Astara,ÄstÄrÄ,ÐÑÑÐ°ÑÐ°,Ø¢Ø³ØªØ§Ø±Ø§,ÄstÄrÄ", :latitude => "38.4291", :longitude => "48.872").save
City.new(:country_id => "110", :name => "Astaneh-ye Ashrafiyeh", :aliases => "Astane,Astaneh,Astaneh-ye Ashrafiyeh,ÄstÄneh,ÄstÄneh-ye AshrafÄ«yeh,Ø¢Ø³ØªØ§ÙÙ Ø§Ø´Ø±ÙÛÙ,ÄstÄneh-ye AshrafÄ«yeh", :latitude => "37.25962", :longitude => "49.94444").save
City.new(:country_id => "110", :name => "Asadabad", :aliases => "Asadabad,Asadabada,AsadÄbÄd,aasad abad,ÐÑÐ°Ð´Ð°Ð±Ð°Ð´Ð°,Ø§Ø³Ø¯ Ø¢Ø¨Ø§Ø¯,Ø§ÙØ³ÙØ¯ Ø¢Ø¨Ø§Ø¯,AsadÄbÄd", :latitude => "34.78241", :longitude => "48.11853").save
City.new(:country_id => "110", :name => "Ardestan", :aliases => "Ardestan,ArdestÄn,Ardistan,ArdistÄn,Ø§Ø±Ø¯Ø³ØªØ§Ù,ArdestÄn", :latitude => "33.3761", :longitude => "52.3694").save
City.new(:country_id => "110", :name => "Ardakan", :aliases => "Ardakan,ArdakÄn,Ardekan,aardakan,aardikan,Ø§Ø±Ø¯Ú©Ø§Ù,Ø§ÙØ±Ø¯ÙÙØ§Ù,Ø§ÙØ±Ø¯ÙÙÙÙ,ArdakÄn", :latitude => "32.31001", :longitude => "54.01747").save
City.new(:country_id => "110", :name => "Ardabil", :aliases => "Ardabil,ArdabÄ«l,Ardebil,Ardebil - ardbyl,Ardebil - Ø§Ø±Ø¯Ø¨ÛÙ,ArdebÄ«l,aardibyl,ardbyl,erdebil,ÆrdÉbil,ÐÑÐ´Ð°Ð±Ð¸Ð»,Ø§Ø±Ø¯Ø¨ÙÙ,Ø§Ø±Ø¯Ø¨ÛÙ,Ø§ÙØ±Ø¯ÙØ¨ÙÙ,ArdabÄ«l", :latitude => "38.2498", :longitude => "48.2933").save
City.new(:country_id => "110", :name => "Arak", :aliases => "Arak,Arak - sawh,Arak - Ø³Ø§ÙÙ,Arok,ArÄk,Ehrak,Soltanabad,SolÅ£ÄnÄbÄd,Sultanabad,SultÄnÄbÄd,`Iraq,arak,sawh,sultan abad,ÐÑoÐº,ÐÑÐ°Ðº,Ð­ÑÐ°Ðº,Ø§Ø±Ø§Ù,Ø§Ø±Ø§Ú©,Ø³Ø§ÙÙ,Ø³ÙÙØ·Ø§Ù Ø¢Ø¨Ø§Ø¯,âIrÄq,ArÄk", :latitude => "34.09174", :longitude => "49.68916").save
City.new(:country_id => "110", :name => "Amol", :aliases => "Amol,Amol',Amul,aml,Ämol,ÐÐ¼Ð¾Ð»Ñ,Ø¢ÙÙ,Ämol", :latitude => "36.46961", :longitude => "52.35072").save
City.new(:country_id => "110", :name => "Alvand", :aliases => "Alband,Alvand,Alwand,El'vend,Elâvend,aalband,alwnd,ÐÐ»Ð²Ð°Ð½Ð´,Ø§ÙÙÙØ¯,Ø§ÙÙØ¨ÙÙØ¯,Ø§ÙÙØ¡ÙÙÙØ¯,Alvand", :latitude => "36.3187", :longitude => "49.1678").save
City.new(:country_id => "110", :name => "Shahriar", :aliases => "Ali Shah `Iwaz,Ali ShÄh âIwaz,Shahreyar,ShahreyÄr,Shahriar,Shahriyar,ShahriyÄr,ShahrÄ«Är,Shakhrijar,`Ali Shah `Avaz,shhryar,Ð¨Ð°ÑÑÐ¸ÑÑ,Ø´ÙØ±ÙØ§Ø±,Ø¹ÙÙÛ Ø´Ø§Ù Ø¹ÙÙÙØ¶,âAlÄ« ShÄh âAvaáº,ShahrÄ«Är", :latitude => "35.6596", :longitude => "51.0593").save
City.new(:country_id => "110", :name => "Aligudarz", :aliases => "Aligoodarz,Aligudarz,AlÄ«gÅ«darz,`Ali Gudar,ÐÐ»Ð¸Ð³ÑÐ´Ð°ÑÐ·,Ø§ÙÙÚ¯ÙØ¯Ø±Ø²,âAli GudÄr,AlÄ«gÅ«darz", :latitude => "33.40063", :longitude => "49.6949").save
City.new(:country_id => "110", :name => "Aleshtar", :aliases => "Alashtar,Aleshtar,Alishtar,AlishtÄr,Qal`eh Mozaffari,Qal`eh `Alishtar,Qalâeh MozÌ§affari,Qalâeh âAlishtÄr,aalashtar,aalishtar,alshtr,Ø§ÙØ´ØªØ±,Ø§ÙÙÙØ´ØªÙØ±,Ø§ÙÙÙØ´ØªÙØ±,Aleshtar", :latitude => "33.8633", :longitude => "48.2619").save
City.new(:country_id => "110", :name => "Akbarabad", :aliases => "Akbar Abad Kawar,Akbarabad,Akbarabad-e Kavar,AkbarÄbÄd,AkbarÄbÄd-e KavÄr,ÐÐºÐ±Ð°ÑÐ°Ð±Ð°Ð´,Ø§Ú©Ø¨Ø± Ø¢Ø¨Ø§Ø¯,AkbarÄbÄd", :latitude => "29.2464", :longitude => "52.7793").save
City.new(:country_id => "110", :name => "`Ajab Shir", :aliases => "Ajabshahr,`Ajab Shir,aajabshahr,Ø§ÙØ¬ÙØ¨Ø´ÙÙØ±,Ø¹Ø¬Ø¨ Ø´ÛØ±,Ø¹ÙØ¬ÙØ¨ Ø´ÙØ±,âAjab ShÄ«r,âAjab ShÄ«r", :latitude => "37.4776", :longitude => "45.8943").save
City.new(:country_id => "110", :name => "Ahvaz", :aliases => "Ahvaz,Ahvaz - ahwaz,Ahvaz - Ø§ÙÙØ§Ø²,AhvÄz,Ahwaz,AhwÄz,Akhvaz,Bandar Nasiri,Bandar NÄsirÄ«,Bandar-e Naser,Bandar-e NÄÅer,Naseri,Nasiri,NÄsiri,NÄÅerÄ«,a wa shi,afuvu~azu,alahwaz,ÐÑÐ²Ð°Ð·,ÐÒ³Ð²Ð¾Ð·,Ø§ÙØ£Ø­ÙØ§Ø²,Ø§ÙÙØ§Ø²,ã¢ãã´ã¡ã¼ãº,é¿ç¦å£«,AhvÄz", :latitude => "31.3203", :longitude => "48.6693").save
City.new(:country_id => "110", :name => "Ahar", :aliases => "Ahar,Akhar,ahr,ÐÑÐ°Ñ,Ø§ÙØ±,Ahar", :latitude => "38.4774", :longitude => "47.0699").save
City.new(:country_id => "110", :name => "Aghajari", :aliases => "Agha Jari,Aghajari,Aqa Jari,ÄghÄ JÄrÄ«,ÄghÄjÄrÄ«,ÄqÄ JarÄ«,Ø¢ØºØ§Ø¬Ø§Ø±Û,ÄghÄjÄrÄ«", :latitude => "30.7006", :longitude => "49.8315").save
City.new(:country_id => "110", :name => "Abyek", :aliases => "Abiak,abyik,Ø¢Ø¨ÙÙÙ,Äbyek", :latitude => "36.06667", :longitude => "50.55").save
City.new(:country_id => "110", :name => "Abhar", :aliases => "Abhar,Abkhar,aabkhar,abr,ÐÐ±ÑÐ°Ñ,Ø§Ø¨Ø±,Ø§ÙØ¨Ø®ÙØ±,Abhar", :latitude => "36.1468", :longitude => "49.218").save
City.new(:country_id => "110", :name => "Abdanan", :aliases => "Abdanan,Qal`a Ab-i-Danan,Qal`eh Ab-i-Danan,Qal`eh-ye Ab Danan,Qalâa Ab-Ä«-Danan,Qalâeh Äb-Ä«-DÄnÄn,Qalâeh-ye Äb DÄnÄn,ÄbdÄnÄn,Ø¢Ø¨Ø¯Ø§ÙØ§Ù,ÙÙÙØ¹ÙÛ Ø¢Ø¨ Ø¯Ø§ÙØ§Ù,ÄbdÄnÄn", :latitude => "32.9926", :longitude => "47.4198").save
City.new(:country_id => "110", :name => "Abadeh", :aliases => "Abadeh,ÄbÄdeh,Ø¢Ø¨Ø§Ø¯Ù,ÄbÄdeh", :latitude => "31.1608", :longitude => "52.6506").save
City.new(:country_id => "110", :name => "Abadan", :aliases => "Abadan,Abadan - abadan,Abadano,AbadÃ¡n,AbadÃ¡n - Ø¢Ø¨Ø§Ø¯Ø§Ù,a ba dan,abadan,ÃbÃ¡dÃ¡n,ÄbÄdÄn,ÐÐ±Ð°Ð´Ð°Ð½,Ø¢Ø¨Ø§Ø¯Ø§Ù,Ø¹Ø¨Ø¯Ø§Ù,ã¢ããã¼ã³,ã¢ã¼ãã¼ãã¼ã³,é¿å·´ä¸¹,ÄbÄdÄn", :latitude => "30.3392", :longitude => "48.3043").save
City.new(:country_id => "110", :name => "Eqbaliyeh", :aliases => "Eqbalieh,Eqbaliyeh,EqbÄlÄ«eh,EqbÄlÄ«yeh,aiqbalyih,Ø§ÙØ¨Ø§ÙÙÙ,Ø§ÙØ¨Ø§ÙÙÙÙ,Ø§ÙÙØ¨Ø§ÙÙÙÙ,EqbÄlÄ«yeh", :latitude => "35.3022", :longitude => "51.5358").save
City.new(:country_id => "110", :name => "Shahreza", :aliases => ",ShÄhreáºÄ", :latitude => "32.03389", :longitude => "51.87944").save
City.new(:country_id => "110", :name => "Rehnan", :aliases => "Rahnan,Rehnan,RehnÄn,Renan,RenÄn,Rohanan,Rohnan,Ø±ÙÙØ§Ù,RehnÄn", :latitude => "32.685", :longitude => "51.6044").save
City.new(:country_id => "110", :name => "Qahderijan", :aliases => "Kedargun,KedargÅ«n,Qadrijan,QadrijÄn,Qadrja,QadrjÄ,Qahderijan,QahderÄ«jÄn,ÙÙØ¯Ø±ÛØ¬Ø§Ù,QahderÄ«jÄn", :latitude => "32.5767", :longitude => "51.455").save
City.new(:country_id => "110", :name => "Najafabad", :aliases => "Nadzhafabad,Najafabad,NajafÄbÄd,Nejafabad,NejafÄbÄd,ÐÐ°Ð´Ð¶Ð°ÑÐ°Ð±Ð°Ð´,ÙØ¬Ù Ø¢Ø¨Ø§Ø¯,NajafÄbÄd", :latitude => "32.6344", :longitude => "51.3668").save
City.new(:country_id => "110", :name => "Khomeyni Shahr", :aliases => "Homayoon Shahr,Homayunshahr,HomÄyÅ«nshahr,Khomeyni Shahr,Khomeynishahr,KhomeynÄ« Shahr,KhomeynÄ«shahr,Sedeh,Ø®ÙÛÙÛ Ø´ÙØ±,KhomeynÄ« Shahr", :latitude => "32.70018", :longitude => "51.52113").save
City.new(:country_id => "110", :name => "Kelishad", :aliases => "Gulshad,GulshÄd,Kalushad,KalÅ«shÄd,Kelishad,Kelishad-e Sofla,Kelishad-e Vasuderjan,KelÄ«shÄd,KelÄ«shÄd-e SoflÃ¡,KelÄ«shÄd-e VasÅ«derjÄn,Ú©ÙÛØ´Ø§Ø¯,KelÄ«shÄd", :latitude => "32.55231", :longitude => "51.5289").save
City.new(:country_id => "110", :name => "Mollavarjan", :aliases => "Falavarjan,FalÄvarjÄn,Felavarjan,FelÄvarjÄn,Mollavarjan,MollÄvarjÄn,Pol-e Vargan,Pol-e VargÄn,Pol-e Varqan,Pol-e VarqÄn,Pul-i-Vargan,Pul-i-VargÄn,ÙÙØ§ÙØ±Ø¬Ø§Ù,ÙÙÙØ§ÙØ±Ø¬Ø§Ù,MollÄvarjÄn", :latitude => "32.5564", :longitude => "51.51").save
City.new(:country_id => "110", :name => "Esfahan", :aliases => "Aspadana,Esfahan,Esfehan,EÅfahÄn,EÅfehÄn,Isfahan,Isfakhan,Ispahan,ÐÑÑÐ°ÑÐ°Ð½,Ø§ØµÙÙØ§Ù,EÅfahÄn", :latitude => "32.65722", :longitude => "51.67761").save
City.new(:country_id => "110", :name => "Dowlatabad", :aliases => "Daulatabad,DaulatÄbÄd,Dowlatabad,DowlatÄbÄd,Ø¯ÙÙØª Ø¢Ø¨Ø§Ø¯,DowlatÄbÄd", :latitude => "32.79978", :longitude => "51.69553").save
City.new(:country_id => "110", :name => "Dorcheh Piaz", :aliases => "Darcheh Piaz,Darcheh PÄ«Äz,Dorcheh Peyaz,Dorcheh PeyÄz,Dorcheh Piaz,Dorcheh PÄ«Äz,Dorcheh PÄ«Äz", :latitude => "32.61528", :longitude => "51.55556").save
City.new(:country_id => "110", :name => "Zabol", :aliases => "Zabol,Zabol',ZÄbol,ÐÐ°Ð±Ð¾Ð»Ñ,Ø²Ø§Ø¨Ù,ZÄbol", :latitude => "31.0287", :longitude => "61.5012").save
City.new(:country_id => "110", :name => "Zahedan", :aliases => "Dowzdab,DowzdÄb,Duzdab,Duzdap,DuzdÄb,DuzdÄp,Zahedan,Zahedan-e (Yek),Zahidan,Zaidan,ZaidÄn,Zakhedan,ZÄhedÄn,ZÄhedÄn-e (Yek),ÐÐ°ÑÐµÐ´Ð°Ð½,Ø²Ø§ÙØ¯Ø§Ù,ZÄhedÄn", :latitude => "29.4963", :longitude => "60.8629").save
City.new(:country_id => "110", :name => "Torbat-e Jam", :aliases => "Torbat-e Jam,Torbat-e JÄm,Torbat-e Sheykh Jam,Torbat-e Sheykh JÄm,Turbat-i-Shaikh Jam,ØªØ±Ø¨Øª Ø¬Ø§Ù,Torbat-e JÄm", :latitude => "35.244", :longitude => "60.6225").save
City.new(:country_id => "110", :name => "Taybad", :aliases => "Taiabad,Taybad,Tayebad,Tayebat,Tayyebat,TaÄ«abad,TÄybÄd,TÄyebÄt,Å¢ayyebÄt,ØªØ§ÙØ¨Ø§Ø¯,TÄybÄd", :latitude => "34.74", :longitude => "60.7756").save
City.new(:country_id => "110", :name => "Sarakhs", :aliases => "Sarakhs,Serakhs,Ð¡Ð°ÑÐ°ÑÑ,Ø³Ø±Ø®Ø³,Sarakhs", :latitude => "36.5449", :longitude => "61.1577").save
City.new(:country_id => "110", :name => "Khash", :aliases => "Kavash,Khash,KhÄsh,Kwash,KwÄsh,Vasht,VÄsht,Ð¥Ð°Ñ,Ø®Ø§Ø´,KhÄsh", :latitude => "28.22107", :longitude => "61.21582").save
City.new(:country_id => "110", :name => "Iranshahr", :aliases => "Fahrej,Fehruj,Iranshahr,Qal`eh-ye Naseri,Qalâeh-ye NÄÅerÄ«,ÄªrÄnshahr,Ø§ÙØ±Ø§ÙØ´ÙØ±,ÄªrÄnshahr", :latitude => "27.20245", :longitude => "60.68476").save
City.new(:country_id => "110", :name => "Chah Bahar", :aliases => "Bandar Beheshti,Bandar BeheshtÄ«,Chabahar,Chabakhar,Chah Bahar,Chah-e-Bahar,Chahbar,ChÄbahÄr,ChÄh BahÄr,ChÄh-e-BahÄr,ChÄhbÄr,Ð§Ð°Ð±Ð°ÑÐ°Ñ,ÚØ§Ù Ø¨ÙØ§Ø±,ChÄh BahÄr", :latitude => "25.2919", :longitude => "60.643").save
