City.new(:country_id => "115", :name => "Wadi as Sir", :aliases => "Wadi Al Seer,Wadi Sir,Wadi as Sir,Wadi es Sir,Wadi es SÄ«r,WÄdÄ« as SÄ«r,WÄdÄ« as SÄ«r", :latitude => "31.95", :longitude => "35.81667").save
City.new(:country_id => "115", :name => "Umm as Summaq", :aliases => "Um el Semmaq,Um es Summaq,Um es SummÄq,Umm as Summaq,Umm as SummÄq,Umm as SummÄq", :latitude => "31.88333", :longitude => "35.85").save
City.new(:country_id => "115", :name => "Sahab", :aliases => "Sahab,Sakhab,Saá¸©Äb,Sehab,Ð¡Ð°ÑÐ°Ð±,Saá¸©Äb", :latitude => "31.87861", :longitude => "36.00444").save
City.new(:country_id => "115", :name => "Madaba", :aliases => "Madaba,Madeba,Medeba,Meideva,MeidevÄ,MÄdeba,mhafzt madba,ÐÐ°Ð´Ð°Ð±Ð°,××¤×ª ×××××,ÙØ­Ø§ÙØ¸Ø© ÙØ§Ø¯Ø¨Ø§,MÄdabÄ", :latitude => "31.71667", :longitude => "35.8").save
City.new(:country_id => "115", :name => "Kurayyimah", :aliases => "Kareime,Kereime,Kuraiyima,Kuraymah,Kurayyimah,Kureima,Kureiyima,Quraymah,Kurayyimah", :latitude => "32.27639", :longitude => "35.59938").save
City.new(:country_id => "115", :name => "Jarash", :aliases => "Djerash,Dzherash,Gerasa,Jarash,Jerasa,Jerash,g'rs,jrsh,mhafzt jrsh,ÐÐ¶ÐµÑÐ°Ñ,×'×¨×©,Ø¬Ø±Ø´,ÙØ­Ø§ÙØ¸Ø© Ø¬Ø±Ø´,Jarash", :latitude => "32.28082", :longitude => "35.89929").save
City.new(:country_id => "115", :name => "`Izra", :aliases => "`Azra,`Izra,âAzrÄ,âIzrÄ,âIzrÄ", :latitude => "31.15889", :longitude => "35.69278").save
City.new(:country_id => "115", :name => "Irbid", :aliases => "Arbela,ArbÄla,Irbid,arbd,ÐÑÐ±Ð¸Ð´,×××¨×××,Ø¥Ø±Ø¨Ø¯,Irbid", :latitude => "32.55556", :longitude => "35.85").save
City.new(:country_id => "115", :name => "Az Zarqa'", :aliases => "Az Zarqa',Az ZarqÄâ,Kalaat el Zerka,Qal`at az Zarqa',Qal`at ez Zerqa,Qalâat az ZarqÄâ,Qalâat ez Zerqa,Zarka,Zarqa,Zarqa',ZarqÄâ,Zerka,ÐÐ°ÑÐºÐ°,Ø§ÙØ²Ø±ÙØ§Ø¡,Ø²Ø±ÙØ§Ø¡,Az ZarqÄâ", :latitude => "32.07275", :longitude => "36.08796").save
City.new(:country_id => "115", :name => "Aydun", :aliases => "Aidun,AidÅ«n,Aydun,AydÅ«n,Eidun,EidÅ«n,AydÅ«n", :latitude => "32.50722", :longitude => "35.8575").save
City.new(:country_id => "115", :name => "At Tafilah", :aliases => "At Tafila,At Tafilah,AÅ£ Å¢afÄ«lah,Aá¹­ á¹¬afÄ«la,El Tafile,Et Tafila,Et TafÄ«la,Tafila,Tafile,Tafileh,TafÄ«la,Tofel,Tophel,Tufailah,Ø§ÙØ·ÙÙÙØ©,AÅ£ Å¢afÄ«lah", :latitude => "30.83333", :longitude => "35.6").save
City.new(:country_id => "115", :name => "As Salt", :aliases => "Al-Salt,As Salt,As SalÅ£,Es Salt,Ramoth Gil`ad,RÄmoth GilâÄd,Salt,As SalÅ£", :latitude => "32.03917", :longitude => "35.72722").save
City.new(:country_id => "115", :name => "Ar Ramtha", :aliases => "Ar Ramtha,Ar RamthÄ,El Remteh,Er Remtha,Ramtha,alrmtha,Ø§ÙØ±ÙØ«Ø§,Ar RamthÄ", :latitude => "32.55917", :longitude => "36.00694").save
City.new(:country_id => "115", :name => "`Anjarah", :aliases => "`Anjara,`Anjarah,âAnjara,âAnjarah,âAnjarah", :latitude => "32.3063", :longitude => "35.75653").save
City.new(:country_id => "115", :name => "Amman", :aliases => "Ama,Aman,Amanas,Amano,Amman,Ammon,AmmÃ¡n,AmÃ¡n - Ø¹ÙØ§Ù,AmÃ£,Philadelphia,Rabbah,Rabbath Ammon,`Amman,`AmmÄn,am'mana,amman,an man,anman,ÎÎ¼Î¼Î¬Î½,ÐÐ¼Ð°Ð½,ÐÐ¼Ð¼Ð°Ð½,ÐÐ¼Ð¼Ð¾Ð½,Ô±Õ´Õ¡Õ¶,×¨××ª ×¢×××,Ø¹ÙØ§Ù,Ø¹ÙÙÙØ§Ù,Ü¥Ü¡Ü¢,à¤à¤®à¥à¤®à¤¾à¤¨,à¦à¦®à§à¦®à¦¾à¦¨,á áá,ã¢ã³ãã³,å®æ¼,ìë§,Amman", :latitude => "31.95522", :longitude => "35.94503").save
City.new(:country_id => "115", :name => "Al Quwaysimah", :aliases => "Al Quwaysimah,El Quweisima,El Quweisme,Al Quwaysimah", :latitude => "31.91667", :longitude => "35.95").save
City.new(:country_id => "115", :name => "Al Mafraq", :aliases => "Al Mafraq,El-Fedein,Kalat el Mafrak,Mafraq,Qal`at al Mafraq,Qal`at el Mafraq,Qalâat al Mafraq,Qalâat el Mafraq,Al Mafraq", :latitude => "32.34289", :longitude => "36.20804").save
City.new(:country_id => "115", :name => "Qir Moav", :aliases => "Al Karak,Ehl'-Karak,El Kerak,Karak,Kerak,Kir Moab,Ð­Ð»Ñ-ÐÐ°ÑÐ°Ðº,QÄ«r MoÄv", :latitude => "31.18248", :longitude => "35.69999").save
City.new(:country_id => "115", :name => "Al Jubayhah", :aliases => "Al Jubayhah,El Jebeihe,El Jubeiha,Jubeiha,Al Jubayhah", :latitude => "32.01667", :longitude => "35.86667").save
City.new(:country_id => "115", :name => "Aqaba", :aliases => "Akaba,Akabe,Al-'Aqabah,Al-âAqabah,Aqaba,Qal`at el `Aqaba,`Aqaba,akaba,ya ke ba,ÐÐºÐ°Ð±Ð°,×¢×§××,Ø§ÙØ¹ÙØ¨Ø©,Ø¹ÙØ¨Ù,ã¢ã«ã,äºåå·´,Aqaba", :latitude => "29.52667", :longitude => "35.00778").save
City.new(:country_id => "115", :name => "`Ajlun", :aliases => "Adjlun,`Ajlun,âAjlÅ«n,âAjlÅ«n", :latitude => "32.33385", :longitude => "35.75238").save
City.new(:country_id => "115", :name => "Karak City", :aliases => "Al-Karak,Karak,Kerak,ÐÐ°ÑÐ°Ðº,Karak City", :latitude => "31.16368", :longitude => "35.76204").save
