City.new(:country_id => "119", :name => "Phnom Penh", :aliases => "Nam Van,Nam-Vang,Phnom Pen,Phnom Penh,Phnom PÃ©nh,Phnom-Penh,Phnompenh,Phnum Penh,Phnum PÃ©nh,PhnÃ´m PÃªnh,Phon Phen,Pnom Pen,Pnom Pen'ch,Pnom Penh,Pnompen',Pnompenis,Ville de Phnom Penh,jin bian,peunompen,phnm pen,phnmpey,pnwm pn,punonpen,Î Î½Î¿Î¼ Î ÎµÎ½Ï,ÐÐ½Ð¾Ð¼ ÐÐµÐ½,ÐÐ½Ð¾Ð¼Ð¿ÐµÐ½Ñ,×¤× ×× ×¤×,Ù¾ÙÙÙÙ Ù¾ÛÙ,à¸à¸à¸¡à¹à¸à¸,à¸à¸à¸¡à¹à¸à¸,ááá áá,áááá»áááááááá,ããã³ãã³,éè¾¹,íëí,Phnom Penh", :latitude => "11.56245", :longitude => "104.91601").save
City.new(:country_id => "119", :name => "Ta Khmau", :aliases => "Ta Khmau,Takhman,Takhmau,Takkhmau,Ð¢Ð°ÐºÑÐ¼Ð°Ñ,Ta Khmau", :latitude => "11.48333", :longitude => "104.95").save
City.new(:country_id => "119", :name => "Stoeng Treng", :aliases => "Stoeng Treng,Stung Teeng,Stung Treng,StÅÌng TrÃªng,StÅÌng TrÃªng", :latitude => "13.52586", :longitude => "105.9683").save
City.new(:country_id => "119", :name => "Sisophon", :aliases => "Sesopone,Sisobhon,Sisophon,SisÅphÅn,SisÅphÅn", :latitude => "13.58588", :longitude => "102.97369").save
City.new(:country_id => "119", :name => "Siemreab", :aliases => "Ciudad de Siem Riep,Khett Siem Reab,Siem Reap,Siem Riep,Siem-Reap,Siemrap,SiemrÃ£p,SiÃªm Riá»p,seiym reiyb,shemuriappu,xian li sheng,xian li shi,Ð¡Ð¸ÐµÐ¼-Ð ÐµÐ°Ð¿,à¹à¸ªà¸µà¸¢à¸¡à¹à¸£à¸µà¸¢à¸,ã·ã§ã ãªã¢ãã,æ¹ç²å¸,æ¹ç²ç,SiÄmrÃ©ab", :latitude => "13.36667", :longitude => "103.85").save
City.new(:country_id => "119", :name => "Pursat", :aliases => "Porsat,Pousat,Pouthisat,PoÅ­sÄt,PoÅ­thÄ­sÄt,Pursat,Pursat", :latitude => "12.53878", :longitude => "103.9192").save
City.new(:country_id => "119", :name => "Phumi Veal Sre", :aliases => ",PhumÄ­ VÃ©al SrÃª", :latitude => "10.98333", :longitude => "104.78333").save
City.new(:country_id => "119", :name => "Phnum Tbeng Meanchey", :aliases => "Kampong Preng,Kimpong Pranak,Kompong Pranak,Kompong Prena,Kompong Preng,Phnom Tbeng Meanchey,Phnom Thbeng Meanchey,Phnom Thbeng Neanchey,Phnum Tbeng Meanchey,Phnum TbÃªng MÃ©anchey,Phom Thbeng Meanchey,Phumi Thbeng Meanchey,PhumÄ­ Thbeng Meanchey,Thbeng Meanchey,Phnum TbÃªng MÃ©anchey", :latitude => "13.81667", :longitude => "104.96667").save
City.new(:country_id => "119", :name => "Paoy Pet", :aliases => "Paoy Pet,PaÃ´y PÃªt,Phum Paoy Pet,Phum PaÃ´y PÃªt,Phumi Paoy Pet,PhumÄ­ PaÃ´y PÃªt,Poipet,Pojpet,ÐÐ¾Ð¹Ð¿ÐµÑ,PaÃ´y PÃªt", :latitude => "13.65611", :longitude => "102.5625").save
City.new(:country_id => "119", :name => "Pailin", :aliases => "Ciudad de Pailin,Ciudad de PailÃ­n,Krong Pailin,Pailin,PailÄ­n,pairin,áááá»áááááá·á,ãã¤ãªã³,PailÄ­n", :latitude => "12.84895", :longitude => "102.60928").save
City.new(:country_id => "119", :name => "Lumphat", :aliases => "Lomphat,Lumphat,LumphÄt,LumphÄt", :latitude => "13.48784", :longitude => "106.98158").save
City.new(:country_id => "119", :name => "Krong Kaoh Kong", :aliases => "Khemarak Phoumin,Khemarak Phoumin Ville,Khemareah Phumint,Koh Kong,Koville,Krong Kao Kong,Krong Kaoh Kong,Krong Khemarak Phoumin,Krong Khemoreah Phumint,Krong Koh Kong,KrÅng KaÃ´h KÅng,KrÅng KhÃ©mÃ´reÄh PhumÄ­nt,KrÅng KaÃ´h KÅng", :latitude => "11.6175", :longitude => "102.98056").save
City.new(:country_id => "119", :name => "Kratie", :aliases => "Kracheh,Krati,Kratie,KrÃ¢chÃ©h,KratiÃ©", :latitude => "12.48811", :longitude => "106.01879").save
City.new(:country_id => "119", :name => "Kampot", :aliases => "Compong Bai,Compong BaÃ¯,Kampat,Kampot,Kamput,Kompong Bai,Krong Kampot,KrÅng KÃ¢mpÃ´t,KÃ¢mpÃ´t,ÐÐ°Ð¼Ð¿Ð¾Ñ,KÃ¢mpÃ´t", :latitude => "10.61667", :longitude => "104.18333").save
City.new(:country_id => "119", :name => "Kampong Thum", :aliases => "Kampong Thom,Kampong Thum,Kampong Thun,Kompong Thom,KÃ¢mpÃ³ng Thum,KÃ¢mpÃ³ng Thum", :latitude => "12.71112", :longitude => "104.88873").save
City.new(:country_id => "119", :name => "Kampong Spoe", :aliases => "Kampong Spoe,Kompon Spu,Kompong Speu,KÃ¢mpÃ³ng SpÅ,KÅmpon Spu,KÃ¢mpÃ³ng SpÅ", :latitude => "11.45", :longitude => "104.53333").save
City.new(:country_id => "119", :name => "Sihanoukville", :aliases => "Ciudad de Sihanoukville,Kampong Saom,Kampong Semville,Kampong Somville,Kom Pong Song,Kompong Som,Kompong Somville,Krong Preah Seihanu,Krong Preah Sihanouk,KrÅng PreÄh SeihanÅ­,KrÅng PreÄh Sihanouk,KÃ¢mpÃ³ng SaÃ´m,Port de Sihanoukville,Preah Seihanouk,Sianukvil',Sihanouk,Sihanoukville,Sikanonville,shianukubiru,sih nu will,xi ha nu ke shi,Ð¡Ð¸Ð°Ð½ÑÐºÐ²Ð¸Ð»Ñ,à¸ªà¸µà¸«à¸à¸¸à¸§à¸´à¸¥à¸¥à¹,áááá»ááááááá¸á áá»,ã·ã¢ãã¼ã¯ãã«,è¥¿ååªåå¸,Sihanoukville", :latitude => "10.60932", :longitude => "103.52958").save
City.new(:country_id => "119", :name => "Kampong Chhnang", :aliases => "Kampong Chhnang,Kampong Chnang,Kampongchnang,Kompon Chnang,Kompong Chhang,Kompong Chhnang,KÃ¢mpÃ³ng ChhnÄng,Phumi Kampong Chhnang,PhumÄ­ KÃ¢mpÃ´ng ChhnÄng,ÐÐ°Ð¼Ð¿Ð¾Ð½Ð³ÑÐ½Ð°Ð½Ð³,KÃ¢mpÃ³ng ChhnÄng", :latitude => "12.25", :longitude => "104.66667").save
City.new(:country_id => "119", :name => "Kampong Cham", :aliases => "Compon-lina,Kampong Cham,Kampongtjam,Kompon Cam,Kompong Cham,KÃ¢mpÃ³ng Cham,ÐÐ°Ð¼Ð¿Ð¾Ð½Ð³ÑÑÐ¼,KÃ¢mpÃ³ng Cham", :latitude => "11.99339", :longitude => "105.4635").save
City.new(:country_id => "119", :name => "Batdambang", :aliases => "Batdambang,Battamban,Battambang,BÄtdÃ¢mbÃ¢ng,Ciudad de Battambang,Khett Batdambang,Phratabong,ma de wang,áá¶áááááá,é©¬å¾·æ,BÄtdÃ¢mbÃ¢ng", :latitude => "13.10271", :longitude => "103.19822").save
