City.new(:country_id => "123", :name => "Yonan-up", :aliases => "Enan,Yonan,Yonan-up,YÅnan,YÅnan-Å­p,YÅnan-Å­p", :latitude => "37.90889", :longitude => "126.16111").save
City.new(:country_id => "123", :name => "Wonsan", :aliases => "Gensan,Genzan,Genzan Hu,Onsan,Vonsan,Vonsanas,Wensen,Wonsan,WÅnsan,Yuenchan,Yuensan,wonsansi,yuan shan,yuan shan shi,ÐÐ¾Ð½ÑÐ°Ð½,åå±±,åå±±å¸,ìì°,ìì°ì,WÅnsan", :latitude => "39.15278", :longitude => "127.44361").save
City.new(:country_id => "123", :name => "T'ongch'on-up", :aliases => "Kojo,KojÅ,Kotei,T'ongch'on,T'ongch'on-up,TâongchâÅn,TâongchâÅn-Å­p,TâongchâÅn-Å­p", :latitude => "38.95389", :longitude => "127.89167").save
City.new(:country_id => "123", :name => "Sungho 1-tong", :aliases => "Shoko-ri,ShÅko-ri,Sungho,Sungho 1-tong,Sungho-dong,Sungno-ri,SÅ­ngho,SÅ­ngho 1-tong,SÅ­ngho-dong,SÅ­ngno-ri,seungho1dong,ì¹í¸1ë,SÅ­ngho 1-tong", :latitude => "38.99139", :longitude => "125.97778").save
City.new(:country_id => "123", :name => "Sunan", :aliases => "Junan,Sunan,Sunan-dong,Sunan-ni,Sunan-up,Sunan-Å­p,Ð¡ÑÐ½Ð°Ð½,Sunan", :latitude => "39.19833", :longitude => "125.69").save
City.new(:country_id => "123", :name => "Songnim", :aliases => "Kenjiho,Kenjiko,Kenniho,Kenziho,Kyomip'o,KyÅmipâo,Shorin,ShÅrin,Songnim,Songnim", :latitude => "38.75417", :longitude => "125.645").save
City.new(:country_id => "123", :name => "Sil-li", :aliases => "Sil-li,Sin-ni,Sil-li", :latitude => "39.49472", :longitude => "125.47361").save
City.new(:country_id => "123", :name => "Sinmak", :aliases => "Shimbaku,Shimmaku,Shinbaku,Sinmak,Sinmak", :latitude => "38.41667", :longitude => "126.23333").save
City.new(:country_id => "123", :name => "Sinanju", :aliases => "Shin-anshu,Shin-anshÅ«,Sin-ansyu,Sin-ansyÅ«,Sinanju,Sinanju-nodongjagu,Sinanju-rodongjagu,Wonhung-ni,WÅnhÅ­ng-ni,sin-anju,ì ìì£¼,Sinanju", :latitude => "39.59806", :longitude => "125.60972").save
City.new(:country_id => "123", :name => "Sariwon", :aliases => "Hozan,Sa-ri-uen,Sarivone,Sariwon,SariwÅn,Shariin,Syariin,SÄ-ri-uen,Ð¡Ð°ÑÐ¸Ð²Ð¾Ð½Ðµ,SariwÅn", :latitude => "38.50722", :longitude => "125.75583").save
City.new(:country_id => "123", :name => "Samho-rodongjagu", :aliases => "Samho,Samho-dong,Samho-nodongjagu,Samho-rodongjagu,Sanko,samholodongjagu,ì¼í¸ë¡ëìêµ¬,Samho-rodongjagu", :latitude => "39.9475", :longitude => "127.87111").save
City.new(:country_id => "123", :name => "Pyongyang", :aliases => "Binh Nhuong,BÃ¬nh NhÆ°á»¡ng,Heijo,Heijo-fu,HeijÅ,HeijÅ-fu,Heizyo,Heizyo Hu,HeizyÅ,HeizyÅ Hu,Hpyeng-yang,P'yongyang,P'yÅngyang,P-hjong-jang,P-hjÃ¶ng-jang,Pchenjanas,Pchjongjang,Phenian,Phenjan,Phenjana,Phyeng-yang,Phyong-yang,Pienyang,Pingyang,Pion'nkgian'nk,Pjoengjang,Pjongjang,Pjongjango,PjÃ¶ngjang,Pkhen'jan,Pkhenjan,Pyengyang,Pyoengyang,Pyongyang,PyÃ¶ngyang,PâyÅngyang,bywnyangh,peiyngyang,ping rang,pyeong-yangjighalsi,pyongayanga,pywngyang,Î Î¹Î¿Î½Î³ÎºÎ³Î¹Î¬Î½Î³Îº,ÐÑÐµÐ½ÑÑÐ½,ÐÑÐµÐ½ÑÐ½,ÐÑÐ¾Ð½Ð³ÑÐ°Ð½Ð³,×¤××× ×××× ×,Ø¨ÙÙÙÙØ§ÙØº,Ù¾ÙÙÚ­ÙØ§Ú­,à¤ªà¥à¤¯à¥à¤à¤à¤¯à¤¾à¤à¤,à¹à¸à¸µà¸¢à¸à¸¢à¸²à¸,áá®áá«áá,å¹³å£,å¹³å£¤,íìì§í ì,Pyongyang", :latitude => "39.03385", :longitude => "125.75432").save
City.new(:country_id => "123", :name => "Ongjin", :aliases => "Bazan,Onchzhin,Ongjin,Ongjin-up,Ongjin-Å­p,Oshin,Osin,Yoshin,YÅshin,ongjin,Åshin,Åsin,ÐÐ½ÑÐ¶Ð¸Ð½,ì¹ì§,Ongjin", :latitude => "37.93472", :longitude => "125.36194").save
City.new(:country_id => "123", :name => "Namp'o", :aliases => "Channampo,Chinnamp'o,Chinnampâo,Chinnanpo,Namp'o,Nampkho,Nampâo,Tinnanpo,Treaty Port,Tschin-nam-p-ho,nampo,ÐÐ°Ð¼Ð¿ÑÐ¾,ë¨í¬,Nampâo", :latitude => "38.7375", :longitude => "125.40778").save
City.new(:country_id => "123", :name => "Kusong", :aliases => "Kijo,KijÅ,Kuisong,KuisÅng,Kusong,Kusong-up,KusÅng,KusÅng-Å­p,Kwisog,KwisÅg,KusÅng", :latitude => "39.98111", :longitude => "125.24472").save
City.new(:country_id => "123", :name => "Kujang-up", :aliases => "Kuchung,Kujang,Kujang-dong,Kujang-up,Kujang-Å­p,Kyujo-do,KyujÅ-dÅ,Kujang-Å­p", :latitude => "39.86722", :longitude => "126.03028").save
City.new(:country_id => "123", :name => "Kowon-up", :aliases => "Kogen,Kovon-do,Kowon,Kowon-up,KowÅn,KowÅn-Å­p,KÅgen,ÐÐ¾Ð²Ð¾Ð½-Ð´Ð¾,ê³ ì,KowÅn-Å­p", :latitude => "39.43806", :longitude => "127.24306").save
City.new(:country_id => "123", :name => "Kosan", :aliases => "Kosan,Kosan-up,Kosan-Å­p,Shinko-san,Shinkozan,ShinkÅ-san,ShinkÅzan,Sin'gosan,Sinâgosan,gosan,ê³ ì°,Kosan", :latitude => "38.85583", :longitude => "127.41806").save
City.new(:country_id => "123", :name => "Kangdong-up", :aliases => "Kandong,Kangdong,Kangdong-up,Kangdong-Å­p,Koto,KÅtÅ,Kangdong-Å­p", :latitude => "39.1425", :longitude => "126.09611").save
City.new(:country_id => "123", :name => "Kaesong", :aliases => "Kaesong,KaesÅng,Kai-seng,Kaijo,KaijÅ,Kaisong,Kaizyo,KaizyÅ,Kehson,Kesonas,KÄsonas,Shoto,ShÅto,Songdo,gaeseongsi,gaeseongteuggeubsi,kai cheng,ÐÑÑÐ¾Ð½,å¼å,éå,ê°ì±ì,ê°ì±í¹ê¸ì,KaesÅng", :latitude => "37.97083", :longitude => "126.55444").save
City.new(:country_id => "123", :name => "Hwangju-up", :aliases => "Hwangju,Hwangju-up,Hwangju-Å­p,Koshu,Koshyu,Kosyu,KÅshÅ«,KÅsyÅ«,Hwangju-Å­p", :latitude => "38.67028", :longitude => "125.77611").save
City.new(:country_id => "123", :name => "Hungnam", :aliases => "Hungbong-ni,Hungdogi-dong,Hungdogil-tong,Hungdok-2-dong,Hungdok-tong,Hungdoki-dong,Hungdong-ni,Hungnam,Hungnam-dong,Hungnam-ni,Hungyam,HÅ­ngbong-ni,HÅ­ngdong-ni,HÅ­ngdÅgi-dong,HÅ­ngdÅgil-tong,HÅ­ngdÅk-2-dong,HÅ­ngdÅk-tong,HÅ­ngdÅki-dong,HÅ­ngnam,HÅ­ngnam-dong,HÅ­ngnam-ni,Konan,KÅnan,HÅ­ngnam", :latitude => "39.83167", :longitude => "127.61861").save
City.new(:country_id => "123", :name => "Hukkyo-ri", :aliases => "Hukkyo-ri,HÅ­kkyo-ri,Kokkyo-ri,KokkyÅ-ri,Kokukyori,heuggyoli,íêµë¦¬,HÅ­kkyo-ri", :latitude => "38.79861", :longitude => "125.79194").save
City.new(:country_id => "123", :name => "Hoeyang", :aliases => "Chunyang,Hoeyang,Hoeyang-up,Hoeyang-Å­p,Junyo,Waiyd,WaiyÃ°,hoeyang,íì,Hoeyang", :latitude => "38.71028", :longitude => "127.59833").save
City.new(:country_id => "123", :name => "Hamhung", :aliases => "Hamheung,Hamhunas,Hamhung,Hamhungo,HamhÅ­ng,Hienhing,Kanko,KankÅ,hamheung,hamheungsi,xian xing,xian xing shi,å¸å´,å¸èå¸,í¨í¥,í¨í¥ì,HamhÅ­ng", :latitude => "39.91833", :longitude => "127.53639").save
City.new(:country_id => "123", :name => "Haeju", :aliases => "Haeju,Hai-dschu,Hai-ju,Hai-tjyou,Haijuube,Haitcheou,Kaishu,KaishÅ«,Khehdzhu,Ð¥ÑÐ´Ð¶Ñ,Haeju", :latitude => "38.04056", :longitude => "125.71472").save
City.new(:country_id => "123", :name => "Chunghwa", :aliases => "Chunghwa,Chunghwa-up,Chunghwa-Å­p,Chuwa,ChÅ«wa,junghwa,ì¤í,Chunghwa", :latitude => "38.86389", :longitude => "125.8").save
City.new(:country_id => "123", :name => "Chongju", :aliases => "Chongju,Chongju-up,ChÅngju,ChÅngju-Å­p,Teishu,TeishÅ«,Teisyu,TeisyÅ«,ì ì£¼,ChÅngju", :latitude => "39.69333", :longitude => "125.21028").save
City.new(:country_id => "123", :name => "Changyon", :aliases => "Changyon,Changyon-up,ChangyÅn,ChangyÅn-Å­p,Choen,ChÅen,Tschang-jon,Tschang-jÃ¶n,ì¥ì°,ChangyÅn", :latitude => "38.25083", :longitude => "125.09611").save
City.new(:country_id => "123", :name => "Chaeryong-up", :aliases => "Chaenyong,ChaenyÅng,Chaeryong,Chaeryong-up,ChaeryÅng,ChaeryÅng-Å­p,Cheyong,Sainei,Sainei-men,Sainei-yu,Sainei-yÅ«,ChaeryÅng-Å­p", :latitude => "38.39917", :longitude => "125.61556").save
City.new(:country_id => "123", :name => "Ayang-ni", :aliases => "Ayang-ni,Gayo-ri,GayÅ-ri,Ayang-ni", :latitude => "38.24306", :longitude => "125.78").save
City.new(:country_id => "123", :name => "Anju", :aliases => "Aanshu,An-dschu,Anju,Anju-up,Anju-Å­p,Anshu,AnshÅ«,Ansyu,Ansyu Yu,AnsyÅ«,AnsyÅ« YÅ«,ìì£¼,Anju", :latitude => "39.61778", :longitude => "125.66472").save
City.new(:country_id => "123", :name => "Anbyon-up", :aliases => "Ampen,Anbyon,Anbyon-up,AnbyÅn,AnbyÅn-Å­p,Anhen,Anpen,AnbyÅn-Å­p", :latitude => "39.0425", :longitude => "127.52389").save
City.new(:country_id => "123", :name => "Anak", :aliases => "Aenak,Anag-up,Anag-Å­p,Anak,Anak-up,Anak-Å­p,Angaku,Nangaku,an-ag,ìì,Anak", :latitude => "38.51083", :longitude => "125.49417").save
City.new(:country_id => "123", :name => "Yuktae-dong", :aliases => "Rokudaito-ri,RokudaitÅ-ri,Yuktae-dong,Yuktae-nodongjagu,Yuktaedong-ni,Yuktaetong-ni,Yuktae-dong", :latitude => "40.02472", :longitude => "128.15972").save
City.new(:country_id => "123", :name => "Uiju", :aliases => "Eui-chu,Gishu,GishÅ«,Gisyu,GisyÅ«,Ui-tsiu,Uiju,Uiju-up,Wi-dschu,Wi-ju,uiju,Å¬iju,Å¬iju-Å­p,ìì£¼,Å¬iju", :latitude => "40.19944", :longitude => "124.53167").save
City.new(:country_id => "123", :name => "Sonbong", :aliases => "Ongei,Sonbon,Sonbong,Sonbong-up,SÅnbong,SÅnbong-Å­p,Unggi,Unggi-up,Unggi-yu,Yuki,YÅ«ki,seonbong,Ð¡Ð¾Ð½Ð±Ð¾Ð½,ì ë´,SÅnbong", :latitude => "42.34222", :longitude => "130.39667").save
City.new(:country_id => "123", :name => "Sinuiju", :aliases => "New Eui-chu,Shingishu,ShingishÅ«,Sin-eui-chu,Sin-gi-shu,Sinuidzu,SinuidÅ¾u,Sinuiju,Sinyichju,SinÅ­iju,Szinidzsu,Wi-dschu,Wi-ju,sin-uiju,sin-uijusi,xin yi zhou,xin yi zhou shi,æ°ä¹å·,æ°ç¾©å·å¸,ì ìì£¼,ì ìì£¼ì,SinÅ­iju", :latitude => "40.10056", :longitude => "124.39806").save
City.new(:country_id => "123", :name => "Sakchu-up", :aliases => "Sakchu,Sakchu-up,Sakchu-Å­p,Sakushu,SakushÅ«,Sakchu-Å­p", :latitude => "40.38944", :longitude => "125.04667").save
City.new(:country_id => "123", :name => "Yonggwang-up", :aliases => "Goro-ri,GorÅ-ri,Oro,Oro-ri,Oro-up,Oro-Å­p,Yonggwang-up,Yongwang,YÅnggwang-Å­p,YÅngwang,YÅnggwang-Å­p", :latitude => "40.01833", :longitude => "127.45472").save
City.new(:country_id => "123", :name => "Onsong", :aliases => "Kosong,Kosong-ni,KosÅng,KosÅng-ni,Onjo,OnjÅ,Onsong,Onsong-up,OnsÅng,OnsÅng-Å­p,onseong,ì¨ì±,OnsÅng", :latitude => "42.95722", :longitude => "129.99333").save
City.new(:country_id => "123", :name => "Nanam", :aliases => "Naman,Nanam,Ranam,lanam,ÐÐ°Ð½Ð°Ð¼,ë¼ë¨,Nanam", :latitude => "41.71361", :longitude => "129.68444").save
City.new(:country_id => "123", :name => "Namyang-dong", :aliases => ",Namyang-dong", :latitude => "42.95", :longitude => "129.86667").save
City.new(:country_id => "123", :name => "Najin", :aliases => "Najin,Najin-up,Najin-Å­p,Radzin,Rashin,Rasin,lajin,Ð Ð°Ð´Ð·Ð¸Ð½,ë¼ì§,Najin", :latitude => "42.24889", :longitude => "130.30028").save
City.new(:country_id => "123", :name => "Musan-up", :aliases => "Mosan,Mozan,Musan,Musan-up,Musan-Å­p,ë¬´ì°ì,Musan-Å­p", :latitude => "42.22609", :longitude => "129.20776").save
City.new(:country_id => "123", :name => "Kyongsong", :aliases => "Churuonjan,Chuul,Chuuronjang,ChuÅ­l,ChuÅ­ronjang,Kyongsong,Kyongsong-up,KyÅngsÅng,KyÅngsÅng-Å­p,Shuotsu,Shuotsuonjo,ShuotsuonjÅ,gyeongseong,ê²½ì±,KyÅngsÅng", :latitude => "41.58778", :longitude => "129.60611").save
City.new(:country_id => "123", :name => "Kilju", :aliases => "Kichishu,KichishÅ«,Kil'dzhu,Kil-dschu,Kilchu,Kilchu-up,Kilchu-Å­p,Kilju,Kisshu,KisshÅ«,gilju,ÐÐ¸Ð»ÑÐ´Ð¶Ñ,ê¸¸ì£¼,Kilju", :latitude => "40.96417", :longitude => "129.32778").save
City.new(:country_id => "123", :name => "Kapsan-up", :aliases => "Kapsan,Kapsan-up,Kapsan-Å­p,Kapsane-do,Kosan,Kozan,KÅsan,KÅzan,ÐÐ°Ð¿ÑÐ°Ð½Ðµ-Ð´Ð¾,ê°ì°ì,Kapsan-Å­p", :latitude => "41.09028", :longitude => "128.29333").save
City.new(:country_id => "123", :name => "Kanggye-si", :aliases => "Kakai,Kang-ge,Kange,Kanggye,Kanggye-si,Kokai,KÅkai,gang-gye,gang-gyesi,jiang jie,jiang jie shi,ÐÐ°Ð½Ð³Ðµ,æ±ç,æ±çå¸,ê°ê³,ê°ê³ì,Kanggye-si", :latitude => "40.96946", :longitude => "126.58523").save
City.new(:country_id => "123", :name => "Iwon-up", :aliases => "Gunsen,Iwon,Iwon-up,IwÅn,IwÅn-Å­p,Kunsen,Kunson,KunsÅn,ë¦¬ì,IwÅn-Å­p", :latitude => "40.32306", :longitude => "128.65528").save
City.new(:country_id => "123", :name => "Hyesan-dong", :aliases => "Hyesan-dong,íì°ë,Hyesan-dong", :latitude => "41.39756", :longitude => "128.17873").save
City.new(:country_id => "123", :name => "Hongwon", :aliases => "Hongwon,Hongwon-up,HongwÅn,HongwÅn-Å­p,Kogen,Kogon,KÅgen,hong-won,íì,HongwÅn", :latitude => "40.02528", :longitude => "127.95583").save
City.new(:country_id => "123", :name => "Hoeryong", :aliases => "Hoenyong,HoenyÅng,Hoeryong,Hoeryong-up,HoeryÅng,HoeryÅng-Å­p,Kaeryong,KaeryÅng,Kainei,Kainei-yu,Kainei-yÅ­,Kwainei,hoelyeong,íë ¹,HoeryÅng", :latitude => "42.44278", :longitude => "129.75083").save
City.new(:country_id => "123", :name => "Ch'ongjin", :aliases => "Ch'ongjin,Ch'Ångjin,Chkhonchzhine,Chongjin,Chonjin,ChâÅngjin,Condzinas,Cshongdzsin,Seishin,Seisin,Tschiun-tschan,TschiÃ¼n-tschan,cheongjin,cheongjinsi,qing jin,qing jin shi,ÄondÅ¾inas,Ð§ÑÐ¾Ð½ÑÐ¶Ð¸Ð½Ðµ,æ¸æ´¥,æ¸æ´¥å¸,ì²­ì§,ì²­ì§ì,ChâÅngjin", :latitude => "41.79556", :longitude => "129.77583").save
City.new(:country_id => "123", :name => "Aoji-ri", :aliases => "Agochi,Agochi-do,Agochi-dÅ,Agoji-do,Agoji-dÅ,Aodi-ri,Aoji,Aoji-dong,Aoji-ri,aojili,ÐÐ¾Ð´Ð¸-ÑÐ¸,ìì¤ì§ë¦¬,Aoji-ri", :latitude => "42.52056", :longitude => "130.39528").save
