City.new(:country_id => "124", :name => "Hunghae", :aliases => "Funhai,Heung-hai,Heunghae,Kokai,KÅkai,Uich'ang,Å¬ich'ang,HÅ­nghae", :latitude => "36.1125", :longitude => "129.35222").save
City.new(:country_id => "124", :name => "Yosu", :aliases => "Josu,Rasui,Reisui,Yosu,YÅsu,ÐÐ¾ÑÑ,YÅsu", :latitude => "34.74417", :longitude => "127.73778").save
City.new(:country_id => "124", :name => "Yonil", :aliases => "Eijitsu,Enjitsu,Yeonil,Yonil,YÅnil,YÅnil", :latitude => "35.99417", :longitude => "129.345").save
City.new(:country_id => "124", :name => "Yongwol", :aliases => "Neietsu,Yongwol,YÅngwÅl,ìì,YÅngwÅl", :latitude => "37.18447", :longitude => "128.46821").save
City.new(:country_id => "124", :name => "Yongju", :aliases => "Eisen,Eishu,EishÅ«,Yongju,YÅngju,YÅngju", :latitude => "36.82167", :longitude => "128.63083").save
City.new(:country_id => "124", :name => "Yonggwang", :aliases => "Reiko,Yonggwang,YÅnggwang,YÅnggwang", :latitude => "35.275", :longitude => "126.50944").save
City.new(:country_id => "124", :name => "Yong-dong", :aliases => "Eido,EidÅ,Yong-dong,YÅng-dong,ìë,YÅng-dong", :latitude => "36.175", :longitude => "127.77639").save
City.new(:country_id => "124", :name => "Yongch'on", :aliases => "Eisen,Yongch'on,YÅngchâÅn,YÅngchâÅn", :latitude => "35.9675", :longitude => "128.93083").save
City.new(:country_id => "124", :name => "yeoncheongun", :aliases => "Yeoncheon Gun,Yon-ch'on-gun,YÅn-ch'Ån-gun,yeoncheon,yeoncheongun,ì°ì²,ì°ì²êµ°,ì°ì²êµ°", :latitude => "38.09404", :longitude => "127.07577").save
City.new(:country_id => "124", :name => "Yoju", :aliases => "Reishu,ReishÅ«,Rishu,RishÅ«,Yeoju,Yoju,YÅju,ì¬ì£¼,YÅju", :latitude => "37.29583", :longitude => "127.63389").save
City.new(:country_id => "124", :name => "Yesan", :aliases => "Esan,Jesan,Reisan,Reizan,Yesan,Yosan,YÅsan,ÐÑÐ°Ð½,ìì°,Yesan", :latitude => "36.67756", :longitude => "126.84272").save
City.new(:country_id => "124", :name => "Yangsan", :aliases => "Jansan,Ryosan,Ryozan,RyÅsan,RyÅzan,Yangsan,Ð¯Ð½ÑÐ°Ð½,Yangsan", :latitude => "35.33861", :longitude => "129.03861").save
City.new(:country_id => "124", :name => "Yangp'yong", :aliases => "Tohei,Yangp'yongumnae,Yangp'yÅngÅ­mnae,Yangpyeong,Yanp'yong,Yanp'yÅng,yangpyeong,yangpyeong-gun,ìí,ìíêµ°,Yangp'yÅng", :latitude => "37.48972", :longitude => "127.49056").save
City.new(:country_id => "124", :name => "Yangju", :aliases => "Yangju-gun,yangju,yangjusi,ìì£¼,ìì£¼ì,Yangju", :latitude => "37.83311", :longitude => "127.06169").save
City.new(:country_id => "124", :name => "Yanggu", :aliases => "Yanggu,yang-gu,yang-gugun,ìêµ¬,ìêµ¬êµ°,Yanggu", :latitude => "38.10583", :longitude => "127.98944").save
City.new(:country_id => "124", :name => "Wonju", :aliases => "Genshu,GenshÅ«,Wonju,WÅnju,WÅnju", :latitude => "37.35139", :longitude => "127.94528").save
City.new(:country_id => "124", :name => "Wanju", :aliases => "wanju,wanju-gun,wanjugun,ìì£¼,ìì£¼êµ°,Wanju", :latitude => "35.84509", :longitude => "127.14752").save
City.new(:country_id => "124", :name => "Waegwan", :aliases => "Oegwan,Waegwan,Waegwan-dong,Waegwan-ni,Waikan,Wakan,chungju,ìê´,Waegwan", :latitude => "35.99175", :longitude => "128.39732").save
City.new(:country_id => "124", :name => "Ulsan", :aliases => "Ul'san,Ulsan,Urusan,ulsangwang-yeogsi,wei shan,wei shan guang yu shi,Ð£Ð»ÑÑÐ°Ð½,èå±±,èå±±åºåå¸,ì¸ì°ê´ì­ì,Ulsan", :latitude => "35.53722", :longitude => "129.31667").save
City.new(:country_id => "124", :name => "Uijongbu", :aliases => "Euijeongbu,Giseifu,Uijongbu,Vijongbu,Å¬ijÅngbu,ìì ë¶,Å¬ijÅngbu", :latitude => "37.7415", :longitude => "127.0474").save
City.new(:country_id => "124", :name => "Tangjin", :aliases => "Tangjin,Toshin,Tosin,TÅshin,TÅsin,ë¹ì§,Tangjin", :latitude => "36.89444", :longitude => "126.62972").save
City.new(:country_id => "124", :name => "Taesal-li", :aliases => "Taesal-li,Taesan,Taesan-ni,Taisan-ri,ëì°ë¦¬,Taesal-li", :latitude => "36.9714", :longitude => "126.4542").save
City.new(:country_id => "124", :name => "Taejon", :aliases => "Daejeon,Daejon,Daiden,Taejon,TaejÅn,Taiden,Tehdzhon,Tetyan,Thai-tyen,ThÄi-tyen,TÄtyan,da tian guang yu shi,daejeongwang-yeogsi,Ð¢ÑÐ´Ð¶Ð¾Ð½,å¤§ç°å¹¿åå¸,å¤§ç°åºåå¸,ëì ,ëì ê´ì­ì,TaejÅn", :latitude => "36.32139", :longitude => "127.41972").save
City.new(:country_id => "124", :name => "Taegu", :aliases => "Daegu,Daikyu,DaikyÅ«,Taegu,Taeguo,Taikando,TaikandÅ,Taiku,Taikyu,TaikyÅ«,Tehgu,da qiu,da qiu guang yu shi,daegugwang-yeogsi,Äáº¡i KhÃ¢u,Ð¢ÑÐ³Ñ,å¤§é±,å¤§é±åºåå¸,ëêµ¬ê´ì­ì,Taegu", :latitude => "35.87028", :longitude => "128.59111").save
City.new(:country_id => "124", :name => "Poryong", :aliases => "Daisen,Hannae-ri,Poryong,PoryÅng,Taech'on,Taech'on-ni,TaechâÅn,TaechâÅn-ni,Taisen,Taisen-ri,ë³´ë ¹,PoryÅng", :latitude => "36.34931", :longitude => "126.59772").save
City.new(:country_id => "124", :name => "T'aebaek", :aliases => "T'aebaek,Tkhehbehk,Tâaebaek,Ð¢ÑÑÐ±ÑÐº,íë°±,Tâaebaek", :latitude => "37.1759", :longitude => "128.9889").save
City.new(:country_id => "124", :name => "Suwon", :aliases => "Suigen,Suvon,Suwon,SuwÅn,shui yuan shi,suwonsi,Ð¡ÑÐ²Ð¾Ð½,æ°´åå¸,ìì,ììì,SuwÅn", :latitude => "37.29111", :longitude => "127.00889").save
City.new(:country_id => "124", :name => "Sunch'on", :aliases => "Junten,Sunch'on,Suncheon,Sunchun,SunchâÅn,ìì²,SunchâÅn", :latitude => "34.94808", :longitude => "127.48947").save
City.new(:country_id => "124", :name => "Seoul", :aliases => "Choei-yuen,Ha-seng,Han-yang,Hang-yang-tcheng,Hansong,HansÅng,HÄ-seng,HÄn-yang,Kan-yo-jo,Kan-yÅ-jÅ,Keijo,Keizyoe,KeizyÅe,Kiung,Kyongsong,KyÅngsÅng,SEL,Seoel,Seoul,Seuel,Seul,Seula,Seulas,Seulo,Seulum,SeÃºl,SeÃ¼l,Soeul,Soul,Suigen,Sye-ul,Syou-ouen,Szoeul,SzÃ¶ul,SÃ©oul,SÃ¶ul,SÅul,Wang-ching,Wo-jo,WÅ-jÅ,ciyol,seoul,seoulteugbyeolsi,shou er,siyola,sol,sola,souru te bie shi,sywl,Î£ÎµÎ¿ÏÎ»,Ð¡ÐµÑÐ»,ÕÕ¥Õ¸ÖÕ¬,×¡×××,×¡××××,Ø³Ø¦ÙÙ,Ø³ÛØ¦ÙÙ,à¤¸à¤¿à¤¯à¥à¤²,à¤¸à¥à¤²,à®à®¿à®¯à¯à®²à¯,à¹à¸à¸¥,á¶á,ã½ã¦ã«ç¹å¥å¸,é¦ç¾,ìì¸,ìì¸í¹ë³ì,Seoul", :latitude => "37.56826", :longitude => "126.97783").save
City.new(:country_id => "124", :name => "Sosan", :aliases => "Seosan,Seosan City,Sosan,Suisan,SÅsan,rui shan shi,seosansi,Ð¡Ð¾ÑÐ°Ð½,çå±±å¸,ìì°,ìì°ì,SÅsan", :latitude => "36.78167", :longitude => "126.45222").save
City.new(:country_id => "124", :name => "Sonsan", :aliases => "Jenzan,Sonsan,SÅnsan,ì ì°,SÅnsan", :latitude => "36.24083", :longitude => "128.2975").save
City.new(:country_id => "124", :name => "Songhwan", :aliases => "Seikan-ri,Seonghwan,Songhwan,Songhwan-ni,Songwon,SÅnghwan,SÅnghwan-ni,ì±í,SÅnghwan", :latitude => "36.91556", :longitude => "127.13139").save
City.new(:country_id => "124", :name => "Sokch'o", :aliases => "Sogcho,Sokch'o,Sokch'o-ri,Sokchkho,Sokcho,Sokchâo,Sokchâo-ri,Ð¡Ð¾ÐºÑÑÐ¾,ìì´,Sokchâo", :latitude => "38.20833", :longitude => "128.59111").save
City.new(:country_id => "124", :name => "Sangju", :aliases => "Ch'angju,Châangju,Sandzhu,Sang-dschu,Sangju,Shoshu,ShÅshÅ«,Syosyu,SyÅsyÅ«,Ð¡Ð°Ð½Ð´Ð¶Ñ,ìì£¼,Sangju", :latitude => "36.41528", :longitude => "128.16056").save
City.new(:country_id => "124", :name => "Samch'ok", :aliases => "Samch'ok,SamchâÅk,Samuchoku,Sanchoku,Sansho,Santyoku,ì¼ì²,SamchâÅk", :latitude => "37.44056", :longitude => "129.17083").save
City.new(:country_id => "124", :name => "Puyo", :aliases => "Fuyo,Pujo,Puyo,PuyÅ,ÐÑÐ¹Ð¾,ë¶ì¬,PuyÅ", :latitude => "36.28194", :longitude => "126.9125").save
City.new(:country_id => "124", :name => "Pusan", :aliases => "Busan,BusÃ¡n,Fousan,Fusan,Fuzan,Phu San,Phá»§ San,Pusan,Pusana,Pusano,Tsau-liang-hai,busangwang-yeogsi,fu shan,fu shan guang yu shi,pu san,ÐÑÑÐ°Ð½,à¸à¸¹à¸à¸²à¸,éå±±,éå±±åºåå¸,ë¶ì°ê´ì­ì,Pusan", :latitude => "35.10278", :longitude => "129.04028").save
City.new(:country_id => "124", :name => "Puch'on", :aliases => "Bucheon,Puch'on,Puchkhon,PuchâÅn,bucheonsi,fu chuan shi,ÐÑÑÑÐ¾Ð½,å¯å·å¸,ë¶ì²ì,PuchâÅn", :latitude => "37.49889", :longitude => "126.78306").save
City.new(:country_id => "124", :name => "Puan", :aliases => "Fuan,Puan,Puan", :latitude => "35.72806", :longitude => "126.73194").save
City.new(:country_id => "124", :name => "Polgyo", :aliases => "Bakkyo-ri,BakkyÅ-ri,Beolgyo,Polgyo,PÅlgyo,ë²êµ,PÅlgyo", :latitude => "34.84494", :longitude => "127.34293").save
City.new(:country_id => "124", :name => "P'ohang", :aliases => "Geijitsu,Hoko,Hoko-do,HokÅ-dÅ,P'ohang,P'ohang-dong,Pâohang,Pâohang-dong,Pâohang", :latitude => "36.03222", :longitude => "129.365").save
City.new(:country_id => "124", :name => "Osan", :aliases => "Osan,Osan-ni,Usan-ri,ì¤ì°,Osan", :latitude => "37.15222", :longitude => "127.07056").save
City.new(:country_id => "124", :name => "Asan", :aliases => "Asan,Asan-si,Onyang,Onyo,OnyÅ,asansi,ya shan shi,ÐÑÐ°Ð½,ÐÑÐ°Ð½-ÑÐ¸,çå±±å¸,ìì°,ìì°ì,ï¿½Â·,Asan", :latitude => "36.78361", :longitude => "127.00417").save
City.new(:country_id => "124", :name => "ogcheongun", :aliases => "Kumgu-ri,ogcheon,ogcheongun,ì¥ì²,ì¥ì²êµ°,ì¥ì²êµ°", :latitude => "36.3012", :longitude => "127.568").save
City.new(:country_id => "124", :name => "Kosong", :aliases => "Kosong,goseong,goseong-gun,ê³ ì±,ê³ ì±êµ°,Kosong", :latitude => "38.37881", :longitude => "128.4676").save
City.new(:country_id => "124", :name => "Nonsan", :aliases => "Nonsan,Ronsan,Ronzan,lun shan shi,nonsansi,ÐÐ¾Ð½ÑÐ°Ð½,è«å±±å¸,ë¼ì°ì,Nonsan", :latitude => "36.20389", :longitude => "127.08472").save
City.new(:country_id => "124", :name => "Namwon", :aliases => "Mangen,Namvon,Namweon,Namwon,Namwun,NamwÅn,NamwÅ­n,Nangen,ÐÐ°Ð¼Ð²Ð¾Ð½,NamwÅn", :latitude => "35.41", :longitude => "127.38583").save
City.new(:country_id => "124", :name => "Naju", :aliases => "Nadzhu,Naju,Rashu,RashÅ«,ÐÐ°Ð´Ð¶Ñ,Naju", :latitude => "35.02833", :longitude => "126.7175").save
City.new(:country_id => "124", :name => "Munsan", :aliases => "Munsan,Munsan-ni,ÐÑÐ½ÑÐ°Ð½,Munsan", :latitude => "37.85944", :longitude => "126.785").save
City.new(:country_id => "124", :name => "Mungyeong", :aliases => "Bunke-gun,Bunkei-gun,BunkÄ-gun,Mun'gyong-gun,Mun'gyÅng-gun,Mungyeong gun,Munkyong-Mining Region,mungyeong,mungyeongsi,ë¬¸ê²½,ë¬¸ê²½ì,Mungyeong", :latitude => "36.59458", :longitude => "128.19946").save
City.new(:country_id => "124", :name => "Mokp'o", :aliases => "Mogpkho,Mogpo,Mok-pho,Mokp'o,Mokpâo,Mokuho,Moppo,ÐÐ¾Ð³Ð¿ÑÐ¾,Mokpâo", :latitude => "34.79361", :longitude => "126.38861").save
City.new(:country_id => "124", :name => "Miryang", :aliases => "Milyang,Mirjan,Miryang,Mitsuyo,MitsuyÅ,ÐÐ¸ÑÑÐ½,Miryang", :latitude => "35.49333", :longitude => "128.74889").save
City.new(:country_id => "124", :name => "Masan", :aliases => "Basan,Basen,Bazan,Bazanpo,Ma-sam-pho,Ma-san-p-ho,Mansan,Masampo,Masan,Masan-si,Masanpo,ma shan shi,masansi,ÐÐ°ÑÐ°Ð½,ÐÐ°ÑÐ°Ð½-ÑÐ¸,é¦¬å±±å¸,é©¬å±±å¸,ë§ì°ì,Masan", :latitude => "35.20806", :longitude => "128.5725").save
City.new(:country_id => "124", :name => "Kyongsan", :aliases => "Gyeongsan,Keigan,Keisan,Keizan,Kjonsan,Kyongsan,KyÅngsan,gyeongsansi,ÐÑÐ½ÑÐ°Ð½,ê²½ì°ì,KyÅngsan", :latitude => "35.82333", :longitude => "128.73778").save
City.new(:country_id => "124", :name => "Kyongju", :aliases => "Gyeongju,Keishu,KeishÅ«,Keisyu,KeisyÅ«,Kjondzhu,Kjong-dschu,KjÃ¶ng-dschu,Kyeng-chu,Kyeng-ju,Kyong-choo,Kyongju,Kyonju,KyÅngju,gyeongjusi,qing zhou,qing zhou shi,ÐÑÐ½Ð´Ð¶Ñ,æ¶å·,æ¶å·å¸,ê²½ì£¼ì,KyÅngju", :latitude => "35.84278", :longitude => "129.21167").save
City.new(:country_id => "124", :name => "Kwangyang", :aliases => "Gwang-yang,Koyo,Kuwagyan,Kwangyang,KÅyÅ,Kwangyang", :latitude => "34.97528", :longitude => "127.58917").save
City.new(:country_id => "124", :name => "Kwangju", :aliases => "Gwangju,Kwangju,ê´ì£¼,Kwangju", :latitude => "37.41", :longitude => "127.25722").save
City.new(:country_id => "124", :name => "Kwangju", :aliases => "Gwangju,Koshu,Kosyu,Kuangju,Kvandzhu,Kwang-choo,Kwang-dschu,Kwangju,KÅshÅ«,KÅsyÅ«,guang zhou,guang zhou guang yu shi,gwangjugwang-yeogsi,ÐÐ²Ð°Ð½Ð´Ð¶Ñ,åå·,åå·åºåå¸,åå·å»£åå¸,ê´ì£¼ê´ì­ì,Kwangju", :latitude => "35.15472", :longitude => "126.91556").save
City.new(:country_id => "124", :name => "Kurye", :aliases => "Kurye,Kyurei,KyÅ«rei,gulye,gulyegun,êµ¬ë¡,êµ¬ë¡êµ°,Kurye", :latitude => "35.20944", :longitude => "127.46444").save
City.new(:country_id => "124", :name => "Kuri", :aliases => "Kuri,Kuri-shi,êµ¬ë¦¬,Kuri", :latitude => "37.5986", :longitude => "127.1394").save
City.new(:country_id => "124", :name => "Kunwi", :aliases => "Guni,Kunwi,gun-wi,gun-wigun,êµ°ì,êµ°ìêµ°,Kunwi", :latitude => "36.23472", :longitude => "128.57278").save
City.new(:country_id => "124", :name => "Kunsan", :aliases => "Gunsan,Gunzan,Kunsan,Kunzan,gunsansi,qun shan shi,ÐÑÐ½ÑÐ°Ð½,ç¾¤å±±å¸,êµ°ì°ì,Kunsan", :latitude => "35.97861", :longitude => "126.71139").save
City.new(:country_id => "124", :name => "Kumsan", :aliases => "Kinsan,Kinzan,Kumsan,Kumzan,KÅ­msan,KÅ­mzan,ê¸ì°,KÅ­msan", :latitude => "36.10306", :longitude => "127.48889").save
City.new(:country_id => "124", :name => "Kumi", :aliases => "Kibi,Kumi,Kwimi,ÐÑÐ¼Ð¸,êµ¬ë¯¸,Kumi", :latitude => "36.1136", :longitude => "128.336").save
City.new(:country_id => "124", :name => "Goyang", :aliases => "Goyang,Koyang,Koyang-ni,Koyo,KÅyÅ,goyang,goyangsi,ê³ ì,ê³ ìì,Goyang", :latitude => "37.65639", :longitude => "126.835").save
City.new(:country_id => "124", :name => "Kosong", :aliases => "Goseong,Kojo,KojÅ,Koson,Kosong,KosÅng,Kozyo,KozyÅ,ÐÐ¾ÑÐ¾Ð½,ê³ ì±,KosÅng", :latitude => "34.97631", :longitude => "128.32361").save
City.new(:country_id => "124", :name => "Kongju", :aliases => "Gongju,Kochu,Kondzhu,Kong Tjou,Kong-dschu,Kongju,Koshu,Kosyu,KÅshÅ«,KÅsyÅ«,gong zhou,gong zhou shi,gongjusi,kondzhu-si,ÐÐ¾Ð½Ð´Ð¶Ñ,ÐÐ¾Ð½Ð´Ð¶Ñ-ÑÐ¸,å¬å·,å¬å·å¸,ê³µì£¼,ê³µì£¼ì,Kongju", :latitude => "36.45556", :longitude => "127.12472").save
City.new(:country_id => "124", :name => "Koje", :aliases => "Koje,Kyosai,KÅje,KÅje", :latitude => "34.85028", :longitude => "128.58861").save
City.new(:country_id => "124", :name => "Koesan", :aliases => "Goesan,Kaesong,Kaisan,Kaizan,Koesan,Kwaesan,Kwaizan,goesan,goesangun,ê´´ì°,ê´´ì°êµ°,Koesan", :latitude => "36.81083", :longitude => "127.79472").save
City.new(:country_id => "124", :name => "Koch'ang", :aliases => "Kosho,KÅshÅ,gochang,gochang-gun,ê³ ì°½,ê³ ì°½êµ°,Koch'ang", :latitude => "35.43333", :longitude => "126.7").save
City.new(:country_id => "124", :name => "Kimje", :aliases => "Kimje,Kintei,Kum,Kumje,KÅ­mje,Kimje", :latitude => "35.80167", :longitude => "126.88889").save
City.new(:country_id => "124", :name => "Kimhae", :aliases => "Kimhae,Kinkai,Kumhae,KÅ­mhae,Kimhae", :latitude => "35.23417", :longitude => "128.88111").save
City.new(:country_id => "124", :name => "Gimcheon", :aliases => "Gimcheon,Kimch'on-si,Kimch'Ån-si,Kumch'on-si,KÅ­mch'Ån-si,gim cheonsi,gimcheon,ê¹ ì²ì,ê¹ì²,Gimcheon", :latitude => "36.12176", :longitude => "128.11981").save
City.new(:country_id => "124", :name => "Kijang", :aliases => "Kichang,Kicho,KichÅ,Kijang,Kijang", :latitude => "35.24417", :longitude => "129.21389").save
City.new(:country_id => "124", :name => "Gapyeong", :aliases => "Gapyeong gun,Kahei-gun,Kap'yong-gun,Kap'yÅng-gun,gapyeong,gapyeong-gun,ê°í,ê°íêµ°,Gapyeong", :latitude => "37.83101", :longitude => "127.51059").save
City.new(:country_id => "124", :name => "Kangnung", :aliases => "Gangneung,Gangreung,Kaguun,Kang-neung,Kangnung,KangnÅ­ng,Kannyn,Koryo,KÅryÅ,gangleungsi,jiang ling shi,ÐÐ°Ð½Ð½ÑÐ½,æ±éµå¸,ê°ë¦ì,KangnÅ­ng", :latitude => "37.75556", :longitude => "128.89611").save
City.new(:country_id => "124", :name => "Kanghwa", :aliases => "Ganghwa,Kanghwa,Kanguhaa,Koka,Kokwa,KÅka,ganghwa,ê°í,Kanghwa", :latitude => "37.74722", :longitude => "126.48556").save
City.new(:country_id => "124", :name => "Iksan", :aliases => "Iksan,Iri,Riri,ÐÐºÑÐ°Ð½,Iksan", :latitude => "35.94389", :longitude => "126.95444").save
City.new(:country_id => "124", :name => "Inch'on", :aliases => "Chemulpho,Chemulpo,Choimulpo,Inch'on,Inch'Ån,Incheon,Inchkhon,Inchon,InchâÅn,Incona,InÄona,Jen-tchoan,Jinsen,Nhan Xuyen,NhÃ¢n XuyÃªn,Tchemoulpo,Tjyei-moul-hpo,Tsche-mul-p-ho,incheongwang-yeogsi,ren chuan,ren chuan guang yu shi,Ä°ncheon,ÐÐ½ÑÐ¾Ð½,ÐÐ½ÑÑÐ¾Ð½,ä»å·,ä»å·åºåå¸,ì¸ì²ê´ì­ì,InchâÅn", :latitude => "37.45361", :longitude => "126.73167").save
City.new(:country_id => "124", :name => "Imsil", :aliases => "Imsil,Ninjitsu,imsil,imsilgun,ìì¤,ìì¤êµ°,Imsil", :latitude => "35.61306", :longitude => "127.27944").save
City.new(:country_id => "124", :name => "Ich'on", :aliases => "Ich'on,Ich'Ån,Icheon,Risen,icheon,ì´ì²,Ich'Ån", :latitude => "37.27917", :longitude => "127.4425").save
City.new(:country_id => "124", :name => "Hwasun", :aliases => "Hwansun,Hwason,Hwasun,Khvasun,Wajun,Ð¥Ð²Ð°ÑÑÐ½,Hwasun", :latitude => "35.05944", :longitude => "126.985").save
City.new(:country_id => "124", :name => "Hwaseong", :aliases => "Hwaseong gun,Hwasong-gun,HwasÅng-gun,Suigen,Suwon-gun,SuwÅn-gun,Whasung-Gun,hwaseong,hwaseongsi,íì±,íì±ì,Hwaseong", :latitude => "37.20682", :longitude => "126.8169").save
City.new(:country_id => "124", :name => "Hwacheon", :aliases => "Huachon,Hwach'on,Hwach'Ån,Hwacheon,Kasen,hwacheon,hwacheongun,íì²,íì²êµ°,Hwacheon", :latitude => "38.10611", :longitude => "127.70667").save
City.new(:country_id => "124", :name => "Hongsong", :aliases => "Hongsong,Hongsung,HongsÅng,Kojo,KÅjÅ,íì±,HongsÅng", :latitude => "36.6009", :longitude => "126.665").save
City.new(:country_id => "124", :name => "Hongch'on", :aliases => "Hongch'on,HongchâÅn,Kosen,KÅsen,hongcheon,hongcheongun,íì²,íì²êµ°,HongchâÅn", :latitude => "37.6918", :longitude => "127.8857").save
City.new(:country_id => "124", :name => "Hayang", :aliases => "Hayang,Kayo,KayÅ,Hayang", :latitude => "35.91333", :longitude => "128.82").save
City.new(:country_id => "124", :name => "Haenam", :aliases => "Haenam,Kainan,haenam,í´ë¨,Haenam", :latitude => "34.57111", :longitude => "126.59889").save
City.new(:country_id => "124", :name => "Ch'unch'on", :aliases => "Ch'unch'on,Chhun-chhen,Chkhunchkhon,Chuncheon,ChâunchâÅn,Shunsen,Shusen,Syunsen,Tsch-hun-tsch-hon,Tsch-hun-tsch-hÅn,chun chuan shi,chuncheonsi,Ð§ÑÑÐ½ÑÑÐ¾Ð½,æ¥å·å¸,ì¶ì²ì,ChâunchâÅn", :latitude => "37.87472", :longitude => "127.73417").save
City.new(:country_id => "124", :name => "Chonju", :aliases => "Chenju,Chondzhu,Chongju,Chonju,Chunju,ChÅngju,ChÅnju,Jenchu,Jeonju,Tjyen-tjyou,Tschon-dschu,TschÃ¶n-dschu,Tsiuentcheou,Tyondyu,TyondyÅ«,jeonjusi,quan zhou,quan zhou shi,Ð§Ð¾Ð½Ð´Ð¶Ñ,å¨å·,å¨å·å¸,ì ì£¼,ì ì£¼ì,ChÅnju", :latitude => "35.82194", :longitude => "127.14889").save
City.new(:country_id => "124", :name => "Cheongsong gun", :aliases => "Ch'ongsong-gun,Ch'Ångsong-gun,Cheongsong gun,Seisho,Seisho-gun,SeishÅ,SeishÅ-gun,cheongsong,cheongsong-eub,cheongsong-gun,ì²­ì¡,ì²­ì¡êµ°,ì²­ì¡ì,Cheongsong gun", :latitude => "36.43351", :longitude => "129.057").save
City.new(:country_id => "124", :name => "Ch'ongju", :aliases => "Ch'ongju,Ch'ungju,Cheng-ju,Cheongju,Cheonju,Chkhundzhu,Chungju,ChâÅngju,Seishu,SeishÅ«,Seisyu,SeisyÅ«,Tschong-dschu,TschÃ¶ng-dschu,Tyundyu,chungjusi,zhong zhou shi,Ð§ÑÑÐ½Ð´Ð¶Ñ,å¿ å·å¸,ì¶©ì£¼ì,ChâÅngju", :latitude => "36.63722", :longitude => "127.48972").save
City.new(:country_id => "124", :name => "Ch'onan", :aliases => "Ch'onan,Cheonan,Chkhonan,Chkhonan-si,ChâÅnan,Tenan,Thyen-an,Thyen-Än,cheon-ansi,tian an shi,Ð§ÑÐ¾Ð½Ð°Ð½,Ð§ÑÐ¾Ð½Ð°Ð½-ÑÐ¸,å¤©å®å¸,ì²ì,ì²ìì,ChâÅnan", :latitude => "36.8065", :longitude => "127.1522").save
City.new(:country_id => "124", :name => "Chinju", :aliases => "Chindzhu,Chinju,Jinju,Shinshu,ShinshÅ«,Sinsyu,SinsyÅ«,Tschin-dschu,jin zhou,jin zhou shi,jinjusi,Ð§Ð¸Ð½Ð´Ð¶Ñ,æå·,æå·å¸,ì§ì£¼ì,Chinju", :latitude => "35.19278", :longitude => "128.08472").save
City.new(:country_id => "124", :name => "Chinhae", :aliases => "Chinhae,Chinkae,Chinkai,Chinkheh,Jinhae,Tinkai,jinhaesi,zhen hai shi,Ð§Ð¸Ð½ÑÑ,é®æµ·å¸,éæµ·å¸,ì§í´ì,Chinhae", :latitude => "35.14944", :longitude => "128.65972").save
City.new(:country_id => "124", :name => "Chinch'on", :aliases => "Chinchon,Chinsen,Jincheon,jincheon,jincheongun,ì§ì²,ì§ì²êµ°,Chinch'Ån", :latitude => "36.85667", :longitude => "127.44333").save
City.new(:country_id => "124", :name => "jin-angun", :aliases => "jin-an,jin-angun,ì§ì,ì§ìêµ°,ì§ìêµ°", :latitude => "35.79167", :longitude => "127.42528").save
City.new(:country_id => "124", :name => "Cheju", :aliases => "Chedzhu,Cheju,Chu-sung,Chyei Chyu,Jeju,Jeju City,Jeju-si,Kota Jeju,Saishu,SaishÅ«,Saisyu,Saisyu Yu,SaisyÅ«,SaisyÅ« YÅ«,Tsche-dschu,Tse-tsiu,Tsitcheou,jejusi,ji zhou shi,Ð§ÐµÐ´Ð¶Ñ,æ¸å·å¸,ì ì£¼ì,Cheju", :latitude => "33.50972", :longitude => "126.52194").save
City.new(:country_id => "124", :name => "Ch'angwon", :aliases => "Ch'angwon,Ch'angwÅn,Changwon,Chkhanvon,ChâangwÅn,Sangwon,Shogen,ShÅgen,chang yuan,chang yuan shi,chang-wonsi,Ð§ÑÐ°Ð½Ð²Ð¾Ð½,æå,æåå¸,ì°½ìì,ChâangwÅn", :latitude => "35.22806", :longitude => "128.68111").save
City.new(:country_id => "124", :name => "Changsu", :aliases => "Changsu,Changsu-ri,Chosui-ri,ChÅsui-ri,jangsu,jangsugun,ì¥ì,ì¥ìêµ°,Changsu", :latitude => "35.64842", :longitude => "127.51523").save
City.new(:country_id => "124", :name => "Anyang", :aliases => "An'jan,Anyang,Anyang-ni,Anyo,Anyo-ri,AnyÅ,AnyÅ-ri,an yang shi,an-yangsi,ÐÐ½ÑÑÐ½,å®é¤å¸,ìì,ììì,Anyang", :latitude => "37.3925", :longitude => "126.92694").save
City.new(:country_id => "124", :name => "Ansong", :aliases => "Anjo,AnjÅ,Anseong,Anson,Ansong,AnsÅng,an cheng shi,anseong,anseongsi,ÐÐ½ÑÐ¾Ð½,å®åå¸,ìì±,ìì±ì,AnsÅng", :latitude => "37.01083", :longitude => "127.27028").save
City.new(:country_id => "124", :name => "Ansan", :aliases => "Ansan,Ansan-si,Anzan,Onson,an shan shi,ansansi,ÐÐ½ÑÐ°Ð½-ÑÐ¸,ÐÐ½ÑÐ¾Ð½,å®å±±å¸,ìì°ì,Ansan", :latitude => "37.32361", :longitude => "126.82194").save
City.new(:country_id => "124", :name => "Andong", :aliases => "Andang,Andon,Andong,Anto,AntÅ,ÐÐ½Ð´Ð¾Ð½,Andong", :latitude => "36.56556", :longitude => "128.725").save
City.new(:country_id => "124", :name => "Aewol-li", :aliases => "Aewol,Aewol-li,AewÅl,AewÅl-li,Gaigetsu,Gaigetsu-ri,Gaigeturi,AewÅl-li", :latitude => "33.46444", :longitude => "126.31833").save
City.new(:country_id => "124", :name => "Sinhyon", :aliases => "Sinhyeon,Sinhyon,SinhyÅn,SinhyÅn", :latitude => "34.8825", :longitude => "128.62667").save
City.new(:country_id => "124", :name => "Yonmu", :aliases => ",YÅnmu", :latitude => "36.12944", :longitude => "127.1").save
City.new(:country_id => "124", :name => "Tonghae", :aliases => ",Tonghae", :latitude => "37.54389", :longitude => "129.10694").save
City.new(:country_id => "124", :name => "Pubal", :aliases => ",Pubal", :latitude => "37.29167", :longitude => "127.50778").save
City.new(:country_id => "124", :name => "Songnam", :aliases => "Seongnam,Songnam,SÅngnam,ì±ë¨,SÅngnam", :latitude => "37.43861", :longitude => "127.13778").save
City.new(:country_id => "124", :name => "Hanam", :aliases => "Hanam,Hanam", :latitude => "37.54", :longitude => "127.20556").save
City.new(:country_id => "124", :name => "Hwado", :aliases => ",Hwado", :latitude => "37.6525", :longitude => "127.3075").save
City.new(:country_id => "124", :name => "Namyangju", :aliases => "Migum,MigÅ­m,Nam'jandzhu,Namjandzhu,Namyangju,nam-yangjusi,nan yang zhou shi,ÐÐ°Ð¼ÑÑÐ½Ð´Ð¶Ñ,ÐÐ°Ð¼ÑÐ½Ð´Ð¶Ñ,åæ¥å·å¸,ë¨ìì£¼ì,Namyangju", :latitude => "37.63667", :longitude => "127.21417").save
City.new(:country_id => "124", :name => "Ungsang", :aliases => ",Ungsang", :latitude => "35.40611", :longitude => "129.16861").save
City.new(:country_id => "124", :name => "Wabu", :aliases => ",Wabu", :latitude => "37.58972", :longitude => "127.22028").save
City.new(:country_id => "124", :name => "Naeso", :aliases => ",NaesÅ", :latitude => "35.24972", :longitude => "128.52").save
City.new(:country_id => "124", :name => "Hwawon", :aliases => ",HwawÅn", :latitude => "35.80167", :longitude => "128.50083").save
City.new(:country_id => "124", :name => "Kwangmyong", :aliases => ",KwangmyÅng", :latitude => "37.47722", :longitude => "126.86639").save
City.new(:country_id => "124", :name => "Sinan", :aliases => "sin-an,sin-angun,ì ì,ì ìêµ°,Sinan", :latitude => "34.8262", :longitude => "126.10863").save
City.new(:country_id => "124", :name => "Changnyeong", :aliases => "Ch'angnyong,ChâangnyÅng,changnyeong,changnyeong-eub,changnyeong-gun,ì°½ë,ì°½ëêµ°,ì°½ëì,Changnyeong", :latitude => "35.54145", :longitude => "128.49506").save
