City.new(:country_id => "125", :name => "Janub as Surrah", :aliases => "Janub as Surrah,JanÅ«b as Surrah,South Surra,janub aalsurat,Ø¬ÙÙÙÙØ¨ Ø§ÙÙØ³ÙÙØ±ÙÙØ©,JanÅ«b as Surrah", :latitude => "29.26917", :longitude => "47.97806").save
City.new(:country_id => "125", :name => "Bayan", :aliases => "Bajan,Bayan,BayÄn,bayan,ÐÐ°ÑÐ½,Ø¨ÙØ§Ù,Ø¨ÙÙÙØ§Ù,BayÄn", :latitude => "29.3032", :longitude => "48.04881").save
City.new(:country_id => "125", :name => "As Salimiyah", :aliases => "Ad Dumna,Ad Dumnah,As - Salimiyah,As Salimiyah,As SÄlimÄ«yah,As-Salimiyah,As-SÄlimiyah,As-SÌaimiyah,As-SÌÄimiyah,AsÌ - SÄlimiyah,Dimnah,Salimiyah,Salmiya,Salmiyah,Salmiyyeh,aalsaalimiat,Ø§ÙØ³Ø§ÙÙÙØ©,Ø§ÙÙØ³ÙÙØ§ÙÙÙÙÙÙÙØ©,As SÄlimÄ«yah", :latitude => "29.33389", :longitude => "48.07611").save
City.new(:country_id => "125", :name => "Ar Riqqah", :aliases => "Al-Riqqah,Ar Riqqah,Reqqa,aalriqat,Ø§ÙØ±ÙØ©,Ø§ÙÙØ±ÙÙÙÙÙØ©,Ar Riqqah", :latitude => "29.14583", :longitude => "48.09472").save
City.new(:country_id => "125", :name => "Al Manqaf", :aliases => "Al Manjaf,Al Manqaf,Al-Mangaf,Manqaf,aalmanqaf,Ø§ÙÙÙÙÙ,Ø§ÙÙÙÙÙÙÙÙÙÙ,Al Manqaf", :latitude => "29.09611", :longitude => "48.13278").save
City.new(:country_id => "125", :name => "Al Mahbulah", :aliases => "Al Mahbulah,Al MahbÅ«lah,Al-Mahabulah,Al-MahabÅ«lah,Mahboola,aalmahbulat,Ø§ÙÙÙØ¨ÙÙØ©,Ø§ÙÙÙÙÙÙÙØ¨ÙÙÙÙØ©,Al MahbÅ«lah", :latitude => "29.145", :longitude => "48.13028").save
City.new(:country_id => "125", :name => "Kuwait", :aliases => "Al Kuwait,Al Kuwayt,Al-Kuwait,Ciudad de Kuwait,Koeweit,Kota Kuwait,Koveyit,Koweit,KoweÃ¯t,Kuvaeyt,Kuvajt,Kuvajto,Kuvajturbo,Kuveitas,Kuvejt,KuvÃ¤yt,Kuwait,Kuwait City,Kuwait Stad,Kuwait by,Kuwait-Stadt,Kuwait-Urbo,Kuwayt,Kuweit,Kuwejt,Madinat al Kuwayt,Madinat al-Kuwait,MadÄ«nat al Kuwayt,Pole tou Koubeit,aalkuayt,ke wei te shi,khuwet si ti,kuu~eto,kuweiteu si,kwwyt syty,mdynt alkwyt,Î ÏÎ»Î· ÏÎ¿Ï ÎÎ¿ÏÎ²Î­Î¹Ï,ÐÑÐ²ÐµÐ¹Ñ,×××××ª ×¡×××,Ø§ÙÙÙÙÙÙÙÙÙØª,ÙØ¯ÙÙØ© Ø§ÙÙÙÙØª,à¸à¸¹à¹à¸§à¸à¸à¸´à¸à¸µ,ã¯ã¦ã§ã¼ã,ç§å¨ç¹å¸,ì¿ ì¨ì´í¸ ì,Kuwait", :latitude => "29.36972", :longitude => "47.97833").save
City.new(:country_id => "125", :name => "Al Jahra'", :aliases => "Al Jahara,Al Jahra,Al Jahra',Al Jahrah,Al JahrÄâ,Al-Jaharah,Iahara,Jahra Village,Jahrah,Ø§ÙÙÙØ¬ÙÙÙØ±ÙØ§Ø¡,Al JahrÄâ", :latitude => "29.3375", :longitude => "47.65806").save
City.new(:country_id => "125", :name => "Al Fahahil", :aliases => "Al Fahahil,Al Faá¸©Äá¸©Ä«l,Al Fuhaihil,Al Fuhayhil,Al FuÄ§aiÄ§il,Al Fuá¸©ayá¸©Ä«l,Al Ifhaihil,Al-Fahaheel,Al-Fahahil,Fahaheel,Fahahil,Fahaihil,FahaihÄ«l,Fahayhil,FahÄhÄ«l,Faá¸©ayá¸©Ä«l,Fuhayhil,Fuá¸©ayá¸©Ä«l,aalfuhayhil,Ø§ÙÙØ­Ø§Ø­ÙÙ,Ø§ÙÙÙÙÙØ­ÙÙÙØ­ÙÙÙ,Al Faá¸©Äá¸©Ä«l", :latitude => "29.0825", :longitude => "48.13028").save
City.new(:country_id => "125", :name => "Al Fintas", :aliases => "Al Fantas,Al Fintas,Al Fintass,Al FintÄs,Al FinÅ£Äs,Al-FintÌas,Al-FintÌÄs,Fantas,Fantass,FanÅ£Äs,Finatus,Fintas,Fintass,FinÅ£Äs,Funtas,FuntÃ¡s,aalfintas,Ø§ÙÙÙØ·Ø§Ø³,Ø§ÙÙÙÙÙÙÙØ·ÙØ§Ø³,Al FinÅ£Äs", :latitude => "29.17389", :longitude => "48.12111").save
City.new(:country_id => "125", :name => "Al Farwaniyah", :aliases => "Al Farwania,Al Farwaniyah,Al FarwÄnÄ«yah,Al-Farawaniyah,Al-Farwaniyyah,Farwaniah,Farwaniyyeh,aalfarwaniat,Ø§ÙÙÙÙÙØ±ÙÙÙØ§ÙÙÙÙÙØ©,Al FarwÄnÄ«yah", :latitude => "29.2775", :longitude => "47.95861").save
City.new(:country_id => "125", :name => "Ad Dasmah", :aliases => "Ad Dasma',Ad Dasmah,Ad DasmÄâ,Dasma,Dasmah,aaldasmat,Ø§ÙÙØ¯ÙÙØ³ÙÙÙØ©,Ad Dasmah", :latitude => "29.365", :longitude => "48.00139").save
City.new(:country_id => "125", :name => "Salwa", :aliases => "Sal'va,Salwa,SalwÃ¡,salway,Ð¡Ð°Ð»ÑÐ²Ð°,Ø³ÙÙÙ,Ø³ÙÙÙÙÙÙ,SalwÃ¡", :latitude => "29.29583", :longitude => "48.07861").save
City.new(:country_id => "125", :name => "Ar Rabiyah", :aliases => "Ar Rabiyah,Ar RÄbiyah,aalraabiat,Ø§ÙÙØ±ÙÙØ§Ø¨ÙÙÙØ©,Ar RÄbiyah", :latitude => "29.295", :longitude => "47.93306").save
City.new(:country_id => "125", :name => "Sabah as Salim", :aliases => "Sabah as Salim,Sabah as Salim as Sabbah,sabah aalsaalim,ÅabÄá¸© as Salim aÅ SabbÄá¸©,ÅabÄá¸© as SÄlim,ØµÙØ¨ÙØ§Ø­ Ø§ÙÙØ³ÙÙØ§ÙÙÙ,ÅabÄá¸© as SÄlim", :latitude => "29.25722", :longitude => "48.05722").save
