City.new(:country_id => "127", :name => "Oral", :aliases => "Oral,OraÅ,Ural'sk,Uralâsk,awral,jbal alawral,ÐÑÐ°Ð»,Ð£ÑÐ°Ð»ÑÑÐº,Ø£ÙØ±Ø§Ù,Ø¬Ø¨Ø§Ù Ø§ÙØ£ÙØ±Ø§Ù,Oral", :latitude => "51.23333", :longitude => "51.36667").save
City.new(:country_id => "127", :name => "Oktyabr'sk", :aliases => "Kandagach,Kandagash,Kandyagash,OKTJABR'SK,Oktyabr',Oktyabr'sk,Oktyabrâ,Oktyabrâsk,ÐÐÐ¢Ð¯ÐÐ Ð¬Ð¡Ð,Oktyabrâsk", :latitude => "49.47444", :longitude => "57.42333").save
City.new(:country_id => "127", :name => "Qulsary", :aliases => "Kol'sary,Kul'sari,Kul'sary,ÐÑÐ»ÑÑÐ°ÑÑ,Qulsary", :latitude => "46.95307", :longitude => "54.01978").save
City.new(:country_id => "127", :name => "Khromtau", :aliases => "KHROMTAU,Khrom-Tai,Khromtau,KhromtaÅ«,Ð¥Ð ÐÐÐ¢ÐÐ£,Khromtau", :latitude => "50.25028", :longitude => "58.43472").save
City.new(:country_id => "127", :name => "Karagandy", :aliases => "Karaganda,Karagandi,Karagandy,ÐÐ°ÑÐ°Ð³Ð°Ð½Ð´Ñ,Karagandy", :latitude => "50.06667", :longitude => "54.86667").save
City.new(:country_id => "127", :name => "Embi", :aliases => "Amba,EHMBA,Emba,Embi,Ð­ÐÐÐ,Embi", :latitude => "48.82639", :longitude => "58.14417").save
City.new(:country_id => "127", :name => "Balyqshy", :aliases => "BALYKSHI,Balykshi,Balyqshy,Belykshi,ÐÐÐÐ«ÐÐ¨Ð,Balyqshy", :latitude => "47.06667", :longitude => "51.86667").save
City.new(:country_id => "127", :name => "Atyrau", :aliases => "Aterau,Atiraw,Atyrau,Atyraw,AtyraÅ«,AtÄ±raw,Chapayev,Gur'yev,Gurev,Guriev,Gurâyev,atilau,ÐÑÑÑÐ°Ñ,ìí°ë¼ì°,Atyrau", :latitude => "47.11667", :longitude => "51.88333").save
City.new(:country_id => "127", :name => "Aqtobe", :aliases => "AKTJUBINSK,Aktiube,Aktiubinsk,Aktobe,Aktoebe,Aktubinsk,Aktyubinsk,AktÃ¶be,Aqtoebe,AqtÃ¶be,Ukhtiubinskii,agtoebe,aktjubinsk,ÐÐÐ¢Ð®ÐÐÐÐ¡Ð,ÐÐºÑÑÐ±Ð¸Ð½ÑÐº,ÐÒÑÓ©Ð±Ðµ,ìí´ë² ,AqtÃ¶be", :latitude => "50.27969", :longitude => "57.20718").save
City.new(:country_id => "127", :name => "Aktau", :aliases => "Aktaou,Aktau,Aktauskiy,Aqtau,AqtaÅ«,Shevchenko,ÐÐºÑÐ°Ñ,ÐÒÑÐ°Ñ,Aktau", :latitude => "43.65", :longitude => "51.2").save
City.new(:country_id => "127", :name => "Aqsay", :aliases => "AKSAJ,Aksay,Aqsay,Kazakhstan,ÐÐÐ¡ÐÐ,Aqsay", :latitude => "51.16778", :longitude => "52.995").save
City.new(:country_id => "127", :name => "Zyryanovsk", :aliases => "Ziryanovsk,Zyranovsk,Zyranovskoye,Zyrjanovsk,Zyryan,Zyryanovsk,Zyryanovskoye,ÐÑÑÑÐ½Ð¾Ð²ÑÐº,Zyryanovsk", :latitude => "49.73861", :longitude => "84.27194").save
City.new(:country_id => "127", :name => "Zhosaly", :aliases => "Dzhusaly,Jusaly,Karmakchi,Zhosaly,Zhusaly,ÐÐ¶ÑÑÐ°Ð»Ñ,Zhosaly", :latitude => "45.48778", :longitude => "64.07806").save
City.new(:country_id => "127", :name => "Zhezqazghan", :aliases => "Bol'shoy Dzhezkazgan,Bolâshoy Dzhezkazgan,Dzhezkazgan,Schesqasghan,Zhezkazgan,Zhezqazghan,ÐÐ¶ÐµÐ·ÐºÐ°Ð·Ð³Ð°Ð½,Zhezqazghan", :latitude => "47.78333", :longitude => "67.76667").save
City.new(:country_id => "127", :name => "Zhetiqara", :aliases => "DZHETYGARA,Dzhetygara,Dzhetygora,Dzhetygorinskiy Sovkhoz,Jetygara,Zhetiqara,Zhitikara,ÐÐÐÐ¢Ð«ÐÐÐ Ð,Zhetiqara", :latitude => "52.19083", :longitude => "61.20056").save
City.new(:country_id => "127", :name => "Zhangatas", :aliases => "Dzhanatas,Dzhanytas,Zhanatas,Zhangatas,Zhangatas", :latitude => "43.56667", :longitude => "69.75").save
City.new(:country_id => "127", :name => "Ayteke Bi", :aliases => "Ayteke Bi,Novokazalinsk,Zhangaqazaly,Ãyteke BÄ«,Ayteke Bi", :latitude => "45.85361", :longitude => "62.15611").save
City.new(:country_id => "127", :name => "Taraz", :aliases => "Auliye-Ata,Dzhambul,Jambul,Talas,Taras,Taraz,Zhambyl,Zhambyl oblysy,ÐÐ°Ð¼Ð±ÑÐ» Ð¾Ð±Ð»ÑÑÑ,Ð¢Ð°ÑÐ°Ð·,Taraz", :latitude => "42.9", :longitude => "71.36667").save
City.new(:country_id => "127", :name => "Zaysan", :aliases => "Zaisan,Zaysan,Zaysan", :latitude => "47.46667", :longitude => "84.86667").save
City.new(:country_id => "127", :name => "Zhangaqorghan", :aliases => "Yani-Kurgan,Yany-Kurian,Yanykurgan,Zhanakorgan,Zhangaqorghan,Zhangaqorghan", :latitude => "43.915", :longitude => "67.24806").save
City.new(:country_id => "127", :name => "Turar Ryskulov", :aliases => "Turar Ryskulov,Vannovka,Vannovskoye,Turar Ryskulov", :latitude => "42.53333", :longitude => "70.33333").save
City.new(:country_id => "127", :name => "Ush-Tyube", :aliases => "Ush-Tyube,Ushtobe,ÃshtÃ¶be,Ð£ÑÑÐ¾Ð±Ðµ,Ush-Tyube", :latitude => "45.24222", :longitude => "77.98222").save
City.new(:country_id => "127", :name => "Turkestan", :aliases => "Turkestan,Turkistan,TÃ¼rkistan,Ð¢ÑÑÐºÐµÑÑÐ°Ð½,Turkestan", :latitude => "43.33333", :longitude => "68.25").save
City.new(:country_id => "127", :name => "Temirtau", :aliases => "Samarand,Samarka,Samarkand,Samarkandskoye,Temirtau,TemirtaÅ«,Ð¢ÐµÐ¼Ð¸ÑÑÐ°Ñ,Temirtau", :latitude => "50.05444", :longitude => "72.94833").save
City.new(:country_id => "127", :name => "Tekeli", :aliases => "Tekeli,Tekely,Ð¢ÐµÐºÐµÐ»Ð¸,Tekeli", :latitude => "44.83", :longitude => "78.82389").save
City.new(:country_id => "127", :name => "Tasboget", :aliases => "Tasboget,Tasbuget,TasbÃ¶get,TasbÃ¶get", :latitude => "44.77278", :longitude => "65.5525").save
City.new(:country_id => "127", :name => "Talghar", :aliases => "Talgar,Talghar,Talghar", :latitude => "43.30444", :longitude => "77.23278").save
City.new(:country_id => "127", :name => "Taldyqorghan", :aliases => "Gavrilovka,Gavrilovskoye,Taldi Kurgan,Taldikorgan,Taldy Kurgan,Taldy-Kurgan,Taldykorgan,Taldyqorghan,Talto-Kurgan,TaltÃ¶-Kurgan,TaÅdy Kurgan,Ð¢Ð°Ð»Ð´Ð¸ÐºÐ¾ÑÐ³Ð°Ð½,Taldyqorghan", :latitude => "45.01556", :longitude => "78.37389").save
City.new(:country_id => "127", :name => "Taldyqorghan", :aliases => "Taldy - Kurgan,Taldy-Kurgan Stantsiya,Taldykurgan,Taldyqorghan,Ð¢Ð°Ð»Ð´Ñ - ÐÑÑÐ³Ð°Ð½,Taldyqorghan", :latitude => "45", :longitude => "77.91667").save
City.new(:country_id => "127", :name => "Shymkent", :aliases => "Chimkent,Chymkent,Schymkent,Shymkent,Sjymkent,Somkent,Szymkient,z'ymqnt,Å Ãµmkent,Ð§Ð¸Ð¼ÐºÐµÐ½Ñ,Ð¨ÑÐ¼ÐºÐµÐ½Ñ,×¦'×××§× ×,Shymkent", :latitude => "42.3", :longitude => "69.6").save
City.new(:country_id => "127", :name => "Shu", :aliases => "Chu,Shu,ShÅ«,Ð¨Ñ,Shu", :latitude => "43.59833", :longitude => "73.76139").save
City.new(:country_id => "127", :name => "Shemonaikha", :aliases => "SHEMONAIKHA,Shemonaikha,ShemonaÄ«kha,Ð¨ÐÐÐÐÐÐÐ¥Ð,ShemonaÄ«kha", :latitude => "50.63278", :longitude => "81.90556").save
City.new(:country_id => "127", :name => "Shchuchinsk", :aliases => "SHHUCHINSK,Shchuch'ye,Shchuchinsk,Shchuchâye,ShchÅ«chÄ«nsk,Ð©Ð£Ð§ÐÐÐ¡Ð,ShchÅ«chÄ«nsk", :latitude => "52.93333", :longitude => "70.2").save
City.new(:country_id => "127", :name => "Semey", :aliases => "SEMIPALATINSK,Semei,Semej,Semey,SemeÃ¯,Semipalatins'k,Semipalatinsk,Semipalatynsk,SemipaÅatyÅsk,Ð¡ÐÐÐÐÐÐÐÐ¢ÐÐÐ¡Ð,Ð¡ÐµÐ¼ÐµÐ¹,Ð¡ÐµÐ¼Ð¸Ð¿Ð°Ð»Ð°ÑÐ¸Ð½ÑÐº,Ð¡ÐµÐ¼Ð¸Ð¿Ð°Ð»Ð°ÑÐ¸Ð½ÑÑÐº,Semey", :latitude => "50.41111", :longitude => "80.2275").save
City.new(:country_id => "127", :name => "Saryaghash", :aliases => "Saryagach,Saryagash,Saryaghash,Ssary-Agatsch,Ð¡Ð°ÑÑÐ°Ð³Ð°Ñ,Saryaghash", :latitude => "41.45", :longitude => "69.16667").save
City.new(:country_id => "127", :name => "Sarkand", :aliases => "Sarkand,Sarkanskaya,Sarqan,Sarqant,Ð¡Ð°ÑÐºÐ°Ð½Ð´,Sarkand", :latitude => "45.41", :longitude => "79.91861").save
City.new(:country_id => "127", :name => "Sorang", :aliases => "Saran',Saranâ,Sorang,Ð¡Ð°ÑÐ°Ð½Ñ,Sorang", :latitude => "49.78", :longitude => "72.85056").save
City.new(:country_id => "127", :name => "Rudnyy", :aliases => "Rudnyj,Rudnyy,RÅ«dnyy,Ð ÑÐ´Ð½ÑÐ¹,Rudnyy", :latitude => "52.95944", :longitude => "63.12056").save
City.new(:country_id => "127", :name => "Qyzylorda", :aliases => "Ak-Mechet',Ak-Mechetâ,Kyzylorda,Kzyl-Orda,Perovsk,Qyzylorda,ÐÑÐ·ÑÐ»Ð¾ÑÐ´Ð°,Qyzylorda", :latitude => "44.85278", :longitude => "65.50917").save
City.new(:country_id => "127", :name => "Qostanay", :aliases => "Kostanaj,Kostanay,Kustanai,Kustanaisk,Kustanaj,Kustanay,Qostanay,ÐÐ¾ÑÑÐ°Ð½Ð°Ð¹,ÐÑÑÑÐ°Ð½Ð°Ð¹,Qostanay", :latitude => "53.16667", :longitude => "63.58333").save
City.new(:country_id => "127", :name => "Karatau", :aliases => "Chulak-Tau,Karatau,Qaratau,QarataÅ«,Karatau", :latitude => "43.16667", :longitude => "70.46667").save
City.new(:country_id => "127", :name => "Qaraghandy", :aliases => "Karaganda,Karagandinskiye Kopi,Karagando,KaragandÃµ,Qaragandi,Qaraghandy,QaraÄandÄ±,ÐÐ°ÑÐ°Ð³Ð°Ð½Ð´Ð°,ÒÐ°ÑÐ°ÒÐ°Ð½Ð´Ñ,Qaraghandy", :latitude => "49.79889", :longitude => "73.09944").save
City.new(:country_id => "127", :name => "Qapshaghay", :aliases => "Ili,Iliisk,Ilijek,Iliysk,Iliyskoye,Kapchagai,Kapchagaj,Kapchagay,Qapshaghay,ÐÐ°Ð¿ÑÐ°Ð³Ð°Ð¹,Qapshaghay", :latitude => "43.88333", :longitude => "77.08333").save
City.new(:country_id => "127", :name => "Petropavlovsk", :aliases => "PETROPAVLOVSK,Petropavl,Petropavlovsk,Petropawl,Petropawlowsk,PetropawÅ,PetropawÅowsk,ÐÐÐ¢Ð ÐÐÐÐÐÐÐÐ¡Ð,ÐÐµÑÑÐ¾Ð¿Ð°Ð²Ð»,ÐÐµÑÑÐ¾Ð¿Ð°Ð²Ð»Ð¾Ð²ÑÐº,Petropavlovsk", :latitude => "54.87528", :longitude => "69.16278").save
City.new(:country_id => "127", :name => "Pavlodar", :aliases => "Kereku,KerekÅ«,PAVLODAR,Pavlodar,Pawlodar,PawÅodar,pabeullodaleu,pavurodaru,pblwdr,ÐÐÐÐÐÐÐÐ ,ÐÐ°Ð²Ð»Ð¾Ð´Ð°Ñ,×¤×××××¨,ãã´ã­ãã«,íë¸ë¡ë¤ë¥´,Pavlodar", :latitude => "52.3", :longitude => "76.95").save
City.new(:country_id => "127", :name => "Zharkent", :aliases => "Djarkent,Dzharkent,Jarkent,Panfilov,PanfÄ«lov,Zharkent,ÐÐ°ÑÐºÐµÐ½Ñ,Zharkent", :latitude => "44.16278", :longitude => "80").save
City.new(:country_id => "127", :name => "Ust'-Kamenogorsk", :aliases => "OEskemen,Oskemen,UST'-KAMENOGORSK,Ust'-Kamenogorsk,Ust-Kamienogorsk,Ustâ-Kamenogorsk,oeseukemen,Ãskemen,Ð£Ð¡Ð¢Ð¬-ÐÐÐÐÐÐÐÐÐ Ð¡Ð,Ð£ÑÑÑ-ÐÐ°Ð¼ÐµÐ½Ð¾Ð³Ð¾ÑÑÐº,ã¦ã¹ãã»ã«ã¡ãã´ã«ã¹ã¯,ì¸ì¤ì¼ë©,Ustâ-Kamenogorsk", :latitude => "49.97889", :longitude => "82.61028").save
City.new(:country_id => "127", :name => "Sarykemer", :aliases => "Mikhaylovka,Sarykamar,Sarykemer,Sarykemer", :latitude => "43", :longitude => "71.5").save
City.new(:country_id => "127", :name => "Merke", :aliases => ",Merke", :latitude => "42.87278", :longitude => "73.17861").save
City.new(:country_id => "127", :name => "Makinsk", :aliases => "MAKINSK,Makinsk,MakÄ«nsk,ÐÐÐÐÐÐ¡Ð,MakÄ«nsk", :latitude => "52.62917", :longitude => "70.41694").save
City.new(:country_id => "127", :name => "Lisakovsk", :aliases => "Lisakovka,Lisakovsk,LÄ«sakovsk,ÐÐ¸ÑÐ°ÐºÐ¾Ð²ÐºÐ°,Lisakovsk", :latitude => "52.53694", :longitude => "62.49361").save
City.new(:country_id => "127", :name => "Baykonyr", :aliases => "Baikonur,Bajkonur,Baykonur,Bayqongyr,Leninsk,Leninskiy,Tyuratam,Zarya,ÐÐ°Ð¹ÐºÐ¾Ð½ÑÑ,ÐÐµÐ½Ð¸Ð½ÑÐº,Baykonyr", :latitude => "45.61667", :longitude => "63.31667").save
City.new(:country_id => "127", :name => "Ridder", :aliases => "LENINOGORSK,Leninogor,Leninogorsk,LenÄ«nogor,LenÄ«nogorsk,Ridder,Ridderskiy,ÐÐÐÐÐÐÐÐÐ Ð¡Ð,Ridder", :latitude => "50.355", :longitude => "83.51333").save
City.new(:country_id => "127", :name => "Lenger", :aliases => "Kopi-Lenger,Lenger,Lenger-Ugol',Lenger-Ugolâ,Lengerskaya,Lengerskij,Lengerskiy,ÐÐµÐ½Ð³ÐµÑ,Lenger", :latitude => "42.2", :longitude => "69.9").save
City.new(:country_id => "127", :name => "Kokshetau", :aliases => "KOKCHETAV,Kochetayev,Koekshetau,Kokchetar,Kokchetau,Kokchetav,Kokshetau,Koshetau,KÃ¶kshetaÅ«,KÃ¶shetaÅ«,ÐÐÐÐ§ÐÐ¢ÐÐ,Kokshetau", :latitude => "53.2775", :longitude => "69.38833").save
City.new(:country_id => "127", :name => "Kentau", :aliases => "Kentau,KentaÅ«,ÐÐµÐ½ÑÐ°Ñ,KentaÅ«", :latitude => "43.52194", :longitude => "68.51083").save
City.new(:country_id => "127", :name => "Esik", :aliases => "Esik,Issok,Issyk,IssÃ¶k,Yesik,ÐÑÐ¸Ðº,ÐÑÑÑÐº,Esik", :latitude => "43.3552", :longitude => "77.45245").save
City.new(:country_id => "127", :name => "Georgievka", :aliases => "Georgievka,Georgievskaya,Georgiyevka,GeorgÄ«evka,ÐÐµÐ¾ÑÐ³Ð¸ÐµÐ²ÐºÐ°,GeorgÄ«evka", :latitude => "49.33139", :longitude => "81.57611").save
City.new(:country_id => "127", :name => "Aqsu", :aliases => "AKSU,Aksu,Aqsu,AqsÅ«,ERMAK,Ermak,Yermak,ÐÐÐ¡Ð£,ÐÐ ÐÐÐ,AqsÅ«", :latitude => "52.03333", :longitude => "76.91667").save
City.new(:country_id => "127", :name => "Energeticheskiy", :aliases => "Energeticheskiy,EnergetÄ«cheskÄ«y,Znergeticheskiy,Energeticheskiy", :latitude => "43.42778", :longitude => "77.02222").save
City.new(:country_id => "127", :name => "Ekibastuz", :aliases => "Ehkibastuz,Ekibastuz,Ekibastuzugol',Ekibastuzugolâ,Energograd,Ð­ÐºÐ¸Ð±Ð°ÑÑÑÐ·,Ekibastuz", :latitude => "51.66667", :longitude => "75.36667").save
City.new(:country_id => "127", :name => "Shieli", :aliases => "Chiili,Shieli,ShÄ«eli,Ð¨Ð¸ÐµÐ»Ð¸,ShÄ«eli", :latitude => "44.16667", :longitude => "66.75").save
City.new(:country_id => "127", :name => "Shardara", :aliases => "Chardara,Shardara,Syrdar'inskiy,Syrdarâinskiy,Ð¨Ð°ÑÐ´Ð°ÑÐ°,Shardara", :latitude => "41.25472", :longitude => "67.96917").save
City.new(:country_id => "127", :name => "Burunday", :aliases => "Baranday,Boralday,Burundaj,Burunday,ÐÑÑÑÐ½Ð´Ð°Ð¹,Burunday", :latitude => "43.36028", :longitude => "76.85778").save
City.new(:country_id => "127", :name => "Aksu", :aliases => "Aksu,Belye Vody,Belyye Vody,ÐÐºÑÑ,Aksu", :latitude => "42.41667", :longitude => "69.83333").save
City.new(:country_id => "127", :name => "Balqash", :aliases => "Balkhash,Balqash,Pribalkhash,Pribalkhashstroy,ÐÐ°Ð»ÑÐ°Ñ,Balqash", :latitude => "46.84806", :longitude => "74.995").save
City.new(:country_id => "127", :name => "Ayagoz", :aliases => "Ayagoz,Ayaguz,Ayakoz,AyakÃ¶z,Sergiopol',Sergiopolâ,Ayagoz", :latitude => "47.97139", :longitude => "80.43917").save
City.new(:country_id => "127", :name => "Atbasar", :aliases => "Atbasa,Atbasar,ÐÑÐ±Ð°ÑÐ°Ñ,Atbasar", :latitude => "51.8", :longitude => "68.33333").save
City.new(:country_id => "127", :name => "Arys", :aliases => "Arys,Arys',Arysâ,Arys", :latitude => "42.43333", :longitude => "68.8").save
City.new(:country_id => "127", :name => "Arkalyk", :aliases => "Arkalyk,Arqalyk,Arqalyq,Arkalyk", :latitude => "50.24861", :longitude => "66.91139").save
City.new(:country_id => "127", :name => "Aral", :aliases => "Aral,Aral Sea,Aral'sk,Aral'skoe,Aral'skoye More,Aralâsk,Aralâskoye More,ÐÑÐ°Ð»ÑÑÐºÐ¾Ðµ,Aral", :latitude => "46.8", :longitude => "61.66667").save
City.new(:country_id => "127", :name => "Astana", :aliases => "Akmola,Akmolinsk,Aqmola,Astana,Astano,AstanÃ ,AstanÃ¡,Asztana,AÏÏÎ¬Î½Î±,Ostona,Qaraotkel,QaraÃ¶tkel,Tselinograd,a si ta na,aseutana,astana,astanh,asutana,ÐÑÑÐ°Ð½Ð°,ÐÑÑÐ¾Ð½Ð°,Ô±Õ½Õ¿Õ¡Õ¶Õ¡,××¡×× ×,Ø¢Ø³ØªØ§ÙÙ,Ø£Ø³Ø·Ø§ÙØ§,à¦à¦¸à§à¦¤à¦¾à¦¨à¦¾,áá¡á¢ááá,á áµá³á,ã¢ã¹ã¿ã,é¿æ¯å¡çº³,ìì¤íë,Astana", :latitude => "51.1801", :longitude => "71.44598").save
City.new(:country_id => "127", :name => "Almaty", :aliases => "Alma Ata,Alma-Ata,Almaato,Almata,Almati,Almato,Almaty,AlmatÃµ,AlmatÃ½,AlmatÄ±,AÅma-Ata,Gorad Alma-Ata,Vernyy,a la mu tu,almaaty,almati,almaty,arumatoi,xal mati,ÎÎ»Î¼Î¬ÏÎ¹,ÐÐ»Ð¼Ð°-ÐÑÐ°,ÐÐ»Ð¼Ð°Ð°ÑÐ¾,ÐÐ»Ð¼Ð°ÑÐ¸,ÐÐ»Ð¼Ð°ÑÑ,ÐÐ¾ÑÐ°Ð´ ÐÐ»Ð¼Ð°-ÐÑÐ°,Ô±Õ¬Õ´Õ¡Õ©Õ«,×××××××¢,×××××,Ø¢ÙÙØ§Ø¢ØªÛ,Ø£ÙÙØ§ØªÙ,Ø¦Ø§ÙÙÛØªØ§,Ø§ÙÙØ§ØªÛ,à¤à¤²à¥à¤®à¤¾à¤à¥,à¸­à¸±à¸¥à¸¡à¸²à¸à¸µ,à½¨à½±à½£à¼à½à¼à½à½²à¼,áááááá,ã¢ã«ããã¤,é¿ææ¨å,ìë§í°,Almaty", :latitude => "43.25", :longitude => "76.95").save
City.new(:country_id => "127", :name => "Akkol'", :aliases => "Akkol',Akkolâ,ÐÐºÐºÐ¾Ð»Ñ,Akkolâ", :latitude => "53.2925", :longitude => "69.60111").save
City.new(:country_id => "127", :name => "Abay", :aliases => "Abaj,Abay,Churbay-Nura,Churubay-Nura,ÐÐ±Ð°Ð¹,Abay", :latitude => "49.63111", :longitude => "72.85389").save
City.new(:country_id => "127", :name => "Stepnogorsk", :aliases => "STEPNOGORSK,Stepnogorsk,Ð¡Ð¢ÐÐÐÐÐÐÐ Ð¡Ð,Stepnogorsk", :latitude => "52.35444", :longitude => "71.88694").save
