City.new(:country_id => "128", :name => "Vientiane", :aliases => "Bientian,Nakhon Viangchan,V'ent'jan,Ventjan,Viang chan,Viangchan,Vien Can,Vien Chang,Vieng Chan,Vieng-Caen,Vieng-Chan,Vieng-CÃ¦n,Viengtjan,Vientane,Vientian,Vientianas,Vientiane,VientiÃ¡n,ViÃªng ChÄn,Wei-t'ien,Wei-tâien,Wiang Chan,Wientian,biantian,vu~ienchan,vu~ienchan shi,weiyngcanthn,yong zhen,ÎÎ¹ÎµÎ½ÏÎ¹Î¬Î½,ÐÐµÐ½ÑÑÐ½,ÐÑÐµÐ½ÑÑÑÐ½,×××× ××××,ÙÛÙâØªÛØ§Ù,à¹à¸§à¸µà¸¢à¸à¸à¸±à¸à¸à¸à¹,à»àºàºàºàº´à»àºªàºàº§àº½àºàºàº±àº,à½à½²à½à¼à½à½²à½ à½à¼,á­á¨ááµá¬á,ã´ã£ã¨ã³ãã£ã³,ã´ã£ã¨ã³ãã£ã³å¸,æ°¸ç,ë¹ìí°ì,Vientiane", :latitude => "17.96667", :longitude => "102.6").save
City.new(:country_id => "128", :name => "Xam Nua", :aliases => "Muang Sam,Sammeua,Samnua,Xam Nua,Xam Nua", :latitude => "20.41972", :longitude => "104.04389").save
City.new(:country_id => "128", :name => "Savannakhet", :aliases => "Khwaeng Savannakhet,Khwaeng_Savannakhet,Muang Savannaket,Province de Savannakhet,Savannaket,Savannakhet,Savannakhet Province,SavannakhÃ©t,Savannakkhet,Suvannakhet,Suwanakhet,Svannakhet,SvannakhÃ©t,sawan'naketo xian,Ð¡Ð°Ð²Ð°Ð½Ð½Ð°ÐºÑÐµÑ,à¹à¸à¸§à¸à¸ªà¸°à¸«à¸§à¸±à¸à¸à¸°à¹à¸à¸,ãµã¯ã³ãã±ã¼ãç,SavannakhÃ©t", :latitude => "16.55", :longitude => "104.75").save
City.new(:country_id => "128", :name => "Pakxe", :aliases => "Pakse,PaksÃ©,Pakxe,PakxÃ©,PakxÃ©", :latitude => "15.11667", :longitude => "105.78333").save
City.new(:country_id => "128", :name => "Muang Xai", :aliases => "Mouang Sai,Muang Xai,Muang Xay,Muangsaj,Muong Sai,Sai,ÐÑÐ°Ð½Ð³ÑÐ°Ð¹,Muang Xai", :latitude => "20.7", :longitude => "101.98333").save
City.new(:country_id => "128", :name => "Muang Vangviang", :aliases => "Muang Vangviang,Vang V'eng,Vang Vieng,Viangviang,ÐÐ°Ð½Ð³ ÐÑÐµÐ½Ð³,Muang Vangviang", :latitude => "18.93333", :longitude => "102.45").save
City.new(:country_id => "128", :name => "Muang Pakxan", :aliases => "Muang Pakxan,Paksane,Pakxan,Muang Pakxan", :latitude => "18.37778", :longitude => "103.66007").save
City.new(:country_id => "128", :name => "Thakhek", :aliases => "Khammouane,Muang Khammouan,Muang Thakek,Tha Khaek,Thakhek,Thakhet,Thakhok,ThakhÃ¨k,ThakhÃ¨k", :latitude => "17.41027", :longitude => "104.83068").save
City.new(:country_id => "128", :name => "Louangphrabang", :aliases => "Louang Prabang,Louangphabang,Louangphrabang,Luan Praban,Luang Phrabang,Luang Prabang,Luang-Prabang,lang bo la bang,meuxng hlwng phra bang,ruanpaban,ÐÑÐ°Ð½Ð³-ÐÑÐ°Ð±Ð°Ð½Ð³,à¹à¸¡à¸·à¸­à¸à¸«à¸¥à¸§à¸à¸à¸£à¸°à¸à¸²à¸,àº«àº¥àº§àºàºàº°àºàº²àº,ã«ã¢ã³ããã¼ã³,çåæé¦,Louangphrabang", :latitude => "19.88556", :longitude => "102.13472").save
City.new(:country_id => "128", :name => "Ban Houakhoua", :aliases => "Ban  Khojjaksjau,Ban Houakhoua,Ban Houayxay,ÐÐ°Ð½  Ð¥Ð¾Ð¹ÑÐºÑÑÑ,Ban Houakhoua", :latitude => "20.24528", :longitude => "100.45472").save
City.new(:country_id => "128", :name => "Ban Phonsavan", :aliases => "Pkhonsavan,ÐÑÐ¾Ð½ÑÐ°Ð²Ð°Ð½,Ban PhÃ´nsavan", :latitude => "19.45907", :longitude => "103.17999").save
