City.new(:country_id => "129", :name => "Zahle", :aliases => "Zahlah,Zahle,Zahleh,ZahlÃ©,Zakhla,Zaá¸©lah,zhlh,zhlt,ÐÐ°ÑÐ»Ð°,××××,Ø²Ø­ÙØ©,ZahlÃ©", :latitude => "33.84972", :longitude => "35.90417").save
City.new(:country_id => "129", :name => "Tripoli", :aliases => "Tarabulus,Trablous,Tripoli,Tripolo,Trypolis,TrÃ¢blous,TrÃ­poli,tarabulus,toripori,trabls,trypwly,Å¢arÄbulus,Ð¢ÑÐ¸Ð¿Ð¾Ð»Ð¸,××¨××¤×××,ØªØ±Ø§Ø¨ÙØ³,Ø·Ø±Ø§Ø¨ÙØ³,Ø·ÙØ±ÙØ§Ø¨ÙÙÙØ³,ããªããª,Tripoli", :latitude => "34.43667", :longitude => "35.84972").save
City.new(:country_id => "129", :name => "Tyre", :aliases => "Es Sur,Sor,Sour,SoÃ»r,Sur,Surru,Tir,Tiro,Tyr,Tyras,Tyre,Tyros,Tyrus,TÃ½ros,alswr,sur,swr,tai er,tirusu,zr,zwr,ÅÅ«r,Î¤ÏÏÎ¿Ï,Ð¢Ð¸Ñ,Ð¢ÑÑ,Ð¢ÑµÑÑ,×¦××¨,×¦×¨,Ø§ÙØµÙØ±,ØµÙØ±,ØµÙÙØ±,á¹¢ur,á¹¢urru,á¹¢År,ãã£ã«ã¹,æ³°ç¾,Tyre", :latitude => "33.27333", :longitude => "35.19389").save
City.new(:country_id => "129", :name => "Sidon", :aliases => "Saida,Sayda,SaÃ¯da,Sidon,Sidon',Sidona,Sidonas,Sidone,SidÃ³n,Sydon,SÃ­don,saida,sayda,syda,zydwn,ÅaydÄ,Î£Î¹Î´ÏÎ½Î±,Ð¡Ð¸Ð´Ð¾Ð½,Ð¡Ð¸Ð´Ð¾Ð½Ñ,×¦××××,ØµÙØ¯Ø§,ØµÙÙÙØ¯ÙØ§,ãµã¤ã,Sidon", :latitude => "33.56306", :longitude => "35.36889").save
City.new(:country_id => "129", :name => "Ra's Bayrut", :aliases => ",Raâs BayrÅ«t", :latitude => "33.9", :longitude => "35.48333").save
City.new(:country_id => "129", :name => "Djounie", :aliases => "Djounie,Jounie,JoÃ¼niÃ©,Juniyah,JÅ«niyah,Djounie", :latitude => "33.98083", :longitude => "35.61778").save
City.new(:country_id => "129", :name => "Jbail", :aliases => "Bibl,Biblos,Byblos,Djebail,DjÃ©bail,Gebal,Gibelet,Giblet,Gubayl,Gubla,Jbail,Jbayl,JbaÃ¯l,Jbeil,Jebail,JebaÃ¯l,Jubayl,Keben,Kepen,biburosu,byblos,gbl,jbyl,Ç¦ubayl,Î²á½»Î²Î»Î¿Ï,ÐÐ¸Ð±Ð»,ÐÐ¸Ð±Ð»Ð¾Ñ,×××,Ø¬Ø¨ÙÙ,ããã­ã¹,Jbail", :latitude => "34.12111", :longitude => "35.64806").save
City.new(:country_id => "129", :name => "Habbouch", :aliases => "Habbouch,Habboush,HabboÃ»ch,Habbush,Khabbushe,Ð¥Ð°Ð±Ð±ÑÑÐµ,á¸¨abbÅ«sh,HabboÃ»ch", :latitude => "33.4075", :longitude => "35.48278").save
City.new(:country_id => "129", :name => "Bcharre", :aliases => "Basharri,BasharrÄ«,Bcharre,Bcharreh,Bcharri,BcharrÃ©,BcharrÄ«,Becharri,Besherri,Bishari,Bisharri,Bsharri,BsharrÄ«,Bsherri,ÐÐ¸ÑÐ°ÑÐ¸,BcharrÃ©", :latitude => "34.25083", :longitude => "36.01056").save
City.new(:country_id => "129", :name => "Beirut", :aliases => "Baeyrut,Bayrut,BayrÅ«t,Beiroet,Beirout,BeiroÅ«t,Beirut,Beirutas,Beirute,BeirÃºt,Bejrut,Bejruto,BejrÃºt,Berytos,Berytus,Beyrouth,Beyrut,BÃ¤yrut,bayrut,bei lu te,beiluteu,beiruto,byrwt,byyrwt,ÎÎ·ÏÏÏÏÏ,ÐÐµÐ¹ÑÑÑ,ÐÐµÑÑÑÑ,Ô²Õ¥ÕµÖÕ¸ÖÕ©,××××¨××ª,Ø¨ÙØ±ÙØª,Ø¨ÙÙÙØ±ÙÙØª,Ø¨ÛØ±ÙØª,ÜÜÜªÜÜ¬,à½ à½à½ºà¼à½£à½´à¼à½,ãã¤ã«ã¼ã,è´é²ç¹,ë² ì´ë£¨í¸,Beirut", :latitude => "33.88894", :longitude => "35.49442").save
City.new(:country_id => "129", :name => "Baalbek", :aliases => "Ba`albak,Ba`labak,Ba`labakk,Baal'bek,Baalbeck,Baalbek,Baâalbak,Baâlabak,Baâlabakk,Heliopolis,HÃ©liopolis,barubekku,ÐÐ°Ð°Ð»Ð±ÐµÐº,ÐÐ°Ð°Ð»ÑÐ±ÐµÐº,××¢×××§,Ø¨Ø¹ÙØ¨Ù,Ø¨Ø¹ÙØ¨Ú©,ãã¼ã«ããã¯,Baalbek", :latitude => "34.00583", :longitude => "36.21806").save
City.new(:country_id => "129", :name => "Nabatiye et Tahta", :aliases => "An Nabatiyah at Tahta,An NabaÅ£Ä«yah at Taá¸©tÄ,NabatÃ®yÃ© et Tahta", :latitude => "33.37889", :longitude => "35.48389").save
