City.new(:country_id => "135", :name => "Visaginas", :aliases => "Snechkus,Snieckus,SnieÄkus,Visagina,Visaginas,Wisaginia,visaginas,ÐÐ¸ÑÐ°Ð³Ð¸Ð½Ð°Ñ,Visaginas", :latitude => "55.6", :longitude => "26.41667").save
City.new(:country_id => "135", :name => "Vilnius", :aliases => "Bilna,Bilnious,VIL'NJUS,Vil'njus,Vil'no,Vil'nyus,Vilna,Vilnia,Vilnious,Vilnius,Vilnjus,Vilno,Vilnues,Vilnus,Vilnyus,VilnÃ­us,VilnÃ¼s,ViÄ¼Åa,VÃ­lnius,Wilna,Wilno,bilnyuseu,birinyusu,fylnyws,vilniusi,wei er niu si,wi lni xus,wylnh,wylnyws,ÎÎ¯Î»Î½Î±,ÎÎ¯Î»Î½Î¹Î¿ÏÏ,ÎÎ¹Î»Î½Î¹Î¿ÏÏ,ÐÐÐÐ¬ÐÐ®Ð¡,ÐÐ¸Ð»Ð½ÑÑ,ÐÐ¸Ð»Ð½ÑÑ,ÐÐ¸Ð»ÑÐ½ÑÑ,ÐÐ¸ÑÐ½ÑÑ,ÐÐ¸ÑÑÑÑ,ÐÑÐ»ÑÐ½ÑÑ,ÐÑÐ»ÑÐ½Ñ,ÕÕ«Õ¬Õ¶ÕµÕ¸ÖÕ½,×××× ×,ÙÙÙÙÙÙØ³,ÙÛÙÙÛÙØ³,à¸§à¸´à¸¥à¸à¸µà¸­à¸¸à¸ª,áááááá£á¡á,áªááááµ,ããªãã¥ã¹,ç»´å°çº½æ¯,ë¹ë´ì¤,Vilnius", :latitude => "54.68916", :longitude => "25.2798").save
City.new(:country_id => "135", :name => "Utena", :aliases => "Outena,UTENA,Uciana,Uciany,Utena,Utenos,Utyana,Uzjany,ÎÏÏÎ­Î½Î±,Ð£Ð¢ÐÐÐ,Ð£ÑÐµÐ½Ð°,Utena", :latitude => "55.5", :longitude => "25.6").save
City.new(:country_id => "135", :name => "Ukmerge", :aliases => "Oukmernke,UKMERGE,Ukmerge,Ukmerges,UkmergÄ,UkmergÄs,UkmerÄ£e,Ukmjarge,Vilkmerge,VilkmergÄ,Vilkomir,Wilkomierz,Wilkomir,WiÅkomierz,ÎÏÎºÎ¼ÎµÏÎ³ÎºÎ­,Ð£ÐÐÐÐ ÐÐ,Ð£ÐºÐ¼ÐµÑÐ³Ðµ,Ð£ÐºÐ¼ÑÑÐ³Ðµ,UkmergÄ", :latitude => "55.25", :longitude => "24.75").save
City.new(:country_id => "135", :name => "Telsiai", :aliases => "TEL'SHJAJ,Tel'shjaj,Telsai,Telsche,Telschen,Telshay,Telshi,Telshyay,Telsi,Telsiai,Telsiu,Telsze,TelÅ¡ai,TelÅ¡i,TelÅ¡iai,TelÅ¡iÅ³,terishiai,Î¤ÎµÎ»ÏÎ¹Î¬Î¹,Ð¢ÐÐÐ¬Ð¨Ð¯Ð,Ð¢ÐµÐ»ÑÑÑÐ¹,ããªã·ã¢ã¤,TelÅ¡iai", :latitude => "55.98139", :longitude => "22.24722").save
City.new(:country_id => "135", :name => "Taurage", :aliases => "Taouranke,Taurage,Taurages,TauragÄ,TauragÄs,TauraÄ£e,Taurogen,Tauroggen,Taurogi,Î¤Î±Î¿ÏÏÎ±Î³ÎºÎ­,Ð¢Ð°ÑÑÐ°Ð³Ðµ,TauragÄ", :latitude => "55.25222", :longitude => "22.28972").save
City.new(:country_id => "135", :name => "Silute", :aliases => "Heidekrug,Heydekrug,Heydekrug-Matzicken,SHILUTE,Shilute,Silute,Szylokarczma,SzyÅokarczma,sillute,Å ilute,Å ilutÄ,Ð¨ÐÐÐ£Ð¢Ð,ì¤ë£¨í,Å ilutÄ", :latitude => "55.34889", :longitude => "21.48306").save
City.new(:country_id => "135", :name => "Siauliai", :aliases => "Sauli,Schaulen,Shaulyay,Shavli,Shjauljaj,Shyaulyay,Siauliai,Siauliu,Sokniai,Szawle,Å auÄ¼i,Å iauliai,Å iauliÅ³,Ð¨ÑÑÐ»ÑÐ¹,Å iauliai", :latitude => "55.93333", :longitude => "23.31667").save
City.new(:country_id => "135", :name => "Rokiskis", :aliases => "Myasto Rokishkis,ROKISHKIS,Rakischki,Rakishki,Rakiskis,Rakiszki,RakiÅ¡kis,Rokishkis,Rokiski,Rokiskio,Rokiskis,RokiÅ¡kio,RokiÅ¡kis,RokiÅ¡Ä·i,Ð ÐÐÐÐ¨ÐÐÐ¡,Ð Ð¾ÐºÐ¸ÑÐºÐ¸Ñ,RokiÅ¡kis", :latitude => "55.96667", :longitude => "25.58333").save
City.new(:country_id => "135", :name => "Radviliskis", :aliases => "RADVILISHKIS,Radvilai,Radvilishkis,Radviliski,Radviliskio,Radviliskis,Radviliskis-Nemunelio,Radvilisks,RadviliÅ¡kio,RadviliÅ¡kis,RadviliÅ¡ks,RadviliÅ¡Ä·i,Radziwiliszki,Rantbiliskis,Î¡Î±Î½ÏÎ²Î¹Î»Î¯ÏÎºÎ¹Ï,Ð ÐÐÐÐÐÐÐ¨ÐÐÐ¡,RadviliÅ¡kis", :latitude => "55.81667", :longitude => "23.53333").save
City.new(:country_id => "135", :name => "Plunge", :aliases => "PLUNGE,Plunge,Plunges,Plungiany,PlungÄ,PlungÄs,PÅungiany,ÐÐÐ£ÐÐÐ,PlungÄ", :latitude => "55.91139", :longitude => "21.84417").save
City.new(:country_id => "135", :name => "Panevezys", :aliases => "PANEVEZHIS,Paneveza,Panevezhi,Panevezhis,Panevezio,Panevezys,PanevÄÅ¾a,PanevÄÅ¾io,PanevÄÅ¾ys,Panjavezhis,Ponewesch,Poniewesch,Poniewiesh,Poniewiez,PoniewieÅ¼,pnbz'ys,ÐÐÐÐÐÐÐÐÐ¡,ÐÐ°Ð½ÐµÐ²ÐµÐ¶Ð¸Ñ,ÐÐ°Ð½ÑÐ²ÐµÐ¶Ð¸Ñ,×¤× ××'××¡,PanevÄÅ¾ys", :latitude => "55.73333", :longitude => "24.35").save
City.new(:country_id => "135", :name => "Palanga", :aliases => "PALANGA,Palanga,Palangos,Polaga,Polanga,Polangen,PoÅÄga,palanga,ÐÐÐÐÐÐÐ,ÐÐ°Ð»Ð°Ð½Ð³Ð°,Palanga", :latitude => "55.9175", :longitude => "21.06861").save
City.new(:country_id => "135", :name => "Mazeikiai", :aliases => "Mazeiki,Mazeikiai,Mazeikiu,Mazhejkjaj,Mazheykyay,MaÅ¾eikiai,MaÅ¾eikiÅ³,MaÅ¾eiÄ·i,Mozejki,MoÅ¼ejki,Muravjovo,Murawlewo,ÎÎ±Î¶ÎµÏÎºÎ¹Î¬Î¹,ÐÐ°Ð¶ÐµÐ¹ÐºÑÐ¹,MaÅ¾eikiai", :latitude => "56.31667", :longitude => "22.33333").save
City.new(:country_id => "135", :name => "Marijampole", :aliases => "Kapsukas,MARIJAMPOLE,Mariampol,Mariampol',Mariampole,Mariampoles,MariampolÄ,MariampolÄs,Mariampolâ,Marigiampole,Marijampole,MarijampolÄ,Mariyampol',Mariyampole,Mariyampolâ,Marjampol,Pasesupiai,PaÅ¡eÅ¡upiai,Starapole,StarapolÄ,ÎÎ±ÏÎ¹Î³Î¹Î±Î¼ÏÎ¿Î»Î­,ÐÐÐ ÐÐ¯ÐÐÐÐÐ,ÐÐ°ÑÐ¸ÑÐ¼Ð¿Ð¾Ð»Ðµ,MarijampolÄ", :latitude => "54.56667", :longitude => "23.35").save
City.new(:country_id => "135", :name => "Kretinga", :aliases => "Kratinga,Kretin'nka,Kretinga,Kretingos,Kretynga,Krottingen,Myasto Kretinga,keuleting-ga,ÎÏÎµÏÎ¯Î½Î³ÎºÎ±,ÐÑÐµÑÐ¸Ð½Ð³Ð°,í¬ë íê°,Kretinga", :latitude => "55.87583", :longitude => "21.25083").save
City.new(:country_id => "135", :name => "Klaipeda", :aliases => "Klaipada,Klaipeda,Klaipenta,KlaipÃ©da,KlaipÄda,KlaipÄda,Klajpeda,Klaypeda,KÅajpeda,Lungsod ng Klaipeda,Lungsod ng KlaipÄda,Memel,Memela,ke lai pei da,keullaipeda,khil pheda,klaipedas,kuraipeda,qlypdh,qlyypdh,ÎÎ»Î±ÏÏÎ­Î½ÏÎ±,ÐÐ»Ð°Ð¸Ð¿ÐµÐ´Ð°,ÐÐ»Ð°Ð¹Ð¿ÐµÐ´Ð°,ÐÐ»Ð°ÑÐ¿ÐµÐ´Ð°,×§××××¤××,×§×××¤××,à¹à¸à¸¥à¹à¸à¸à¸²,ã¯ã©ã¤ãã,åè±ä½©è¾¾,í´ë¼ì´íë¤,KlaipÄda", :latitude => "55.71722", :longitude => "21.1175").save
City.new(:country_id => "135", :name => "Kedainiai", :aliases => "KEDAJNJAJ,Kedaini,Kedainiai,Kedainiu,KedainiÅ³,Kedajnaj,Kedayny,Kedaynyai,Kedaynyay,Keidany,Kentainiai,Keydany,Kiejdany,KÄdaiÅi,KÄdainiai,kedajnjaj,ÎÎµÎ½ÏÎ±ÏÎ½Î¹Î¬Î¹,ÐÐÐÐÐÐÐ¯Ð,ÐÐµÐ´Ð°jÑÐ°Ñ,ÐÐµÐ´Ð°Ð¹Ð½ÑÐ¹,KÄdainiai", :latitude => "55.28833", :longitude => "23.97472").save
City.new(:country_id => "135", :name => "Kaunas", :aliases => "Caunas,KAUNAS,Kauen,Kaunas,Kauno,Kovno,Kowno,Palemonas,ÐÐÐ£ÐÐÐ¡,ÐÐ°ÑÐ½Ð°Ñ,Kaunas", :latitude => "54.9", :longitude => "23.9").save
City.new(:country_id => "135", :name => "Jonava", :aliases => "IONAVA,Ionava,Janow,JanÃ³w,Jonava,Jonavos Miestelis,Yonava,ÐÐÐÐÐÐ,Jonava", :latitude => "55.08333", :longitude => "24.28333").save
City.new(:country_id => "135", :name => "Gargzdai", :aliases => "GARGZHDAJ,Gardzdai,GardÅ¾dai,Gargzdai,Gargzdi,Gargzdu,Gargzhdaj,Gargzhday,GargÅ¾dai,GargÅ¾di,GargÅ¾dÅ³,Garsden,Garzdai,GarÅ¾dai,Gorzdy,GorÅ¼dy,ÐÐÐ ÐÐÐÐÐ,ÐÐ°ÑÐ³Ð¶Ð´Ð°Ð¹,GargÅ¾dai", :latitude => "55.71278", :longitude => "21.40333").save
City.new(:country_id => "135", :name => "Druskininkai", :aliases => "DRUSKININKAJ,Druskeniki,Druskieniki,Druskiniki,Druskininkai,Druskininkaj,Druskininkay,Druskininki,DruÅkieniki,ÐÐ Ð£Ð¡ÐÐÐÐÐÐÐÐ,ÐÑÑÑÐºÐ¸Ð½Ð¸Ð½ÐºÐ°Ð¹,Druskininkai", :latitude => "54.01667", :longitude => "23.96667").save
City.new(:country_id => "135", :name => "Alytus", :aliases => "ALITUS,Alita,Alitus,Alytaus,Alytus,AlÄ«ta,Olita,allituseu,ÐÐÐÐ¢Ð£Ð¡,ÐÐ»Ð¸ÑÑÑ,ìë¦¬í¬ì¤,Alytus", :latitude => "54.4", :longitude => "24.05").save
City.new(:country_id => "135", :name => "Dainava (Kaunas)", :aliases => ",Dainava (Kaunas)", :latitude => "54.91525", :longitude => "23.96831").save
