City.new(:country_id => "137", :name => "Valmiera", :aliases => "Valmeena,Valmeera,Valmera,Valmiera,Valmieras,Vol'mar,Wolmar,ÐÐ°Ð»Ð¼Ð¸ÐµÑÐ°,Valmiera", :latitude => "57.54108", :longitude => "25.42751").save
City.new(:country_id => "137", :name => "Ventspils", :aliases => "Ventspils,Vindau,Vindava,Wentspils,Windau,ÐÐµÐ½ÑÑÐ¿Ð¸Ð»Ñ,Ventspils", :latitude => "57.38944", :longitude => "21.56056").save
City.new(:country_id => "137", :name => "Vec-Liepaja", :aliases => "Old Libau,Old Liepaja,Old LiepÄja,Staraya Libava,Vec-Liepaja,Vec-LiepÄja,Vec-LiepÄja", :latitude => "56.53333", :longitude => "21.01667").save
City.new(:country_id => "137", :name => "Tukums", :aliases => "Tukkum,Tukum,Tukumas,Tukums,Ð¢ÑÐºÑÐ¼Ñ,Tukums", :latitude => "56.96694", :longitude => "23.15528").save
City.new(:country_id => "137", :name => "Salaspils", :aliases => "Kirchholm,Kirkholm,Salaspilis,Salaspils,Ð¡Ð°Ð»Ð°ÑÐ¿Ð¸Ð»Ñ,Salaspils", :latitude => "56.86014", :longitude => "24.36544").save
City.new(:country_id => "137", :name => "Riga", :aliases => "RIGA,Riga,Rigae,Rigo,Riia,Riika,Rija,Ryga,RÃ­ga,RÄ«ga,li jia,liga,riga,rika,rygh,rygha,Î¡Î¯Î³Î±,Ð ÐÐÐ,Ð Ð¸Ð³Ã¦,Ð Ð¸Ð³Ð°,Ð ÑÒÐ°,×¨×××,Ø±ÙØºØ§,à¤°à¤¿à¤à¤¾,à¸£à¸´à¸à¸²,á ááá,áªá,ãªã¬,éå ,ë¦¬ê°,Riga", :latitude => "56.946", :longitude => "24.10589").save
City.new(:country_id => "137", :name => "Rezekne", :aliases => "REZEKNE,Rezekne,RezeknÄ,Rezhitsa,Rositten,Ryezhitsa,Rzezyca,RzeÅ¼yca,RÄzekne,RÄzeknÄ,rzqnh,Î¡Î­Î¶ÎµÎºÎ½Îµ,Ð ÐÐÐÐÐÐ,Ð ÐµÐ·ÐµÐºÐ½Ðµ,×¨××§× ×,RÄzekne", :latitude => "56.5", :longitude => "27.31667").save
City.new(:country_id => "137", :name => "Ogre", :aliases => "OGRE,Ogre,Uogre,UogrÄ,ÐÐÐ Ð,Ogre", :latitude => "56.8162", :longitude => "24.61401").save
City.new(:country_id => "137", :name => "Liepaja", :aliases => "Leepaja,Lepaya,Libau,Libava,Liepaa,Liepagia,Liepaiya,Liepaja,Liepaya,Liepoja,LiepÄja,Lietaja,Lietaya,Lipawa,Liyepaya,liepaya,riepaya,ÎÎ¹ÎµÏÎ¬Î³Î¹Î±,ÎÎ¹ÎµÏÎ±Î³Î¹Î±,ÐÐ¸ÐµÐ¿Ð°Ñ,ÐÑÐµÐ¿Ð°Ñ,×××¤×××,ãªã¨ãã¼ã¤,ë¦¬ìíì¼,LiepÄja", :latitude => "56.51667", :longitude => "21.01667").save
City.new(:country_id => "137", :name => "Jurmala", :aliases => "Jurmala,JÅ«rmala,Riga Beach,Riga-Strand,Rigas Iurmala,Rigas Jormalas Pilseta,Rigas Jurmala,Rigas Yurmala,Rigastrand,Rizhskoye Vzmor'ye,RÄ«gas Jormalas PilsÄta,RÄ«gas JÅ«rmala,Yuomala,Yurmala,Ð®ÑÐ¼Ð°Ð»Ð°,JÅ«rmala", :latitude => "56.968", :longitude => "23.77038").save
City.new(:country_id => "137", :name => "Jelgava", :aliases => "Elgava,Iyelgava,Jelgava,Jelgawa,Mitau,Mitava,Mitawa,Yelgava,ÐÐ»Ð³Ð°Ð²Ð°,ÐÐ»ÒÐ°Ð²Ð°,Jelgava", :latitude => "56.65", :longitude => "23.71278").save
City.new(:country_id => "137", :name => "Jekabpils", :aliases => "EKABPILS,Jakobstadt,Jekabpilis,Jekabpils,JÄkabpils,Kreuzburg,Krustpils,Yakabpils,Yekabpils,ÐÐÐÐÐÐÐÐ¡,ÐÐµÐºÐ°Ð±Ð¿Ð¸Ð»Ñ,JÄkabpils", :latitude => "56.49903", :longitude => "25.85735").save
City.new(:country_id => "137", :name => "Daugavpils", :aliases => "DAUGAVPILS,Daugaupils,Daugavpils,Daugawpils,Daugpilis,Duenaburg,Dvinsk,Dwinsk,Dyneburg,DÃ¼naburg,Vaeinaenlinna,VÃ¤inÃ¤nlinna,daugafupirusu,daugapeupilseu,ÐÐÐ£ÐÐÐÐÐÐÐ¡,ÐÐ°ÑÐ³Ð°Ð²Ð¿Ð¸Ð»Ñ,ÐÐ°ÑÒÐ°ÑÐ¿ÑÐ»Ñ,××××××¤×××¡,ãã¦ã¬ããã«ã¹,ë¤ì°ê°ííì¤,Daugavpils", :latitude => "55.88333", :longitude => "26.53333").save
City.new(:country_id => "137", :name => "Cesis", :aliases => "CESIS,Cesis,Cesys,CÄsis,CÄsys,Tsesis,Venden,Wenden,tsu~eshisu,Ð¦ÐÐ¡ÐÐ¡,Ð¦ÐµÑÐ¸Ñ,ãã§ã¼ã·ã¹,CÄsis", :latitude => "57.31188", :longitude => "25.27456").save
