City.new(:country_id => "138", :name => "Tobruk", :aliases => "Antipyrgos,Antipyrgus,Tobroek,Tobrouk,Tobruch,Tobruck,Tobruk,Tubruk,Tubruq,TÃ³bruch,tbrq,toburuku,tu bo lu ge,tubruq,twbrwq,Å¢ubruq,Ð¢Ð¾Ð±ÑÑÐº,××××¨××§,Ø·Ø¨Ø±Ù,Ø·ÙØ¨ÙØ±ÙÙ,ããã«ã¯,å¾åé²æ ¼,Tobruk", :latitude => "32.08361", :longitude => "23.97639").save
City.new(:country_id => "138", :name => "Suluq", :aliases => "Qaryat Salug,Qaryat Saluq,Qaryat SalÅ«g,Qaryat SalÅ«q,Soluch,Solugh,SolÃ¹gh,Suluq,SulÅ«q,SulÅ«q", :latitude => "31.66861", :longitude => "20.25").save
City.new(:country_id => "138", :name => "Darnah", :aliases => "Daernae,Darnah,Darnis,Derna,DÃ¤rnÃ¤,DÃ©rna,drnh,drnt,××¨× ×,Ø¯Ø±ÙØ©,Darnah", :latitude => "32.76704", :longitude => "22.63669").save
City.new(:country_id => "138", :name => "Banghazi", :aliases => "Baengasi,Banghazi,BanghÄzÄ«,Bengasi,Bengaze,Bengazi,Benghasi,Benghazi,Berenice,Bingazi,Binghazi,BinghÄzÄ«,BÃ¤ngasi,Hesperides,ban jia xi,bnghazy,ÎÎµÎ³Î³Î¬Î¶Î·,ÐÐµÐ½Ð³Ð°Ð·Ð¸,×× ××××,Ø¨ÙØºØ§Ø²Ù,Ø¨ÙØºØ§Ø²Û,ç­å è¥¿,BanghÄzÄ«", :latitude => "32.11667", :longitude => "20.06667").save
City.new(:country_id => "138", :name => "Az Zuwaytinah", :aliases => "Az Zuwaytinah,Az ZuwaytÄ«nah,Ez Zuetina,Ez ZuetÃ­na,Marsa Uasili,Qaryat az Zuwaytinah,Qaryat az ZuwaytÄ«nah,Zueitina,Zuetina,Az ZuwaytÄ«nah", :latitude => "30.95389", :longitude => "20.12167").save
City.new(:country_id => "138", :name => "At Taj", :aliases => "At Taj,At TÄj,Et Tag,At TÄj", :latitude => "24.21667", :longitude => "23.3").save
City.new(:country_id => "138", :name => "Al `Aquriyah", :aliases => "Taukra,Teuchira,Tocra,Tokrah,Tukrah,TÃ³cra,TÅ«krah,Al `ÄqÅ«rÄ«yah", :latitude => "32.53333", :longitude => "20.56667").save
City.new(:country_id => "138", :name => "Al Qubbah", :aliases => "Al Gubbah,Berta,El-Gubba,El-GÃºbba,Giovanni Berta,Gubba,Al Qubbah", :latitude => "32.76667", :longitude => "22.25").save
City.new(:country_id => "138", :name => "Al Marj", :aliases => "Al Marj,Al'-Mardzh,El Merj,Maerciaen,MÃ¤rciÃ¤n,almrj,ÐÐ»Ñ-ÐÐ°ÑÐ´Ð¶,Ø§ÙÙØ±Ø¬,Ø´Ø¹Ø¨ÙØ© Ø§ÙÙØ±Ø¬,Al Marj", :latitude => "32.48798", :longitude => "20.83174").save
City.new(:country_id => "138", :name => "Al Jawf", :aliases => "Al Jawf,Al-Jof,El-Giof,El-GiÃ³f,Al Jawf", :latitude => "24.1989", :longitude => "23.29093").save
City.new(:country_id => "138", :name => "Al Bayda'", :aliases => "Al Bayda',Al Bayá¸Äâ,Al-Baida,Az Zawiyah al Bayda',Az ZÄwiyah al Bayá¸Äâ,Baida,Balagrae,Balis,Bayda,Beda,Beida,El Beida,White Monastery,Zauia el Beda,Zawiat al-Baida,Zawiyat al Bayda',Zawiyat el-Beda',ZÄwiyat al Bayá¸Äâ,ZÄwiyat el-BÄá¸Äâ,albydaÊ¾,Ø§ÙØ¨ÙØ¶Ø§Ø¡,Al Bayá¸Äâ", :latitude => "32.76272", :longitude => "21.75506").save
City.new(:country_id => "138", :name => "Al Abyar", :aliases => "Alabia,El Abiar,Madirat al Abyar,MadÄ«rat al AbyÄr,Al AbyÄr", :latitude => "32.19", :longitude => "20.59653").save
City.new(:country_id => "138", :name => "Ajdabiya", :aliases => "AEcdabiya,Adjadabia,Agedabia,Ajdabiya,Ajdabiyah,AjdÄbiyah,AjdÄbiyÄ,Laecdabiaen,LÃ¤cdabiÃ¤n,ajdabya,Ãcdabiya,Ø£Ø¬Ø¯Ø§Ø¨ÙØ§,Ø´Ø¹Ø¨ÙØ© Ø¥Ø¬Ø¯Ø§Ø¨ÙØ§,AjdÄbiyÄ", :latitude => "30.75917", :longitude => "20.22306").save
City.new(:country_id => "138", :name => "Zuwarah", :aliases => "Zuara,Zuava,Zuwarah,ZuwÄrah,ZuÃ¡ra,ZuÃ¡va,zuart,ÐÑÐ°ÑÐ°,Ø²ÙÙØ§Ø±Ø©,ZuwÄrah", :latitude => "32.9312", :longitude => "12.08199").save
City.new(:country_id => "138", :name => "Zlitan", :aliases => "Isliten,IslÄ«ten,Izliten,IzlÄ«ten,Subgoli,Ziliten,Zlitan,Zliten,ZlÄ«Å£an,ZlÄ«Å£an", :latitude => "32.46667", :longitude => "14.56667").save
City.new(:country_id => "138", :name => "Zaltan", :aliases => "Zaltan,ZalÅ£an,Zelten,ZalÅ£an", :latitude => "32.94701", :longitude => "11.86647").save
City.new(:country_id => "138", :name => "Yafran", :aliases => "Gasr Iefren,Iefren,Jafran,Jefren,Yaefraeniaen,Yafran,Yafrin,YÃ¤frÃ¤niÃ¤n,Ð¯ÑÑÐ°Ð½,Ø´Ø¹Ø¨ÙØ© ÙÙØ±Ù,Yafran", :latitude => "32.06306", :longitude => "12.52694").save
City.new(:country_id => "138", :name => "Waddan", :aliases => "Uaddan,Waddan,WaddÄn,WaddÄn", :latitude => "29.1614", :longitude => "16.13904").save
City.new(:country_id => "138", :name => "Tarhunah", :aliases => "El-Buerat,El-BuerÃ¡t,El-Ubberat,El-UbberÃ¡t,Gasr Tarhuna,Qasr Tarhunah,QaÅr TarhÅ«nah,Tarhuna,Tarhunah,TarhÅ«nah,Tarkhuny,Ð¢Ð°ÑÑÑÐ½Ñ,TarhÅ«nah", :latitude => "32.43502", :longitude => "13.6332").save
City.new(:country_id => "138", :name => "Tripoli", :aliases => "Aea,Ea,Oea,Tarables,Tarabulus,Tarabulus al Gharb,Tarabulus el Gharb,TarÃ bles,Tripole,Tripoli,Tripolis,TrÃ­poli,tarabulus,Å¢arÄbulus,Å¢arÄbulus al Gharb,Î¤ÏÎ¯ÏÎ¿Î»Î·,Ð¢ÑÐ¸Ð¿Ð¾Ð»Ð¸,Ø·ÙØ±ÙØ§Ø¨ÙÙÙØ³,Tripoli", :latitude => "32.87519", :longitude => "13.18746").save
City.new(:country_id => "138", :name => "Tajura'", :aliases => "Tagiura,Tajura',Tajurah,TÄjÅ«rÄh,TÄjÅ«rÄâ,TÄjÅ«rÄâ", :latitude => "32.88167", :longitude => "13.35056").save
City.new(:country_id => "138", :name => "Surt", :aliases => "Gasr Zaafran,Gasr ZaafrÃ¡n,Macomades-Euphranta,Qasr Sirt,Qasr Za`faran,QaÅr Sirt,QaÅr ZaâfarÄn,Sert,Sirt,Sirte,Surt,Surtaen,Surtiaen,SurtiÃ¤n,SurtÃ¤n,Syrte,astan srt,srt,su er te,su te,Ð¡ÑÑÑ,Ø§Ø³ØªØ§Ù Ø³Ø±Øª,Ø³Ø±Øª,Ø´Ø¹Ø¨ÙØ© Ø³Ø±Øª,èå°ç¹,èç¹,Surt", :latitude => "31.20892", :longitude => "16.58866").save
City.new(:country_id => "138", :name => "Surman", :aliases => "Sorman,SormÃ¡n,Surman,ÅurmÄn,ÅurmÄn", :latitude => "32.75639", :longitude => "12.575").save
City.new(:country_id => "138", :name => "Sabratah", :aliases => "Madinat Sabratah,MadÄ«nat ÅabrÄtah,Sabra,Sabrah,Sabratah,Sabratha,SÃ¡bra,Åabrah,ÅabrÄtah,ÅabrÄtah", :latitude => "32.79194", :longitude => "12.48472").save
City.new(:country_id => "138", :name => "Sabha", :aliases => "El-Gedid,El-GedÃ­d,Fort Leclerc,Sabha,Sabhah,SabhÄ,Saebha,Saebhiaen,Sebha,Sebhah,SÃ¤bha,SÃ¤bhiÃ¤n,sabha,sai bo ha,sbha,Ø³Ø¨ÙØ§,Ø³ÙØ¨ÙØ§,Ø´Ø¹Ø¨ÙØ© Ø³Ø¨ÙØ§,å¡åå,SabhÄ", :latitude => "27.03766", :longitude => "14.42832").save
City.new(:country_id => "138", :name => "Nalut", :aliases => "Lalut,LalÃºt,Nalut,NÄlÅ«t,nalwt,ÙØ§ÙÙØª,NÄlÅ«t", :latitude => "31.86848", :longitude => "10.9812").save
City.new(:country_id => "138", :name => "Murzuq", :aliases => "Marzuq,MarzÅ«q,Mourzouk,Mursukiaen,MursukiÃ¤n,Murzuch,Murzuk,Murzuq,Ø´Ø¹Ø¨ÙØ© ÙØ±Ø²Ù,Murzuq", :latitude => "25.91552", :longitude => "13.91839").save
City.new(:country_id => "138", :name => "Mizdah", :aliases => "Misdah,Mizda,Mizdah", :latitude => "31.43333", :longitude => "12.98333").save
City.new(:country_id => "138", :name => "Misratah", :aliases => "Al Misratah,Madinat Misratah,MadÄ«nat MiÅrÄtah,Misrata,Misratah,Misurata,MiÅrÄtah,msrath,msratt,myswrth,ÐÐ¸ÑÑÑÐ°ÑÐ°,×××¡××¨××,ÙØµØ±Ø§ØªØ©,ÙØµØ±Ø§ØªÙ,MiÅrÄtah", :latitude => "32.37535", :longitude => "15.09254").save
City.new(:country_id => "138", :name => "Masallatah", :aliases => ",MasallÄtah", :latitude => "32.61667", :longitude => "14").save
City.new(:country_id => "138", :name => "Hun", :aliases => "Hon,Hun,HÅ«n,Madinat Hun,MadÄ«nat HÅ«n,hwn,ÙÙÙ,HÅ«n", :latitude => "29.12684", :longitude => "15.94772").save
City.new(:country_id => "138", :name => "Harat az Zawiyah", :aliases => "Al Harah,Al á¸¨Ärah,El-Hara,El-HÃ¡ra,Haraf Az Zawiyah,Haraf Az ZÄwÄ«yah,Harat az Zawiyah,á¸¨Ärat az ZÄwiyah,á¸¨Ärat az ZÄwiyah", :latitude => "32.76306", :longitude => "12.715").save
City.new(:country_id => "138", :name => "Ghat", :aliases => "Gat,Ghat,GhÄt,Rhat,ghat,ÐÐ°Ñ,ØºØ§Øª,GhÄt", :latitude => "24.96472", :longitude => "10.17278").save
City.new(:country_id => "138", :name => "Gharyan", :aliases => "Garian,Gasr Garian,Gasr GariÃ n,Gharyan,GharyÄn,gharyan,ghryan,ØºØ±ÙØ§Ù,ØºÙØ±ÙØ§Ù,GharyÄn", :latitude => "32.17222", :longitude => "13.02028").save
City.new(:country_id => "138", :name => "Birak", :aliases => "Birak,BirÄk,Brach,BirÄk", :latitude => "27.54956", :longitude => "14.27138").save
City.new(:country_id => "138", :name => "Bani Walid", :aliases => "Beni Ulid,Gasr Beni Ulid,Gasr BÃ©ni UlÃ­d,Qasr Bani Walid,QaÅr BanÄ« WalÄ«d,BanÄ« WalÄ«d", :latitude => "31.76667", :longitude => "13.98333").save
City.new(:country_id => "138", :name => "Az Zintan", :aliases => "Az Zantam,Az ZantÄm,Az Zintan,Az ZintÄn,Ez-Zintan,Ez-ZintÃ¡n,Zintan,ZintÃ¡n,Az ZintÄn", :latitude => "31.93333", :longitude => "12.23333").save
City.new(:country_id => "138", :name => "Awbari", :aliases => "Awbari,AwbÄrÄ«,Ubari,awbary,Ø£ÙØ¨Ø§Ø±Ù,AwbÄrÄ«", :latitude => "26.58333", :longitude => "12.76667").save
City.new(:country_id => "138", :name => "Al Khums", :aliases => "Al Khums,El Choms,Homs,Khoms,Labdah,Lebda,alkhums,Ø§ÙØ®ÙÙØ³,Al Khums", :latitude => "32.65", :longitude => "14.26667").save
City.new(:country_id => "138", :name => "Al Jadid", :aliases => "Al Jadid,Al JadÄ«d,Al'-Dzhadid,El-Gedid,El-GedÃ­d,ÐÐ»Ñ-ÐÐ¶Ð°Ð´Ð¸Ð´,Al JadÄ«d", :latitude => "27.05", :longitude => "14.4").save
