City.new(:country_id => "139", :name => "Zaio", :aliases => "Toumiat Zaio,Toumiat ZaÃ¯o,Tumiat,Tumiat Zaio,Zaio,ZaÃ¯o,ZaÃ¯o", :latitude => "34.94282", :longitude => "-2.7329").save
City.new(:country_id => "139", :name => "Zagora", :aliases => "Zagora,ÐÐ°Ð³Ð¾ÑÐ°,Zagora", :latitude => "30.33241", :longitude => "-5.8384").save
City.new(:country_id => "139", :name => "Youssoufia", :aliases => "Louis Gentil,Youssoufia,Youssoufia", :latitude => "32.24634", :longitude => "-8.52941").save
City.new(:country_id => "139", :name => "Tiznit", :aliases => "Tiznit,Ð¢Ð¸Ð·Ð½Ð¸Ñ,Tiznit", :latitude => "29.69742", :longitude => "-9.73162").save
City.new(:country_id => "139", :name => "Tirhanimine", :aliases => ",TirhanimÃ®ne", :latitude => "35.23619", :longitude => "-3.95453").save
City.new(:country_id => "139", :name => "Tineghir", :aliases => "Tineghir,Tinerhir,Tinghir,Tinrhir,Tineghir", :latitude => "31.51571", :longitude => "-5.53428").save
City.new(:country_id => "139", :name => "Tiflet", :aliases => ",Tiflet", :latitude => "33.89469", :longitude => "-6.3065").save
City.new(:country_id => "139", :name => "Tetouan", :aliases => "Tetouan,Tetuan,TetuÃ¡n,TÃ©touan,ttwan,Ð¢ÐµÑÑÐ°Ð½,ØªØ·ÙØ§Ù,TÃ©touan", :latitude => "35.57109", :longitude => "-5.37242").save
City.new(:country_id => "139", :name => "Taza", :aliases => "Taza,tazh,tazt,Ð¢Ð°Ð·Ð°,ØªØ§Ø²Ø©,ØªØ§Ø²Ù,Taza", :latitude => "34.21", :longitude => "-4.01").save
City.new(:country_id => "139", :name => "Taroudant", :aliases => "Taroudant,Tarudant,Ð¢Ð°ÑÑÐ´Ð°Ð½Ñ,Taroudant", :latitude => "30.47028", :longitude => "-8.87695").save
City.new(:country_id => "139", :name => "Taourirt", :aliases => ",Taourirt", :latitude => "34.4073", :longitude => "-2.89732").save
City.new(:country_id => "139", :name => "Taounate", :aliases => "Taounat,Taounate,Taunat,Tawnat,Ð¢Ð°ÑÐ½Ð°Ñ,Taounate", :latitude => "34.53822", :longitude => "-4.64143").save
City.new(:country_id => "139", :name => "Tan-Tan", :aliases => "Tan-Tan,tantan,Ð¢Ð°Ð½-Ð¢Ð°Ð½,Ø·Ø§ÙØ·Ø§Ù,Tan-Tan", :latitude => "28.43799", :longitude => "-11.10321").save
City.new(:country_id => "139", :name => "Tangier", :aliases => "Tanger,Tangeri,Tangero,Tangier,Tanzher,TanÄero,Tingis,TÃ nger,TÃ¡nger,TÃ¢nger,tan ji ya,tnjt,Ð¢Ð°Ð½Ð³ÐµÑ,Ð¢Ð°Ð½Ð¶ÐµÑ,Ø·ÙØ¬Ø©,å¦å¹¾äº,Tangier", :latitude => "35.78058", :longitude => "-5.81365").save
City.new(:country_id => "139", :name => "Tahala", :aliases => "El Ayba Tahalla,Tahala,Tahala", :latitude => "34.04845", :longitude => "-4.42795").save
City.new(:country_id => "139", :name => "Souq Larb'a al Gharb", :aliases => "El Arba du Gharb,El Arba du Rharb,El Arbaa du Rharb,El Arboa du Rharb,Souk-el-Arba-du-Gharb,Souq Larb'a al Gharb,Souq Larbâa al Gharb,Souq Larbâa al Gharb", :latitude => "34.68664", :longitude => "-6.00272").save
City.new(:country_id => "139", :name => "Sidi Yahia el Gharb", :aliases => "Sidi Yahia al Gharb,Sidi Yahia del Garb,Sidi Yahia el Gharb,Sidi Yahia el Rharb,Sidi Yahya du Rharb,Sidi Yanya du Rharb,Sidi Yaya du Rhanb,SÃ¯di Yaya du Rhanb,Sidi Yahia el Gharb", :latitude => "34.30652", :longitude => "-6.30618").save
City.new(:country_id => "139", :name => "Sidi Slimane", :aliases => "Sidi Slamain,Sidi Sliman,Sidi Slimane,Sidi-Slimane,Ð¡Ð¸Ð´Ð¸-Ð¡Ð»Ð¸Ð¼Ð°Ð½Ðµ,Sidi Slimane", :latitude => "34.26478", :longitude => "-5.92598").save
City.new(:country_id => "139", :name => "Sidi Qacem", :aliases => "Petitjean,Pettijean,Sidi Kacem,Sidi Qacem,Sidi Qasim,SÄ«dÄ« QÄsim,sdy qasm,Ø³Ø¯Ù ÙØ§Ø³Ù,Sidi Qacem", :latitude => "34.22149", :longitude => "-5.70775").save
City.new(:country_id => "139", :name => "Sidi Ifni", :aliases => "Ifni,Sidi Ifni,Sidifni,sydy afny,Ð¡Ð¸Ð´Ð¸ ÐÑÐ½Ð¸,Ø³ÙØ¯Ù Ø¥ÙÙÙ,Sidi Ifni", :latitude => "29.37975", :longitude => "-10.17299").save
City.new(:country_id => "139", :name => "Sidi Bennour", :aliases => ",Sidi Bennour", :latitude => "32.65236", :longitude => "-8.42769").save
City.new(:country_id => "139", :name => "Settat", :aliases => "Settat,stat,Ð¡ÐµÑÑÐ°Ñ,Ø³Ø·Ø§Øª,Settat", :latitude => "33.0007", :longitude => "-7.62035").save
City.new(:country_id => "139", :name => "Sefrou", :aliases => "Sefrou,Sefru,SefrÃº,Sefrou", :latitude => "33.83186", :longitude => "-4.828").save
City.new(:country_id => "139", :name => "Sale", :aliases => "Sala,Sale,Sali,Sallee,SalÃ©,Sla,sla,Ð¡Ð°Ð»Ðµ,Ø³ÙØ§,SalÃ©", :latitude => "34.03892", :longitude => "-6.8166").save
City.new(:country_id => "139", :name => "Safi", :aliases => "Asfi,Safi,Safim,asfy,Ð¡Ð°ÑÐ¸,Ø£Ø³ÙÙ,Safi", :latitude => "32.29939", :longitude => "-9.23718").save
City.new(:country_id => "139", :name => "Rabat", :aliases => "Rabat,Rabatas,Rampat,alrbat,la ba te,labateu,rabat,rabato,rbat,Î¡Î±Î¼ÏÎ¬Ï,Ð Ð°Ð±Ð°Ñ,×¨×××,Ø§ÙØ±Ø¨Ø§Ø·,Ø±Ø¨Ø§Ø·,à½¢à¼à½à¼à½à½º,á«á£áµ,ã©ãã,æå·´ç¹,ë¼ë°í¸,Rabat", :latitude => "34.01325", :longitude => "-6.83255").save
City.new(:country_id => "139", :name => "Oulad Teima", :aliases => "Oulad Teima,Oulad TeÃ¯ma,Ouled Teima,Oulad TeÃ¯ma", :latitude => "30.39467", :longitude => "-9.20897").save
City.new(:country_id => "139", :name => "Oujda", :aliases => "Oudja,Oudjda,Ouja,Oujda,Udzda,Udzhda,Wadzda,WadÅ¼da,wjdh,wjdt,Ð£Ð´Ð¶Ð´Ð°,Ð£ÑÐ´Ð°,ÙØ¬Ø¯Ø©,ÙØ¬Ø¯Ù,Oujda", :latitude => "34.68052", :longitude => "-1.90764").save
City.new(:country_id => "139", :name => "Oued Zem", :aliases => ",Oued Zem", :latitude => "32.8627", :longitude => "-6.57359").save
City.new(:country_id => "139", :name => "Ouazzane", :aliases => "Ouazzane,Quazzane,Uazan,UazÃ¡n,Wazzan,Ouazzane", :latitude => "34.79711", :longitude => "-5.58224").save
City.new(:country_id => "139", :name => "Ouarzazat", :aliases => "Ouarzazat,Ouarzazate,Ouarzazte,Ouorzazate,Uarzazatas,Varzazat,Warzazat,WarzÄzÄt,wrzazat,wrzzat,ÐÐ°ÑÐ·Ð°Ð·Ð°Ñ,ÙØ±Ø²Ø§Ø²Ø§Øª,ÙØ±Ø²Ø²Ø§Øª,Ouarzazat", :latitude => "30.91894", :longitude => "-6.89341").save
City.new(:country_id => "139", :name => "Nador", :aliases => "Nador,Nadoras,Villa Nador,alnazwr,nazwr,ÐÐ°Ð´Ð¾Ñ,Ø§ÙÙØ§Ø¸ÙØ±,ÙØ§Ø¸ÙØ±,Nador", :latitude => "35.17404", :longitude => "-2.92866").save
City.new(:country_id => "139", :name => "Mohammedia", :aliases => "Al Muhammadiyah,Al Muá¸©ammadÄ«yah,Fadalah,Faá¸Älah,Fdala,Fedala,Fedhala,Mohammadia,Mohammedia,Mokhammedija,Sedala,alhrawyyn,ÐÐ¾ÑÐ°Ð¼Ð¼ÐµÐ´Ð¸Ñ,Ø§ÙÙØ±Ø§ÙÙÙÙ,Mohammedia", :latitude => "33.70659", :longitude => "-7.39442").save
City.new(:country_id => "139", :name => "Midelt", :aliases => "Midelt,Midelt", :latitude => "32.6852", :longitude => "-4.74512").save
City.new(:country_id => "139", :name => "Meknes", :aliases => "Mekinez,Meknes,MeknÃ¨s,mei ke nei si,mekunesu,mknas,mqns,ÐÐµÐºÐ½ÐµÑ,××§× ×¡,ÙÙÙØ§Ø³,ÙÚ©ÙØ§Ø³,ã¡ã¯ãã¹,æ¢ååæ¯,MeknÃ¨s", :latitude => "33.89352", :longitude => "-5.54727").save
City.new(:country_id => "139", :name => "Mechra Belqsiri", :aliases => "Ksiri,Mechra Belqsiri,Mechra al Ksiri,Mechra-bel-Kairi,MechrÃ¡ Belqsiri,MechrÃ¡ Belqsiri", :latitude => "34.57396", :longitude => "-5.95372").save
City.new(:country_id => "139", :name => "Martil", :aliases => "Martil,Rio Martin,Rio Martine,RÃ­o MartÃ­n,Wad Martin,WÄd MartÄ«n,Martil", :latitude => "35.61662", :longitude => "-5.27522").save
City.new(:country_id => "139", :name => "Marrakech", :aliases => "Marakes,Marakesh,Marakeso,MarakeÅo,MarakeÅ¡,Maraksh,Marrakech,Marrakes,Marrakesch,Marrakesh,Marrakesz,Marraqueix,Marraquexe,MarrÃ queix,MarrÃ¡keÅ¡,Merrakex,Morocco City,ma la ke shen,marakeshu,mraksh,ÐÐ°ÑÐ°ÐºÐµÑ,ÐÐ°ÑÑÐ°ÐºÐµÑ,ÙØ±Ø§ÙØ´,ãã©ã±ã·ã¥,é©¬æåä»,Marrakech", :latitude => "31.63148", :longitude => "-8.00828").save
City.new(:country_id => "139", :name => "Larache", :aliases => "Al `Ara'ish,Al âArÄâÄ«sh,Al-Araisz,El Aaraich,Larache,Larasha,Laraxe,Lavache,ÐÐ°ÑÐ°ÑÐ°,Ø§ÙØ¹Ø±Ø§Ø¦Ø´,Ø¹Ø±Ø§Ø¦Ø´,Larache", :latitude => "35.19321", :longitude => "-6.15572").save
City.new(:country_id => "139", :name => "Ksar el Kebir", :aliases => "Alcazarquebir,Alcazarquivir,Alcazquivir,El Ksar El Kbir,El Ksar El Kebir,Ksar el Kebir,Ksar el Kebir", :latitude => "35.00174", :longitude => "-5.90534").save
City.new(:country_id => "139", :name => "Khouribga", :aliases => "Khouribga,Khouribja,Kouriga,Kourigha,khrybkt,Ø®Ø±ÙØ¨ÙØ©,Khouribga", :latitude => "32.88108", :longitude => "-6.9063").save
City.new(:country_id => "139", :name => "Khenifra", :aliases => "Khenifra,Khenifra", :latitude => "32.9391", :longitude => "-5.6686").save
City.new(:country_id => "139", :name => "Kenitra", :aliases => "Al Qunaytirah,Al QunayÅ£irah,Kenitra,Khenifra,KÃ©nitra,Lyautey,Mina Hassan Tani,Port Laoti,Port-Lyautey,Ville de Kenitra,alqnytrt,qnytrh,ÐÐµÐ½Ð¸ÑÑÐ°,Ø§ÙÙÙÙØ·Ø±Ø©,ÙÙÛØ·Ø±Ù,Kenitra", :latitude => "34.26101", :longitude => "-6.5802").save
City.new(:country_id => "139", :name => "Kasba Tadla", :aliases => "Kasba Tadla,Kasbah Tadla,Tadla,Kasba Tadla", :latitude => "32.5977", :longitude => "-6.26844").save
City.new(:country_id => "139", :name => "Jerada", :aliases => "Djerada,Dzherada,Jerada,ÐÐ¶ÐµÑÐ°Ð´Ð°,Jerada", :latitude => "34.31", :longitude => "-2.16").save
City.new(:country_id => "139", :name => "Imzourene", :aliases => "Ain Zoren,AÃ¯n ZorÃ¨n,Im Zouren,Imzourene,ImzoÃ»rene,ImzoÃ»rene", :latitude => "35.15", :longitude => "-3.86").save
City.new(:country_id => "139", :name => "Guercif", :aliases => "Garsif,Guercif,Guercif", :latitude => "34.22568", :longitude => "-3.35361").save
City.new(:country_id => "139", :name => "Guelmim", :aliases => "Goulimine,Guelmim,klmym,ÙÙÙÙÙ,Guelmim", :latitude => "28.98696", :longitude => "-10.05738").save
City.new(:country_id => "139", :name => "Fkih Ben Salah", :aliases => ",Fkih Ben Salah", :latitude => "32.50093", :longitude => "-6.69062").save
City.new(:country_id => "139", :name => "Fes", :aliases => "Fes,Fez,FÃ¨s,fas,fezu,Ð¤ÐµÑ,ÙØ§Ø³,ãã§ãº,FÃ¨s", :latitude => "34.03715", :longitude => "-4.9998").save
City.new(:country_id => "139", :name => "Essaouira", :aliases => "As Suwayrah,AÅ Åuwayrah,Ehs-Suvejra,Ehssuehjra,Es Suira,Essaouira,Magador,Mogadar,Mogador,alswyrt,swyrh,Ð­Ñ-Ð¡ÑÐ²ÐµÐ¹ÑÐ°,Ð­ÑÑÑÑÐ¹ÑÐ°,××¡××××¨×,Ø§ÙØµÙÙØ±Ø©,ØµÙÛØ±Ù,Essaouira", :latitude => "31.5125", :longitude => "-9.77").save
City.new(:country_id => "139", :name => "El Jadida", :aliases => "Al Jadida,Al Yadida,Ehl'-Dzhadida,El Jadida,El-Jadida,Mazagan,Mazagao,MazagÃ£o,aljdydh,aljdydt,Ð­Ð»Ñ-ÐÐ¶Ð°Ð´Ð¸Ð´Ð°,Ø§ÙØ¬Ø¯ÙØ¯Ø©,Ø§ÙØ¬Ø¯ÛØ¯Ù,Ø§ÙØ¬Ø¯ÛØ¯Û,El Jadida", :latitude => "33.25492", :longitude => "-8.50602").save
City.new(:country_id => "139", :name => "El Hajeb", :aliases => ",El Hajeb", :latitude => "33.68786", :longitude => "-5.371").save
City.new(:country_id => "139", :name => "El Aioun", :aliases => "Aioun Sidi Mellouk,Al 'Youn,Al âYoun,El Aioun,El Aioun Sidi Mellouk,El AÃ¯oun,El AÃ¯oun Sidi Mellouk,El AÃ¯oun", :latitude => "34.58319", :longitude => "-2.50612").save
City.new(:country_id => "139", :name => "Chefchaouene", :aliases => "Chaouen,ChaouÃ¨n,Chauen,Chechaouen,Chechaouene,ChechaouÃ¨n,Chefchaouen,Chefchaouene,Chichaouene,Ech Chaouene,Scheschauen,Ville de Chechaouen,Ville de ChechaouÃ¨n,Xauen,Xexauen,Chefchaouene", :latitude => "35.16878", :longitude => "-5.2636").save
City.new(:country_id => "139", :name => "Casablanca", :aliases => "Ad Dar al Bayda',Ad DÄr al Bayá¸Äâ,Anfa,Casa Branca,Casablanca,Dar-el-Beida,Ed Dar el Baida,Ed DÄr el Baida,Kasablanka,Kazablanka,Kazablanko,ka sa bu lan ka,ka sab langka,kasa blanka,kasabeullangka,kasaburanka,kazablanka,qzblnqh,ÐÐ°Ð·Ð°Ð±Ð»Ð°Ð½ÐºÐ°,ÐÐ°ÑÐ°Ð±Ð»Ð°Ð½ÐºÐ°,×§×××× ×§×,Ø§ÙØ¯Ø§Ø± Ø§ÙØ¨ÙØ¶Ø§Ø¡,Ú©Ø§Ø²Ø§Ø¨ÙØ§ÙÚ©Ø§,Ú©Ø§Ø³Ø§ Ø¨ÙØ§ÙÚ©Ø§,à¸à¸²à¸à¸²à¸à¸¥à¸±à¸à¸à¸²,ã«ãµãã©ã³ã«,å¡è¨å¸å°å¡,ì¹´ì¬ë¸ëì¹´,Casablanca", :latitude => "33.59278", :longitude => "-7.61916").save
City.new(:country_id => "139", :name => "Bouznika", :aliases => "Bouzhika,Bouznika,Bouzniqa,Buznike,Kasba bou Znika,ÐÑÐ·Ð½Ð¸ÐºÐµ,Bouznika", :latitude => "33.78942", :longitude => "-7.15968").save
City.new(:country_id => "139", :name => "Berkane", :aliases => "Berkan,Berkane,Berkawe,BerkÃ¡n,brkan,Ø¨Ø±ÙØ§Ù,Berkane", :latitude => "34.92", :longitude => "-2.32").save
City.new(:country_id => "139", :name => "Beni Mellal", :aliases => "Beni Mellal,Beni-Mellal',Beni-Mellal-Centre,bny mlal,ÐÐµÐ½Ð¸-ÐÐµÐ»Ð»Ð°Ð»Ñ,Ø¨ÙÙ ÙÙØ§Ù,Beni Mellal", :latitude => "32.33725", :longitude => "-6.34984").save
City.new(:country_id => "139", :name => "Berrechid", :aliases => "Barrechid,Berrechid,Bev-rechid,Berrechid", :latitude => "33.26553", :longitude => "-7.58754").save
City.new(:country_id => "139", :name => "Azrou", :aliases => "Azrou,Azrou", :latitude => "33.43443", :longitude => "-5.22126").save
City.new(:country_id => "139", :name => "Azemmour", :aliases => "Azemmour,Azimur,Azzegour,Azemmour", :latitude => "33.28952", :longitude => "-8.3425").save
City.new(:country_id => "139", :name => "Asilah", :aliases => "Arcila,Arcilas,Arsila,Arzila,Arzilah,ArzÄ«lah,Asila,Asilah,Asilakh,Augusta Zilil,Aá¹£Ä«la,Colonia Augusti Iulia Constantia Zilil,Ville d'Arcila,Ville dâArcila,asylt,sylt,ÐÑÐ¸Ð»Ð°Ñ,Ø£ØµÙÙØ©,ØµÙÙØ©,Asilah", :latitude => "35.46502", :longitude => "-6.0348").save
City.new(:country_id => "139", :name => "Khemisset", :aliases => "Al Khmissat,Khemisset,Kimisset,Khemisset", :latitude => "33.82404", :longitude => "-6.06627").save
City.new(:country_id => "139", :name => "Ahfir", :aliases => "Ahfir,Martimprey du Kiss,Ahfir", :latitude => "34.95368", :longitude => "-2.10027").save
City.new(:country_id => "139", :name => "Agadir", :aliases => "Agadair,Agadir,Agadir - akadyr,Agadir - Ø§ÙØ§Ø¯ÙØ±,Agadir Ighir,Irhir,Santa Cruz,a jia di er,agadiru,agadyr,akadyr,ÐÐ³Ð°Ð´Ð¸Ñ,ÐÐ³Ð°Ð´ÑÑ,Ø£ÙØ§Ø¯ÙØ±,Ø§Ú¯Ø§Ø¯ÛØ±,ã¢ã¬ãã£ã¼ã«,é¿å è¿ªå°,Agadir", :latitude => "30.42018", :longitude => "-9.59815").save
City.new(:country_id => "139", :name => "Skhirat", :aliases => "Ac Ckhirat,AÃ§ Ãkhirat,Kasba Skira,Minaret de Skhirat,Skhirat,Skhirate,Skhirat", :latitude => "33.84984", :longitude => "-7.04037").save
