City.new(:country_id => "141", :name => "Edinet", :aliases => "Edincy,Edinec,Edinet,EdineÅ£,Edinita,Edinita-Targ,Ediniti,EdiniÅ£a,EdiniÅ£a-TÃ¢rg,Yedintsy,Yedintsy-Tyrg,edinecheu,ÐÐ´Ð¸Ð½ÐµÑ,ÐÐ´Ð¸Ð½ÑÑ,ìëë¤ì¸ ,EdineÅ£", :latitude => "48.16806", :longitude => "27.305").save
City.new(:country_id => "141", :name => "Ungheni", :aliases => "Nyaradto,NyÃ¡rÃ¡dtÅ,Ukgeni Tyrg,Ungen,Ungen',Ungen' Tyrg,Ungeni,Ungeny,Ungenâ Tyrg,Ungheni,Ungheni Targ,Ð£Ð½Ð³ÐµÐ½Ñ,Ungheni", :latitude => "47.20417", :longitude => "27.79583").save
City.new(:country_id => "141", :name => "Tiraspol", :aliases => "Tiraspol,Tiraspol',Tiraspole,Tiraspoli,Tiraspolis,Tiraspolo,Tiraspolâ,Tyraspal',Tyraspol,tilaseupol,tirasupori,tyrspwl,Ð¢Ð¸ÑÐ°ÑÐ¿Ð¾Ð»,Ð¢Ð¸ÑÐ°ÑÐ¿Ð¾Ð»Ñ,Ð¢Ð¸ÑÐ°ÑÐ¿Ð¾Ñ,Ð¢ÑÑÐ°ÑÐ¿Ð°Ð»Ñ,×××¨×¡×¤××,ãã£ã©ã¹ããª,í°ë¼ì¤í´,Tiraspol", :latitude => "46.84028", :longitude => "29.64333").save
City.new(:country_id => "141", :name => "Straseni", :aliases => "Straseni,Strashen',Strashenskij rajon,Strasheny,Strashenâ,Stresheni,StrÄÅeni,Ð¡ÑÑÐ°ÑÐµÐ½ÑÐºÐ¸Ð¹ ÑÐ°Ð¹Ð¾Ð½,StrÄÅeni", :latitude => "47.14139", :longitude => "28.61028").save
City.new(:country_id => "141", :name => "Bilicenii Vechi", :aliases => "Belichany,Biliceni,Bilicenii Vechi,Bilichen',Bilicheni,Bilichenâ,Bliceni,Gilicheny,Staryye Bilicheny,Bilicenii Vechi", :latitude => "47.65639", :longitude => "28.04722").save
City.new(:country_id => "141", :name => "Soroca", :aliases => "Soroca,Soroka,Soroki,Ð¡Ð¾ÑÐ¾ÐºÐ°,Soroca", :latitude => "48.15583", :longitude => "28.2975").save
City.new(:country_id => "141", :name => "Slobozia", :aliases => "Moldavanskaya-Slobodzaya,Slobodzeya,Slobodzeya Moldavanskaya,Slobozia,Slobozia", :latitude => "46.72806", :longitude => "29.70778").save
City.new(:country_id => "141", :name => "Ribnita", :aliases => "Rabnita,Ribnica,Ribnicja,Ribnita,RibÅica,Rybnica,Rybnitsa,Rybniza,RÃ¢bniÅ£a,RÃ®bniÅ£a,rybnyzh,Ð Ð¸Ð±Ð½Ð¸ÑÑ,Ð ÑÐ±Ð½Ð¸ÑÐ°,×¨××× ××¦×,RÃ®bniÅ£a", :latitude => "47.76639", :longitude => "29.00111").save
City.new(:country_id => "141", :name => "Orhei", :aliases => "Orgeev,Orgeyev,Orhei,Orheiu,Orkhej,Orkhey,ÐÑÐ³ÐµÐµÐ²,ÐÑÑÐµÐ¹,Orhei", :latitude => "47.38306", :longitude => "28.82306").save
City.new(:country_id => "141", :name => "Causeni", :aliases => "Causani-Novi,Causanii-Noui,Causeni,CÄuÅani-Novi,CÄuÅanii-Noui,CÄuÅeni,Kaushani,Kaushani-Noui,Kaushany,Kehushan',Noui Causanii,Noui CÄuÅanii,Novo Kaushani,Novyye Kaushany,Novyye Keushani,ÐÐ°ÑÑÐ°Ð½Ñ,ÐÑÑÑÐ°Ð½Ñ,CÄuÅeni", :latitude => "46.64417", :longitude => "29.41389").save
City.new(:country_id => "141", :name => "Floresti", :aliases => "Floresht',Floreshti,Floreshty,Floreshtâ,Floresti,FloreÅti,Ð¤Ð»Ð¾ÑÐµÑÑÑ,FloreÅti", :latitude => "47.89333", :longitude => "28.30139").save
City.new(:country_id => "141", :name => "Dubasari", :aliases => "Dubasari,Dubehsar',Dubosari,Dubossary,DubÄsari,dubeosali,ÐÑÐ±Ð¾ÑÑÐ°ÑÑ,ÐÑÐ±ÑÑÐ°ÑÑ,ëë²ì¬ë¦¬,DubÄsari", :latitude => "47.26306", :longitude => "29.16083").save
City.new(:country_id => "141", :name => "Drochia", :aliases => "Drochia,Drokija,Drokiya,Drokiya Sat,ÐÑÐ¾ÐºÐ¸Ñ,Drochia", :latitude => "48.035", :longitude => "27.81611").save
City.new(:country_id => "141", :name => "Comrat", :aliases => "Comrat,Komrad,Komrat,komlateu,ÐÐ¾Ð¼ÑÐ°Ñ,ì½¤ë¼í¸,Comrat", :latitude => "46.30028", :longitude => "28.65722").save
City.new(:country_id => "141", :name => "Chisinau", :aliases => "Chisinau,Chisinau - Chisinau,Chisinau - ChiÅinÄu,ChiÅinÄu,Kischinew,Kiscinev,Kishinef,Kishinehu,Kishinev,Kishiniv,Kishinjov,KishinÃ«v,Kisinaou,Kisinev,Kisineva,Kisinevo,Kisiniovas,Kisinjev,Kisinov,Kisinyov,Kisyneu,Kiszyniow,KiszyniÃ³w,KiÅinevo,KiÅinev,KiÅ¡iniovas,KiÅ¡injev,KiÅ¡inÄv,KiÅ¡iÅeva,KiÅ¡iÅov,cisina'u,cisinau,ji xi ne wu,kishinau,kisineou,kyshynaw,ÎÎ¹ÏÎ¹Î½Î¬Î¿Ï,ÎÎ¹ÏÎ¹Î½Î±Î¿Ï,ÐÐ¸ÑÐ¸Ð½ÐµÐ²,ÐÐ¸ÑÐ¸Ð½ÑÑ,ÐÐ¸ÑÐ¸Ð½ÑÐ²,ÐÐ¸ÑÐ¸ÑÐµÐ²,ÐÑÑÑÐ½ÑÑ,Ô¿Õ«Õ·Õ«Õ¶ÕµÕ¸Õ¾,×§××©×× ××,ÙÙØ´ÙÙØ§Ù,à¤à¤¿à¤¶à¤¿à¤¨à¤¾à¤,à¤à¤¿à¤¶à¤¿à¤¨à¥,ááá¨áááááá,áªáºáá,ã­ã·ãã¦,åºå¸è®·ä¹,í¤ìëì°,ChiÅinÄu", :latitude => "47.00556", :longitude => "28.8575").save
City.new(:country_id => "141", :name => "Ceadir-Lunga", :aliases => "Ceadar-Lunga,Ceadir-Lunga,CeadÃ¢r-Lunga,CeadÃ®r-Lunga,Chadyr-Lunga,Ð§Ð°Ð´ÑÑ-ÐÑÐ½Ð³Ð°,CeadÃ®r-Lunga", :latitude => "46.055", :longitude => "28.83028").save
City.new(:country_id => "141", :name => "Cahul", :aliases => "Cahul,Kagul,Kakhul,ÐÐ°Ð³ÑÐ»,ÐÐ°ÑÑÐ»,Cahul", :latitude => "45.9075", :longitude => "28.19444").save
City.new(:country_id => "141", :name => "Tighina", :aliases => "Bendary,Bender,Benderai,Benderi,Bendery,Tighina,Tigina,tigina,tygynh,ÐÐµÐ½Ð´ÐµÑÐ¸,ÐÐµÐ½Ð´ÐµÑÑ,Ð¢Ð¸Ð³Ð¸Ð½Ð°,××××× ×,í°ê¸°ë,Tighina", :latitude => "46.83056", :longitude => "29.47111").save
City.new(:country_id => "141", :name => "Balti", :aliases => "Balti,Baltsy,Behlc',Bel'cy,Bel'tsy,Belcai,Belci,Beltsi,Belâtsy,Bielce,Byelcy,BÄlÅ£i,Municipalite de Balti,MunicipalitÃ© de BÄlÅ£i,blzy,ÐÐµÐ»ÑÐ¸,ÐÐµÐ»ÑÑÑ,ÐÑÐ»ÑÑ,×××¦×,BÄlÅ£i", :latitude => "47.76167", :longitude => "27.92889").save
