City.new(:country_id => "146", :name => "Zhelino", :aliases => "Zelino,Zeljino,Zheline,Zhelino,ZhelinÃ«,Å½eljino,ÐÐµÐ»Ð¸Ð½Ð¾,ÐÐµÐ»Ð¸Ð½Ð¾", :latitude => "41.98028", :longitude => "21.06417").save
City.new(:country_id => "146", :name => "Vinica", :aliases => "Vinica,ÐÐ¸Ð½Ð¸ÑÐ°,ÐÐ¸Ð½Ð¸ÑÐ°", :latitude => "41.88278", :longitude => "22.50917").save
City.new(:country_id => "146", :name => "Veles", :aliases => "Koprulu,KÃ¶prÃ¼lÃ¼,Titov Veles,Veles,Velessa,Weles,ÐÐµÐ»ÐµÑ,ÐÐµÐ»ÐµÑ", :latitude => "41.71556", :longitude => "21.77556").save
City.new(:country_id => "146", :name => "Tetovo", :aliases => "Kalkandelen,Qalqan Delen,Tetobo,Tetova,Tetovas,Tetove,Tetovo,TetovÃ«,Tetowo,Î¤Î­ÏÎ¿Î²Î¿,Ð¢ÐµÑÐ¾Ð²Ð¾,Ð¢ÐµÑÐ¾Ð²Ð¾", :latitude => "42.01056", :longitude => "20.97139").save
City.new(:country_id => "146", :name => "Tearce", :aliases => "Tearce,Ð¢ÐµÐ°ÑÑÐµ,Ð¢ÐµÐ°ÑÑÐµ", :latitude => "42.07444", :longitude => "21.0525").save
City.new(:country_id => "146", :name => "Studenichani", :aliases => "Studenicane,Studenichani,StudeniÄane,Ð¡ÑÑÐ´ÐµÐ½Ð¸ÑÐ°Ð½Ð¸,Ð¡ÑÑÐ´ÐµÐ½Ð¸ÑÐ°Ð½Ð¸", :latitude => "41.91583", :longitude => "21.53056").save
City.new(:country_id => "146", :name => "Strumica", :aliases => "Stromitza,Stromnitsa,Stromnitza,Stroumitsa,Strumica,Strumitsa,Strumitza,Ustrumcha,Ð¡ÑÑÑÐ¼Ð¸ÑÐ°,Strumica", :latitude => "41.4375", :longitude => "22.64333").save
City.new(:country_id => "146", :name => "Struga", :aliases => "Struga,Ustrugha,astrwga,Ð¡ÑÑÑÐ³Ð°,Ø§Ø³ØªØ±ÙÚ¯Ø§,Struga", :latitude => "41.17806", :longitude => "20.67611").save
City.new(:country_id => "146", :name => "Shtip", :aliases => "Ishtib,Istip,Shhip,Shtip,Stip,Stiplia,Ä°Åtip,Å tip,Ð¨ÑÐ¸Ð¿,Ð©Ð¸Ð¿,Ð¨ÑÐ¸Ð¿", :latitude => "41.74583", :longitude => "22.19583").save
City.new(:country_id => "146", :name => "Skopje", :aliases => "Scupi,Shkup,Shkupi,Skop'e,Skope,Skopeia,Skopia,Skopie,Skopiye,Skopje,Skopjo,SkopjÄ,Skople,Skoplie,Skoplje,Skopye,Szkopje,UEskuep,Uskub,UskÃ¼b,askwpyh,seukope,si ke pu li,skwbyh,sqwpyh,sukopie,ÃskÃ¼p,Î£ÎºÏÏÎ¹Î±,Ð¡ÐºÐ¾Ð¿'Ðµ,Ð¡ÐºÐ¾Ð¿Ðµ,Ð¡ÐºÐ¾Ð¿Ð¸Ðµ,Ð¡ÐºÐ¾Ð¿ÑÐµ,Ð¡ÐºÐ¾Ð¿ÑÐµ,Ð¡ÐºÐ¾Ð¿ÑÐµ,Ð¡ÑÐºÐ¾Ð¿Ð¸Ñ¥,ÕÕ¯Õ¸ÕºÕµÕ¥,×¡×§××¤××,Ø§Ø³Ú©ÙÙ¾ÛÙ,Ø³ÙÙØ¨ÙÙ,á¡ááááá,áµá®áá¬,ã¹ã³ãã¨,æ¯ç§æ®é,ì¤ì½í,Skopje", :latitude => "42", :longitude => "21.43333").save
City.new(:country_id => "146", :name => "Saraj", :aliases => "Saraj,Ð¡Ð°ÑÐ°Ð¹,Ð¡Ð°ÑÐ°Ñ,Ð¡Ð°ÑÐ°Ñ", :latitude => "42", :longitude => "21.32778").save
City.new(:country_id => "146", :name => "Resen", :aliases => "Resan,Resen,Resna,Ð ÐµÑÐµÐ½,Ð ÐµÑÐµÐ½", :latitude => "41.08889", :longitude => "21.01222").save
City.new(:country_id => "146", :name => "Radovish", :aliases => "Radovis,Radovish,Radoviste,RadoviÅ¡te,Rodovis,RodoviÅ¡,Ð Ð°Ð´Ð¾Ð²Ð¸Ñ,Ð Ð°Ð´Ð¾Ð²Ð¸Ñ", :latitude => "41.63833", :longitude => "22.46472").save
City.new(:country_id => "146", :name => "Prilep", :aliases => "Perlepe,Perlepes,PerlepÃ©,Pirlepe,Prilep,Prilepa,Prilepas,pirlepe,ÐÑÐ¸Ð»ÐµÐ¿,ÐÑÐ¸Ð»ÐµÐ¿", :latitude => "41.34639", :longitude => "21.55444").save
City.new(:country_id => "146", :name => "Ohrid", :aliases => "Akhris,Ochrida,Ochryda,Ohri,Ohrid,Okhri,Okhrid,awhryd,ÎÏÏÎ¯Î´Î±,ÐÑÑÐ¸Ð´,Ø§ÙÙØ±ÛØ¯,Ohrid", :latitude => "41.11722", :longitude => "20.80194").save
City.new(:country_id => "146", :name => "Negotino", :aliases => "Negotin,Negotino,Negotino-Poloshko,Negotino-Polosko,Negotino-PoloÅ¡ko,ÐÐµÐ³Ð¾ÑÐ¸Ð½Ð¾,ÐÐµÐ³Ð¾ÑÐ¸Ð½Ð¾-ÐÐ¾Ð»Ð¾ÑÐºÐ¾,ÐÐµÐ³Ð¾ÑÐ¸Ð½Ð¾", :latitude => "41.87861", :longitude => "20.88389").save
City.new(:country_id => "146", :name => "Negotino", :aliases => "Negotin,Negotin Vardarski,Negotino,ÐÐµÐ³Ð¾ÑÐ¸Ð½Ð¾,ÐÐµÐ³Ð¾ÑÐ¸Ð½Ð¾", :latitude => "41.48389", :longitude => "22.08917").save
City.new(:country_id => "146", :name => "Lipkovo", :aliases => "Lipkove,Lipkovo,LipkovÃ«,ÐÐ¸Ð¿ÐºÐ¾Ð²Ð¾,ÐÐ¸Ð¿ÐºÐ¾Ð²Ð¾", :latitude => "42.15639", :longitude => "21.58528").save
City.new(:country_id => "146", :name => "Kumanovo", :aliases => "Kumanova,Kumanovas,Kumanove,Kumanovo,KumanovÃ«,ÐÑÐ¼Ð°Ð½Ð¾Ð²Ð¾,Kumanovo", :latitude => "42.13222", :longitude => "21.71444").save
City.new(:country_id => "146", :name => "Kriva Palanka", :aliases => "Kriva Palanka,Palangha,ÐÑÐ¸Ð²Ð° ÐÐ°Ð»Ð°Ð½ÐºÐ°,ÐÑÐ¸Ð²Ð° ÐÐ°Ð»Ð°Ð½ÐºÐ°", :latitude => "42.20194", :longitude => "22.33194").save
City.new(:country_id => "146", :name => "Kochani", :aliases => "Kocane,Kocani,Kochani,KoÄane,KoÄani,ÐÐ¾ÑÐ°Ð½Ð¸,ÐÐ¾ÑÐ°Ð½Ð¸", :latitude => "41.91639", :longitude => "22.41278").save
City.new(:country_id => "146", :name => "Kicevo", :aliases => "Kicevo,Kichevo,KiÄevo,ÐÐ¸ÑÐµÐ²Ð¾,KiÄevo", :latitude => "41.51444", :longitude => "20.96333").save
City.new(:country_id => "146", :name => "Kavadarci", :aliases => "Kavadar,Kavadarci,Tikves,Tikvesh,TikveÅ¡,ÐÐ°Ð²Ð°Ð´Ð°ÑÑÐ¸,ÐÐ°Ð²Ð°Ð´Ð°ÑÑÐ¸", :latitude => "41.43306", :longitude => "22.01194").save
City.new(:country_id => "146", :name => "Kamenjane", :aliases => "Kamenane,Kamenjan,Kamenjane,ÐÐ°Ð¼ÐµÑÐ°Ð½Ðµ,Kamenjane", :latitude => "41.94444", :longitude => "20.92667").save
City.new(:country_id => "146", :name => "Gostivar", :aliases => "Gostivar,Gostivari,Kostovon,ÐÐ¾ÑÑÐ¸Ð²Ð°Ñ,ÐÐ¾ÑÑÐ¸Ð²Ð°Ñ", :latitude => "41.79722", :longitude => "20.90833").save
City.new(:country_id => "146", :name => "Gevgelija", :aliases => "Devdelijad,Gevegeli,Gevgeli,Gevgelia,Gevgelija,ÃevÄelijad,ÐÐµÐ²Ð³ÐµÐ»Ð¸Ñ,ÐÐµÐ²Ð³ÐµÐ»Ð¸ÑÐ°,ÐÐµÐ²Ð³ÐµÐ»Ð¸ÑÐ°", :latitude => "41.13917", :longitude => "22.5025").save
City.new(:country_id => "146", :name => "Delchevo", :aliases => "Carevo Selo,Delcevo,Delchevo,ÐÐµÐ»ÑÐµÐ²Ð¾,ÐÐµÐ»ÑÐµÐ²Ð¾", :latitude => "41.96722", :longitude => "22.76944").save
City.new(:country_id => "146", :name => "Debar", :aliases => "Bebar,Debar,Debur,Dibra,Dibre-i-Bala,debre,ÐÐµÐ±Ð°Ñ,ÐÐµÐ±ÑÑ,ÐÐµÐ±Ð°Ñ", :latitude => "41.525", :longitude => "20.5275").save
City.new(:country_id => "146", :name => "Brvenica", :aliases => "Bervenice,Brvence,Brvenica,BÃ«rvenicÃ«,ÐÑÐ²ÐµÐ½Ð¸ÑÐ°,Brvenica", :latitude => "41.96722", :longitude => "20.98083").save
City.new(:country_id => "146", :name => "Bogovinje", :aliases => "Bogovina,Bogovine,Bogovinje,Bogovino,ÐÐ¾Ð³Ð¾Ð²Ð¸ÑÐµ,Bogovinje", :latitude => "41.92361", :longitude => "20.91361").save
City.new(:country_id => "146", :name => "Bitola", :aliases => "Bitol,Bitola,Bitolj,Bitolja,Bitolya,Manastir,Manastiri,ManastÄ±r,Monasteri,Monasterium,Monasteron,Monastir,bitora,bytwla,ÎÎ¿Î½Î±ÏÏÎ®ÏÎ¹,ÐÐ¸ÑÐ¾Ð»Ð°,ÐÐ¸ÑÐ¾Ð»Ñ,ÐÐ¸ÑÐ¾Ñ,Ø¨ÛØªÙÙØ§,ããã©,ÐÐ¸ÑÐ¾Ð»Ð°", :latitude => "41.03111", :longitude => "21.34028").save
City.new(:country_id => "146", :name => "Ilinden", :aliases => "Belimbegovo,Ilinden,ÐÐ»Ð¸Ð½Ð´ÐµÐ½", :latitude => "41.99611", :longitude => "21.58222").save
City.new(:country_id => "146", :name => "Vinica", :aliases => "Venica,Vinica", :latitude => "41.52861", :longitude => "21.01389").save
