City.new(:country_id => "149", :name => "Ulaangom", :aliases => "ULANGOM,Ulaan Goom,Ulaanggom,Ulaangom,Ulaangom sumu,Ulan Kan,Ulangom,Ulankom,Wu-lan-ku-mu,Ð£ÐÐÐÐÐÐ,Ð£Ð»Ð°Ð°Ð½Ð³Ð¾Ð¼,Ð£Ð»Ð°Ð½Ð³Ð¾Ð¼,Ulaangom", :latitude => "49.98111", :longitude => "92.06667").save
City.new(:country_id => "149", :name => "OElgiy", :aliases => "Bayan-Ulegey,Olgii,Ologey,Ul'gey,Ulegei,Ulegey,Ulegy,Ulgij,ÃlÃ¶gey,Ð£Ð»Ð³Ð¸Ð¹,Ó¨Ð»Ð³Ð¸Ð¹,Ãlgiy", :latitude => "48.96833", :longitude => "89.9625").save
City.new(:country_id => "149", :name => "Hovd", :aliases => "Chirgalantu,Chzhirgalantu,Djirgalantu,Dund-Us,Dzhaghalantu,Dzhargalantu,Dzhirgalantu,Hobdo,Hobdo Gol,Hovd,Jargalant,Jirgalanta,Jirgalantu,K'o-pu-to,Khobdo,Khovd,Kobdo,Kâo-pu-to,ÐÐ¾Ð±Ð´Ð¾,Ð¥Ð¾Ð²Ð´,Hovd", :latitude => "48.00556", :longitude => "91.64194").save
City.new(:country_id => "149", :name => "Ulaanbaatar", :aliases => "Da Huryee,Da HÃ¼ryee,Da Khure,Da-Kure,K'u-lun,Orgoo,Oulan Mpator,Oulan-Bator,Ourga,Ulaan Baatar Hoto,Ulaanbaatar,Ulaanbaator,Ulaanbaator hota,Ulaanbaatur,Ulan Bator,Ulan Bator - Ulaanbaatar,Ulan Bator Hoto,Ulan Batoras,Ulan Batur,Ulan-Bator,Ulan-Bator Khoto,Ulan-Batoro,Ulanbatar,Ulanbator,UlÃ¡n Bator,UlÃ¡n BÃ¡tor - Ð£Ð»Ð°Ð°Ð½Ð±Ð°Ð°ÑÐ°Ñ,UlÃ¡nbÃ¡tar,UlÃ¡nbÃ¡tor,Uranbatoru,Urga,Uruga,UÅan Bator,awlan batwr,ulanabatara,ullanbatoleu,uranbatoru,wu lan ba tuo,xulanbatxr,ÃrgÃ¶Ã¶,ÎÏÎ»Î¬Î½ ÎÏÎ±ÏÏÏ,Ð£Ð»Ð°Ð°Ð½Ð±Ð°Ð°ÑÐ°Ñ,Ð£Ð»Ð°Ð½ ÐÐ°ÑÐ¾Ñ,Ð£Ð»Ð°Ð½-ÐÐ°ÑÐ¾Ñ,×××× ××××¨,Ø£ÙÙØ§Ù Ø¨Ø§ØªÙØ±,Ø§ÙÙØ§ÙâØ¨Ø§ØªÙØ±,à¤à¤²à¤¾à¤¨à¤¬à¤¾à¤¤à¤°,à¸­à¸¹à¸¥à¸²à¸à¸à¸²à¸à¸­à¸£à¹,à½à½´à¼à½£à½à¼à½à¼à½à½´à½¢,á¡ááá á£áá³á­,ã¦ã©ã³ãã¼ãã«,ä¹å°å·´æ,ì¸ëë°í ë¥´,Ulaanbaatar", :latitude => "47.90771", :longitude => "106.88324").save
City.new(:country_id => "149", :name => "Suhbaatar", :aliases => "Suehbaatar,Suhbaatar,Suhe Baatar,Suhe Batar,Sukhbaatar,Sukhe Batur,Sukhe-Bator,Sukheh-Bator,SÃ¼hbaatar,SÃ¼he Baatar,SÃ¼he Batar,SÃ¼khbaatar,Ð¡ÑÑÑ-ÐÐ°ÑÐ¾Ñ,Ð¡Ò¯ÑÐ±Ð°Ð°ÑÐ°Ñ,SÃ¼hbaatar", :latitude => "50.23139", :longitude => "106.20778").save
City.new(:country_id => "149", :name => "Murun-kuren", :aliases => "MUREHN,Moeroen,Moron,Moron'i hurie,Moronii Huryee,Moronii khuree,Moronu hurie,Mu-lin,Mu-lin-fu-lieh,Murehn,Muren,Murenfure,Muringoru,Murun-kuren,MÃ¶rÃ¶n,MÃ¶rÃ¶nii HÃ¼ryee,MÃ¶rÃ¶nii khÃ¼ree,MÃ¶rÃ¶nu hurie,MÃ¶rÃ¶nâi hÃ¼rie,ÐÐ£Ð Ð­Ð,ÐÑÑÑÐ½,ÐÓ©ÑÓ©Ð½,Murun-kuren", :latitude => "49.63417", :longitude => "100.1625").save
City.new(:country_id => "149", :name => "Mandalgovi", :aliases => "Dund-gobi,Mandal Gobi,Mandalgov',Mandalgovi,MandalgovÄ­,Mandalgow',Mandalgowâ,ÐÐ°Ð½Ð´Ð°Ð»Ð³Ð¾Ð²Ñ,MandalgovÄ­", :latitude => "45.7625", :longitude => "106.27083").save
City.new(:country_id => "149", :name => "Hovd", :aliases => "Bogd,Khovd,Ð¥Ð¾Ð²Ð´,Hovd", :latitude => "44.67024", :longitude => "102.17491").save
City.new(:country_id => "149", :name => "Erdenet", :aliases => "Ehrdehneht,Ehrdehneht khot,Ehrdenet,Erdenet,e er deng te,eleudeneteu,Ð­ÑÐ´ÐµÐ½ÐµÑ,Ð­ÑÐ´ÑÐ½ÑÑ,Ð­ÑÐ´ÑÐ½ÑÑ ÑÐ¾Ñ,××¨×× ×,é¢å°ç»ç¹,ìë¥´ë°ë¤í¸,Erdenet", :latitude => "49.03333", :longitude => "104.08333").save
City.new(:country_id => "149", :name => "Dzuunharaa", :aliases => "DZUNKHARA,Dzueuenharaa,Dzuunkharaa,DzÃ¼Ã¼nharaa,DzÃ¼Ã¼nkharaa,ÐÐÐ£ÐÐ¥ÐÐ Ð,DzÃ¼Ã¼nharaa", :latitude => "48.85229", :longitude => "106.45786").save
City.new(:country_id => "149", :name => "Darhan", :aliases => "Darchan,Darhan,Darkhan,da er han,ÐÐ°ÑÑÐ°Ð½,××¨×××,è¾¾å°æ±,Darhan", :latitude => "49.48667", :longitude => "105.92278").save
City.new(:country_id => "149", :name => "Dalandzadgad", :aliases => "Dalan Dsadagad,Dalan Dzadagad,Dalan Tszadagad,Dalan Tzadagad,Dalan-Zadagad,Dalandzadgad,Dalanzadgad,Daranzagatai,Dzadagad,Ta-lan-ken-kuo-lo,Ta-leng-keng Miao,ÐÐ°Ð»Ð°Ð½Ð·Ð°Ð´Ð³Ð°Ð´,Dalandzadgad", :latitude => "43.57083", :longitude => "104.425").save
City.new(:country_id => "149", :name => "Saynshand", :aliases => "Buyant-Uhaa,Dalai Sain Shanda,Dalay Sayn Shanda,Darai Sain Shanda,Sain Shanda,Sain-Shand,Sajnshand,Sayn Shanda,Sayn-Shenda,Ð¡Ð°Ð¹Ð½ÑÐ°Ð½Ð´,Saynshand", :latitude => "44.88239", :longitude => "110.11631").save
City.new(:country_id => "149", :name => "Bulgan", :aliases => "BULGAN,Bulagan,Bulagan Suma,Bulagan Sumu,Bulagan somon,Bulagan-khan,Bulgan,Bulgan Han,ÐÐ£ÐÐÐÐ,ÐÑÐ»Ð³Ð°Ð½,Bulgan", :latitude => "48.8125", :longitude => "103.53472").save
City.new(:country_id => "149", :name => "Bayanhongor", :aliases => "Bajankhongor,Bayan Hangor,Bayan Hongor Suma,Bayan Khongor,Bayan Khongor Somon,Bayan Khonkhor Sume,Bayan honhor sumu,Bayan-hongoru,Bayanhongor,ÐÐ°ÑÐ½ÑÐ¾Ð½Ð³Ð¾Ñ,Bayanhongor", :latitude => "46.71667", :longitude => "100.11667").save
City.new(:country_id => "149", :name => "Baruun-Urt", :aliases => "Baruun Urta,Baruun-Urt,Burunurt,Dzhapkhalanta-sharga,Dzhibkhalantu-Sharga,Jibhalanta Sharga Suma,Jibholantu Sharga sumu,Jibhulantu sharga,Sharga Sume,ÐÐ°ÑÑÑÐ½-Ð£ÑÑ,Baruun-Urt", :latitude => "46.68056", :longitude => "113.27917").save
City.new(:country_id => "149", :name => "Zuunmod", :aliases => ",ÐÑÑÐ½Ð¼Ð¾Ð´", :latitude => "47.70693", :longitude => "106.95276").save
