City.new(:country_id => "181", :name => "Zyrardow", :aliases => "Zyrardow,Å»yrardÃ³w,Å»yrardÃ³w", :latitude => "52.0488", :longitude => "20.44599").save
City.new(:country_id => "181", :name => "Zielonka", :aliases => "ZELENKA,Zielonka,ÐÐÐÐÐÐÐ,Zielonka", :latitude => "52.30376", :longitude => "21.16018").save
City.new(:country_id => "181", :name => "Zamosc", :aliases => "Zamosc,Zamosc',Zamosca,Zamoscia,Zamose,Zamost'ye,Zamostâye,ZamoÅÄ,ÐÐ°Ð¼Ð¾ÑÑÑ,ZamoÅÄ", :latitude => "50.72314", :longitude => "23.25196").save
City.new(:country_id => "181", :name => "Zambrow", :aliases => "ZAMBRUV,Zambrov,Zambrow,ZambrÃ³w,ÐÐÐÐÐ Ð£Ð,ZambrÃ³w", :latitude => "52.9855", :longitude => "22.24319").save
City.new(:country_id => "181", :name => "Zabki", :aliases => "ZOMBKI,Zabki,ZÄbki,ÐÐÐÐÐÐ,ZÄbki", :latitude => "52.28333", :longitude => "21.11667").save
City.new(:country_id => "181", :name => "Wyszkow", :aliases => "VYSHKUV,Vyshkov,Wyszkow,WyszkÃ³w,ÐÐ«Ð¨ÐÐ£Ð,WyszkÃ³w", :latitude => "52.59278", :longitude => "21.4584").save
City.new(:country_id => "181", :name => "Wolomin", :aliases => "VOLOMIN,Wolomin,WoÅomin,ÐÐÐÐÐÐÐ,WoÅomin", :latitude => "52.34006", :longitude => "21.24207").save
City.new(:country_id => "181", :name => "Wieliczka", :aliases => "Velichka,Velicka,VeÄ¼iÄka,Wieliczka,ÐÐµÐ»Ð¸ÑÐºÐ°,Wieliczka", :latitude => "49.98738", :longitude => "20.06473").save
City.new(:country_id => "181", :name => "Warsaw", :aliases => "Barsobia,VARSHAVA,Varsa,Varsava,Varsavia,Varsavja,Varshava,Varshavae,Varshovija,Varsja,VarsjÃ¡,Varso,Varsova,Varsovia,Varsovia - Warszawa,Varsovie,Varsovio,Varssavi,Varsuva,VarsÃ²via,VarsÃ³,VarsÃ³via,VarÅova,VarÅovia,VarÅ¡ava,VarÅ¡uva,VÃ¡rsÃ¡,Warsaw,Warsawa,Warschau,Warskou,Warszawa,WarÅ¡awa,baleusyaba,hua sha,varshava,vorso,warsw,warushawa,wrsh,wrshw,wrsw,wxrsx,ÎÎ±ÏÏÎ¿Î²Î¯Î±,ÐÐÐ Ð¨ÐÐÐ,ÐÐ°ÑÑÐ°Ð²Ã¦,ÐÐ°ÑÑÐ°Ð²Ð°,ÐÐ°ÑÑÐ¾Ð²Ð¸Ñ,ÕÕ¡ÖÕ·Õ¡Õ¾Õ¡,××××¨×©×¢,××¨×©×,×°×Ö·×¨×©×¢,ÙØ§Ø±Ø³Ù,ÙØ±Ø´Ù,ÛØ§Ø±Ø´Ø§ÛØ§,ÜÜªÜ£Ü,à¤µà¥à¤°à¥à¤¸à¥,à¸§à¸­à¸£à¹à¸à¸­,ááá á¨ááá,áá­á¶á,ã¯ã«ã·ã£ã¯,åæ²,è¯æ²,ë°ë¥´ì¤ë°,Warsaw", :latitude => "52.22977", :longitude => "21.01178").save
City.new(:country_id => "181", :name => "Tomaszow Mazowiecki", :aliases => "Tomashuv-Mazovecki,Tomasova Mazovecka,Tomaszow,Tomaszow Mazowiecki,TomaszÃ³w,TomaszÃ³w Mazowiecki,TomaÅ¡ova Mazovecka,Ð¢Ð¾Ð¼Ð°ÑÑÐ²-ÐÐ°Ð·Ð¾Ð²ÐµÑÐºÐ¸,TomaszÃ³w Mazowiecki", :latitude => "51.53131", :longitude => "20.00855").save
City.new(:country_id => "181", :name => "Tomaszow Lubelski", :aliases => "Tomashev,Tomashuv,Tomashuv-Ljubel'ski,Tomaszow,TomaszÃ³w,Tomoshuv Lyubel'ski,Ð¢Ð¾Ð¼Ð°ÑÑÐ²-ÐÑÐ±ÐµÐ»ÑÑÐºÐ¸,TomaszÃ³w Lubelski", :latitude => "50.44767", :longitude => "23.41616").save
City.new(:country_id => "181", :name => "Tarnow", :aliases => "Tarnov,Tarnova,Tarnow,Tarnuv,TarnÃ³w,tarunufu,Ð¢Ð°ÑÐ½ÑÐ²,ã¿ã«ãã,TarnÃ³w", :latitude => "50.01381", :longitude => "20.98698").save
City.new(:country_id => "181", :name => "Tarnobrzeg", :aliases => "Tarnobrzeg,Tarnobzega,Tarnobzhege,TarnobÅ¾ega,Ð¢Ð°ÑÐ½Ð¾Ð±Ð¶ÐµÐ³Ðµ,Tarnobrzeg", :latitude => "50.57304", :longitude => "21.67937").save
City.new(:country_id => "181", :name => "Szczytno", :aliases => "Ortel'sberg,Ortelsburg,Ortelâsberg,Shhitno,Szczytno,Szczyton,Ð©Ð¸ÑÐ½Ð¾,Szczytno", :latitude => "53.56667", :longitude => "21").save
City.new(:country_id => "181", :name => "Swidnik", :aliases => "Swidnik,Swidnik Duzy,Åwidnik,Åwidnik DuÅ¼y,Åwidnik", :latitude => "51.21898", :longitude => "22.69621").save
City.new(:country_id => "181", :name => "Suwalki", :aliases => "SUVALKI,Suvalkai,Suvalki,Suwalki,Suwalkie,SuwaÅki,Ð¡Ð£ÐÐÐÐÐ,SuwaÅki", :latitude => "54.11175", :longitude => "22.93087").save
City.new(:country_id => "181", :name => "Sulejowek", :aliases => ",SulejÃ³wek", :latitude => "52.25221", :longitude => "21.26902").save
City.new(:country_id => "181", :name => "Staszow", :aliases => "Stashev,StaszÃ³w", :latitude => "50.56307", :longitude => "21.16593").save
City.new(:country_id => "181", :name => "Starachowice", :aliases => "Starachowice,Starachowice-Wierzbnik,Starahovice,Starachowice", :latitude => "51.0374", :longitude => "21.07126").save
City.new(:country_id => "181", :name => "Stalowa Wola", :aliases => "Stalova Vola,Stalowa Wola,Stalowa Wola", :latitude => "50.58286", :longitude => "22.05334").save
City.new(:country_id => "181", :name => "Sokolow Podlaski", :aliases => "Sokolow,Sokolow Podlaski,Sokoluv-Podljaski,SokoÅÃ³w,SokoÅÃ³w Podlaski,Ð¡Ð¾ÐºÐ¾Ð»ÑÐ²-ÐÐ¾Ð´Ð»ÑÑÐºÐ¸,SokoÅÃ³w Podlaski", :latitude => "52.40677", :longitude => "22.25307").save
City.new(:country_id => "181", :name => "Sokolka", :aliases => "SOKULKA,Sokola,Sokolka,Sokulka,SokÃ³Åka,Ð¡ÐÐÐ£ÐÐÐ,SokÃ³Åka", :latitude => "53.41667", :longitude => "23.5").save
City.new(:country_id => "181", :name => "Sochaczew", :aliases => "Sokhachev,Ð¡Ð¾ÑÐ°ÑÐµÐ²,Sochaczew", :latitude => "52.22944", :longitude => "20.23838").save
City.new(:country_id => "181", :name => "Skierniewice", :aliases => "Skernevice,Skernevitsy,Skieniewice,Skiernievice,Skierniewice,Ð¡ÐºÐµÑÐ½ÐµÐ²Ð¸ÑÐµ,Skierniewice", :latitude => "51.95485", :longitude => "20.15837").save
City.new(:country_id => "181", :name => "Skarzysko-Kamienna", :aliases => "Kamenna-Skarzhisko,Kamienna-Skarzhisko,Skarzhisko-Kamenna,Skarzysko,Skarzysko-Kamienna,SkarÅ¼ysko-Kamienna,Ð¡ÐºÐ°ÑÐ¶Ð¸ÑÐºÐ¾-ÐÐ°Ð¼ÐµÐ½Ð½Ð°,SkarÅ¼ysko-Kamienna", :latitude => "51.11311", :longitude => "20.87162").save
City.new(:country_id => "181", :name => "Siemiatycze", :aliases => "Semjatiche,Semyatichi,Siemiatycze,Sjamjatychy,Ð¡ÐµÐ¼ÑÑÐ¸ÑÐµ,Ð¡ÑÐ¼ÑÑÑÑÑ,Siemiatycze", :latitude => "52.45", :longitude => "22.88333").save
City.new(:country_id => "181", :name => "Siedlce", :aliases => "SEDL'CE,Sedl'ce,Sedl'tse,Sedlce,Siedlce,Ð¡ÐÐÐÐ¬Ð¦Ð,Ð¡ÐµÐ´Ð»ÑÑÐµ,Siedlce", :latitude => "52.16772", :longitude => "22.29006").save
City.new(:country_id => "181", :name => "Sanok", :aliases => "Sanok,Sjanok,Sunok,SÃ¡nÃ³k,Ð¡ÑÐ½Ð¾Ðº,Sanok", :latitude => "49.55573", :longitude => "22.2056").save
City.new(:country_id => "181", :name => "Sandomierz", :aliases => "Sandomer,Sandomierz,Sandomir,SandomÄÅ,Ð¡Ð°Ð½Ð´Ð¾Ð¼Ð¸Ñ,Sandomierz", :latitude => "50.68265", :longitude => "21.74898").save
City.new(:country_id => "181", :name => "Rzeszow", :aliases => "Reichshof,Resov,Resovia,Rzeszow,RzeszÃ³w,Zesova,Zheshev,Zheshuv,jeshufu,ÅeÅ¡ov,Å½eÅ¡ova,ÐÐµÑÑÐ²,ã¸ã§ã·ã¥ã,RzeszÃ³w", :latitude => "50.04132", :longitude => "21.99901").save
City.new(:country_id => "181", :name => "Ropczyce", :aliases => "Ropczyce,Ropczyce", :latitude => "50.05229", :longitude => "21.60891").save
City.new(:country_id => "181", :name => "Rawa Mazowiecka", :aliases => "Rawa,Rawa Mazowiecka,Rawa Mazowiecka", :latitude => "51.76437", :longitude => "20.25493").save
City.new(:country_id => "181", :name => "Radzyn Podlaski", :aliases => "Radzyn,Radzyn Podlaski,RadzyÅ,RadzyÅ Podlaski,RadzyÅ Podlaski", :latitude => "51.78333", :longitude => "22.61667").save
City.new(:country_id => "181", :name => "Radom", :aliases => "Radom,Radoma,la duo mu,Ð Ð°Ð´Ð¾Ð¼,×¨××××,æå¤å§,Radom", :latitude => "51.40253", :longitude => "21.14714").save
City.new(:country_id => "181", :name => "Pultusk", :aliases => "PULTUSK,Pultusk,PuÅtusk,ÐÐ£ÐÐ¢Ð£Ð¡Ð,ÐÑÐ»ÑÑÑÐº,PuÅtusk", :latitude => "52.7025", :longitude => "21.08276").save
City.new(:country_id => "181", :name => "Pulawy", :aliases => "Pulavy,Pulawy,Putawy,PuÅawy,puwavu~i,ÐÑÐ»Ð°Ð²Ñ,ãã¯ã´ã£,PuÅawy", :latitude => "51.41655", :longitude => "21.96939").save
City.new(:country_id => "181", :name => "Przeworsk", :aliases => "Przeworsk,Pshevors'k,ÐÑÐµÐ²Ð¾ÑÑÑÐº,Przeworsk", :latitude => "50.05912", :longitude => "22.49408").save
City.new(:country_id => "181", :name => "Przemysl", :aliases => "Peremishl',Peremishlâ,Peremyshl',Peremyshlâ,Przemysl,PrzemyÅl,Pshemys'l',Pshemysâlâ,ÐÐµÑÐµÐ¼Ð¸ÑÐ»Ñ,ÐÐµÑÐµÐ¼ÑÑÐ»Ñ,PrzemyÅl", :latitude => "49.78498", :longitude => "22.76728").save
City.new(:country_id => "181", :name => "Przasnysz", :aliases => "PSHASNYSH,Przasnysz,Pshasnysh,ÐÐ¨ÐÐ¡ÐÐ«Ð¨,Przasnysz", :latitude => "53.01907", :longitude => "20.88029").save
City.new(:country_id => "181", :name => "Pruszkow", :aliases => "Prushkov,Pruskova,Pruszkow,PruszkÃ³w,PruÅ¡kova,ÐÑÑÑÐºÐ¾Ð²,PruszkÃ³w", :latitude => "52.17072", :longitude => "20.81214").save
City.new(:country_id => "181", :name => "Plonsk", :aliases => "PLON'SK,Plonsk,Plonska,PÅoÅsk,plwnsq,ÐÐÐÐÐ¬Ð¡Ð,ÐÐ»Ð¾Ð½ÑÐº,×¤××× ×¡×§,PÅoÅsk", :latitude => "52.62348", :longitude => "20.37552").save
City.new(:country_id => "181", :name => "Pisz", :aliases => "Janowa Gora,Johannisburg,PISH,Pisz,ÐÐÐ¨,Pisz", :latitude => "53.63333", :longitude => "21.8").save
City.new(:country_id => "181", :name => "Pionki", :aliases => "Pionki,Pionki", :latitude => "51.47604", :longitude => "21.44995").save
City.new(:country_id => "181", :name => "Piastow", :aliases => ",PiastÃ³w", :latitude => "52.18435", :longitude => "20.83952").save
City.new(:country_id => "181", :name => "Piaseczno", :aliases => "PJASECHNO,Piaseczno,Pjasechno,ÐÐ¯Ð¡ÐÐ§ÐÐ,ÐÑÐ°ÑÐµÑÐ½Ð¾,Piaseczno", :latitude => "52.0814", :longitude => "21.02397").save
City.new(:country_id => "181", :name => "Otwock", :aliases => "Otvock,Otvotsk,Otwock,ÐÑÐ²Ð¾ÑÐº,Otwock", :latitude => "52.10577", :longitude => "21.26129").save
City.new(:country_id => "181", :name => "Ostrow Mazowiecka", :aliases => "Ostrov-Mazovetskiy,Ostrow,Ostrow Mazowiecka,Ostrow Mazowiecki,Ostruv-Mazovecka,OstrÃ³w,OstrÃ³w Mazowiecka,OstrÃ³w Mazowiecki,ÐÑÑÑÑÐ²-ÐÐ°Ð·Ð¾Ð²ÐµÑÐºÐ°,OstrÃ³w Mazowiecka", :latitude => "52.80245", :longitude => "21.89507").save
City.new(:country_id => "181", :name => "Ostrowiec Swietokrzyski", :aliases => "Ostroveca Sventoksiska,Ostroveca SventokÅ¡iska,Ostrovets,Ostrowiec,Ostrowiec Swietokrzyski,Ostrowiec ÅwiÄtokrzyski,Ostrowiec ÅwiÄtokrzyski", :latitude => "50.92936", :longitude => "21.38525").save
City.new(:country_id => "181", :name => "Ostroleka", :aliases => "OSTROLENKA,Ostroleka,Ostrolenka,OstroÅÄka,osutorou~enka,ÐÐ¡Ð¢Ð ÐÐÐÐÐÐ,ãªã¹ãã­ã¦ã§ã³ã«,OstroÅÄka", :latitude => "53.08333", :longitude => "21.56667").save
City.new(:country_id => "181", :name => "Opoczno", :aliases => "Opochno,Opoczno,ÐÐ¿Ð¾ÑÐ½Ð¾,Opoczno", :latitude => "51.37569", :longitude => "20.27827").save
City.new(:country_id => "181", :name => "Olsztyn", :aliases => "Allenshteyn,Allenstein,Ol'shtyn,Olsztyn,ÐÐ»ÑÑÑÑÐ½,Olsztyn", :latitude => "53.78333", :longitude => "20.48333").save
City.new(:country_id => "181", :name => "Olecko", :aliases => "Marggrabowa,Margrabowa,OLECKO,Olecko,Oletzko,Treuburg,ÐÐÐÐ¦ÐÐ,Olecko", :latitude => "54.03374", :longitude => "22.50704").save
City.new(:country_id => "181", :name => "Nowy Targ", :aliases => "Novi Targa,Novy Targ,Novy Targas,Novy-Targ,Novyy Targ,NovÃ½ Targ,Nowy Targ,ÐÐ¾Ð²Ñ-Ð¢Ð°ÑÐ³,áááá á¢áá áá,Nowy Targ", :latitude => "49.47783", :longitude => "20.03228").save
City.new(:country_id => "181", :name => "Nowy Sacz", :aliases => "Neu Sandez,Neu-Sandec,Novi Sonca,Novi SonÄa,Novy-Sonch,Novyy Sandets,Novyy Sonch,Nowy Sacz,Nowy SÄcz,Ujszandec,Ãjszandec,ãã´ã£ã»ã½ã³ã,Nowy SÄcz", :latitude => "49.62177", :longitude => "20.69705").save
City.new(:country_id => "181", :name => "Nowy Dwor Mazowiecki", :aliases => "Novy Dvor,Novy-Dvur-Mazovecki,Nowy Dwor,Nowy DwÃ³r,ÐÐ¾Ð²Ñ-ÐÐ²ÑÑ-ÐÐ°Ð·Ð¾Ð²ÐµÑÐºÐ¸,Nowy DwÃ³r Mazowiecki", :latitude => "52.43022", :longitude => "20.71652").save
City.new(:country_id => "181", :name => "Nisko", :aliases => "Nisko,Nisko", :latitude => "50.51987", :longitude => "22.13968").save
City.new(:country_id => "181", :name => "Mragowo", :aliases => "Mrongovo,Sensburg,Zadzbork,Å¹adzbork,ÐÑÐ¾Ð½Ð³Ð¾Ð²Ð¾,MrÄgowo", :latitude => "53.86437", :longitude => "21.30507").save
City.new(:country_id => "181", :name => "Mlawa", :aliases => "MLAVA,Mlava,Mlawa,MÅawa,ÐÐÐÐÐ,MÅawa", :latitude => "53.11278", :longitude => "20.3841").save
City.new(:country_id => "181", :name => "Minsk Mazowiecki", :aliases => "Min'sk-Mazovecki,Minsk,Minsk Mazowiecki,Minsk-Mazovetskiy,MiÅsk Mazowiecki,ÐÐ¸Ð½ÑÑÐº-ÐÐ°Ð·Ð¾Ð²ÐµÑÐºÐ¸,MiÅsk Mazowiecki", :latitude => "52.17935", :longitude => "21.57251").save
City.new(:country_id => "181", :name => "Milanowek", :aliases => "MILJANUVEK,Milanowek,MilanÃ³wek,ÐÐÐÐ¯ÐÐ£ÐÐÐ,MilanÃ³wek", :latitude => "52.11879", :longitude => "20.67155").save
City.new(:country_id => "181", :name => "Mielec", :aliases => "Melec,Meleca,Melets,Mielec,ÐÐµÐ»ÐµÑ,Mielec", :latitude => "50.28709", :longitude => "21.4239").save
City.new(:country_id => "181", :name => "Miedzyrzec Podlaski", :aliases => "Mendzizeca Podlaska,MendziÅ¾eca PodÄ¼aska,Mendzyzhec-Podljaski,Meserici,Mezhirech'ye,Mezhirechâye,Miedzyrzec,Miedzyrzec Podlaski,MiÄdzyrzec,MiÄdzyrzec Podlaski,Mjendzizhec-Podlaski,Palenkes Mendzizecas,PalenkÄs MendziÅ¾ecas,miengjijecheupodeullaseuki,mytsyrzyk bwdlasky,ÐÐµÐ½Ð´Ð·Ð¸Ð¶ÐµÑÑ ÐÑÐ´Ð»ÑÑÑÐºÐ¸Ð¹,ÐÐµÐ½Ð´Ð·ÑÐ¶ÐµÑ-ÐÐ¾Ð´Ð»ÑÑÐºÐ¸,ÐÑÐµÐ½Ð´Ð·Ð¸Ð¶ÐµÑ-ÐÐ¾Ð´Ð»Ð°ÑÐºÐ¸,ÙÙØªØ³ÙØ±Ø²ÙÙ Ø¨ÙØ¯ÙØ§Ø³ÙÙ,ë¯¸ì¥ì§ì ì¸ í¬ë¤ë¼ì¤í¤,MiÄdzyrzec Podlaski", :latitude => "51.98333", :longitude => "22.78333").save
City.new(:country_id => "181", :name => "Marki", :aliases => "MARKI,Marki,ÐÐÐ ÐÐ,Marki", :latitude => "52.32065", :longitude => "21.10474").save
City.new(:country_id => "181", :name => "Lukow", :aliases => "Lukov,Lukow,Lukuv,ÅukÃ³w,ÐÑÐºÑÐ²,ÅukÃ³w", :latitude => "51.91667", :longitude => "22.38333").save
City.new(:country_id => "181", :name => "Lublin", :aliases => "Liublinas,Ljublin,Lublin,Lublina,Lublino,Lyublin,lublini,lwblyn,ruburin,Ä»ubÄ¼ina,ÐÑÐ±Ð»Ð¸Ð½,ÐÑÐ±Ð»Ð¸Ð½,ÐÑÐ±Ð»ÑÐ½,××××××,áá£ááááá,ã«ããªã³,Lublin", :latitude => "51.25", :longitude => "22.56667").save
City.new(:country_id => "181", :name => "Lubartow", :aliases => "Lubartow,LubartÃ³w,Lyubartov,LubartÃ³w", :latitude => "51.46026", :longitude => "22.60952").save
City.new(:country_id => "181", :name => "Lomza", :aliases => "Lomza,Lomzha,LomÅ¾a,u~omuja,ÅomÅ¼a,ÐÐ¾Ð¼Ð¶Ð°,ã¦ã©ã ã¸ã£,ÅomÅ¼a", :latitude => "53.17806", :longitude => "22.05935").save
City.new(:country_id => "181", :name => "Lomianki", :aliases => "Lomianki,Åomianki,Åomianki", :latitude => "52.33413", :longitude => "20.88602").save
City.new(:country_id => "181", :name => "Lidzbark Warminski", :aliases => "Heilsberg,Heilsburg,Kheyl'sberg,LIDZBARK-VARMIN'SKI,Licbark,Lidzbark Warminski,Lidzbark WarmiÅski,Lidzbark-Varmin'ski,ÐÐÐÐÐÐÐ Ð-ÐÐÐ ÐÐÐÐ¬Ð¡ÐÐ,ÐÐ¸Ð´Ð·Ð±Ð°ÑÐº-ÐÐ°ÑÐ¼Ð¸Ð½ÑÑÐºÐ¸,Lidzbark WarmiÅski", :latitude => "54.12588", :longitude => "20.57954").save
City.new(:country_id => "181", :name => "Legionowo", :aliases => "Jablonna-Legionowo,JabÅonna-Legionowo,Legionova,Legionovo,Legionowo,ÐÐµÐ³Ð¸Ð¾Ð½Ð¾Ð²Ð¾,Legionowo", :latitude => "52.4", :longitude => "20.93333").save
City.new(:country_id => "181", :name => "Leczna", :aliases => "Leczna,ÅÄczna,ÅÄczna", :latitude => "51.30121", :longitude => "22.88135").save
City.new(:country_id => "181", :name => "Lapy", :aliases => "LAPY,Lapy,Zieciuki,ZiÄciuki,Åapy,ÐÐÐÐ«,Åapy", :latitude => "52.98333", :longitude => "22.86667").save
City.new(:country_id => "181", :name => "Lancut", :aliases => "Lancut,ÅaÅcut,ÅaÅcut", :latitude => "50.06871", :longitude => "22.22912").save
City.new(:country_id => "181", :name => "Krosno", :aliases => "Krosno,ÐÑÐ¾ÑÐ½Ð¾,Krosno", :latitude => "49.68333", :longitude => "21.78333").save
City.new(:country_id => "181", :name => "Krasnystaw", :aliases => "Krasnostav,Krasnystaw,Krasnystaw", :latitude => "50.98464", :longitude => "23.1742").save
City.new(:country_id => "181", :name => "Krasnik", :aliases => "Krasnik,KraÅnik,ÐÑÐ°ÑÐ½Ð¸Ðº,KraÅnik", :latitude => "50.9236", :longitude => "22.22706").save
City.new(:country_id => "181", :name => "Kozienice", :aliases => "Kozenitse,Kozienice,Kozienice", :latitude => "51.58294", :longitude => "21.54779").save
City.new(:country_id => "181", :name => "Konstancin-Jeziorna", :aliases => "KONSTANCIN-EZERNA,Konstancin-Jeziorna,Skolimow-Konstancin,SkolimÃ³w-Konstancin,ÐÐÐÐ¡Ð¢ÐÐÐ¦ÐÐ-ÐÐÐÐ ÐÐ,Konstancin-Jeziorna", :latitude => "52.0938", :longitude => "21.11761").save
City.new(:country_id => "181", :name => "Konskie", :aliases => "Kon'ske,Konsk,Konskie,KoÅskie,ÐÐ¾Ð½ÑÑÐºÐµ,KoÅskie", :latitude => "51.19166", :longitude => "20.40607").save
City.new(:country_id => "181", :name => "Kobylka", :aliases => ",KobyÅka", :latitude => "52.33953", :longitude => "21.19589").save
City.new(:country_id => "181", :name => "Kielce", :aliases => "Kel'ce,Kel'tsy,Kelce,Kielce,kyerutsu~e,ÐÐµÐ»ÑÐµ,ÐÐµÐ»ÑÑÐµ,ã­ã§ã«ãã§,Kielce", :latitude => "50.87033", :longitude => "20.62752").save
City.new(:country_id => "181", :name => "Ketrzyn", :aliases => "Ketrzyn,Ketzyn,KÄtrzyn,Rastembork,Rastenburg,KÄtrzyn", :latitude => "54.07676", :longitude => "21.37527").save
City.new(:country_id => "181", :name => "Kabaty", :aliases => "Kabaty,Kabaty", :latitude => "52.13012", :longitude => "21.08148").save
City.new(:country_id => "181", :name => "Jozefow", :aliases => ",JÃ³zefÃ³w", :latitude => "52.13707", :longitude => "21.23589").save
City.new(:country_id => "181", :name => "Jedrzejow", :aliases => "Yendzheyev,JÄdrzejÃ³w", :latitude => "50.63945", :longitude => "20.30454").save
City.new(:country_id => "181", :name => "Jaslo", :aliases => "Jaslo,Jasto,JasÅo,Yaslo,Ð¯ÑÐ»Ð¾,JasÅo", :latitude => "49.74506", :longitude => "21.47252").save
City.new(:country_id => "181", :name => "Jaroslaw", :aliases => "Jaroslau,Jaroslav,Jaroslaw,JarosÅaw,Yaroslav,Ð¯ÑÐ¾ÑÐ»Ð°Ð²,JarosÅaw", :latitude => "50.01623", :longitude => "22.67776").save
City.new(:country_id => "181", :name => "Hrubieszow", :aliases => "Grubeshev,Grubeshov,Grubeshuv,Hrubieszow,HrubieszÃ³w,Khrubeshuv,HrubieszÃ³w", :latitude => "50.80502", :longitude => "23.89251").save
City.new(:country_id => "181", :name => "Hajnowka", :aliases => "Hajnowka,HajnÃ³wka,KHAJNUVKA,Ð¥ÐÐÐÐ£ÐÐÐ,HajnÃ³wka", :latitude => "52.73333", :longitude => "23.58333").save
City.new(:country_id => "181", :name => "Grodzisk Mazowiecki", :aliases => "Grodzisk,Grodzisk Mazowiecki,Grodzisk-Mazovecki,Grodzisk-Mazovetskiy,ÐÑÐ¾Ð´Ð·Ð¸ÑÐº-ÐÐ°Ð·Ð¾Ð²ÐµÑÐºÐ¸,Grodzisk Mazowiecki", :latitude => "52.10387", :longitude => "20.6337").save
City.new(:country_id => "181", :name => "Grajewo", :aliases => "Graevo,Grajewo,ÐÑÐ°ÐµÐ²Ð¾,Grajewo", :latitude => "53.64728", :longitude => "22.45537").save
City.new(:country_id => "181", :name => "Gorlice", :aliases => "Gorlice,ÐÐ¾ÑÐ»Ð¸ÑÐµ,×××¨×××¥,Gorlice", :latitude => "49.65563", :longitude => "21.16035").save
City.new(:country_id => "181", :name => "Gizycko", :aliases => "GIZHICKO,Gizycko,GiÅ¼ycko,Lec,Lettsen,Lotzen,Luczany,Lutsany,LÃ«ttsen,LÃ¶tzen,Åuczany,ÐÐÐÐÐ¦ÐÐ,GiÅ¼ycko", :latitude => "54.0425", :longitude => "21.76944").save
City.new(:country_id => "181", :name => "Gierloz", :aliases => "Gierloz,GierÅoÅ¼,Gorlitz,GÃ¶rlitz,GierÅoÅ¼", :latitude => "54.08333", :longitude => "21.48333").save
City.new(:country_id => "181", :name => "Garwolin", :aliases => "Garvolin,Garwolin,Garwolin", :latitude => "51.89747", :longitude => "21.61466").save
City.new(:country_id => "181", :name => "Elk", :aliases => "Elk,Elka,EÅk,Lik,Lyck,EÅk", :latitude => "53.82824", :longitude => "22.36469").save
City.new(:country_id => "181", :name => "Dzialdowo", :aliases => "DZJALDOVO,Dzialdowo,DziaÅdowo,Soldau,ÐÐÐ¯ÐÐÐÐÐ,DziaÅdowo", :latitude => "53.23333", :longitude => "20.18333").save
City.new(:country_id => "181", :name => "Deblin", :aliases => "Demblin,DÄblin", :latitude => "51.55912", :longitude => "21.84829").save
City.new(:country_id => "181", :name => "Debica", :aliases => "Debica,Dembitsa,DÄbica,DÄbica", :latitude => "50.05146", :longitude => "21.41141").save
City.new(:country_id => "181", :name => "Ciechanow", :aliases => "CEKHANUV,Ciechanow,CiechanÃ³w,Tsekhanov,Ð¦ÐÐ¥ÐÐÐ£Ð,CiechanÃ³w", :latitude => "52.88141", :longitude => "20.61996").save
City.new(:country_id => "181", :name => "Chelm", :aliases => "Chelm,CheÅm,Helma,Khelm,Kholm,hlm,Ð¥ÐµÐ»Ð¼,Ð¥Ð¾Ð»Ð¼,×××,CheÅm", :latitude => "51.14312", :longitude => "23.4716").save
City.new(:country_id => "181", :name => "Busko-Zdroj", :aliases => "Busk,Busko,Busko Zdroj,Busko ZdrÃ³j,Busko-Zdroj,Busko-Zdruj,Busko-ZdrÃ³j,ÐÑÑÐºÐ¾-ÐÐ´ÑÑÑ,Busko-ZdrÃ³j", :latitude => "50.47078", :longitude => "20.71884").save
City.new(:country_id => "181", :name => "Brzesko", :aliases => "Brzesko,Brzesko", :latitude => "49.96911", :longitude => "20.60606").save
City.new(:country_id => "181", :name => "Bochnia", :aliases => "Bochnia,Bohna,Bokhnja,Bokhnya,ÐÐ¾ÑÐ½Ñ,ÐÐ¾ÑÑÐ°,Bochnia", :latitude => "49.96905", :longitude => "20.43028").save
City.new(:country_id => "181", :name => "Bilgoraj", :aliases => "Bilgora,Bilgoraj,Bilgoraja,Bilgoray,BiÅgora,BiÅgoraj,ÐÐ¸Ð»Ð³Ð¾ÑÐ°Ð¹,ÐÐ¸Ð»Ð³Ð¾ÑÐ°Ñ,BiÅgoraj", :latitude => "50.54114", :longitude => "22.72204").save
City.new(:country_id => "181", :name => "Bielsk Podlaski", :aliases => "Bel'sk-Podljaski,Bielsk,Bielsk Podlaski,Podlaski,ÐÐµÐ»ÑÑÐº-ÐÐ¾Ð´Ð»ÑÑÐºÐ¸,Bielsk Podlaski", :latitude => "52.76512", :longitude => "23.18647").save
City.new(:country_id => "181", :name => "Bialystok", :aliases => "Balstoge,BalstogÄ,Belastok,Belostok,Belostoko,Bialystok,BiaÅystok,Bjalistok,Bjalistoka,Bjalistoko,Bjelostock,Byelostok,biawiseutokeu,byau~isutoku,ÐÐµÐ»Ð°ÑÑÐ¾Ðº,ÐÐµÐ»Ð¾ÑÑÐ¾Ðº,ÐÑÐ»Ð¸ÑÑÐ¾Ðº,××××××¡×××§,ãã£ã¦ã£ã¹ãã¯,ë¹ììì¤í í¬,BiaÅystok", :latitude => "53.13333", :longitude => "23.15").save
City.new(:country_id => "181", :name => "Biala Podlaska", :aliases => "Biala Podlaska,BiaÅa Podlaska,Bjala Podlaska,Bjala PodÄ¼aska,Bjala-Podljaska,ÐÑÐ»Ð°-ÐÐ¾Ð´Ð»ÑÑÐºÐ°,BiaÅa Podlaska", :latitude => "52.03238", :longitude => "23.11652").save
City.new(:country_id => "181", :name => "Bartoszyce", :aliases => "BARTOSHICE,Bartenstein,Bartoshice,Bartoszyce,ÐÐÐ Ð¢ÐÐ¨ÐÐ¦Ð,ÐÐ°ÑÑÐ¾ÑÐ¸ÑÐµ,Bartoszyce", :latitude => "54.25354", :longitude => "20.80819").save
City.new(:country_id => "181", :name => "Augustow", :aliases => "AVGUSTOV,Augustavas,Augustov,Augustow,AugustÃ³w,Avgustov,ÐÐÐÐ£Ð¡Ð¢ÐÐ,ÐÑÐ³ÑÑÑÐ¾Ð²,AugustÃ³w", :latitude => "53.84321", :longitude => "22.97979").save
City.new(:country_id => "181", :name => "Zywiec", :aliases => "Saybusch,Zwyiec,Zywiec,Å»ywiec,Å»ywiec", :latitude => "49.68529", :longitude => "19.19243").save
City.new(:country_id => "181", :name => "Zory", :aliases => "Sohrau,Zhory,Zori,Zory,Å»ory,Å½ori,Å½ory,ÐÐ¾ÑÑ,Å»ory", :latitude => "50.04523", :longitude => "18.70062").save
City.new(:country_id => "181", :name => "Zlotow", :aliases => "Flatow,ZÅotÃ³w", :latitude => "53.36346", :longitude => "17.04082").save
City.new(:country_id => "181", :name => "Zlotoryja", :aliases => "Aurimontium,Goldberg,Goldberg in Schlesien,Slotoryja,SÅotoryja,Zlota Gora,Zlotoryja,ZÅota GÃ³ra,ZÅotoryja,ZÅotoryja", :latitude => "51.12637", :longitude => "15.91979").save
City.new(:country_id => "181", :name => "Zielona Gora", :aliases => "Gruentberg,Grunberg,GrÃ¼nberg,Zelona Gura,ZeÄ¼ona Gura,Zielona Gora,Zielona GÃ³ra,lu shan cheng,ã¸ã§ã­ãã»ã°ã©,ç¶ å±±å,Zielona GÃ³ra", :latitude => "51.93548", :longitude => "15.50643").save
City.new(:country_id => "181", :name => "Zgorzelec", :aliases => "Gorlitz,GÃ¶rlitz,Zgorzelec,Zgorzelice,Zgozhelec,ÐÐ³Ð¾Ð¶ÐµÐ»ÐµÑ,Zgorzelec", :latitude => "51.14942", :longitude => "15.00835").save
City.new(:country_id => "181", :name => "Zgierz", :aliases => "Zgeza,Zgezh,ZgeÅ¾a,Zgierz,ÐÐ³ÐµÐ¶,Zgierz", :latitude => "51.85561", :longitude => "19.40623").save
City.new(:country_id => "181", :name => "Zdunska Wola", :aliases => "Zdunska Wola,ZduÅska Wola,ZduÅska Wola", :latitude => "51.59915", :longitude => "18.93974").save
City.new(:country_id => "181", :name => "Zawiercie", :aliases => "Zaverce,Zavertse,Zawiercie,ÐÐ°Ð²ÐµÑÑÐµ,Zawiercie", :latitude => "50.48766", :longitude => "19.41679").save
City.new(:country_id => "181", :name => "Zary", :aliases => "Sorau in Nieder Lausitz,Soraw,Zary,Zhara,Zoraw,ZÃ³raw,Å»ary,ÐÐ°ÑÐ°,Å»ary", :latitude => "51.64205", :longitude => "15.13727").save
City.new(:country_id => "181", :name => "Zakopane", :aliases => "Zakopane,zakopane,ÐÐ°ÐºÐ¾Ð¿Ð°Ð½Ðµ,×××§××¤× ×,ã¶ã³ãã,Zakopane", :latitude => "49.29899", :longitude => "19.94885").save
City.new(:country_id => "181", :name => "Zagan", :aliases => "Sagan,Saganum,Zagan,Zagan',Zegan,ZegaÅ,Zhagan',jagani,Å»agaÅ,ÐÐ°Ð³Ð°Ð½Ñ,ÐÐ°Ð³Ð°Ñ,ÐÐ°Ð³Ð°Ð½Ñ,ã¸ã£ã¬ã,Å»agaÅ", :latitude => "51.61759", :longitude => "15.31486").save
City.new(:country_id => "181", :name => "Zabrze", :aliases => "Hindenburg,Zaborze,Zabrze,Zabze,Zabzhe,ZabÅ¾e,ÐÐ°Ð±Ð¶Ðµ,Zabrze", :latitude => "50.32492", :longitude => "18.78576").save
City.new(:country_id => "181", :name => "Zabkowice Slaskie", :aliases => "Frankenstein,Frankenstein in Schlesien,Zabkowice,Zabkowice Slaskie,Zabkowice Szlascze,ZÄbkowice SzlÄsczÃ©,ZÄbkowice ÅlÄskie,ZÄbkowice ÅlÄskie", :latitude => "50.58969", :longitude => "16.81239").save
City.new(:country_id => "181", :name => "Wrzesnia", :aliases => "Vzhes'nya,Vzhesânya,Wreschen,Wrzesnia,WrzeÅnia,WrzeÅnia", :latitude => "52.32512", :longitude => "17.56519").save
City.new(:country_id => "181", :name => "Wroclaw", :aliases => "Brassel,Breslau,Breslavia,Breslavl',Breslavlâ,Vratislav,Vratislavia,Vroclav,Vroclava,Vroclavas,Vroclavo,Vrotslav,Wroclaw,Wroclow,WrocÅaw,WrocÅow,Wroslaw,WrosÅaw,beulocheuwapeu,fu luo ci wa fu,vurotsuwafu,wrwzlb,ÐÑÐ¾ÑÐ»Ð°Ð²,××¨××¦××,ã´ã­ãã¯ã,å¼ç½è¨ç¦å¤«,ë¸ë¡ì¸ ìí,WrocÅaw", :latitude => "51.1", :longitude => "17.03333").save
City.new(:country_id => "181", :name => "Wodzislaw Slaski", :aliases => "Wodislaw-Slaski,WodisÅaw-ÅlÄski,Wodzislaw,Wodzislaw Slaski,WodzisÅaw,WodzisÅaw ÅlÄski,WodzisÅaw ÅlÄski", :latitude => "50.00377", :longitude => "18.47205").save
City.new(:country_id => "181", :name => "Wloclawek", :aliases => "Leslau,VLOCLAVEK,Vloclavek,Vloclaveka,Wloclawek,WÅocÅawek,ÐÐÐÐ¦ÐÐÐÐÐ,ÐÐ»Ð¾ÑÐ»Ð°Ð²ÐµÐº,WÅocÅawek", :latitude => "52.64817", :longitude => "19.0678").save
City.new(:country_id => "181", :name => "Wielun", :aliases => "Velun,Velun',Velyun',Weilun,Wielun,WieluÅ,ÐÐµÐ»ÑÐ½Ñ,WieluÅ", :latitude => "51.22097", :longitude => "18.56964").save
City.new(:country_id => "181", :name => "Wejherowo", :aliases => "Neustadt,VEJKHEROVO,Veykherovo,Weiherowo,Wejherowo,Wejrowo,WejrowÃ²,ÐÐÐÐ¥ÐÐ ÐÐÐ,Wejherowo", :latitude => "54.60568", :longitude => "18.23559").save
City.new(:country_id => "181", :name => "Walcz", :aliases => "Deutsch Krone,Walcz,WaÅcz,WaÅcz", :latitude => "53.27787", :longitude => "16.47122").save
City.new(:country_id => "181", :name => "Walbrzych", :aliases => "Valbzhikh,Valbziha,ValbÅ¾iha,Walbrzych,Waldenburg,Waldenburg in Schlesien,WaÅbrzych,wa wu bu ri he,ÐÐ°Ð»Ð±Ð¶Ð¸Ñ,ç¦çå¸æ¥èµ«,WaÅbrzych", :latitude => "50.76667", :longitude => "16.28333").save
City.new(:country_id => "181", :name => "Wagrowiec", :aliases => "Eichenbruck,EichenbrÃ¼ck,Vongrovec,Wagrowiec,WÄgrowiec,ÐÐ¾Ð½Ð³ÑÐ¾Ð²ÐµÑ,WÄgrowiec", :latitude => "52.80842", :longitude => "17.19961").save
City.new(:country_id => "181", :name => "Wadowice", :aliases => "Bantobitse,Vadovice,Wadowice,badobiche,vu~adovu~itsu~e,wdwbyz',ÎÎ±Î½ÏÎ¿Î²Î¯ÏÏÎµ,ÐÐ°Ð´Ð¾Ð²Ð¸ÑÐµ,××××××¥',ã´ã¡ãã´ã£ãã§,ë°ëë¹ì²´,Wadowice", :latitude => "49.88335", :longitude => "19.49292").save
City.new(:country_id => "181", :name => "Ustron", :aliases => "Ustron,UstroÅ,UstroÅ", :latitude => "49.71667", :longitude => "18.8").save
City.new(:country_id => "181", :name => "Ustka", :aliases => "Stolpmunde,StolpmÃ¼nde,Ustka,wu si te ka,ä¹æ¯ç¹å¡,Ustka", :latitude => "54.58048", :longitude => "16.86194").save
City.new(:country_id => "181", :name => "Tychy", :aliases => "Tichau,Tihi,Tychy,Tychy", :latitude => "50.13333", :longitude => "18.98333").save
City.new(:country_id => "181", :name => "Turek", :aliases => "TUREK,Turek,Ð¢Ð£Ð ÐÐ,Turek", :latitude => "52.01548", :longitude => "18.50055").save
City.new(:country_id => "181", :name => "Trzebinia", :aliases => "Trzebinia,Trzebinia", :latitude => "50.15931", :longitude => "19.46966").save
City.new(:country_id => "181", :name => "Trzcianka", :aliases => "Kreisstadt Schonlanke,Kreisstadt SchÃ¶nlanke,Schonlanke,SchÃ¶nlanke,Trzcianka,Trzcianka", :latitude => "53.04063", :longitude => "16.45628").save
City.new(:country_id => "181", :name => "Torun", :aliases => "Thorn,Torun,Torun',Toruna,Torune,ToruÅ,ToruÅa,ToruÅ,TorÅ«nÄ,torun,tuo lun,Ð¢Ð¾ÑÑÐ½,Ð¢Ð¾ÑÑÐ½Ñ,ãã«ã³,æä¼¦,ToruÅ", :latitude => "53.01375", :longitude => "18.59814").save
City.new(:country_id => "181", :name => "Tczew", :aliases => "Derszewo,Dirschau,DÃ«rszewÃ²,TCHEV,Tceva,Tcevas,Tchev,Tczew,TÄeva,TÄevas,Ð¢Ð§ÐÐ,Tczew", :latitude => "54.09242", :longitude => "18.77787").save
City.new(:country_id => "181", :name => "Tarnowskie Gory", :aliases => "Tarnowitz,Tarnowskie Gory,Tarnowskie GÃ³ry,Tarnowskie GÃ³ry", :latitude => "50.44548", :longitude => "18.86147").save
City.new(:country_id => "181", :name => "Szczecinek", :aliases => "Neustettin,Neustettiu,Shhecinek,Szczecinek,Ð©ÐµÑÐ¸Ð½ÐµÐº,Szczecinek", :latitude => "53.70791", :longitude => "16.69937").save
City.new(:country_id => "181", :name => "Szczecin", :aliases => "Estetino,Scecin,Scecina,Scecinas,Secin,Shchechin,Shchehcyn,Shhecin,Stetin,Stettin,Stettino,Szczecin,Szteteno,SztetÃ«no,shen qie qing,shuchechin,syuchechin,Å tetÃ­n,Å tÄtÃ­n,Å Äecina,Å Äecinas,Ð¨ÑÐµÑÐ¸Ð½,Ð¨ÑÐµÑÐ¸Ð½,Ð¨ÑÑÑÑÐ½,Ð¨ÑÑÑÑÐ½,Ð©ÐµÑÐ¸Ð½,Ð©ÐµÑÑÐ½,ã·ã¥ãã§ãã³,ä»åé,ìì²´ì¹,Szczecin", :latitude => "53.42894", :longitude => "14.55302").save
City.new(:country_id => "181", :name => "Szamotuly", :aliases => "Samter,Shamotuly,Szamotuly,SzamotuÅy,shamoto~uu~i,ã·ã£ã¢ãã¥ã¦ã£,SzamotuÅy", :latitude => "52.61201", :longitude => "16.57794").save
City.new(:country_id => "181", :name => "Swinoujscie", :aliases => "Sbinooustsie,Svinoujs'ce,Svioujscie,Swienemuenn,SwienemÃ¼nn,Swina,Swinemude,Swinemunde,SwinemÃ¼de,SwinemÃ¼nde,Swinioujscie,Swinmunde,Swinoujscie,ÅwinoujÅcie,Î£Î²Î¹Î½ÏÎ¿ÏÏÏÏÎ¹Îµ,Ð¡Ð²Ð¸Ð½Ð¾ÑÐ¹ÑÑÑÐµ,Ð¡Ð²Ð¸Ð¾ÑÐ¹ÑÑÐ¸Ðµ,ÅwinoujÅcie", :latitude => "53.91053", :longitude => "14.24712").save
City.new(:country_id => "181", :name => "Swietochlowice", :aliases => "Sbietochlobitse,Schweintochlitz,Schwientochlowitz,Shvientokhlovice,Sventochlovice,SventochlovicÄ,Sventohlovice,Sventokhlovice,Svetohlovice,Svjentokhlovice,Svjetohlovice,Swietochlowice,ashfyntwhwytz,shfyntwkhwfytsh,shifientofuu~ovu~itsu~e,xi wei tuo he luo wei cai,ÅwiÄtochÅowice,Å vetohlovice,Î£Î²Î¹ÎµÏÎ¿ÏÎ»ÏÎ²Î¹ÏÏÎµ,Ð¡Ð²ÐµÐ½ÑÐ¾ÑÐ»Ð¾Ð²Ð¸ÑÐµ,Ð¡Ð²ÐµÐ½ÑÐ¾ÑÐ»Ð¾Ð²ÑÑÐµ,Ð¡Ð²ÑÐµÐ½ÑÐ¾ÑÐ»Ð¾Ð²Ð¸ÑÐµ,Ð¨Ð²Ð¸ÐµÐ½ÑÐ¾ÑÐ»Ð¾Ð²Ð¸ÑÐµ,Ø§Ø´ÙÛÙØªÙÙÙÛØªØ²,Ø´ÙÙÙØªÙØ®ÙÙÙØªØ³Ù,ã·ãã£ã¨ã³ããã¦ã©ã´ã£ãã§,å¸ç»´æèµ«æ´ç»´é,ÅwiÄtochÅowice", :latitude => "50.29636", :longitude => "18.91726").save
City.new(:country_id => "181", :name => "Swiebodzin", :aliases => "Schweibus,Schwiebus,Svebodzin,Ð¡Ð²ÐµÐ±Ð¾Ð´Ð·Ð¸Ð½,Åwiebodzin", :latitude => "52.24751", :longitude => "15.53355").save
City.new(:country_id => "181", :name => "Swiecie", :aliases => "Schwetz,Swiecie,Åwiecie,Åwiecie", :latitude => "53.40953", :longitude => "18.44742").save
City.new(:country_id => "181", :name => "Swiebodzice", :aliases => "Freiburg,Freiburg in Schlesien,Frybork,Svebodzice,Swiebodzice,Åwiebodzice,Ð¡Ð²ÐµÐ±Ð¾Ð´Ð·Ð¸ÑÐµ,Åwiebodzice", :latitude => "50.86667", :longitude => "16.33333").save
City.new(:country_id => "181", :name => "Swidwin", :aliases => "Schivelbein,Swibowina,Swidwin,Åwidwin,Åwidwin", :latitude => "53.77464", :longitude => "15.77671").save
City.new(:country_id => "181", :name => "Swidnica", :aliases => "Schweidnitz,Schweidnitz-Schlesian,Schweinitz,Svidnica,Swidnica,Åwidnica,Å vidÅica,Ð¡Ð²Ð¸Ð´Ð½Ð¸ÑÐ°,Åwidnica", :latitude => "50.84378", :longitude => "16.48859").save
City.new(:country_id => "181", :name => "Swarzedz", :aliases => "Swarzedz,SwarzÄdz,SwarzÄdz", :latitude => "52.41289", :longitude => "17.08503").save
City.new(:country_id => "181", :name => "Sulechow", :aliases => "Cylichow,CylichÃ³w,Sulechow,SulechÃ³w,Zullichau,ZÃ¼llichau,SulechÃ³w", :latitude => "52.08362", :longitude => "15.62513").save
City.new(:country_id => "181", :name => "Strzelce Opolskie", :aliases => "Gross Strehlitz,Gross Strohlitz,Strehlitz,Strzelce,Strzelce Opolskie,Stshel'ce-Opol'ske,Ð¡ÑÑÐµÐ»ÑÑÐµ-ÐÐ¿Ð¾Ð»ÑÑÐºÐµ,Strzelce Opolskie", :latitude => "50.5107", :longitude => "18.30056").save
City.new(:country_id => "181", :name => "Strzegom", :aliases => "Striegau,Strzegom,Strzyglow,StrzygÅow,Strzegom", :latitude => "50.96264", :longitude => "16.35006").save
City.new(:country_id => "181", :name => "Starogard Gdanski", :aliases => "Starogard,Starogard Gdanski,Starogard GdaÅski,Starogard-Gdan'ski,Ð¡ÑÐ°ÑÐ¾Ð³Ð°ÑÐ´-ÐÐ´Ð°Ð½ÑÑÐºÐ¸,Starogard GdaÅski", :latitude => "53.96396", :longitude => "18.52638").save
City.new(:country_id => "181", :name => "Stargard Szczecinski", :aliases => "Stargard,Stargard Shchechin'ski,Stargard Shchechinski,Stargard Szczecinski,Stargard SzczeciÅski,Stargard-Shhecin'ski,Stargarda Scecinska,Stargarda Å ÄeciÅska,Stargardia,Starnkarnt Setsetsinski,Starogrod,Storgard,StÃ´rgard,starghard ztsysynsky,Î£ÏÎ¬ÏÎ³ÎºÎ±ÏÎ½Ï Î£ÎµÏÏÎ­ÏÏÎ¹Î½ÏÎºÎ¹,Ð¡ÑÐ°ÑÐ³Ð°ÑÐ´ Ð¨ÑÐµÑÐ¸Ð½ÑÐºÐ¸,Ð¡ÑÐ°ÑÐ³Ð°ÑÐ´ Ð¨ÑÐµÑÐ¸Ð½ÑÑÐºÐ¸,Ð¡ÑÐ°ÑÐ³Ð°ÑÐ´ Ð©ÐµÑÑÐ½ÑÑÐºÐ¸Ð¹,Ð¡ÑÐ°ÑÐ³Ð°ÑÐ´ Ð©ÐµÑÑÐ½ÑÑÐºÐ¸,Ð¡ÑÐ°ÑÐ³Ð°ÑÐ´-Ð©ÐµÑÐ¸Ð½ÑÑÐºÐ¸,Ø³ØªØ§Ø±ØºØ§Ø±Ø¯ Ø²ØªØ³ÙØ³ÙÙØ³ÙÙ,ã¹ã¿ã«ã¬ã«ãã»ã·ã¥ãã§ãã¥ã³ã¹ã­,Stargard SzczeciÅski", :latitude => "53.33672", :longitude => "15.0499").save
City.new(:country_id => "181", :name => "Sroda Wielkopolska", :aliases => "Schroda,Sroda,Sroda Wielkopolska,Åroda,Åroda Wielkopolska,Åroda Wielkopolska", :latitude => "52.22843", :longitude => "17.27617").save
City.new(:country_id => "181", :name => "Srem", :aliases => "Srem,Årem,Ð¡ÑÐµÐ¼,Årem", :latitude => "52.08868", :longitude => "17.01508").save
City.new(:country_id => "181", :name => "Sosnowiec", :aliases => "Sosnovec,Sosnoveca,Sosnovecas,Sosnovice,Sosnowez,Sosnowiec,Sossnowitz,Ð¡Ð¾ÑÐ½Ð¾Ð²ÐµÑ,Sosnowiec", :latitude => "50.28682", :longitude => "19.10385").save
City.new(:country_id => "181", :name => "Sopot", :aliases => "SOPOT,Sopot,Sopoty,SopÃ²t,Zoppot,Ð¡ÐÐÐÐ¢,Ð¡Ð¾Ð¿Ð¾Ñ,Sopot", :latitude => "54.4418", :longitude => "18.56003").save
City.new(:country_id => "181", :name => "Solec Kujawski", :aliases => "Schulitz,Solec Kujawski,Solec-Kujavski,Ð¡Ð¾Ð»ÐµÑ-ÐÑÑÐ²ÑÐºÐ¸,Solec Kujawski", :latitude => "53.08371", :longitude => "18.22572").save
City.new(:country_id => "181", :name => "Slupsk", :aliases => "Slupsk,Slupska,Stolp,Stolp in Pommern,Stolpe,Stolpsk,StÃ´Åpsk,SÅupsk,Ð¡Ð»ÑÐ¿ÑÐº,SÅupsk", :latitude => "54.46405", :longitude => "17.02872").save
City.new(:country_id => "181", :name => "Slubice", :aliases => "Damm-Vorstadt,Slubice,SÅubice,Ð¡Ð»ÑÐ±Ð¸ÑÐµ,SÅubice", :latitude => "52.35088", :longitude => "14.56065").save
City.new(:country_id => "181", :name => "Skawina", :aliases => "Skavina,Skawina,Ð¡ÐºÐ°Ð²Ð¸Ð½Ð°,Skawina", :latitude => "49.97524", :longitude => "19.82869").save
City.new(:country_id => "181", :name => "Sierpc", :aliases => "SERPC,Serpts,Sierpc,Ð¡ÐÐ ÐÐ¦,Sierpc", :latitude => "52.8568", :longitude => "19.66913").save
City.new(:country_id => "181", :name => "Sieradz", :aliases => "Seradz,Sieradz,Ð¡ÐµÑÐ°Ð´Ð·,Sieradz", :latitude => "51.59584", :longitude => "18.73023").save
City.new(:country_id => "181", :name => "Siemianowice Slaskie", :aliases => "Siemianowice,Siemianowice Slaskie,Siemianowice ÅlÄskie,Siemianowitz,Simjanovice Slonska,Siemianowice ÅlÄskie", :latitude => "50.32738", :longitude => "19.02901").save
City.new(:country_id => "181", :name => "Rypin", :aliases => "RYPIN,Ripin,Rypin,Ð Ð«ÐÐÐ,Rypin", :latitude => "53.06603", :longitude => "19.40941").save
City.new(:country_id => "181", :name => "Rydultowy", :aliases => "Rydultovy,Rydultowy,RyduÅtowy,Ð ÑÐ´ÑÐ»ÑÐ¾Ð²Ñ,RyduÅtowy", :latitude => "50.05857", :longitude => "18.41703").save
City.new(:country_id => "181", :name => "Rybnik", :aliases => "Ribnika,RibÅika,Rybnik,lei bu ni ke,ribuniku,ãªããã¯,é·å¸å°¼å,Rybnik", :latitude => "50.09713", :longitude => "18.54179").save
City.new(:country_id => "181", :name => "Rumia", :aliases => "RUMJA,Rumia,Rumja,Ð Ð£ÐÐ¯,Rumia", :latitude => "54.57092", :longitude => "18.38802").save
City.new(:country_id => "181", :name => "Ruda Slaska", :aliases => "Ruda,Ruda Slaska,Ruda Slonska,Ruda ÅlÄska,Ruda-Slenska,Ð ÑÐ´Ð°-Ð¡Ð»ÐµÐ½ÑÐºÐ°,Ruda ÅlÄska", :latitude => "50.2584", :longitude => "18.85632").save
City.new(:country_id => "181", :name => "Reda", :aliases => "REDA,Reda,Ð ÐÐÐ,Reda", :latitude => "54.60528", :longitude => "18.34717").save
City.new(:country_id => "181", :name => "Rawicz", :aliases => "Ravich,Rawicz,Rawitsch,Ð Ð°Ð²iÑ,Ð Ð°Ð²Ð¸Ñ,Rawicz", :latitude => "51.60946", :longitude => "16.85852").save
City.new(:country_id => "181", :name => "Radzionkow", :aliases => "Radzionkow,RadzionkÃ³w,RadzionkÃ³w", :latitude => "50.40026", :longitude => "18.90232").save
City.new(:country_id => "181", :name => "Radomsko", :aliases => "Novoradomsk,Nowo Radomsko,Radomsko,Ð Ð°Ð´Ð¾Ð¼ÑÐºÐ¾,Radomsko", :latitude => "51.06713", :longitude => "19.44477").save
City.new(:country_id => "181", :name => "Radlin", :aliases => "Radlin,Radlin", :latitude => "50.0502", :longitude => "18.47626").save
City.new(:country_id => "181", :name => "Raciborz", :aliases => "Raciborz,Raciboza,RaciboÅ¾a,RacibÃ³rz,Ratibor,Ratihor,rachibushu,Ð Ð°ÑÐ¸Ð±Ð¾Ñ,ã©ããã·ã¥,RacibÃ³rz", :latitude => "50.09195", :longitude => "18.21928").save
City.new(:country_id => "181", :name => "Pyskowice", :aliases => "Peiskretscham,Pieskretscham,Pyskowice,Pyskowice", :latitude => "50.4", :longitude => "18.63333").save
City.new(:country_id => "181", :name => "Pszczyna", :aliases => "Pless,Pszczyn,Pszczyna,Pszczyna", :latitude => "49.98037", :longitude => "18.95382").save
City.new(:country_id => "181", :name => "Pruszcz Gdanski", :aliases => "Praust,Pruszcz,Pruszcz Gdanski,Pruszcz GdaÅski,Pruszcz GdaÅski", :latitude => "54.26217", :longitude => "18.63625").save
City.new(:country_id => "181", :name => "Prudnik", :aliases => "Neustadt,Neustadt in Oberschlesien,Prudnik,ÐÑÑÐ´Ð½Ð¸Ðº,Prudnik", :latitude => "50.32124", :longitude => "17.57461").save
City.new(:country_id => "181", :name => "Poznan", :aliases => "Posen,Poznan,Poznan',PoznaÅ,ÐÐ¾Ð·Ð½Ð°Ð½Ñ,PoznaÅ", :latitude => "52.41667", :longitude => "16.96667").save
City.new(:country_id => "181", :name => "Polkowice", :aliases => "Bolkowice,Heerwegen,Pol'kovice,Polkowice,Polkwitz,Polkwitz Kreis Glogau,ÐÐ¾Ð»ÑÐºÐ¾Ð²Ð¸ÑÐµ,Polkowice", :latitude => "51.50391", :longitude => "16.07261").save
City.new(:country_id => "181", :name => "Police", :aliases => "Police,Policija,Politz,PÃ¶litz,ÐÐ¾Ð»Ð¸ÑÐ¸Ñ,Police", :latitude => "53.55214", :longitude => "14.57182").save
City.new(:country_id => "181", :name => "Plock", :aliases => "PLOCK,Plock,Plocka,Plotsk,PÅock,puu~otsuku,ÐÐÐÐ¦Ð,ÐÐ»Ð¾ÑÐº,ãã¦ã©ãã¯,PÅock", :latitude => "52.54682", :longitude => "19.70638").save
City.new(:country_id => "181", :name => "Pleszew", :aliases => ",Pleszew", :latitude => "51.89636", :longitude => "17.78549").save
City.new(:country_id => "181", :name => "Piotrkow Trybunalski", :aliases => "Petrikau,Petrokov,Piotrkow,Piotrkow Trybunalski,PiotrkÃ³w,PiotrkÃ³w Trybunalski,Pjotrkova Tribunalska,Pjotrkova TribunaÄ¼ska,Pjotrkuv-Trybunal'ski,ÐÑÑÑÐºÑÐ²-Ð¢ÑÑÐ±ÑÐ½Ð°Ð»ÑÑÐºÐ¸,PiotrkÃ³w Trybunalski", :latitude => "51.40547", :longitude => "19.70321").save
City.new(:country_id => "181", :name => "Pila", :aliases => "Pila,Pily,PiÅa,Schneidemuhl,SchneidemÃ¼hl,ÐÐ¸Ð»Ñ,PiÅa", :latitude => "53.15145", :longitude => "16.73782").save
City.new(:country_id => "181", :name => "Piekary Slaskie", :aliases => "Piekary Slaskie,Piekary Wielkie,Piekary ÅlÄskie,Piekary ÅlÄskie", :latitude => "50.38017", :longitude => "18.92653").save
City.new(:country_id => "181", :name => "Pabianice", :aliases => "Pab'janice,Pab'yanitsy,Pabianice,Pabjanice,PabjaÅice,Pabâyanitsy,ÐÐ°Ð±ÑÑÐ½Ð¸ÑÐµ,ÐÐ°Ð±ÑÐ½Ð¸ÑÐµ,ÐÐ°Ð±ÑÐ°ÑÐ¸ÑÐµ,Pabianice", :latitude => "51.66446", :longitude => "19.35473").save
City.new(:country_id => "181", :name => "Ozorkow", :aliases => "Ozorkov,Ozorkow,OzorkÃ³w,OzorkÃ³w", :latitude => "51.96336", :longitude => "19.29139").save
City.new(:country_id => "181", :name => "Oswiecim", :aliases => "Auschwitz,Osbietsim,Osvencim,Osvetim,Osviencim,OsvÄtim,Oswiecim,OÅwiÄcim,oshifienchimu,ÎÏÎ²Î¹ÎµÏÏÎ¹Î¼,ÐÑÐ²ÐµÐ½ÑÐ¸Ð¼,ÐÑÐ²Ð¸ÐµÐ½ÑÐ¸Ð¼,ãªã·ãã£ã¨ã³ãã ,OÅwiÄcim", :latitude => "50.03437", :longitude => "19.21037").save
City.new(:country_id => "181", :name => "Ostrow Wielkopolski", :aliases => "Ostrov,Ostrova Velkopolska,Ostrova VeÄ¼kopoÄ¼ska,Ostrovia,Ostrovo,Ostrow,Ostrow Wielkopolski,Ostruv-Vel'kopol'ski,OstrÃ³w,OstrÃ³w Wielkopolski,ÐÑÑÑÑÐ²-ÐÐµÐ»ÑÐºÐ¾Ð¿Ð¾Ð»ÑÑÐºÐ¸,OstrÃ³w Wielkopolski", :latitude => "51.65501", :longitude => "17.80686").save
City.new(:country_id => "181", :name => "Ostroda", :aliases => "OSTRUDA,Osterode,Ostroda,OstrÃ³da,ÐÐ¡Ð¢Ð Ð£ÐÐ,OstrÃ³da", :latitude => "53.69671", :longitude => "19.96486").save
City.new(:country_id => "181", :name => "Orzesze", :aliases => "Orzesze,Orzesze", :latitude => "50.15", :longitude => "18.78333").save
City.new(:country_id => "181", :name => "Opole", :aliases => "Opole,Oppein,Oppeln,ao bo lai,opore,ÐÐ¿Ð¾Ð»Ðµ,×××¤×××,ãªãã¼ã¬,å¥¥æ³¢è±,Opole", :latitude => "50.66667", :longitude => "17.95").save
City.new(:country_id => "181", :name => "Olkusz", :aliases => "Ol'kush,Olkusz", :latitude => "50.2813", :longitude => "19.56503").save
City.new(:country_id => "181", :name => "Olesnica", :aliases => "Oels,Olesnica,OleÅnica,Ols,Ãls,ÐÐ»ÐµÑÐ½Ð¸ÑÐ°,OleÅnica", :latitude => "51.21338", :longitude => "17.38986").save
City.new(:country_id => "181", :name => "Olawa", :aliases => "Ohiau,Ohlau,Olava,Olawa,OÅawa,ÐÐ»Ð°Ð²Ð°,OÅawa", :latitude => "50.9466", :longitude => "17.2926").save
City.new(:country_id => "181", :name => "Oborniki", :aliases => "Obornik,Oborniki,Oborniki", :latitude => "52.64739", :longitude => "16.81406").save
City.new(:country_id => "181", :name => "Nysa Zamlynie", :aliases => ",Nysa ZamÅynie", :latitude => "50.4575", :longitude => "17.31308").save
City.new(:country_id => "181", :name => "Nysa", :aliases => "Neisse,Neisze,Niesse,Nysa,nu~isa,ãã£ãµ,Nysa", :latitude => "50.47379", :longitude => "17.33437").save
City.new(:country_id => "181", :name => "Nowy Tomysl", :aliases => "Nowy Tomysl,Nowy TomyÅl,Nowy TomyÅl", :latitude => "52.3195", :longitude => "16.12844").save
City.new(:country_id => "181", :name => "Nowogard", :aliases => "Naugard,Nowogard", :latitude => "53.67437", :longitude => "15.1163").save
City.new(:country_id => "181", :name => "Nowa Sol", :aliases => "Neusalz,Nowa Sol,Nowa SÃ³l,Nowa SÃ³l", :latitude => "51.80333", :longitude => "15.71702").save
City.new(:country_id => "181", :name => "Nowa Ruda", :aliases => "Neurode,Nova-Ruda,Nowa Ruda,Nowy Ruda,ÐÐ¾Ð²Ð°-Ð ÑÐ´Ð°,Nowa Ruda", :latitude => "50.58008", :longitude => "16.50164").save
City.new(:country_id => "181", :name => "Namyslow", :aliases => "Namslau,Namyslow,NamysÅÃ³w,NamysÅÃ³w", :latitude => "51.07592", :longitude => "17.72284").save
City.new(:country_id => "181", :name => "Naklo nad Notecia", :aliases => "Nakel,Naklo,Naklo nad Notecia,NakÅo,NakÅo nad NoteciÄ,NakÅo nad NoteciÄ", :latitude => "53.14214", :longitude => "17.60181").save
City.new(:country_id => "181", :name => "Myszkow", :aliases => "Myshkov,Myszkow,Myszkow Nowy,MyszkÃ³w,MyszkÃ³w Nowy,ÐÑÑÐºÐ¾Ð²,MyszkÃ³w", :latitude => "50.5752", :longitude => "19.32461").save
City.new(:country_id => "181", :name => "Myslowice", :aliases => "Mislovice,Myslovice,Myslowice,MysÅowice,ÐÑÑÐ»Ð¾Ð²Ð¸ÑÐµ,MysÅowice", :latitude => "50.20745", :longitude => "19.16668").save
City.new(:country_id => "181", :name => "Myslenice", :aliases => "Myslenice,MyÅlenice,MyÅlenice", :latitude => "49.83383", :longitude => "19.9383").save
City.new(:country_id => "181", :name => "Mikolow", :aliases => "Miklos,MiklÃ³s,Mikolow,MikoÅÃ³w,Mikulas,MikulÃ¡Å¡,Nicolaas,Nicolai,Nikolaj,Nikolaus,mikoufu,ÐÐ¸ÐºÐ¾Ð»Ð°Ð¹,ãã³ã¦ã,MikoÅÃ³w", :latitude => "50.16667", :longitude => "18.9").save
City.new(:country_id => "181", :name => "Miedzyrzecz", :aliases => "Mesdirtz,Meseritz,Miedzyrzecz,MiÄdzyrzecz,MiÄdzyrzecz", :latitude => "52.44461", :longitude => "15.57801").save
City.new(:country_id => "181", :name => "Malbork", :aliases => "MAL'BORK,Mal'bork,Malbork,Malborka,Malborkas,Marienburg,ÐÐÐÐ¬ÐÐÐ Ð,ÐÐ°Ð»ÑÐ±Ð¾ÑÐº,Malbork", :latitude => "54.03591", :longitude => "19.0266").save
City.new(:country_id => "181", :name => "Lubon", :aliases => "Ljubon,Lubon,LuboÅ,ÐÑÐ±Ð¾Ð½,LuboÅ", :latitude => "52.34705", :longitude => "16.89267").save
City.new(:country_id => "181", :name => "Lubliniec", :aliases => "Ljublinec,Lublinek,Lubliniec,Lublinitz,ruburinyetsu,ÐÑÐ±Ð»Ð¸Ð½ÐµÑ,ã«ããªãã§ã,Lubliniec", :latitude => "50.66897", :longitude => "18.6844").save
City.new(:country_id => "181", :name => "Lubin", :aliases => "Ljubin,Luben,Lubin,Lubina,LÃ¼ben,Ä»ubina,ÐÑÐ±Ð¸Ð½,Lubin", :latitude => "51.40089", :longitude => "16.20149").save
City.new(:country_id => "181", :name => "Luban", :aliases => "Lauban,Ljuban',Luban,LubaÅ,ÐÑÐ±Ð°Ð½Ñ,LubaÅ", :latitude => "51.12014", :longitude => "15.28768").save
City.new(:country_id => "181", :name => "Lowicz", :aliases => "Lowicz,Lowitsch,Åowicz,Åowicz", :latitude => "52.10714", :longitude => "19.94525").save
City.new(:country_id => "181", :name => "Litzmannstadt", :aliases => "Litzmannstadt,Lodz,Lodz',Lodza,Lodze,Lodzo,LodzÄ,LodÅ¾,lwdz',utchi,ÅÃ³dÅº,ÐÐ¾Ð´Ð·,ÐÐ¾Ð´Ð·Ñ,ÐÐ¾Ñ,××××',ã¦ãã,Litzmannstadt", :latitude => "51.75", :longitude => "19.46667").save
City.new(:country_id => "181", :name => "Libiaz", :aliases => "Libiaz,LibiÄÅ¼,LibiÄÅ¼", :latitude => "50.10396", :longitude => "19.31568").save
City.new(:country_id => "181", :name => "Leszno", :aliases => "Leshno,Lesno,Leszno,LeÅ¡no,Lissa,ÐÐµÑÐ½Ð¾,Leszno", :latitude => "51.84034", :longitude => "16.57494").save
City.new(:country_id => "181", :name => "Legnica", :aliases => "Legnica,Liegnitz,Lignica,ÐÐµÐ³Ð½Ð¸ÑÐ°,Legnica", :latitude => "51.21006", :longitude => "16.1619").save
City.new(:country_id => "181", :name => "Ledziny", :aliases => "Ledziny,LÄdziny,LÄdziny", :latitude => "50.14264", :longitude => "19.13149").save
City.new(:country_id => "181", :name => "Leczyca", :aliases => "Leczyca,u~enchitsu~a,ÅÄczyca,ã¦ã§ã³ããã¡,ÅÄczyca", :latitude => "52.05959", :longitude => "19.19972").save
City.new(:country_id => "181", :name => "Lebork", :aliases => "Lauenburg,Lauenburg in Pommern,Lebork,Lembork,LÄbork,LÄbork", :latitude => "54.53921", :longitude => "17.75012").save
City.new(:country_id => "181", :name => "Laziska Gorne", :aliases => "Lagissa,Laziska Gorne,Laziskagorna,Oberlasisk,Oberlazisk,Åaziska GÃ³rne,Åaziska GÃ³rne", :latitude => "50.14952", :longitude => "18.84215").save
City.new(:country_id => "181", :name => "Lask", :aliases => "Lask,Åask,Åask", :latitude => "51.59056", :longitude => "19.13278").save
City.new(:country_id => "181", :name => "Kwidzyn", :aliases => "KVIDZYN,Kwidzyn,Marienwerder,ÐÐÐÐÐÐ«Ð,Kwidzyn", :latitude => "53.73333", :longitude => "18.91667").save
City.new(:country_id => "181", :name => "Kutno", :aliases => "KUTNO,Kutno,ÐÐ£Ð¢ÐÐ,ÐÑÑÐ½Ð¾,Kutno", :latitude => "52.23064", :longitude => "19.36409").save
City.new(:country_id => "181", :name => "Krotoszyn", :aliases => "Krotoshin,Krotoszyn,ÐÑÐ¾ÑÐ¾ÑÐ¸Ð½,Krotoszyn", :latitude => "51.69868", :longitude => "17.43738").save
City.new(:country_id => "181", :name => "Krapkowice", :aliases => "Chrapkowice,Krapkowice,Krappitz,Krapkowice", :latitude => "50.47515", :longitude => "17.96539").save
City.new(:country_id => "181", :name => "Krakow", :aliases => "Cracau,CracaÃ»,Cracovia,Cracovie,Cracow,CracÃ²via,CracÃ³via,Kraka,Krakau,Krakiv,Krakko,KrakkÃ³,Krakobia,Krakov,Krakova,Krakovija,Krakovja,Krakovo,Krakow,KrakÃ¡,KrakÃ³w,Krokuva,ke la ke fu,keulakupeu,kurakufu,qrqwb,ÎÏÎ±ÎºÎ¿Î²Î¯Î±,ÐÑÐ°ÐºÐ°Ñ,ÐÑÐ°ÐºÐ¾Ð²,ÐÑÐ°ÐºÐ¾Ð²Ð¸Ñ,ÐÑÐ°ÐºÑÐ²,×§×¨×§××,áá ááááá,ã¯ã©ã¯ã,åæç§å¤«,í¬ë¼ì¿ í,KrakÃ³w", :latitude => "50.08333", :longitude => "19.91667").save
City.new(:country_id => "181", :name => "Koszalin", :aliases => "Kezlin,Koeslin,Kosalina,Koshalin,Koslin,Koszalin,KoÅ¡alina,KÃ¶slin,Scurgum,ÐÐ¾ÑÐ°Ð»Ð¸Ð½,Koszalin", :latitude => "54.19438", :longitude => "16.17222").save
City.new(:country_id => "181", :name => "Kostrzyn nad Odra", :aliases => "Cuestrin,CÃ¼strin,Kistrzyn,Kostrzyn,Kuestrin,KÃ¼strin,Kostrzyn nad OdrÄ", :latitude => "52.58713", :longitude => "14.64953").save
City.new(:country_id => "181", :name => "Koscierzyna", :aliases => "Koscierzyna,KoÅcierzyna,KoÅcierzyna", :latitude => "54.12226", :longitude => "17.98119").save
City.new(:country_id => "181", :name => "Koscian", :aliases => "Kos'tsyan,Koscian,Kosten,Kosâtsyan,KoÅcian,KoÅcian", :latitude => "52.08829", :longitude => "16.64866").save
City.new(:country_id => "181", :name => "Konstantynow Lodzki", :aliases => "Konstantynow,Konstantynow Lodzki,KonstantynÃ³w,KonstantynÃ³w ÅÃ³dzki,KonstantynÃ³w ÅÃ³dzki", :latitude => "51.74776", :longitude => "19.32564").save
City.new(:country_id => "181", :name => "Konin", :aliases => "KONIN,Konin,Konina,KoÅina,ÐÐÐÐÐ,Konin", :latitude => "52.22338", :longitude => "18.25121").save
City.new(:country_id => "181", :name => "Kolobrzeg", :aliases => "Kolberg,Kolobrzeg,Kolobzheg,KoÅobrzeg,ÐÐ¾Ð»Ð¾Ð±Ð¶ÐµÐ³,KoÅobrzeg", :latitude => "54.17565", :longitude => "15.58342").save
City.new(:country_id => "181", :name => "Kolo", :aliases => "KOLO,Kolas,Kolo,KoÅo,Warthbrucken,WarthbrÃ¼cken,ÐÐÐÐ,ÐÐ¾Ð»Ð¾,KoÅo", :latitude => "52.20024", :longitude => "18.63865").save
City.new(:country_id => "181", :name => "Knurow", :aliases => "Knurow,KnurÃ³w,KnurÃ³w", :latitude => "50.21667", :longitude => "18.66667").save
City.new(:country_id => "181", :name => "Kluczbork", :aliases => "Klauczbork,Kljuchbork,Kluczbork,Kluozborek,Kreuzburg,ÐÐ»ÑÑÐ±Ð¾ÑÐº,Kluczbork", :latitude => "50.97281", :longitude => "18.21816").save
City.new(:country_id => "181", :name => "Klodzko", :aliases => "Glatz,Kladsko,Kladzko,Klodzko,KÅadzko,KÅodzko,ÐÐ»Ð¾Ð´Ð·ÐºÐ¾,KÅodzko", :latitude => "50.43488", :longitude => "16.66145").save
City.new(:country_id => "181", :name => "Kety", :aliases => "Kety,KÄty,KÄty", :latitude => "49.88214", :longitude => "19.22333").save
City.new(:country_id => "181", :name => "Kedzierzyn-Kozle", :aliases => "Heydebreck,Kandrzin,Kandrzin Pogorzelletz,Kedzierzyn,Kedzierzyn-Kozle,Kendzezhin-Kozle,KÄdzierzyn,KÄdzierzyn-KoÅºle,ÐÐµÐ½Ð´Ð·ÐµÐ¶Ð¸Ð½-ÐÐ¾Ð·Ð»Ðµ,KÄdzierzyn-KoÅºle", :latitude => "50.34984", :longitude => "18.22606").save
City.new(:country_id => "181", :name => "Katowice", :aliases => "Catowice,Katobitse,Katovica,Katovice,Katovicum,KatovicÄ,Katovitse,Katowice,Katowihi,Kattowitz,Stalinogorod,Stalinograd,Stalinogrod,StalinogrÃ³d,ka tuo wei zi,katobiche,katovitses,katovu~itsu~e,katwfytsh,katwwyts,ketovica,ketovis,kha to wits,kha to witsu,kyatobhisa,mstkhdm:mhmd alqyrwany,qtwbyz,ÎÎ¬ÏÎ¿Î²Î¹ÏÏÎµ,ÎÎ±ÏÎ¿Î²Î¯ÏÏÎµ,ÎÎ±ÏÎ¿Î²Î¹ÏÏÎµ,ÐÐ°ÑÐ¾Ð²Ð¸ÑÐ°,ÐÐ°ÑÐ¾Ð²Ð¸ÑÐµ,ÐÐ°ÑÐ¾Ð²ÑÑÐµ,Ô¿Õ¡Õ¿Õ¸Õ¾Õ«ÖÕ¥,×§×××××¥,ÙØ§ØªÙÙÙØªØ³Ù,ÙØ³ØªØ®Ø¯Ù:ÙØ­ÙØ¯ Ø§ÙÙÙØ±ÙØ§ÙÙ,Ú©Ø§ØªÙÙÛØªØ³,ÞÞ¬ÞÞ®ÞÞ¨ÞÞ°,à¤à¥à¤à¥à¤µà¤¿à¤,à¤à¥à¤¯à¤¾à¤à¥à¤­à¤¿à¤¸,à¸à¸°à¹à¸à¸§à¸´à¸à¸,à¸à¸°à¹à¸à¸§à¸´à¸à¸à¸¶,ááá¢ááááªá,á«á¶áªá¸,ã«ãã´ã£ãã§,å¡æç»´å¹,ì¹´í ë¹ì²´,Katowice", :latitude => "50.26667", :longitude => "19.01667").save
City.new(:country_id => "181", :name => "Kartuzy", :aliases => "KARTUZY,Kartuze,Kartuzy,KartuzÃ«,ÐÐÐ Ð¢Ð£ÐÐ«,Kartuzy", :latitude => "54.33424", :longitude => "18.19735").save
City.new(:country_id => "181", :name => "Kamienna Gora", :aliases => "Kamienna Gora,Kamienna GÃ³ra,Landeshut,Kamienna GÃ³ra", :latitude => "50.78333", :longitude => "16.03333").save
City.new(:country_id => "181", :name => "Kalisz", :aliases => "Kalisa,Kalisch,Kalish,Kalisz,KaliÅ¡a,ÐÐ°Ð»Ð¸Ñ,Kalisz", :latitude => "51.76109", :longitude => "18.09102").save
City.new(:country_id => "181", :name => "Jelenia Gora", :aliases => "Hirschberg,Hirschberg im Riesengebirge,Hirschberg in Schlesien,Jelena Gura,Jelenia Gora,Jelenia GÃ³ra,Jelenja Gura,JeleÅa Gura,yelleniagula,ÐÐµÐ»ÐµÐ½Ñ ÐÑÑÐ°,ìë ëìêµ¬ë¼,Jelenia GÃ³ra", :latitude => "50.89973", :longitude => "15.72899").save
City.new(:country_id => "181", :name => "Jelcz", :aliases => "Jelcz,Jelczc,Jelez,Jeltsch,Jelcz", :latitude => "51.02102", :longitude => "17.32095").save
City.new(:country_id => "181", :name => "Jaworzno", :aliases => "Javozhno,Jaworzyna,Ð¯Ð²Ð¾Ð¶Ð½Ð¾,Jaworzno", :latitude => "50.20528", :longitude => "19.27498").save
City.new(:country_id => "181", :name => "Jawor", :aliases => "Jauer,Javor,Jawor,Ð¯Ð²Ð¾Ñ,Jawor", :latitude => "51.05", :longitude => "16.18333").save
City.new(:country_id => "181", :name => "Jastrzebie Zdroj", :aliases => "Jastrzebie Zdroj,Jastrzebie-Zdroj,JastrzÄbie ZdrÃ³j,JastrzÄbie-ZdrÃ³j,Jastsembe Zdroja,JastÅ¡embe Zdroja,JastrzÄbie ZdrÃ³j", :latitude => "49.95542", :longitude => "18.57479").save
City.new(:country_id => "181", :name => "Jarocin", :aliases => "Jarocin,ya luo qin,Ð¯ÑÐ¾ÑÐ¸Ð½,äºç½é¦,Jarocin", :latitude => "51.97266", :longitude => "17.50256").save
City.new(:country_id => "181", :name => "Inowroclaw", :aliases => "Hohensalza,INOVROCLAV,Inovroclava,Inovrotslav,Inowraclaw,InowracÅaw,Inowroclaw,InowrocÅaw,Irownoclaw,ÐÐÐÐÐ ÐÐ¦ÐÐÐ,InowrocÅaw", :latitude => "52.79886", :longitude => "18.26388").save
City.new(:country_id => "181", :name => "Ilawa", :aliases => "Deutsch Eylau,ILAVA,Ilawa,IÅawa,iwavu~a,ÐÐÐÐÐ,ã¤ã¯ã´ã¡,IÅawa", :latitude => "53.59601", :longitude => "19.56849").save
City.new(:country_id => "181", :name => "Gubin", :aliases => "Guben,Gubin,Gubin", :latitude => "51.94956", :longitude => "14.72837").save
City.new(:country_id => "181", :name => "Gryfino", :aliases => "Greifenhagen,Gryfino,ÐÑÑÑÐ¸Ð½Ð¾,Gryfino", :latitude => "53.25243", :longitude => "14.48831").save
City.new(:country_id => "181", :name => "Gryfice", :aliases => "Greifenberg,Greifenberg in Pommern,Gryfice", :latitude => "53.9165", :longitude => "15.20027").save
City.new(:country_id => "181", :name => "Grudziadz", :aliases => "GRUDZENDZ,Graudenz,Grudzendz,Grudziadz,GrudziÄdz,Grudzjondza,GrudzÃ«ndz,ÐÐ Ð£ÐÐÐÐÐÐ,GrudziÄdz", :latitude => "53.48411", :longitude => "18.75366").save
City.new(:country_id => "181", :name => "Gostynin", :aliases => "GOSTYNIN,Gostyn,Gostynin,ÐÐÐ¡Ð¢Ð«ÐÐÐ,Gostynin", :latitude => "52.42938", :longitude => "19.46194").save
City.new(:country_id => "181", :name => "Gostyn", :aliases => "Gostingen,Gostyn,GostyÅ,ÐÐ¾ÑÑÑÐ½,GostyÅ", :latitude => "51.88247", :longitude => "17.01226").save
City.new(:country_id => "181", :name => "Gorzow Wielkopolski", :aliases => "Gorzow Wielkopolski,GorzÃ³w Wielkopolski,Gozhuv-Vel'kopol'ski,Gozova Velkopolska,GoÅ¾ova VeÄ¼kopoÄ¼ska,Landsberg,Landsberg an der Warthe,ÐÐ¾Ð¶ÑÐ²-ÐÐµÐ»ÑÐºÐ¾Ð¿Ð¾Ð»ÑÑÐºÐ¸,GorzÃ³w Wielkopolski", :latitude => "52.73679", :longitude => "15.22878").save
City.new(:country_id => "181", :name => "Goleniow", :aliases => "Goleniow,GoleniÃ³w,Golenjov,Gollnow,Golnowo,GÃ²lnowÃ²,ÐÐ¾Ð»ÐµÐ½ÑÐ²,GoleniÃ³w", :latitude => "53.56392", :longitude => "14.82854").save
City.new(:country_id => "181", :name => "Gniezno", :aliases => "Gnesen,Gnesna,Gnezno,Gniezno,GÅezno,ÐÐ½ÐµÐ·Ð½Ð¾,ÐÐ½ÑÐ·Ð½Ð¾,Gniezno", :latitude => "52.53481", :longitude => "17.58259").save
City.new(:country_id => "181", :name => "Glucholazy", :aliases => "Glucholazy,GÅuchoÅazy,Ziegenhals,GÅuchoÅazy", :latitude => "50.31505", :longitude => "17.38355").save
City.new(:country_id => "181", :name => "Glowno", :aliases => "Glovno,Glowd,Glowno,GÅowno,GÅowno", :latitude => "51.96463", :longitude => "19.71565").save
City.new(:country_id => "181", :name => "Glogow", :aliases => "Glogau,Glogov,Glogovia,Glogow,Gloguva,GÅogÃ³w,Hlohov,ge wo gu fu,guu~ogufu,ÐÐ»Ð¾Ð³Ð¾Ð²,ã°ã¦ã©ã°ã,æ ¼æ²å¤å¤«,GÅogÃ³w", :latitude => "51.66361", :longitude => "16.0845").save
City.new(:country_id => "181", :name => "Gliwice", :aliases => "Gleiwitz,Glivice,Gliwice,Gliwice-Sosnowiec,GÄ¼ivice,gurivu~itsu~e,ÐÐ»Ð¸Ð²Ð¸ÑÐµ,ã°ãªã´ã£ãã§,Gliwice", :latitude => "50.28333", :longitude => "18.66667").save
City.new(:country_id => "181", :name => "Gdynia", :aliases => "Civitas Gdinensis,Gdina,Gdingen,Gdinio,GdiniÃ´,Gdinja,GdiÅa,Gdyne,Gdynia,Gdynja,GdynÄ,Gotenhafen,Gothenhafen,ge ding ni ya,gudinya,ÐÐ´Ð¸Ð½Ñ,ÐÐ´ÑÐ½Ñ,ã°ãã£ãã£,æ ¼ä¸å°¼äº,Gdynia", :latitude => "54.51889", :longitude => "18.53188").save
City.new(:country_id => "181", :name => "Gdansk", :aliases => "Dancigo,Danzica,Danzig,Gdan'sk,Gdansk,Gdanska,Gdanskas,GdaÅsk,GdaÅska,GdaÅsk,Gdunsk,GduÅsk,Gedania,Gydanysg,Nkntansk,gdnsq,ge dan si ke,geudanseukeu,gudanisuku,ÎÎºÎ½ÏÎ±Î½ÏÎº,ÐÐ´Ð°Ð½ÑÐº,ÐÐ´Ð°Ð½ÑÑÐº,ÐÐ´Ð°ÑÑÐº,ÒÐ´Ð°Ð½ÑÑÐº,××× ×¡×§,ã°ããã¹ã¯,æ ¼ä½æ¯å,ê·¸ë¨ì¤í¬,GdaÅsk", :latitude => "54.35205", :longitude => "18.64637").save
City.new(:country_id => "181", :name => "Fordon", :aliases => ",Fordon", :latitude => "53.14821", :longitude => "18.17036").save
City.new(:country_id => "181", :name => "Elblag", :aliases => "EHL'BLONG,El'bleng,Elbing,Elbinga,Elblag,Elblong,Elblonga,ElblÄg,ElâblÃ«ng,Ð­ÐÐ¬ÐÐÐÐÐ,Elblag", :latitude => "54.1522", :longitude => "19.40884").save
City.new(:country_id => "181", :name => "Dzierzoniow", :aliases => "Dzierzoniow,DzierÅ¼oniÃ³w,Reichenbach,Reichenbach im Eulengebirge,Reichenbach in Schlesien,Rychbach,DzierÅ¼oniÃ³w", :latitude => "50.7282", :longitude => "16.65141").save
City.new(:country_id => "181", :name => "Dabrowa Gornicza", :aliases => "Dabrowa Gornicza,Dombrova Gurnica,Dombrova GurÅiÄa,Dombrowa,DÄbrowa GÃ³rnicza,DÄbrowa GÃ³rnicza", :latitude => "50.31818", :longitude => "19.2374").save
City.new(:country_id => "181", :name => "Czestochowa", :aliases => "Censtakava,Censtochova,Censtohova,Chenstochov,Chenstokhov,Chenstokhova,Czenstochau,Czestochowa,CzÄstochowa,Tschenstochau,qin si tuo huo wa,z'nstwhwbh,Äenstakava,ÄenstochovÃ¡,Äenstohova,Ð§ÐµÐ½ÑÑÐ¾ÑÐ¾Ð²Ð°,×¦'× ×¡××××××,ç´æ¯æéç¦,CzÄstochowa", :latitude => "50.79646", :longitude => "19.12409").save
City.new(:country_id => "181", :name => "Czerwionka-Leszczyny", :aliases => "Czerwionka,Leszczyny,Czerwionka-Leszczyny", :latitude => "50.15007", :longitude => "18.67762").save
City.new(:country_id => "181", :name => "Czeladz", :aliases => "Czeladz,Czeladz Piaski,CzeladÅº,CzeladÅº", :latitude => "50.31667", :longitude => "19.1").save
City.new(:country_id => "181", :name => "Czechowice-Dziedzice", :aliases => "Czchowice,Czechowice,Czechowice-Dziedzice,Dziedzice,Dzieozice,Zabracze,Czechowice-Dziedzice", :latitude => "49.91667", :longitude => "19.01667").save
City.new(:country_id => "181", :name => "Cieszyn", :aliases => "Ceshin,Cesina,CeÅ¡ina,Cieszyn,Teschen,Tesin,Tesino,TeÅino,TeÅ¡Ã­n,TÄÅ¡Ã­n,z'syn,Ð¦ÐµÑÐ¸Ð½,×¦'×©××,Cieszyn", :latitude => "49.75133", :longitude => "18.63213").save
City.new(:country_id => "181", :name => "Chrzanow", :aliases => "Chrzanow,ChrzanÃ³w,Khshanov,Krenau,××©×× ××,ChrzanÃ³w", :latitude => "50.13546", :longitude => "19.40203").save
City.new(:country_id => "181", :name => "Choszczno", :aliases => "Arnswalde,Choszczno,Choszczno", :latitude => "53.16905", :longitude => "15.42054").save
City.new(:country_id => "181", :name => "Chorzow", :aliases => "Cherzow,CherzÃ³w,Chorzow,ChorzÃ³w,Hozova,HoÅ¾ova,Khozhuv,Konigshutte,Krolewska Huta,KrÃ³lewska Huta,KÃ¶nigshÃ¼tte,hwrshaw,Ð¥Ð¾Ð¶ÑÐ²,ÙÙØ±Ø´Ø§Ù,ChorzÃ³w", :latitude => "50.3", :longitude => "18.96667").save
City.new(:country_id => "181", :name => "Chojnice", :aliases => "Chojnice,Chonice,ChÃ²nice,Hojnice,Khojnice,Khoynitsy,Konitz,hoinitsu~e,Ð¥Ð¾Ð¹Ð½Ð¸ÑÐµ,Ð¥Ð¾ÑÑÐ¸ÑÐµ,ãã¤ããã§,Chojnice", :latitude => "53.69554", :longitude => "17.55701").save
City.new(:country_id => "181", :name => "Chodziez", :aliases => "Chodziez,ChodzieÅ¼,Kolmar,hojeshu,Ð¥Ð¾ÑÐµÐ¶,ãã¸ã§ã·ã¥,ChodzieÅ¼", :latitude => "52.99505", :longitude => "16.9198").save
City.new(:country_id => "181", :name => "Chelmza", :aliases => "Chelmza,CheÅmÅ¼a,KHELMZHA,Khelmzha,Ð¥ÐÐÐÐÐ,Ð¥ÐµÐ»Ð¼Ð¶Ð°,CheÅmÅ¼a", :latitude => "53.18463", :longitude => "18.60466").save
City.new(:country_id => "181", :name => "Chelmno", :aliases => "Campo di sterminio di Chelmno,Campo di sterminio di CheÅmno,Chelmno,Chelmno nad Wisla,CheÅmno,CheÅmno nad WisÅÄ,Ekstermejo Chelmno,Ekstermejo CheÅmno,KHELMNO,Khelmno,hlmnw,Ð¥ÐÐÐÐÐ,Ð¥ÐµÐ»Ð¼Ð½Ð¾,×××× ×,CheÅmno", :latitude => "53.34855", :longitude => "18.4251").save
City.new(:country_id => "181", :name => "Bytow", :aliases => "Betowo,Bitov,Butow,Bytow,Bytowe,BytÃ³w,BÃ«towÃ²,BÃ¼tow,ÐÐ¸ÑÐ¾Ð²,BytÃ³w", :latitude => "54.17057", :longitude => "17.49187").save
City.new(:country_id => "181", :name => "Bytom", :aliases => "Beuthen,Bitom,Bitoma,Bytom,bi tuo mu,ÐÐ¸ÑÐ¾Ð¼,ÐÑÑÐ¾Ð¼,æ¯æå§,Bytom", :latitude => "50.35", :longitude => "18.96667").save
City.new(:country_id => "181", :name => "Bydgoszcz", :aliases => "Bidgosc,Bidgosca,Bidgoshch,Bidgoshh,BidgoÅ¡Äa,Bintnkos,Brombarg,Bromberch,Bromberg,Bydgoscius,Bydgoshh,Bydgostia,Bydgoszcz,BydgoÅ¡Äius,Bydhost,BydhoÅ¡Å¥,BÄ±dgoÅÃ§,Gorad Bydgashch,bi de ge shen,bideugosyuchi,bidgoshchi,bu~idogoshuchu,bydgwshch,bydgwsz',ÎÏÎ¹Î½ÏÎ³ÎºÏÏ,ÐÐ¸Ð´Ð³Ð¾ÑÑ,ÐÐ¸Ð´Ð³Ð¾Ñ,ÐÑÐ´Ð³Ð¾Ñ,ÐÐ¾ÑÐ°Ð´ ÐÑÐ´Ð³Ð°ÑÑ,××××××©×¥',Ø¨ÛØ¯Ú¯ÙØ´Ú,áááááá¨á©á,ãã£ãã´ã·ã¥ãã¥,æ¯å¾å¥ä»,ë¹ëê³ ìì¹,Bydgoszcz", :latitude => "53.1235", :longitude => "18.00762").save
City.new(:country_id => "181", :name => "Brzeg", :aliases => "Brieg,Brzeg,Bzheg,bujeku,ÐÐ¶ÐµÐ³,ãã¸ã§ã¯,Brzeg", :latitude => "50.86079", :longitude => "17.4674").save
City.new(:country_id => "181", :name => "Brodnica", :aliases => "BRODNICA,Brodnica,ÐÐ ÐÐÐÐÐ¦Ð,ÐÑÐ¾Ð´ÑÐ¸ÑÐ°,Brodnica", :latitude => "53.25967", :longitude => "19.39653").save
City.new(:country_id => "181", :name => "Braniewo", :aliases => "BRANEVO,Branevo,Braniewo,Braunsberg,Brunsberga,ÐÐ ÐÐÐÐÐ,ÐÑÐ°ÑÐµÐ²Ð¾,Braniewo", :latitude => "54.37971", :longitude => "19.81959").save
City.new(:country_id => "181", :name => "Boleslawiec", :aliases => "Boleslavec,Boleslavjec,Boleslawice,Boleslawiec,BolesÅawiec,Bunzlau,buntsurau,ÐÐ¾Ð»ÐµÑÐ»Ð°Ð²ÐµÑ,ÐÐ¾Ð»ÐµÑÐ»Ð°Ð²ÑÐµÑ,ãã³ãã©ã¦,BolesÅawiec", :latitude => "51.26418", :longitude => "15.5697").save
City.new(:country_id => "181", :name => "Boguszow-Gorce", :aliases => "Bogushov-Gorce,Boguszow,Boguszow-Gorce,BoguszÃ³w,BoguszÃ³w-Gorce,Gottesberg,bogushufu=gorutsu~e,ÐÐ¾Ð³ÑÑÐ¾Ð²-ÐÐ¾ÑÑÐµ,ãã°ã·ã¥ãï¼ã´ã«ãã§,BoguszÃ³w-Gorce", :latitude => "50.75", :longitude => "16.2").save
City.new(:country_id => "181", :name => "Bogatynia", :aliases => "Bogatina,Bogatynia,Reichenau,ÐÐ¾Ð³Ð°ÑÐ¸ÑÐ°,Bogatynia", :latitude => "50.90747", :longitude => "14.95634").save
City.new(:country_id => "181", :name => "Bierun", :aliases => "Bierun,Bierun Stary,BieruÅ,BieruÅ Stary,BieruÅ", :latitude => "50.09", :longitude => "19.09291").save
City.new(:country_id => "181", :name => "Bielsko-Biala", :aliases => "Bel'sko-Bjala,Bel'sko-Bjalo,Belsko-Bjala,BeÄ¼sko-Bjala,Biala,Biala Krakowska,BiaÅa,BiaÅa Krakowska,Bielsko-Biala,Bielsko-BiaÅa,Bilsko,Byala,BÃ­lsko,byerusuko=byawa,ÐÐµÐ»ÑÑÐºÐ¾-ÐÑÐ»Ð°,ÐÐµÐ»ÑÑÐºÐ¾-ÐÑÐ»Ð¾,ãã§ã«ã¹ã³ï¼ãã£ã¯,Bielsko-BiaÅa", :latitude => "49.81667", :longitude => "19.03333").save
City.new(:country_id => "181", :name => "Bielawa", :aliases => "Bielawa,Langenbielau,Bielawa", :latitude => "50.69075", :longitude => "16.623").save
City.new(:country_id => "181", :name => "Bialogard", :aliases => "Belgard,Bialogard,Bialogrod,BiaÅogard,BiaÅogrod,Bjalograd,ÐÑÐ°Ð»Ð¾Ð³ÑÐ°Ð´,BiaÅogard", :latitude => "54.00696", :longitude => "15.98751").save
City.new(:country_id => "181", :name => "Belchatow", :aliases => "Belchatow,Belhatova,Belkhatov,Belkhatuv,BeÅchatÃ³w,ÐÐµÐ»ÑÐ°ÑÐ¾Ð²,ÐÐµÐ»ÑÐ°ÑÑÐ²,BeÅchatÃ³w", :latitude => "51.36883", :longitude => "19.35671").save
City.new(:country_id => "181", :name => "Bedzin", :aliases => "Bedzin,Bendzin,Bendzina,BÄdzin,ÐÐµÐ½Ð´Ð·Ð¸Ð½,BÄdzin", :latitude => "50.32607", :longitude => "19.12565").save
City.new(:country_id => "181", :name => "Andrychow", :aliases => "Andrychow,AndrychÃ³w,AndrychÃ³w", :latitude => "49.85497", :longitude => "19.33834").save
City.new(:country_id => "181", :name => "Aleksandrow Lodzki", :aliases => "Aleksandrow,Aleksandrow Lodzki,AleksandrÃ³w,AleksandrÃ³w ÅÃ³dzki,ÐÐ»ÐµÐºÑÐ°Ð½Ð´ÑÐ¾Ð² ÐÐ¾ÑÑÐºÐ¸,AleksandrÃ³w ÅÃ³dzki", :latitude => "51.81965", :longitude => "19.30384").save
City.new(:country_id => "181", :name => "Jelcz Laskowice", :aliases => ",Jelcz Laskowice", :latitude => "51.02134", :longitude => "17.31649").save
