City.new(:country_id => "185", :name => "Rafah", :aliases => "Er Rafa,Rafa,Rafaa,Rafah,Rafakh,Rafaá¸©,Rafia,Rafiah,RafÄ«ah,Raphia,Rifah,RÃ fia,la fa he,rfh,rpyh,Ð Ð°ÑÐ°,Ð Ð°ÑÐ°Ñ,×¨×¤××,Ø±ÙØ­,Ø±ÙÙÙØ­Ù,ææ³èµ«,Rafaá¸©", :latitude => "31.287", :longitude => "34.25952").save
City.new(:country_id => "185", :name => "Khan Yunis", :aliases => "Hanut Yona,HanÅ«t YÅnÄ,Jan Yunis,Jan YunÃ­s,Khan Younes,Khan Younis,Khan Yumus,Khan Yunis,Khan Yunus,Khan-Junis,KhÄn YÅ«nis,KhÄn YÅ«nus,Yunas,Yunus,Ð¥Ð°Ð½-Ð®Ð½Ð¸Ñ,Ø®Ø§Ù ÙÙÙØ³,KhÄn YÅ«nis", :latitude => "31.34018", :longitude => "34.30627").save
City.new(:country_id => "185", :name => "Jabalya", :aliases => "Dzhabalija,Jabalia,Jabaliya,Jabalya,JabÄliyÄ,JabÄlyÄ,ÐÐ¶Ð°Ð±Ð°Ð»Ð¸Ñ,Ø¬Ø¨Ø§ÙÙØ§,Ø¬ÙØ¨Ø§ÙÙØ§,JabÄlyÄ", :latitude => "31.52722", :longitude => "34.48634").save
City.new(:country_id => "185", :name => "Gaza", :aliases => "Azzah,Gaza,Gaza City,Ghazah,Ghazza,Ghazzah,Ghazze,Ghazzi,Ghuzze,`Azza,`AzzÄ,gaza,ghzt,jia sa,jia sha,ÐÐ°Ð·Ð°,×¢××,ØºØ²Ø©,ã¬ã¶,å æ²,å è©,Gaza", :latitude => "31.5", :longitude => "34.46667").save
City.new(:country_id => "185", :name => "Dayr al Balah", :aliases => "Belar,Dayr al Balah,Dayr al Balaá¸©,Deir el-Balah,Der el Bela,Ø¯ÙØ± Ø§ÙØ¨ÙØ­,Dayr al Balaá¸©", :latitude => "31.41655", :longitude => "34.34525").save
City.new(:country_id => "185", :name => "Bayt La'iya", :aliases => "Bayt La'iya,Bayt Lahiya,Bayt Lahiyah,Bayt LÄhiya,Bayt LÄhiyah,Bayt LÄâÄ«yÄ,Beit Lahia,Beit Lahiya,Beit Lahya,Beit LÄhiya,Ø¨ÙØª ÙØ§Ø¦ÙØ§,Bayt LÄâÄ«yÄ", :latitude => "31.5464", :longitude => "34.49514").save
City.new(:country_id => "185", :name => "Al Burayj", :aliases => "Al Burayj,Al-Bureij,El Bureij,Al Burayj", :latitude => "31.43944", :longitude => "34.40306").save
City.new(:country_id => "185", :name => "Yattah", :aliases => "Jatta,Yatta,Yattah,YaÅ£Å£ah,Yaá¹­á¹­a,Yuta,YaÅ£Å£ah", :latitude => "31.45", :longitude => "35.08333").save
City.new(:country_id => "185", :name => "Tulkarm", :aliases => "Keram,Toelkarem,Tul Kerem,Tul'karm,Tulkarem,Tulkarm,TÅ«l Kerem,twl krm,twlkrm,Å¢Å«lkarm,Ð¢ÑÐ»ÑÐºÐ°ÑÐ¼,××× ××¨×,Ø·ÙÙÙØ±Ù,Å¢Å«lkarm", :latitude => "32.31083", :longitude => "35.02583").save
City.new(:country_id => "185", :name => "Tubas", :aliases => "Tubas,Å¢Å«bÄs,Å¢Å«bÄs", :latitude => "32.32139", :longitude => "35.36917").save
City.new(:country_id => "185", :name => "Ramallah", :aliases => "Rahm Alla,Ram Allah,Ramala,Ramalla,Ramallah,Ramallakh,RÄm AllÄh,la mu an la,ram allh,Ð Ð°Ð¼Ð°Ð»Ð°,Ð Ð°Ð¼Ð°Ð»Ð»Ð°,Ð Ð°Ð¼Ð°Ð»Ð»Ð°Ñ,×¨×××××,Ø±Ø§Ù Ø§ÙÙÙ,Ø±Ø§ÙâØ§ÙÙÙ,æå§å®æ,Ramallah", :latitude => "31.9", :longitude => "35.2").save
City.new(:country_id => "185", :name => "Qalqilyah", :aliases => "Kal Kiliya,Kal'kilija,Kalkilieh,Kfar Saba,Qalkilya,Qalqiliya,Qalqilyah,Qalqilye,QalqÄ«liya,QalqÄ«lyah,QalqÄ«lye,ÐÐ°Ð»ÑÐºÐ¸Ð»Ð¸Ñ,QalqÄ«lyah", :latitude => "32.18639", :longitude => "34.96306").save
City.new(:country_id => "185", :name => "Qabatiyah", :aliases => "Kubatie,Kubatiya,Qabatiya,Qabatiyah,Qabatye,QabÄtiya,QabÄtye,QabÄÅ£Ä«yah,QabÄÅ£Ä«yah", :latitude => "32.40861", :longitude => "35.28").save
City.new(:country_id => "185", :name => "Nablus", :aliases => "Flavia Neapolis,Nablus,Nabulus,Naplouse,Naplusa,Napouse,Neapolis,NÄblus,Schechem,Shechem,Shekhem,Sichem,Siquem,Sychem,Sykhem,nabls,skm,ÐÐ°Ð±Ð»ÑÑ,×©××,ÙØ§Ø¨ÙØ³,Nablus", :latitude => "32.22111", :longitude => "35.25444").save
City.new(:country_id => "185", :name => "Janin", :aliases => "Djenin,Dschenin,Dzhanin,Engannim,Janin,JanÄ«n,Jenin,Jenine,Jinin,JÃ©nine,`Ein Gannim,g'nyn,jnyn,ÐÐ¶Ð°Ð½Ð¸Ð½,×'× ××,Ø¬ÙÙÙ,âEin GannÄ«m,JanÄ«n", :latitude => "32.45639", :longitude => "35.29583").save
City.new(:country_id => "185", :name => "Halhul", :aliases => ",á¸¨alá¸©Å«l", :latitude => "31.58333", :longitude => "35.11667").save
City.new(:country_id => "185", :name => "Dura", :aliases => "Dura,Durah,Dury,DÅ«rah,DÅ«rÄ,ÐÑÑÑ,DÅ«rÄ", :latitude => "31.5", :longitude => "35.03333").save
City.new(:country_id => "185", :name => "Bethlehem", :aliases => "Bayt Lahm,Bayt Laá¸©m,Beit Lahm,Beit Lehem,Beitheal,Belem,Belen,Belen de Juda,BelÃ©m,BelÃ©n,BelÃ©n de JudÃ¡,Bet-Lehem,Bet-LeÄ¥em,Bethleem,Bethleem Efrata,Bethlehem,BethlÃ©em,Betlehem,Betlejem,Betlem,Betlemme,Betleyem,BÃ¨tleyÃ¨m,Vifleem,bedeullehem,beit-lahmi,betsurehemu,bo li heng,byt lhm,ÎÎ·Î¸Î»ÎµÎ­Î¼,ÐÐ¸ÑÐ»ÐµÐµÐ¼,ÐÑÑÐ»ÐµÑÐ¼,×××ª ×××,Ø¨ÙØª ÙØ­Ù,áááá-ááá°áá,ããã¬ãã ,ä¼¯å©æ,ë² ë¤ë í´,Bethlehem", :latitude => "31.71667", :longitude => "35.2").save
City.new(:country_id => "185", :name => "Bayt Jala", :aliases => "Bayt Jala,Bayt JÄlÄ,Beit Jala,Beit JÄlÄ,Bayt JÄlÄ", :latitude => "31.71667", :longitude => "35.18333").save
City.new(:country_id => "185", :name => "Balatah", :aliases => "Balata,Balatah,BalÄta,BalÄÅ£ah,BalÄÅ£ah", :latitude => "32.205", :longitude => "35.28472").save
City.new(:country_id => "185", :name => "Az Zahiriyah", :aliases => "Ad Dahiriyah,Adh Dhahiriya,Az Zahiriyah,AzÌ§ ZÌ§ÄhirÄ«yah,Aá¸ á¸ÄhirÄ«yah,Debir,Devir,DevÄ«r,Dhahiriya,DhÄhirÄ«ya,Ed Dhaherie,Edh Dhahiriya,Edh Dhahriye,Edh Dhairiya,Edh DhÄhrÄ«ye,Edh DhÄiriya,El Dahaheriya,Eá¸h á¸hÄhiriya,AzÌ§ ZÌ§ÄhirÄ«yah", :latitude => "31.41667", :longitude => "34.96667").save
City.new(:country_id => "185", :name => "Ar Ram", :aliases => "Ar Ram,Ar RÄm,Er Ram,Er RÄm,Ram,RÄm,Ar RÄm", :latitude => "31.85", :longitude => "35.23333").save
City.new(:country_id => "185", :name => "Jericho", :aliases => "Ariha,ArÄ«á¸©Ä,Eriha,Erihon,ErÄ«ha,Gerico,Ierikhon,Jericho,Jerichonas,Jerico,JericÃ³,Jerihon,Jerika,Jerikhon,Jeriko,Jerycho,JÃ©richo,JÄrika,Yeriho,YerÄ«hÅ,Yirihu,YirÄ«á¸©Å«,aryha,eriko,jie li ke,yryhw,ÐÑÐ¸ÑÐ¾Ð½,ÐÐµÑÐ¸ÑÐ¾Ð½,ÐÐµÑÐ¸ÑÐ¾Ð½,××¨×××,Ø£Ø±ÙØ­Ø§,Ø§Ø±ÛØ­Ø§,ã¨ãªã³,æ°éç§,Jericho", :latitude => "31.86667", :longitude => "35.45").save
City.new(:country_id => "185", :name => "Al Yamun", :aliases => "Al Yamun,Al YÄmÅ«n,El Yamun,El YÄmÅ«n,Yamun,YÄmÅ«n,Al YÄmÅ«n", :latitude => "32.4825", :longitude => "35.2275").save
City.new(:country_id => "185", :name => "Hebron", :aliases => "Al Khalil,Al KhalÄ«l,El Khalil,El Khulil,Habrun,Hebrom,Hebron,HebrÃ³n,Hevron,HevrÅn,HÃ©bron,Khalil-el-Rahman,Khevron,alkhlyl,hbrwn,heburon,Ð¥ÐµÐ²ÑÐ¾Ð½,×××¨××,Ø§ÙØ®ÙÙÙ,á¸¨abrÅ«n,ããã­ã³,Hebron", :latitude => "31.53333", :longitude => "35.1").save
City.new(:country_id => "185", :name => "Al Birah", :aliases => "Al Bira,Al Birah,Al BÄ«rah,Al'-Bira,Be-erot,Be-eroth,Be-Ärot,Be-Äroth,Bira,Birah,Bire,BÄ«ra,BÄ«rah,BÄ«re,El Bira,El BÄ«ra,ÐÐ»Ñ-ÐÐ¸ÑÐ°,Al BÄ«rah", :latitude => "31.9", :longitude => "35.21667").save
City.new(:country_id => "185", :name => "East Jerusalem", :aliases => "Aust-Jerusalem,Jerusalem East,Jerusalem-Est,JÃ©rusalem-Est,OEstra Jerusalem,Ost-Jerusalem,Ostjerusalem,lqds alshrqyt,mzrh yrwslym,Ãstra Jerusalem,Ãst-Jerusalem,Ãstjerusalem,×××¨× ××¨××©×××,ÙÙØ¯Ø³ Ø§ÙØ´Ø±ÙÙØ©,East Jerusalem", :latitude => "31.78336", :longitude => "35.23388").save
