City.new(:country_id => "188", :name => "Villarrica", :aliases => "Vil'jarrika,Viljarika,Villa Rica,Villarrica,Villarrica del Espiritu Santo,Villarrica del EspÃ­ritu Santo,ÐÐ¸Ð»ÑÑÑÑÐ¸ÐºÐ°,Villarrica", :latitude => "-25.75", :longitude => "-56.43333").save
City.new(:country_id => "188", :name => "Villa Elisa", :aliases => "Colonia Eliza,Villa Elisa,Villa Elisa", :latitude => "-25.36667", :longitude => "-57.61667").save
City.new(:country_id => "188", :name => "San Lorenzo", :aliases => "San Lorenzo,San Lorenzo del Campo Grande,San Lorenzo", :latitude => "-25.33333", :longitude => "-57.53333").save
City.new(:country_id => "188", :name => "San Antonio", :aliases => ",San Antonio", :latitude => "-25.38333", :longitude => "-57.63333").save
City.new(:country_id => "188", :name => "Presidente Franco", :aliases => "Presidente Franco,Puerto Presidente Franco,Presidente Franco", :latitude => "-25.53333", :longitude => "-54.61667").save
City.new(:country_id => "188", :name => "Pilar", :aliases => "Pilar,Pilar", :latitude => "-26.86667", :longitude => "-58.38333").save
City.new(:country_id => "188", :name => "Nemby", :aliases => "Nemby,San Lorenzo de la Frontera,Nemby", :latitude => "-25.36667", :longitude => "-57.6").save
City.new(:country_id => "188", :name => "Limpio", :aliases => ",Limpio", :latitude => "-25.18333", :longitude => "-57.53333").save
City.new(:country_id => "188", :name => "Lambare", :aliases => "Lambare,LambarÃ©,LambarÃ©", :latitude => "-25.35", :longitude => "-57.65").save
City.new(:country_id => "188", :name => "Itaugua", :aliases => "Itaugua,ItauguÃ¡,ItauguÃ¡", :latitude => "-25.38333", :longitude => "-57.33333").save
City.new(:country_id => "188", :name => "Ita", :aliases => ",ItÃ¡", :latitude => "-25.48333", :longitude => "-57.35").save
City.new(:country_id => "188", :name => "Fernando de la Mora", :aliases => "Fernando de la Mora,Fernando de la Mora", :latitude => "-25.31667", :longitude => "-57.6").save
City.new(:country_id => "188", :name => "Encarnacion", :aliases => "Ehnkarnas'on,Encarnacion,EncarnaciÃ³n,Enkarnasjonas,en ka na xi weng,Ð­Ð½ÐºÐ°ÑÐ½Ð°ÑÑÐ¾Ð½,æ©å¡çº³è¥¿ç¿,EncarnaciÃ³n", :latitude => "-27.33333", :longitude => "-55.9").save
City.new(:country_id => "188", :name => "Coronel Oviedo", :aliases => "Ajos,Coronel Oviedo,Koronel'-Ov'edo,ÐÐ¾ÑÐ¾Ð½ÐµÐ»Ñ-ÐÐ²ÑÐµÐ´Ð¾,Coronel Oviedo", :latitude => "-25.41667", :longitude => "-56.45").save
City.new(:country_id => "188", :name => "Concepcion", :aliases => "Concepcion,ConcepciÃ³n,Konseps'on,Konsepsjonas,Villa Concepcion,Villa ConcepciÃ³n,ÐÐ¾Ð½ÑÐµÐ¿ÑÑÐ¾Ð½,ConcepciÃ³n", :latitude => "-23.40639", :longitude => "-57.43444").save
City.new(:country_id => "188", :name => "Colonia Mariano Roque Alonso", :aliases => "Colonia Mariano Roque Alonso,Colonia Roque Alonso,Mariano Roque Alonso,Colonia Mariano Roque Alonso", :latitude => "-25.16667", :longitude => "-57.55").save
City.new(:country_id => "188", :name => "Capiata", :aliases => "Capiata,CapiatÃ¡,Capista,CapiatÃ¡", :latitude => "-25.35", :longitude => "-57.41667").save
City.new(:country_id => "188", :name => "Caaguazu", :aliases => ",CaaguazÃº", :latitude => "-25.45", :longitude => "-56.01667").save
City.new(:country_id => "188", :name => "Caacupe", :aliases => "Caacupe,CaacupÃ©,CaacupÃ©", :latitude => "-25.38333", :longitude => "-57.15").save
City.new(:country_id => "188", :name => "Asuncion", :aliases => "Asounthion,Assumptio,Assuncao,AssunÃ§Ã£o,Asuncion,Asunciono,AsunciÃ³n,Asuns'jon,Asuns'on,Asunsion,Asunsjonas,La Muy Noble y Leal Ciudad de Nuestra Senora Santa Maria de la Asuncion,La Muy Noble y Leal Ciudad de Nuestra SeÃ±ora Santa MarÃ­a de la AsunciÃ³n,Nuestra Senora Santa Maria de la Asuncion,Nuestra SeÃ±ora Santa MarÃ­a de la AsunciÃ³n,asunshion,asunsion,aswnsywn,xa sun si xxng,ya song sen,ÎÏÎ¿ÏÎ½Î¸Î¹ÏÎ½,ÐÑÑÐ½ÑÐ¸Ð¾Ð½,ÐÑÑÐ½ÑÑÐ¹Ð¾Ð½,ÐÑÑÐ½ÑÑÐ¾Ð½,××¡×× ×¡×××,Ø¢Ø³ÙÙØ³ÛÙÙ,Ø£Ø³ÙÙØ³ÙÙÙ,à¸­à¸°à¸à¸¸à¸à¸à¸´à¸­à¸­à¸,á á±áá²á®á,ã¢ã¹ã³ã·ãªã³,äºæ¾æ£®,ìììì¨,AsunciÃ³n", :latitude => "-25.30066", :longitude => "-57.63591").save
