City.new(:country_id => "191", :name => "Zimnicea", :aliases => "Zimnicea,Zimnicea", :latitude => "43.66667", :longitude => "25.36667").save
City.new(:country_id => "191", :name => "Zalau", :aliases => "Zalau,Zalehu,ZalÄu,Zelau,Zilah,ÐÐ°Ð»ÑÑ,ZalÄu", :latitude => "47.2", :longitude => "23.05").save
City.new(:country_id => "191", :name => "Vulcan", :aliases => ",Vulcan", :latitude => "45.38333", :longitude => "23.26667").save
City.new(:country_id => "191", :name => "Voluntari", :aliases => "Cetatea Voluntareasca,Cetatea VoluntÄreascÄ,Parcu Voluntarilor,Stefanestii Noi,StefÄneÅtii Noi,Voluntari,ÐÐ¾Ð»ÑÐ½ÑÐ°ÑÐ¸,Voluntari", :latitude => "44.46667", :longitude => "26.13333").save
City.new(:country_id => "191", :name => "Viseu de Sus", :aliases => "Felsoviso,FelsÃ¶visÃ³,Visauel-de-Sus,Visaul-de-Sus,Viseu,Viseu de Sus,Viseul,Viseul de Sus,Visuel de-Sus,ViÅeu,ViÅeu de Sus,ViÅeul,ViÅeul de Sus,ViÅuel de-Sus,ViÅÄuel-de-Sus,ViÅÄul-de-Sus,ViÅeu de Sus", :latitude => "47.71667", :longitude => "24.43333").save
City.new(:country_id => "191", :name => "Vatra Dornei", :aliases => "Dorna Vatra,Vatra Dornei,Vatra Dornei", :latitude => "47.35", :longitude => "25.36667").save
City.new(:country_id => "191", :name => "Vaslui", :aliases => "Vaslui,Vasluiul,Vasluj,Vaszlo,VÃ¡szlÃ³,ÐÐ°ÑÐ»ÑÐ¹,Vaslui", :latitude => "46.63333", :longitude => "27.73333").save
City.new(:country_id => "191", :name => "Urziceni", :aliases => ",Urziceni", :latitude => "44.71667", :longitude => "26.63333").save
City.new(:country_id => "191", :name => "Turnu Magurele", :aliases => "Turnu Magurele,Turnu MÄgurele,Turnul-Magurele,Turnul-MÄgurele,Turnu MÄgurele", :latitude => "43.75", :longitude => "24.86667").save
City.new(:country_id => "191", :name => "Turda", :aliases => "Thorenburg,Torda,Turda,to~uruda,Ð¢ÑÑÐ´Ð°,ãã¥ã«ã,Turda", :latitude => "46.56667", :longitude => "23.78333").save
City.new(:country_id => "191", :name => "Tulcea", :aliases => "Aegyssos,Tulca,Tulcea,Tulcha,Tulcia,Tulcsa,Tulcza,Tultscha,TulÃ§a,TulÄia,twlchy,Ð¢ÑÐ»ÑÐ°,Ø·ÙÙÚÛ,Tulcea", :latitude => "45.16667", :longitude => "28.8").save
City.new(:country_id => "191", :name => "Tirgu Secuiesc", :aliases => "Kezdivasarhely,Kezoi-Vasarmely,KÃ¨zdivÃ¡sÃ rhely,KÃ¨zoi-Vasarmely,Tarcu Sacuesc,Targu-Sacuesc,Targul Sacuesc,Tirgu Secuesc,Tirgu Secuiesc,Tirgul Sacuesc,TÃ¢rgu-SÄcuesc,TÃ¢rgul SÄcuesc,TÃ®rgu Secuesc,TÃ®rgu Secuiesc,TÃ®rgul SÄcuesc,TÃ®rgu Secuiesc", :latitude => "46", :longitude => "26.13333").save
City.new(:country_id => "191", :name => "Tirgu Neamt", :aliases => "Neamtzu,Pomete,Pometea,Targu-Neamt,Targul Neamt,Tirgu Neamt,Tuteni,TÃ¢rgu-NeamÅ£,TÃ¢rgul NeamÅ£,TÃ®rgu NeamÅ£,Å¢uÅ£eni,TÃ®rgu NeamÅ£", :latitude => "47.2", :longitude => "26.36667").save
City.new(:country_id => "191", :name => "Targu-Mures", :aliases => "Maros-Vasarhely,Maros-VÃ¡sÃ¡rhely,Marosvasarhely,MarosvÃ¡sÃ¡rhely,Muresh,Neumarkt,Neumarkt am Mieresch,Novum Forum Siculorum,Targu Mures,Targul-Mures,Tirgu Mures,Turgul Mures,Tyrgu-Muresh,TÃ¢rgu MureÅ,TÃ¢rgul-MureÅ,TÃ®rgu MureÅ,trgw mwrs,Ð¢ÑÑÐ³Ñ-ÐÑÑÐµÑ,××¨×× ×××¨×©,TÃ¢rgu-MureÅ", :latitude => "46.54245", :longitude => "24.55747").save
City.new(:country_id => "191", :name => "Targu Jiu", :aliases => "Jiu,Targu Jiu,Targul-Jiu,Tirgu Jiu,Turgu Zhiu,TÃ¢rgu Jiu,TÃ¢rgul-Jiu,TÃ®rgu Jiu,Zsilvasarhely,ZsilvÃ¡sÃ¡rhely,trgw z'yw,Ð¢ÑÑÐ³Ñ ÐÐ¸Ñ,××¨×× ×'××,TÃ¢rgu Jiu", :latitude => "45.05", :longitude => "23.28333").save
City.new(:country_id => "191", :name => "Targoviste", :aliases => "Targoviste,Tirgoviste,Turgovishhe,TÃ¢rgoviste,TÃ¢rgoviÅte,TÃ®rgoviÅte,to~urugovu~ishute,Ð¢ÑÑÐ³Ð¾Ð²Ð¸ÑÐµ,ãã¥ã«ã´ã´ã£ã·ã¥ã,TÃ¢rgoviÅte", :latitude => "44.93333", :longitude => "25.45").save
City.new(:country_id => "191", :name => "Timisoara", :aliases => "Freidorf,Josefvarosa,Josephs-Stadt,Jozsefvaros,JÃ³sefvÃ¡rosa,JÃ³zsefvÃ¡ros,Kendetelep,Szabadfalu,Temeschburg,Temeschwar,Temesvar,Temesvarinum,TemesvÃ¡r,Temeswar,TemeÅvar,TemeÅ¡vÃ¡r,Temishvar,Temisoara,Temisvar,TemiÅoara,TemiÅ¡var,Timishoara,Timisoara,TimiÅoara,TimiÅ¡oara,timishoara,timisyoala,tmshwar,tymyshwara,Ð¢ÐµÐ¼Ð¸ÑÐ²Ð°Ñ,Ð¢Ð¸Ð¼Ð¸ÑÐ¾Ð°ÑÐ°,×××××©×××¨×,ØªÙÙÙØ´ÙØ§Ø±Ø§,Ø·ÙØ´ÙØ§Ø±,ãã£ãã·ã§ã¢ã©,í°ë¯¸ì¼ìë¼,TimiÅoara", :latitude => "45.74944", :longitude => "21.22722").save
City.new(:country_id => "191", :name => "Tecuci", :aliases => "Tecuci,Tekuch,Ð¢ÐµÐºÑÑ,Tecuci", :latitude => "45.86667", :longitude => "27.41667").save
City.new(:country_id => "191", :name => "Suceava", :aliases => "Suceava,Suchava,Suczawa,Szucsava,SzucsÃ¡va,suchavu~a,Ð¡ÑÑÐ°Ð²Ð°,×¡××¦'×××,×©×Ö¸×¥,ã¹ãã£ã´ã¡,Suceava", :latitude => "47.63333", :longitude => "26.25").save
City.new(:country_id => "191", :name => "Slatina", :aliases => "Slatina,Striharet,Ð¡Ð»Ð°ÑÐ¸Ð½Ð°,Slatina", :latitude => "44.43333", :longitude => "24.36667").save
City.new(:country_id => "191", :name => "Simleu Silvaniei", :aliases => "Simleu Silvaniei,Simleul Silvaiei,Szilagysomlyo,SzilÃ¡gysomlyÃ³,Åimleu Silvaniei,Åimleu Silvaniei", :latitude => "47.23333", :longitude => "22.8").save
City.new(:country_id => "191", :name => "Sighetu Marmatiei", :aliases => "Maramaros Szighet,Maramarossziget,Marmaros Sihot,Marmarosska,MarmaroÅ¡ Sihot,MÃ¡ramarossziget,Sighet,Sighetu Marmatiei,Sighetu MarmaÅ£iei,sygt,Ð¡Ð¸Ð³ÑÑ ÐÐ°ÑÐ¼Ð°ÑÐ¾ÑÑÐºÐ¸Ð¹,×¡×××,Sighetu MarmaÅ£iei", :latitude => "47.93333", :longitude => "23.88333").save
City.new(:country_id => "191", :name => "Sibiu", :aliases => "Hermannstadt,Nagy-Szeben,Nagy-SzÃ©ben,Nagyszeben,Sibiu,Sybin,Szeben,shibiu,sibiu,Ð¡Ð¸Ð±Ð¸Ñ,ã·ãã¦,ìë¹ì°,Sibiu", :latitude => "45.8", :longitude => "24.15").save
City.new(:country_id => "191", :name => "Sfantu-Gheorghe", :aliases => "Sepsiszentgyorgy,SepsiszentgyÅrgy,Sfantu-Gheorghe,Sfantul,Sfantul-Gheorghe,Sfehntu-Georg,Sfintu Gheorghe,SfÃ¢ntu-Gheorghe,SfÃ¢ntul,SfÃ¢ntul-Gheorghe,SfÃ®ntu Gheorghe,Ð¡ÑÑÐ½ÑÑ-ÐÐµÐ¾ÑÐ³,SfÃ¢ntu-Gheorghe", :latitude => "45.86667", :longitude => "25.78333").save
City.new(:country_id => "191", :name => "Sebes", :aliases => "Muehlbach,MÃ¼hlbach,Sebes,Sebesh,SebeÅ,Ð¡ÐµÐ±ÐµÑ,SebeÅ", :latitude => "45.96667", :longitude => "23.56667").save
City.new(:country_id => "191", :name => "Satu Mare", :aliases => "Satmar,Satu Mare,Satu-Mare,Satul Mare,Szathmar,Szatmar,Szatmar-Nemeti,Szatmarnemeti,SzatmÃ¡r,SzatmÃ¡r-NÃ©meti,SzatmÃ¡rnÃ©meti,SÄtmar,Ð¡Ð°ÑÑ ÐÐ°ÑÐµ,Ð¡Ð°ÑÑ-ÐÐ°ÑÐµ,×¡×Ö·×××Ö·×¨,×¡××× ×××¨×,×¡×××××¨,×¡×× ×××¨×,ãµãã¥ã»ãã¼ã¬,Satu Mare", :latitude => "47.8", :longitude => "22.88333").save
City.new(:country_id => "191", :name => "Salonta", :aliases => "Nagyszalonta,Salonta,Ð¡Ð°Ð»Ð¾Ð½ÑÐ°,Salonta", :latitude => "46.8", :longitude => "21.65").save
City.new(:country_id => "191", :name => "Sacele", :aliases => "Hetfalu,Sehchele,Sieben Dorfer,Sieben DÃ¶rfer,Ð¡ÑÑÐµÐ»Ðµ,SÄcele", :latitude => "45.6174", :longitude => "25.69427").save
City.new(:country_id => "191", :name => "Rosiori de Vede", :aliases => "Roisori de Vede,RoiÅori de Vede,Rosiori de Vede,Rosiorii de Vede,RoÅiori de Vede,RoÅiorii de Vede,RoÅiori de Vede", :latitude => "44.11667", :longitude => "24.98333").save
City.new(:country_id => "191", :name => "Roman", :aliases => "Roman,×¨××××,Roman", :latitude => "46.91667", :longitude => "26.91667").save
City.new(:country_id => "191", :name => "Risnov", :aliases => "Barcarozsnyo,BarcarozsnyÃ³,R'shnov,Rasnov,Risnov,Rosenau,Ryshnov,RÃ¢Ånov,RÃ®Ånov,Ð ÑÑÐ½Ð¾Ð²,Ð ÑÑÐ½Ð¾Ð²,RÃ®Ånov", :latitude => "45.58333", :longitude => "25.45").save
City.new(:country_id => "191", :name => "Ramnicu Valcea", :aliases => "Ramnicu Valcea,Ramnicul Valcea,Rimnicu Vilcea,RÃ¢mnicu VÃ¢lcea,RÃ¢mnicul VÃ¢lcea,RÃ®mnicu VÃ®lcea,RÃ¢mnicu VÃ¢lcea", :latitude => "45.1", :longitude => "24.36667").save
City.new(:country_id => "191", :name => "Rimnicu Sarat", :aliases => "Ramnicu Sarat,Ramnicul Sarat,Rimnic,Rimnicu Sarat,RÃ¢mnicu SÄrat,RÃ¢mnicul SÄrat,RÃ®mnic,RÃ®mnicu SÄrat,RÃ®mnicu SÄrat", :latitude => "45.38333", :longitude => "27.05").save
City.new(:country_id => "191", :name => "Resita", :aliases => "Recita,ReciÅ£a,Reschitz,Reschitza,Resicabanya,ResicabÃ¡nya,Resicza,Resiczabanya,ResiczabÃ¡nya,Resita,ReÅiÅ£a,ReÅiÅ£a", :latitude => "45.30083", :longitude => "21.88917").save
City.new(:country_id => "191", :name => "Reghin-Sat", :aliases => ",Reghin-Sat", :latitude => "46.78333", :longitude => "24.71667").save
City.new(:country_id => "191", :name => "Radowce", :aliases => "Radauci,Radauti,Radautio,Radautz,Radivci,Radoc,Radowce,RadÃ³c,Rehdehuci,RÄdÄutio,RÄdÄuÅ£i,Ð Ð°Ð´Ð°ÑÑÐ¸,Ð Ð°Ð´ÑÐ²ÑÑ,Ð ÑÐ´ÑÑÑÐ¸,Radowce", :latitude => "47.85", :longitude => "25.91667").save
City.new(:country_id => "191", :name => "Popesti-Leordeni", :aliases => "Popesti,Popesti-Leordeni,Popesti-Leurdeni,Popestii,Popestii-Conduratu,PopeÅti,PopeÅti-Leordeni,PopeÅti-Leurdeni,PopeÅtii,PopeÅtii-Conduratu,Popoestii-Leordeni,PopoeÅtii-Leordeni,PopeÅti-Leordeni", :latitude => "44.38333", :longitude => "26.16667").save
City.new(:country_id => "191", :name => "Ploiesti", :aliases => "Ploeshh,Ploesti,Ploeszti,PloeÅti,Ploiesti,PloieÅti,plwyst,plwysty,ÐÐ»Ð¾ÐµÑ,×¤××××©×,×¤××××©××,PloieÅti", :latitude => "44.95", :longitude => "26.01667").save
City.new(:country_id => "191", :name => "Pitesti", :aliases => "Pitesci,PitescÃ¯,Piteshh,Piteshti,Pitesti,PiteÅti,pytst,ÐÐ¸ÑÐµÑ,×¤×××©×,PiteÅti", :latitude => "44.85", :longitude => "24.86667").save
City.new(:country_id => "191", :name => "Piatra Neamt", :aliases => "Piatra Neamt,Piatra NeamÅ£,Piatra-Neamt,Piatra NeamÅ£", :latitude => "46.91667", :longitude => "26.33333").save
City.new(:country_id => "191", :name => "Petrosani", :aliases => "Petrosani,Petroseni,Petroshani,Petrozseny,PetrozsÃ©ny,PetroÅani,PetroÅeni,Pietrosani,PietroÅani,ÐÐµÑÑÐ¾ÑÐ°Ð½Ð¸,PetroÅani", :latitude => "45.41667", :longitude => "23.36667").save
City.new(:country_id => "191", :name => "Petrila", :aliases => ",Petrila", :latitude => "45.45", :longitude => "23.41667").save
City.new(:country_id => "191", :name => "Pantelimon", :aliases => ",Pantelimon", :latitude => "44.45", :longitude => "26.2").save
City.new(:country_id => "191", :name => "Orastie", :aliases => "Broos,Orastie,Orehshtie,OrÄÅtie,ÐÑÑÑÑÐ¸Ðµ,OrÄÅtie", :latitude => "45.83333", :longitude => "23.2").save
City.new(:country_id => "191", :name => "Oradea", :aliases => "Grosswardein,GroÃwardein,Nagy-Varad,Nagy-VÃ¡rad,Nagyvarad,NagyvÃ¡rad,Oradea,Oradea-Mare,Oradja,Varadinum,Velky Varadin,VelkÃ½ VaradÃ­n,ao la di ya,oladea,oradea,orateya,varadinum,ÐÑÐ°Ð´Ñ,×××¨×××,à®à®°à®¾à®à¯à®¯à®¾,ãªã©ãã¢,å¥¥æè¿ªäº,ì¤ë¼ë°ì,Oradea", :latitude => "47.06667", :longitude => "21.93333").save
City.new(:country_id => "191", :name => "Oltenita", :aliases => "Oltenice,Oltenita,Oltenitao,OlteniÅ£a,ÐÐ»ÑÐµÐ½Ð¸ÑÐµ,OlteniÅ£a", :latitude => "44.08333", :longitude => "26.63333").save
City.new(:country_id => "191", :name => "Odorheiu Secuiesc", :aliases => "Oderhellen,Odorheiu,Odorheiu Secuiesc,Odorheiul Secuiesc,Szekelyudvarhely,SzÃ©kelyudvarhely,Odorheiu Secuiesc", :latitude => "46.3", :longitude => "25.3").save
City.new(:country_id => "191", :name => "Ocna Mures", :aliases => "Ocna Mures,Ocna MureÅ,Ocna-Muresului,Ocna-MureÅului,Ocna MureÅ", :latitude => "46.38333", :longitude => "23.85").save
City.new(:country_id => "191", :name => "Navodari", :aliases => "Caracoim,Caracoium,Karakoium,Navodari,Nehvodari,NÄvodari,ÐÑÐ²Ð¾Ð´Ð°ÑÐ¸,NÄvodari", :latitude => "44.31667", :longitude => "28.6").save
City.new(:country_id => "191", :name => "Motru", :aliases => ",Motru", :latitude => "44.80333", :longitude => "22.97194").save
City.new(:country_id => "191", :name => "Moreni", :aliases => ",Moreni", :latitude => "44.98333", :longitude => "25.65").save
City.new(:country_id => "191", :name => "Moinesti", :aliases => ",MoineÅti", :latitude => "46.46667", :longitude => "26.48333").save
City.new(:country_id => "191", :name => "Mizil", :aliases => "Mizil,Mizilue,ÐÐ¸Ð·Ð¸Ð»,Mizil", :latitude => "45.01667", :longitude => "26.45").save
City.new(:country_id => "191", :name => "Miercurea-Ciuc", :aliases => "Csikszereda,CsÃ­kszereda,Mercurea Ciuc,Merkurja-Chuk,Miercurea Ciuc,Miercurea-Ciuc,Miercurea-Ciucului,ÐÐµÑÐºÑÑÑ-Ð§ÑÐº,Miercurea-Ciuc", :latitude => "46.35", :longitude => "25.8").save
City.new(:country_id => "191", :name => "Medias", :aliases => "Aronyosmeggyes,AronyÃ³smeggyes,Medgyes,Medias,Mediasch,MediaÅ,Medivisch,MediaÅ", :latitude => "46.16667", :longitude => "24.35").save
City.new(:country_id => "191", :name => "Medgidia", :aliases => "Mecidiye,Medgidia,Medjidia,Medzhidija,mjydyh,ÐÐµÐ´Ð¶Ð¸Ð´Ð¸Ñ,ÙØ¬ÛØ¯ÛÙ,Medgidia", :latitude => "44.25", :longitude => "28.28333").save
City.new(:country_id => "191", :name => "Margita", :aliases => ",Margita", :latitude => "47.35", :longitude => "22.33333").save
City.new(:country_id => "191", :name => "Mangalia", :aliases => "Mangalia,Mangalija,Mangalla,Mankalya,ÐÐ°Ð½Ð³Ð°Ð»Ð¸Ñ,Mangalia", :latitude => "43.8", :longitude => "28.58333").save
City.new(:country_id => "191", :name => "Lupeni", :aliases => "Luoeni,Lupeni,Lupeny,LupÃ©ny,ÐÑÐ¿ÐµÐ½Ð¸,Lupeni", :latitude => "45.35", :longitude => "23.23333").save
City.new(:country_id => "191", :name => "Lugoj", :aliases => "Deutsch-Lugosch,Lugas,Lugoi,Lugoj,Lugos,Lugosch,Lugozh,Nemet-Lugos,NÃ©met-Lugos,Olah-Lugos,OlÃ¡h-Lugos,Walachisch-Lugosch,ÐÑÐ³Ð¾Ð¶,Lugoj", :latitude => "45.68861", :longitude => "21.90306").save
City.new(:country_id => "191", :name => "Ludus", :aliases => "Ludas,Ludos,Ludus,LuduÅ,LuduÅ", :latitude => "46.48333", :longitude => "24.1").save
City.new(:country_id => "191", :name => "Iasi", :aliases => "Copou,Copou-Targ,Copou-TÃ¢rg,Galata,Iasi,Iasio,Iassy,IaÅi,Ilasi,Jash,Jasi,Jassenmarkt,Jassy,Jaszvasar,JaÃenmarkt,JÃ¡szvÃ¡sÃ¡r,Munteni,Pacurari,Pacuret,Podgoria,PÄcurari,PÄcureÅ£,Socol,Socola,Yas,Yashi,Yassi,Yassy,YaÅ,ya xi,yashi,yashy,ÎÎ¬ÏÎ¹Î¿,Ð¯ÑÐ¸,Ð¯ÑÑÑ,Ð¯Ñ,×××©×,ÙØ§Ø´Ù,ã¤ã·,éè¥¿,IaÅi", :latitude => "47.16667", :longitude => "27.6").save
City.new(:country_id => "191", :name => "Husi", :aliases => "Gusi,Husi,HuÅi,ÐÑÑÐ¸,HuÅi", :latitude => "46.67361", :longitude => "28.05944").save
City.new(:country_id => "191", :name => "Hunedoara", :aliases => "Hunedoara,Khunedoara,Vajdahunyad,Ð¥ÑÐ½ÐµÐ´Ð¾Ð°ÑÐ°,××× ××××¨×,Hunedoara", :latitude => "45.75", :longitude => "22.9").save
City.new(:country_id => "191", :name => "Gura Humorului", :aliases => "Gura Homorului,Gura Humorului,Gura-Humourlui,Gura Humorului", :latitude => "47.55", :longitude => "25.9").save
City.new(:country_id => "191", :name => "Giurgiu", :aliases => "Giurgiu,Gjurgevo,Gyurgyevo,GyurgyevÃ³,Yergogu,YergoÄu,giurgiu,ÐÑÑÐ³ÐµÐ²Ð¾,ááá£á ááá£,Giurgiu", :latitude => "43.88333", :longitude => "25.96667").save
City.new(:country_id => "191", :name => "Gherla", :aliases => "Gerla,Gherla,Szamosujvar,SzamosÃºjvÃ¡r,ÐÐµÑÐ»Ð°,Gherla", :latitude => "47.03333", :longitude => "23.91667").save
City.new(:country_id => "191", :name => "Gheorgheni", :aliases => "Gheorghem,Gheorgheni,Gheorghieni,Gyergoszentmiklos,Gyergyo,Gyergyoszentmiklos,GyergyÃ³szentmiklÃ³s,GyergÃ²szentmiklÃ²s,Gheorgheni", :latitude => "46.71667", :longitude => "25.61667").save
City.new(:country_id => "191", :name => "Galati", :aliases => "Galac,Galacz,Galati,Galatz,Galaz,GalaÅ£i,GaÅacz,jia la ci,ÐÐ°Ð»Ð°Ñ,×××××¥,××××¥,å æè¨,GalaÅ£i", :latitude => "45.45", :longitude => "28.05").save
City.new(:country_id => "191", :name => "Gaesti", :aliases => ",GÄeÅti", :latitude => "44.71667", :longitude => "25.31667").save
City.new(:country_id => "191", :name => "Focsani", :aliases => "Focsani,FocÅani,Foksany,Fokshani,FoksÃ¡ny,Ð¤Ð¾ÐºÑÐ°Ð½Ð¸,×¤××§×©××,×¤××§×©×× ×,FocÅani", :latitude => "45.7", :longitude => "27.18333").save
City.new(:country_id => "191", :name => "Filiasi", :aliases => "Filias,Filiasi,FiliaÅ,FiliaÅi,FiliaÅi", :latitude => "44.55", :longitude => "23.51667").save
City.new(:country_id => "191", :name => "Fetesti", :aliases => ",FeteÅti", :latitude => "44.38333", :longitude => "27.83333").save
City.new(:country_id => "191", :name => "Falticeni", :aliases => "Buciumeni,Falticeni,Falticenii Vechi,Fehlticheni,FÄlticeni,FÄlticenii Vechi,Gradinile,GrÄdinile,Opriseni,OpriÅeni,Tampesti,Timpesti,TÃ¢mpeÅti,TÃ®mpeÅti,Ð¤ÑÐ»ÑÐ¸ÑÐµÐ½Ð¸,FÄlticeni", :latitude => "47.45", :longitude => "26.3").save
City.new(:country_id => "191", :name => "Fogarasch", :aliases => "Fagaras,Fagaraso,Fehgehrash,Fogaras,Fogarasch,FÄgÄraso,FÄgÄraÅ,Ð¤ÑÐ³ÑÑÐ°Ñ,Fogarasch", :latitude => "45.85", :longitude => "24.96667").save
City.new(:country_id => "191", :name => "Drobeta-Turnu Severin", :aliases => "Drobeta Turnu Severin,Drobeta Turnu-Severin,Drobeta-Turnu Severin,Drubeta,Szoerenyvar,SzÃ¶rÃ©nyvÃ¡r,Turnu Severin,Turnul Severin,drobeta turnu severin,ÐÑÐ¾Ð±ÐµÑÐ° Ð¢ÑÑÐ½Ñ Ð¡ÐµÐ²ÐµÑÐ¸Ð½,Drobeta-Turnu Severin", :latitude => "44.63194", :longitude => "22.65611").save
City.new(:country_id => "191", :name => "Dragasani", :aliases => "Dragasani,Drehgehshani,DrÄgÄÅani,ÐÑÑÐ³ÑÑÐ°Ð½Ð¸,DrÄgÄÅani", :latitude => "44.65", :longitude => "24.26667").save
City.new(:country_id => "191", :name => "Dorohoi", :aliases => "Dorohoi,Dorohoiu,Dorokhoj,Dorokhoy,ÐÐ¾ÑÐ¾ÑÐ¾Ð¹,Dorohoi", :latitude => "47.95", :longitude => "26.4").save
City.new(:country_id => "191", :name => "Deva", :aliases => "Deva,Diemrich,DÃ©va,ÐÐµÐ²Ð°,Deva", :latitude => "45.88333", :longitude => "22.9").save
City.new(:country_id => "191", :name => "Dej", :aliases => "Dej,Des,DÃ©s,ÐÐµÐ¹,Dej", :latitude => "47.15", :longitude => "23.86667").save
City.new(:country_id => "191", :name => "Curtea de Arges", :aliases => "Argyasudvarhely,Curt de-Arges,Curt de-ArgeÅ,Curtea de Arges,Curtea de ArgeÅ,Curtea de ArgeÅ", :latitude => "45.13333", :longitude => "24.68333").save
City.new(:country_id => "191", :name => "Cugir", :aliases => ",Cugir", :latitude => "45.83333", :longitude => "23.36667").save
City.new(:country_id => "191", :name => "Craiova", :aliases => "Craiova,Croiova,Krajova,Krajowa,ke la yue wa,qrywbh,ÐÑÐ°Ð¹Ð¾Ð²Ð°,ÐÑÐ°ÑÐ¾Ð²Ð°,×§×¨×××××,×§×¨××××,åæç´ç¦,Craiova", :latitude => "44.31667", :longitude => "23.8").save
City.new(:country_id => "191", :name => "Corabia", :aliases => ",Corabia", :latitude => "43.78333", :longitude => "24.5").save
City.new(:country_id => "191", :name => "Constanta", :aliases => "Constanta,Constantia,Constantza,Constanza,ConstanÅ£a,Costanza,Koestence,Konstanca,Konstanco,Konstanza,Kuestence,Kustenja,Kustenje,Kustenji,Kyustendja,KÃ¶stence,KÃ¼stence,KÃ¼stenja,kang si tan cha,konseutancha,konsutantsu~a,qwnstnzh,ÐÐ¾Ð½ÑÑÐ°Ð½ÑÐ°,×§×× ×¡×× ×¦×,áááá¡á¢áááªá,ã³ã³ã¹ã¿ã³ãã¡,åº·æ¯å¦å¯,ì½ì¤íì°¨,ConstanÅ£a", :latitude => "44.18333", :longitude => "28.65").save
City.new(:country_id => "191", :name => "Comanesti", :aliases => ",ComÄneÅti", :latitude => "46.41667", :longitude => "26.43333").save
City.new(:country_id => "191", :name => "Codlea", :aliases => "Codlea,Feketehalom,Kodlja,Zeiden,ÐÐ¾Ð´Ð»Ñ,Codlea", :latitude => "45.7", :longitude => "25.45").save
City.new(:country_id => "191", :name => "Cluj-Napoca", :aliases => "Castrum Clus,Claudiopolis,Clausemburgo,Clausenburg,Cluj,Cluj-Napoca,Klausenburg,Klouz-Napoka,Klujo,Kluz,Kluz-Napoka,Kluza-Napoka,Kluzas-Napoka,Kluzh-Napoka,KluÄµo,KluÅ¼-Napoka,KluÅ¾,KluÅ¾a-Napoka,KluÅ¾as-Napoka,Koloszvar,KoloszvÃ¡r,Kolozsvar,KolozsvÃ¡r,Municipium Aelium Hadrianum Napoca,Napoca,ke lu ri-na bo ka,keullujinapoka,klwj-nabwka,klwzh-napwka,kuruju=napoka,qlwyznbwrg,qlwz'-npwqh,ÎÎ»Î¿ÏÎ¶-ÎÎ±ÏÏÎºÎ±,ÐÐ»ÑÐ¶-ÐÐ°Ð¿Ð¾ÐºÐ°,×§×××'-× ××¤××§×,×§×××'-× ×¤××§×,×§××××× ×××¨×,ÙÙÙØ¬-ÙØ§Ø¨ÙÙØ§,Ú©ÙÙÚ-ÙØ§Ù¾ÙÚ©Ø§,ã¯ã«ã¼ã¸ã¥ï¼ããã«,åå¢æ¥-çº³æ³¢å¡,í´ë£¨ì§ëí¬ì¹´,Cluj-Napoca", :latitude => "46.76667", :longitude => "23.6").save
City.new(:country_id => "191", :name => "Cisnadie", :aliases => "Cisnadie,CisnÄdie,Heltau,Nagydisznod,NagydisznÃ³d,CisnÄdie", :latitude => "45.71667", :longitude => "24.15").save
City.new(:country_id => "191", :name => "Campulung Moldovenesc", :aliases => "Campulung,Campulung Moldovenesc,Campulungul Moldov,Campulungul Moldovenesc,Cimpulung Moldovenesc,CÃ¢mpulung,CÃ¢mpulung Moldovenesc,CÃ¢mpulungul Moldov,CÃ¢mpulungul Moldovenesc,CÃ®mpulung Moldovenesc,CÃ¢mpulung Moldovenesc", :latitude => "47.53333", :longitude => "25.56667").save
City.new(:country_id => "191", :name => "Cimpia Turzii", :aliases => "Campia Turzei,Campia Turzi,Campia Turzii,Cimpia Turzii,CÃ¢mpia Turzei,CÃ¢mpia Turzi,CÃ¢mpia Turzii,CÃ®mpia Turzii,CÃ®mpia Turzii", :latitude => "46.55", :longitude => "23.88333").save
City.new(:country_id => "191", :name => "Cernavoda", :aliases => "Bogazkoey,BoÄazkÃ¶y,Cernavoda,CernavodÄ,Cherna voda,Tcherna Voda,Ð§ÐµÑÐ½Ð° Ð²Ð¾Ð´Ð°,CernavodÄ", :latitude => "44.36667", :longitude => "28.01667").save
City.new(:country_id => "191", :name => "Carei / Nagykaroly / Grosskarol", :aliases => "Careii,Careii Mare,Careii Mari,Nagy Karoly,Nagy KÃ¡roly,Nagykaroly,NagykÃ¡roly,Carei / NagykÃ¡roly / GroÃkarol", :latitude => "47.68333", :longitude => "22.46667").save
City.new(:country_id => "191", :name => "Caransebes", :aliases => "Caransebes,CaransebeÅ,Carensebes,Karansebes,Karansebeshe,KarÃ¡nsebes,ÐÐ°ÑÐ°Ð½ÑÐµÐ±ÐµÑÐµ,CaransebeÅ", :latitude => "45.41667", :longitude => "22.21667").save
City.new(:country_id => "191", :name => "Caracal", :aliases => ",Caracal", :latitude => "44.11667", :longitude => "24.35").save
City.new(:country_id => "191", :name => "Calafat", :aliases => ",Calafat", :latitude => "43.99111", :longitude => "22.93278").save
City.new(:country_id => "191", :name => "Buzau", :aliases => "Buzau,Buzeu,Buzuu,BuzÄu,ÐÑÐ·ÑÑ,BuzÄu", :latitude => "45.15", :longitude => "26.83333").save
City.new(:country_id => "191", :name => "Buhusi", :aliases => "Buhus,Buhusi,BuhuÅ,BuhuÅi,BuhuÅi", :latitude => "46.71667", :longitude => "26.7").save
City.new(:country_id => "191", :name => "Buftea", :aliases => ",Buftea", :latitude => "44.56139", :longitude => "25.94889").save
City.new(:country_id => "191", :name => "Bucuresti", :aliases => "BUH,Boekarest,Boukouresti,Bucarest,Bucaresta,Bucareste,BucarÃ¨st,Bucharest,Bucuresti,BucureÅti,Buekres,Bukarest,Bukarestas,Bukareste,Bukaresto,Bukareszt,BukareÅto,BukareÅ¡tas,Bukharest,Bukureshh,Bukuresht,Bukuresht',Bukureshta,Bukureshti,Bukurest,BukureÅ¡t,BukureÅ¡Å¥,Buxarest,BÃºkarest,BÃ»karest,BÃ¼kreÅ,bkharst,bu jia lei si te,bukaresuto,bukulesyuti,bwkharst,bwqrst,ÎÎ¿ÏÎºÎ¿ÏÏÎ­ÏÏÎ¹,ÐÑÐºÑÑÐµÑÑ,ÐÑÐºÑÑÐµÑÑÑ,ÐÑÐºÑÑÐµÑ,ÐÑÑÐ°ÑÐµÑÑ,Ô²Õ¸ÖÕ­Õ¡ÖÕ¥Õ½Õ¿,×××§×Ö·×¨×¢×©×,×××§×¨×©×,Ø¨Ø®Ø§Ø±Ø³Øª,Ø¨ÙØ®Ø§Ø±Ø³Øª,Ø¨ÛØ®Ø§Ø±ÛØ³Øª,à½à½´à¼à½à¼à½¢à½ºà¼à½¦à½²à½,áá£á¥áá áá¡á¢á,á¡á«á¨áµáµ,ãã«ã¬ã¹ã,å¸å åæ¯ç¹,ë¶ì¿ ë ìí°,BucureÅti", :latitude => "44.43225", :longitude => "26.10626").save
City.new(:country_id => "191", :name => "Breaza", :aliases => ",Breaza", :latitude => "45.18333", :longitude => "25.66667").save
City.new(:country_id => "191", :name => "Brasov", :aliases => "Brashov,Brasov,Brasso,BrassÃ³,Braszow,BraszÃ³w,Brazov,BraÅov,BraÅ¡ov,Kronstadt,Kronstant,Orasu Stalin,Orasul Stalin,OraÅu Stalin,OraÅul Stalin,beulasyobeu,brswb,burashofu,ÐÑÐ°ÑÐ¾Ð²,××¨×©××,ãã©ã·ã§ã,ë¸ë¼ì¼ë¸,BraÅov", :latitude => "45.64861", :longitude => "25.60613").save
City.new(:country_id => "191", :name => "Braila", :aliases => "Braila,Brailov,BraiÅa,BrÄila,Ibrail,ÐÑÐ°Ð¸Ð»Ð°,××¨××××,BrÄila", :latitude => "45.26667", :longitude => "27.98333").save
City.new(:country_id => "191", :name => "Brad", :aliases => ",Brad", :latitude => "46.13333", :longitude => "22.78333").save
City.new(:country_id => "191", :name => "Botosani", :aliases => "Botosani,Botoshani,Botoszany,BotoÅani,ÐÐ¾ÑÐ¾ÑÐ°Ð½Ð¸,×××××©××,BotoÅani", :latitude => "47.75", :longitude => "26.66667").save
City.new(:country_id => "191", :name => "Borsa", :aliases => ",BorÅa", :latitude => "47.65", :longitude => "24.66667").save
City.new(:country_id => "191", :name => "Bocsa", :aliases => "Bocsa,Bocsa Montana,Bocsa Romina,Bocsa-Romaana,Bocsa-Romana,BocÅa,BocÅa MontanÄ,BocÅa RomÃ®nÄ,BocÅa-RomÃ¢anÄ,BocÅa-RomÃ¢nÄ,Bogsan,BogsÃ¡n,Boksa Romana,Boksan,Boksanbanya,Bokschan,BoksÃ¡n,BoksÃ¡nbÃ¡nya,BokÅ¡a Romana,Deutsch-Bogschan,Deutsch-Bokschan,Nemet-Bogsan,Nemet-Bogschan,Nemet-Boksan,NÃ©met-BogschÃ¡n,NÃ©met-BogsÃ¡n,NÃ©met-BoksÃ¡n,Varkboksan,Vassafalva,VÃ¡rkboksÃ¡n,Wallachisch-Bokschan,Werk-Bogschan,BocÅa", :latitude => "45.37333", :longitude => "21.70917").save
City.new(:country_id => "191", :name => "Blaj", :aliases => "Balazsfalva,BalÃ¡zsfalva,Blaj,Blasendorf,ÐÐ»Ð°Ð¹,Blaj", :latitude => "46.18333", :longitude => "23.91667").save
City.new(:country_id => "191", :name => "Bistrita", :aliases => "Beszterce,Besztercze,Bistrica,Bistrita,Bistritz,BistriÅ£a,bisutoritsu~a,ÐÐ¸ÑÑÑÐ¸ÑÐ°,ãã¹ããªãã¡,BistriÅ£a", :latitude => "47.13316", :longitude => "24.50011").save
City.new(:country_id => "191", :name => "Birlad", :aliases => "Barlad,Birlad,BÃ¢rlad,BÃ®rlad,BÃ®rlad", :latitude => "46.23333", :longitude => "27.66667").save
City.new(:country_id => "191", :name => "Bals", :aliases => ",BalÅ", :latitude => "44.35", :longitude => "24.1").save
City.new(:country_id => "191", :name => "Bailesti", :aliases => ",BÄileÅti", :latitude => "44.01667", :longitude => "23.35").save
City.new(:country_id => "191", :name => "Baicoi", :aliases => "Baicoi,Baicoiu,BÄicoi,BÄicoiu,BÄicoi", :latitude => "45.03333", :longitude => "25.85").save
City.new(:country_id => "191", :name => "Baia Sprie", :aliases => "Baia Sprie,Civitas in medio monte,Felsobanya,FelsÅbÃ¡nya,Mittelstadt,Baia Sprie", :latitude => "47.66189", :longitude => "23.69215").save
City.new(:country_id => "191", :name => "Baia Mare", :aliases => "Baia Mare,Baja Mare,Baja-Mare,Frauenbach,Nagybanya,NagybÃ¡nya,Neustadt,Rivulus Dominarum,ÐÐ°Ñ-ÐÐ°ÑÐµ,Baia Mare", :latitude => "47.65729", :longitude => "23.56808").save
City.new(:country_id => "191", :name => "Bacau", :aliases => "Bacau,BacÄu,Bako,Bakuu,BÃ¡kÃ³,ÐÐ°ÐºÑÑ,××§××,BacÄu", :latitude => "46.56667", :longitude => "26.9").save
City.new(:country_id => "191", :name => "Arad", :aliases => "Altarad,Arad,Aradia,Aradinum Vetus,Micalaca,MicÄlaca,Mikelaka,Murasel,Muresel,MureÅel,MurÄÅel,O-Arad,Orodinum,Zsigmondhaza,ZsigmondhÃ¡za,Å-Arad,ÐÑÐ°Ð´,Arad", :latitude => "46.18333", :longitude => "21.31667").save
City.new(:country_id => "191", :name => "Alexandria", :aliases => "Alexandria,Alexandria", :latitude => "43.98333", :longitude => "25.33333").save
City.new(:country_id => "191", :name => "Alba Iulia", :aliases => "Alba Iulia,Alba Julija,Gyulafehervar,GyulafehÃ©rvÃ¡r,Karlsburg,Weissenburg,Weisskirchen,WeiÃkirchen,ÐÐ»Ð±Ð° Ð®Ð»Ð¸Ñ,Alba Iulia", :latitude => "46.06667", :longitude => "23.58333").save
City.new(:country_id => "191", :name => "Aiud", :aliases => "Aiud,Ajud,Nagyenyed,Strassburg,ÐÐ¹ÑÐ´,Aiud", :latitude => "46.3", :longitude => "23.71667").save
City.new(:country_id => "191", :name => "Adjud", :aliases => "Ad Judul,Adjud,Adjud", :latitude => "46.1", :longitude => "27.16667").save
City.new(:country_id => "191", :name => "Baia Mare", :aliases => ",Baia Mare", :latitude => "47.65331", :longitude => "23.57949").save
City.new(:country_id => "191", :name => "Targoviste", :aliases => ",Targoviste", :latitude => "44.92142", :longitude => "25.45575").save
City.new(:country_id => "191", :name => "Miercurea Ciuc", :aliases => ",Miercurea Ciuc", :latitude => "46.35795", :longitude => "25.80405").save
City.new(:country_id => "191", :name => "Pascani", :aliases => ",PaÅcani", :latitude => "47.2469", :longitude => "26.72291").save
