City.new(:country_id => "192", :name => "Zrenjanin", :aliases => "Becicherecu Mare,Becicherecul Mare,Beckerek,Becskerek,Betschkerek,BeÃ§kerek,Gross-Betschkerek,Nagybecskerek,Petrovgrad,Veliki Beckerek,Veliki BeÄkerek,Zrenanin,Zrenjanin,Zrenjaninas,bchkrk,ÐÑÐµÐ½ÑÐ½Ð¸Ð½,ÐÑÐµÑÐ°Ð½Ð¸Ð½,Ø¨ÚÚ©Ø±Ú©,Zrenjanin", :latitude => "45.38361", :longitude => "20.38194").save
City.new(:country_id => "192", :name => "Zemun", :aliases => "Semlin,Taurunum,Zeman,Zemlen,ZemlÃ©n,Zemun,Zimony,ÐÐµÐ¼ÑÐ½,Zemun", :latitude => "44.84306", :longitude => "20.40111").save
City.new(:country_id => "192", :name => "Zajecar", :aliases => "Zaechar,Zaiciar,Zaychar,ÐÐ°ÐµÑÐ°Ñ,ZajeÄar", :latitude => "43.90358", :longitude => "22.26405").save
City.new(:country_id => "192", :name => "Vrsac", :aliases => "Hennemannstadt,Varset,Versec,Versecz,Vershice,Vrsac,Vrsacas,Vrshac,VrÅ¡ac,VrÅ¡acas,VÃ¢rÅeÅ£,Werschetz,Werschitz,ÐÑÑÐ°Ñ,VrÅ¡ac", :latitude => "45.11667", :longitude => "21.30361").save
City.new(:country_id => "192", :name => "Vranje", :aliases => "Ivranya,Vrane,Vranja,Vranje,Vranya,ÐÑÐ°Ð½Ñ,ÐÑÐ°ÑÐµ,Vranje", :latitude => "42.55139", :longitude => "21.90028").save
City.new(:country_id => "192", :name => "Trstenik", :aliases => ",Trstenik", :latitude => "43.61694", :longitude => "21.0025").save
City.new(:country_id => "192", :name => "Stara Pazova", :aliases => "Alt-Pasua,Alt-Pazua,Opazova,Pazua,Stara Pazova,ÃpÃ¡zova,Stara Pazova", :latitude => "44.985", :longitude => "20.16083").save
City.new(:country_id => "192", :name => "Sremcica", :aliases => ",SremÄica", :latitude => "44.67653", :longitude => "20.39232").save
City.new(:country_id => "192", :name => "Smederevska Palanka", :aliases => "Palanka,Palanka Smederevska,Smederevska-Palanka,Ð¡Ð¼ÐµÐ´ÐµÑÐµÐ²ÑÐºÐ°-ÐÐ°Ð»Ð°Ð½ÐºÐ°,Smederevska Palanka", :latitude => "44.36548", :longitude => "20.95885").save
City.new(:country_id => "192", :name => "Smederevo", :aliases => "Semendria,Smedere,Smederevas,Smederevo,Szendro,SzendrÅ,Ð¡Ð¼ÐµÐ´ÐµÑÐµÐ²Ð¾,Smederevo", :latitude => "44.66278", :longitude => "20.93").save
City.new(:country_id => "192", :name => "Senta", :aliases => "Senta,Szenta,SzÃ©nta,Zenta,Ð¡ÐµÐ½ÑÐ°,Senta", :latitude => "45.9275", :longitude => "20.07722").save
City.new(:country_id => "192", :name => "Prokuplje", :aliases => "Prokuple,Prokuplje,Prokuplje", :latitude => "43.23417", :longitude => "21.58806").save
City.new(:country_id => "192", :name => "Pozarevac", :aliases => "Pozarevac,Pozarewac,Pozerevac,Pozharevac,Pozsarevac,PozsarevÃ¡c,PoÅ¼arewac,PoÅ¾arevac,PoÅ¾erevac,ÐÐ¾Ð¶Ð°ÑÐµÐ²Ð°Ñ,PoÅ¾arevac", :latitude => "44.61528", :longitude => "21.1825").save
City.new(:country_id => "192", :name => "Pirot", :aliases => "Pirot,ÐÐ¸ÑÐ¾Ñ,Pirot", :latitude => "43.15306", :longitude => "22.58611").save
City.new(:country_id => "192", :name => "Pancevo", :aliases => "Banstadt,Hertelendyfalva,Marienfeld,Pancevas,Pancevo,Panchevo,Panciova,Pancsal,Pancsaly,Pancsova,Pantschowa,PanÄevas,PanÄevo,Vojlovica,Wojlowitz,Wojlowitza,ÐÐ°Ð½ÑÐµÐ²Ð¾,PanÄevo", :latitude => "44.87083", :longitude => "20.64028").save
City.new(:country_id => "192", :name => "Obrenovac", :aliases => ",Obrenovac", :latitude => "44.65486", :longitude => "20.20017").save
City.new(:country_id => "192", :name => "Novi Pazar", :aliases => "Novi Pazar,Novi pazar,Pazari i Ri,Yeni Pazar,Yenipazar,novi pazar,ÐÐ¾Ð²Ð¸ ÐÐ°Ð·Ð°Ñ,ÐÐ¾Ð²Ð¸ Ð¿Ð°Ð·Ð°Ñ,Novi Pazar", :latitude => "43.13667", :longitude => "20.51222").save
City.new(:country_id => "192", :name => "bar", :aliases => "Neu-Pasua,Ujpazova,ÃjpÃ¡zova,bar", :latitude => "44.94366", :longitude => "20.21931").save
City.new(:country_id => "192", :name => "Nis", :aliases => "Nich,Nis,Nisch,Nish,Niso,Nissa,Nisz,Nix,NiÅo,NiÅ¡,ÐÐ¸Ñ,NiÅ¡", :latitude => "43.32472", :longitude => "21.90333").save
City.new(:country_id => "192", :name => "Negotin", :aliases => "Negotin,Negotin Krajina,Negotin Krajinski,ÐÐµÐ³Ð¾ÑÐ¸Ð½,Negotin", :latitude => "44.22639", :longitude => "22.53083").save
City.new(:country_id => "192", :name => "Leskovac", :aliases => "Leskovac,Leskovacas,ÐÐµÑÐºÐ¾Ð²Ð°Ñ,Leskovac", :latitude => "42.99806", :longitude => "21.94611").save
City.new(:country_id => "192", :name => "Lazarevac", :aliases => "Lazarevac,ÐÐ°Ð·Ð°ÑÐµÐ²Ð°Ñ,Lazarevac", :latitude => "44.38534", :longitude => "20.2557").save
City.new(:country_id => "192", :name => "Krusevac", :aliases => "Alacahisar,Krusevac,Krusevacas,Krushevac,KruÅ¡evac,KruÅ¡evacas,alajh hsar,ke lu she wa ci,ÐÑÑÑÐµÐ²Ð°Ñ,Ø§ÙØ§Ø¬Ù Ø­ØµØ§Ø±,åé²èç¦è¨,KruÅ¡evac", :latitude => "43.58", :longitude => "21.33389").save
City.new(:country_id => "192", :name => "Kraljevo", :aliases => "Kralevo,Kraljevas,Kraljevo,Rankovicevo,RankoviÄevo,ÐÑÐ°Ð»ÐµÐ²Ð¾,ÐÑÐ°ÑÐµÐ²Ð¾,Kraljevo", :latitude => "43.72583", :longitude => "20.68944").save
City.new(:country_id => "192", :name => "Kragujevac", :aliases => "Krabujevac,Kragiyevac,Kraguevac,Kragujevac,Kragujevaca,Kragujevacas,kuraguievu~atsu,qrgwyybz,ÐÑÐ°Ð³ÑÐµÐ²Ð°Ñ,ÐÑÐ°Ð³ÑÑÐµÐ²Ð°Ñ,×§×¨××××××¥,ã¯ã©ã°ã¤ã¨ã´ã¡ã,Kragujevac", :latitude => "44.01667", :longitude => "20.91667").save
City.new(:country_id => "192", :name => "Kikinda", :aliases => "Chichinda Mare,Gross-Kikinda,Kikinda,Kokend,KÃ¶kÃ©nd,Nagykikinda,Velika Kikinda,ÐÐ¸ÐºÐ¸Ð½Ð´Ð°,Kikinda", :latitude => "45.82972", :longitude => "20.46528").save
City.new(:country_id => "192", :name => "Jagodina", :aliases => "Jagodina,Svetozarevo,yaghwdynh,Ð¯Ð³Ð¾Ð´Ð¸Ð½Ð°,ÛØ§ØºÙØ¯ÛÙÙ,Jagodina", :latitude => "43.98139", :longitude => "21.26222").save
City.new(:country_id => "192", :name => "Ingija", :aliases => "India,Indjija,InÄija", :latitude => "45.04917", :longitude => "20.07917").save
City.new(:country_id => "192", :name => "Gornji Milanovac", :aliases => "Gornji Milanovac,Gornji Milanovac", :latitude => "44.03333", :longitude => "20.45").save
City.new(:country_id => "192", :name => "Glogovac", :aliases => "Glogovac,Glogovac", :latitude => "44.03972", :longitude => "21.31639").save
City.new(:country_id => "192", :name => "Cuprija", :aliases => "Cuprija,Äuprija,Äuprija", :latitude => "43.9275", :longitude => "21.37").save
City.new(:country_id => "192", :name => "Cacak", :aliases => "Cacak,Cacakas,Chachak,cha cha ke,ÄaÄak,ÄaÄakas,Ð§Ð°ÑÐ°Ðº,æ¥æ¥å,ÄaÄak", :latitude => "43.89139", :longitude => "20.34972").save
City.new(:country_id => "192", :name => "Bor", :aliases => "Bor,ÐÐ¾Ñ,Bor", :latitude => "44.07833", :longitude => "22.09528").save
City.new(:country_id => "192", :name => "Belgrade", :aliases => "Belehrad,Belgrad,Belgrada,Belgradas,Belgrade,Belgrado,Belgradu,Belgradum,Belgrau,BelgraÃ°,BelgrÃ¡d,BelgrÃ¡u,Beligradi,Belohrod,Beograd,Beogradi,Beogrado,BÃ¨lgrade,BÄlehrad,BÄÅohrÃ³d,Nandorfehervar,NÃ¡ndorfehÃ©rvÃ¡r,Singidunum,be-ogeuladeu,bei er ge lai de,belgradi,beogurado,blghrad,blgrd,pelkiret,ÎÎµÎ»Î¹Î³ÏÎ¬Î´Î¹,ÐÐµÐ»Ð³ÑÐ°Ð´,ÐÐµÐ¾Ð³ÑÐ°Ð´,ÐÑ£Ð»Ñ ÐÑÐ°Ð´Ñ,Ô²Õ¥Õ¬Õ£ÖÕ¡Õ¤,××××¨×,Ø¨ÙØºØ±Ø§Ø¯,Ø¨ÛÙÚ¯Ø±Ø§Ø¯,à®ªà¯à®²à¯à®à®¿à®±à¯à®à¯,ááááá ááá,á ááá«áµ,ããªã°ã©ã¼ã,è´å°æ ¼è±å¾·,ë² ì¤ê·¸ë¼ë,Belgrade", :latitude => "44.80401", :longitude => "20.46513").save
City.new(:country_id => "192", :name => "Becej", :aliases => "Alt-Betsche,Bechej,Becse,Becsej,Obecse,Stari Becej,Stari BeÄej,Ãbecse,ÐÐµÑÐµÐ¹,BeÄej", :latitude => "45.61632", :longitude => "20.03331").save
City.new(:country_id => "192", :name => "Arangelovac", :aliases => "Arangjelovac,AranÄelovac", :latitude => "44.30694", :longitude => "20.56").save
City.new(:country_id => "192", :name => "Vrbas", :aliases => "Alt-Werbass,Neu-Werbass,Overbasz,Titov Vrbas,Ujverbasz,Verbasz,VerbÃ¡sz,Vrbas,Weidenheim,ÃverbÃ¡sz,ÃjverbÃ¡sz,ÐÑÐ±Ð°Ñ,Vrbas", :latitude => "45.57139", :longitude => "19.64083").save
City.new(:country_id => "192", :name => "Valjevo", :aliases => "Valevo,Valjevas,Valjevo,ÐÐ°Ð»ÐµÐ²Ð¾,ÐÐ°ÑÐµÐ²Ð¾,Valjevo", :latitude => "44.27513", :longitude => "19.89821").save
City.new(:country_id => "192", :name => "Uzice", :aliases => "Oujiste,Titovo Uzice,Titovo UÅ¾ice,Uzhice,Uzice,UÅ¾ice,UÅ¾icÄ,Ð£Ð¶Ð¸ÑÐµ,Ñ¸Ð¶Ð¸ÑÐµ,UÅ¾ice", :latitude => "43.85861", :longitude => "19.84878").save
City.new(:country_id => "192", :name => "Subotica", :aliases => "Maria-Theresianopel,Maria-Theresiopel,Maria-Theresiopolis,Sawaditz,Subotica,Subotiza,Szabadka,Szent-Maria,Szent-MÃ¡ria,Theresiopel,Zubotica,Ð¡ÑÐ±Ð¾ÑÐ¸ÑÐ°,Subotica", :latitude => "46.1", :longitude => "19.66667").save
City.new(:country_id => "192", :name => "Sremska Mitrovica", :aliases => "Dimitrofce,DimitrofÃ§e,Mitrovic,Mitrovica,Mitrovicz,Mitrovicza,Mitrovitza,Mitrowitz,Opshtina Sremska Mitrovica,Opstina Sremska Mitrovica,OpÅ¡tina Sremska Mitrovica,Sirmion,Sirmium,Sremska Mitrovica,Srijemska Mitrovica,Strema Mitrovica,Syrmisch-Mitrowitz,Szavaszentdemeter,SzÃ¡vaszentdemeter,dmtrwfchh,ÐÐ¿ÑÑÐ¸Ð½Ð° Ð¡ÑÐµÐ¼ÑÐºÐ° ÐÐ¸ÑÑÐ¾Ð²Ð¸ÑÐ°,Ø¯ÙØªØ±ÙÙÚÙ,Sremska Mitrovica", :latitude => "44.97639", :longitude => "19.61222").save
City.new(:country_id => "192", :name => "Sombor", :aliases => "Coborszentmihaly,CoborszentmihÃ¡ly,Kiszombor,Mezozombor,MezÅzombor,Nagy-Zombor,Opshtina Sombor,Opstina Sombor,OpÅ¡tina Sombor,Schomburg,Sombor,Szentmihaly,SzentmihÃ¡ly,Zombor,ÐÐ¿ÑÑÐ¸Ð½Ð° Ð¡Ð¾Ð¼Ð±Ð¾Ñ,Sombor", :latitude => "45.77417", :longitude => "19.11222").save
City.new(:country_id => "192", :name => "Sabac", :aliases => "Chabats,Shabac,Ð¨Ð°Ð±Ð°Ñ,Å abac", :latitude => "44.74667", :longitude => "19.69").save
City.new(:country_id => "192", :name => "Ruma", :aliases => "Arpatarlo,Arpataro,Ruma,ÃrpatarlÃ³,ÃrpatarÃ³,Ð ÑÐ¼Ð°,Ruma", :latitude => "45.00806", :longitude => "19.82222").save
City.new(:country_id => "192", :name => "Novi Sad", :aliases => "Neoplanta,Neusatz,Novi Sad,Novi Sadas,Novisada,Novy Sad,NovÃ½ Sad,Nowy Sad,O-petervaradja,Petervarad,PÃ©tervÃ¡rad,Ujvidek,Varadinum Petri,Vasaros-Varad,VÃ¡sÃ¡ros-VÃ¡rad,nuo wei sa,Ã-pÃ©tervÃ¡radja,ÃjvidÃ©k,ÐÐ¾Ð²Ð¸ Ð¡Ð°Ð´,è¯ºå¨è¨,Novi Sad", :latitude => "45.25167", :longitude => "19.83694").save
City.new(:country_id => "192", :name => "Backa Topola", :aliases => "Andrasfoldje,AndrÃ¡sfÃ¶ldje,Bacstopolya,Batsch-Topola,BÃ¡cstopolya,Kisbelgrad,KisbelgrÃ¡d,Mali Beograd,Topolo,Topolya,BaÄka Topola", :latitude => "45.81516", :longitude => "19.6318").save
City.new(:country_id => "192", :name => "Backa Palanka", :aliases => "Alt-Palanka,Deutsch-Palanka,Nemet-Palanka,Nova Palanka,NÃ©met-PalÃ¡nka,Opalanka,Palanka,PalÃ¡nka,Plakenburg,Stara Palanka,Ujpalanka,ÃpalÃ¡nka,ÃjpalÃ¡nka,BaÄka Palanka", :latitude => "45.25083", :longitude => "19.39194").save
City.new(:country_id => "192", :name => "Apatin", :aliases => "Abthausen,Apathin,Apati,Apatin,ÐÐ¿Ð°ÑÐ¸Ð½,Apatin", :latitude => "45.67111", :longitude => "18.98472").save
City.new(:country_id => "192", :name => "Knjazevac", :aliases => ",Knjazevac", :latitude => "43.56484", :longitude => "22.25023").save
