City.new(:country_id => "195", :name => "Yanbu` al Bahr", :aliases => "Yambo,Yanbu al-Bahar,Yanbu`,Yanbu` al Bahr,Yanbuâ,Yanbuâ al Baá¸©r,Yenbo,Yenbo` al Bahar,Yenboâ al Bahar,Yanbuâ al Baá¸©r", :latitude => "24.08528", :longitude => "38.04861").save
City.new(:country_id => "195", :name => "Umm Lajj", :aliases => "Umm Lajj,Umm Lej,Umm Lujj,Umm Lajj", :latitude => "25.02417", :longitude => "37.26889").save
City.new(:country_id => "195", :name => "Turayf", :aliases => "At Turayf,AÅ£ Å¢urayf,Et Turaif,Eá¹­ á¹¬uraif,Mahattat al Turayf,Mahattat at Turayf,Maá¸©aÅ£Å£at al Å¢urayf,Maá¸©aÅ£Å£at aÅ£ Å¢urayf,Turaif,Turayf,Å¢urayf,Å¢urayf", :latitude => "31.6775", :longitude => "38.65306").save
City.new(:country_id => "195", :name => "Turabah", :aliases => "Ramadan,Taraba,Turaba,Turabah,Turbah,Turabah", :latitude => "21.21722", :longitude => "41.63556").save
City.new(:country_id => "195", :name => "Tarut", :aliases => "Darin Fort,Tarut,Tarut fort,TÄrÅ«t,TÄrÅ«t fort,TÄrÅ«t", :latitude => "26.5725", :longitude => "50.065").save
City.new(:country_id => "195", :name => "Tabuk", :aliases => "Gabouk,Tabouk,Tabuk,Tebuk,Ð¢Ð°Ð±ÑÐº,TabÅ«k", :latitude => "28.38333", :longitude => "36.58333").save
City.new(:country_id => "195", :name => "Tubarjal", :aliases => "Tabarjal,Tubarjal,Å¢abarjal,Å¢ubarjal,Ø·Ø¨Ø±Ø¬Ù,Å¢ubarjal", :latitude => "30.49778", :longitude => "38.21944").save
City.new(:country_id => "195", :name => "Sultanah", :aliases => "Sultanah,SulÅ£Änah,SulÅ£Änah", :latitude => "24.5", :longitude => "39.58333").save
City.new(:country_id => "195", :name => "Sayhat", :aliases => "As Saihat,As SaihÄt,As Sayhat,As SayhÄt,Saihat,Sayhat,SayhÄt,Sihat,SÄ«hÄt,SayhÄt", :latitude => "26.47944", :longitude => "50.045").save
City.new(:country_id => "195", :name => "Samitah", :aliases => "Samitah,Samta,ÅÄmitah,Ð¡Ð°Ð¼ÑÐ°,ÅÄmitah", :latitude => "16.59722", :longitude => "42.94389").save
City.new(:country_id => "195", :name => "Sakaka", :aliases => "Sakaka,Sakakah,SakÄkah,SakÄkÄ,Skaka,SkÃ¢ka,SakÄkÄ", :latitude => "29.97028", :longitude => "40.20861").save
City.new(:country_id => "195", :name => "Safwa", :aliases => "Safwa,Safwah,Åafwah,ÅafwÃ¡,ÅafwÃ¡", :latitude => "26.65083", :longitude => "49.95583").save
City.new(:country_id => "195", :name => "Sabya", :aliases => "Al-Sabya,As Sabya,AÅ ÅabyÄ,Sabie,Sabiya,Sabya,ÅabyÄ,ØµØ¨ÙØ§,ÅabyÄ", :latitude => "17.1495", :longitude => "42.62537").save
City.new(:country_id => "195", :name => "Rahimah", :aliases => "Rahaima,Rahimah,Raá¸©Ä«mah,Raá¸©Ä«mah", :latitude => "26.70583", :longitude => "50.05889").save
City.new(:country_id => "195", :name => "Rabigh", :aliases => "Rabegh,Rabigh,Rabigh Qasr,RÄbigh,RÄbigh", :latitude => "22.79861", :longitude => "39.03222").save
City.new(:country_id => "195", :name => "Qal`at Bishah", :aliases => "Bisha,Qal`at Bishah,Qalâat BÄ«shah,Qalâat BÄ«shah", :latitude => "20", :longitude => "42.6").save
City.new(:country_id => "195", :name => "Najran", :aliases => "Najran,NajrÄn,NajrÄn", :latitude => "17.50556", :longitude => "44.18417").save
City.new(:country_id => "195", :name => "Mecca", :aliases => "A Meca,A Meca - mkt,A Meca - ÙÙØ©,La Meca,La Mecca,La Mecque,Macoraba,Maekkae,Makka,Makkah,Makkah al Mukarramah,Makkah al Mukarraman,Makkah al-Mukarramah,Meca,Mecca,Meice,Meka,Mekao,Mekka,Mekkah,Mekke,Mekko,MÃ¤kkÃ¤,mai jia,makka,meka,mkh,mkt,ÎÎ­ÎºÎºÎ±,ÐÐµÐºÐ°,ÐÐµÐºÐºÐ°,×××,ÙÙØ©,ÙÚ©Ù,ÙÚ©Û,à¸¡à¸±à¸à¸à¸°à¸«à¸º,à½à¼à½,ááá¥á,ããã«,éº¥å ,ë©ì¹´,Mecca", :latitude => "21.42667", :longitude => "39.82611").save
City.new(:country_id => "195", :name => "Khamis Mushayt", :aliases => "Khamis Mushait,Khamis Mushayt,KhamÄ«s Mushayt,khmys mshyt,Ø®ÙÙØ³ ÙØ´ÙØ·,KhamÄ«s Mushayt", :latitude => "18.30639", :longitude => "42.72917").save
City.new(:country_id => "195", :name => "Jizan", :aliases => "Djayzan,DjayzÄn,Djazan,DjÄzÄn,Dzhizan,Gizan,GizÃ¡n,Jaizan,Jazan,Jezan,Jizan,JÄzÄn,JÄ«zÄn,Qizan,QÄ«zÄn,ÐÐ¶Ð¸Ð·Ð°Ð½,JÄ«zÄn", :latitude => "16.88917", :longitude => "42.55111").save
City.new(:country_id => "195", :name => "Jiddah", :aliases => "Ciddae,Cidde,CiddÃ¤,Djedda,Djeddah,Djidda,Dschidda,Dzedda,Dzhidda,Dzida,Dzudda,DÅ¼udda,DÅ¾edda,DÅ¾ida,Gedda,Gidda,Gido,Jaddah,Jedda,Jeddah,Jida,Jidda,Jiddah,JidÃ¡,Juddah,Yida,Yidda,g'dh,jdh,jdt,ji da,jidda,Äido,ÐÐ¶Ð¸Ð´Ð´Ð°,×'××,Ø¬Ø¯Ø©,Ø¬Ø¯Ù,ã¸ãã,åè¾¾,Jiddah", :latitude => "21.51694", :longitude => "39.21917").save
City.new(:country_id => "195", :name => "Hayil", :aliases => "Ha'il,Hael,Hajel,Hayil,á¸¤Ã¢jel,á¸¨Äâil,Hayil", :latitude => "27.51639", :longitude => "41.69694").save
City.new(:country_id => "195", :name => "Zbe", :aliases => "Daba,Dhaba,Diba,Duba,Zbe,Ziba',ZÌ§ibÄâ,ÐÑÐ±Ð°,á¸abÄ,á¸ubÄ,Zbe", :latitude => "27.353", :longitude => "35.68798").save
City.new(:country_id => "195", :name => "Buraydah", :aliases => "Buraeydae,Buraida,Buraidah,Burajda,Buraydah,BurÃ¤ydÃ¤,brydt,Ø¨Ø±ÙØ¯Ø©,Buraydah", :latitude => "26.33167", :longitude => "43.97167").save
City.new(:country_id => "195", :name => "Abqaiq", :aliases => "Abaqaiq,Abkayk,Abqaik,Abqaiq,Abqayq,Bukayk,Buqayq,Madinat Abqaiq,Abqaiq", :latitude => "25.93556", :longitude => "49.66833").save
City.new(:country_id => "195", :name => "Badr Hunayn", :aliases => "Badr,Badr Hunain,Badr Hunayn,Badr á¸¨unayn,Badr á¸¨unayn", :latitude => "23.78", :longitude => "38.79056").save
City.new(:country_id => "195", :name => "Az Zulfi", :aliases => "Az Zilfi,Az ZilfÄ«,Az Zulfi,Zilfi,Az Zulfi", :latitude => "26.29667", :longitude => "44.80361").save
City.new(:country_id => "195", :name => "Dhahran", :aliases => "Az Zahran,AzÌ§ ZÌ§ahrÄn,Dahahron,Dakhran,Dhahram,Dhahran,Zahran,ÐÐ°ÑÑÐ°Ð½,Dhahran", :latitude => "26.30417", :longitude => "50.1325").save
City.new(:country_id => "195", :name => "At Taraf", :aliases => "Al-Taraf,At Taraf,AÅ£ Å¢araf,AÅ£ Å¢araf", :latitude => "25.35889", :longitude => "49.72194").save
City.new(:country_id => "195", :name => "Tayif", :aliases => "Al-Ta'if,Al-á¹¬Äâif,At Ta'if,AÅ£ Å¢Äâif,Ta'if,Taef,Taif,Tayif,TaÃ«f,Taâif,TÄif,altayf,Ð¢Ð°Ð¸Ñ,Ø§ÙØ·Ø§Ø¦Ù,Tayif", :latitude => "21.27028", :longitude => "40.41583").save
City.new(:country_id => "195", :name => "As Sulayyil", :aliases => "As Sulayyil,As Sullayyil,Sulaiyil,As Sulayyil", :latitude => "20.45972", :longitude => "45.57444").save
City.new(:country_id => "195", :name => "Riyadh", :aliases => "Al-Riyad,Ar Riyad,Ar Riyadh,Ar RiyÄdh,Ar RiyÄá¸,Ar-Riyad,Ar-RiyÄá¸,Ehr-Rijad,Er Rijad,Riad,Riade,Riant,Rijad,Rijada,Rijadas,RijÃ¡d,RijÄda,Riyad,Riyadh,alryad,li ya de,liadeu,riyad,riyada,riyadha,riyado,ryad,Î¡Î¹Î¬Î½Ï,ÐÑ Ð Ð¸ÑÐ°Ð´,Ð Ð¸ÑÐ´,Ð­Ñ-Ð Ð¸ÑÐ´,×¨×××,Ø§ÙØ±ÙØ§Ø¶,Ø±ÛØ§Ø¶,à¤°à¤¿à¤¯à¤¾à¤§,à¦°à¦¿à¦¯à¦¼à¦¾à¦¦,à¸£à¸´à¸¢à¸²à¸,áªá«áµ,ãªã¤ã,å©éå¾·,ë¦¬ìë,Riyadh", :latitude => "24.68773", :longitude => "46.72185").save
City.new(:country_id => "195", :name => "Ar Rass", :aliases => "Al Russ,Ar Rass,El Russ,Rass,alrs,Ø§ÙØ±Ø³,Ar Rass", :latitude => "25.86972", :longitude => "43.50222").save
City.new(:country_id => "195", :name => "`Ar`ar", :aliases => "Ara`ar,Arar,Araâar,`Ar`ar,Ø¹Ø±Ø¹Ø±,âArâar,âArâar", :latitude => "30.95178", :longitude => "41.05969").save
City.new(:country_id => "195", :name => "An Nimas", :aliases => "Al-Nimas,Al-NimÄs,An Nimas,An NimÄÅ,Numas,NumÄs,An NimÄÅ", :latitude => "19.11667", :longitude => "42.13333").save
City.new(:country_id => "195", :name => "Al Qurayyat", :aliases => "Al Qurayyat,Al QurayyÄt,Al `Aqaylah,Al `Uqaylah,Al `Uqaylah Kaf,Al âAqaylah,Al âUqaylah,Al âUqaylah KÄf,Al-`Akejla,Al-âAkejla,An Nabk,An Nabk Abu Nakhlah,Nabek,Ø§ÙÙØ±ÙØ§Øª,Al QurayyÄt", :latitude => "31.33333", :longitude => "37.34194").save
City.new(:country_id => "195", :name => "Al Wajh", :aliases => "Al Wajh,Alwejh,Wajj,Wejh,Al Wajh", :latitude => "26.23333", :longitude => "36.46667").save
City.new(:country_id => "195", :name => "Al Qaysumah", :aliases => "Al Qaysumah,Al QayÅÅ«mah,Gaisum,Gaisun,Qaisumah,Qaysumah,QayÅumah,Quasomeh,Al QayÅÅ«mah", :latitude => "28.30972", :longitude => "46.1275").save
City.new(:country_id => "195", :name => "Al Qatif", :aliases => "Al Qatif,Al QaÅ£Ä«f,Ehl'-Katif,El Katif,Qatif,Ð­Ð»Ñ-ÐÐ°ÑÐ¸Ñ,Al QaÅ£Ä«f", :latitude => "26.52", :longitude => "50.02472").save
City.new(:country_id => "195", :name => "Al Munayzilah", :aliases => "Al Munaizilah,Al Munayzilah,Manaizlah,Manzilah,Minazla,Al Munayzilah", :latitude => "25.38333", :longitude => "49.66667").save
City.new(:country_id => "195", :name => "Al Mubarraz", :aliases => "Al Mubarraz,Al Mubarraz", :latitude => "25.41", :longitude => "49.58083").save
City.new(:country_id => "195", :name => "Medina", :aliases => "Al Madina,Al Madinah,Al Madinah al Munawwarah,Al MadÄ«nah,Al MadÄ«nah al Munawwarah,Al Medina,El Medina,Lathrippa,Madinah,Madinah al-Munawwarah,Maedinae,Mediina,Medina,Medine,Medino,Medyna,MedÃ­na,MedÃ®ne,MÃ¤dinÃ¤,MÃ©dine,Yathrib,almdynt,almdynt almnwrt,madina,mai de na,mdynh,medina,ÐÐµÐ´Ð¸Ð½Ð°,××-×××× ×,Ø§ÙÙØ¯ÙÙØ©,Ø§ÙÙØ¯ÙÙØ© Ø§ÙÙÙÙØ±Ø©,ÙØ¯ÛÙÙ,ÙØ¯ÛÙÛ ÙÙÙØ±Û,à¤®à¤¦à¥à¤¨à¤¾,áááááá,ããã£ã¼ã,éº¦å°é£,Medina", :latitude => "24.46861", :longitude => "39.61417").save
City.new(:country_id => "195", :name => "Al Khubar", :aliases => "Al Khobar,Al Khubar,Khobar,Al Khubar", :latitude => "26.27944", :longitude => "50.20833").save
City.new(:country_id => "195", :name => "Al Khafji", :aliases => "Al Khafji,Al KhafjÄ«,Ra's al Khafji,Raâs al KhafjÄ«,Al KhafjÄ«", :latitude => "28.41306", :longitude => "48.48417").save
City.new(:country_id => "195", :name => "Al Jumum", :aliases => "Al Jumum,Al Jumun,Al JumÅ«m,Al JumÅ«n,Jumum,Al JumÅ«m", :latitude => "21.61694", :longitude => "39.69806").save
City.new(:country_id => "195", :name => "Al Jubayl", :aliases => "Ainain,Ainan,Al Jubayl,Al'-Dzhubajl',Jubail,Jubail al Bahri,Jubayl,Jubayl `Aynayw,Jubayl al Bahri,Jubayl al Baá¸©ri,Jubayl âAynayw,`Aynayn,aljbyl,ÐÐ»Ñ-ÐÐ¶ÑÐ±Ð°Ð¹Ð»Ñ,Ø§ÙØ¬Ø¨ÙÙ,âAynayn,Al Jubayl", :latitude => "27.00472", :longitude => "49.66139").save
City.new(:country_id => "195", :name => "Al Hufuf", :aliases => "Al Hufuf,Al HufÅ«f,Hofuf,HofÅ«f,Hufuf,HufÅ«f,Al HufÅ«f", :latitude => "25.37833", :longitude => "49.58667").save
City.new(:country_id => "195", :name => "Al Bukayriyah", :aliases => "Al Bukayriyah,Al BukayrÄ«yah,Bukayriyah,BukayrÄ«yah,Keriya,Al BukayrÄ«yah", :latitude => "26.15056", :longitude => "43.66").save
City.new(:country_id => "195", :name => "Al Battaliyah", :aliases => "Al Battaliyah,Al BaÅ£Å£ÄlÄ«yah,Al BaÅ£Å£ÄlÄ«yah", :latitude => "25.43333", :longitude => "49.63333").save
City.new(:country_id => "195", :name => "Al Bahah", :aliases => "Al Bahah,Al BÄá¸©ah,Al BÄá¸©ah", :latitude => "20.01667", :longitude => "41.46667").save
City.new(:country_id => "195", :name => "`Afif", :aliases => "Afif,`Afif,âAfÄ«f,âAfÄ«f", :latitude => "23.91667", :longitude => "42.93333").save
City.new(:country_id => "195", :name => "Ad Dilam", :aliases => "Ad Dilam,Dilam,Ad Dilam", :latitude => "23.99694", :longitude => "47.165").save
City.new(:country_id => "195", :name => "Ad Dawadimi", :aliases => "Ad Dawadami,Ad Dawadimi,Ad DawÄdamÄ«,Ad DawÄdimÄ«,Ad Duwadami,Ad DuwÄdamÄ«,Al-Dawadimi,Al-DawÄdimi,Duwadami,Duwadimi,DuwÄdimi,Ad DawÄdimÄ«", :latitude => "24.49417", :longitude => "44.38333").save
City.new(:country_id => "195", :name => "Ad Dammam", :aliases => "Ad Dammam,Ad DammÄm,Daemmam,Dammam,Damman,DammÄm,DÃ¤mmam,aldmam,danmamu,ÐÐ°Ð¼Ð¼Ð°Ð¼,Ø§ÙØ¯ÙØ§Ù,ãã³ãã¼ã ,Ad DammÄm", :latitude => "26.42583", :longitude => "50.11417").save
City.new(:country_id => "195", :name => "Abu `Arish", :aliases => "Abi `Arish,Abu `Arish,Abu al `Arish,Abu al âArish,AbÄ« âArÄ«sh,AbÅ« âArÄ«sh,Ù²Ø¨Ù Ø¹Ø±ÙØ´,AbÅ« âArÄ«sh", :latitude => "16.95865", :longitude => "42.83549").save
City.new(:country_id => "195", :name => "Abha", :aliases => "AEbha,Abha,AbhÄ,Abkha,Ebha,abha,Ãbha,ÐÐ±ÑÐ°,Ø£Ø¨ÙØ§,AbhÄ", :latitude => "18.21639", :longitude => "42.50528").save
