City.new(:country_id => "202", :name => "Trbovlje", :aliases => "Obcina Trbovlje,ObÄina Trbovlje,Trbovlje,torubovurye,ãã«ãã´ãªã§,Trbovlje", :latitude => "46.155", :longitude => "15.05333").save
City.new(:country_id => "202", :name => "Velenje", :aliases => "Belenie,Mestna obcina Velenje,Mestna obÄina Velenje,Titovo Velenje,Velen'e,Velenje,Wollan,WÃ¶llan,bellenye,vu~erenie,ÎÎ­Î»ÎµÎ½Î¹Îµ,ÐÐµÐ»ÐµÐ½ÑÐµ,ã´ã§ã¬ãã¨,ë²¨ë ë,Velenje", :latitude => "46.35917", :longitude => "15.11028").save
City.new(:country_id => "202", :name => "Ptuj", :aliases => "Mestna obcina Ptuj,Mestna obÄina Ptuj,Pettau,Ptuj,puto~ui,ÐÑÑÐ¹,ããã¥ã¤,Ptuj", :latitude => "46.42005", :longitude => "15.87018").save
City.new(:country_id => "202", :name => "Novo Mesto", :aliases => "Nova Mesta,Nova mehsta,Novo Mesto,Novo mesto,Rudolfswert,Rudolfswerth,xin mei si tuo shi,ÐÐ¾Ð²Ð° Ð¼ÑÑÑÐ°,ÐÐ¾Ð²Ð¾ ÐÐµÑÑÐ¾,ÐÐ¾Ð²Ð¾ Ð¼ÐµÑÑÐ¾,ãã´ã©ã»ã¡ã¹ã,æ°æ¢æ¯æå¸,Novo Mesto", :latitude => "45.80397", :longitude => "15.16886").save
City.new(:country_id => "202", :name => "Maribor", :aliases => "Marburg an der Drau,Marburgo,Maribor,Maribora,Mariboras,Mariboro,Mestna obcina Maribor,Mestna obÄina Maribor,ma li bo er,mariboru,ÐÐ°ÑÐ¸Ð±Ð¾Ñ,ããªãã«,é©¬éåå°,Maribor", :latitude => "46.55472", :longitude => "15.64667").save
City.new(:country_id => "202", :name => "Ljubljana", :aliases => "Aemona,Laibach,Lioumpliana,Liubliana,Ljubljana,Lubiana,Lubjana,Lublan,Lublana,LublaÅ,Lubliano,Lubljana,Lyublyana,li'ubliyana,liubliana,lu bu er ya na,lyubeullyana,lywblyana,ryuburyana,Ä»ubÄ¼ana,Ä½ubÄ¾ana,ÎÎ¹Î¿ÏÎ¼ÏÎ»Î¹Î¬Î½Î±,ÐÑÐ±ÑÐ°Ð½Ð°,ÐÑÐ±Ð»ÑÐ½Ð°,Ô¼ÕµÕ¸ÖÕ¢Õ¬ÕµÕ¡Õ¶Õ¡,××××××× ×,ÙÙÙØ¨ÙÙØ§ÙØ§,ÙÛÙØ¨ÙÛØ§ÙØ§,à¦²à¦¿à¦à¦¬à§à¦²à¦¿à¦¯à¦¼à¦¾à¦¨à¦¾,ááá£áááááá,áá©á¥áá«á,ãªã¥ããªã£ã,å¢å¸å°éé£,ë¥ë¸ë´ë,Ljubljana", :latitude => "46.05108", :longitude => "14.50513").save
City.new(:country_id => "202", :name => "Kranj", :aliases => "Cragni,Krainburg,Kran',Kranj,kurani,ÐÑÐ°Ð½Ñ,ã¯ã©ã¼ã,Kranj", :latitude => "46.23887", :longitude => "14.35561").save
City.new(:country_id => "202", :name => "Koper", :aliases => "Capodistria,Grad Kopar,Kopar,Koper,Koperis,koperu,ÐÐ¾Ð¿ÐµÑ,ã³ãã«,Koper", :latitude => "45.54694", :longitude => "13.72944").save
City.new(:country_id => "202", :name => "Celje", :aliases => "Cele,Celeia,Celje,Cilli,Tsel'e,tsu~erye,Ð¦ÐµÐ»Ðµ,Ð¦ÐµÑÐµ,ãã§ãªã§,Celje", :latitude => "46.23092", :longitude => "15.26044").save
