City.new(:country_id => "204", :name => "Vranov nad Topl'ou", :aliases => "Varanno,VarannÃ³,Vranov,Vranov nad Topl'ou,Vranov nad Toplou,Vranov nad TopÄ¾ou,vranov,ÐÑÐ°Ð½Ð¾Ð²,Vranov nad TopÄ¾ou", :latitude => "48.9", :longitude => "21.68333").save
City.new(:country_id => "204", :name => "Trebisov", :aliases => "Toketerebes,Trebishov,Trebisov,TrebiÅ¡ov,TÅketerebes,Ð¢ÑÐµÐ±Ð¸ÑÐ¾Ð²,TrebiÅ¡ov", :latitude => "48.63333", :longitude => "21.71667").save
City.new(:country_id => "204", :name => "Stara lubovna", :aliases => "Olublo,Stara Ljubovnja,Stara Lubovna,Stara Lubowla,StarÃ¡ Ä½ubovÅa,ÃlublÃ³,Ð¡ÑÐ°ÑÐ° ÐÑÐ±Ð¾Ð²Ð½Ñ,StarÃ¡ Ä¾ubovÅa", :latitude => "49.3", :longitude => "20.7").save
City.new(:country_id => "204", :name => "Spisska Nova Ves", :aliases => "Iglo,IglÃ³,Neudorf,Spishska Nova Ves,Spiska Nowa Wies,Spiska Nowa WieÅ,Spisska,Spisska Nova Ves,SpiÅ¡skÃ¡,SpiÅ¡skÃ¡ NovÃ¡ Ves,Ð¡Ð¿Ð¸ÑÑÐºÐ° ÐÐ¾Ð²Ð° ÐÐµÑ,SpiÅ¡skÃ¡ NovÃ¡ Ves", :latitude => "48.95", :longitude => "20.56667").save
City.new(:country_id => "204", :name => "Snina", :aliases => "Snina,Szinna,Ð¡Ð½Ð¸Ð½Ð°,Snina", :latitude => "48.98333", :longitude => "22.15").save
City.new(:country_id => "204", :name => "Roznava", :aliases => "Rosenau,Rozhnjava,Roznava,Rozsnyo,RozsnyÃ³,RoÅ¾Åava,Ð Ð¾Ð¶Ð½ÑÐ²Ð°,RoÅ¾Åava", :latitude => "48.66667", :longitude => "20.53333").save
City.new(:country_id => "204", :name => "Rimavska Sobota", :aliases => "Rima-Szombat,Rimaszombat,Rimavska Sobota,RimavskÃ¡ Sobota,Sobota Rimavska,Sobota RimavskÃ¡,Ð Ð¸Ð¼Ð°Ð²ÑÐºÐ° Ð¡Ð¾Ð±Ð¾ÑÐ°,RimavskÃ¡ Sobota", :latitude => "48.38333", :longitude => "20.03333").save
City.new(:country_id => "204", :name => "Presov", :aliases => "Eperjes,Prasiv,Preshov,Presov,Presova,Preszow,PreszÃ³w,PreÅ¡ov,PreÅ¡ova,Prjashev,prswb,ÐÑÐµÑÐ¾Ð²,ÐÑÑÑÐµÐ²,ÐÑÑÑÑÐ²,×¤×¨×©××,PreÅ¡ov", :latitude => "49", :longitude => "21.25").save
City.new(:country_id => "204", :name => "Poprad", :aliases => "Deutschendorf,Poprad,ÐÐ¾Ð¿ÑÐ°Ð´,Poprad", :latitude => "49.05", :longitude => "20.3").save
City.new(:country_id => "204", :name => "Michalovce", :aliases => "Grossmichel,GroÃmichel,Michalovce,Mikhalovce,Nagymihaly,NagymihÃ¡ly,miharofutsu~e,ÐÐ¸ÑÐ°Ð»Ð¾Ð²ÑÐµ,ããã­ããã§,Michalovce", :latitude => "48.75", :longitude => "21.93333").save
City.new(:country_id => "204", :name => "Kosice", :aliases => "Kaschau,Kassa,Koesice,Koshice,Kosice,Koszyce,KoÅ¡ice,KÃ¶sice,ke xi ce,koshitsu~e,kosiche,qwsyzh,ÐÐ¾ÑÐ¸ÑÐµ,×§××©××¦×,ã³ã·ãã§,ç§å¸ç­,ì½ìì²´,KoÅ¡ice", :latitude => "48.71667", :longitude => "21.25").save
City.new(:country_id => "204", :name => "Kezmarok", :aliases => "Kaesmark,Kesmark,Kezhmarok,Kezmarok,Kezmarokas,KeÅ¾marok,KeÅ¾marokas,Kiezmark,KieÅ¼mark,KÃ¤smark,KÃ©smÃ¡rk,ÐÐµÐ¶Ð¼Ð°ÑÐ¾Ðº,KeÅ¾marok", :latitude => "49.13333", :longitude => "20.43333").save
City.new(:country_id => "204", :name => "Humenne", :aliases => "Gumenne,Homonna,Humenne,HumennÃ©,ÐÑÐ¼ÐµÐ½Ð½Ðµ,HumennÃ©", :latitude => "48.93333", :longitude => "21.91667").save
City.new(:country_id => "204", :name => "Bardejov", :aliases => "Bardejov,Bardiow,BardiÃ³w,Bartfa,Bartfeld,BÃ¡rtfa,bardejov,brdywb,ÐÐ°ÑÐ´ÐµÐ¹Ð¾Ð²,××¨××××,Bardejov", :latitude => "49.28333", :longitude => "21.28333").save
City.new(:country_id => "204", :name => "Zvolen", :aliases => "Altsohl,Zolyom,Zvolen,Zwolen,ZwoleÅ,ZÃ³lyom,zvolen,ÐÐ²Ð¾Ð»ÐµÐ½,Zvolen", :latitude => "48.58333", :longitude => "19.13333").save
City.new(:country_id => "204", :name => "Zlate Moravce", :aliases => "Zlate Moravce,ZlatÃ© Moravce,ZlatÃ© Moravce", :latitude => "48.38333", :longitude => "18.4").save
City.new(:country_id => "204", :name => "Zilina", :aliases => "Sillein,Solna,Zhilina,Zilina,Zsolna,Zylina,Å»ylina,Å½ilina,ÐÐ¸Ð»Ð¸Ð½Ð°,Å½ilina", :latitude => "49.22315", :longitude => "18.73941").save
City.new(:country_id => "204", :name => "Ziar nad Hronom", :aliases => "Svaty Kriz nad Hronom,SvÃ¤tÃ½ KrÃ­Å¾ nad Hronom,Ziar nad Hronom,Å½iar nad Hronom,Å½iar nad Hronom", :latitude => "48.58333", :longitude => "18.86667").save
City.new(:country_id => "204", :name => "Trnava", :aliases => "Nagyszombat,Trnava,Trnawa,Tyrnau,Ð¢ÑÐ½Ð°Ð²Ð°,Trnava", :latitude => "48.36667", :longitude => "17.6").save
City.new(:country_id => "204", :name => "Trencin", :aliases => "Trenchin,Trencin,Trencsen,TrencsÃ©n,Trenczyn,Trentschin,Trentsen,TrenÄin,TrenÄÃ­n,Ð¢ÑÐµÐ½ÑÐ¸Ð½,TrenÄÃ­n", :latitude => "48.89452", :longitude => "18.04436").save
City.new(:country_id => "204", :name => "Skalica", :aliases => "Skalica,Skalica", :latitude => "48.85", :longitude => "17.23333").save
City.new(:country_id => "204", :name => "Senica", :aliases => "Senica,Ð¡ÐµÐ½Ð¸ÑÐ°,Senica", :latitude => "48.68333", :longitude => "17.36667").save
City.new(:country_id => "204", :name => "Sellye", :aliases => "Sal'a,Sala,Sala nad Vahom,Sellye,Shalja,Vagsellye,VÃ¡gsellye,Å ala nad VÃ¡hom,Å aÄ¾a,Ð¨Ð°Ð»Ñ,Sellye", :latitude => "48.15", :longitude => "17.88333").save
City.new(:country_id => "204", :name => "Ruzomberok", :aliases => "Rosenberg,Rozahegy,Rozsahegy,RoÅºahegy,Ruzhomberok,Ruzomberk,Ruzomberok,RuÅ¼omberk,RuÅ¾omberok,RÃ³zsahegy,Ð ÑÐ¶Ð¾Ð¼Ð±ÐµÑÐ¾Ðº,RuÅ¾omberok", :latitude => "49.08333", :longitude => "19.31667").save
City.new(:country_id => "204", :name => "Puchov", :aliases => "Pucho,Puchov,Puho,PuhÃ³,Pukhov,PÃºchov,ÐÑÑÐ¾Ð²,PÃºchov", :latitude => "49.13333", :longitude => "18.33333").save
City.new(:country_id => "204", :name => "Prievidza", :aliases => "Pr'evidza,Prievidza,Privigye,ÐÑÑÐµÐ²Ð¸Ð´Ð·Ð°,Prievidza", :latitude => "48.76667", :longitude => "18.63333").save
City.new(:country_id => "204", :name => "Povazska Bystrica", :aliases => "Bystrica,Povazhska Bistrica,Povazska Bystrica,Povazske Bystraica,PovaÅ¾skÃ¡ Bystrica,Powazska Bystrzyca,PowaÅ¼ska Bystrzyca,Vagbeszterce,VÃ¡gbeszterce,Waagbistritz,ÐÐ¾Ð²Ð°Ð¶ÑÐºÐ° ÐÐ¸ÑÑÑÐ¸ÑÐ°,PovaÅ¾skÃ¡ Bystrica", :latitude => "49.11667", :longitude => "18.45").save
City.new(:country_id => "204", :name => "Piestany", :aliases => "Piest'anoch,Piestany,Pieszczany,PieÅ¡Å¥anoch,PieÅ¡Å¥any,Poestyen,PÃ¶styÃ©n,p'eshtjany,ÐÑÐµÑÑÑÐ½Ñ,PieÅ¡Å¥any", :latitude => "48.6", :longitude => "17.83333").save
City.new(:country_id => "204", :name => "Pezinok", :aliases => "Bazin,Pezinok,Poesing,PÃ¶sing,ÐÐµÐ·Ð¸Ð½Ð¾Ðº,Pezinok", :latitude => "48.28333", :longitude => "17.26667").save
City.new(:country_id => "204", :name => "Partizanske", :aliases => "Bat'ovany,BaÅ¥ovany,Partizanske,PartizÃ¡nske,Partyzanske,PartyzÃ¡nske,Simonovany,Simony,Å imonovany,Î Î±ÏÏÎ¹Î¶Î¬Î½ÏÎºÎµ,ÐÐ°ÑÑÐ¸Ð·Ð°Ð½ÑÐºÐµ,PartizÃ¡nske", :latitude => "48.63333", :longitude => "18.38333").save
City.new(:country_id => "204", :name => "Nove Zamky", :aliases => "Ersekujvar,Neuhaeusel,Neuhaus,NeuhÃ¤usel,Nove Zamky,NovÃ© ZÃ¡mky,Uyvar,awywar,nove zamki,ÃrsekÃºjvÃ¡r,ÐÐ¾Ð²Ðµ ÐÐ°Ð¼ÐºÐ¸,Ø§ÙÛÙØ§Ø±,NovÃ© ZÃ¡mky", :latitude => "47.98544", :longitude => "18.16195").save
City.new(:country_id => "204", :name => "Nove Mesto nad Vahom", :aliases => "Nove Mesto nad Vagom,Nove Mesto nad Vahom,NovÃ© Mesto nad VÃ¡hom,Otura,Vagujhely,VÃ¡gÃºjhely,Ãtura,ÐÐ¾Ð²Ðµ ÐÐµÑÑÐ¾ Ð½Ð°Ð´ ÐÐ°Ð³Ð¾Ð¼,NovÃ© Mesto nad VÃ¡hom", :latitude => "48.75763", :longitude => "17.8309").save
City.new(:country_id => "204", :name => "Nitra", :aliases => "Neutra,Nitra,Nyitra,nitora,nytrh,ÐÐ¸ÑÑÐ°,× ×××¨×,ããã©,Nitra", :latitude => "48.30763", :longitude => "18.08453").save
City.new(:country_id => "204", :name => "Martin", :aliases => "Martin,Turciansky Svaty Martin,TurÄiansky SvÃ¤tÃ½ Martin,ÐÐ°ÑÑÐ¸Ð½,Martin", :latitude => "49.06667", :longitude => "18.93333").save
City.new(:country_id => "204", :name => "Malacky", :aliases => "Malacka,Malacke,Malacki,Malacky,Malaczka,Malczka,ÐÐ°Ð»Ð°ÑÐºÐ¸,Malacky", :latitude => "48.43333", :longitude => "17.01667").save
City.new(:country_id => "204", :name => "Lucenec", :aliases => "Losonc,Losoncz,Lucenec,Luchenec,LuÄenec,ÐÑÑÐµÐ½ÐµÑ,LuÄenec", :latitude => "48.33333", :longitude => "19.66667").save
City.new(:country_id => "204", :name => "Liptovsky Mikulas", :aliases => "Liptau-Sankt-Nikolaus,Liptoszentmiklos,Liptovski Mikulash,Liptovsky Mikulas,Liptovsky Svaty Mikulas,LiptovskÃ½ MikulÃ¡Å¡,LiptovskÃ½ SvÃ¤tÃ½ MikulÃ¡Å¡,Liptowski Mikulasz,LiptÃ³szentmiklÃ³s,ÐÐ¸Ð¿ÑÐ¾Ð²ÑÐºÐ¸ ÐÐ¸ÐºÑÐ»Ð°Ñ,LiptovskÃ½ MikulÃ¡Å¡", :latitude => "49.08061", :longitude => "19.62218").save
City.new(:country_id => "204", :name => "Levice", :aliases => "Leua,Leva,Levice,LÃ©va,lwh,ÐÐµÐ²Ð¸ÑÐµ,ÙÙÙ,Levice", :latitude => "48.21667", :longitude => "18.6").save
City.new(:country_id => "204", :name => "Kysucke Nove Mesto", :aliases => "Kisucke Nove Mesto,Kiszucaujhely,KiszucaÃºjhely,Kysucke Nove Mesto,KysuckÃ© NovÃ© Mesto,ÐÐ¸ÑÑÑÐºÐµ ÐÐ¾Ð²Ðµ ÐÐµÑÑÐ¾,KysuckÃ© NovÃ© Mesto", :latitude => "49.3", :longitude => "18.78333").save
City.new(:country_id => "204", :name => "Komarno", :aliases => "Eszak-Komarom,Komarno,Komarnom,Komarom,Komorn,KomÃ¡rno,KomÃ¡rom,Ãszak-KomÃ¡rom,ÐÐ¾Ð¼Ð°ÑÐ½Ð¾,KomÃ¡rno", :latitude => "47.76356", :longitude => "18.12263").save
City.new(:country_id => "204", :name => "Hlohovec", :aliases => "Galgoc,GalgÃ³c,Hlohovec,glogovec,ÐÐ»Ð¾Ð³Ð¾Ð²ÐµÑ,Hlohovec", :latitude => "48.43333", :longitude => "17.8").save
City.new(:country_id => "204", :name => "Handlova", :aliases => "Handlova,HandlovÃ¡,HandlovÃ¡", :latitude => "48.73333", :longitude => "18.76667").save
City.new(:country_id => "204", :name => "Galanta", :aliases => "Galanta,GalÃ¡nta,ÐÐ°Ð»Ð°Ð½ÑÐ°,Galanta", :latitude => "48.19001", :longitude => "17.72747").save
City.new(:country_id => "204", :name => "Dunajska Streda", :aliases => "Duna-Szerdahely,Dunajska Streda,DunajskÃ¡ Streda,Dunaszerdahely,ÐÑÐ½Ð°Ð¹ÑÐºÐ° Ð¡ÑÑÐµÐ´Ð°,ãã¥ãã¤ã¹ã«ã¼ã»ã¹ãã¬ã,DunajskÃ¡ Streda", :latitude => "47.99268", :longitude => "17.61211").save
City.new(:country_id => "204", :name => "Dubnica nad Vahom", :aliases => "Dubnica nad Vahom,Dubnica nad VÃ¡hom,Dubnica-nad-Vagom,Mariatoelgyes,MÃ¡riatÃ¶lgyes,ÐÑÐ±Ð½Ð¸ÑÐ°-Ð½Ð°Ð´-ÐÐ°Ð³Ð¾Ð¼,Dubnica nad VÃ¡hom", :latitude => "48.96667", :longitude => "18.18333").save
City.new(:country_id => "204", :name => "Dolny Kubin", :aliases => "Alsokubin,AlsÃ³kubin,Dolni Kubin,Dolny Kubin,DolnÃ­ KubÃ­n,DolnÃ½ KubÃ­n,ÐÐ¾Ð»Ð½Ñ ÐÑÐ±Ð¸Ð½,DolnÃ½ KubÃ­n", :latitude => "49.2", :longitude => "19.3").save
City.new(:country_id => "204", :name => "Detva", :aliases => "Detva,Gyetva,ÐÐµÑÐ²Ð°,Detva", :latitude => "48.56082", :longitude => "19.41954").save
City.new(:country_id => "204", :name => "Cadca", :aliases => "Cadca,Chadca,Csaca,Csacza,Czaca,Äadca,Ð§Ð°Ð´ÑÐ°,Äadca", :latitude => "49.43333", :longitude => "18.78333").save
City.new(:country_id => "204", :name => "Brezno", :aliases => "Brezno,Brezno nad Hronom,Breznobanya,Breznon,BreznÃ³bÃ¡nya,Bries,ÐÑÐµÐ·Ð½Ð¾,Brezno", :latitude => "48.81667", :longitude => "19.65").save
City.new(:country_id => "204", :name => "Bratislava", :aliases => "An Bhrataslaiv,An BhrataslÃ¡iv,Bratislava,Bratislavae,Bratislavo,Bratislawa,Bratisllava,Bratyslawa,BratysÅawa,BratÃ®slava,Gorad Bracislava,Mpratislaba,Posonium,Pozsony,Presburg,Presporok,Prespurk,Pressburg,Preszburg,PreÃburg,PreÅ¡porok,PreÅ¡purk,beulatiseullaba,bra ti sla wa,bratislabha,bratislava,bratislavha,bratyslafa,bratyslava,bratyslaw,bratyslawa,brtyslÊ¾bÊ¾,bu la di si la fa,burachisuravu~a,ÎÏÏÎ±ÏÎ¹ÏÎ»Î¬Î²Î±,ÐÑÐ°ÑÐ¸ÑÐ»Ð°Ð²Ã¦,ÐÑÐ°ÑÐ¸ÑÐ»Ð°Ð²Ð°,ÐÑÐ°ÑÑÑÐ»Ð°Ð²Ð°,ÐÐ¾ÑÐ°Ð´ ÐÑÐ°ÑÑÑÐ»Ð°Ð²Ð°,Ô²ÖÕ¡Õ¿Õ«Õ½Õ¬Õ¡Õ¾Õ¡,××¨××××¡×××××,××¨×××¡××××,Ø¨Ø±Ø§ØªÙØ³ÙØ§ÛØ§,Ø¨Ø±Ø§ØªÙØ³ÙØ§ÙØ§,Ø¨Ø±Ø§ØªÛØ³ÙØ§Ù,Ø¨Ø±Ø§ØªÛØ³ÙØ§ÙØ§,Ø¨Ø±Ø§Ù¹ÛØ³ÙØ§ÙØ§,ÜÜªÜÜÜ£Ü ÜÜÜ,à¤¬à¥à¤°à¤¾à¤¤à¤¿à¤¸à¥à¤²à¤¾à¤µà¥à¤¹à¤¾,à¦¬à§à¦°à¦¾à¦¤à¦¿à¦¸à§à¦²à¦¾à¦­à¦¾,à²¬à³à²°à²¾à²à²¿à²¸à³à²²à²¾à²µà²¾,à´¬àµà´°à´¾à´àµà´à´¿à´¸àµâà´²à´¾à´µ,à¸à¸£à¸²à¸à¸´à¸ªà¸¥à¸²à¸§à¸²,à½à¼à½¢à¼à½à½²à½¦à½²à¼à½£à¼à½à¼,áá áá¢áá¡áááá,á¥á«á²áµáá«,ãã©ãã¹ã©ã´ã¡,å¸æè¿ªæ¯æå,ë¸ë¼í°ì¬ë¼ë°,Bratislava", :latitude => "48.14816", :longitude => "17.10674").save
City.new(:country_id => "204", :name => "Banska Bystrica", :aliases => "Banska Bistrica,Banska Bystrica,Banska Bystrzyca,BanskÃ¡ Bystrica,BaÅska Bystrzyca,Besztercebanya,BesztercebÃ¡nya,Beszterczebanya,BeszterczebÃ¡nya,Neusohl,ÐÐ°Ð½ÑÐºÐ° ÐÐ¸ÑÑÑÐ¸ÑÐ°,ÐÐ°ÑÑÐºÐ° ÐÐ¸ÑÑÑÐ¸ÑÐ°,ãã³ã¹ã«ã¼ã»ãã¹ããªãã¡,BanskÃ¡ Bystrica", :latitude => "48.73333", :longitude => "19.15").save
City.new(:country_id => "204", :name => "Banovce nad Bebravou", :aliases => "Banovce,Banovce nad Bebravou,BÃ¡novce nad Bebravou,BÃ¡novce nad Bebravou", :latitude => "48.71667", :longitude => "18.26667").save
