City.new(:country_id => "208", :name => "Wanlaweyn", :aliases => "Bahle Dogli,Uanle Uen,Wangleweyn,Wanla Uen,Wanla Weyne,Wanlaweyn,Wanle Weyne,Wanlaweyn", :latitude => "2.61912", :longitude => "44.89258").save
City.new(:country_id => "208", :name => "Qoryooley", :aliases => "Coriole,Coriolei,Koriolay,Qoreyole,Qoryolay,Qoryooley,Qoryooley", :latitude => "1.78333", :longitude => "44.53333").save
City.new(:country_id => "208", :name => "Qandala", :aliases => "Candala,Kandala,Qandala,Qandala", :latitude => "11.47245", :longitude => "49.87159").save
City.new(:country_id => "208", :name => "Mogadishu", :aliases => "Magadiscio,Maqdishu,Mogadiisho,Mogadisa,Mogadisas,Mogadischu,Mogadiscio,Mogadish,Mogadisho,Mogadishu,Mogadiso,Mogadisu,Mogadisxo,Mogadiszu,MogadiÅo,MogadiÅu,MogadiÅ¡a,MogadiÅ¡as,MogadiÅ¡o,MogadiÅ¡u,MogadÃ­scio,Mogaidisiu,MogaidisiÃº,Moukntiso,Muqdisho,Muqdishow,Muqdishu,Xamar,mo jia di xiu,mogadisho,mogadishu,mogadisyu,mqdyshw,mqdyshyw,mwgadyshw,mwgdysw,ÎÎ¿ÏÎºÎ½ÏÎ¯ÏÎ¿,ÐÐ¾Ð³Ð°Ð´Ð¸ÑÑ,××××××©×,ÙÙØ¯ÙØ´Ù,ÙÙØ¯ÙØ´ÙÙ,ÙÙÚ¯Ø§Ø¯ÛØ´Ù,ááááááá¨á,ááá²á¾,ã¢ã¬ãã£ã·ã¥,æ©å è¿ªä¼,ëª¨ê°ëì,Mogadishu", :latitude => "2.03711", :longitude => "45.34375").save
City.new(:country_id => "208", :name => "Luuq", :aliases => "Lugh,Lugh Ferrandi,Lugh Ganana,Lugh Ganane,Lughferandi,Luk,Luuq,ÐÑÐº,Luuq", :latitude => "3.79651", :longitude => "42.54421").save
City.new(:country_id => "208", :name => "Chisimayu", :aliases => "Chisimaio,Chisimayu,Kisimayo,Kisimayu,Kismaanyo,Kismaayo,Kismanyo,Kismayo,Kismayu,KismÄnyÃ³,kisumayo,ã­ã¹ãã¨,Chisimayu", :latitude => "-0.35817", :longitude => "42.54536").save
City.new(:country_id => "208", :name => "Jilib", :aliases => "Dzhilib,Gelib,Jeelib,Jilib,ÐÐ¶Ð¸Ð»Ð¸Ð±,Jilib", :latitude => "0.49583", :longitude => "42.77278").save
City.new(:country_id => "208", :name => "Giohar", :aliases => "Giohar,Jawhar,Johar,Joher,Joowhar,Jowhar,JÅwhar,Villa Duca Abruzzi,Villaggio Duca Abruzzi,Villaggio Duca degli Abruzzi,Giohar", :latitude => "2.78087", :longitude => "45.50048").save
City.new(:country_id => "208", :name => "Jamaame", :aliases => "Giamama,Giamame,Giamana,Giamane,Jamaame,Jamame,JamÄme,Margherita,Jamaame", :latitude => "0.07222", :longitude => "42.75056").save
City.new(:country_id => "208", :name => "Hargeysa", :aliases => "Hargeisa,Hargesa,Hargeysa,Khargejse,Ð¥Ð°ÑÐ³ÐµÐ¹ÑÐµ,Hargeysa", :latitude => "9.56", :longitude => "44.065").save
City.new(:country_id => "208", :name => "Galcaio", :aliases => "Gaalkacyo,Galcaio,Galka`yo',Galkaâyoâ,Gallacai,Rocca Littorio,Galcaio", :latitude => "6.76972", :longitude => "47.43083").save
City.new(:country_id => "208", :name => "Eyl", :aliases => "Ayl,Ceel,Eeyl,Eil,Eyl,Eyl", :latitude => "7.98333", :longitude => "49.81667").save
City.new(:country_id => "208", :name => "Erigavo", :aliases => "Ceerigaabo,Cerigaabo,Erigabo,Erigavo,Erigavo", :latitude => "10.61806", :longitude => "47.37").save
City.new(:country_id => "208", :name => "Ceeldheere", :aliases => "Ceeldheer,Ceeldheere,El Dere,Ceeldheere", :latitude => "3.84878", :longitude => "47.18064").save
City.new(:country_id => "208", :name => "Buurhakaba", :aliases => "Bur Acaba,Bur Hacaba,Burhakaba,Buur Hakkaba,Buurhakaba,Buurhakaba", :latitude => "2.79649", :longitude => "44.08101").save
City.new(:country_id => "208", :name => "Buulobarde", :aliases => "Bulo Berde,Bulo Burti,Buulo,Buulo Berde,Buulo Burte,Buulobarde,BÅ«lo BÃ©rde,Buulobarde", :latitude => "3.85366", :longitude => "45.56557").save
City.new(:country_id => "208", :name => "Burao", :aliases => "Bur `o,Bur âÃ³,Burao,Burco,ÐÑÑÐ°Ð¾,Burao", :latitude => "9.52417", :longitude => "45.53694").save
City.new(:country_id => "208", :name => "Bender Cassim", :aliases => "Bandar Kassim,Bender Cassim,Bender Qaasin,Bender Qasin,Boosaaso,Boosaso,Bosaso,Bosasso,BÃ©nder QÄsin,Bender Cassim", :latitude => "11.28421", :longitude => "49.18158").save
City.new(:country_id => "208", :name => "Berbera", :aliases => "Berbera,Berberah,Berbere,bai pei la,ÐÐµÑÐ±ÐµÑÐ°,æå¹æ,Berbera", :latitude => "10.43556", :longitude => "45.01639").save
City.new(:country_id => "208", :name => "Beledweyne", :aliases => "Balad Weyn,Belai-Wen,Beled Weyn,Beleduehjne,Beledueyne,Beledweyne,Belet Uen,Belet Wayne,Belet Wen,Belet Weyne,BÄlad Weyn,ÐÐµÐ»ÐµÐ´ÑÑÐ¹Ð½Ðµ,Beledweyne", :latitude => "4.73583", :longitude => "45.20361").save
City.new(:country_id => "208", :name => "Baidoa", :aliases => "Baidabho,Baidabo,Baidoa,Bajdoa,Baydhabo,Iscia Baidoa,Isha Baydabo,Isha Baydhaba,Isha Baydhabo,bai duo ya,baidoa,ri ben yu,ÐÐ°Ð¹Ð´Ð¾Ð°,ãã¤ãã¢,æå¤äº,æ¥æ¬èª,Baidoa", :latitude => "3.11667", :longitude => "43.65").save
City.new(:country_id => "208", :name => "Baardheere", :aliases => ",Baardheere", :latitude => "2.34464", :longitude => "42.27644").save
City.new(:country_id => "208", :name => "Afgooye", :aliases => "Afgoi,Afgoje,Afgooye,Afgoye,AfgÅye,Asgoi,ÐÑÐ³Ð¾Ð¹Ðµ,Afgooye", :latitude => "2.13998", :longitude => "45.12002").save
City.new(:country_id => "208", :name => "Laascaanood", :aliases => "Laascaanood,Las Anod,Laascaanood", :latitude => "8.47556", :longitude => "47.35778").save
