City.new(:country_id => "212", :name => "Yabrud", :aliases => "Gebru,Jabrud,Jebru,Jebrud,Yabroud,YabroÃ»d,Yabrud,YabrÅ«d,Ð¯Ð±ÑÑÐ´,YabrÅ«d", :latitude => "33.96667", :longitude => "36.66667").save
City.new(:country_id => "212", :name => "Tayyibat al Imam", :aliases => "Taibet el Imam,Taybat al Imam,Taybat al Imam `Ali,Tayyibat al Imam,TaÃ¯bet el ImÃ¢m,Tibbat al Imam,Tibbat al ImÄm,Tibet Iman,Å¢aybat al ImÄm,Å¢aybat al ImÄm âAlÄ«,Å¢ayyibat al ImÄm,Å¢ayyibat al ImÄm", :latitude => "35.26539", :longitude => "36.71148").save
City.new(:country_id => "212", :name => "Tartouss", :aliases => "Antaradus,Tartous,Tartouss,TartoÃ»s,Tartus,mhafzt trtws,trtws,Å¢arÅ£Å«s,Ð¢Ð°ÑÑÑÑ,××¨×××¡,Ø·Ø±Ø·ÙØ³,ÙØ­Ø§ÙØ¸Ø© Ø·Ø±Ø·ÙØ³,Tartouss", :latitude => "34.88902", :longitude => "35.88659").save
City.new(:country_id => "212", :name => "Tall Rif`at", :aliases => "Tall Rif`at,Tall Rifâat,Tell Arfad,Tell Refaat,Tell Rifaate,Tell Rifat,Tell RifaÃ¢te,Tall Rifâat", :latitude => "36.46667", :longitude => "37.1").save
City.new(:country_id => "212", :name => "Tall Kalakh", :aliases => "Talkalakh,Tall Kalakh,Telkalakh,Tell Kalakh,Tall Kalakh", :latitude => "34.66667", :longitude => "36.25").save
City.new(:country_id => "212", :name => "Talbisah", :aliases => "Talbisah,Talbiseh,TalbÄ«sah,Tall Bisih,Tall Bissah,Tall BÄ«sih,Tel Bisi,Telbise,Tell Bise,Tell Bisse,Tell BÃ®sse,Tell BÄ«se,TalbÄ«sah", :latitude => "34.84063", :longitude => "36.73093").save
City.new(:country_id => "212", :name => "Tafas", :aliases => "Tafas,Tafass,Å¢afas,Å¢afas", :latitude => "32.73564", :longitude => "36.06694").save
City.new(:country_id => "212", :name => "Tadmur", :aliases => "Pal'mira,Palmira,Palmuera,Palmyra,Palmyre,PalmÃ¼ra,PalmÃ½ra,Tadmor,Tadmur,Tedmor,ba er mi la,mmlkt tdmr,parumira yi ji,tdmwr,ÐÐ°Ð»Ð¼Ð¸ÑÐ°,ÐÐ°Ð»ÑÐ¼Ð¸ÑÐ°,×ª××××¨,ÙÙÙÙØ© ØªØ¯ÙØ±,ãã«ãã©éºè·¡,å·´å°ç±³æ,Tadmur", :latitude => "34.55", :longitude => "38.28333").save
City.new(:country_id => "212", :name => "Tadif", :aliases => "Tadef,Tader,Tadif,Teft,TÃ¢def,TÃ¢der,TÄdif,TÄdif", :latitude => "36.33333", :longitude => "37.53333").save
City.new(:country_id => "212", :name => "Souran", :aliases => "Soran,Souran,Sourane,SoÃ»rÃ¢ne,Suran,ÅÅ«rÄn,Ð¡ÑÑÐ°Ð½,Souran", :latitude => "35.29138", :longitude => "36.74865").save
City.new(:country_id => "212", :name => "Subaykhan", :aliases => "Sabikhan,Soubeikhane,SoubeÃ¯khÃ¢ne,Subaykhan,SubaykhÄn,SubaykhÄn", :latitude => "34.85444", :longitude => "40.60833").save
City.new(:country_id => "212", :name => "Shaykh Miskin", :aliases => "Ash Shaykh Maskin,Ash Shaykh MaskÄ«n,Ash Shaykh Miskin,Ash Shaykh MiskÄ«n,Cheikh Meskine,CheÃ¯kh MeskÃ®ne,Chikh Meskine,Shaykh Maskin,Shaykh MaskÄ«n,Shaykh Miskin,Shaykh MiskÄ«n,Sheikh Miskin,Sheikh MiskÄ«n,Shaykh MiskÄ«n", :latitude => "32.82944", :longitude => "36.15933").save
City.new(:country_id => "212", :name => "Saraqib", :aliases => "Sarakeb,Saraqeb,Saraqib,Saraquib,SarÃ¢qeb,SarÄqib,Seraikin,Serakab,Seraqab,Seraqib,SerÄqab,SarÄqib", :latitude => "35.86361", :longitude => "36.80056").save
City.new(:country_id => "212", :name => "Salqin", :aliases => "Salkine,SalkÃ®ne,Salqin,Salqine,SalqÃ®ne,SalqÄ«n,Selkin,Silkin,SalqÄ«n", :latitude => "36.13809", :longitude => "36.45322").save
City.new(:country_id => "212", :name => "Salamiyah", :aliases => "Salamias,Salamiyah,Salamiyeh,SalamÄ«yah,Selemie,Selemiya,Selemiye,SelemiÃ©,SelemÄ«ya,SÃ©lÃ©mÃ®yÃ©,SalamÄ«yah", :latitude => "35.01127", :longitude => "37.05324").save
City.new(:country_id => "212", :name => "Satita", :aliases => "Borj Safita,Borj SÃ¢fÃ®ta,Khokhu,Safita,Satita,ÅÄfÄ«tÄ,Satita", :latitude => "34.81667", :longitude => "36.11667").save
City.new(:country_id => "212", :name => "Qatana", :aliases => "Katana,Qatana,Qatanah,QaÅ£anah,QaÅ£anÄ,QaÅ£anÄ", :latitude => "33.43544", :longitude => "36.08148").save
City.new(:country_id => "212", :name => "Qasim", :aliases => "Jacem,Jasem,Jasim,Jassem,JÃ¢ssem,JÄsim,Kasim,Qasim,QÄsim,ÐÐ°ÑÐ¸Ð¼,QÄsim", :latitude => "32.99233", :longitude => "36.06018").save
City.new(:country_id => "212", :name => "Qarah", :aliases => "Kara,Karra,Qara,Qarah,QÄrah,QÄrÄ,QÄrah", :latitude => "34.15", :longitude => "36.73333").save
City.new(:country_id => "212", :name => "Nubl", :aliases => "Noubbel,Noubbol,Nubl,Nubl", :latitude => "36.3771", :longitude => "36.99238").save
City.new(:country_id => "212", :name => "Masyaf", :aliases => "Imranie,Massiaf,Massiyaf,MassiÃ¢f,Massyaf,Masyab,Masyad,Masyaf,MasyÄb,MaÅyÄf,MaÅÅÄ«yaf,Misiaf,Omranie,OmraniÃ©,`Omraniye,`Umraniya,âOmrÄnÄ«ye,âUmraniya,MaÅyÄf", :latitude => "35.05", :longitude => "36.35").save
City.new(:country_id => "212", :name => "Manbij", :aliases => "Hierapolis,Manbej,Manbi,Manbij,Membidj,Membij,Memdidge,Menbidj,Menbij,Mennbidj,Minbej,Manbij", :latitude => "36.52667", :longitude => "37.95639").save
City.new(:country_id => "212", :name => "Ma`arrat Misrin", :aliases => "Ma`arrat Misrin,Ma`arrat Misriyn,Maarat Missrin,Maarrat al Masrin,Maarret Misrine,Maarret el Mesrine,Maâarrat Misriyn,Maâarrat MiÅrÄ«n,Maâarrat MiÅrÄ«n", :latitude => "36.01337", :longitude => "36.67254").save
City.new(:country_id => "212", :name => "Khan Shaykhun", :aliases => "Khan Cheykoun,Khan Shaykhun,Khan Sheikhun,Khan-Sheikhoun,Khane Chaikhoun,Khane Cheikhoun,KhÃ¢ne ChaÃ¯khoun,KhÃ¢ne CheÃ¯khoÃ»n,KhÄn ShaykhÅ«n,KhÄn SheikhÅ«n,KhÄn ShaykhÅ«n", :latitude => "35.44063", :longitude => "36.64995").save
City.new(:country_id => "212", :name => "Kafr Zayta", :aliases => "Kafer Zaita,Kafer ZaÃ¯ta,Kafer Zita,Kafer ez Zaita,Kafer ez ZaÃ¯ta,Kafr Zayta,Kafr Zaytah,Kafr ZaytÄ,Kafr Zita,Kafr ZÄ«ta,Kafr ZaytÄ", :latitude => "35.37382", :longitude => "36.60365").save
City.new(:country_id => "212", :name => "Kafr Takharim", :aliases => "Kafar Takharim,Kafer Harut,Kafer Taharim,Kafer TahÃ¢rim,Kafer Takharim,Kafer TakhÃ¢rim,Kafer Tkherim,Kafr Taharim,Kafr Takharim,Kafr TakhÄrÄ«m,Kafr Taá¸©ÄrÄ«m,Kafr TakhÄrÄ«m", :latitude => "36.11684", :longitude => "36.51528").save
City.new(:country_id => "212", :name => "Kafr Nabl", :aliases => "Kafer Nebal,Kafr Nabl,Kafr Nubl,Kafr Nubul,Kufer Nabel,Kafr Nabl", :latitude => "35.6", :longitude => "36.56667").save
City.new(:country_id => "212", :name => "Kafr Lahah", :aliases => "Kafer Laha,Kafer LÃ¢ha,Kafr Laha,Kafr Lahah,Kafr LÄhÄ,Kafr LÄá¸©ah,Kefrlehe,Kufer Laha,Kafr LÄá¸©ah", :latitude => "34.89464", :longitude => "36.49404").save
City.new(:country_id => "212", :name => "Jisr ash Shughur", :aliases => "Djisr el Choghour,Jisr Al-Shughour,Jisr ash Shaghur,Jisr ash Shughur,Jisr ash ShughÅ«r,Jisr ash ShÄghÅ«r,Jisr ech Chorhour,Jisr esh Shaur,Jisr esh Shughur,Jisr esh ShughÅ«r,Jisr-esh-Shughour,Jisr ash ShughÅ«r", :latitude => "35.81556", :longitude => "36.3175").save
City.new(:country_id => "212", :name => "Jayrud", :aliases => "Djeroud,Djerud,DjÃ©roud,Jairoud,Jairud,Jayrud,JayrÅ«d,JaÃ¯roud,Jerud,JerÅ«d,JayrÅ«d", :latitude => "33.81667", :longitude => "36.73333").save
City.new(:country_id => "212", :name => "Jarabulus", :aliases => "Carablus,Djarablous,Djerablous,DjÃ©rÃ¢bloÃ»s,Jarablos,Jarabulus,JarÄbulus,Jerablus,Jirablus,JirÄblus,JarÄbulus", :latitude => "36.8175", :longitude => "38.01111").save
City.new(:country_id => "212", :name => "Jablah", :aliases => "Djeble,DjÃ©blÃ©,Jablah,Jableh,Jebele,Jebeleh,Jebelli,Jeble,Jablah", :latitude => "35.35", :longitude => "35.91667").save
City.new(:country_id => "212", :name => "`Irbin", :aliases => "Aarbil,AarbÃ®l,Arbine,Irbin,Irbine,`Irbin,âIrbÄ«n,âIrbÄ«n", :latitude => "33.5376", :longitude => "36.36856").save
City.new(:country_id => "212", :name => "Inkhil", :aliases => "Enn Nakhl,Ennkhel,Inkhel,Inkhil,Inkhil", :latitude => "33", :longitude => "36.11667").save
City.new(:country_id => "212", :name => "Idlib", :aliases => "Idleb,Idlib,adlb,mhafzt adlb,ÐÐ´Ð»Ð¸Ð±,Ø¥Ø¯ÙØ¨,ÙØ­Ø§ÙØ¸Ø© Ø¥Ø¯ÙØ¨,Idlib", :latitude => "35.93062", :longitude => "36.63393").save
City.new(:country_id => "212", :name => "Hums", :aliases => "Emesa,Hims,Homs,Houmousse,Hums,Khoms,hms,hwms,mdynt hms,Ð¥Ð¾Ð¼Ñ,××××¡,Ø­ÙØµ,ÙØ¯ÙÙØ© Ø­ÙØµ,á¸¨imÅ,Hums", :latitude => "34.72682", :longitude => "36.72339").save
City.new(:country_id => "212", :name => "Hirista", :aliases => "Arasta Bassal,Harasta,Harasta al Basal,Harasta el Bassal,Harastah al Basal,Harastah al BaÅal,Hirista,á¸¨arastÄ al BaÅal,á¸¨iristÄ,á¸¨iristÄ", :latitude => "33.55899", :longitude => "36.36432").save
City.new(:country_id => "212", :name => "Hamah", :aliases => "Epiphaneia,Epiphania,Hama,Hamah,Hamao,Hamath,Khama,hmat,Ð¥Ð°Ð¼Ð°,Ø­ÙØ§Ø©,á¸¨amÄh,á¸¨amÄh", :latitude => "35.13179", :longitude => "36.75783").save
City.new(:country_id => "212", :name => "Halfaya", :aliases => "Halfaya,á¸¨alfÄyÄ,á¸¨alfÄyÄ", :latitude => "35.25995", :longitude => "36.60572").save
City.new(:country_id => "212", :name => "Aleppo", :aliases => "Alep,Alepas,Alepo,Alepo - hlb,Alepo - Ø­ÙØ¨,Aleppe,Aleppo,Berea,Beroea,Halab,Haleb,Halep,Heleb,Khaleb,Khalepion,Madinat Halab,MadÄ«nat á¸¨alab,areppo,hlb,Ð¥Ð°Ð»ÐµÐ±,××××,Ø­ÙØ¨,á¸¨alab,ã¢ã¬ãã,Aleppo", :latitude => "36.20278", :longitude => "37.15861").save
City.new(:country_id => "212", :name => "Douma", :aliases => "Douma,Duma,DÅ«mÄ,ÐÑÐ¼Ð°,Douma", :latitude => "33.57175", :longitude => "36.4027").save
City.new(:country_id => "212", :name => "Damascus", :aliases => "Al-Sham,Al-ShÄm,Cham,Damas,Damasc,Damasco,Damascu,Damascus,Damasek,Damask,Damask',Damaskas,Damasko,Damaskos,Damaskus,Damaszek,DamaÅ¡ek,Dammeseq,Dimaejk,Dimashk,Dimashk al-Sham,Dimashk al-ShÄm,Dimashq,Dimeshki esh Sham,Dimishq,DimÃ¤jk,Esh Sham,Esh ShÄm,Sam,da ma shi ge,damaseukuseu,damasukasu,dmshq,dmsq,drmswq,Åam,ÎÎ±Î¼Î±ÏÎºÏÏ,ÐÐ°Ð¼Ð°ÑÐº,ÐÐ°Ð¼Ð°ÑÐºÑ,ÐÐ¸Ð¼Ð¸ÑÒ,Ô´Õ¡Õ´Õ¡Õ½Õ¯Õ¸Õ½,×××©×§,Ø¯ÙØ´Ù,ÜÜªÜ¡Ü£ÜÜ©,á°ááµá,ããã¹ã«ã¹,å¤§é¦¬å£«é©,ë¤ë§ì¤ì¿ ì¤,Damascus", :latitude => "33.5102", :longitude => "36.29128").save
City.new(:country_id => "212", :name => "Dayr Hafir", :aliases => "Dayr Hafir,Dayr á¸¨Äfir,Deir Hafer,Deir Hafero,Deir Hafir,Deir HÃ¢fero,Deir HÃ¢fir,DeÃ¯r HÃ¢fer,Dayr á¸¨Äfir", :latitude => "36.15361", :longitude => "37.70667").save
City.new(:country_id => "212", :name => "Dayr az Zawr", :aliases => "Azaura,Dayr al-Zor,Dayr az Zawr,Dayr az Zur,Dayr az ZÅ«r,Deir Zzor,Deir ez Zoar,Deir ez Zor,DeÃ¯r ez Zor,dyr alzwr,Ø¯ÙØ± Ø§ÙØ²ÙØ±,Dayr az Zawr", :latitude => "35.33333", :longitude => "40.15").save
City.new(:country_id => "212", :name => "Darbasiyah", :aliases => "Darbasiyah,DarbÄsÄ«yah,Derbassiye,Derbisiye,DerbisÄ«ye,Dirbassiyeh,DarbÄsÄ«yah", :latitude => "37.07279", :longitude => "40.65199").save
City.new(:country_id => "212", :name => "Darayya", :aliases => "Daraiya,Daraje,Daraya,Daraye,Darayya,Darayyah,Dareiya,Deraya,DÃ¢raiya,DÄrayyah,DÄrayyÄ,DÄreiya,ÐÐ°ÑÐ°Ð¹Ðµ,DÄrayyÄ", :latitude => "33.45897", :longitude => "36.23742").save
City.new(:country_id => "212", :name => "Binnish", :aliases => "Binnesh,Binnich,Binnish,Binnish", :latitude => "35.95554", :longitude => "36.71393").save
City.new(:country_id => "212", :name => "Baniyas", :aliases => "Banias,Banijas,Baniyas,Bulunyas,BulunyÄs,BÃ¢niÃ¢s,BÄniyÄs,ÐÐ°Ð½Ð¸ÑÑ,BÄniyÄs", :latitude => "35.18333", :longitude => "35.95").save
City.new(:country_id => "212", :name => "Az Zabadani", :aliases => "Az Zabadani,Az ZabadÄnÄ«,Zabadani,Zabdani,ZabdÄnÄ«,Zebdani,ZebdÄni,Zebedani,Zibdani,ZibdÄnÄ«,Az ZabadÄnÄ«", :latitude => "33.72565", :longitude => "36.09704").save
City.new(:country_id => "212", :name => "A`zaz", :aliases => "A`zaz,Aazaz,AazÃ¢z,Azaz,AâzÄz,I`zaz,IâzÄz,ÐÐ·Ð°Ð·,AâzÄz", :latitude => "36.58889", :longitude => "37.04417").save
City.new(:country_id => "212", :name => "At Tall", :aliases => "Al-Tal,At Tall,Ett Tell,Tal,Tall,Tell,At Tall", :latitude => "33.6099", :longitude => "36.30964").save
City.new(:country_id => "212", :name => "Ath Thawrah", :aliases => "Al Tabaqah,Al-Tabbaqah,Al-Thawra,At Tabqah,Ath Thawrah,Madinat ath Thawrah,MadÄ«nat ath Thawrah,Medinat Al Thawra,Revolution City,Tabaqah,Tabqa,Å¢abaqah,Ath Thawrah", :latitude => "35.84688", :longitude => "38.54427").save
City.new(:country_id => "212", :name => "As Suwayda'", :aliases => "Al-Sweida,As Suwayda',As Suwaydah,As SuwaydÄâ,Dionysia,Es Suweida,Es Suweidiya,Es SuweidÄ«ya,Soueida,SoueÃ¯da,Suwaydah,Sweida,As SuwaydÄâ", :latitude => "32.70896", :longitude => "36.56951").save
City.new(:country_id => "212", :name => "As Sanamayn", :aliases => "Aere,AerÃ©,As Sanamayn,AÅ Åanamayn,Es Sanamein,Es Sannamain,Sanamayn,Sanamein,Sanameine,SanameÃ¯ne,Sanmayn,Åanamayn,AÅ Åanamayn", :latitude => "33.07312", :longitude => "36.18499").save
City.new(:country_id => "212", :name => "As Safirah", :aliases => "Al-Safira,As Safirah,As SafÄ«rah,Safir,Safira,Safirah,SafÄ«rah,Sfira,Sfire,SfirÃ©,SfÄ«ra,alsfyrt,ÅafÄ«r,Ø§ÙØ³ÙÙØ±Ø©,As SafÄ«rah", :latitude => "36.07696", :longitude => "37.37251").save
City.new(:country_id => "212", :name => "Ar Rastan", :aliases => "Al-Rastan,Ar Rastan,Arethousa,Arethus,El Rastane,Er Rastan,Rastan,Rastane,RastÃ¢ne,Ar Rastan", :latitude => "34.92653", :longitude => "36.73238").save
City.new(:country_id => "212", :name => "Ar Raqqah", :aliases => "Al-Rakka,Ar Raqqah,Ar-Rakka,Ar-Raqqah,Nicephorium,Rakka,Raqqa,Raqqah,alrqt,ÐÑ-Ð Ð°ÐºÐºÐ°,Ø§ÙØ±ÙØ©,Ar Raqqah", :latitude => "35.95", :longitude => "39.01667").save
City.new(:country_id => "212", :name => "An Nabk", :aliases => "Al-Nabek,An Nabk,En Nebk,Kalamom,Nabak,Nabaq,Nabek,Nebeck,Nebek,Nebk,NÃ©beck,An Nabk", :latitude => "34.01667", :longitude => "36.73333").save
City.new(:country_id => "212", :name => "Al Qutayfah", :aliases => "Al Qutayfah,Al QuÅ£ayfah,Al-Kutaifeh,El Qtaife,El QtaÃ¯fÃ©,Kouteife,KouteifÃ©,Kutayfa,Kuteife,Qtaife,QtaÃ¯fÃ©,Qutayfah,Quteifa,Quteife,Quteifeh,QuÅ£ayfah,Al QuÅ£ayfah", :latitude => "33.75", :longitude => "36.6").save
City.new(:country_id => "212", :name => "Al Qusayr", :aliases => "Al Qusayr,Al QuÅayr,Al'-Kusajra,Al-Kuseir,El Qoussair,El Quseir,Kouseir,Koussaie,Kousseir,Kuseir,Qoussair,QoussaÃ¯r,Qusayr,Qusir,QuÅayr,ÐÐ»Ñ-ÐÑÑÐ°Ð¹ÑÐ°,Al QuÅayr", :latitude => "34.50914", :longitude => "36.57975").save
City.new(:country_id => "212", :name => "Al Qunaytirah", :aliases => "Al Qunaytirah,Al QunayÅ£irah,El Kuneitra,El Qnaitra,El QnaÃ¯tra,El Quneitra,Kuneitra,KuneÃ¯tra,Qhaitra,Qnaitra,Qnaytra,QnayÅ£ra,QnaÃ¯tra,Qunaytirah,Qunayturah,QunayÅ£irah,QunayÅ£urah,Quneitra,Al QunayÅ£irah", :latitude => "33.12594", :longitude => "35.82461").save
City.new(:country_id => "212", :name => "Al Qaryatayn", :aliases => "Al Qaryatayn,El Qaryatein,Kariatein,Kariateine,Karyatein,Kuriatein,Kuryatein,Nezala,Qariateine,QariateÃ¯ne,Qaryatayn,Al Qaryatayn", :latitude => "34.23333", :longitude => "37.23333").save
City.new(:country_id => "212", :name => "Al Mayadin", :aliases => "Al Mayadin,Al MayÄdÄ«n,Al-Mayadeen,Audattha,Mayadin,Mayadine,MayÄdÄ«n,Meyadin,Meyadine,Meyedine,MeyÄdÄ«n,Al MayÄdÄ«n", :latitude => "35.01667", :longitude => "40.45").save
City.new(:country_id => "212", :name => "Latakia", :aliases => "Al Ladhiqiyah,Al LÄdhiqÄ«yah,Al-Laziqiyah,El Ladhaqiye,El Ladhiqiya,El LÄdhaqiyÃ©,El LÄdhiqÄ«ya,Ladhiqiye,Ladikis,Ladikiya,Laodicea,Laodicea ad Mare,Laodicee,LaodicÃ©e,Laodikeia,Latakia,Latakieh,Latakija,Lattakia,Lattaquie,LattaquiÃ©,Lazkiye,alladhqyt,ladhqyh,ladhqyt,ltqyh,ÐÐ°ÑÐ°ÐºÐ¸Ñ,×××§××,Ø§ÙÙØ§Ø°ÙÙØ©,ÙØ§Ø°ÙÙØ©,ÙØ§Ø°ÙÛÙ,Latakia", :latitude => "35.51667", :longitude => "35.78333").save
City.new(:country_id => "212", :name => "Al Kiswah", :aliases => "Al Kiswah,Kisoue,KisouÃ©,Kissoue,Kisswa,Kiswah,Kiswe,Kisweh,Al Kiswah", :latitude => "33.3572", :longitude => "36.24278").save
City.new(:country_id => "212", :name => "Al Hasakah", :aliases => "Al Hasakah,Al á¸¨asakah,Al-Hasakeh,El Haseke,Hasakeh,Hasijih,Hassetche,Hasskih,alhskt,Ø§ÙØ­Ø³ÙØ©,á¸¨asijih,á¸¨asskih,Al á¸¨asakah", :latitude => "36.50237", :longitude => "40.74772").save
City.new(:country_id => "212", :name => "Al Harak", :aliases => "Al Harak,Al á¸¨arÄk,El Hrak,El HrÃ¢k,Al á¸¨arÄk", :latitude => "32.74932", :longitude => "36.30994").save
City.new(:country_id => "212", :name => "Al Bab", :aliases => "Al Bab,Al Balo,Al BÄb,Al BÄlo,Bab,BÃ¢b,El Bab,El BÄb,Al BÄb", :latitude => "36.3725", :longitude => "37.51778").save
City.new(:country_id => "212", :name => "`Afrin", :aliases => "Aafrine,AafrÃ®ne,Afrin,Afrine,`Afrin,`Ifrin,âAfrÄ«n,âIfrÄ«n,âAfrÄ«n", :latitude => "36.51598", :longitude => "36.86305").save
City.new(:country_id => "212", :name => "Ad Dana", :aliases => "Ad Dana,Ad Danah,Ad DÄnah,Ad DÄnÄ,Dana,DÄnÄ,Ed Dana,Ed DÃ¢na,Ad DÄnÄ", :latitude => "36.21252", :longitude => "36.76978").save
City.new(:country_id => "212", :name => "Abu Kamal", :aliases => "Abou Kemal,Abu Kamal,Abu Kemal,Abu KemÄl,Abu-Kamal',AbÅ« KamÄl,Al-bu-Kamal,Hindane,HindanÃ©,ÐÐ±Ñ-ÐÐ°Ð¼Ð°Ð»Ñ,AbÅ« KamÄl", :latitude => "34.45", :longitude => "40.91861").save
City.new(:country_id => "212", :name => "Hajin", :aliases => "Abou Hardane,Abou HardÃ¢ne,Abu Hardan,Abu Hardub,AbÅ« á¸¨ardÄn,AbÅ« á¸¨ardÅ«b,Bou Hardane,Hajin,Hajine,HajÃ®ne,HajÄ«n,HajÄ«n", :latitude => "34.68972", :longitude => "40.83").save
