City.new(:country_id => "218", :name => "Ban Talat Yai", :aliases => "Talat-Jai,Ð¢Ð°Ð»Ð°Ñ-Ð¯Ð¸,Ban Talat Yai", :latitude => "7.87973", :longitude => "98.40398").save
City.new(:country_id => "218", :name => "Ban Talat Nua", :aliases => "Talat-Nua,Ð¢Ð°Ð»Ð°Ñ-ÐÑÐ°,Ban Talat Nua", :latitude => "7.88489", :longitude => "98.38557").save
City.new(:country_id => "218", :name => "Sam Roi Yot", :aliases => "Amphoe Sam Roi Yot,Ban Sam Roi Yot,King Amphoe Sam Roi Yot,Sam Roi Yot,à¸ªà¸²à¸¡à¸£à¹à¸­à¸¢à¸¢à¸­à¸,Sam Roi Yot", :latitude => "12.27081", :longitude => "99.87203").save
City.new(:country_id => "218", :name => "Phetchaburi", :aliases => "Amphoe Khlong Krachaeng,Amphoe Muang Phet Buri,Bejraburi,Bhej Buri,Changwat Phet Buri,Moeang Bhejburi,Muang Bheja Buri,Muang Pecha Buri,Muang Petchaboun,Mueang Phetchaburi,Pechaburi,Petchaburi,Phet Buri,Phetchaburi,Pkhetchaburi,ÐÑÐµÑÑÐ°Ð±ÑÑÐ¸,à¹à¸à¸à¸£à¸à¸¸à¸£à¸µ,à¹à¸¡à¸·à¸­à¸à¹à¸à¸à¸£à¸à¸¸à¸£à¸µ,Phetchaburi", :latitude => "13.11189", :longitude => "99.94467").save
City.new(:country_id => "218", :name => "Trang", :aliases => "Amphoe Muang Trang,Changwat Trang,Trang,Ð¢ÑÐ°Ð½Ð³,Trang", :latitude => "7.55633", :longitude => "99.61141").save
City.new(:country_id => "218", :name => "Thung Song", :aliases => "Amphoe Dhung Song,Amphoe Thung Song,Amphoe Tungsong,Ban Chamai,Chamai,Dhung Song,DhÅ«ng Song,Thung Song,Tungsong,à¸à¸¸à¹à¸à¸ªà¸,Thung Song", :latitude => "8.16453", :longitude => "99.68039").save
City.new(:country_id => "218", :name => "Thoen", :aliases => "Amphoe Moeang Theun,Amphoe Moeangthenn,Amphoe Muang Thoen,Amphoe Thoen,Ban Laum Read,Ban Lohm Red,Ban Lom Raet,Lau Raet,Lohm Red,Muang Tern,Muang Teun,Muang Tharn,Muang Thoen,Thoen,à¹à¸à¸´à¸,Thoen", :latitude => "17.61289", :longitude => "99.21612").save
City.new(:country_id => "218", :name => "Thap Than", :aliases => "Amphoe Thap Than,Amphu Tap Tan,Ban Thap Than,Dhapdhan,Nong Kradi,Thap Than,à¸à¸±à¸à¸à¸±à¸,Thap Than", :latitude => "15.46063", :longitude => "99.89166").save
City.new(:country_id => "218", :name => "Tha Muang", :aliases => "Amphoe Tai,Amphoe Tha Muang,Amphoe Wang Khanai,Ban Tha Muang,Tha Muang,Wang Kanai,Wang Khanai,à¸à¹à¸²à¸¡à¹à¸§à¸,Tha Muang", :latitude => "13.96118", :longitude => "99.64122").save
City.new(:country_id => "218", :name => "Tha Maka", :aliases => "Amphoe Tha Maka,Tha Maka,Tha Maka", :latitude => "13.9", :longitude => "99.76667").save
City.new(:country_id => "218", :name => "Tak", :aliases => "Amphoe Mueang Tak,Baheng,Ban Rahaeng,Ban Raheang,Changwat Tak,Muang Raheng,Muang Tak,Rahaeng,Rahaong,Raheng,Tak,Tark,Ð¢Ð°Ðº,à¸à¸²à¸,Tak", :latitude => "16.86968", :longitude => "99.12898").save
City.new(:country_id => "218", :name => "Surat Thani", :aliases => "Amphoe Ban Don,Amphoe Muang Surat Thani,Ban Dohn,Ban Don,Ban Makham Tia,Ban Makham Tir,Bandaun,Changwat Surat,Changwat Surat Thani,Makham Tia,Mueang Surat Thani,Suras,Surashtradhani,Surat Thani,Surattkhani,suratotani,Ð¡ÑÑÐ°ÑÑÑÐ°Ð½Ð¸,à¸ªà¸¸à¸£à¸²à¸©à¸à¸£à¹à¸à¸²à¸à¸µ,à¹à¸à¸¨à¸à¸²à¸¥à¹à¸¡à¸·à¸­à¸à¸ªà¸¸à¸£à¸²à¸©à¸à¸£à¹à¸à¸²à¸à¸µ,ã¹ã©ã¼ãã¿ã¼ãã¼,Surat Thani", :latitude => "9.14011", :longitude => "99.33311").save
City.new(:country_id => "218", :name => "Sukhothai", :aliases => "Amphoe Muang Sukhothai,Amphoe Mueang Sukhothai,Amphoe Sukhodhai,Amphoe Sukhothai,Ban Thani,Changwat Sukhobhai,Changwat Sukhodhai,Changwat Sukhothai,Muang Soukotai,Muang Sukotai,New Sukhothai,Sukanthai,Sukauthai,Sukhobhai,Sukhodhai,Sukhothai,Sukhothat,Sukkhotaj,Sukodhai,sukotai,Ð¡ÑÐºÑÐ¾ÑÐ°Ð¹,à¸ªà¸¸à¹à¸à¸à¸±à¸¢,ã¹ã³ã¼ã¿ã¤,Sukhothai", :latitude => "17.00778", :longitude => "99.823").save
City.new(:country_id => "218", :name => "Si Satchanalai", :aliases => "Amphoe Si Satchanalai,Hat Siao,Si Satchanalai,à¸¨à¸£à¸µà¸ªà¸±à¸à¸à¸²à¸¥à¸±à¸¢,Si Satchanalai", :latitude => "17.51692", :longitude => "99.75978").save
City.new(:country_id => "218", :name => "Sawankhalok", :aliases => "Amphoe Sawankhalok,Ban Wang Mai Kaun,Ban Wang Mai Khon,Changwat Muang Sawarngalok,Changwat Sawankhalok,Muang Savankulok,Muang Sawan Kalok,Muang Sawankalauk,Muang Sawarngalok,Mueang Sawankhalok,Mueang Wang Mai Khon,Sawankalauk,Sawankaloke,Sawankhalok,Sawankhalor,Sawarngalok,Swankalauk,Swankhalok,Wang Mai Kuan,à¸ªà¸§à¸£à¸£à¸à¹à¸¥à¸,Sawankhalok", :latitude => "17.31597", :longitude => "99.83186").save
City.new(:country_id => "218", :name => "San Pa Tong", :aliases => "Amphoe San Pa Tong,San Pa Tong,à¸ªà¸±à¸à¸à¹à¸²à¸à¸­à¸,San Pa Tong", :latitude => "18.62828", :longitude => "98.89572").save
City.new(:country_id => "218", :name => "San Kamphaeng", :aliases => "Amphoe San Kamphaeng,Ban San Gampheang,Ban San Kamphaeng,Ban San Kamphaeng Luang,BÄn San Gampheang,Kwaeng Mae Om,San Kamphaeng,Sankambheng,SankambhÄng,à¸ªà¸±à¸à¸à¸³à¹à¸à¸,San Kamphaeng", :latitude => "18.74486", :longitude => "99.11953").save
City.new(:country_id => "218", :name => "Ron Phibun", :aliases => "Amphoe Ron Phibun,Ban Romphi Bull,Ban Ron Phibun,Raun Phibun,Ron Phibun,Ronipibon,à¸£à¹à¸­à¸à¸à¸´à¸à¸¹à¸¥à¸¢à¹,Ron Phibun", :latitude => "8.17911", :longitude => "99.85425").save
City.new(:country_id => "218", :name => "Ratchaburi", :aliases => "Amphoe Muang Rat Buri,Changwat Rat Buri,Mondhol Rajburi,Muang Rajburi,Muang Ratburi,Mueang Ratchaburi,Rajburi,Rat Buri,Ratchaburi,Ð Ð°ÑÑÐ°Ð±ÑÑÐ¸,à¸£à¸²à¸à¸à¸¸à¸£à¸µ,Ratchaburi", :latitude => "13.53671", :longitude => "99.81712").save
City.new(:country_id => "218", :name => "Ranong", :aliases => "Amphoe Muang Ranong,Changwat Ranong,Muang Ra Nohng,Muang Ranawng,Muang Ranong,Ranaong,Ranaung,Ranawng,Ranohng,Ranong,Renawng,Renong,Ð Ð°Ð½Ð¾Ð½Ð³,à¸£à¸°à¸à¸­à¸,Ranong", :latitude => "9.96583", :longitude => "98.63476").save
City.new(:country_id => "218", :name => "Pran Buri", :aliases => "Amphoe Pranburi,Ban Pak O Pran,Meuangpran,Muang Pran,Muang Pran Kao,Mueang Pran,Mueang Pran Buri,Pran,Pran Buri,à¸à¸£à¸²à¸à¸à¸¸à¸£à¸µ,Pran Buri", :latitude => "12.38466", :longitude => "99.90983").save
City.new(:country_id => "218", :name => "Prachuap Khiri Khan", :aliases => "Amphoe Muang Prachuap Khim Khan,Changwat Prachuap Khiri Khan,Muang Prachuab Giri Khan,Muang Prachuabkhirikun,PRACHUAB KHIRI KHAN,Prachuab,Prachuab Girikhan,Prachuab Khirakhanda,Prachuab Kirikan,Prachuap,Prachuap Giri Khan,Prachuap Khiri Khan,Prachuap Kirikan,Prachuapgirikhand,PrachÅ«ab GÄ«rÄ«khan,Prachuap Khiri Khan", :latitude => "11.82098", :longitude => "99.7841").save
City.new(:country_id => "218", :name => "Phunphin", :aliases => "Amphoe Phunphin,Amphoe Tha Kham,Ban Phumphin,Ban Phun Phin,Phun Phin,Phunphin,Punpin,à¸à¸¸à¸à¸à¸´à¸,Phunphin", :latitude => "9.11072", :longitude => "99.23208").save
City.new(:country_id => "218", :name => "Phuket", :aliases => "Amphoe Muang Phuket,Bhuket,Changwat Phuket,Phuket,Pkhuket,Puket,Tongka,Tongkah,phuket,ÐÑÑÐºÐµÑ,à¸ à¸¹à¹à¸à¹à¸,Phuket", :latitude => "7.89059", :longitude => "98.3981").save
City.new(:country_id => "218", :name => "Photharam", :aliases => "Amphoe Photharam,Amphu Po Ta-ram,Ban Photharam,Bhodharam,BhÅdhÄrÄm,Kwaeng Photharam,Photharam,Pkhotkharam,ÐÑÐ¾ÑÑÐ°ÑÐ°Ð¼,à¹à¸à¸à¸²à¸£à¸²à¸¡,Photharam", :latitude => "13.69234", :longitude => "99.84969").save
City.new(:country_id => "218", :name => "Phayao", :aliases => "Amphoe Moeang Bha Yao,Amphoe Muang Phayao,Amphoe Muang Pra Yao,Amphoe Phayao,Ban Nai Wiang,Bhayao,Moeangbhayao,Muang Phayao,Muang Prao,Muang Prayao,Mueang Chang Wat Pha Yao,Mueang Phayao,Phayao,Pkhajao,Prayao,ÐÑÐ°ÑÐ¾,à¸à¸±à¸à¸«à¸§à¸±à¸à¸à¸°à¹à¸¢à¸²,à¸à¸°à¹à¸¢à¸²,Phayao", :latitude => "19.19203", :longitude => "99.87883").save
City.new(:country_id => "218", :name => "Pa Sang", :aliases => "Amphoe Pa Sang,Ban Pa Sang,Pa Sang,à¸à¹à¸²à¸à¸²à¸,Pa Sang", :latitude => "18.52617", :longitude => "98.93936").save
City.new(:country_id => "218", :name => "Nakhon Si Thammarat", :aliases => "Amphoe Muang Nakhon Si Thammarat,Changwat Nakhon Si Thammarat,Lakawn,Lakon,Ligor,Muang Nagorn Sridharmaraj,Muang Nakawn Sri Tamarat,Mueang Nakhon Si Thammarat,Nagara Sridharmaraj,Nagor Sridhamaraj,Nagorn Sridharmrat,Nagorri Sridharmrat,Nakawn Sitamarat,Nakawn Sritamarat,Nakhaun Si Thammarat,Nakhon Si Tammarat,Nakhon Si Thammarat,Nakhon Si Thammarht,Nakhon Sritamarai,Nakhon Srithamarat,Nakhon Srithamrat,Nakhonsithamrat,Nakkhonsitkhammarat,Nakon,Nakon Si Tham Rat,Nakon Sitamarat,Nakon Sri Tammarat,Nakon Sritamaraj,Nakon Sritamarat,Nakorn Si Thamarat,Nakorn Sridamaraja,nakonshitanmarato,ÐÐ°ÐºÑÐ¾Ð½ÑÐ¸ÑÑÐ°Ð¼Ð¼Ð°ÑÐ°Ñ,à¸à¸à¸£à¸¨à¸£à¸µà¸à¸£à¸£à¸¡à¸£à¸²à¸,ãã³ã¼ã³ã·ã¼ã¿ã³ãã©ã¼ã,Nakhon Si Thammarat", :latitude => "8.43333", :longitude => "99.96667").save
City.new(:country_id => "218", :name => "Mae Sot", :aliases => "Amphoe Ban Mae Sot,Amphoe Mae Saut,Amphoe Mae Sot,Amphoe Mesoht,Ban Mae Sot,Ban Me Ramat,Ban Me Sohd,Ban Mesod,Branch Amphoe Me Sohd,Branch Amphoe MÄ SÅhd,Mae Saut,Mae Sord,Mae Sot,Mehsord,Mesod,Mesoht,Mesort,MÄsoht,à¹à¸¡à¹à¸ªà¸­à¸,Mae Sot", :latitude => "16.71667", :longitude => "98.56667").save
City.new(:country_id => "218", :name => "Mae Sai", :aliases => "Amphoe Mae Sai,King Amphoe Mae Sai,Mae Sai,à¹à¸¡à¹à¸ªà¸²à¸¢,Mae Sai", :latitude => "20.43353", :longitude => "99.87617").save
City.new(:country_id => "218", :name => "Mae Ramat", :aliases => "Amphoe Mae Ramat,Ban Mae Ramat,King Amphoe Mae Ramat,Mae Ramat,Meramas,Meramat,MÄramat,MÄramÄs,Tambon Mae Ramat,à¹à¸¡à¹à¸£à¸°à¸¡à¸²à¸,Mae Ramat", :latitude => "16.98403", :longitude => "98.51665").save
City.new(:country_id => "218", :name => "Mae Chan", :aliases => "Amphoe Chiang Saen,Amphoe Mae Chan,Ban Gasa,Ban Kasa,Ban Mae Chan,Ban Mea Jan,BÄn GÄsa,BÄn Mea Jan,Chiang Saen,Chieng Sean,Chiengsen,Mae Chan,Pong Hong,à¹à¸¡à¹à¸à¸±à¸,Mae Chan", :latitude => "20.14675", :longitude => "99.85256").save
City.new(:country_id => "218", :name => "Lat Yao", :aliases => "Amphoe Lat Yao,Ban Lad Yao,Ban Lat Yao,Ban Lat Yau,BÄn LÄd Yao,BÄn LÄt YÄu,Lat Yao,à¸¥à¸²à¸à¸¢à¸²à¸§,Lat Yao", :latitude => "15.751", :longitude => "99.78925").save
City.new(:country_id => "218", :name => "Lang Suan", :aliases => "Amper Khan Ngern,Amphoe Khan Ngoen,Amphoe Khanngeun,Amphoe Lang Suan,Ban Khan Ngoen,Khan Ngden,Khan Ngoen,Lang Suan,Moeang Hlang Suan,Moeang Hlang SÅ«an,Muang Hlang Suan,Muang Lang Suan,Mueang Lang Suan,à¸«à¸¥à¸±à¸à¸ªà¸§à¸,Lang Suan", :latitude => "9.94561", :longitude => "99.07847").save
City.new(:country_id => "218", :name => "Lamphun", :aliases => "Amphoe Muang Lamphun,Amphoe Mueang Lamphun,Changwat Lamphun,Changwat Muang Lamphun,Lambhun,Lamphun,Lampkhun,Lampoon,Lampun,Muang Lam Poun,Muang Lamphun,Muang Lampun,Mueang Lamphun,ÐÐ°Ð¼Ð¿ÑÑÐ½,à¸¥à¸³à¸à¸¹à¸,Lamphun", :latitude => "18.58054", :longitude => "99.00745").save
City.new(:country_id => "218", :name => "Lampang", :aliases => "Amphoe Muang Lampang,Amphoe Mueang Lampang,Changwat Lampang,Changwat Muang Lampang,Changwat Muang Nagorn Lambang,Lakhon,Lakhon Lampang,Lampang,Lampangas,Muang Lakhon Lampang,Muang Lampang,Muang Nagorn Lambang,Muang Nakon Lampang,Mueang Lampang,Nakawn,Nakawn Lampang,Nakhon Lampang,Nakon Lampang,Nakorn Lampang,ÐÐ°Ð¼Ð¿Ð°Ð½Ð³,à¸¥à¸³à¸à¸²à¸,Lampang", :latitude => "18.29232", :longitude => "99.49277").save
City.new(:country_id => "218", :name => "Kui Buri", :aliases => "Amphoe Kui Buri,Ban Kui Buri,Ban Kui Kao,Ban Kui Nua,King Amphoe Kui Buri,Kui,Kui Buri,Kui Kao,Kui Nua,Kuwi,Menangkuwi,Meng Kui,Moeang Kui,Muang Gui Gao,Muang Kui,Muang Kui Kao,Muang Kuwi,à¸à¸¸à¸¢à¸à¸¸à¸£à¸µ,Kui Buri", :latitude => "12.08283", :longitude => "99.85431").save
City.new(:country_id => "218", :name => "Krabi", :aliases => "Amphoe Muang Krabi,Amphoe Mueang Krabi,Amphoe Pak Nam,Changwat Krabi,Ghirbi,Krabi,Moeang Kra-bi,Muang Krabi,Mueang Krabi,canghwad krabi,meuxng krabi,ÐÑÐ°Ð±Ð¸,à¸à¸£à¸°à¸à¸µà¹,à¸à¸±à¸à¸«à¸§à¸±à¸à¸à¸£à¸°à¸à¸µà¹,à¹à¸¡à¸·à¸­à¸à¸à¸£à¸°à¸à¸µà¹,Krabi", :latitude => "8.07257", :longitude => "98.91052").save
City.new(:country_id => "218", :name => "Ko Samui", :aliases => "Amphoe Ko Samui,Samui,Ð¡Ð°Ð¼ÑÐ¸,Ko Samui", :latitude => "9.53423", :longitude => "99.93537").save
City.new(:country_id => "218", :name => "Khao Yoi", :aliases => "Amphoe Huai Luang,Amphoe Khao Yoi,Khao Yoi,à¹à¸à¸²à¸¢à¹à¸­à¸¢,Khao Yoi", :latitude => "13.24025", :longitude => "99.82428").save
City.new(:country_id => "218", :name => "Khanu Woralaksaburi", :aliases => "Amphoe Khanuworalak Buri,Khanu Woralaksaburi,Khanworalak Buri,King Amphoe Khanu Woralaksaburi,à¸à¸²à¸à¸¸à¸§à¸£à¸¥à¸±à¸à¸©à¸à¸¸à¸£à¸µ,Khanu Woralaksaburi", :latitude => "16.0617", :longitude => "99.86058").save
City.new(:country_id => "218", :name => "Kathu", :aliases => "Ban Talat Kathu,Kathu,Katu,Tambon Kathu,tabl kathu,ÐÐ°ÑÑ,à¸à¸³à¸à¸¥à¸à¸°à¸à¸¹à¹,Kathu", :latitude => "7.91779", :longitude => "98.33322").save
City.new(:country_id => "218", :name => "Kanchanaburi", :aliases => "Changwat Kanchanaburi,Kanburi,Kanchana,Kanchanaburi,Kanpuri,Moeang Kanchana Buri,Muang Kanchana Buri,kanchanaburi,ÐÐ°Ð½ÑÐ°Ð½Ð°Ð±ÑÑÐ¸,ã«ã¼ã³ãã£ãããªã¼,Kanchanaburi", :latitude => "14.00412", :longitude => "99.54832").save
City.new(:country_id => "218", :name => "Kamphaeng Phet", :aliases => "Amphoe Muang Kamphaeng Phet,Amphoe Mueang Kamphaeng Phet,Changwat Kamphaeng Phet,Changwat Muang Kam Bheng Bhej,Gamphaeng Phet,Gampheang Phet,Kam Baeng Bejr,Kambheng Bhej,Kamphaeng Phet,Meuangkamphayng,Muang Kam Bheng Bhej,Muang Kam Phaeng Phet,Muang Kum Pang Pet,à¸à¸³à¹à¸à¸à¹à¸à¸à¸£,Kamphaeng Phet", :latitude => "16.48344", :longitude => "99.52153").save
City.new(:country_id => "218", :name => "Huai Yot", :aliases => "Amphoe Huai Yot,Amphoe Khao Khao,Amphoe Khau Khaw,Ban Kao Kau,Ban Khaokao,Ban Nam Phrai,Ban Nem Phrai,BÄn KÄo KÄu,Huai Yot,Khao Khao,Khaokao,Khou Khaw,Nam Phrai,à¸«à¹à¸§à¸¢à¸¢à¸­à¸,Huai Yot", :latitude => "7.78933", :longitude => "99.63478").save
City.new(:country_id => "218", :name => "Hua Hin", :aliases => "Amphoe Hua Hin,Ban Hua Hin,Hau Hin,Hua Hin,King Amphoe Ban Hua Hin,King Amphoe Hua Hin,chaamu=fuwahin,hawhin-pranburi,xaphex hawhin,à¸«à¸±à¸§à¸«à¸´à¸-à¸à¸£à¸²à¸à¸à¸¸à¸£à¸µ,à¸­à¸³à¹à¸ à¸­à¸«à¸±à¸§à¸«à¸´à¸,ãã£ã¢ã =ãã¯ãã³,ãã£ã¢ã ï¼ãã¯ãã³,Hua Hin", :latitude => "12.57065", :longitude => "99.95876").save
City.new(:country_id => "218", :name => "Hang Dong", :aliases => "Amphoe Hang Dong,Ban Hang Dong,Hang Dong,Khwaeng Mae Tha Chang,King Amphoe Hang Dong,à¸«à¸²à¸à¸à¸,à¹à¸à¸§à¸à¹à¸¡à¹à¸à¹à¸²à¸à¹à¸²à¸,Hang Dong", :latitude => "18.68703", :longitude => "98.91939").save
City.new(:country_id => "218", :name => "Dok Kham Tai", :aliases => "Amphoe Dok Kham Tai,Ban Dauk Kam Tai,Ban Dauk Kam TÄi,Ban Dok Kham Tai,Dauk Kham Tai,Dok Kham Tai,King Amphoe Dok Kham Tai,à¸à¸­à¸à¸à¸³à¹à¸à¹,Dok Kham Tai", :latitude => "19.16242", :longitude => "99.99342").save
City.new(:country_id => "218", :name => "Damnoen Saduak", :aliases => "Amphoe Damnoen Saduak,Ban Damnoen Saduak,Ban Khlong Damnoen Saduak,Damnoen Saduak,Damnoensaduak,ÐÐ°Ð¼Ð½Ð¾ÐµÐ½ÑÐ°Ð´ÑÐ°Ðº,à¸à¸³à¹à¸à¸´à¸à¸ªà¸°à¸à¸§à¸,Damnoen Saduak", :latitude => "13.51824", :longitude => "99.95469").save
City.new(:country_id => "218", :name => "Chumphon", :aliases => "Amphoe Muang Chumphon,Champawn,Changwat Chumphon,Chumphaun,Chumphon,Chumpkhon,Chumpon,Chumporn,Jumbhorn,Jumbor,Muang Champawn,Muang Choum Pon,Muang Chum Pon,Muang Chumporn,Muang Jum Bhorn,Mueang Chumphon,Ð§ÑÐ¼Ð¿ÑÐ¾Ð½,à¸à¸¸à¸¡à¸à¸£,Chumphon", :latitude => "10.5", :longitude => "99.16667").save
City.new(:country_id => "218", :name => "Chom Bueng", :aliases => "Amphoe Chom Bueng,Amphoe Chom Bung,Ban Chom Bung,Chaum Boeng,Chohm Boeng,Chom Bueng,Chom Bung,King Amphoe Chom Bueng,King Chom Bung,à¸à¸­à¸¡à¸à¸¶à¸,Chom Bueng", :latitude => "13.62", :longitude => "99.59169").save
City.new(:country_id => "218", :name => "Chiang Rai", :aliases => "Amphoe Chiang Rai,Amphoe Muang Chiang Rai,Chang Rai,Changwat Chiang Rai,Changwat Muang Chiang Rai,Changwat Muang Jieng Rai,Chiang Rai,Chiang-Raj,Chiengrai,Cziang Raj,Jieng Rai,Muang Chiang Rai,Muang Chieng Rai,Muang Jieng Rai,Mueang Chiang Rai,Xieng Rai,chienrai,qing lai,Ð§Ð¸Ð°Ð½Ð³-Ð Ð°Ð¹,×¦'××× × ×¨××,à¹à¸à¸µà¸¢à¸à¸£à¸²à¸¢,ãã¨ã³ã©ã¼ã¤,æ¸è,Chiang Rai", :latitude => "19.90858", :longitude => "99.8325").save
City.new(:country_id => "218", :name => "Chiang Mai", :aliases => "Amphoe Muang Chiang Mai,Changwat Chiang Mai,Chiang Mai,Chiang-Maj,Chiangmai,Chiengmai,Cziang Maj,Kiangmai,Muang Chieng Mai,Muang Jieng Hmai,Mueang Chiang Mai,Xieng Mai,Zimme,ZimmÃ©,chiangmai,chienmai,qing mai,Ð§Ð¸Ð°Ð½Ð³-ÐÐ°Ð¹,×¦'×× × ×××,×¦'××× × ×××,à¹à¸à¸µà¸¢à¸à¹à¸«à¸¡à¹,à¹à¸¡à¹à¸£à¸´à¸¡ à¹à¸à¸µà¸¢à¸à¹à¸«à¸¡à¹,ãã¨ã³ãã¤,æ¸è¿,æ¸é,ì¹ìë§ì´,Chiang Mai", :latitude => "18.79038", :longitude => "98.98468").save
City.new(:country_id => "218", :name => "Cha-am", :aliases => "Amphoe Cha-am,Amphoe Na Yang,Amphoe Nong Chok,Ban Chaam,Cha Am,Cha-am,Sha-am,chaxa,Ð§Ð°-Ð°Ð¼,à¸à¸°à¸­à¸³,Cha-am", :latitude => "12.8", :longitude => "99.96667").save
City.new(:country_id => "218", :name => "Bo Phloi", :aliases => "Amphoe Bo Phloi,Ban Bo Phloi,Bo Phloi,King Bau Phloi,King Bo Phloi,Bo Phloi", :latitude => "14.32361", :longitude => "99.51611").save
City.new(:country_id => "218", :name => "Ban Tak", :aliases => "Amphoe Ban Tak,Ban Tak,Tak,à¸à¹à¸²à¸à¸à¸²à¸,Ban Tak", :latitude => "17.04325", :longitude => "99.08128").save
City.new(:country_id => "218", :name => "Ban Pong", :aliases => "Amphoe Ban Pong,Amphu Ban Pong,Ban Pong,Pan-pong,ÐÐ°Ð½-Ð¿Ð¾Ð½Ð³,à¸à¹à¸²à¸à¹à¸à¹à¸,Ban Pong", :latitude => "13.81629", :longitude => "99.87739").save
City.new(:country_id => "218", :name => "Ban Na San", :aliases => "Amphoe Ban Na,Ban Na San,Na Sau,Nasan,à¸à¹à¸²à¸à¸à¸²à¸ªà¸²à¸£,Ban Na San", :latitude => "8.80036", :longitude => "99.36372").save
City.new(:country_id => "218", :name => "Ban Na", :aliases => ",Ban Na", :latitude => "17.03056", :longitude => "99.7525").save
City.new(:country_id => "218", :name => "Bang Saphan", :aliases => "Amphoe Bang Saphan,Amphu Bangspan,Ban Bang Saphan Yai,Bang Saphan Yai,Bangsabhan,Bang Saphan", :latitude => "11.21259", :longitude => "99.51167").save
City.new(:country_id => "218", :name => "Bang Phae", :aliases => "Amphoe Bang Phae,Amphoe Hua Pho,Amphoe Lam Phraya,Ban Bang Phae,Ban Bang Phae Tai,Bang Phae,Bang Phae Tai,Tha Rap,à¸à¸²à¸à¹à¸,Bang Phae", :latitude => "13.69157", :longitude => "99.92982").save
City.new(:country_id => "218", :name => "Nong Kung Si", :aliases => ",Nong Kung Si", :latitude => "16.65", :longitude => "103.3").save
City.new(:country_id => "218", :name => "Ban Nong Wua So", :aliases => ",Ban Nong Wua So", :latitude => "17.2675", :longitude => "103.22472").save
City.new(:country_id => "218", :name => "Ban Mai", :aliases => "Ban Mai,à¸à¹à¸²à¸à¹à¸«à¸¡à¹,Ban Mai", :latitude => "7.20411", :longitude => "100.54508").save
City.new(:country_id => "218", :name => "Ban Huai Thalaeng", :aliases => ",Ban Huai Thalaeng", :latitude => "14.98333", :longitude => "102.65").save
City.new(:country_id => "218", :name => "Ban Khlong Bang Sao Thong", :aliases => "Ban Bang Sao Thong,Ban Khlong Bang Sao Thong,à¸à¹à¸²à¸à¸à¸¥à¸­à¸à¸à¸²à¸à¹à¸ªà¸²à¸à¸,Ban Khlong Bang Sao Thong", :latitude => "13.64172", :longitude => "100.83272").save
City.new(:country_id => "218", :name => "Na Klang", :aliases => "Na Klang,à¸à¸²à¸à¸¥à¸²à¸,Na Klang", :latitude => "17.3072", :longitude => "102.18886").save
City.new(:country_id => "218", :name => "Yasothon", :aliases => "Amphoe Muang Yasothon,Amphoe Yasodhom,Amphoe Yasodhorn,Amphoe Yasothon,Ban Nai Muang,Ban Singh Tha,Changwat Yasothon,Jasotkhon,Muang Iott-so Ton,Muang Yasothaun,Muang Yasothon,Mueang Yasothon,Yasodhorn,Yasotawn,Yasothon,Yasotorn,Ð¯ÑÐ¾ÑÑÐ¾Ð½,à¸¢à¹à¸ªà¸à¸£,Yasothon", :latitude => "15.79408", :longitude => "104.1451").save
City.new(:country_id => "218", :name => "Yaring", :aliases => "Amphoe Yamu,Amphoe Yaring,Ban Yamu,Jaring,Muang Yaring,Muang Yering,Yamu,Yaring,à¸¢à¸°à¸«à¸£à¸´à¹à¸,Yaring", :latitude => "6.86617", :longitude => "101.36894").save
City.new(:country_id => "218", :name => "Yala", :aliases => "Amphoe Mueang Yala,Amphoe Yala,Ban Yala,Changwat Yala,Jala,Muang Yala,Mueang Yala,Yala,Ð¯Ð»Ð°,à¸¢à¸°à¸¥à¸²,Yala", :latitude => "6.53995", :longitude => "101.28128").save
City.new(:country_id => "218", :name => "Wiset Chaichan", :aliases => "Amphoe Phai Cham Sin,Amphoe Wiset Chai Chan,Wises Jai-jan,Wises Jai-jÄn,Wiset Chai Chan,Wiset Chaichan,à¸§à¸´à¹à¸¨à¸©à¸à¸±à¸¢à¸à¸²à¸,Wiset Chaichan", :latitude => "14.5945", :longitude => "100.33825").save
City.new(:country_id => "218", :name => "Wichian Buri", :aliases => "Amphoe Tha Rong,Amphoe Wichian,Amphoe Wichian Buri,Amphoe Wijiern,Ban Wichian,Tha Rong,Wi-jiern,Wi-jiÄrn,Wichian,Wichian Buri,à¸§à¸´à¹à¸à¸µà¸¢à¸£à¸à¸¸à¸£à¸µ,Wichian Buri", :latitude => "15.65778", :longitude => "101.10603").save
City.new(:country_id => "218", :name => "Warin Chamrap", :aliases => "Amphoe Thaksin Ubon,Amphoe Warin Chamrap,Amphoe Warinjamrap,Ban That,Varindra,Warim Chamrap,Warin Chamrap,à¸§à¸²à¸£à¸´à¸à¸à¸³à¸£à¸²à¸,Warin Chamrap", :latitude => "15.19319", :longitude => "104.8628").save
City.new(:country_id => "218", :name => "Wang Saphung", :aliases => "Amphoe Wang Saphung,Ban Wang Sa Pung,Ban Wang San Phung,Ban Wang Saphung,Khwaeng Wang Saphung,Wang Saphung,Wangsabhung,à¸§à¸±à¸à¸ªà¸°à¸à¸¸à¸,Wang Saphung", :latitude => "17.30097", :longitude => "101.7685").save
City.new(:country_id => "218", :name => "Wang Noi", :aliases => "Amphoe Uthai Noi,Amphoe Wang Noi,Ban Bang Pla Kot Noi,Ban Wang Noi,Wang Noi,à¸§à¸±à¸à¸à¹à¸­à¸¢,Wang Noi", :latitude => "14.22689", :longitude => "100.7155").save
City.new(:country_id => "218", :name => "Wang Nam Yen", :aliases => "Amphoe Wang Nam Yen,King Amphoe Wang Nam Yen,Wang Nam Yen,à¸§à¸±à¸à¸à¹à¸³à¹à¸¢à¹à¸,Wang Nam Yen", :latitude => "13.50325", :longitude => "102.18115").save
City.new(:country_id => "218", :name => "Uttaradit", :aliases => "Amphoe Mueang Uttaradit,Changwat Muang Utaradith,Changwat Uttaradit,Muang Utaradit,Muang Utaradith,Outaradit,Utaradit,Utaraditra,Uttaradit,Uttradit,Ð£ÑÑÐ°ÑÐ°Ð´Ð¸Ñ,à¸­à¸¸à¸à¸£à¸à¸´à¸à¸à¹,Uttaradit", :latitude => "17.62557", :longitude => "100.09421").save
City.new(:country_id => "218", :name => "Uthai Thani", :aliases => "Amphoe Nam Sum,Ban Nam Sum,Changwat Muang Uthai Thani,Changwat Uthai Thani,Muang Udhai Dhani,Muang Utai Tani,Muang Uthai Thani,Mueang Uthai Thani,Udhaidhani,Uthai Thani,à¸­à¸¸à¸à¸±à¸¢à¸à¸²à¸à¸µ,Uthai Thani", :latitude => "15.37939", :longitude => "100.0245").save
City.new(:country_id => "218", :name => "Udon Thani", :aliases => "Ban Dua Makeng,Ban Ma Keng,Ban Mak Khaeng,Bar Deua Ma Khong,Changwat Udaunthani,Changwat Udon Thani,Mak Khaeng,Mueang Udon Thani,Udaun Thani,Udon,Udon Thani,Udon-Tkhani,Udorn,Udorndhani,Udornthani,Ð£Ð´Ð¾Ð½-Ð¢ÑÐ°Ð½Ð¸,à¸­à¸¸à¸à¸£à¸à¸²à¸à¸µ,Udon Thani", :latitude => "17.41567", :longitude => "102.78589").save
City.new(:country_id => "218", :name => "Ubon Ratchathani", :aliases => "Changwat Muang Ubon,Changwat Ubon Ratchathani,Muang Ubol,Muang Ubon,Muang Ubon Ratcha-Thani,Muang Ubun,Mueang Ubon Ratchathani,Oubon,Ubol,Ubol Rachatani,Ubol Rajadhani,Ubolrajdhani,Ubon,Ubon Rachatani,Ubon Rachpani,Ubon Ratchathani,Ubon Ratczathani,Ubonrajathani,Ubonrajdhani,Ubonrajthani,ubonrachatani,xaphex meuxng xublrachthani,à¸­à¸³à¹à¸ à¸­à¹à¸¡à¸·à¸­à¸à¸­à¸¸à¸à¸¥à¸£à¸²à¸à¸à¸²à¸à¸µ,à¸­à¸¸à¸à¸¥à¸£à¸²à¸à¸à¸²à¸à¸µ,ã¦ãã³ã©ã¼ãã£ã¿ã¼ãã¼,Ubon Ratchathani", :latitude => "15.22483", :longitude => "104.85289").save
City.new(:country_id => "218", :name => "Trat", :aliases => "Ban Bang Phra,Ban Prah,Bang Phra,Changwat Trat,Krat,Muang Krat,Trad,Trat,Ð¢ÑÐ°Ñ,Trat", :latitude => "12.24364", :longitude => "102.51514").save
City.new(:country_id => "218", :name => "Tha Yang", :aliases => "Amphoe Tha Yang,Ban Tha Yang,Tha Yang", :latitude => "12.95772", :longitude => "99.90555").save
City.new(:country_id => "218", :name => "Tha Rua", :aliases => "Amphoe Nakhon Noi,Amphoe Tha Rua,Ban Tah Roea,Ban Tha Rua,Dha Roea,DhÄ RoÄa,Tha Rha,Tha Rua,à¸à¹à¸²à¹à¸£à¸·à¸­,Tha Rua", :latitude => "14.56739", :longitude => "100.72598").save
City.new(:country_id => "218", :name => "Thap Khlo", :aliases => "Amphoe Thap Khlo,King Amphoe Thap Khlo,Thap Khlo,à¸à¸±à¸à¸à¸¥à¹à¸­,Thap Khlo", :latitude => "16.16003", :longitude => "100.59656").save
City.new(:country_id => "218", :name => "Tha Mai", :aliases => "Amphoe Khamong,Amphoe Phloi Waen,Amphoe Tha Mai,Ban Tha Mai,Talat Amphoe Tha Mai,Tha Mai,à¸à¹à¸²à¹à¸«à¸¡à¹,Tha Mai", :latitude => "12.62137", :longitude => "102.0048").save
City.new(:country_id => "218", :name => "Tha Bo", :aliases => "Amphoe Tha Bo,Ban Tha Bau,Ban Tha Bo,Mong Ta Bo,Mueang Tha Bo,MÃ¶ng Ta Bo,Tha Bo,Tha Bor,à¸à¹à¸²à¸à¹à¸­,Tha Bo", :latitude => "17.85003", :longitude => "102.58139").save
City.new(:country_id => "218", :name => "Taphan Hin", :aliases => "Amphoe Taphan Hin,King Amphoe Taphan Hin,Taphan Hin,à¸à¸°à¸à¸²à¸à¸«à¸´à¸,Taphan Hin", :latitude => "16.22094", :longitude => "100.41978").save
City.new(:country_id => "218", :name => "Tak Bai", :aliases => "Amphoe Kampong Chehe,Amphoe Tak Bai,Ampur Takbai,Ban Takbai,Chavhay,Chayhay,Che He,Kampong Chehe,Tak Bai,Takbar,à¸à¸²à¸à¹à¸,Tak Bai", :latitude => "6.25947", :longitude => "102.05461").save
City.new(:country_id => "218", :name => "Surin", :aliases => "Changwat Surin,Muang Sourin,Muang Surin,Mueang Surin,Surin,Surindr,Surindra,Ð¡ÑÑÐ¸Ð½,à¸ªà¸¸à¸£à¸´à¸à¸à¸£à¹,Surin", :latitude => "14.88181", :longitude => "103.49364").save
City.new(:country_id => "218", :name => "Suphan Buri", :aliases => "Amphoe Muang Suphan Buri,Ban Tha Phi Liang,Changwat Suphan Buri,Muang Subharn,Muang Supan,Muang Suphan,Mueang Suphan Buri,Subhan Buri,Subharn,Sufan Buri,Supan,Supanburi,Supham Buri,Suphan Buri,Thaphi Liang,Ð¡ÑÑÐ°Ð½ ÐÑÑÐ¸,à¸ªà¸¸à¸à¸£à¸£à¸à¸à¸¸à¸£à¸µ,Suphan Buri", :latitude => "14.47418", :longitude => "100.12218").save
City.new(:country_id => "218", :name => "Su-ngai Kolok", :aliases => "Amphoe Sungai Kolok,King Amphoe Su-ngai Kolok,Kolok,Su-ngai Kolok,Sungai Kolok,Sungei Kolok,à¸ªà¸¸à¹à¸«à¸à¹à¸-à¸¥à¸,Su-ngai Kolok", :latitude => "6.02977", :longitude => "101.96586").save
City.new(:country_id => "218", :name => "Songkhla", :aliases => "Amphoe Muang Songkhla,Changwat Songkhla,Monthon Nakhon Si Thamarat,Monthon Nakhon Si Thammarat,Muang Sawng Kla,Muang Songkla,Sawng Kla,Senggora,Singgora,Singora,Singorra,Songkhla,Songkkhla,Songkla,Sung Kla,sngkhla,Ð¡Ð¾Ð½Ð³ÐºÑÐ»Ð°,à¸ªà¸à¸à¸¥à¸²,Songkhla", :latitude => "7.19882", :longitude => "100.5951").save
City.new(:country_id => "218", :name => "Si Sa Ket", :aliases => "Amphoe Muang Sisaket,Amphoe Sisaket,Cangwat Khukhan,Changwat Khu Khan,Changwat Si Sa Ket,Khukhan,Muang Sisaket,Muang Srisaket,Mueang Si Sa Ket,Si Sa Ket,Si Saket,Sisakate,Sisaket,Srisakesa,Srisaket,Ð¡Ð¸ Ð¡Ð° ÐÐµÑ,à¸¨à¸£à¸µà¸ªà¸°à¹à¸à¸©,Si Sa Ket", :latitude => "15.11481", :longitude => "104.32938").save
City.new(:country_id => "218", :name => "Si Racha", :aliases => "Amphoe Si Racha,Amphu Sri Maha Raja,Ban Si Racha,Ban Sriracha,Si Racha,Sri Maha Raja,Sri MahÄ RÄjÄ,Sriracha,Srirachi,à¸¨à¸£à¸µà¸£à¸²à¸à¸²,Si Racha", :latitude => "13.17372", :longitude => "100.93111").save
City.new(:country_id => "218", :name => "Sing Buri", :aliases => "Amphoe Muang Sing Buri,Ban Bang Phutsa,Ban Bang Putsa,Bang Phutsa,Changwat Sing Buri,Muang Sing,Mueang Sing Buri,Sing,Sing Buri,Singburi,Singha Buri,Ð¡Ð¸Ð½Ð³ ÐÑÑÐ¸,à¸ªà¸´à¸à¸«à¹à¸à¸¸à¸£à¸µ,Sing Buri", :latitude => "14.88786", :longitude => "100.40464").save
City.new(:country_id => "218", :name => "Seka", :aliases => "Amphoe Seka,King Amphoe Seka,Seka,à¹à¸à¸à¸²,Seka", :latitude => "17.92851", :longitude => "103.95519").save
City.new(:country_id => "218", :name => "Sawang Daen Din", :aliases => "Amphoe Sawang Daen Din,Ban Han,Mueang Sawang Daen Din,Sawang Daen Din,Sawang Din Daen,à¸ªà¸§à¹à¸²à¸à¹à¸à¸à¸à¸´à¸,Sawang Daen Din", :latitude => "17.47531", :longitude => "103.45753").save
City.new(:country_id => "218", :name => "Satun", :aliases => "Changwat Satun,Satul,Satun,Setul,Ð¡Ð°ÑÑÐ½,à¸ªà¸à¸¹à¸¥,Satun", :latitude => "6.62314", :longitude => "100.06676").save
City.new(:country_id => "218", :name => "Sattahip", :aliases => "Amphoe Sattahip,Ban Sata Hib,Ban Satahip,Ban Sattahip,King Amphoe Sattahip,Satahib,Sattaheeb,Sattaheep,Sattahib,Sattahiep,Sattahip,à¸ªà¸±à¸à¸«à¸µà¸,Sattahip", :latitude => "12.66644", :longitude => "100.90073").save
City.new(:country_id => "218", :name => "Saraburi", :aliases => "Ban Pak Phrieo,Changwat Sara Buri,Muang Sara Buri,Pak Phrieu,Pak Phrio,Pak Preo,Sita,Sraburi,Saraburi", :latitude => "14.53333", :longitude => "100.91667").save
City.new(:country_id => "218", :name => "Samut Songkhram", :aliases => "Amphoe Ban Prok,Amphoe Lam Thuan,Changwat Samut Songkkhram,Mae Khlaung,Mae Klong,Maikulaung,Maklong,Me Klawng,Me-klohng,Meh Klong,Meklong,Muang Samudh Songgram,Muang Samut Sang Khran,Muang Samut Songgram,Mueang Samut Songkhram,Samudh Songgram,Samudh SÅnggrÄm,Samut Songkhram,Samut Songkram,Smut Songkhram,à¸ªà¸¡à¸¸à¸à¸£à¸ªà¸à¸à¸£à¸²à¸¡,Samut Songkhram", :latitude => "13.41456", :longitude => "100.00264").save
City.new(:country_id => "218", :name => "Samut Sakhon", :aliases => "Ban Maha Chai,Ban Tachin,Changwat Samut Sakhon,Dha-chin,Mahachai,Muang Samudh Sagorn,Muang Samut Sakawn,Muang Samut Sakhon,Mueang Sakhon Buri,Mueang Samut Sakhon,Mueang Tha Chin,Samudh Sagorn,Samut Sakhon,Smutsakhon,Taachin,Tachin,Tanchin,Tha Chin,à¸ªà¸¡à¸¸à¸à¸£à¸ªà¸²à¸à¸£,Samut Sakhon", :latitude => "13.54753", :longitude => "100.27362").save
City.new(:country_id => "218", :name => "Samut Prakan", :aliases => "Amphoe Mueang Samut Prakan,Ban Pak Nam,Changwat Samut Prakan,Muang Samudh Prakarn,Muang Samut Prakan,Muang Samut Prakon,Paakunamu,Pakham,Paknam,Samudh Prakarn,Samut,Samut Prakan,Samutpraken,Smutprakan,samuttopurakan,xaphex meuxng smuthrprakar,Ð¡Ð°Ð¼ÑÑ ÐÑÐ°ÐºÐ°Ð½,à¸­à¸³à¹à¸ à¸­à¹à¸¡à¸·à¸­à¸à¸ªà¸¡à¸¸à¸à¸£à¸à¸£à¸²à¸à¸²à¸£,ãµã ãããã©ã¼ã«ã¼ã³,Samut Prakan", :latitude => "13.59934", :longitude => "100.59675").save
City.new(:country_id => "218", :name => "Sam Phran", :aliases => "Amphoe Sam Phran,Amphoe Talat Mai,Ban Sam Phran,Sam Phran,à¸ªà¸²à¸¡à¸à¸£à¸²à¸,Sam Phran", :latitude => "13.72698", :longitude => "100.21526").save
City.new(:country_id => "218", :name => "Sakon Nakhon", :aliases => "Amphoe Muang Sakhon Nakhon,Ban That Choeng Chum,Changwat Muang Sakhon Nakhon,Changwat Sakon Nakhon,Muang Sakol Nakorn,Muang Sakon Lakon,Muang Sakon Nakawn,Muang Sakon Nakon,Mueang Sakon Nakhon,Sakhon Nakhon,Sakol,Sakol Nagorn,Sakol Nakorn,Sakon Nakawn,Sakon Nakhaun,Sakon Nakhon,Sakon Nakorn,Skol Nakon,Thatchoengchum,à¸ªà¸à¸¥à¸à¸à¸£,Sakon Nakhon", :latitude => "17.16116", :longitude => "104.14725").save
City.new(:country_id => "218", :name => "Sa Kaeo", :aliases => "Amphoe Mueang Sa Kaeo,Amphoe Sa Kaeo,Ban Sa Kaeo,King Amphoe Sa Kaeo,Mueang Sa Kaeo,Sa Kaeo,Sa Kaew,Sa Keo,Sakaeo,Sara Kaeo,Srakeo,à¸ªà¸£à¸°à¹à¸à¹à¸§,Sa Kaeo", :latitude => "13.81411", :longitude => "102.07222").save
City.new(:country_id => "218", :name => "Sadao", :aliases => "Ban Sadao,Sadao,Sendawa,Ð¡Ð°Ð´Ð°Ð¾,à¸ªà¸°à¹à¸à¸²,Sadao", :latitude => "6.63883", :longitude => "100.42342").save
City.new(:country_id => "218", :name => "Roi Et", :aliases => "Amphoe Muang Roi Et,Changwat Muang Roi Et,Changwat Roi Et,Muang Roi Et,Rio Et,Roi Ech,Roi Eht,Roi Et,Roi-ed,Ð Ð¾Ð¸ Ð­Ñ,Roi Et", :latitude => "16.0567", :longitude => "103.65309").save
City.new(:country_id => "218", :name => "Rayong", :aliases => "Muang Ra-yohng,Muang Rayong,Rajong,Rayaung,Rayohng,Rayong,Ð Ð°Ð¹Ð¾Ð½Ð³,Rayong", :latitude => "12.68095", :longitude => "101.25798").save
City.new(:country_id => "218", :name => "Ranot", :aliases => "Amphoe Ranot,Ban Rahnot,Ban Ranok,Ban Ranot,Cha Thing Phra,King Amphoe Cha Thing Phra,Rahnot,Ranod,Ranot,Renut,à¸£à¸°à¹à¸à¸,Ranot", :latitude => "7.77768", :longitude => "100.32134").save
City.new(:country_id => "218", :name => "Ra-ngae", :aliases => "Amphoe Rangae,Ban Tanyong Mat,Kampong Bangae,Kampong Bangek,Mueang Ra-ngae,Ra-ngae,Rangek,Tanyong Mas,Tanyong Mat,à¸£à¸°à¹à¸à¸°,Ra-ngae", :latitude => "6.29678", :longitude => "101.72844").save
City.new(:country_id => "218", :name => "Prakhon Chai", :aliases => "Amphoe Prakhon Chai,Amphoe Talung,Ban Pradonchai,Makong Xai,Muang Makong Se,Muang Makong Xai,Muang Nakawn Chai,Muang Nakhaun Chai,Muang Nakhon Chai,Muang Pa Khon Thai,Pakenejai,Pradonchai,Prakhan Chai,Prakhon Chai,Talung,Prakhon Chai", :latitude => "14.60592", :longitude => "103.12081").save
City.new(:country_id => "218", :name => "Prachin Buri", :aliases => "Amphoe Muang Prachin Buri,Changwat Prachin Buri,Muang Prachin Buri,Mueang Prachin Buri,Pachim,Prachim,Prachin,Prachin Buri,à¸à¸£à¸²à¸à¸µà¸à¸à¸¸à¸£à¸µ,Prachin Buri", :latitude => "14.04992", :longitude => "101.36864").save
City.new(:country_id => "218", :name => "Phu Kradueng", :aliases => "Amphoe Phu Kradueng,Ban Wong Wian,King Amphoe Phu Kradueng,Phu Kradueng,Phu Kradung,à¸ à¸¹à¸à¸£à¸°à¸à¸¶à¸,Phu Kradueng", :latitude => "16.88425", :longitude => "101.88467").save
City.new(:country_id => "218", :name => "Phu Khiao", :aliases => "Amphoe Phu Khieo,Ban Phak Pang,Mueang Phu Khiao,Phak Pang,Pho Khieo,Phu Khiao,Phu Khieo,à¸ à¸¹à¹à¸à¸µà¸¢à¸§,Phu Khiao", :latitude => "16.3765", :longitude => "102.12853").save
City.new(:country_id => "218", :name => "Phra Pradaeng", :aliases => "Amphoe Bhra Pradeng,Amphoe Bhra PradÄng,Amphoe Phra Padaeng,Amphoe Phra Pradaeng,Bhra Pradeng,Khoan Khan,Muang Nagorn Khoean Khan,Muang Nakawn Khoan Khan,Muang Nakhon Khaun Khan,Muang Nakhon Khuan Khan,Nakhon Khuan Khan,Nakhon Khuen Khan,Phra Pradaeng,purapuraden jun,à¸à¸£à¸°à¸à¸£à¸°à¹à¸à¸,à¸­à¸³à¹à¸ à¸­à¸à¸£à¸°à¸à¸£à¸°à¹à¸à¸,ãã©ãã©ãã¼ã³é¡,Phra Pradaeng", :latitude => "13.65854", :longitude => "100.53362").save
City.new(:country_id => "218", :name => "Phra Phutthabat", :aliases => "Amphoe Phra Phutthabat,Ban Khun Khlon,Bhra Bhudhabadh,Bhra BhudhÄbadh,Khun Khlon,King Amphoe Phra Phutthabat,King Phra Phutthabat,Phra Phutthabat,Phra Phutthabet,à¸à¸£à¸°à¸à¸¸à¸à¸à¸à¸²à¸,Phra Phutthabat", :latitude => "14.72526", :longitude => "100.79536").save
City.new(:country_id => "218", :name => "Phra Nakhon Si Ayutthaya", :aliases => "Ajuthaja,Ajutija,Amphoe Krung Kao,Amphoe Phra Nakhon Si Ayutthaya,Amphoe Rop Krung,Ayouthia,Ayudhya,Ayuthaya,Ayuthia,Ayuthya,Ayutia,Ayutthaya,Ayutthaya - phrankhrsrixyuthya,Ayutthaya - à¸à¸£à¸°à¸à¸à¸£à¸¨à¸£à¸µà¸­à¸¢à¸¸à¸à¸¢à¸²,Ayutthia,Ayutya,Changwat Phra Nakhon Si Ayutthaya,Krung Kao,Monthon Ayutthaya,Phra Nakhon Si Ax Ayutthaya,Phra Nakhon Si Ayutthaya,ayutaya,xyuthya,ÐÑÑÐ¸Ñ,à¸à¸£à¸°à¸à¸à¸£à¸¨à¸£à¸µà¸­à¸¢à¸¸à¸à¸¢à¸²,à¸­à¸¢à¸¸à¸à¸¢à¸²,ã¢ã¦ã¿ã¤,Phra Nakhon Si Ayutthaya", :latitude => "14.35167", :longitude => "100.57739").save
City.new(:country_id => "218", :name => "Phrae", :aliases => "Amphoe Muang Phrae,Amphoe Mueang Phrae,Bhre,Changwat Muang Bhre,Changwat Muang BhrÃ©,Changwat Muang Phrae,Changwat Phrae,Muang Bhre,Muang Phrae,Muang Pre,Mueang Phrae,Phrae,Phrea,Pkhrae,Prae,Pre,ÐÑÑÐ°Ðµ,à¹à¸à¸£à¹,Phrae", :latitude => "18.14589", :longitude => "100.14103").save
City.new(:country_id => "218", :name => "Phon Charoen", :aliases => ",Phon Charoen", :latitude => "18.03333", :longitude => "103.16667").save
City.new(:country_id => "218", :name => "Phitsanulok", :aliases => "Amphoe Muang Phitsanulok,Amphoe Mueang Phitsanulok,Bhisanulok,Bisanulok,Bisnulok,Changwat Phitsanulok,Muang Phitsanulok,Muang Pitsanulok,Philtsanuloke,Phisanulauk,Phitsanulok,Pisanuloke,Pitsanoulok,Pitsanulok,Pitsanuloke,Pkhitsanulok,ÐÑÐ¸ÑÑÐ°Ð½ÑÐ»Ð¾Ðº,à¸à¸´à¸©à¸à¸¸à¹à¸¥à¸,à¹à¸¡à¸·à¸­à¸à¸à¸´à¸©à¸à¸¸à¹à¸¥à¸,Phitsanulok", :latitude => "16.82481", :longitude => "100.25858").save
City.new(:country_id => "218", :name => "Phichit", :aliases => "Amphoe Muang Phichit,Amphoe Ta Luang,Amphoe Tha Luang,Ban Nai Muang,Bhichit,Changwat Muang Bichit,Changwat Muang Phichit,Changwat Phichit,Muang Bhichit,Muang Phichit,Muang Phijit,Muang Pitchit,Okhaburi,Phichit,Pichit,Pkhichit,Sra Luang,Tha Luang,ÐÑÐ¸ÑÐ¸Ñ,à¸à¸´à¸à¸´à¸à¸£,Phichit", :latitude => "16.44184", :longitude => "100.34879").save
City.new(:country_id => "218", :name => "Phibun Mangsahan", :aliases => "Amphoe Bhimunmangsaharn,Amphoe Phibun Mangsahan,Amphoe Phimun Mangahan,Amphoe Phimun Mangsahan,Ban Phimun,Muang Phi Moun,Muang Pimour,Phi Moun,Phibun Mangdshan,Phibun Mangsahan,Phimun,Phimun Mangsahan,Phinum Mangsahan,Pibulmangsahan,Pimool,Pimul,Pimun,à¸à¸´à¸à¸¹à¸¥à¸¡à¸±à¸à¸ªà¸²à¸«à¸²à¸£,Phibun Mangsahan", :latitude => "15.24467", :longitude => "105.22908").save
City.new(:country_id => "218", :name => "Phetchabun", :aliases => "Amphoe Muang Phetchabun,Bhejaburn,Changwat Muang Bheia Burn,Changwat Muang BhÄia BÅ«rn,Changwat Muang Phetchabun,Changwat Phetchabun,Muang Bheia Burn,Muang Petchboun,Muang Phecha Bun,Muang Phetchabun,Pechabun,Petchabun,Phetchabun,Pkhetchabun,ÐÑÐµÑÑÐ°Ð±ÑÐ½,Phetchabun", :latitude => "16.41904", :longitude => "101.16056").save
City.new(:country_id => "218", :name => "Phatthalung", :aliases => "Amphoe Klang Mueang,Amphoe Lampam,Amphoe Muang Phatthalung,Badalung,Bhadhalung,Changwat Phattalung,Changwat Phatthalung,Muang Patalung,Mueang Phatthalung,Patalung,Phatalung,Phathalung,Phattalung,Phatthalung,Pkhetchabun,ÐÑÐµÑÑÐ°Ð±ÑÐ½,à¸à¸±à¸à¸¥à¸¸à¸,Phatthalung", :latitude => "7.61786", :longitude => "100.07792").save
City.new(:country_id => "218", :name => "Phan Thong", :aliases => "Amphoe Phan Thong,Amphoe Tha Ta Kut,Phan Thong,à¸à¸²à¸à¸à¸­à¸,Phan Thong", :latitude => "13.46804", :longitude => "101.09532").save
City.new(:country_id => "218", :name => "Phanom Sarakham", :aliases => "Amphoe Phanom Sarakham,Amphu Panom Sarakam,Ban Phanom Sarakham,Bhanom Saragam,Phanom Sarakham,à¸à¸à¸¡à¸ªà¸²à¸£à¸à¸²à¸¡,Phanom Sarakham", :latitude => "13.74787", :longitude => "101.3553").save
City.new(:country_id => "218", :name => "Phanat Nikhom", :aliases => "Amphoe Phanat Nikhom,Amphu Panas Nikom,Ban Phanat Nikhom,Bhanasnigom,Mueang Phanat Nikhom,Phanat Nikhom,Phanatikhom,à¸à¸à¸±à¸ªà¸à¸´à¸à¸¡,Phanat Nikhom", :latitude => "13.44581", :longitude => "101.18445").save
City.new(:country_id => "218", :name => "Phak Hai", :aliases => "Amphoe Phak Hai,Amphoe Sena Yai,Amphu Phak Hai,Ban Phakhai,Khwaeng Sena Yai,Phak Hai,à¸à¸±à¸à¹à¸«à¹,Phak Hai", :latitude => "14.45736", :longitude => "100.36989").save
City.new(:country_id => "218", :name => "Pattani", :aliases => "Changwat Pattani,Muang Patani,Muang Tara,Patani,Pattam,Pattani,PattÄm,ftany,pattani,ÐÐ°ÑÑÐ°Ð½Ð¸,ÙØ·Ø§ÙÙ,ããã¿ã¼ãã¼,Pattani", :latitude => "6.86814", :longitude => "101.25009").save
City.new(:country_id => "218", :name => "Pathum Thani", :aliases => "Amphoe Bang Kadi,Amphoe Muang Pathum Thani,Amphoe Pathum Thani,Ban Bang Kadi,Ban Patok,Bang Kadi,Changwat Pathum Thani,Muang Pradhum Dhani,Muang Prathum Tani,Muang Prathum Thani,Mueang Pathum Thani,Padumdhani,Pathum Rani,Pathum Thani,Pathumthani,Pradhum Dhani,Prathum Thani,Pthumthani,Ratkhum Tkhani,Ð Ð°ÑÑÑÐ¼ Ð¢ÑÐ°Ð½Ð¸,à¸à¸à¸¸à¸¡à¸à¸²à¸à¸µ,Pathum Thani", :latitude => "14.01346", :longitude => "100.53049").save
City.new(:country_id => "218", :name => "Pak Phanang", :aliases => "Amphoe Bia Sad,Amphoe Pak Phanang,Ban Pak Phanang,Ban Pakpenang,Pak Phanang,Pakpenang,PÄkpenang,à¸à¸²à¸à¸à¸à¸±à¸,Pak Phanang", :latitude => "8.35109", :longitude => "100.20195").save
City.new(:country_id => "218", :name => "Pak Kret", :aliases => "Amphoe Pak Kret,Ban Pak Kret,Pak Kred,Pak Kret,xaphex pakkerd,à¸à¸²à¸à¹à¸à¸£à¹à¸,à¸­à¸³à¹à¸ à¸­à¸à¸²à¸à¹à¸à¸£à¹à¸,Pak Kret", :latitude => "13.91301", :longitude => "100.49883").save
City.new(:country_id => "218", :name => "Pak Chong", :aliases => "Amphoe Pak Chong,Ban Pak Chong,Ban Par Chong,King Amphoe Pak Chong,Pak Chong,Tambon Pak Chong,à¸à¸²à¸à¸à¹à¸­à¸,Pak Chong", :latitude => "14.70802", :longitude => "101.41614").save
City.new(:country_id => "218", :name => "Mueang Nonthaburi", :aliases => "Amphoe Muang Nonthaburi,Changwat Nonthaburi,Muang Nondha Buri,Muang Nonta Buri,Muang Nontha Buri,Mueang Nonthaburi,Non Buri,Nondaburi,Nondha Buri,Nonthaburi,Nontkhaburi,ÐÐ¾Ð½ÑÑÐ°Ð±ÑÑÐ¸,à¹à¸¡à¸·à¸­à¸à¸à¸à¸à¸à¸¸à¸£à¸µ,Mueang Nonthaburi", :latitude => "13.86075", :longitude => "100.51477").save
City.new(:country_id => "218", :name => "Non Sung", :aliases => "Amphoe Non Sung,Amphoe Non Wat,Non Sung,à¹à¸à¸à¸ªà¸¹à¸,Non Sung", :latitude => "15.18014", :longitude => "102.25694").save
City.new(:country_id => "218", :name => "Nong Phai", :aliases => "Amphoe Nong Phai,Ban Nong Phai,King Amphoe Nong Phai,Nong Phai,Nong Phai", :latitude => "15.99025", :longitude => "101.06183").save
City.new(:country_id => "218", :name => "Nong Khai", :aliases => "Amphoe Muang Nong Khai,Ban Mi Chai,Changwat Nang Khai,Changwat Nong Khai,Hnohnggai,Michai,Muang Nawng Kai,Muang Nong Khay,Mueang Nong Khai,Naung Khai,Nawng Kai,Nong Hai,Nong Kai,Nong Khai,Nong-Kkhaj,nonkai,ÐÐ¾Ð½Ð³-ÐÑÐ°Ð¹,à¸à¸´à¹à¸à¸­à¸³à¹à¸ à¸­à¸ªà¸£à¸°à¹à¸à¸£,à¸«à¸à¸­à¸à¸à¸²à¸¢,ãã¼ã³ã«ã¼ã¤,Nong Khai", :latitude => "17.87847", :longitude => "102.742").save
City.new(:country_id => "218", :name => "Nong Khae", :aliases => "Amphoe Nong Khae,Ban Na Roeng,Hnohng Ga,HnÅhng GÄ,Na Roeng,Naung Khae,Nong Khae,à¸«à¸à¸­à¸à¹à¸,Nong Khae", :latitude => "14.34062", :longitude => "100.86733").save
City.new(:country_id => "218", :name => "Nong Bua Lamphu", :aliases => "Amphoe Nong Bua Lamphu,Ban Nong Bua,Changwat Nong Bua Lamphu,Kamouttasai,Kmuthasai,Muang Gamutra Sai,Muang Kamatdhasai,Muang Kamouttasai,Muang Kamuta Sai,Muang Kamutthasai,Muang Kmuthasai,Mueang Nong Bua Lamphu,Naung Bua,Nong Bua Lamphu,à¸«à¸à¸­à¸à¸à¸±à¸§à¸¥à¸³à¸ à¸¹,Nong Bua Lamphu", :latitude => "17.20406", :longitude => "102.44068").save
City.new(:country_id => "218", :name => "Narathiwat", :aliases => "Ban Bangnara,Bang Nara,Changwat Naradhiwas,Changwat Narathiwat,Naradhivas,Naradhiwas,Narathiwat,Narativas,Narativat,Naratkhivat,ÐÐ°ÑÐ°ÑÑÐ¸Ð²Ð°Ñ,à¸à¸£à¸²à¸à¸´à¸§à¸²à¸ª,Narathiwat", :latitude => "6.42639", :longitude => "101.82308").save
City.new(:country_id => "218", :name => "Nang Rong", :aliases => "Amphoe Nang Rong,Ban Nang Rong,Mong Nang Rawng,Mueang Nang Rong,Muong Nang Rong,MÃ¶ng Nang Rawng,Nang Raung,Nang Rong,à¸à¸²à¸à¸£à¸­à¸,Nang Rong", :latitude => "14.6377", :longitude => "102.79138").save
City.new(:country_id => "218", :name => "Nan", :aliases => "Amphoe Muang Nam,Amphoe Mueang Nam,Ban Muang Nan,Changwat Muang Nan,Changwat Nan,Changwat Nana,Muang Nan,Mueang Nan,Nagor Nan,Nan,ÐÐ°Ð½,à¸à¹à¸²à¸,Nan", :latitude => "18.79292", :longitude => "100.72972").save
City.new(:country_id => "218", :name => "Nam Som", :aliases => "Amphoe Nam Som,King Amphoe Nam Som,Nam Som,à¸à¹à¸³à¹à¸ªà¸¡,Nam Som", :latitude => "17.77036", :longitude => "102.18947").save
City.new(:country_id => "218", :name => "Nakhon Sawan", :aliases => "Amphoe Muang Nakhon Sawan,Changwat Muang Nakhon Sawan,Changwat Nakhon Sawan,Muang Nagorn Sawarn,Muang Nakawn Sawan,Muang Nakhon Savan,Muang Nakhon Sawan,Mueang Nakhon Sawan,Nagara Sawan,Nagor Svarga,Nagorn Sawarn,Nakaun Sawan,Nakawan Sawn,Nakawn Sawan,Nakhaun Sawan,Nakhon Sawan,Naklon Sawan,Nakon Sawan,Nakorn Sawan,à¸à¸à¸£à¸ªà¸§à¸£à¸£à¸à¹,Nakhon Sawan", :latitude => "15.70472", :longitude => "100.13717").save
City.new(:country_id => "218", :name => "Nakhon Ratchasima", :aliases => "Amphoe Muang Nakhon Ratchasima,Changwat Nakhon Rarchasima,Changwat Nakhon Rat Sima,Corat,Khorat,Korat,Koyat,Muang Nakawn Rachasima,Nagara Rajasima,Nagor Rajashima,Nagor Rajasima,Nakhaun Rachasima,Nakhon Ratchasima,Nakhon Ratchsima,Nakhon Ratczasima,Nakhonratsima,Nakkhonratchasima,Nakonrajsima,Nakonratchasima,Nakorn Rajsima,nakonrachashima,ÐÐ°ÐºÑÐ¾Ð½ÑÐ°ÑÑÐ°ÑÐ¸Ð¼Ð°,ãã³ã¼ã³ã©ã¼ãã£ã·ã¼ãã¼,Nakhon Ratchasima", :latitude => "14.97066", :longitude => "102.10196").save
City.new(:country_id => "218", :name => "Nakhon Phanom", :aliases => "Amphoe Muang Nakhon Phanom,Amphoe Nong Buek,Ban Nakhon Phnom,Changwat Muang Nakhon Phanom,Changwat Nakhon Phanom,Lakhon,Muang Nakhon Phanom,Mueang Nakhon Phanom,Nagorn Bhanom,Nakawn Panom,Nakhaun Phanom,Nakhon Phanom,Nakol Phanom,Nakon Panom,Nakorn Panom,Naung Bua,Nong Buk,à¸à¸à¸£à¸à¸à¸¡,Nakhon Phanom", :latitude => "17.41081", :longitude => "104.77856").save
City.new(:country_id => "218", :name => "Nakhon Pathom", :aliases => "Amphoe Muang Nakhon Pathom,Changwat Nakhon Chai Si,Changwat Nakhon Pathom,Monthon Nakhon Chai Si,Mueang Nakhon Pathom,Nagara Pathom,Nagorn Pathom,Nakawn Patom,Nakhaun Pathom,Nakhon Chai Si,Nakhon Pathom,Nakon Patom,nakonpatomu,à¸à¸à¸£à¸à¸à¸¡,ãã³ã¼ã³ããã ,Nakhon Pathom", :latitude => "13.8196", :longitude => "100.04427").save
City.new(:country_id => "218", :name => "Nakhon Nayok", :aliases => "Amphoe Muang Nakhon Nayok,Amphoe Nakhon Nayok,Changwat Nakhon Nayok,Muang Nagorn Nayok,Muang Nakawn Nayok,Muang Nakhon Nayok,Mueang Lablae,Mueang Nakhon Nayok,Nagorn Nayok,Nakaunnayok,Nakaunnoyok,Nakhaun Nayok,Nakhon Nauok,Nakhon Nayok,Nakon Nayok,Nayok,à¸à¸à¸£à¸à¸²à¸¢à¸,Nakhon Nayok", :latitude => "14.20463", :longitude => "101.21295").save
City.new(:country_id => "218", :name => "Nakhon Luang", :aliases => "Amphoe Nakhon Klang,Amphoe Nakhon Luang,Amphu Luang,Ban Nakhon Luang,Hluang,HlÅ«ang,Nakhon Luang,à¸à¸à¸£à¸«à¸¥à¸§à¸,Nakhon Luang", :latitude => "14.46281", :longitude => "100.60832").save
City.new(:country_id => "218", :name => "Mukdahan", :aliases => "Amphoe Mueang Mukdahan,Amphoe Mukdahan,Ban Mouk,Ban Si Mongkhon,Ban Srimongkhon,Makdaharn,Mokdaharn,Muang Ban Muk Dahan,Muang Muk Da Han,Mueang Mukdahan,Mueng Mukdahan,Muk,Mukdahan,Mukdaharn,Mukdakhan,Mukdatarn,Si Mongkhon,Srimongkhon,ÐÑÐºÐ´Ð°ÑÐ°Ð½,à¸¡à¸¸à¸à¸à¸²à¸«à¸²à¸£,Mukdahan", :latitude => "16.54531", :longitude => "104.72351").save
City.new(:country_id => "218", :name => "Maha Sarakham", :aliases => "Amphoe Muang Maha Sarakham,Ban Khlong Khleng,Ban Lat,Ban Talat,Changwat Maha Sarakham,Maha Saragam,Maha Sarakam,Maha Sarakham,Mueang Maha Sarakham,Talat,Uthai Sarakham,à¸¡à¸«à¸²à¸ªà¸²à¸£à¸à¸²à¸¡,Maha Sarakham", :latitude => "16.18483", :longitude => "103.30067").save
City.new(:country_id => "218", :name => "Lop Buri", :aliases => "Amphoe Muang Lop Buri,Ban Tha Hin,Changwat Lop Buri,Changwat Thahanbok Lop Buri,Lava Pura,Lavo,Lobh Buri,Lop Buri,Lopburi,Muang Lobh Buri,Muang Lopburi,Muang Xop Buri,Mueang Lop Buri,Tha Hin,robburi,ÐÐ¾Ð¿Ð±ÑÑÐ¸,à¸¥à¸à¸à¸¸à¸£à¸µ,ã­ãããªã¼,Lop Buri", :latitude => "14.79808", :longitude => "100.65397").save
City.new(:country_id => "218", :name => "Lom Sak", :aliases => "Amphoe Lom Sak,Amphoe Wat Pa,Ban Lom Sak,Changwat Muang Hlom Sak,Changwat Muang Lom Sak,Hlomsak,Lom Sak,Muang Hlom Sak,Muang Lom Sak,Wat Pa,à¸«à¸¥à¹à¸¡à¸ªà¸±à¸,Lom Sak", :latitude => "16.77983", :longitude => "101.24225").save
City.new(:country_id => "218", :name => "Loei", :aliases => "Amphoe Muang Loei,Changwat Loei,Changwat Muang Lai,Changwat Muang Loei,Leui,Loeh,Loei,Loey,Muang Lai,Muang Leoi,Muang Loei,Muang Loeui,Muang Loi,Mueang Loei,ÐÐ¾Ñ,à¹à¸¥à¸¢,Loei", :latitude => "17.49052", :longitude => "101.72749").save
City.new(:country_id => "218", :name => "Laem Sing", :aliases => "Amphoe Laem Sing,Amphoe Phlio,Laem Sing,Naiamphur,à¹à¸«à¸¥à¸¡à¸ªà¸´à¸à¸«à¹,Laem Sing", :latitude => "12.48164", :longitude => "102.07375").save
City.new(:country_id => "218", :name => "Kut Chap", :aliases => "Amphoe Kut Chap,Ban Kut Chap,King Amphoe Kut Chap,Kut Chap,à¸à¸¸à¸à¸à¸±à¸,Kut Chap", :latitude => "17.4257", :longitude => "102.56692").save
City.new(:country_id => "218", :name => "Kuchinarai", :aliases => "Amphoe Kuchinarai,Ban Bua Khao,Bua Khao,Kuchinarai,Kutsinnarai,à¸à¸¸à¸à¸´à¸à¸²à¸£à¸²à¸¢à¸à¹,à¸à¸¸à¸à¸ªà¸´à¸¡à¸à¸²à¸£à¸²à¸¢à¸à¹,Kuchinarai", :latitude => "16.541", :longitude => "104.05004").save
City.new(:country_id => "218", :name => "Bangkok", :aliases => "Amphoe Phra Nakhon,Bancac,BancÃ¡c,Bangkok,Bangkok - krungthephmhankhr,Bangkok - à¸à¸£à¸¸à¸à¹à¸à¸à¸¡à¸«à¸²à¸à¸à¸£,Bangkoka,Banguecoque,Bankok,Bankokas,Changwat Phra Nakhon,Krung Thep,Krung Thep Mahanakhon Amon Rattanakosin Mahinthara Ayuthaya Mahadilok Phop Noppharat Ratchathani Burirom Udomratchaniwet Mahasathan Amon Piman Awatan Sathit Sakkathattiya Witsanukam Prasit,Krungdeb,Phra Nakhon,Siayuthia,bainkoka,bangkog,bangkwk,bankoku,bankwk,bngqwq,byankaka,krungtheph,krungthephmhankhr,man gu,ÐÐ°Ð½Ð³ÐºÐ¾Ðº,ÐÐ°Ð½ÐºÐ¾Ðº,×× ××§××§,Ø¨Ø§ÙÙÙÙ,Ø¨Ø§ÙÚ©ÙÚ©,Ø¨Ø§ÙÚ¯ÙÙÙ,à¤¬à¥à¤à¤à¥à¤,à¦¬à§à¦¯à¦¾à¦à¦à¦,à¸à¸£à¸¸à¸à¹à¸à¸,à¸à¸£à¸¸à¸à¹à¸à¸à¸¡à¸«à¸²à¸à¸à¸£,à½à½à¼à½à½¼à½,áááááááá,á£áá®á­,ãã³ã³ã¯,æ¼è°·,ë°©ì½,Bangkok", :latitude => "13.75", :longitude => "100.51667").save
City.new(:country_id => "218", :name => "Krathum Baen", :aliases => "Amphor Kathum Baen,Ban Krathum Baen,Ban Talat Kathum Baen,Kathum Baen,Krathu Baen,Krathum Baen,Krathumban,Talat Kathum Baen,à¸à¸£à¸°à¸à¸¸à¹à¸¡à¹à¸à¸,Krathum Baen", :latitude => "13.6533", :longitude => "100.25972").save
City.new(:country_id => "218", :name => "Klaeng", :aliases => "Amphoe Klaeng,Ban Sam Yan,Ban Thang Kwian,Klaeng,Kleng,KlÄng,Mueang Klaeng,Thang Kwian,t.kÃ¦lng,à¸.à¹à¸à¸¥à¸,à¹à¸à¸¥à¸,Klaeng", :latitude => "12.7912", :longitude => "101.63433").save
City.new(:country_id => "218", :name => "Khon Kaen", :aliases => "Amphoe Muang Khon Kaen,Amphoe Phralap,Amphoe Pralap,Changwat Khon Kaen,Changwat Muang Khon Kaen,Kawn Ken,Khohn Ken,Khon Kaen,Khon Kan,Khon Khen,Khonkean,Khonkhaen,Kkhonkehn,Konkahen,Muang Kaun Gean,Muang Khaunkaen,Muang Khon Kaen,Mueang Khon Kaen,ÐÑÐ¾Ð½ÐºÑÐ½,à¹à¸¡à¸·à¸­à¸à¸à¸­à¸à¹à¸à¹à¸,Khon Kaen", :latitude => "16.44671", :longitude => "102.833").save
City.new(:country_id => "218", :name => "Khon Buri", :aliases => "Amphoe Khon Buri,Ban Khon Buri,Khon Buri,King Amphoe Chae,Mueang Khon,à¸à¸£à¸à¸¸à¸£à¸µ,Khon Buri", :latitude => "14.52541", :longitude => "102.24591").save
City.new(:country_id => "218", :name => "Khlong Luang", :aliases => "Amphoe Bang Wai,Amphoe Khlong Luang,Ban Bang Wai,Ban Khlong Song (3),Bang Wai,Khlong Luang,à¸à¸¥à¸­à¸à¸«à¸¥à¸§à¸,Khlong Luang", :latitude => "14.06467", :longitude => "100.64578").save
City.new(:country_id => "218", :name => "Khao Wong", :aliases => "Amphoe Khao Wong,Khao Wong,King Amphoe Khao Wong,à¹à¸à¸²à¸§à¸,Khao Wong", :latitude => "16.70008", :longitude => "104.0902").save
City.new(:country_id => "218", :name => "Kaset Wisai", :aliases => "Amphoe Kaset Wisai,Kaset Wisai,Nong Waeng,à¹à¸à¸©à¸à¸£à¸§à¸´à¸ªà¸±à¸¢,Kaset Wisai", :latitude => "15.65558", :longitude => "103.58361").save
City.new(:country_id => "218", :name => "Kaset Sombun", :aliases => "Amphoe Kaset Sombun,Ban Yang,Kaset Sombun,King Amphoe Kaset Sombun,à¹à¸à¸©à¸à¸£à¸ªà¸¡à¸à¸¹à¸£à¸à¹,Kaset Sombun", :latitude => "16.28053", :longitude => "101.95422").save
City.new(:country_id => "218", :name => "Kantharalak", :aliases => "Amphoe Kantharalak,Amphoe Nam Om,Ban Nam Om,Kanthanalak,Kantharalak,Kantkharalak,Muang Uthumpa,Muang Uthumpau,Mueang Uthumphon Phisai,Muong Utumpar,Nam Aum,ÐÐ°Ð½ÑÑÐ°ÑÐ°Ð»Ð°Ðº,à¸à¸±à¸à¸à¸£à¸¥à¸±à¸à¸©à¸à¹,Kantharalak", :latitude => "14.64056", :longitude => "104.64992").save
City.new(:country_id => "218", :name => "Kamalasai", :aliases => "Amphoe Kamalasai,Ban Amphoe Kamalasai,Ban Komlasai,Kamalasai,Komlasai,Kramalasai,à¸à¸¡à¸¥à¸²à¹à¸ªà¸¢,à¸à¸£à¸°à¸¡à¸²à¸¥à¸²à¹à¸ªà¸¢,Kamalasai", :latitude => "16.33839", :longitude => "103.57564").save
City.new(:country_id => "218", :name => "Kalasin", :aliases => "Amphoe Hlup,Amphoe Kalasin,Amphoe Lup,Amphoe Muang Kalasin,Ban Neur,Changwat Kalasin,Changwat Muang Kalasin,Kalasim,Kalasin,Kalasindhu,Lup,Muang Kalasim,Muang Kalasin,Muang Kalassim,Muang Kansin,Mueang Kalasin,ÐÐ°Ð»Ð°ÑÐ¸Ð½,à¸à¸²à¸¬à¸ªà¸´à¸à¸à¸¸à¹,Kalasin", :latitude => "16.43281", :longitude => "103.50658").save
City.new(:country_id => "218", :name => "Kaeng Khoi", :aliases => "Amphoe Kaeng Khoi,Kaeng Khoi,Khwaeng Kaeng Khoi,à¹à¸à¹à¸à¸à¸­à¸¢,Kaeng Khoi", :latitude => "14.58617", :longitude => "100.99758").save
City.new(:country_id => "218", :name => "Kaeng Khro", :aliases => "Amphoe Kaeng Khlo,Amphoe Kaeng Khro,Kaeng Khlo,Kaeng Khro,à¹à¸à¹à¸à¸à¸£à¹à¸­,Kaeng Khro", :latitude => "16.10864", :longitude => "102.25808").save
City.new(:country_id => "218", :name => "Kabin Buri", :aliases => "Amphoe Kabin Buri,Ban Kabin Buri,Kabin Buri,Mong Krabin,Mueang Kabin Buri,à¸à¸à¸´à¸à¸à¸£à¹à¸à¸¸à¸£à¸µ,Kabin Buri", :latitude => "13.95114", :longitude => "101.71769").save
City.new(:country_id => "218", :name => "Hat Yai", :aliases => "Amphoe Hat Yai,Ban Haad Yai,Ban Hat Yai,Haad Yai,Had Yai,Hat Yai,hatoyai jun,he ai,à¸«à¸²à¸à¹à¸«à¸à¹,ãã¼ãã¤ã¤é¡,åè¾,Hat Yai", :latitude => "7.00836", :longitude => "100.47668").save
City.new(:country_id => "218", :name => "Det Udom", :aliases => "Amphoe Det Udom,Amphoe Det Udon,Ban Muang Det,Ban Muang Detudom,Det,Det Udom,Det Udon,Muang Det,Mueang Det Udom,à¹à¸à¸à¸­à¸¸à¸à¸¡,Det Udom", :latitude => "14.90598", :longitude => "105.07836").save
City.new(:country_id => "218", :name => "Den Chai", :aliases => "Amphoe Den Chai,Ban Den Chai,Den Chai,à¹à¸à¹à¸à¸à¸±à¸¢,Den Chai", :latitude => "17.98372", :longitude => "100.05217").save
City.new(:country_id => "218", :name => "Dan Khun Thot", :aliases => "Amphoe Ban Han,Amphoe Dan Khun Thot,Amphoe Phan Chana,Dan Khun Thot,à¸à¹à¸²à¸à¸à¸¸à¸à¸à¸,Dan Khun Thot", :latitude => "15.2085", :longitude => "101.77138").save
City.new(:country_id => "218", :name => "Chum Phae", :aliases => "Amphoe Chum Phae,Ban Chum Phae,Chum Phae,à¸à¸¸à¸¡à¹à¸,Chum Phae", :latitude => "16.5443", :longitude => "102.09924").save
City.new(:country_id => "218", :name => "Chon Daen", :aliases => "Amphoe Chon Daen,Ban Chon Daen,Ban Chon Dean,BÄn Chon Dean,Chon Daen,Jonden,JondÄn,King Amphoe Chon Daen,King Chon Daen,à¸à¸à¹à¸à¸,Chon Daen", :latitude => "16.18953", :longitude => "100.85958").save
City.new(:country_id => "218", :name => "Chon Buri", :aliases => "Amphoe Muang Chon Buri,Baanburaisoi,Ban Bang Pla Soi,Ban Pla Sai,Ban Pla Soi,Bang Pla Soi,Bang Pla Soil,Changwat Chon Buri,Cholburi,Chon Buri,Chonburi,Chor Buri,Jilburi,JÄ«lburi,Muang Jol Buri,Muang Xonburi,Mueang Chon Buri,Ð§Ð¾Ð½Ð±ÑÑÐ¸,à¸à¸¥à¸à¸¸à¸£à¸µ,Chon Buri", :latitude => "13.3622", :longitude => "100.98345").save
City.new(:country_id => "218", :name => "Chok Chai", :aliases => "Amphoe Chok Chai,Ban Chok Chai,Choc Chai,Chok Chai,Kra Thok,à¹à¸à¸à¸à¸±à¸¢,Chok Chai", :latitude => "14.72844", :longitude => "102.16524").save
City.new(:country_id => "218", :name => "Chanthaburi", :aliases => "Amphoe Muang Chanthaburi,Chandaburi,Chandha Buri,Changwat Chanthaburi,Chantaboun,Chantabun,Chantaburi,Chanthaburi,Chantkhaburi,Chentabun,Chiyandburii,Mueang Chanthaburi,Ð§Ð°Ð½ÑÑÐ°Ð±ÑÑÐ¸,à¸à¸±à¸à¸à¸à¸¸à¸£à¸µ,Chanthaburi", :latitude => "12.60961", :longitude => "102.10447").save
City.new(:country_id => "218", :name => "Chaiyaphum", :aliases => "Amphoe Muang Chaiyaphum,Ban Hin Tang,Chai Phum,Chaiaphum,Chaiapum,Chaiyaphum,Chaiyaphun,Chaiyapoom,Chajjapkhum,Chalyaphum,Changwat Chaiyaphum,Changwat Chaiyaphun,Jaibhum,Jaiyabhum,Jayabhumi,Muang Chaiyapum,Muang Jaiyabhum,Tchaiapoum,Ð§Ð°Ð¹ÑÐ¿ÑÑÐ¼,à¸à¸±à¸¢à¸ à¸¹à¸¡à¸´,Chaiyaphum", :latitude => "15.81047", :longitude => "102.02881").save
City.new(:country_id => "218", :name => "Chai Nat", :aliases => "Amphoe Ban Kluai,Amphoe Muang Chainat,Ban Kluai,Chai Nad,Chai Nat,Chainat,Changwat Chainat,Changwat Muang Chainat,Cheinat,Jai-Nadh,Jai-NÄdh,Jainat,Muang Chainat,Muang Jai Nadh,Muang Xai Nat,Mueang Chai Nat,à¸à¸±à¸¢à¸à¸²à¸,Chai Nat", :latitude => "15.18636", :longitude => "100.12353").save
City.new(:country_id => "218", :name => "Chai Badan", :aliases => ",Chai Badan", :latitude => "15.2", :longitude => "101.13333").save
City.new(:country_id => "218", :name => "Chachoengsao", :aliases => "Amphoe Muang Chachoengsao,Chacherngsao,Chachoengsao,Chachurngsao,Changwat Chachoengsao,Chaxerngsao,Chaxoengsao,Muang Chachurngsao,Muang Shajeungdhrao,Muang Shajeungtrao,Mueang Chachoengsao,Muong Chaxungsao,Paet Riu,Petrin,Petriou,Petriu,Shacheungzao,Shajeungdhrao,Shajeungdrao,Shajeungzao,Ð§Ð°ÑÐ¾ÐµÐ½Ð³ÑÐ°Ð¾,à¹à¸¡à¸·à¸­à¸à¸à¸°à¹à¸à¸´à¸à¹à¸à¸£à¸²,Chachoengsao", :latitude => "13.6882", :longitude => "101.07156").save
City.new(:country_id => "218", :name => "Bua Yai", :aliases => "Amphoe Bua Yai,Bua Yai,Dan Nok,à¸à¸±à¸§à¹à¸«à¸à¹,Bua Yai", :latitude => "15.58552", :longitude => "102.42587").save
City.new(:country_id => "218", :name => "Betong", :aliases => "Amphoe Betong,Amphoe Yarom,Ban Betong,Betong,Kampong Betong,ÐÐµÑÐ¾Ð½Ð³,à¸­à¸³à¹à¸ à¸­à¹à¸à¸à¸,à¹à¸à¸à¸,Betong", :latitude => "5.77434", :longitude => "101.07231").save
City.new(:country_id => "218", :name => "Ban Selaphum", :aliases => ",Ban Selaphum", :latitude => "16.01667", :longitude => "103.95").save
City.new(:country_id => "218", :name => "Ban Rangsit", :aliases => "Ban Rangsit,Dhanya Buri,Mong Tania Buri,MÃ¶ng Tania Buri,Rangsit,Thanyaburi,Ban Rangsit", :latitude => "14.01667", :longitude => "100.73333").save
City.new(:country_id => "218", :name => "Phattaya", :aliases => "Ban Hat Phatthaya (2),Ban Phatthaya,Pataja,Pattajja,Pattaya,Phattaya,Port Phattaya,ba da ya,pattaya te bie shi,phathya,ÐÐ°ÑÐ°Ñ,ÐÐ°ÑÑÐ°Ð¹Ñ,à¸à¸±à¸à¸¢à¸²,ããã¿ã¤ã¼ç¹å¥å¸,è­éäº,Phattaya", :latitude => "12.93333", :longitude => "100.88333").save
City.new(:country_id => "218", :name => "Ban Phan Don", :aliases => "Amphoe Kumbhawapi,Amphoe Kumphawapi,Ban Nam Khong,Ban Phan Don,Koumpa Ouapi,Kumpawapi,Kumphawapi,Muang Kumpawapi,Muang Kumpu Kwapi,Nam Khaung,Ban Phan Don", :latitude => "17.13361", :longitude => "102.9675").save
City.new(:country_id => "218", :name => "Ban Phai", :aliases => "Amphoe Ban Phai,Ban Keng,Ban Phai,King Amphoe Ban Phai,à¸à¹à¸²à¸à¹à¸à¹,Ban Phai", :latitude => "16.05997", :longitude => "102.73097").save
City.new(:country_id => "218", :name => "Ban Phaeo", :aliases => "Amphoe Ban Phaeo,Ban Phaeo,Ban Pheo,à¸à¹à¸²à¸à¹à¸à¹à¸§,Ban Phaeo", :latitude => "13.59072", :longitude => "100.10748").save
City.new(:country_id => "218", :name => "Ban Mo", :aliases => "Amphoe Ban Mo,Ban Mo,à¸à¹à¸²à¸à¸«à¸¡à¸­,Ban Mo", :latitude => "14.61544", :longitude => "100.72731").save
City.new(:country_id => "218", :name => "Ban Lam Luk Ka", :aliases => "Lam Luk Ka,Luk Ka,LÅ«k Ka,Ban Lam Luk Ka", :latitude => "13.97738", :longitude => "100.77776").save
City.new(:country_id => "218", :name => "Bang Rakam", :aliases => "Amphoe Bang Rakam,Amphoe Chum Saeng,Amphu Bang Raka,Ban Bang Ragam,Ban Bang Rakam,Bang Rakam,BÄn BÄng Ragam,Chum Saeng,Rakam,à¸à¸²à¸à¸£à¸°à¸à¸³,Bang Rakam", :latitude => "16.75847", :longitude => "100.11742").save
City.new(:country_id => "218", :name => "Bang Racham", :aliases => "Amphoe Bang Rachan,Amphoe Sing,Ban Sing,Ban Wang Wua,Bang Racham,Mueang Sing,à¸à¸²à¸à¸£à¸°à¸à¸±à¸,Bang Racham", :latitude => "14.892", :longitude => "100.31728").save
City.new(:country_id => "218", :name => "Bang Pakong", :aliases => "Amphoe Bang Pakong,Ban Tha Saan,Bang Pakong,Tha Sa-an,à¸à¸²à¸à¸à¸°à¸à¸,Bang Pakong", :latitude => "13.54297", :longitude => "100.99333").save
City.new(:country_id => "218", :name => "Bang Pa-in", :aliases => "Amphoe Bang Pa-In,Amphoe Phra Ratchawang,Ban Ko Bang Pa-in,Ban Len,Bang Pa-in,Khwaeng U Thai,à¸à¸²à¸à¸à¸°à¸­à¸´à¸,Bang Pa-in", :latitude => "14.22728", :longitude => "100.57879").save
City.new(:country_id => "218", :name => "Bang Mun Nak", :aliases => "Amphoe Bang Mun Nak,Amphoe Mueang Phum,Ban Bang Mun Nak,Ban Mun Nak,Bang Mun Nak,à¸à¸²à¸à¸¡à¸¹à¸¥à¸à¸²à¸,Bang Mun Nak", :latitude => "16.02781", :longitude => "100.37917").save
City.new(:country_id => "218", :name => "Bang Len", :aliases => "Amphoe Bang Len,Amphoe Bang Phai Nat,Amphoe Bang Pla,Ban Bang Len,Bang Len,à¸à¸²à¸à¹à¸¥à¸,Bang Len", :latitude => "14.02188", :longitude => "100.17183").save
City.new(:country_id => "218", :name => "Bang Lamung", :aliases => "Amphoe Ban Lamung,Amphoe Bang Lamung,Amphoe Naklua,Ban Na Kloea,Ban Na-Glua,Ban Naklua,Bang La-muang,Bang Lamung,Na Klua,à¸à¸²à¸à¸¥à¸°à¸¡à¸¸à¸,Bang Lamung", :latitude => "13.04704", :longitude => "100.92891").save
City.new(:country_id => "218", :name => "Bang Kruai", :aliases => "Amphoe Bang Kruai,Amphoe Bang Yai,Ban Bang Yai,Bang Krai,Bang Kruai,Bang Yai,à¸à¸²à¸à¸à¸£à¸§à¸¢,Bang Kruai", :latitude => "13.805", :longitude => "100.47283").save
City.new(:country_id => "218", :name => "Bang Krathum", :aliases => "Amphoe Bang Krathum,Ban Bang Gathum,Ban Bang Krahtum,Bang Kathum,Bang Krathem,Bang Krathum,BÄn Bang Gathum,Kathum,King Amphoe Bang Krathum,King Bang Kathum,à¸à¸²à¸à¸à¸£à¸°à¸à¸¸à¹à¸¡,Bang Krathum", :latitude => "16.57831", :longitude => "100.30034").save
City.new(:country_id => "218", :name => "Bang Bua Thong", :aliases => "Amphoe Bang Bua Thong,Bang Bua Thong,à¸à¸²à¸à¸à¸±à¸§à¸à¸­à¸,Bang Bua Thong", :latitude => "13.91783", :longitude => "100.42403").save
City.new(:country_id => "218", :name => "Bang Ban", :aliases => "Amphoe Bang Ban,Amphoe Sena Nai,Ban Bang Bal,Ban Bang Ban,Bang Bal,Bang Ban,BÄng BÄl,à¸à¸²à¸à¸à¸²à¸¥,Bang Ban", :latitude => "14.37394", :longitude => "100.48528").save
City.new(:country_id => "218", :name => "Ban Dung", :aliases => "Amphoe Ban Dung,Ban Dung,King Amphoe Ban Dung,à¸à¹à¸²à¸à¸à¸¸à¸,Ban Dung", :latitude => "17.699", :longitude => "103.25957").save
City.new(:country_id => "218", :name => "Ban Chang", :aliases => "Amphoe Ban Chang,Ban Chang,King Amphoe Ban Chang,à¸à¹à¸²à¸à¸à¸²à¸,Ban Chang", :latitude => "12.72543", :longitude => "101.0553").save
City.new(:country_id => "218", :name => "Ban Talat Bueng", :aliases => "Ban Boeng,Ban Bung,Ban Talat Bueng,Boeng,à¸à¹à¸²à¸à¸à¸¥à¸²à¸à¸à¸¶à¸,Ban Talat Bueng", :latitude => "13.07147", :longitude => "101.00314").save
City.new(:country_id => "218", :name => "Ban Bang Kadi Pathum Thani", :aliases => ",Ban Bang Kadi Pathum Thani", :latitude => "13.99904", :longitude => "100.54962").save
City.new(:country_id => "218", :name => "Ban Bang Bo (1)", :aliases => "Bang Bo,Ban Bang Bo (1)", :latitude => "13.58333", :longitude => "100.81667").save
City.new(:country_id => "218", :name => "Aranyaprathet", :aliases => "Amphoe Aranpradbet,Amphoe Aranya Prathet,Amphoe Aranyaprathet,Amphoe Ban Aranyaprathet,Aran Pradhesa,Aran Pradhet,Aran Prathet,Aran'japratkhet,Aranh,Aranya Pradesa,Aranya Pradhesa,Aranyaprathet,Ban Aran,Ban Aranyaprathet,Muang Aran Pradhet,Muang Aran Pratet,Muang Aranyapraphet,aran'yapurateto jun,xaphex xray pra ths,xaphex xrayprathes,ÐÑÐ°Ð½ÑÑÐ¿ÑÐ°ÑÑÐµÑ,à¸­à¸£à¸±à¸à¸à¸£à¸°à¹à¸à¸¨,à¸­à¸³à¹à¸ à¸­à¸­à¸£à¸±à¸à¸à¸£à¸°à¸à¸¨,à¸­à¸³à¹à¸ à¸­à¸­à¸£à¸±à¸à¸à¸£à¸°à¹à¸à¸¨,ã¢ã©ã³ã¤ãã©ãã¼ãé¡,Aranyaprathet", :latitude => "13.69276", :longitude => "102.50128").save
City.new(:country_id => "218", :name => "Amnat Charoen", :aliases => "Amanat Charoem,Amnat Charoen,Amphoe Amnat Charoen,Amphoe Bung,Ban Bung,Mueang Amnat Charoen,ÐÐ¼Ð½Ð°Ñ Ð§Ð°ÑÐ¾ÐµÐ½,à¸­à¸³à¸à¸²à¸à¹à¸à¸£à¸´à¸,Amnat Charoen", :latitude => "15.85833", :longitude => "104.6292").save
City.new(:country_id => "218", :name => "Amphoe Sikhiu", :aliases => ",Amphoe Sikhiu", :latitude => "14.89944", :longitude => "101.70833").save
City.new(:country_id => "218", :name => "Wichit", :aliases => ",Wichit", :latitude => "7.8894", :longitude => "98.38523").save
City.new(:country_id => "218", :name => "Ban Chalong", :aliases => "ban chlxng,à¸à¹à¸²à¸à¸à¸¥à¸­à¸,Ban Chalong", :latitude => "7.84468", :longitude => "98.33897").save
City.new(:country_id => "218", :name => "Ban Ratsada", :aliases => "Ratsada,Ð Ð°ÑÑÐ°Ð´Ð°,à¸à¹à¸²à¸à¸£à¸±à¸©à¸à¸²,Ban Ratsada", :latitude => "7.90963", :longitude => "98.40248").save
