City.new(:country_id => "222", :name => "Balkanabat", :aliases => "Balkanabat,Nebit-Dag,Nebitdag,Neftedag,ÐÐ°Ð»ÐºÐ°Ð½Ð°Ð±Ð°Ñ,ÐÐµÐ±Ð¸Ñ-ÐÐ°Ð³,Balkanabat", :latitude => "39.51194", :longitude => "54.365").save
City.new(:country_id => "222", :name => "Kaka", :aliases => "Kaakhka,Kaka,ÐÐ°ÐºÐ°,Kaka", :latitude => "37.35", :longitude => "59.6").save
City.new(:country_id => "222", :name => "Gumdag", :aliases => "Gumdag,Gumdage,Khudaidag,Khuday-Dag,Kum-Dag,ÐÑÐ¼Ð´Ð°Ð³Ðµ,Gumdag", :latitude => "39.20611", :longitude => "54.59056").save
City.new(:country_id => "222", :name => "Gazanjyk", :aliases => "Gazandzhyk,Gazanjyk,Kasandshik,Kazandzhik,Kazanjik,ÐÐ°Ð·Ð°Ð½Ð´Ð¶ÑÐº,Gazanjyk", :latitude => "39.24306", :longitude => "55.51694").save
City.new(:country_id => "222", :name => "Buzmeyin", :aliases => "Bezmein,Buzmeyin,BÃ¼zmeÃ½in,BÃ¼zmeÃ½in", :latitude => "38.05167", :longitude => "58.21").save
City.new(:country_id => "222", :name => "Baherden", :aliases => "Baherden,Bakharden,BÃ¤herden,BÃ¤herden", :latitude => "38.43028", :longitude => "57.43694").save
City.new(:country_id => "222", :name => "Ashgabat", :aliases => "Achgabat,Achkhabad - Asgabat,Achkhabad - AÅgabat,Aschabad,Aschabadas,Asgabat,Asgabato,Ashgabat,Ashkabad,Ashkhabad,Ashkhobad,Ashqabad,Asjchabad,Asjkhabad,Askabad,Askhabad,Asnkampat,Asqabad,Aszchabad,AÅgabato,AÅgabat,AÅqabad,AÅ¡chabad,AÅ¡chabadas,AÅ¡gabat,Poltoratsk,a shen ha ba de,ashigabato,ashkhabadi,asigabateu,ÎÏÎ³ÎºÎ±Î¼ÏÎ¬Ï,ÐÑÐ³Ð°Ð±Ð°Ñ,ÐÑÑÐ°Ð±Ð°Ð´,ÐÑÑÐ¾Ð±Ð°Ð´,××©××××,Ø¹Ø´ÙâØ¢Ø¨Ø§Ø¯,áá¨á®ááááá,á á½áá£áµ,âé¿ä»åå·´å¾·,ã¢ã·ã¬ãã¼ã,é¿ä»åå·´å¾·,ììê°ë°í¸,Ashgabat", :latitude => "37.95", :longitude => "58.38333").save
City.new(:country_id => "222", :name => "Annau", :aliases => "Anau,Anew,Annau,Enev,Ãnew,Annau", :latitude => "37.88833", :longitude => "58.52806").save
City.new(:country_id => "222", :name => "Tagta", :aliases => "Tagta,Takhta,Tagta", :latitude => "41.65", :longitude => "59.9").save
City.new(:country_id => "222", :name => "Turkmenbasy", :aliases => "KRASNOVODSK,Krasnovodsk,Krasnowodsk,Krassnowodsk,Tuerkmenbasy,Turkmenbashi,Turkmenbashy,Turkmenbasi,Turkmenbasy,Turkmenbaszy,TÃ¼rkmenbashy,TÃ¼rkmenbaÅy,TÃ¼rkmenbaÅÄ±,ÐÐ ÐÐ¡ÐÐÐÐÐÐ¡Ð,ÐÑÐ°ÑÐ½Ð¾Ð²Ð¾Ð´ÑÐº,Ð¢ÑÑÐºÐ¼ÐµÐ½Ð±Ð°ÑÑ,TÃ¼rkmenbaÅy", :latitude => "40.02306", :longitude => "52.96972").save
City.new(:country_id => "222", :name => "Koeneuergench", :aliases => "Gadymy UErgenc,Gadymy ÃrgenÃ§,Koeneuergenc,Koneurgench,Kounya-Ourguentch,Kunja-Urgench,Kunja-Urgentj,Kunya Urgench,Kunya-Urgen,Kunya-Urgench,KÃ¶neÃ¼rgench,KÃ¶neÃ¼rgenÃ§,grganj,kone-uleugenchi,ÐÑÐ½Ñ-Ð£ÑÐ³ÐµÐ½Ñ,Ú¯Ø±Ú¯Ø§ÙØ¬,ì½ë¤ì°ë¥´ê²ì¹,KÃ¶neÃ¼rgench", :latitude => "42.31667", :longitude => "59.16667").save
City.new(:country_id => "222", :name => "Boldumsaz", :aliases => "Boldumsaz,Kalinin,Kalininsk,Porsu,Porsy,ÐÐ¾Ð»Ð´ÑÐ¼ÑÐ°Ð·,Boldumsaz", :latitude => "42.13333", :longitude => "59.66667").save
City.new(:country_id => "222", :name => "Dasoguz", :aliases => "Dashhowuz,Dashkhovuz,Dashoguz,Dashowuz,Dasoguz,DaÅoguz,DaÅoÄuz,DaÅ¡howuz,Tashauz,Taszauz,ÐÐ°ÑÐ¾Ð³ÑÐ·,DaÅoguz", :latitude => "41.83333", :longitude => "59.96667").save
City.new(:country_id => "222", :name => "Yoloten", :aliases => "Iolotan',Iolotanâ,Yolotan,Yoloten,YolÃ¶ten,ÐÐ¾Ð»Ð¾ÑÐ°Ð½Ñ,YolÃ¶ten", :latitude => "37.3", :longitude => "62.35").save
City.new(:country_id => "222", :name => "Tejen", :aliases => "Tedjen,Tedzen,Tedzhen,TedÅ¼en,Tejen,Tejend,Ð¢ÐµÐ´Ð¶ÐµÐ½,Tejen", :latitude => "37.37861", :longitude => "60.49611").save
City.new(:country_id => "222", :name => "Seydi", :aliases => "Neftezavodsk,Sejdi,Seydi,Ð¡ÐµÐ¹Ð´Ð¸,Seydi", :latitude => "39.41667", :longitude => "62.9").save
City.new(:country_id => "222", :name => "Sayat", :aliases => ",SaÃ½at", :latitude => "38.78111", :longitude => "63.88667").save
City.new(:country_id => "222", :name => "Mary", :aliases => "Mary,Merv,ÐÐ°ÑÑ,Mary", :latitude => "37.6", :longitude => "61.83333").save
City.new(:country_id => "222", :name => "Atamyrat", :aliases => "Atamyrat,Kerki,Qarki,QÄrki,ÐÑÐ°Ð¼ÑÑÐ°Ñ,Atamyrat", :latitude => "37.83444", :longitude => "65.20972").save
City.new(:country_id => "222", :name => "Gowurdak", :aliases => "Gaurdak,Gaurdakstroy,Gaurdstroi,Gaurdstroy,Gowurdak,Gowurdak", :latitude => "37.80694", :longitude => "66.05667").save
City.new(:country_id => "222", :name => "Turkmenabat", :aliases => "Chardzha,Chardzhou,Chardzhui,Chardzhuy,Charjew,Charjou,ChÃ¤rjew,Leninsk-Turkmenski,Leninsk-Turmenski,Nov Charjui,Nov ChÄrjui,Novo Chardzhou,Novo-Chardzhuy,Tuerkmenabat,Turkmenabad,Turkmenabat,TÃ¼rkmenabat,te~yurukumenabato,tuleukeumenabateu,turkmenabat,Ð¢ÑÑÐºÐ¼ÐµÐ½Ð°Ð±Ð°Ñ,Ð§Ð°ÑÐ´Ð¶Ð¾Ñ,ãã¥ã«ã¯ã¡ããã¼ã,í¬ë¥´í¬ë©ëë°í¸,TÃ¼rkmenabat", :latitude => "39.10139", :longitude => "63.575").save
City.new(:country_id => "222", :name => "Bayramaly", :aliases => "Bairam Ali,Bajramalijskogo,Bayram-Ali,Bayramaly,ÐÐ°Ð¹ÑÐ°Ð¼Ð°Ð»Ð¸Ð¹ÑÐºÐ¾Ð³Ð¾,Bayramaly", :latitude => "37.61667", :longitude => "62.16667").save
City.new(:country_id => "222", :name => "Gazojak", :aliases => "Gaz-Achak,Gazojak,Gazojak", :latitude => "41.18333", :longitude => "61.4").save
