City.new(:country_id => "223", :name => "Zaghouan", :aliases => "Zaghouan,Zaghouane,Zaghwan,ZaghwÄn,Zarhouan,Zaghouan", :latitude => "36.40291", :longitude => "10.14292").save
City.new(:country_id => "223", :name => "Oued Lill", :aliases => "Oued Ellil,Oued Lill,Wadi al Layl,WÄdÄ« al Layl,Oued Lill", :latitude => "36.83408", :longitude => "10.04057").save
City.new(:country_id => "223", :name => "Tunis", :aliases => "Tunes,Tunez,Tunis,Tunis-Ville,Tunisas,Tunisi,Tunisz,Tunizo,Tynida,TÃºnez,TÃºnis,chunisu,tu ni si,tu ni si shi,twiniseu,twns,twnys,tyunisa,Î¤ÏÎ½Î¹Î´Î±,Ð¢ÑÐ½Ð¸Ñ,×ª×× ××¡,ØªÙÙØ³,à¤à¥à¤¯à¥à¤¨à¤¿à¤¸,á±ááµ,ãã¥ãã¹,çªå°¼æ¯,çªå°¼æ¯å¸,íëì¤,Tunis", :latitude => "36.81897", :longitude => "10.16579").save
City.new(:country_id => "223", :name => "Tozeur", :aliases => "Tawzar,Tozer,Tozeur,Ð¢Ð¾Ð·ÐµÑ,Tozeur", :latitude => "33.91968", :longitude => "8.13352").save
City.new(:country_id => "223", :name => "Tataouine", :aliases => "Foum Tatahouine,Foum Tataouine,Fum Tatawin,Fum TaÅ£ÄwÄ«n,Fumm Tattauin,Tatahouine,TatahouÃ¯ne,Tataouine,Tatawin,TaÅ£ÄwÄ«n,Tataouine", :latitude => "32.92967", :longitude => "10.45177").save
City.new(:country_id => "223", :name => "Thala", :aliases => "Tala,Talah,Thala,TÄlah,Thala", :latitude => "35.57244", :longitude => "8.67031").save
City.new(:country_id => "223", :name => "Taklisah", :aliases => "Takelsa,Taklisah,TÄklisah,TÄklisah", :latitude => "36.78333", :longitude => "10.63333").save
City.new(:country_id => "223", :name => "Tajerouine", :aliases => "Tadjerouine,Tadjrouine,TadjrouÃ¯ne,Tajerouine,Tajerouine", :latitude => "35.89174", :longitude => "8.55276").save
City.new(:country_id => "223", :name => "Sousse", :aliases => "Hadrumetum,Sousa,Souse,Soussa,Sousse,Susa,Susah,Suss,SÅ«sah,qyrnh,susu,swst,xi lan ni,Ð¡ÑÑÑ,×§××¨× ×,Ø³ÙØ³Ø©,ã¹ã¼ã¹,æå°å°¼,Sousse", :latitude => "35.82539", :longitude => "10.63699").save
City.new(:country_id => "223", :name => "Siliana", :aliases => "Siliana,Silyanah,SilyÄnah,Souk el Kremis,Ð¡Ð¸Ð»Ð¸Ð°Ð½Ð°,Siliana", :latitude => "36.08497", :longitude => "9.37082").save
City.new(:country_id => "223", :name => "Sidi Bouzid", :aliases => "Gammouda,Qamudah,QamÅ«dah,Sidi Bou Zid,Sidi Bouzid,Sidi Bu Zayd,Sidi-Bu-Zid,SÄ«dÄ« BÅ« Zayd,Ð¡Ð¸Ð´Ð¸-ÐÑ-ÐÐ¸Ð´,Sidi Bouzid", :latitude => "35.03823", :longitude => "9.48494").save
City.new(:country_id => "223", :name => "Saqanis", :aliases => "Chekanes,Saqanis,Skanes,ÅaqÄnis,ÅaqÄnis", :latitude => "35.78333", :longitude => "10.8").save
City.new(:country_id => "223", :name => "Sfax", :aliases => "Safakis,Safaqis,Sfax,Sfvks,Taparura,sfaqs,spqs,sufakkusu,ÅafÄqis,Ð¡ÑÐ²ÐºÑ,×¡×¤×§×¡,ØµÙØ§ÙØ³,ã¹ãã¡ãã¯ã¹,Sfax", :latitude => "34.74056", :longitude => "10.76028").save
City.new(:country_id => "223", :name => "La Sebala du Mornag", :aliases => "Cebala-du-Mornag,La Cebala,La Cebala du Mornag,La Sebala du Mornag,Sabalat Murnaq,SabÄlat MurnÄq,La Sebala du Mornag", :latitude => "36.67931", :longitude => "10.29195").save
City.new(:country_id => "223", :name => "Rades", :aliases => "Maxula,Maxula-Rades,Maxula-RadÃ¨s,Rades,Radis,RadÃ¨s,RÄdis,RadÃ¨s", :latitude => "36.76806", :longitude => "10.27528").save
City.new(:country_id => "223", :name => "Ksour Essaf", :aliases => "Ksour Essaf,Ksursef,Qsour Essaf,Qusur as Saf,QuÅÅ«r as SÄf,Ksour Essaf", :latitude => "35.41808", :longitude => "10.99475").save
City.new(:country_id => "223", :name => "Korba", :aliases => "Korba,Kourba,Kurba,Qurbah,ÐÐ¾ÑÐ±Ð°,Korba", :latitude => "36.57861", :longitude => "10.85861").save
City.new(:country_id => "223", :name => "Qulaybiyah", :aliases => "Clupea,Kelibia,Kelibija,KÃ©libia,Qulaybiyah,QulaybÄ«yah,ÐÐµÐ»Ð¸Ð±Ð¸Ñ,QulaybÄ«yah", :latitude => "36.84757", :longitude => "11.09386").save
City.new(:country_id => "223", :name => "Kebili", :aliases => "Kebili,Qibili,QibilÄ«,Kebili", :latitude => "33.70439", :longitude => "8.96903").save
City.new(:country_id => "223", :name => "Qasr Hallal", :aliases => "Kassar el Hal,Kesser el Hal,Ksar Hellal,Qasr Hallal,QaÅr HallÄl,QaÅr HallÄl", :latitude => "35.64773", :longitude => "10.89046").save
City.new(:country_id => "223", :name => "Carthage", :aliases => "Karfagen,Qartajannah,QarÅ£Äjannah,ÐÐ°ÑÑÐ°Ð³ÐµÐ½,Carthage", :latitude => "36.86108", :longitude => "10.33161").save
City.new(:country_id => "223", :name => "El Fahs", :aliases => "Al Fahs,Al Faá¸©Å,El Fahs,Fahs,Pont du Fas,Pont-du-Fahs,Port-du-Fachs,Qantarat al Fahs,QanÅ£arat al Faá¸©Å,El Fahs", :latitude => "36.37419", :longitude => "9.90651").save
City.new(:country_id => "223", :name => "Qal'at al Andalus", :aliases => "El Gelaah,Galaat el Andeless,Galaat el Andless,Galaat el Anndles,Galaat el AnndlÃ¨s,Galas el Andeless,Guelaat el Andeless,Guelaat-el-Andless,Kalaat-El-Andaleus,Kalaat-el-Andleus,Kalat-al'-Andalus,Qal`at al Andalus,Qalâat al Andalus,ÐÐ°Ð»Ð°Ñ-Ð°Ð»Ñ-ÐÐ½Ð´Ð°Ð»ÑÑ,Qalâat al Andalus", :latitude => "37.0629", :longitude => "10.11829").save
City.new(:country_id => "223", :name => "Gafsa", :aliases => "Capsa,Gafsa,Gafso,Justiniania,Kafsa,Qafsah,QafÅah,ÐÐ°ÑÑÐ°,Gafsa", :latitude => "34.425", :longitude => "8.78417").save
City.new(:country_id => "223", :name => "Gabes", :aliases => "Abes,Gabes,GabÃ¨s,Kabis,KÄbis,Qabes,Qabis,QÄbis,Tacapae,Tacape,qabs,wlayt qabs,ÐÐ°Ð±ÐµÑ,ÙØ§Ø¨Ø³,ÙÙØ§ÙØ© ÙØ§Ø¨Ø³,GabÃ¨s", :latitude => "33.88146", :longitude => "10.0982").save
City.new(:country_id => "223", :name => "Nefta", :aliases => "Aggarset Nepte,Naftah,NafÅ£ah,Nefta,Netta,ÐÐµÑÑÐ°,Nefta", :latitude => "33.87309", :longitude => "7.87765").save
City.new(:country_id => "223", :name => "Nabeul", :aliases => "Nabeul,Naboel,Nabul,NÄbul,ÐÐ°Ð±ÑÐ»,Nabeul", :latitude => "36.45606", :longitude => "10.73763").save
City.new(:country_id => "223", :name => "Midoun", :aliases => "Midoun,Midun,MÄ«dÅ«n,ÐÐ¸Ð´ÑÐ½,Midoun", :latitude => "33.80813", :longitude => "10.99228").save
City.new(:country_id => "223", :name => "Mateur", :aliases => "Matem,Mateur,Matir,MÄÅ£ir,Mateur", :latitude => "37.04045", :longitude => "9.66557").save
City.new(:country_id => "223", :name => "Masakin", :aliases => "M'saken,Masakin,MasÄkin,Msaken,Msaker,msakn,ÙØ³Ø§ÙÙ,MasÄkin", :latitude => "35.72917", :longitude => "10.58082").save
City.new(:country_id => "223", :name => "Menzel Jemil", :aliases => "Djemil,Manzil Jamil,Manzil JamÄ«l,Menjel Djemil,Mennzel Djemil,Menzel Djemil,Menzel Jemil,Menzel Jemil", :latitude => "37.23618", :longitude => "9.91448").save
City.new(:country_id => "223", :name => "Manzil Bu Zalafah", :aliases => "Manzil Bu Zalafah,Manzil BÅ« Zalafah,Mennzel Bou Zelfa,Menzel Bou Zelfa,Manzil BÅ« Zalafah", :latitude => "36.68312", :longitude => "10.58431").save
City.new(:country_id => "223", :name => "Menzel Bourguiba", :aliases => "Bourguiba,Ferryville,Manzil Bu Ruqaybah,Manzil BÅ« Ruqaybah,Menzel Bourguiba,Sidi Fath Allah,SÄ«dÄ« Fatá¸© AllÄh,Menzel Bourguiba", :latitude => "37.15368", :longitude => "9.78594").save
City.new(:country_id => "223", :name => "Menzel Abderhaman", :aliases => "Manzil `Abd ar Rahman,Manzil âAbd ar Raá¸©mÄn,Mennzel Abd er Rahmane,Mennzel-Abd-er-Ralmane,Menzel Abd er Rahmane,Menzel Abd-er-Raman,Menzel Abderhaman,Menzel Abderrahman,Menzel Abderhaman", :latitude => "37.23737", :longitude => "9.86313").save
City.new(:country_id => "223", :name => "Manouba", :aliases => "La Manouba,Manouba,Manubah,ManÅ«bah,Manouba", :latitude => "36.80803", :longitude => "10.0972").save
City.new(:country_id => "223", :name => "Majaz al Bab", :aliases => "Majaz al Bab,MajÄz al BÄb,Medjez el Bab,MajÄz al BÄb", :latitude => "36.64964", :longitude => "9.61231").save
City.new(:country_id => "223", :name => "Jendouba", :aliases => "Dzhenduba,Jendouba,Jundubah,JundÅ«bah,Souk el Arba,Souq el Arba,Suq al Arba`a',SÅ«q al ArbaâÄâ,ÐÐ¶ÐµÐ½Ð´ÑÐ±Ð°,Jendouba", :latitude => "36.50114", :longitude => "8.78024").save
City.new(:country_id => "223", :name => "Zarzis", :aliases => "Jarjis,JarjÄ«s,Zarzia,Zarzis,Zarzis", :latitude => "33.50398", :longitude => "11.11216").save
City.new(:country_id => "223", :name => "Jammal", :aliases => "Djemal,Djemmal,Djemmel,Dzhamal',Jammal,JammÄl,ÐÐ¶Ð°Ð¼Ð°Ð»Ñ,JammÄl", :latitude => "35.62231", :longitude => "10.75696").save
City.new(:country_id => "223", :name => "Houmt Souk", :aliases => "Djerba,Hawmat as Suq,Houmet Es Souk,Houmet Essouk,Houmt Souk,Houmt Souq,Humk-Suk,Humt-Suk,á¸¨awmat as SÅ«q,Houmt Souk", :latitude => "33.87576", :longitude => "10.85745").save
City.new(:country_id => "223", :name => "Hammam Sousse", :aliases => "Hadrumete,HadrumÃ¨te,Hammam Sousse,Hammam Susa,Hammam Susah,Hamman-Sousse,Justiniapolis,á¸¨ammÄm SÅ«sah,Hammam Sousse", :latitude => "35.8609", :longitude => "10.60313").save
City.new(:country_id => "223", :name => "Hammam-Lif", :aliases => "Hammam al Anf,Hammam-Lif,Hamman-Lif,Khammam-Lif,Ð¥Ð°Ð¼Ð¼Ð°Ð¼-ÐÐ¸Ñ,á¸¨ammÄm al Anf,Hammam-Lif", :latitude => "36.72866", :longitude => "10.34163").save
City.new(:country_id => "223", :name => "La Goulette", :aliases => "El Aouina,Goletta,Goulette,Halk el Oued,Halq al Wadi,Halq el Oued,La Goletta,La Gouletta,La Goulette,á¸¨alq al WÄdÄ«,La Goulette", :latitude => "36.81806", :longitude => "10.305").save
City.new(:country_id => "223", :name => "Douz", :aliases => "Douz,Duz,DÅ«z,ÐÑÐ·,Douz", :latitude => "33.46632", :longitude => "9.0203").save
City.new(:country_id => "223", :name => "Dawwar Tinjah", :aliases => "Dawwar Tinjah,DawwÄr TÄ«njah,Douar Tindja,DawwÄr TÄ«njah", :latitude => "37.16667", :longitude => "9.75").save
City.new(:country_id => "223", :name => "Dar Chabanne", :aliases => "Dar Chabane,Dar Chabanne,Dar Sha`ban,Dar-Chaabane,Dar-Chaabane-el-Fehri,DÄr ShaâbÄn,Dar Chabanne", :latitude => "36.46798", :longitude => "10.75167").save
City.new(:country_id => "223", :name => "Bizerte", :aliases => "Banzart,Biserta,Bizerta,Bizerte,Hippo Diarrhytus,Hippou Aksa,bnzrt,byzrth,ÐÐ¸Ð·ÐµÑÑÐ°,××××¨××,Ø¨ÙØ²Ø±Øª,Bizerte", :latitude => "37.27442", :longitude => "9.87391").save
City.new(:country_id => "223", :name => "Beni Khiar", :aliases => "Bani Khiyar,BanÄ« KhiyÄr,Beni Khaar,Beni Khiar,Beni Kriar,Beni Khiar", :latitude => "36.46917", :longitude => "10.78222").save
City.new(:country_id => "223", :name => "Beja", :aliases => "Bajah,Bedja,Bedzha,Beja,BÃ©ja,BÄjah,ÐÐµÐ´Ð¶Ð°,BÃ©ja", :latitude => "36.72564", :longitude => "9.18169").save
City.new(:country_id => "223", :name => "Zouila", :aliases => "Az Zawilah,Az ZawÄ«lah,Zouila,Zuila,Zouila", :latitude => "35.50056", :longitude => "11.06056").save
City.new(:country_id => "223", :name => "Chebba", :aliases => "Ash Shabbah,Ash ShÄbbah,Chebba,La Chebba,Sheba,Chebba", :latitude => "35.23722", :longitude => "11.115").save
City.new(:country_id => "223", :name => "Ar Rudayyif", :aliases => "Ar Rudayyif,Redevef,Redevel,Redeyef,Ar Rudayyif", :latitude => "34.3827", :longitude => "8.15549").save
City.new(:country_id => "223", :name => "Al Wardanin", :aliases => "Al Wardanin,Al WardÄnÄ«n,Ouadenine,Ouardanine,Ouardenine,Uardenine,Al WardÄnÄ«n", :latitude => "35.70915", :longitude => "10.67397").save
City.new(:country_id => "223", :name => "Kairouan", :aliases => "Al Qayrawan,Al QayrawÄn,Al-Kayrawan,Al-KayrawÄn,Kairouan,Kairuan,Kairwan,Kajruan,Kajruano,Kayravan,Qairouan,Qairwan,Qayrawan,qyrwan,ÐÐ°Ð¹ÑÑÐ°Ð½,×§××¨×××,ÙÙØ±ÙØ§Ù,Kairouan", :latitude => "35.6781", :longitude => "10.09633").save
City.new(:country_id => "223", :name => "Kasserine", :aliases => "Al Qasrayn,Al QaÅrayn,Kasserin,Kasserine,Qasserine,ÐÐ°ÑÑÐµÑÐ¸Ð½,Kasserine", :latitude => "35.16758", :longitude => "8.83651").save
City.new(:country_id => "223", :name => "Al Qarmadah", :aliases => "Al Qarmadah,Gremda,Al Qarmadah", :latitude => "34.75", :longitude => "10.78333").save
City.new(:country_id => "223", :name => "Monastir", :aliases => "Al Munastir,Al MunastÄ«r,El Menstir,Hadrumetum,Monastir,Ruspina,almnstyr,mnstyr,ÐÐ¾Ð½Ð°ÑÑÐ¸Ñ,Ø§ÙÙÙØ³ØªÙØ±,ÙÙØ³ØªÙØ±,Monastir", :latitude => "35.78333", :longitude => "10.83333").save
City.new(:country_id => "223", :name => "La Mohammedia", :aliases => "Al Muhammadiyah,Al Muá¸©ammadÄ«yah,La Mohammedia,Mohamedia,Mohamedla,Mohammedia,La Mohammedia", :latitude => "36.67446", :longitude => "10.15633").save
City.new(:country_id => "223", :name => "Al Metlaoui", :aliases => "Al Metlaoui,Matlaoui,Metlaoni,Metlaoui,Al Metlaoui", :latitude => "34.32081", :longitude => "8.40158").save
City.new(:country_id => "223", :name => "Al Marsa", :aliases => "Al Marsa,Al MarsÃ¡,El Marsa,La Marsa,Al MarsÃ¡", :latitude => "36.87818", :longitude => "10.32466").save
City.new(:country_id => "223", :name => "Mahdia", :aliases => "Africa,Al Mahdiyah,Al MahdÄ«yah,Madhia,Mahdia,Mahedia,Mehdia,Zella,Mahdia", :latitude => "35.50472", :longitude => "11.06222").save
City.new(:country_id => "223", :name => "El Kef", :aliases => "Al Kaf,Al KÄf,Chakbanaria,Chikka Benar,Ehl'-Kef,El Kef,Kef,Le Kef,Sicca Veneria,Ð­Ð»Ñ-ÐÐµÑ,El Kef", :latitude => "36.17424", :longitude => "8.70486").save
City.new(:country_id => "223", :name => "El Jem", :aliases => "Al Jamm,Ehl' Dzhem,El Djem,El Jem,El Jemm,Sidi el Djem,Thysdrus,Ð­Ð»Ñ ÐÐ¶ÐµÐ¼,El Jem", :latitude => "35.3", :longitude => "10.71667").save
City.new(:country_id => "223", :name => "Al Hammamat", :aliases => "Al Hammamat,Al á¸¨ammÄmÄt,Hammamet,Khammamet,alhmamat,Ð¥Ð°Ð¼Ð¼Ð°Ð¼ÐµÑ,Ø§ÙØ­ÙØ§ÙØ§Øª,Al á¸¨ammÄmÄt", :latitude => "36.4", :longitude => "10.61667").save
City.new(:country_id => "223", :name => "El Hamma", :aliases => "Al Hammah,Al á¸¨Ämmah,Ehl'-Khamma,El Hamma,El Hamma de l'Arad,El Hamma de lâArad,Ð­Ð»Ñ-Ð¥Ð°Ð¼Ð¼Ð°,El Hamma", :latitude => "33.89152", :longitude => "9.79629").save
City.new(:country_id => "223", :name => "Al Baqalitah", :aliases => "Al Baqalitah,Al BaqÄliÅ£ah,Bekalta,Mkalta,Al BaqÄliÅ£ah", :latitude => "35.61739", :longitude => "10.99466").save
City.new(:country_id => "223", :name => "Al `Aliyah", :aliases => "Al `Aliyah,Al âÄliyah,Ehl'-Alija,El Alia,Uzalis,Ð­Ð»Ñ-ÐÐ»Ð¸Ñ,Al âÄliyah", :latitude => "37.1691", :longitude => "10.03478").save
City.new(:country_id => "223", :name => "Akouda", :aliases => "Akkudah,AkkÅ«dah,Akouda,Akuda,Akouda", :latitude => "35.8691", :longitude => "10.5653").save
City.new(:country_id => "223", :name => "Douane", :aliases => ",Douane", :latitude => "36.44766", :longitude => "10.7557").save
