City.new(:country_id => "228", :name => "Douliu", :aliases => "Douliou,Douliu,Jun'-lin',Tou-liu,Tou-liu-chieh,Yun-lin,Yun-lin-hsien,YÃ¼n-lin,YÃ¼n-lin-hsien,Ð®Ð½Ñ-Ð»Ð¸Ð½Ñ,æå­,Douliu", :latitude => "23.70944", :longitude => "120.54333").save
City.new(:country_id => "228", :name => "Yujing", :aliases => "Chiao-pa-nien,Yu-ching,Yu-ching-chuang,Yu-ching-ts'un,Yujing,YÃ¼-ching,YÃ¼-ching-chuang,YÃ¼-ching-tsâun,yu jing,çäº,Yujing", :latitude => "23.12493", :longitude => "120.46138").save
City.new(:country_id => "228", :name => "Taipei", :aliases => "Kota Taipei,Pan Kiao,Pan-ch'iao,Pan-ch'iao-chen,Pan-ch'iao-chieh,Pan-châiao,Pan-châiao-chen,Pan-châiao-chieh,T'ai-pei,T'ai-pei Shih,T'ai-pei-hsien,Taibei Shi,Taibei Shih,Taibejus,TaibÄjus,Taipe,Taipeh,Taipei,Taipeium,Taipejus,TaipÃ©,TaipÃ©i,TaipÄjus,Tajbehj,Tajpej,Tajpeo,Tayipeh,TayipÃ¨h,Tchaj-pej,Tâai-pei,Tâai-pei Shih,Tâai-pei-hsien,ta'ipe,tai bei shi,taibei,taibei si,thipe,ÄÃ i Báº¯c,Î¤Î±ÏÏÎ­Î¹,Ð¢Ð°Ð¹Ð±ÑÐ¹,Ð¢Ð°Ð¹Ð¿ÐµÐ¹,Ð¢Ð°ÑÐ¿ÐµÑ,××××¤×,××××¤××,ØªÛÙØ¨ÛÙ,à¤¤à¤¾à¤à¤ªà¥,à¹à¸à¹à¸,à½à½ à½ºà¼à½à½º,á³á­á,å°åå¸,èºåå¸,íì´ë² ì´,íì´ë² ì´ ì,Taipei", :latitude => "25.04776", :longitude => "121.53185").save
City.new(:country_id => "228", :name => "Taichung", :aliases => "T'ai-chung,T'ai-chung-shih,Taichung,Taijhong Shih,Taizhong Shi,Tâai-chung,Tâai-chung-shih,èºä¸­å¸,Taichung", :latitude => "24.1469", :longitude => "120.6839").save
City.new(:country_id => "228", :name => "Daxi", :aliases => "Dasi,Daxi,Ta-Si-chen,Ta-ch'i,Ta-ch'i-chen,Ta-ch'i-chieh,Ta-châi,Ta-châi-chen,Ta-châi-chieh,Ta-hsi,Ta-hsi-chen,Ta-k'o-k'an,Ta-kâo-kâan,Ð¢Ð°-Ð¡Ð¸-ÑÐµÐ½,å¤§æºª,Daxi", :latitude => "24.88373", :longitude => "121.29043").save
City.new(:country_id => "228", :name => "Banqiao", :aliases => "Banciao,Banqiao,Fan-ch'iao,Fan-châiao,Fang-ch'iao,Fang-châiao,Pan-ch'iao,Pan-châiao,San-kuang,San-kuang-li,ban qiao,æ¿æ©,Banqiao", :latitude => "25.01427", :longitude => "121.46719").save
City.new(:country_id => "228", :name => "Buli", :aliases => "Buli,Pu-li,Pu-li-chieh,Puli,bu li,ÐÑÐ»Ð¸,åé,Buli", :latitude => "23.96639", :longitude => "120.96952").save
City.new(:country_id => "228", :name => "Nantou", :aliases => "Nan'tou,Nan-t'ou,Nan-t'ou-chieh,Nan-t'ou-hsien,Nan-t'ou-shih,Nan-tâou,Nan-tâou-chieh,Nan-tâou-hsien,Nan-tâou-shih,Nantou,Nantow,nan tou,ÐÐ°Ð½ÑÑÐ¾Ñ,åæ,Nantou", :latitude => "23.91566", :longitude => "120.66387").save
City.new(:country_id => "228", :name => "Ma-kung", :aliases => "Magong,Magun,P'eng-hu,P'eng-hu-hsien,ma gong,ÐÐ°Ð³ÑÐ½,é¦¬å¬,Ma-kung", :latitude => "23.5654", :longitude => "119.58627").save
City.new(:country_id => "228", :name => "Lugu", :aliases => "Ch'iang-tzu-liao,Châiang-tzu-liao,Lu-ku,Lugu,lu gu,ÐÑÐ³Ñ,é¹¿è°·,Lugu", :latitude => "23.74639", :longitude => "120.7525").save
City.new(:country_id => "228", :name => "Kaohsiung", :aliases => "Gaosjun,Gaosyongshih,Gaoxiongshi,Kao-hsiung,Kao-hsiung-shih,Kaohsiung,Kaohsiung City,gao xiong shi,ÐÐ°Ð¾ÑÑÐ½,é«éå·¿,é«éå¸,Kaohsiung", :latitude => "22.61626", :longitude => "120.31333").save
City.new(:country_id => "228", :name => "Yilan", :aliases => "I-lan,I-lan-hsien,I-lan-shih,Ilan,Ka-ma-lan,Yilan,Yilan City,YÃ­lÃ¡n,yi lan,yi lan shi,å®è­,å®è­å¸,Yilan", :latitude => "24.757", :longitude => "121.753").save
City.new(:country_id => "228", :name => "Hualian", :aliases => "Hua Lien Kang,Hua-lien,Hua-lien-chiang,Hua-lien-hsien,Hua-lien-shih,Hualian,Hualien,Hualian", :latitude => "23.97694", :longitude => "121.60444").save
City.new(:country_id => "228", :name => "Xinzhushi", :aliases => "Hsin-chu,Hsin-chu-hsien,Hsin-chu-shih,Sin'chzhu,Sinjhushih,Xinzhushi,xin zhu shi,Ð¡Ð¸Ð½ÑÑÐ¶Ñ,æ°ç«¹å¸,Xinzhushi", :latitude => "24.80361", :longitude => "120.96861").save
City.new(:country_id => "228", :name => "Hengchun", :aliases => "Heng-ch'un,Heng-châun,Hengchun,heng chun,ææ¥,Hengchun", :latitude => "22.00417", :longitude => "120.74389").save
City.new(:country_id => "228", :name => "Keelung", :aliases => "Chi-lung,Chi-lung-shih,Chilung,Co Long,CÆ¡ Long,Jilong,Jilongshi,Jilongshih,Keelung,Shi-lun,ji long shi,jilung si,Ð¨Ð¸-Ð»ÑÐ½,åºé,åºéå¸,ì§ë£½ ì,Keelung", :latitude => "25.12825", :longitude => "121.7419").save
City.new(:country_id => "228", :name => "Tainan City", :aliases => "Tajnan',Ð¢Ð°Ð¹Ð½Ð°Ð½Ñ,Tainan City", :latitude => "23.02476", :longitude => "120.16811").save
City.new(:country_id => "228", :name => "Taoyuan City", :aliases => "Taojuan',Ð¢Ð°Ð¾ÑÐ°Ð½Ñ,Taoyuan City", :latitude => "24.99368", :longitude => "121.29696").save
City.new(:country_id => "228", :name => "Taitung City", :aliases => "GJai GJong,Taidong,Taitung,Tchaj-tung,TÃ¡idong,tai dong shi,ÄÃ i ÄÃ´ng,å°æ±å¸,Taitung City", :latitude => "22.7583", :longitude => "121.1444").save
City.new(:country_id => "228", :name => "Zhongxing New Village", :aliases => "Chung-hsing-hsin-tsun,Jhongsing,Zhongxing,Zhongxing New Village", :latitude => "23.95908", :longitude => "120.68516").save
