City.new(:country_id => "229", :name => "Zanzibar", :aliases => "Unguja,Zanzibar,Zanzibar City,ÐÐ°Ð½Ð·Ð¸Ð±Ð°Ñ,Zanzibar", :latitude => "-6.16394", :longitude => "39.19793").save
City.new(:country_id => "229", :name => "Wete", :aliases => "Veto,Wete,Weti,ÐÐµÑÐ¾,Wete", :latitude => "-5.05589", :longitude => "39.72938").save
City.new(:country_id => "229", :name => "Vwawa", :aliases => "Vawa,Vwawa,Vwawa", :latitude => "-9.11667", :longitude => "32.93333").save
City.new(:country_id => "229", :name => "Vikindu", :aliases => "Vikindu,Vikindu", :latitude => "-7.00667", :longitude => "39.29849").save
City.new(:country_id => "229", :name => "Uyovu", :aliases => ",Uyovu", :latitude => "-3.28333", :longitude => "31.52583").save
City.new(:country_id => "229", :name => "Uvinza", :aliases => "Kimalapamba,Rutschugiposten,Urvinsa,Uvinza,Uwinsa,Uvinza", :latitude => "-5.10361", :longitude => "30.39111").save
City.new(:country_id => "229", :name => "Ushirombo", :aliases => ",Ushirombo", :latitude => "-3.49194", :longitude => "31.96389").save
City.new(:country_id => "229", :name => "Usevia", :aliases => "Usevia,Usevya,Usevia", :latitude => "-7.1", :longitude => "31.23333").save
City.new(:country_id => "229", :name => "Usagara", :aliases => ",Usagara", :latitude => "-2.68333", :longitude => "33").save
City.new(:country_id => "229", :name => "Usa", :aliases => "Usa,Usa River,Usa", :latitude => "-3.36667", :longitude => "36.85").save
City.new(:country_id => "229", :name => "Urambo", :aliases => ",Urambo", :latitude => "-5.06667", :longitude => "32.05").save
City.new(:country_id => "229", :name => "Tunduma", :aliases => "Tunduma,Tunduma", :latitude => "-9.3", :longitude => "32.76667").save
City.new(:country_id => "229", :name => "Tumbi", :aliases => ",Tumbi", :latitude => "-5.06667", :longitude => "32.73333").save
City.new(:country_id => "229", :name => "Tukuyu", :aliases => "Neu-Langenberg,Neu-Langenburg,New Langenberg,Ntukuju,Tukuyu,Tukuyu", :latitude => "-9.25", :longitude => "33.65").save
City.new(:country_id => "229", :name => "Tinde", :aliases => ",Tinde", :latitude => "-3.88333", :longitude => "33.2").save
City.new(:country_id => "229", :name => "Tarime", :aliases => ",Tarime", :latitude => "-1.35", :longitude => "34.36667").save
City.new(:country_id => "229", :name => "Tanga", :aliases => "Longa,Tanga,tnjanyqa,Ð¢Ð°Ð½Ð³Ð°,ØªÙØ¬Ø§ÙÙÙØ§,Tanga", :latitude => "-5.06667", :longitude => "39.1").save
City.new(:country_id => "229", :name => "Tabora", :aliases => "Tabora,Ð¢Ð°Ð±Ð¾ÑÐ°,Tabora", :latitude => "-5.01667", :longitude => "32.8").save
City.new(:country_id => "229", :name => "Sumbawanga", :aliases => "Sumbawanga,Zumbawanga,Zumbayanga,Sumbawanga", :latitude => "-7.96667", :longitude => "31.61667").save
City.new(:country_id => "229", :name => "Songwa", :aliases => ",Songwa", :latitude => "-3.51667", :longitude => "33.51667").save
City.new(:country_id => "229", :name => "Somanda", :aliases => ",Somanda", :latitude => "-3.36667", :longitude => "33.95").save
City.new(:country_id => "229", :name => "Sokoni", :aliases => ",Sokoni", :latitude => "-6.43333", :longitude => "39.55").save
City.new(:country_id => "229", :name => "Sirari", :aliases => ",Sirari", :latitude => "-1.23333", :longitude => "34.43333").save
City.new(:country_id => "229", :name => "Singida", :aliases => ",Singida", :latitude => "-4.81667", :longitude => "34.75").save
City.new(:country_id => "229", :name => "Sikonge", :aliases => ",Sikonge", :latitude => "-5.63333", :longitude => "32.76667").save
City.new(:country_id => "229", :name => "Shinyanga", :aliases => "Schinjanga,Shinyanga,Shinyanga", :latitude => "-3.66667", :longitude => "33.43333").save
City.new(:country_id => "229", :name => "Shelui", :aliases => ",Shelui", :latitude => "-4.36667", :longitude => "34.2").save
City.new(:country_id => "229", :name => "Sepuka", :aliases => "Sepuka,Sipuka,Sepuka", :latitude => "-4.75", :longitude => "34.53333").save
City.new(:country_id => "229", :name => "Same", :aliases => "Same,Ssame,Zame,Same", :latitude => "-4.06667", :longitude => "37.73333").save
City.new(:country_id => "229", :name => "Rulenge", :aliases => ",Rulenge", :latitude => "-2.7175", :longitude => "30.6325").save
City.new(:country_id => "229", :name => "Rujewa", :aliases => "Rujewa,Rujewo,Rujewa", :latitude => "-8.7", :longitude => "34.38333").save
City.new(:country_id => "229", :name => "Puma", :aliases => ",Puma", :latitude => "-5", :longitude => "34.73333").save
City.new(:country_id => "229", :name => "Old Shinyanga", :aliases => ",Old Shinyanga", :latitude => "-3.55", :longitude => "33.4").save
City.new(:country_id => "229", :name => "Nzega", :aliases => ",Nzega", :latitude => "-4.21667", :longitude => "33.18333").save
City.new(:country_id => "229", :name => "Nyamuswa", :aliases => ",Nyamuswa", :latitude => "-1.9", :longitude => "34.01667").save
City.new(:country_id => "229", :name => "Nyalikungu", :aliases => "Nyalikungu,Nyarikungu,Nyalikungu", :latitude => "-3.18333", :longitude => "33.78333").save
City.new(:country_id => "229", :name => "Nyakabindi", :aliases => ",Nyakabindi", :latitude => "-2.63333", :longitude => "33.98333").save
City.new(:country_id => "229", :name => "Nsunga", :aliases => ",Nsunga", :latitude => "-1.14389", :longitude => "31.39472").save
City.new(:country_id => "229", :name => "Nshamba", :aliases => ",Nshamba", :latitude => "-1.79833", :longitude => "31.55111").save
City.new(:country_id => "229", :name => "Njombe", :aliases => "Njobe,Njombe,Njombe", :latitude => "-9.33333", :longitude => "34.76667").save
City.new(:country_id => "229", :name => "Nguruka", :aliases => ",Nguruka", :latitude => "-5.10917", :longitude => "31.04194").save
City.new(:country_id => "229", :name => "Ngudu", :aliases => ",Ngudu", :latitude => "-2.96667", :longitude => "33.33333").save
City.new(:country_id => "229", :name => "Ngerengere", :aliases => ",Ngerengere", :latitude => "-6.75", :longitude => "38.11667").save
City.new(:country_id => "229", :name => "Ngara", :aliases => ",Ngara", :latitude => "-2.51222", :longitude => "30.65583").save
City.new(:country_id => "229", :name => "Nangwa", :aliases => ",Nangwa", :latitude => "-4.46667", :longitude => "35.45").save
City.new(:country_id => "229", :name => "Namanyere", :aliases => ",Namanyere", :latitude => "-7.51667", :longitude => "31.05").save
City.new(:country_id => "229", :name => "Mwanza", :aliases => "Muansa,Muanza,Muvanzo,Mvanza,Mwamza,Mwansa,Mwanza,ÐÐ²Ð°Ð½Ð·Ð°,Mwanza", :latitude => "-2.51667", :longitude => "32.9").save
City.new(:country_id => "229", :name => "Mwadui", :aliases => ",Mwadui", :latitude => "-3.55", :longitude => "33.6").save
City.new(:country_id => "229", :name => "Mvomero", :aliases => ",Mvomero", :latitude => "-6.25", :longitude => "38.66667").save
City.new(:country_id => "229", :name => "Musoma", :aliases => "Mazama,Misoma,Musoma,Musome,Muzoma,ÐÑÑÐ¾Ð¼Ð°,Musoma", :latitude => "-1.5", :longitude => "33.8").save
City.new(:country_id => "229", :name => "Muriti", :aliases => ",Muriti", :latitude => "-1.98333", :longitude => "32.91667").save
City.new(:country_id => "229", :name => "Mungaa", :aliases => ",Mungaa", :latitude => "-4.96667", :longitude => "34.88333").save
City.new(:country_id => "229", :name => "Muheza", :aliases => "Mubeza,Muheza,Muheza", :latitude => "-5.16667", :longitude => "38.78333").save
City.new(:country_id => "229", :name => "Mugumu", :aliases => ",Mugumu", :latitude => "-1.85", :longitude => "34.7").save
City.new(:country_id => "229", :name => "Mtwango", :aliases => ",Mtwango", :latitude => "-9.01667", :longitude => "34.8").save
City.new(:country_id => "229", :name => "Mto wa Mbu", :aliases => ",Mto wa Mbu", :latitude => "-3.35", :longitude => "35.85").save
City.new(:country_id => "229", :name => "Mtinko", :aliases => ",Mtinko", :latitude => "-4.55", :longitude => "34.85").save
City.new(:country_id => "229", :name => "Msowero", :aliases => ",Msowero", :latitude => "-6.53333", :longitude => "37.2").save
City.new(:country_id => "229", :name => "Mpwapwa", :aliases => "Mpapua,Mpapwa,Mpwapwa,Mpwapwa", :latitude => "-6.35", :longitude => "36.48333").save
City.new(:country_id => "229", :name => "Mpanda", :aliases => "Mpanda,Mpanda", :latitude => "-6.36546", :longitude => "31.04091").save
City.new(:country_id => "229", :name => "Moshi", :aliases => "Moschi,Moshi,ÐÐ¾ÑÐ¸,Moshi", :latitude => "-3.35", :longitude => "37.33333").save
City.new(:country_id => "229", :name => "Morogoro", :aliases => "Mkoa wa Morogoro,Morogoro,Mrogoro,Murogoro,morogoro zhou,ÐÐ¾ÑÐ¾Ð³Ð¾ÑÐ¾,ã¢ã­ã´ã­å·,Morogoro", :latitude => "-6.81667", :longitude => "37.66667").save
City.new(:country_id => "229", :name => "Mlowo", :aliases => ",Mlowo", :latitude => "-9", :longitude => "32.98333").save
City.new(:country_id => "229", :name => "Mlimba", :aliases => "Mlimba,Mlimba", :latitude => "-8.8", :longitude => "35.81667").save
City.new(:country_id => "229", :name => "Mlangali", :aliases => ",Mlangali", :latitude => "-9.78333", :longitude => "34.51667").save
City.new(:country_id => "229", :name => "Mlandizi", :aliases => ",Mlandizi", :latitude => "-6.7", :longitude => "38.73333").save
City.new(:country_id => "229", :name => "Mlalo", :aliases => ",Mlalo", :latitude => "-4.93333", :longitude => "38.93333").save
City.new(:country_id => "229", :name => "Mkuranga", :aliases => "Mkuranga,Mkwanga,Mkuranga", :latitude => "-7.11799", :longitude => "39.20782").save
City.new(:country_id => "229", :name => "Mwandiga", :aliases => "Mandyga,Miwandica,Mwandiga,Mwandiga", :latitude => "-4.83", :longitude => "29.65806").save
City.new(:country_id => "229", :name => "Missungwi", :aliases => "Isungwi,Missungwi,Misungwi,Missungwi", :latitude => "-2.85", :longitude => "33.08333").save
City.new(:country_id => "229", :name => "Mikumi", :aliases => "Mikumi,Mikumi", :latitude => "-7.40409", :longitude => "36.98309").save
City.new(:country_id => "229", :name => "Mhango", :aliases => ",Mhango", :latitude => "-3.28333", :longitude => "32.85").save
City.new(:country_id => "229", :name => "Mgandu", :aliases => ",Mgandu", :latitude => "-5.95", :longitude => "34.13333").save
City.new(:country_id => "229", :name => "Mbuguni", :aliases => ",Mbuguni", :latitude => "-3.56667", :longitude => "36.95").save
City.new(:country_id => "229", :name => "Mbeya", :aliases => "Mbee,Mbeya,ÐÐ±ÐµÐµ,Mbeya", :latitude => "-8.9", :longitude => "33.45").save
City.new(:country_id => "229", :name => "Mazinde", :aliases => ",Mazinde", :latitude => "-4.8", :longitude => "38.21667").save
City.new(:country_id => "229", :name => "Matui", :aliases => ",Matui", :latitude => "-4.8", :longitude => "38.25").save
City.new(:country_id => "229", :name => "Matai", :aliases => ",Matai", :latitude => "-8.3", :longitude => "31.51667").save
City.new(:country_id => "229", :name => "Maswa", :aliases => ",Maswa", :latitude => "-2.68333", :longitude => "33.98333").save
City.new(:country_id => "229", :name => "Masumbwe", :aliases => ",Masumbwe", :latitude => "-3.63333", :longitude => "32.18333").save
City.new(:country_id => "229", :name => "Maramba", :aliases => ",Maramba", :latitude => "-5.05", :longitude => "38.61667").save
City.new(:country_id => "229", :name => "Malinyi", :aliases => ",Malinyi", :latitude => "-8.93333", :longitude => "36.13333").save
City.new(:country_id => "229", :name => "Malampaka", :aliases => ",Malampaka", :latitude => "-3.13333", :longitude => "33.53333").save
City.new(:country_id => "229", :name => "Makuyuni", :aliases => ",Makuyuni", :latitude => "-4.73333", :longitude => "38.1").save
City.new(:country_id => "229", :name => "Makumbako", :aliases => "Makambako,Makumbako,Makumbako", :latitude => "-8.85", :longitude => "34.83333").save
City.new(:country_id => "229", :name => "Mahanje", :aliases => ",Mahanje", :latitude => "-9.93333", :longitude => "35.33333").save
City.new(:country_id => "229", :name => "Magu Kahangara", :aliases => ",Magu Kahangara", :latitude => "-2.58333", :longitude => "33.35").save
City.new(:country_id => "229", :name => "Magugu", :aliases => "Magagu,Magugu,Magugu", :latitude => "-4.01667", :longitude => "35.76667").save
City.new(:country_id => "229", :name => "Magomeni", :aliases => ",Magomeni", :latitude => "-6.8", :longitude => "39.25").save
City.new(:country_id => "229", :name => "Magole", :aliases => ",Magole", :latitude => "-6.36667", :longitude => "37.36667").save
City.new(:country_id => "229", :name => "Mafinga", :aliases => ",Mafinga", :latitude => "-7.25", :longitude => "35.06667").save
City.new(:country_id => "229", :name => "Mabama", :aliases => ",Mabama", :latitude => "-5.13333", :longitude => "32.53333").save
City.new(:country_id => "229", :name => "Lushoto", :aliases => "Lushoto,Wilhelmstal,Lushoto", :latitude => "-4.78333", :longitude => "38.28333").save
City.new(:country_id => "229", :name => "Lugoba", :aliases => ",Lugoba", :latitude => "-6.45", :longitude => "38.33333").save
City.new(:country_id => "229", :name => "Liwale", :aliases => "Livale,Liwale,Liwale", :latitude => "-9.76667", :longitude => "37.93333").save
City.new(:country_id => "229", :name => "Lembeni", :aliases => ",Lembeni", :latitude => "-3.78333", :longitude => "37.61667").save
City.new(:country_id => "229", :name => "Lalago", :aliases => ",Lalago", :latitude => "-3.45", :longitude => "33.95").save
City.new(:country_id => "229", :name => "Laela", :aliases => ",Laela", :latitude => "-8.56667", :longitude => "32.05").save
City.new(:country_id => "229", :name => "Kyela", :aliases => "Kyela,Kyela", :latitude => "-9.58333", :longitude => "33.85").save
City.new(:country_id => "229", :name => "Kondoa", :aliases => "Kondoa,Kondoa Irangi,Kondoa", :latitude => "-4.9", :longitude => "35.78333").save
City.new(:country_id => "229", :name => "Kiwira", :aliases => ",Kiwira", :latitude => "-9.16667", :longitude => "33.53333").save
City.new(:country_id => "229", :name => "Kishapu", :aliases => ",Kishapu", :latitude => "-3.61667", :longitude => "33.86667").save
City.new(:country_id => "229", :name => "Kisesa", :aliases => ",Kisesa", :latitude => "-3.08333", :longitude => "34.15").save
City.new(:country_id => "229", :name => "Kirando", :aliases => ",Kirando", :latitude => "-7.41667", :longitude => "30.6").save
City.new(:country_id => "229", :name => "Kiomboi", :aliases => ",Kiomboi", :latitude => "-4.26667", :longitude => "34.36667").save
City.new(:country_id => "229", :name => "Kingori", :aliases => ",Kingori", :latitude => "-3.28333", :longitude => "36.98333").save
City.new(:country_id => "229", :name => "Kilosa", :aliases => "Kilosa,Kilossa,Kilosa", :latitude => "-6.83333", :longitude => "36.98333").save
City.new(:country_id => "229", :name => "Kigoma", :aliases => "Kigoma,Kigome,Kigomo,qygwmh,ÐÐ¸Ð³Ð¾Ð¼Ðµ,×§×××××,Kigoma", :latitude => "-4.87694", :longitude => "29.62667").save
City.new(:country_id => "229", :name => "Kidodi", :aliases => "Kidodi,Kidodi", :latitude => "-7.60361", :longitude => "37.00438").save
City.new(:country_id => "229", :name => "Kidatu", :aliases => "Kidatu,Kidatu", :latitude => "-7.69916", :longitude => "36.95722").save
City.new(:country_id => "229", :name => "Kibondo", :aliases => ",Kibondo", :latitude => "-3.58639", :longitude => "30.72028").save
City.new(:country_id => "229", :name => "Kibiti", :aliases => "Kibiti,Kibiti", :latitude => "-7.72178", :longitude => "38.93749").save
City.new(:country_id => "229", :name => "Kibara", :aliases => "Kibara,Kibarra,Kibara", :latitude => "-2.15", :longitude => "33.45").save
City.new(:country_id => "229", :name => "Kibakwe", :aliases => ",Kibakwe", :latitude => "-6.71667", :longitude => "36.36667").save
City.new(:country_id => "229", :name => "Kibaha", :aliases => "Kibaha,Kibaha", :latitude => "-6.76667", :longitude => "38.91667").save
City.new(:country_id => "229", :name => "Katumba", :aliases => "Kabumba,Katumba,ÐÐ°ÑÑÐ¼Ð±Ð°,Katumba", :latitude => "-9.23333", :longitude => "33.61667").save
City.new(:country_id => "229", :name => "Katoro", :aliases => ",Katoro", :latitude => "-3.02028", :longitude => "31.89583").save
City.new(:country_id => "229", :name => "Katerero", :aliases => ",Katerero", :latitude => "-1.4", :longitude => "31.73333").save
City.new(:country_id => "229", :name => "Kasulu", :aliases => "Kassulo,Kasulo,Kasulu,ÐÐ°ÑÑÐ»Ñ,Kasulu", :latitude => "-4.57667", :longitude => "30.1025").save
City.new(:country_id => "229", :name => "Kasamwa", :aliases => ",Kasamwa", :latitude => "-2.85", :longitude => "32.43333").save
City.new(:country_id => "229", :name => "Karatu", :aliases => "Karatu,Karatu", :latitude => "-3.33333", :longitude => "35.66667").save
City.new(:country_id => "229", :name => "Kamachumu", :aliases => ",Kamachumu", :latitude => "-1.61861", :longitude => "31.62").save
City.new(:country_id => "229", :name => "Kakonko", :aliases => ",Kakonko", :latitude => "-3.28278", :longitude => "30.96417").save
City.new(:country_id => "229", :name => "Kahama", :aliases => ",Kahama", :latitude => "-3.83333", :longitude => "32.6").save
City.new(:country_id => "229", :name => "Kabanga", :aliases => ",Kabanga", :latitude => "-2.63861", :longitude => "30.46778").save
City.new(:country_id => "229", :name => "Izazi", :aliases => "Isasi,Izazi,Zasi,Izazi", :latitude => "-7.2", :longitude => "35.73333").save
City.new(:country_id => "229", :name => "Itigi", :aliases => "Itigi,Itigi", :latitude => "-5.7", :longitude => "34.48333").save
City.new(:country_id => "229", :name => "Isaka", :aliases => "Isaka,ÐÑÐ°ÐºÐ°,Isaka", :latitude => "-3.9", :longitude => "32.93333").save
City.new(:country_id => "229", :name => "Iringa", :aliases => "Iringa,ÐÑÐ¸Ð½Ð³Ð°,Iringa", :latitude => "-7.76667", :longitude => "35.7").save
City.new(:country_id => "229", :name => "Ipinda", :aliases => "Ipande,Ipinda,Ipinda", :latitude => "-9.48333", :longitude => "33.9").save
City.new(:country_id => "229", :name => "Ilula", :aliases => "Ilula,Ilula", :latitude => "-7.6766", :longitude => "36.03658").save
City.new(:country_id => "229", :name => "Ilongero", :aliases => "Ilongero,Irongero,Ilongero", :latitude => "-4.66667", :longitude => "34.86667").save
City.new(:country_id => "229", :name => "Ilembula", :aliases => ",Ilembula", :latitude => "-8.9", :longitude => "34.58333").save
City.new(:country_id => "229", :name => "Ikungi", :aliases => ",Ikungi", :latitude => "-5.13333", :longitude => "34.76667").save
City.new(:country_id => "229", :name => "Igurusi", :aliases => "Igurunzi,Igurusi,Igurusi", :latitude => "-8.85", :longitude => "33.85").save
City.new(:country_id => "229", :name => "Igunga", :aliases => ",Igunga", :latitude => "-4.28333", :longitude => "33.88333").save
City.new(:country_id => "229", :name => "Igugunu", :aliases => "Iguguno,Igugunu,Igugunu", :latitude => "-4.56667", :longitude => "34.63333").save
City.new(:country_id => "229", :name => "Ifakara", :aliases => "Ifakara,Ifakara", :latitude => "-8.13333", :longitude => "36.68333").save
City.new(:country_id => "229", :name => "Hedaru", :aliases => ",Hedaru", :latitude => "-4.5", :longitude => "37.9").save
City.new(:country_id => "229", :name => "Geiro", :aliases => "Gairo,Geiro,Geiro", :latitude => "-6.15", :longitude => "36.86667").save
City.new(:country_id => "229", :name => "Galappo", :aliases => "Galapo,Galappo,Gwanzave,Galappo", :latitude => "-4.26667", :longitude => "35.85").save
City.new(:country_id => "229", :name => "Dongobesh", :aliases => "Dongabesh,Dongobesh,Dongobesh", :latitude => "-4.06667", :longitude => "35.38333").save
City.new(:country_id => "229", :name => "Dodoma", :aliases => "Dodoma,Dodomao,DÃ³dÃ³ma,Idodoma,dodoma,duo duo ma,dwdwma,dwdwmh,ÐÐ¾Ð´Ð¾Ð¼Ð°,××××××,Ø¯ÙØ¯ÙÙØ§,à¤¡à¥à¤¡à¥à¤®à¤¾,á¶á¶á,ããã,å¤å¤é©¬,Dodoma", :latitude => "-6.17486", :longitude => "35.73792").save
City.new(:country_id => "229", :name => "Dar es Salaam", :aliases => "Dar es Salaam,Dar es Salam,Dar es Salamas,Dar es SalÃ¡m,Dar es-Salaam,Dar-ehs-Salam,Dar-es-Salaam,Daresalamo,Daressalam,DÄr es SalÄm,Ntontoma,da lei si sa la mu,daleueseusallam,dar alslam,daruesusaramu,ÎÏÎ¿Î½ÏÏÎ¼Î±,ÐÐ°Ñ ÐµÑ Ð¡Ð°Ð»Ð°Ð¼,ÐÐ°Ñ-ÐµÑ-Ð¡Ð°Ð»Ð°Ð°Ð¼,ÐÐ°Ñ-ÑÑ-Ð¡Ð°Ð»Ð°Ð¼,×××¨ ×-×¡×××,Ø¯Ø§Ø± Ø§ÙØ³ÙØ§Ù,ãã«ã¨ã¹ãµã©ã¼ã ,è¾¾ç´¯æ¯è¨æå§,ë¤ë¥´ìì¤ì´ë,Dar es Salaam", :latitude => "-6.82349", :longitude => "39.26951").save
City.new(:country_id => "229", :name => "Dareda", :aliases => "Dareda,Ndareda,Dareda", :latitude => "-4.21667", :longitude => "35.55").save
City.new(:country_id => "229", :name => "Chimala", :aliases => ",Chimala", :latitude => "-8.85", :longitude => "34.01667").save
City.new(:country_id => "229", :name => "Chato", :aliases => "Chato,Shato,Chato", :latitude => "-2.63778", :longitude => "31.76694").save
City.new(:country_id => "229", :name => "Chanika", :aliases => ",Chanika", :latitude => "-5.41667", :longitude => "38.01667").save
City.new(:country_id => "229", :name => "Chalinze", :aliases => ",Chalinze", :latitude => "-6.6", :longitude => "38.35").save
City.new(:country_id => "229", :name => "Chala", :aliases => ",Chala", :latitude => "-7.58333", :longitude => "31.26667").save
City.new(:country_id => "229", :name => "Chake Chake", :aliases => "Chake Chake,Chaki Chaki,Chake Chake", :latitude => "-5.24586", :longitude => "39.76659").save
City.new(:country_id => "229", :name => "Butiama", :aliases => "Buliama,Butiama,Butiama", :latitude => "-1.76667", :longitude => "33.96667").save
City.new(:country_id => "229", :name => "Buseresere", :aliases => ",Buseresere", :latitude => "-3.02361", :longitude => "31.87472").save
City.new(:country_id => "229", :name => "Bungu", :aliases => "Bungu,Bungu", :latitude => "-7.63369", :longitude => "39.05818").save
City.new(:country_id => "229", :name => "Bunda", :aliases => ",Bunda", :latitude => "-2.05", :longitude => "33.86667").save
City.new(:country_id => "229", :name => "Bukoba", :aliases => "Bukoba,ÐÑÐºÐ¾Ð±Ð°,Bukoba", :latitude => "-1.33167", :longitude => "31.81222").save
City.new(:country_id => "229", :name => "Bugarama", :aliases => ",Bugarama", :latitude => "-2.87056", :longitude => "30.52806").save
City.new(:country_id => "229", :name => "Biharamulo", :aliases => "Biaramulo,Biharamulo,Usuwi,Biharamulo", :latitude => "-2.63194", :longitude => "31.30889").save
City.new(:country_id => "229", :name => "Basotu", :aliases => ",Basotu", :latitude => "-4.36667", :longitude => "35.08333").save
City.new(:country_id => "229", :name => "Bashanet", :aliases => "Bashanet,Endalaghanet,Endalaghranid,Bashanet", :latitude => "-4.23333", :longitude => "35.41667").save
City.new(:country_id => "229", :name => "Bariadi", :aliases => "Bariadi,Bariati,Bariadi", :latitude => "-2.8", :longitude => "33.98333").save
City.new(:country_id => "229", :name => "Bagamoyo", :aliases => "Bagamojo,Bagamoyo,Bagamoyo", :latitude => "-6.43333", :longitude => "38.9").save
City.new(:country_id => "229", :name => "Babati", :aliases => "Babati,Babati", :latitude => "-4.21667", :longitude => "35.75").save
City.new(:country_id => "229", :name => "Arusha", :aliases => "Aruscha,Arusha,Aruso,AruÅo,a lu sha,arusha,arwsha,ÐÑÑÑÐ°,Ø¢Ø±ÙØ´Ø§,ã¢ã«ã¼ã·ã£,é¿é²æ²,Arusha", :latitude => "-3.36667", :longitude => "36.68333").save
City.new(:country_id => "229", :name => "Tingi", :aliases => ",Tingi", :latitude => "-11.3", :longitude => "35.03333").save
City.new(:country_id => "229", :name => "Tandahimba", :aliases => ",Tandahimba", :latitude => "-10.75", :longitude => "39.63333").save
City.new(:country_id => "229", :name => "Songea", :aliases => "Songea,Ssongea,Ð¡Ð¾Ð½Ð³ÐµÐ°,Songea", :latitude => "-10.68333", :longitude => "35.65").save
City.new(:country_id => "229", :name => "Nyangao", :aliases => ",Nyangao", :latitude => "-10.33333", :longitude => "39.28333").save
City.new(:country_id => "229", :name => "Newala Kisimani", :aliases => ",Newala Kisimani", :latitude => "-10.95", :longitude => "39.28333").save
City.new(:country_id => "229", :name => "Nanyamba", :aliases => ",Nanyamba", :latitude => "-10.68333", :longitude => "39.83333").save
City.new(:country_id => "229", :name => "Nangomba", :aliases => ",Nangomba", :latitude => "-10.9", :longitude => "38.5").save
City.new(:country_id => "229", :name => "Nanganga", :aliases => ",Nanganga", :latitude => "-10.38333", :longitude => "39.15").save
City.new(:country_id => "229", :name => "Nachingwea", :aliases => "Nachingwa,Nachingwea,Nachingwea", :latitude => "-10.38333", :longitude => "38.76667").save
City.new(:country_id => "229", :name => "Mtwara", :aliases => "Mikindani,Mtvara,Mtwara,ÐÑÐ²Ð°ÑÐ°,Mtwara", :latitude => "-10.26667", :longitude => "40.18333").save
City.new(:country_id => "229", :name => "Mbinga", :aliases => ",Mbinga", :latitude => "-10.93333", :longitude => "35.01667").save
City.new(:country_id => "229", :name => "Matiri", :aliases => ",Matiri", :latitude => "-10.75", :longitude => "34.9").save
City.new(:country_id => "229", :name => "Masasi", :aliases => "Masasi,Massassi,ÐÐ°ÑÐ°ÑÐ¸,Masasi", :latitude => "-10.71667", :longitude => "38.8").save
City.new(:country_id => "229", :name => "Maposeni", :aliases => ",Maposeni", :latitude => "-10.58333", :longitude => "35.4").save
City.new(:country_id => "229", :name => "Lukuledi", :aliases => ",Lukuledi", :latitude => "-10.56667", :longitude => "38.8").save
City.new(:country_id => "229", :name => "Luchingu", :aliases => ",Luchingu", :latitude => "-10.9", :longitude => "39.33333").save
City.new(:country_id => "229", :name => "Lindi", :aliases => "Linda,Lindi,ÐÐ¸Ð½Ð´Ð°,Lindi", :latitude => "-10", :longitude => "39.71667").save
City.new(:country_id => "229", :name => "Kitama", :aliases => ",Kitama", :latitude => "-10.71667", :longitude => "39.73333").save
City.new(:country_id => "229", :name => "Kigonsera", :aliases => ",Kigonsera", :latitude => "-10.8", :longitude => "35.05").save
City.new(:country_id => "229", :name => "Merelani", :aliases => "Meralani,Merelani,Merelani Hills,Simanjiro district,Tanzanite Mine and Deposit,Merelani", :latitude => "-3.56182", :longitude => "36.97895").save
