City.new(:country_id => "230", :name => "Lebedyn", :aliases => "LEBEDIN,Lebedin,Lebedyn,ÐÐÐÐÐÐÐ,Lebedyn", :latitude => "50.58806", :longitude => "34.48028").save
City.new(:country_id => "230", :name => "Druzhkovka", :aliases => "DRUZHKOVKA,Druzhkovka,ÐÐ Ð£ÐÐÐÐÐÐ,Druzhkovka", :latitude => "48.61667", :longitude => "37.55").save
City.new(:country_id => "230", :name => "Vasylivka", :aliases => "Vasil'yevka,Vasilevka,Vasilivka,Vasilâyevka,Vasylivka,ÐÐ°ÑÐ¸Ð»ÑÐ²ÐºÐ°,Vasylivka", :latitude => "47.43694", :longitude => "35.27417").save
City.new(:country_id => "230", :name => "Zvenyhorodka", :aliases => "ZVENIGORODKA,Zvenigorodka,Zvenyhorodka,ÐÐÐÐÐÐÐÐ ÐÐÐÐ,Zvenyhorodka", :latitude => "49.08333", :longitude => "30.96667").save
City.new(:country_id => "230", :name => "Zuhres", :aliases => "ZUGREHS,Zugres,Zuhres,ÐÐ£ÐÐ Ð­Ð¡,ÐÑÐ³ÑÐµÑ,Zuhres", :latitude => "48.01639", :longitude => "38.26944").save
City.new(:country_id => "230", :name => "Zolotonosha", :aliases => "ZOLOTONOSHA,Zolotonosha,ÐÐÐÐÐ¢ÐÐÐÐ¨Ð,Zolotonosha", :latitude => "49.66667", :longitude => "32.03333").save
City.new(:country_id => "230", :name => "Zolochiv", :aliases => "Zlochev,Zlochuv,Zloczow,Zolochev,Zolochiv,Zolociv,ZÅoczÃ³w,ÐÐ¾Ð»Ð¾ÑÐµÐ²,ÐÐ¾Ð»Ð¾ÑÑÐ²,Zolochiv", :latitude => "49.8", :longitude => "24.9").save
City.new(:country_id => "230", :name => "Znomenka", :aliases => "Snamenka,ZNAMENKA,Znam'yanka,Znamenka,Znamenka Pervaya,Znamâyanka,Znomenka,ÐÐÐÐÐÐÐÐ,Znomenka", :latitude => "48.71278", :longitude => "32.66472").save
City.new(:country_id => "230", :name => "Zmiyev", :aliases => "Gottvald,Gotval'd,Gotvalâd,ZMIEV,Zmiev,Zmiiv,Zmiyev,Zmiyiv,ÐÐÐÐÐ,ÐÐ¼ÑÑÐ²,Zmiyev", :latitude => "49.7025", :longitude => "36.37694").save
City.new(:country_id => "230", :name => "Zhytomyr", :aliases => "Jitomir,Schytomyr,Shitomir,Zhitomir,Zhytomyr,Zitomir,Zjytomyr,Zsitomir,Zytomierz,Zytomyr,jitomileu,jitomiru,z'ytwmyr,Å»ytomierz,Å½itomir,Å½ytomyr,ÐÐ¸ÑÐ¾Ð¼Ð¸Ñ,×'××××××¨,ã¸ãã¼ãã«,ì§í ë¯¸ë¥´,Zhytomyr", :latitude => "50.25", :longitude => "28.66667").save
City.new(:country_id => "230", :name => "Zhmerynka", :aliases => "Zhmerinka,Zhmerynka,ÐÐ¼ÐµÑÐ¸Ð½ÐºÐ°,Zhmerynka", :latitude => "49.03333", :longitude => "28.1").save
City.new(:country_id => "230", :name => "Zhovti Vody", :aliases => "Rudnik Shvarts,Zheleznyy Rudnik Shvarts,Zheltaya Reka,Zheltye Vody,Zheltyye Vody,Zhovti Vody,ZhÃ«ltaya Reka,ZhÃ«ltyye Vody,Zovti Vodi,ÐÐµÐ»ÑÑÐµ ÐÐ¾Ð´Ñ,ÐÐ¾Ð²ÑÑ ÐÐ¾Ð´Ð¸,Zhovti Vody", :latitude => "48.34361", :longitude => "33.50778").save
City.new(:country_id => "230", :name => "Zhashkiv", :aliases => "ZHASHKOV,Zasashkhov,Zaskiv,Zhashkiv,Zhashkov,ÐÐÐ¨ÐÐÐ,ÐÐ°ÑÐºÑÐ²,Zhashkiv", :latitude => "49.25", :longitude => "30.1").save
City.new(:country_id => "230", :name => "Zdolbuniv", :aliases => "Zdolbuniv,Zdolbunov,Zdolbunovo,Zdolbunow,Zdolbunuv,ZdoÅbunÃ³w,ÐÐ´Ð¾Ð»Ð±ÑÐ½Ð¾Ð²,ÐÐ´Ð¾Ð»Ð±ÑÐ½ÑÐ²,Zdolbuniv", :latitude => "50.51667", :longitude => "26.25").save
City.new(:country_id => "230", :name => "Zaporizhzhya", :aliases => "Aleksandrovsk,Saporoshje,Zaborozha,Zaporizhzhya,Zaporizza,Zaporozh'e,Zaporozh'ye,Zaporozhâe,Zaporozhâye,ÐÐ°Ð¿Ð¾ÑÐ¾Ð¶ÑÐµ,ÐÐ°Ð¿Ð¾ÑÑÐ¶Ð¶Ñ,Zaporizhzhya", :latitude => "47.81667", :longitude => "35.18333").save
City.new(:country_id => "230", :name => "Yuzhne", :aliases => "Juzhne,Juzhnyj,Ð®Ð¶Ð½Ðµ,Ð®Ð¶Ð½ÑÐ¹,Yuzhne", :latitude => "46.62211", :longitude => "31.10131").save
City.new(:country_id => "230", :name => "Yevpatoriya", :aliases => "Eupatoria,Eupatorio,Evpatoria,Evpatorija,EÅ­patorio,Gazlevi,Jevpatorija,Jewpatorija,Kezlev,Kozlov,Yevpatoriya,ywwptwryh,ÐÐ²Ð¿Ð°ÑÐ¾ÑÑÑ,ÐÐ²Ð¿Ð°ÑÐ¾ÑÐ¸Ñ,Ð­Ð²Ð¿Ð°ÑÐ¾ÑÑÑ,××××¤×××¨××,Yevpatoriya", :latitude => "45.19575", :longitude => "33.35963").save
City.new(:country_id => "230", :name => "Yenakiyeve", :aliases => "ENAKIEVO,Ordshonikidse,Ordzhonikidze,Rykovo,Yenakiyeve,Yenakiyevo,ÐÐÐÐÐÐÐÐ,Yenakiyeve", :latitude => "48.23222", :longitude => "38.21611").save
City.new(:country_id => "230", :name => "Yasinovataya", :aliases => "IAsinovataia,Jasinovataja,Yasinovatara,Yasinovataya,Ð¯ÑÐ¸Ð½Ð¾Ð²Ð°ÑÐ°Ñ,Yasinovataya", :latitude => "48.135", :longitude => "37.85028").save
City.new(:country_id => "230", :name => "Yalta", :aliases => "Ialta,Jalta,Jalto,JaÅta,Yalta,ya er ta,yalta,yaruta,Ð¯Ð»ÑÐ°,ÙØ§ÙØ·Ø§,áááá¢á,ã¤ã«ã¿,éå°å¡,ìí,Yalta", :latitude => "44.5", :longitude => "34.16667").save
City.new(:country_id => "230", :name => "Yahotyn", :aliases => "JAGOTIN,Yagotin,Yahotyn,Ð¯ÐÐÐ¢ÐÐ,Yahotyn", :latitude => "50.28333", :longitude => "31.76667").save
City.new(:country_id => "230", :name => "Vyshhorod", :aliases => "VYSHGOROD,Vishgorod,Vyshgorod,Vyshhorod,ÐÐ«Ð¨ÐÐÐ ÐÐ,ÐÐ¸ÑÐ³Ð¾ÑÐ¾Ð´,Vyshhorod", :latitude => "50.58333", :longitude => "30.5").save
City.new(:country_id => "230", :name => "Vynohradiv", :aliases => "Horvinogradovo,Nagyszollos,NagyszÃ¶llÃ¶s,NagyszÅllÅs,Sevljus,Sevlus,SevluÅ¡,Sevlyush,Vel'ky Sevl'yush,Velâky Sevlâyush,Vinogradiv,Vinogradov,Vynohradiv,ÐÐ¸Ð½Ð¾Ð³ÑÐ°Ð´Ð¾Ð²,ÐÐ¸Ð½Ð¾Ð³ÑÐ°Ð´ÑÐ²,Vynohradiv", :latitude => "48.15", :longitude => "22.76667").save
City.new(:country_id => "230", :name => "Voznesensk", :aliases => "Voznesen's'k,Voznesensk,ÐÐ¾Ð·Ð½ÐµÑÐµÐ½ÑÐº,ÐÐ¾Ð·Ð½ÐµÑÐµÐ½ÑÑÑÐº,Voznesensk", :latitude => "47.56494", :longitude => "31.33078").save
City.new(:country_id => "230", :name => "Volnovakha", :aliases => "VOLNOVAKHA,Volnovakha,Volovakha,Wolnowacha,ÐÐÐÐÐÐÐÐ¥Ð,Volnovakha", :latitude => "47.6", :longitude => "37.5").save
City.new(:country_id => "230", :name => "Vovchans'k", :aliases => "VOLCHANSK,Volchansk,Vovchans'k,Vovchansâk,Woltschansk,ÐÐÐÐ§ÐÐÐ¡Ð,ÐÐ¾Ð²ÑÐ°Ð½ÑÑÐº,Vovchansâk", :latitude => "50.28838", :longitude => "36.94198").save
City.new(:country_id => "230", :name => "Volodymyr-Volyns'kyy", :aliases => "Vladimir,Vladimir-Volynsk,Vladimir-Volynskij,Vladimir-Volynskiy,Vlodzimezh,Volodimir-Volins'kij,Volodymir-Volyns'kyy,Volodymir-Volynsâkyy,Volodymyr-Volyns'kyy,Volodymyr-Volynsâkyy,Wladimir-Wolynsk,Wlodzimierz,Wlodzimierz Wolynski,Wlodzimierzec,WÅodzimierz,WÅodzimierz WoÅyÅski,WÅodzimierzec,ÐÐ»Ð°Ð´Ð¸Ð¼Ð¸Ñ-ÐÐ¾Ð»ÑÐ½ÑÐºÐ¸Ð¹,ÐÐ¾Ð»Ð¾Ð´Ð¸Ð¼Ð¸Ñ-ÐÐ¾Ð»Ð¸Ð½ÑÑÐºÐ¸Ð¹,Volodymyr-Volynsâkyy", :latitude => "50.85", :longitude => "24.33333").save
City.new(:country_id => "230", :name => "Vyshneve", :aliases => "VISHNEVOE,Vishneve,Vishnevoye,VishnÃ«voye,Vyshneve,ÐÐÐ¨ÐÐÐÐÐ,ÐÐ¸ÑÐ½ÐµÐ²Ðµ,Vyshneve", :latitude => "50.38333", :longitude => "30.36667").save
City.new(:country_id => "230", :name => "Vinnytsya", :aliases => "Vinnica,Vinnitsa,Vinnytsya,Winniza,ÐÐ¸Ð½Ð½Ð¸ÑÐ°,ÐÑÐ½Ð½Ð¸ÑÑ,Vinnytsya", :latitude => "49.23333", :longitude => "28.48333").save
City.new(:country_id => "230", :name => "Vatutine", :aliases => "VATUTINO,Vatutine,Vatutino,ÐÐÐ¢Ð£Ð¢ÐÐÐ,ÐÐ°ÑÑÑÑÐ½Ðµ,Vatutine", :latitude => "49.01778", :longitude => "31.06222").save
City.new(:country_id => "230", :name => "Vasyl'kiv", :aliases => "VASIL'KOV,Vasil'kov,Vasilikov,Vasilâkov,Vasyl'kiv,Vasylâkiv,Wassilkow,ÐÐÐ¡ÐÐÐ¬ÐÐÐ,Vasylâkiv", :latitude => "50.18333", :longitude => "30.31667").save
City.new(:country_id => "230", :name => "Uzhhorod", :aliases => "Oujhorod,Ungvar,UngvÃ¡r,Uschhorod,Uzgorod,Uzhgorod,Uzhhorod,Uzhorod,UÅ¼horod,UÅ¾gorod,UÅ¾horod,Ð£Ð¶Ð³Ð¾ÑÐ¾Ð´,××× ××°××¨,Uzhhorod", :latitude => "48.61667", :longitude => "22.3").save
City.new(:country_id => "230", :name => "Uman'", :aliases => "Uman',Umanâ,Ð£Ð¼Ð°Ð½Ñ,Umanâ", :latitude => "48.75", :longitude => "30.22222").save
City.new(:country_id => "230", :name => "Tul'chyn", :aliases => "Tu'chin,Tul'chin,Tul'chyn,Tultschin,Tulâchyn,Tuâchin,Ð¢ÑÐ»ÑÑÐ¸Ð½,Tulâchyn", :latitude => "48.68148", :longitude => "28.86705").save
City.new(:country_id => "230", :name => "Tsyurupyns'k", :aliases => "Aleshki,Cjurupinsk,Tsyurupinsk,Tsyurupyns'k,Tsyurupynsâk,Ð¦ÑÑÑÐ¿Ð¸Ð½ÑÐº,Tsyurupynsâk", :latitude => "46.61639", :longitude => "32.71139").save
City.new(:country_id => "230", :name => "Truskavets", :aliases => "Truskavec,Truskavets,Truskawiec,Ð¢ÑÑÑÐºÐ°Ð²ÐµÑ,Truskavets", :latitude => "49.28333", :longitude => "23.5").save
City.new(:country_id => "230", :name => "Torez", :aliases => "Chistyakovo,Torez,Tschistjakowa,Tschistjakowo,Ð¢Ð¾ÑÐµÐ·,Torez", :latitude => "48.03833", :longitude => "38.58778").save
City.new(:country_id => "230", :name => "Tokmak", :aliases => "Bol'shoy Tokmak,Bolâshoy Tokmak,Tokmak,Tomak,Ð¢Ð¾ÐºÐ¼Ð°Ðº,Tokmak", :latitude => "47.25139", :longitude => "35.70583").save
City.new(:country_id => "230", :name => "Ternopil'", :aliases => "Tarnopol,Tarnopol',Tarnopolâ,Ternopil,Ternopil',Ternopilo,Ternopilâ,Ternopol',Ternopolâ,trnwpwl,Ð¢ÐµÑÐ½Ð¾Ð¿Ð¾Ð»Ñ,Ð¢ÐµÑÐ½Ð¾Ð¿ÑÐ»Ñ,××¨× ××¤××,Ternopilâ", :latitude => "49.5516", :longitude => "25.60875").save
City.new(:country_id => "230", :name => "Syeverodonets'k", :aliases => "SEVERODONECK,Severodonec'k,Severodonetsk,Syeverodonets'k,Syeverodonetsâk,Ð¡ÐÐÐÐ ÐÐÐÐÐÐ¦Ð,Ð¡ÑÐ²ÑÑÐ¾Ð´Ð¾Ð½ÐµÑÑÐº,Syeverodonetsâk", :latitude => "48.94556", :longitude => "38.50222").save
City.new(:country_id => "230", :name => "Svitlovods'k", :aliases => "Khrushchev,KhrushchÃ«v,Kremges,Krylov,Novogeorgievsk,Novogeorgiyevsk,SVETLOVODSK,Svetlovodsk,Svitlovods'k,Svitlovodsâk,Ð¡ÐÐÐ¢ÐÐÐÐÐÐ¡Ð,Svitlovodsâk", :latitude => "49.08333", :longitude => "33.25").save
City.new(:country_id => "230", :name => "Sverdlovs'k", :aliases => "Imeni Sverdlova,Selo Imeni Sverdlova,Selo imeni Sverdlova,Sverdlovs'k,Sverdlovsk,Sverdlovsâk,Ð¡Ð²ÐµÑÐ´Ð»Ð¾Ð²ÑÐº,Ð¡ÐµÐ»Ð¾ Ð¸Ð¼ÐµÐ½Ð¸ Ð¡Ð²ÐµÑÐ´Ð»Ð¾Ð²Ð°,Sverdlovsâk", :latitude => "48.07667", :longitude => "39.65333").save
City.new(:country_id => "230", :name => "Svatove", :aliases => "SVATOVO,Svatove,Svatovo,Swatowo,Ð¡ÐÐÐ¢ÐÐÐ,Ð¡Ð²Ð°ÑÐ¾Ð²Ðµ,Svatove", :latitude => "49.41222", :longitude => "38.15083").save
City.new(:country_id => "230", :name => "Svalyava", :aliases => "Svalava,Svaljava,Svalva,Svalyava,Ð¡Ð²Ð°Ð»ÑÐ²Ð°,Svalyava", :latitude => "48.55", :longitude => "22.98333").save
City.new(:country_id => "230", :name => "Sumy", :aliases => "Soemy,Sumi,Sumy,sumu~i,swmy,Ð¡ÑÐ¼Ð¸,Ð¡ÑÐ¼Ñ,×¡×××,Ø³ÙÙÙ,ã¹ã ã£,Sumy", :latitude => "50.91972", :longitude => "34.78194").save
City.new(:country_id => "230", :name => "Stryy", :aliases => "Strij,Stry,Stryj,Stryy,Ð¡ÑÑÐ¸Ð¹,Stryy", :latitude => "49.25", :longitude => "23.85").save
City.new(:country_id => "230", :name => "Stebnik", :aliases => "Stebnik,Stebniki,Stebnyk,Ð¡ÑÐµÐ±Ð½Ð¸Ðº,Stebnik", :latitude => "49.3", :longitude => "23.56667").save
City.new(:country_id => "230", :name => "Starokostyantyniv", :aliases => "Starokonstantinov,Starokonstantinow,Starokostantiniv,Starokostyantyniv,Ð¡ÑÐ°ÑÐ¾ÐºÐ¾Ð½ÑÑÐ°Ð½ÑÐ¸Ð½Ð¾Ð²,Ð¡ÑÐ°ÑÐ¾ÐºÐ¾ÑÑÑÐ½ÑÐ¸Ð½ÑÐ²,Starokostyantyniv", :latitude => "49.75", :longitude => "27.21667").save
City.new(:country_id => "230", :name => "Starobil's'k", :aliases => "Bel'skiy Gorodok,Belâskiy Gorodok,STAROBEL'SK,Staraya Belaya,Starobel'sk,Starobelâsk,Starobil's'k,Starobilâsâk,Ð¡Ð¢ÐÐ ÐÐÐÐÐ¬Ð¡Ð,Starobilâsâk", :latitude => "49.27639", :longitude => "38.90583").save
City.new(:country_id => "230", :name => "Stakhanov", :aliases => "Kadijewka,Kadiyevka,STAKHANOV,Ssergo,Stachanow,Stakhanov,Ð¡Ð¢ÐÐ¥ÐÐÐÐ,Ð¡ÑÐ°ÑÐ°Ð½Ð¾Ð²,Stakhanov", :latitude => "48.56333", :longitude => "38.65083").save
City.new(:country_id => "230", :name => "Sokal'", :aliases => "Sokal',Sokalâ,Ð¡Ð¾ÐºÐ°Ð»Ñ,Sokalâ", :latitude => "50.48333", :longitude => "24.28333").save
City.new(:country_id => "230", :name => "Snizhne", :aliases => "SNEZHNOE,Shezhnoye,Snezhnoye,Snizhne,Snizne,Ð¡ÐÐÐÐÐÐ,Ð¡Ð½ÑÐ¶Ð½Ðµ,Snizhne", :latitude => "48.01694", :longitude => "38.76583").save
City.new(:country_id => "230", :name => "Smila", :aliases => "SMELA,Smela,Smila,Ð¡ÐÐÐÐ,Ð¡Ð¼ÑÐ»Ð°,Smila", :latitude => "49.23333", :longitude => "31.88333").save
City.new(:country_id => "230", :name => "Sloviansk", :aliases => "Slavjansk,Slavyansk,Slawjansk,Sloviansk,Slovâyans'k,Ð¡Ð»Ð°Ð²ÑÐ½ÑÐº,Sloviansk", :latitude => "48.86667", :longitude => "37.61667").save
City.new(:country_id => "230", :name => "Slavuta", :aliases => "Slavuta,Slawuta,Sslawuta,Ð¡Ð»Ð°Ð²ÑÑÐ°,Slavuta", :latitude => "50.3", :longitude => "26.86667").save
City.new(:country_id => "230", :name => "Skvyra", :aliases => "Skvira,Skvyra,Ð¡ÐºÐ²Ð¸ÑÐ°,Skvyra", :latitude => "49.73333", :longitude => "29.66667").save
City.new(:country_id => "230", :name => "Skadovs'k", :aliases => "Skadovs'k,Skadovsk,Skadovsâk,Skadowsk,Ð¡ÐºÐ°Ð´Ð¾Ð²ÑÐº,Skadovsâk", :latitude => "46.11667", :longitude => "32.91667").save
City.new(:country_id => "230", :name => "Synel'nykove", :aliases => "Sinel'nikovo,Sinelânikovo,Synel'nykove,Synelânykove,Ð¡Ð¸Ð½ÐµÐ»ÑÐ½Ð¸ÐºÐ¾Ð²Ð¾,Synelânykove", :latitude => "48.33333", :longitude => "35.51667").save
City.new(:country_id => "230", :name => "Simferopol'", :aliases => "Ak-Mechet,Akmescit,Aqmescit,Simferopol,Simferopol',Simferopoli,Simferopolo,Simferopolâ,Ssimferopol,Symferopol,shinferopori,smfrwbl,symprwpwl,xin fei luo bo er,Ð¡Ð¸Ð¼ÑÐµÑÐ¾Ð¿Ð¾Ð»,Ð¡Ð¸Ð¼ÑÐµÑÐ¾Ð¿Ð¾Ð»Ñ,Ð¡ÑÐ¼ÑÐµÑÐ¾Ð¿Ð¾Ð»Ñ,×¡×××¤×¨××¤××,Ø³ÙÙØ±ÙØ¨Ù,ã·ã³ãã§ã­ããª,è¾è²ç½æ³¢å°,Simferopolâ", :latitude => "44.95844", :longitude => "34.10558").save
City.new(:country_id => "230", :name => "Shpola", :aliases => "Shpola,Ð¨Ð¿Ð¾Ð»Ð°,Shpola", :latitude => "49.00389", :longitude => "31.39167").save
City.new(:country_id => "230", :name => "Shostka", :aliases => "SHOSTKA,Schostka,Shostka,Ð¨ÐÐ¡Ð¢ÐÐ,Ð¨Ð¾ÑÑÐºÐ°,Shostka", :latitude => "51.86667", :longitude => "33.48333").save
City.new(:country_id => "230", :name => "Shepetivka", :aliases => "Schepetowka,Sepetivka,Shepetivka,Shepetovka,Ð¨ÐµÐ¿ÐµÑÐ¾Ð²ÐºÐ°,Ð¨ÐµÐ¿ÐµÑÑÐ²ÐºÐ°,Shepetivka", :latitude => "50.18333", :longitude => "27.06667").save
City.new(:country_id => "230", :name => "Shakhtersk", :aliases => "Katyk,Shakhtersk,ShakhtÃ«rsk,Zapadno-Gruppskiy,Ð¨Ð°ÑÑÐµÑÑÐº,ShakhtÃ«rsk", :latitude => "48.04694", :longitude => "38.46861").save
City.new(:country_id => "230", :name => "Sevastopol'", :aliases => "Akhiar,Akhtyar,Akyar,Aqyar,Sebastopol,Sebastopoli,Sebastopolis,Sebastopolo,SebastÃ²pol,Sevastopol,Sevastopol',Sevastopolis,Sevastopolo,Sevastopolâ,SevastopoÄ¾,Sewastopol,Sivastopol,SÃ©bastopol,sai wa si tuo bo er,sbstwpwl,sebaseutopol,sevu~asutopori,Ð¡ÐµÐ²Ð°ÑÑÐ¾Ð¿Ð¾Ð»,Ð¡ÐµÐ²Ð°ÑÑÐ¾Ð¿Ð¾Ð»Ñ,×¡××¡×××¤××,ã»ã´ã¡ã¹ãããª,å¡ç¦æ¯ææ³¢ç¾,ì¸ë°ì¤í í´,Sevastopolâ", :latitude => "44.58883", :longitude => "33.5224").save
City.new(:country_id => "230", :name => "Sarny", :aliases => "Sarni,Sarnv,Sarny,Ð¡Ð°ÑÐ½Ð¸,Sarny", :latitude => "51.33333", :longitude => "26.6").save
City.new(:country_id => "230", :name => "Sambir", :aliases => "Sambir,Sambor,Ð¡Ð°Ð¼Ð±Ð¾Ñ,Ð¡Ð°Ð¼Ð±ÑÑ,Sambir", :latitude => "49.51667", :longitude => "23.2").save
City.new(:country_id => "230", :name => "Saky", :aliases => "Saki,Saky,Ssaki,Ð¡Ð°ÐºÐ¸,Saky", :latitude => "45.13327", :longitude => "33.59408").save
City.new(:country_id => "230", :name => "Rubizhne", :aliases => "Rubezhnaya,Rubezhnoe,Rubezhnoye,Rubizhne,Rubizne,Ð ÑÐ±ÐµÐ¶Ð½Ð¾Ðµ,Ð ÑÐ±ÑÐ¶Ð½Ðµ,Rubizhne", :latitude => "49.01583", :longitude => "38.36694").save
City.new(:country_id => "230", :name => "Rozdil'na", :aliases => "Posad Pazdelnaya,Razdel'naja,Razdel'naya,Razdelânaya,Ð Ð°Ð·Ð´ÐµÐ»ÑÐ½Ð°Ñ,Rozdilâna", :latitude => "46.84334", :longitude => "30.07919").save
City.new(:country_id => "230", :name => "Roven'ki", :aliases => "Roven'ki,Rovenki,Rovenâki,Rowenki,Ð Ð¾Ð²ÐµÐ½ÑÐºÐ¸,Rovenâki", :latitude => "48.08222", :longitude => "39.36694").save
City.new(:country_id => "230", :name => "Romny", :aliases => "ROMNY,Rommy,Romni,Romny,lomni,romunu~i,Ð ÐÐÐÐ«,Ð Ð¾Ð¼Ð½Ð¸,Ð Ð¾Ð¼Ð½Ñ,ã­ã ãã£,ë¡¬ë,Romny", :latitude => "50.75", :longitude => "33.46667").save
City.new(:country_id => "230", :name => "Rivne", :aliases => "Rivne,Riwne,Rovno,Rowne,Ruvne,RÃ³wne,rivune,rwbnw,Ð Ð¾Ð²Ð½Ð¾,Ð ÑÐ²Ð½Ðµ,×¨××× ×,ãªã´ã,Rivne", :latitude => "50.61667", :longitude => "26.25").save
City.new(:country_id => "230", :name => "Reni", :aliases => "Reni,Ð ÐµÐ½Ñ,Reni", :latitude => "45.45", :longitude => "28.28333").save
City.new(:country_id => "230", :name => "Radomyshl'", :aliases => "Radomishl,Radomyshl',Radomyshlâ,Ð Ð°Ð´Ð¾Ð¼ÑÑÐ»Ñ,Radomyshlâ", :latitude => "50.5", :longitude => "29.23333").save
City.new(:country_id => "230", :name => "Piatykhatky", :aliases => "P'yatykhatky,Pitikhatki,Pjatichatka,Pjatichatki,Pjatikhatki,Pyatikhatka,Pyatikhatki,ÐÑÑÐ¸ÑÐ°ÑÐºÐ¸,Piatykhatky", :latitude => "48.41333", :longitude => "33.71056").save
City.new(:country_id => "230", :name => "Putyvl'", :aliases => "Putivl',Putivlâ,Putyvl',Putyvlâ,ÐÑÑÐ¸Ð²Ð»Ñ,Putyvlâ", :latitude => "51.33333", :longitude => "33.86667").save
City.new(:country_id => "230", :name => "Pryluky", :aliases => "PRILUKI,Priluki,Pryluki,Pryluky,PryÅuki,ÐÐ ÐÐÐ£ÐÐ,ÐÑÐ¸Ð»ÑÐºÐ¸,Pryluky", :latitude => "50.6", :longitude => "32.4").save
City.new(:country_id => "230", :name => "Popasnaya", :aliases => "Imeni Kaganovicha,Imeni L.M. Kaganovicha,Kaganovich,Kaganowitsch,Popasnaja,Popasnaya,ÐÐ¾Ð¿Ð°ÑÐ½Ð°Ñ,Popasnaya", :latitude => "48.62917", :longitude => "38.38333").save
City.new(:country_id => "230", :name => "Poltava", :aliases => "POLTAVA,Poltava,Poltawa,PoÅtawa,Pultava,bo er ta wa,poltaba,porutavu~a,pwltbh,ÐÐÐÐ¢ÐÐÐ,ÐÐ¾Ð»ÑÐ°Ð²Ð°,×¤×××××,ãã«ã¿ã´ã¡,æ³¢å°å¡ç¦,í´íë°,Poltava", :latitude => "49.58333", :longitude => "34.56667").save
City.new(:country_id => "230", :name => "Polonne", :aliases => "Pollonoye,Polonne,Polonnoje,Polonnoye,ÐÐ¾Ð»Ð¾Ð½Ð½Ðµ,Polonne", :latitude => "50.11667", :longitude => "27.51667").save
City.new(:country_id => "230", :name => "Polohy", :aliases => "Chubarovka,POLOGI,Pologi,Polohy,ÐÐÐÐÐÐ,Polohy", :latitude => "47.48444", :longitude => "36.25361").save
City.new(:country_id => "230", :name => "Pidhorodne", :aliases => "PODGORODNOE,Pidgorodne,Pidhorodne,Podgorodnoye,ÐÐÐÐÐÐ ÐÐÐÐÐ,ÐÑÐ´Ð³Ð¾ÑÐ¾Ð´Ð½Ðµ,Pidhorodne", :latitude => "48.58333", :longitude => "35.11667").save
City.new(:country_id => "230", :name => "Pyryatyn", :aliases => "PIRJATIN,Piryatin,Pyryatin,Pyryatyn,ÐÐÐ Ð¯Ð¢ÐÐ,Pyryatyn", :latitude => "50.25", :longitude => "32.51667").save
City.new(:country_id => "230", :name => "Pervomaysk", :aliases => "Pervomaika,Pervomaisk,Pervomajs'k,Pervomajsk,Pervomaysk,ÐÐµÑÐ²Ð¾Ð¼Ð°Ð¹ÑÐº,ÐÐµÑÐ²Ð¾Ð¼Ð°Ð¹ÑÑÐº,Pervomaysk", :latitude => "48.62833", :longitude => "38.55583").save
City.new(:country_id => "230", :name => "Pervomays'k", :aliases => "Ol'viopol',Olwiopol,Olâviopolâ,Pervomaisk,Pervomajsk,Pervomays'k,Pervomaysâk,Perwomaisk,ÐÐµÑÐ²Ð¾Ð¼Ð°Ð¹ÑÐº,Pervomaysâk", :latitude => "48.04722", :longitude => "30.85028").save
City.new(:country_id => "230", :name => "Pereyaslav-Khmel'nyts'kyy", :aliases => "Perejaslav-Khmel'nickij,Perejaslawl,Pereyaslav,Pereyaslav-Khmel'nitskiy,Pereyaslav-Khmel'nyts'kyy,Pereyaslav-Khmelânitskiy,Pereyaslav-Khmelânytsâkyy,ÐÐµÑÐµÑÑÐ»Ð°Ð²-Ð¥Ð¼ÐµÐ»ÑÐ½Ð¸ÑÐºÐ¸Ð¹,Pereyaslav-Khmelânytsâkyy", :latitude => "50.08333", :longitude => "31.46667").save
City.new(:country_id => "230", :name => "Pereval'sk", :aliases => "PEREVAL'SK,Pereval'sk,Perevalâsk,ÐÐÐ ÐÐÐÐÐ¬Ð¡Ð,Perevalâsk", :latitude => "48.43917", :longitude => "38.81556").save
City.new(:country_id => "230", :name => "Pavlohrad", :aliases => "PAVLOGRAD,Pavlogi,Pavlograd,Pavlohrad,Pawlograd,ÐÐÐÐÐÐÐ ÐÐ,ÐÐ°Ð²Ð»Ð¾Ð³ÑÐ°Ð´,Pavlohrad", :latitude => "48.51667", :longitude => "35.86667").save
City.new(:country_id => "230", :name => "Ovruch", :aliases => "Ovruch,Owrutsch,ÐÐ²ÑÑÑ,Ovruch", :latitude => "51.31667", :longitude => "28.8").save
City.new(:country_id => "230", :name => "Orikhiv", :aliases => "Orechoff,Orechowka,Orekhov,Orihiv,Orikhiv,ÐÑÑÑÑÐ²,Orikhiv", :latitude => "47.56556", :longitude => "35.78861").save
City.new(:country_id => "230", :name => "Oleksandriya", :aliases => "ALEKSANDRIJA,Aleksandria,Aleksandriya,Alexandrija Pervaya,Oleksandrija,Oleksandriya,ÐÐÐÐÐ¡ÐÐÐÐ ÐÐ¯,ÐÐ»ÐµÐºÑÐ°Ð½Ð´ÑÐ¸Ñ,Oleksandriya", :latitude => "48.66972", :longitude => "33.12056").save
City.new(:country_id => "230", :name => "Odesa", :aliases => "Adehsa,Odesa,Odeso,Odessa,Odessos,Odessus,OdÄsa,ao de sa,odesa,odessa,ÎÎ´Î·ÏÏÏÏ,ÐÐ´ÑÑÐ°,ÐÐ´ÐµÑÐ°,ÐÐ´ÐµÑÑÐ°,ÕÕ¤Õ¥Õ½Õ¡,××××¡×,áááá¡á,ãªãããµ,æå¾·è©,ì¤ë°ì¬,Odesa", :latitude => "46.47747", :longitude => "30.73262").save
City.new(:country_id => "230", :name => "Ochakiv", :aliases => "Ocakiv,Ochakiv,Ochakov,Otschakow,ÐÑÐ°ÐºÑÐ²,Ochakiv", :latitude => "46.61667", :longitude => "31.55").save
City.new(:country_id => "230", :name => "Obukhiv", :aliases => "OBUKHOV,Obuhiv,Obukhiv,Obukhov,ÐÐÐ£Ð¥ÐÐ,ÐÐ±ÑÑÑÐ²,Obukhiv", :latitude => "50.1", :longitude => "30.63333").save
City.new(:country_id => "230", :name => "Novyy Buh", :aliases => "Novi Bug,Novij Bug,Novo Bug,Novy Bug,Novyy Bug,Novyy Buh,Nowyi Bug,ÐÐ¾Ð²Ð¸Ð¹ ÐÑÐ³,Novyy Buh", :latitude => "47.68333", :longitude => "32.5").save
City.new(:country_id => "230", :name => "Novovolyns'k", :aliases => "Novovolyns'k,Novovolynsk,Novovolynskiy,Novovolynsâk,ÐÐ¾Ð²Ð¾Ð²Ð¾Ð»ÑÐ½ÑÐº,Novovolynsâk", :latitude => "50.73333", :longitude => "24.16667").save
City.new(:country_id => "230", :name => "Novoukrayinka", :aliases => "NOVOUKRAINKA,Novo-Urainka,Novoukrainka,Novoukrainsk,Novoukrayinka,ÐÐÐÐÐ£ÐÐ ÐÐÐÐÐ,ÐÐ¾Ð²Ð¾ÑÐºÑÐ°ÑÐ½ÐºÐ°,Novoukrayinka", :latitude => "48.32167", :longitude => "31.52028").save
City.new(:country_id => "230", :name => "Novomoskovs'k", :aliases => "Novomoskovs'k,Novomoskovsk,Novomoskovsâk,ÐÐ¾Ð²Ð¾Ð¼Ð¾ÑÐºÐ¾Ð²ÑÐº,Novomoskovsâk", :latitude => "48.61667", :longitude => "35.2").save
City.new(:country_id => "230", :name => "Novohrad-Volyns'kyy", :aliases => "Novograd Volynski,Novograd-Volynsk,Novograd-Volynskij,Novograd-Volynskiy,Novohrad-Volyns'kyy,Novohrad-Volynsâkyy,Nowograd Wolynsk,Zvyagel',Zvyagelâ,Zvydgel,Zwiahl,ÐÐ¾Ð²Ð¾Ð³ÑÐ°Ð´-ÐÐ¾Ð»ÑÐ½ÑÐºÐ¸Ð¹,Novohrad-Volynsâkyy", :latitude => "50.6", :longitude => "27.61667").save
City.new(:country_id => "230", :name => "Nova Kakhovka", :aliases => "Nova Kakhovka,Novaya Kakhova,Novaya Kakhovka,Novo Kakhovka,ÐÐ¾Ð²Ð° ÐÐ°ÑÐ¾Ð²ÐºÐ°,Nova Kakhovka", :latitude => "46.75083", :longitude => "33.38028").save
City.new(:country_id => "230", :name => "Nosivka", :aliases => "NOSOVKA,Nosivka,Nosovka,Nosowka,ÐÐÐ¡ÐÐÐÐ,ÐÐ¾ÑÑÐ²ÐºÐ°,Nosivka", :latitude => "50.93333", :longitude => "31.58333").save
City.new(:country_id => "230", :name => "Nizhyn", :aliases => "NEZHIN,Neshin,Nezhin,Niezyn,NieÅ¼yn,Nijino,Nischyn,Nizhin,Nizhyn,Nizin,NiÄµino,NiÅ¾in,ÐÐÐÐÐ,ÐÐµÐ¶Ð¸Ð½,ÐÑÐ¶Ð¸Ð½,Nizhyn", :latitude => "51.05", :longitude => "31.88333").save
City.new(:country_id => "230", :name => "Nyzhn'ohirs'kyy", :aliases => "Nizhnegorskij,Nizhnegorskiy,Nyzhn'ohirs'kyy,Nyzhnâohirsâkyy,Seitler,Seytler,Sseitler,ÐÐ¸Ð¶Ð½ÐµÐ³Ð¾ÑÑÐºÐ¸Ð¹,Nyzhnâohirsâkyy", :latitude => "45.45082", :longitude => "34.73953").save
City.new(:country_id => "230", :name => "Nikopol'", :aliases => "Nikopol',Nikopolâ,ÐÐ¸ÐºÐ¾Ð¿Ð¾Ð»Ñ,Nikopolâ", :latitude => "47.56667", :longitude => "34.4").save
City.new(:country_id => "230", :name => "Netishyn", :aliases => "Neteshin,Netishin,Netishyn,Netisin,Solov'ye Goryn',Solovâye Gorynâ,ÐÐµÑÐµÑÐ¸Ð½,ÐÐµÑÑÑÐ¸Ð½,Netishyn", :latitude => "50.35", :longitude => "26.63333").save
City.new(:country_id => "230", :name => "Nadvirna", :aliases => "Naduvrna,Nadvirna,Nadvorna,Nadvornaja,Nadvornaya,Nadworna,ÐÐ°Ð´Ð²Ð¾ÑÐ½Ð°Ñ,ÐÐ°Ð´Ð²ÑÑÐ½Ð°,Nadvirna", :latitude => "48.63", :longitude => "24.57694").save
City.new(:country_id => "230", :name => "Mykolayiv", :aliases => "Mykolayiv,Nikolaev,Nikolajew,Nikolayev,Vernoleninsk,ÐÐ¸ÐºÐ¾Ð»Ð°ÐµÐ²,Mykolayiv", :latitude => "46.96667", :longitude => "32").save
City.new(:country_id => "230", :name => "Mukacheve", :aliases => "Mikachevo,Mukaceve,Mukacevo,Mukacheve,Mukachevo,Mukaczewo,Mukatschewe,MukaÄeve,MukaÄevo,Munkacevo,Munkachevo,Munkacs,MunkaÄevo,MunkÃ¡cs,ÐÑÐºÐ°ÑÐµÐ²Ðµ,ÐÑÐºÐ°ÑÐµÐ²Ð¾,××× ×§×××©,××× ×§××¥',Mukacheve", :latitude => "48.45", :longitude => "22.71667").save
City.new(:country_id => "230", :name => "Molodogvardeysk", :aliases => "Molodogvardejsk,Molodogvardejskoe,Molodogvardeysk,Molodogvardeyskoye,ÐÐ¾Ð»Ð¾Ð´Ð¾Ð³Ð²Ð°ÑÐ´ÐµÐ¹ÑÐº,ÐÐ¾Ð»Ð¾Ð´Ð¾Ð³Ð²Ð°ÑÐ´ÐµÐ¹ÑÐºÐ¾Ðµ,Molodogvardeysk", :latitude => "48.34972", :longitude => "39.72778").save
City.new(:country_id => "230", :name => "Mohyliv-Podil's'kyy", :aliases => "Mogilev-Podol'skij,Mogilev-Podol'skiy,Mogilov Podolski,MogilÃ«v-Podolâskiy,Mohyliv-Podil's'kyy,Mohyliv-Podilâsâkyy,ÐÐ¾Ð³Ð¸Ð»ÐµÐ²-ÐÐ¾Ð´Ð¾Ð»ÑÑÐºÐ¸Ð¹,Mohyliv-Podilâsâkyy", :latitude => "48.45", :longitude => "27.8").save
City.new(:country_id => "230", :name => "Miskhor", :aliases => "Miskhor,ÐÐ¸ÑÑÐ¾Ñ,Miskhor", :latitude => "44.43333", :longitude => "34.08333").save
City.new(:country_id => "230", :name => "Myrhorod", :aliases => "MIRGOROD,Mirgorod,Myrhorod,ÐÐÐ ÐÐÐ ÐÐ,Myrhorod", :latitude => "49.96667", :longitude => "33.6").save
City.new(:country_id => "230", :name => "Merefa", :aliases => "MEREFA,Meref,Merefa,ÐÐÐ ÐÐ¤Ð,Merefa", :latitude => "49.81972", :longitude => "36.05194").save
City.new(:country_id => "230", :name => "Melitopol'", :aliases => "Melitopol,Melitopol',Melitopolâ,mellitopol,ÐÐµÐ»Ð¸ÑÐ¾Ð¿Ð¾Ð»Ñ,ÐÐµÐ»ÑÑÐ¾Ð¿Ð¾Ð»Ñ,ë©ë¦¬í í´,Melitopolâ", :latitude => "46.84222", :longitude => "35.37306").save
City.new(:country_id => "230", :name => "Mariupol'", :aliases => "Mariupol,Mariupol',Zhdanov,ÐÐ´Ð°Ð½Ð¾Ð²,ÐÐ°ÑÐ¸ÑÐ¿Ð¾Ð»Ñ,ÐÐ°ÑÑÑÐ¿Ð¾Ð»Ñ,Mariupol'", :latitude => "47.06667", :longitude => "37.5").save
City.new(:country_id => "230", :name => "Marhanets'", :aliases => "Komintern,Marganec,Marganets,Marhanets',Marhanetsâ,ÐÐ°ÑÐ³Ð°Ð½ÐµÑ,Marhanetsâ", :latitude => "47.63972", :longitude => "34.63639").save
City.new(:country_id => "230", :name => "Malyn", :aliases => "Malin,Malyn,ÐÐ°Ð»Ð¸Ð½,Malyn", :latitude => "50.76667", :longitude => "29.23333").save
City.new(:country_id => "230", :name => "Makiyivka", :aliases => "Dmitriyevsk,Makayevka,Makeevka,Makejewka,Makeyevka,Makiivka,Makiyivka,Makyeevka,Makyevka,ÐÐ°ÐºÐµÐµÐ²ÐºÐ°,ÐÐ°ÐºÑÑÐ²ÐºÐ°,Makiyivka", :latitude => "48.03333", :longitude => "37.96667").save
City.new(:country_id => "230", :name => "Lyubotyn", :aliases => "LJUBOTIN,Lyobotin,Lyubotin,Lyubotyn,ÐÐ®ÐÐÐ¢ÐÐ,Lyubotyn", :latitude => "49.94691", :longitude => "35.92907").save
City.new(:country_id => "230", :name => "L'viv", :aliases => "L'viv,L'vov,Lavov,Lemberg,Leopoli,Leopolis,Liov,Lviv,Lviva,Lvov,Lvovas,Lvovo,Lwiw,Lwow,LwÃ³w,l'vov,lbwb,li wo fu,libiu,lvov,rivu~ifu,Ä»viva,Ä½vov,ÐÐ²Ð¾Ð²,ÐÑÐ²Ð¾Ð²,ÐÑÐ²ÑÐ²,××××,××¢×××¢×¨×,ãªã´ã£ã,å©æ²å¤«,ë¦¬ë¹ì°,L'viv", :latitude => "49.83826", :longitude => "24.02324").save
City.new(:country_id => "230", :name => "Lutugino", :aliases => "Loutougino,Lutugino,ÐÑÑÑÐ³Ð¸Ð½Ð¾,Lutugino", :latitude => "48.40194", :longitude => "39.21028").save
City.new(:country_id => "230", :name => "Luts'k", :aliases => "Loetsk,Loutsk,Luc'k,Luck,Luckas,Lucko,Luts'k,Lutsk,Lutsâk,Luzk,lwzq,Åuck,ÐÑÑÐº,ÐÑÑÑÐº,×××¦×§,Lutsâk", :latitude => "50.75", :longitude => "25.33333").save
City.new(:country_id => "230", :name => "Luhans'k", :aliases => "Lugans'k,Lugansk,Luhans'k,Luhansâk,Voroshilovgrad,Woroschilowgrad,ÐÐ¾ÑÐ¾ÑÐ¸Ð»Ð¾Ð²Ð³ÑÐ°Ð´,ÐÑÐ³Ð°Ð½ÑÐº,ÐÑÐ³Ð°Ð½ÑÑÐº,Luhansâk", :latitude => "48.56667", :longitude => "39.33333").save
City.new(:country_id => "230", :name => "Lubny", :aliases => "LUBNY,Lubin,Lubni,Lubny,ÐÐ£ÐÐÐ«,ÐÑÐ±Ð½Ð¸,Lubny", :latitude => "50.01667", :longitude => "33").save
City.new(:country_id => "230", :name => "Lozova", :aliases => "LOZOVAJA,Losowaja,Lozova,Lozovaya,ÐÐÐÐÐÐÐ¯,ÐÐ¾Ð·Ð¾Ð²Ð°,Lozova", :latitude => "48.88333", :longitude => "36.38333").save
City.new(:country_id => "230", :name => "Lisichansk", :aliases => "LISICHANSK,Lisichans'k,Lisichansk,ÐÐÐ¡ÐÐ§ÐÐÐ¡Ð,ÐÐ¸ÑÐ¸ÑÐ°Ð½ÑÐº,ÐÐ¸ÑÐ¸ÑÐ°Ð½ÑÑÐº,Lisichansk", :latitude => "48.91917", :longitude => "38.41583").save
City.new(:country_id => "230", :name => "Ladyzhyn", :aliases => "Ladizhin,Ladyzhin,Ladyzhyn,Lodyzhin,ÐÐ°Ð´Ð¸Ð¶Ð¸Ð½,Ladyzhyn", :latitude => "48.66667", :longitude => "29.25").save
City.new(:country_id => "230", :name => "Kiev", :aliases => "Chijv,Chiovia,Kaenugardur,Kiebo,Kieu,Kiev,Kievo,Kiew,Kiiev,Kiiv,Kijev,Kijeva,Kijevas,Kijow,Kijv,KijÃ³w,Kiova,Kyiiv,Kyjev,KÃ¦nugarÃ°ur,KÃ­ev,ji fu,kheiyf,kiefu,kiva,kiyebha,kiyepeu,kyf,kyiva,kyyf,qyyb,ÎÎ¯ÎµÎ²Î¿,ÐÐ¸ÐµÐ²,ÐÐ¸ÑÐ²,ÐÐ¸ÑÐµÐ²,ÐÑÑ¥Ð²Ñ,ÐÑÐµÑ,Ô¿Õ«Ö,×§×××,×§××¢×°,ÙÙÙÙ,Ú©ÛÙ,à¤à¥à¤µ,à¤à¥à¤¯à¥à¤µ,à¦à¦¿à¦¯à¦¼à§à¦­,à¹à¸à¸µà¸¢à¸,ááááá,áªá¨á­,ã­ã¨ã,åºè¼,í¤ìí,Kiev", :latitude => "50.45466", :longitude => "30.5238").save
City.new(:country_id => "230", :name => "Kuznetsovs'k", :aliases => "Kuznecovsk,Kuznetsovs'k,Kuznetsovsk,Kuznetsovsâk,ÐÑÐ·Ð½ÐµÑÐ¾Ð²ÑÐº,Kuznetsovsâk", :latitude => "51.68333", :longitude => "25.86667").save
City.new(:country_id => "230", :name => "Kurakhovo", :aliases => "Kurakhovo,Kurakhovstroy,Novo-Ulakly,Petrovka,ÐÑÑÐ°ÑÐ¾Ð²Ð¾,Kurakhovo", :latitude => "47.98333", :longitude => "37.26667").save
City.new(:country_id => "230", :name => "Kryvyy Rih", :aliases => "Krivij Rig,Krivoj Rog,Krivoy Rog,Kriwoi Rog,Kryvyy Rih,ÐÑÐ¸Ð²Ð¸Ð¹ Ð ÑÐ³,ÐÑÐ¸Ð²Ð¾Ð¹ Ð Ð¾Ð³,Kryvyy Rih", :latitude => "47.91667", :longitude => "33.35").save
City.new(:country_id => "230", :name => "Krolevets", :aliases => "Korolevets,Krolevec,Krolevets,Krolovets,ÐÑÐ¾Ð»ÐµÐ²ÐµÑ,Krolevets", :latitude => "51.55", :longitude => "33.38333").save
City.new(:country_id => "230", :name => "Kreminna", :aliases => "KREMENNAJA,Kremennaya,Kreminna,ÐÐ ÐÐÐÐÐÐÐ¯,ÐÑÐµÐ¼ÑÐ½Ð½Ð°,Kreminna", :latitude => "49.04944", :longitude => "38.21972").save
City.new(:country_id => "230", :name => "Kremenets'", :aliases => "Kremenec',Kremenets,Kremenets',Kremenetsâ,Krzemieniec,Kshemenets,ÐÑÐµÐ¼ÐµÐ½ÐµÑÑ,Kremenetsâ", :latitude => "50.1", :longitude => "25.71667").save
City.new(:country_id => "230", :name => "Kremenchuk", :aliases => "Kremenchug,Kremenchuk,Kremencuk,Krementschug,Krementschuk,Krementsuk,KrementÅ¡uk,KremenÄuk,Krenenchur,Krzemienczuk,KrzemieÅczuk,keulemenchukeu,kuremenchuku,ÐÑÐµÐ¼ÐµÐ½ÑÑÐ³,ÐÑÐµÐ¼ÐµÐ½ÑÑÐº,ã¯ã¬ã¡ã³ãã¥ã¯,í¬ë ë©ì¶í¬,Kremenchuk", :latitude => "49.09725", :longitude => "33.41972").save
City.new(:country_id => "230", :name => "Krasnyy Luch", :aliases => "KR.LUCH,Krasnij Luch,Krasniluch,Krasny Luch,Krasnyy Luch,Krassntjlutsch,ÐÐ .ÐÐ£Ð§,ÐÑÐ°ÑÐ½Ð¸Ð¹ ÐÑÑ,Krasnyy Luch", :latitude => "48.13306", :longitude => "38.9325").save
City.new(:country_id => "230", :name => "Krasnyy Liman", :aliases => "Krasniy Liman,Krasny Liman,Krasnyj Liman,Krasnyy Liman,Liman,ÐÑÐ°ÑÐ½ÑÐ¹ ÐÐ¸Ð¼Ð°Ð½,Krasnyy Liman", :latitude => "48.98333", :longitude => "37.81667").save
City.new(:country_id => "230", :name => "Krasnoperekops'k", :aliases => "Krasnoperekops'k,Krasnoperekopsk,Krasnoperekopsâk,Or qapu,ÐÑÐ°ÑÐ½Ð¾Ð¿ÐµÑÐµÐºÐ¾Ð¿ÑÐº,ÐÑÐ°ÑÐ½Ð¾Ð¿ÐµÑÐµÐºÐ¾Ð¿ÑÑÐº,Krasnoperekopsâk", :latitude => "45.95472", :longitude => "33.79579").save
City.new(:country_id => "230", :name => "Krasnohrad", :aliases => "KRASNOGRAD,Konstantinograd,Krasnograd,Krasnohrad,ÐÐ ÐÐ¡ÐÐÐÐ ÐÐ,Krasnohrad", :latitude => "49.36667", :longitude => "35.45").save
City.new(:country_id => "230", :name => "Krasnodon", :aliases => "KRASNODON,Krasnodon,Krassnodon,Sorokin,Sorokino,ÐÐ ÐÐ¡ÐÐÐÐÐ,Krasnodon", :latitude => "48.295", :longitude => "39.74").save
City.new(:country_id => "230", :name => "Krasnoarmiys'k", :aliases => "Grishino,KRASNOARMEJSK,Krasnoarmeysk,Krasnoarmeyskoye,Krasnoarmiys'k,Krasnoarmiysâk,Krassnoarmeiskoje,ÐÐ ÐÐ¡ÐÐÐÐ ÐÐÐÐ¡Ð,ÐÑÐ°ÑÐ½Ð¾Ð°ÑÐ¼ÑÐ¹ÑÑÐº,Krasnoarmiysâk", :latitude => "48.28333", :longitude => "37.18333").save
City.new(:country_id => "230", :name => "Krasyliv", :aliases => "Krasiliv,Krasilov,Krasilow,Krasyliv,ÐÑÐ°ÑÐ¸Ð»ÑÐ²,Krasyliv", :latitude => "49.65", :longitude => "26.96667").save
City.new(:country_id => "230", :name => "Kramators'k", :aliases => "Kramators'k,Kramatorsk,Kramatorskaja,Kramatorskaya,Kramatorsâk,ÐÑÐ°Ð¼Ð°ÑÐ¾ÑÑÐº,ÐÑÐ°Ð¼Ð°ÑÐ¾ÑÑÑÐº,Kramatorsâk", :latitude => "48.71667", :longitude => "37.53333").save
City.new(:country_id => "230", :name => "Kivsharivka", :aliases => "Kivsarivka,Kivsharivka,Kovsharov,Kovsharovka,ÐÑÐ²ÑÐ°ÑÑÐ²ÐºÐ°,Kivsharivka", :latitude => "49.62139", :longitude => "37.70306").save
City.new(:country_id => "230", :name => "Kovel'", :aliases => "Kovel,Kovel',Kovelâ,Kowel,ÐÐ¾Ð²ÐµÐ»Ñ,Kovelâ", :latitude => "51.21667", :longitude => "24.71667").save
City.new(:country_id => "230", :name => "Kotovs'k", :aliases => "Birzula,Kotovs'k,Kotovsk,Kotovsâk,Kotowsk,ÐÐ¾ÑÐ¾Ð²ÑÐº,Kotovsâk", :latitude => "47.75", :longitude => "29.53306").save
City.new(:country_id => "230", :name => "Korsun'-Shevchenkivs'kyy", :aliases => "Karun' Sheychenkovskaya,Karunâ Sheychenkovskaya,Korssun-Schewtschem Kowskij,Korsun',Korsun'-Shevchenkivs'kyy,Korsun'-Shevchenkovskij,Korsun'-Shevchenkovskiy,Korsunâ,Korsunâ-Shevchenkivsâkyy,Korsunâ-Shevchenkovskiy,ÐÐ¾ÑÑÑÐ½Ñ-Ð¨ÐµÐ²ÑÐµÐ½ÐºÐ¾Ð²ÑÐºÐ¸Ð¹,Korsunâ-Shevchenkivsâkyy", :latitude => "49.43333", :longitude => "31.25").save
City.new(:country_id => "230", :name => "Korostyshiv", :aliases => "Korostisiv,Korostyshev,Korostyshiv,ÐÐ¾ÑÐ¾ÑÑÐ¸ÑÑÐ²,ÐÐ¾ÑÐ¾ÑÑÑÑÐµÐ²,Korostyshiv", :latitude => "50.31667", :longitude => "29.06667").save
City.new(:country_id => "230", :name => "Korosten'", :aliases => "Korosten,Korosten',Korostenj,Korostenâ,KorosteÅ,Koroszteny,ÐÐ¾ÑÐ¾ÑÑÐµÐ½Ñ,Korostenâ", :latitude => "50.95", :longitude => "28.65").save
City.new(:country_id => "230", :name => "Kostyantynivka", :aliases => "KONSTANTINOVKA,Konstantinovka,Konstantinowka,Kostantinivka,Kostjantyniwka,Kostyantynivka,ÐÐÐÐ¡Ð¢ÐÐÐ¢ÐÐÐÐÐÐ,ÐÐ¾Ð½ÑÑÐ°Ð½ÑÐ¸Ð½Ð¾Ð²ÐºÐ°,ÐÐ¾ÑÑÑÐ½ÑÐ¸Ð½ÑÐ²ÐºÐ°,Kostyantynivka", :latitude => "48.53333", :longitude => "37.71667").save
City.new(:country_id => "230", :name => "Konotop", :aliases => "KONOTOP,Konotop,ÐÐÐÐÐ¢ÐÐ,ÐÐ¾Ð½Ð¾ÑÐ¾Ð¿,Konotop", :latitude => "51.23333", :longitude => "33.2").save
City.new(:country_id => "230", :name => "Komsomol's'ke", :aliases => "Komsomol's'ke,Komsomol'skoe,Komsomol'skoye,Komsomolâskoye,Komsomolâsâke,ÐÐ¾Ð¼ÑÐ¾Ð¼Ð¾Ð»ÑÑÐºÐ¾Ðµ,Komsomolâsâke", :latitude => "49.59472", :longitude => "36.52528").save
City.new(:country_id => "230", :name => "Kolomyya", :aliases => "Colomeea,Kholomya,Kolomea,Kolomea-Ost,Kolomeo,Kolomija,Kolomyia,Kolomyja,Kolomyya,KoÅomyja,ÐÐ¾Ð»Ð¾Ð¼Ð¸Ñ,ÐÐ¾Ð»Ð¾Ð¼ÑÑ,Kolomyya", :latitude => "48.53056", :longitude => "25.04028").save
City.new(:country_id => "230", :name => "Kivertsy", :aliases => "Kiverci,Kivertse,Kivertsi,Kivertsy,Kiwerce,ÐÑÐ²ÐµÑÑÑ,Kivertsy", :latitude => "50.83333", :longitude => "25.46667").save
City.new(:country_id => "230", :name => "Kirovsk", :aliases => "Golubovka,KIROVSK,Kirovsk,ÐÐÐ ÐÐÐ¡Ð,Kirovsk", :latitude => "48.64194", :longitude => "38.65278").save
City.new(:country_id => "230", :name => "Kirovohrad", :aliases => "Elizavetgrad,KIROVOGRAD,Kirovo,Kirovograd,Kirovohrad,Kirowo,Kirowograd,Kirowohrad,Sinowjewsk,Yelizavetgrad,Yelizavety,Zinov'evsk,Zinov'yevsk,Zinovievsk,Zinovâevsk,Zinovâyevsk,kirovu~ofurado,qyrwbwgrd,ÐÐÐ ÐÐÐÐÐ ÐÐ,ÐÐ¸ÑÐ¾Ð²Ð¾Ð³ÑÐ°Ð´,ÐÑÑÐ¾Ð²Ð¾Ð³ÑÐ°Ð´,×§××¨×××××¨×,ã­ã­ã´ã©ãã©ã¼ã,Kirovohrad", :latitude => "48.50417", :longitude => "32.26306").save
City.new(:country_id => "230", :name => "Kiliya", :aliases => "Chilia,Chilia Noua,Chilia-Noua,Chilia-NouÄ,Kilaya,Kilia,Kilia Noue,Kilija,Kiliya,Kiliya Noua,ÐÐ¸Ð»Ð¸Ñ,ÐÑÐ»ÑÑ,Kiliya", :latitude => "45.45", :longitude => "29.26667").save
City.new(:country_id => "230", :name => "Khust", :aliases => "Chust,Guste,Huszt,Khust,Ð¥ÑÑÑ,Khust", :latitude => "48.18139", :longitude => "23.29778").save
City.new(:country_id => "230", :name => "Khmel'nyts'kyy", :aliases => "Kamelnitskiy,Khmel'nickij,Khmel'nitskiy,Khmel'nyts'kyy,Khmelinitski,Khmelânitskiy,Khmelânytsâkyy,Proskurov,Proskurovak,Proskurow,ÐÑÐ¾ÑÐºÑÑÐ¾Ð²,Ð¥Ð¼ÐµÐ»ÑÐ½Ð¸ÑÐºÐ¸Ð¹,Khmelânytsâkyy", :latitude => "49.41667", :longitude => "27").save
City.new(:country_id => "230", :name => "Khmil'nyk", :aliases => "Khmel'nik,Khmel'niki,Khmelânik,Khmelâniki,Khmil'nik,Khmil'nyk,Khmilânyk,Ð¥Ð¼ÐµÐ»ÑÐ½Ð¸Ðº,Ð¥Ð¼ÑÐ»ÑÐ½Ð¸Ðº,Khmilânyk", :latitude => "49.55979", :longitude => "27.95754").save
City.new(:country_id => "230", :name => "Kherson", :aliases => "Cherson,Chersonas,ChersoÅ,H'erson,Herson,Kherson,he er song,heleuson,hrswn,Ä¤erson,Ð¥ÐµÑÑÐ¾Ð½,××¨×¡××,èµ«å°æ¾,í¤ë¥´ì,Kherson", :latitude => "46.63333", :longitude => "32.6").save
City.new(:country_id => "230", :name => "Khartsyzsk", :aliases => "Kharcyzsk,Khartsysk,Khartsyzsk,Ð¥Ð°ÑÑÑÐ·ÑÐº,Khartsyzsk", :latitude => "48.03528", :longitude => "38.155").save
City.new(:country_id => "230", :name => "Kharkiv", :aliases => "Carcovia,CarcÃ³via,Charcovia,Charkiv,Charkiw,Charkov,Charkovas,Charkow,CharkÃ³w,Harkiv,Harkiva,Harkivo,Harkov,Harkova,Jarkov,KHAR'KOV,Khar'kov,Kharkiv,Kharkov,Kharâkov,ha er ke fu,haleukiu,harikofu,hrqwb,kharkwf,Ä¤arkivo,Ä¤arkov,Ð¥ÐÐ Ð¬ÐÐÐ,Ð¥Ð°ÑÐºÐ¾Ð²,Ð¥Ð°ÑÐºÑÐ²,Ð¥Ð°ÑÑÐºÐ¾Ð²,××¨×§××,Ø®Ø§Ø±ÙÙÙ,á®áá áááá,ããªã³ã,åç¾ç§å¤«,íë¥´í¤ì°,Kharkiv", :latitude => "50", :longitude => "36.25").save
City.new(:country_id => "230", :name => "Kerch", :aliases => "Bospor,Bospora,KERCH',Kerc,Kerch,Kerch',Kerchâ,Kerco,Kercz,Kertch,Kertj,Kerts,Kertsch,Kertsj,KertÅ¡,KerÃ§,KerÄo,Panticapaeum,Pantikapea,krch,ÐÐÐ Ð§Ð¬,ÐÐµÑÑ,ÐÐµÑÑÑ,Ú©Ø±Ú,Kerch", :latitude => "45.35799", :longitude => "36.46798").save
City.new(:country_id => "230", :name => "Kozyatyn", :aliases => "Kasatin,Kazatin,Kozjatin,Kozyatyn,ÐÐ¾Ð·ÑÑÐ¸Ð½,Kozyatyn", :latitude => "49.71667", :longitude => "28.83333").save
City.new(:country_id => "230", :name => "Karlivka", :aliases => "KARLOVKA,Karlivka,Karlovka,Karlowka,ÐÐÐ ÐÐÐÐÐ,ÐÐ°ÑÐ»ÑÐ²ÐºÐ°,Karlivka", :latitude => "49.45", :longitude => "35.13333").save
City.new(:country_id => "230", :name => "Kaniv", :aliases => "KANEV,Kanev,Kanew,Kaniv,KanÃ«v,ÐÐÐÐÐ,ÐÐ°Ð½ÑÐ²,Kaniv", :latitude => "49.75", :longitude => "31.46667").save
City.new(:country_id => "230", :name => "Kamieniec Podolski", :aliases => "Kam'yanets'-Podil's'kyy,Kamenec-Podol'skij,Kamenec-Podolski,Kamenets Podol'ski,Kamenets Podolâski,Kamenets-Podilski,Kamenets-Podol'sk,Kamenets-Podol'skiy,Kamenets-Podolsk,Kamenets-Podolâsk,Kamenets-Podolâskiy,Kamenez-Podolsk,Kamianets-Podilskyi,Kamieniec Podolski,Kamjanets-Podilski,Kamjanets-Podilskyi,Kamjanez-Podilskyj,Kamâyanetsâ-Podilâsâkyy,ÐÐ°Ð¼'ÑÐ½ÐµÑÑ-ÐÐ¾Ð´ÑÐ»ÑÑÑÐºÐ¸Ð¹,ÐÐ°Ð¼ÐµÐ½ÐµÑ-ÐÐ¾Ð´Ð¾Ð»ÑÐºÐ¸,ÐÐ°Ð¼ÐµÐ½ÐµÑ-ÐÐ¾Ð´Ð¾Ð»ÑÑÐºÐ¸Ð¹,Kamieniec Podolski", :latitude => "48.66667", :longitude => "26.56667").save
City.new(:country_id => "230", :name => "Kalush", :aliases => "Kalouch,Kalush,Kalusz,Katusz,KaÅusz,karushu,ÐÐ°Ð»ÑÑ,×§×Ö·×××©,ã«ã«ã·ã¥,Kalush", :latitude => "49.01667", :longitude => "24.36667").save
City.new(:country_id => "230", :name => "Kalynivka", :aliases => "Kalinivka,Kalinovka,Kalinovskiy,Kalynivka,ÐÐ°Ð»Ð¸Ð½Ð¾Ð²ÐºÐ°,ÐÐ°Ð»Ð¸Ð½ÑÐ²ÐºÐ°,Kalynivka", :latitude => "49.46667", :longitude => "28.53333").save
City.new(:country_id => "230", :name => "Kakhovka", :aliases => "Kachowka,Kakhovka,ÐÐ°ÑÐ¾Ð²ÐºÐ°,Kakhovka", :latitude => "46.81028", :longitude => "33.47667").save
City.new(:country_id => "230", :name => "Izyum", :aliases => "IZJUM,Izyum,ÐÐÐ®Ð,Izyum", :latitude => "49.21278", :longitude => "37.25694").save
City.new(:country_id => "230", :name => "Izyaslav", :aliases => "Izjaslav,Izyaslav,Izyaslavl',Izyaslavlâ,ÐÐ·ÑÑÐ»Ð°Ð²,Izyaslav", :latitude => "50.11667", :longitude => "26.8").save
City.new(:country_id => "230", :name => "Izmayil", :aliases => "Ismail,Ismajil,Izmail,IzmaiÅ,Izmayil,Tuchkov,Ä°smail,ÐÐ·Ð¼Ð°ÑÐ»,ÐÐ·Ð¼Ð°Ð¸Ð»,ÐÐ·Ð¼Ð°ÑÐ»,Izmayil", :latitude => "45.35", :longitude => "28.83333").save
City.new(:country_id => "230", :name => "Ivano-Frankivs'k", :aliases => "Ivano-Frankivs'k,Ivano-Frankivsâk,Ivano-Frankovsk,Stanislau,Stanislav,Stanislavov,Stanislavyv,Stanistawow,StanistawÃ³w,ÐÐ²Ð°Ð½Ð¾-Ð¤ÑÐ°Ð½ÐºÐ¾Ð²ÑÐº,Ivano-Frankivsâk", :latitude => "48.9215", :longitude => "24.70972").save
City.new(:country_id => "230", :name => "Irpin'", :aliases => "Dachi Irpen',Dachi Irpenâ,IRPEN',Irpen',Irpenâ,Irpin',Irpinâ,ÐÐ ÐÐÐÐ¬,Irpinâ", :latitude => "50.51667", :longitude => "30.25").save
City.new(:country_id => "230", :name => "Ilovays'k", :aliases => "Ilovaiskaia,Ilovajsk,Ilovays'k,Ilovayskaya,Ilovaysâk,ÐÐ»Ð¾Ð²Ð°Ð¹ÑÐº,Ilovaysâk", :latitude => "47.92504", :longitude => "38.19714").save
City.new(:country_id => "230", :name => "Illichivs'k", :aliases => "Il'ichevka,Il'ichevsk,Illichivs'k,Illichivsâk,Ilyitschovsk,Ilâichevka,Ilâichevsk,IlâichÃ«vsk,ÐÐ»ÑÐ¸ÑÐµÐ²ÑÐº,Illichivsâk", :latitude => "46.3", :longitude => "30.66667").save
City.new(:country_id => "230", :name => "Horodok", :aliases => "Gorodok,Gorodok-Proskurovskiy,Horodok,Horodok", :latitude => "49.16667", :longitude => "26.56667").save
City.new(:country_id => "230", :name => "Horlivka", :aliases => "GORLOVKA,Gorlivka,Gorlovka,Gorlowka,Horlivka,Horliwka,ÐÐÐ ÐÐÐÐÐ,ÐÐ¾ÑÐ»Ð¾Ð²ÐºÐ°,ÐÐ¾ÑÐ»ÑÐ²ÐºÐ°,Horlivka", :latitude => "48.3", :longitude => "38.05").save
City.new(:country_id => "230", :name => "Hlukhiv", :aliases => "GLUKHOV,Gluchoff,Gluchow,Gluhiv,Glukhov,Hlukhiv,ÐÐÐ£Ð¥ÐÐ,ÐÐ»ÑÑÑÐ²,Hlukhiv", :latitude => "51.68333", :longitude => "33.91667").save
City.new(:country_id => "230", :name => "Hulyaypole", :aliases => "GULJAJPOLE,Guljai-Pole,Gulyai Pole,Gulyaypole,Hulyaypole,ÐÐ£ÐÐ¯ÐÐÐÐÐ,Hulyaypole", :latitude => "47.66528", :longitude => "36.25778").save
City.new(:country_id => "230", :name => "Gorodok", :aliases => "Gorodok,Gorodok-Yagellonskiy,Grodek,Grodek Jagiellonski,Grodok Jagiellonski,Grudek Yagellon'ski,Grudek Yagellonâski,Grudek-Yagel'on'ski,Grudek-Yagelâonâski,GrÃ³dek JagielloÅski,GrÃ³dok JagielloÅski,ÐÐ¾ÑÐ¾Ð´Ð¾Ðº,Gorodok", :latitude => "49.78333", :longitude => "23.65").save
City.new(:country_id => "230", :name => "Horodyshche", :aliases => "GORODISHHE,Gorodishche,Horodyshche,Imeni G.I. Petrovskogo,Poselok Imeni G.I. Petrovskogo,PosÃ«lok Imeni G.I. Petrovskogo,ÐÐÐ ÐÐÐÐ©Ð,Horodyshche", :latitude => "49.28333", :longitude => "31.45").save
City.new(:country_id => "230", :name => "Hola Prystan'", :aliases => "Golaja Pristan',Golaya Pristan',Golaya Pristanâ,Hola Prystan',Hola Prystanâ,ÐÐ¾Ð»Ð°Ñ ÐÑÐ¸ÑÑÐ°Ð½Ñ,Hola Prystanâ", :latitude => "46.52056", :longitude => "32.52583").save
City.new(:country_id => "230", :name => "Heniches'k", :aliases => "Genichesk,Genitschesk,Heniches'k,Henichesâk,ÐÐµÐ½Ð¸ÑÐµÑÐº,Henichesâk", :latitude => "46.1735", :longitude => "34.80797").save
City.new(:country_id => "230", :name => "Hayvoron", :aliases => "Gaivoron,Gajvoron,Gayvoron,Hayvoron,ÐÐ°Ð¹Ð²Ð¾ÑÐ¾Ð½,Hayvoron", :latitude => "48.35", :longitude => "29.85").save
City.new(:country_id => "230", :name => "Haysyn", :aliases => "Gaisin,Gaissin,Gajsin,Gaysin,Haysyn,ÐÐ°Ð¹ÑÐ¸Ð½,Haysyn", :latitude => "48.8", :longitude => "29.4").save
City.new(:country_id => "230", :name => "Hadyach", :aliases => "Gadjach,Gadyach,Hadyach,ÐÐ°Ð´ÑÑ,Hadyach", :latitude => "50.36667", :longitude => "34").save
City.new(:country_id => "230", :name => "Feodosiya", :aliases => "Caffa,Feodosia,Feodosija,Feodosiya,Feodossia,Feodossija,Fyeodosiya,Kaffa,Kefe,Teodosia,Teodozio,Teodozja,TeodÃ²sia,TeodÃ³sia,Theodosia,Theodosie,ThÃ©odosie,feodoshiya,pe-odosiya,Ð¤ÐµÐ¾Ð´Ð¾ÑÐ¸Ñ,Ð¤ÐµÐ¾Ð´Ð¾ÑÑÑ,ãã§ãªãã·ã¤,íì¤ëìì¼,Feodosiya", :latitude => "45.03252", :longitude => "35.37698").save
City.new(:country_id => "230", :name => "Fastiv", :aliases => "Fastiv,Fastov,Fastow,Ð¤Ð°ÑÑÐ¾Ð²,Ð¤Ð°ÑÑÑÐ²,Fastiv", :latitude => "50.08333", :longitude => "29.91667").save
City.new(:country_id => "230", :name => "Energodar", :aliases => "Ehnergodar,Energodar,ÐÐ½ÐµÑÐ³Ð¾Ð´Ð°Ñ,Ð­Ð½ÐµÑÐ³Ð¾Ð´Ð°Ñ,Energodar", :latitude => "47.49865", :longitude => "34.6574").save
City.new(:country_id => "230", :name => "Dzhankoy", :aliases => "Dshankoi,Dzhanhoi,Dzhankoi,Dzhankoj,Dzhankoy,ÐÐ¶Ð°Ð½ÐºÐ¾Ð¹,Dzhankoy", :latitude => "45.71287", :longitude => "34.39559").save
City.new(:country_id => "230", :name => "Dzerzhyns'k", :aliases => "DZERZHINSK,Dzerzhins'k,Dzerzhinsk,Dzerzhyns'k,Dzerzhynsâk,Imeni Dzerzhinskogo,ÐÐÐÐ ÐÐÐÐ¡Ð,ÐÐ·ÐµÑÐ¶Ð¸Ð½ÑÑÐº,Dzerzhynsâk", :latitude => "48.40472", :longitude => "37.83278").save
City.new(:country_id => "230", :name => "Dunaivtsi", :aliases => "Dunaivci,Dunaivtsi,Dunajewzy,Dunayevtsy,Dunayivtsi,ÐÑÐ½Ð°ÑÐ²ÑÑ,Dunaivtsi", :latitude => "48.9", :longitude => "26.83333").save
City.new(:country_id => "230", :name => "Dubno", :aliases => "Dubno,ÐÑÐ±Ð½Ð¾,Dubno", :latitude => "50.41667", :longitude => "25.75").save
City.new(:country_id => "230", :name => "Drogobych", :aliases => "Drogobich,Drogobych,Drogobycz,Drohobic,Drohobico,DrohobiÄ,DrohobiÄo,Drohobych,Drohobycz,Drohobytsch,Drohobytsj,dorohobichi,drwhwbyz',ÐÑÐ¾Ð³Ð¾Ð±Ð¸Ñ,ÐÑÐ¾Ð³Ð¾Ð±ÑÑ,××¨××××××¥',ãã­ããã,Drogobych", :latitude => "49.35", :longitude => "23.5").save
City.new(:country_id => "230", :name => "Donets'k", :aliases => "Donec'k,Doneck,Donets'k,Donetsk,Donetsâk,Hughesovka,Jusowka,Juzovka,Stalin,Staline,Stalino,Uzivka,Yuzovka,Yuzovo,ÐÐ¾Ð½ÐµÑÐº,ÐÐ¾Ð½ÐµÑÑÐº,Ð¡ÑÐ°Ð»Ð¸Ð½Ð¾,Ð¡ÑÐ°Ð»ÑÐ½Ðµ,Ð¡ÑÐ°Ð»ÑÐ½Ð¾,Ð®Ð·Ð¾Ð²ÐºÐ°,Ð®Ð·ÑÐ²ÐºÐ°,Donetsâk", :latitude => "48", :longitude => "37.8").save
City.new(:country_id => "230", :name => "Dolyna", :aliases => "Dolina,Dolyna,ÐÐ¾Ð»Ð¸Ð½Ð°,Dolyna", :latitude => "48.97056", :longitude => "24.01111").save
City.new(:country_id => "230", :name => "Dolyns'ka", :aliases => "Dolinskaja,Dolinskaya,Dolinskoye,Dolyns'ka,Schewtschenkowo,Shevchenkovo,ÐÐ¾Ð»Ð¸Ð½ÑÐºÐ°Ñ,Dolyns'ka", :latitude => "48.11041", :longitude => "32.76449").save
City.new(:country_id => "230", :name => "Dokuchayevsk", :aliases => "Dokuchaevsk,Dokuchayevsk,Yelenovskiy Kar'yer,Yelenovskiy Karâyer,Yelenovskiye Kar'yery,Yelenovskiye Karâyery,ÐÐ¾ÐºÑÑÐ°ÐµÐ²ÑÐº,Dokuchayevsk", :latitude => "47.73333", :longitude => "37.66667").save
City.new(:country_id => "230", :name => "Dobropol'ye", :aliases => "Dobropol'e,Dobropol'ye,Dobropolâye,Krasnoarmeyskiy Rudnik,ÐÐ¾Ð±ÑÐ¾Ð¿Ð¾Ð»ÑÐµ,Dobropolâye", :latitude => "48.48333", :longitude => "37.1").save
City.new(:country_id => "230", :name => "Dnipropetrovsk", :aliases => "Dnepropetrovsk,Dnepropetrowsk,Dnetropetrovsk,Dniepropetrovsk,Dnipropetrovs'k,Dnjepropetrowsk,Ekaterinoslav,Ekaá¹­erinoslav,Iekaterinoslav,Katerynoslav,Yekaterinoslav,ÐÐ½ÐµÐ¿ÑÐ¾Ð¿ÐµÑÑÐ¾Ð²ÑÐº,ÐÐ½ÑÐ¿ÑÐ¾Ð¿ÐµÑÑÐ¾Ð²ÑÑÐº,ÐÐºÐ°ÑÐµÑÐ¸Ð½Ð¾ÑÐ»Ð°Ð²,Dnipropetrovsk", :latitude => "48.45", :longitude => "34.98333").save
City.new(:country_id => "230", :name => "Dniprodzerzhyns'k", :aliases => "Dneprodsershinsk,Dneprodzerzhinsk,Dneprodzherzhinsk,Dniprodzerzhyns'k,Dniprodzerzhynsâk,Kamenskoye,ÐÐ½ÐµÐ¿ÑÐ¾Ð´Ð·ÐµÑÐ¶Ð¸Ð½ÑÐº,Dniprodzerzhynsâk", :latitude => "48.5", :longitude => "34.61667").save
City.new(:country_id => "230", :name => "Dniprorudne", :aliases => "Dneprograd,Dneprorudnoe,Dneprorudnoye,Dniprorudne,ÐÐ½ÐµÐ¿ÑÐ¾ÑÑÐ´Ð½Ð¾Ðµ,ÐÐ½ÑÐ¿ÑÐ¾ÑÑÐ´Ð½Ðµ,Dniprorudne", :latitude => "47.41", :longitude => "35.01972").save
City.new(:country_id => "230", :name => "Derhachy", :aliases => "DERGACHI,Dergachi,Dergatschi,Derhachi,Derhachy,ÐÐÐ ÐÐÐ§Ð,Derhachy", :latitude => "50.10944", :longitude => "36.12083").save
City.new(:country_id => "230", :name => "Debal'tsevo", :aliases => "Debal'cevo,Debal'tsevo,Debalzewo,Debalâtsevo,ÐÐµÐ±Ð°Ð»ÑÑÐµÐ²Ð¾,Debalâtsevo", :latitude => "48.33694", :longitude => "38.40028").save
City.new(:country_id => "230", :name => "Chuhuyiv", :aliases => "CHUGUEV,Chuguyev,Chuhuyiv,Cuguiv,Tschugujew,Ð§Ð£ÐÐ£ÐÐ,Ð§ÑÐ³ÑÑÐ²,Chuhuyiv", :latitude => "49.83556", :longitude => "36.68639").save
City.new(:country_id => "230", :name => "Chortkiv", :aliases => "Chertkov,Chortkiv,Chortkov,Chortkuv,Cortkiv,Czortkow,CzortkÃ³w,Tschortkow,Ð§Ð¾ÑÑÐºÐ¾Ð²,Ð§Ð¾ÑÑÐºÑÐ²,Chortkiv", :latitude => "49.01667", :longitude => "25.8").save
City.new(:country_id => "230", :name => "Chervonograd", :aliases => "Chervonograd,Kristinopol',Kristinopolâ,Krvstonopol,Krystynopol,Ð§ÐµÑÐ²Ð¾Ð½Ð¾Ð³ÑÐ°Ð´,Chervonograd", :latitude => "50.38333", :longitude => "24.23333").save
City.new(:country_id => "230", :name => "Chernivtsi", :aliases => "Cernauti,Cernivci,Cernivco,Cernovice,CernÄuÅ£i,Chernehuc',Chernivtsi,Chernovcy,Chernovits,Chernovitsy,Chernovtsy,Czerniowce,Czernowitz,Tchernivtsi,Tjernivtsi,Tschernowitz,Tsjernivtsi,cheleuniuchi,cherunifuchi,z'rnwbyz,Äernivco,Äernovice,Ð§ÐµÑÐ½Ð¾Ð²ÑÑ,Ð§ÐµÑÐ½ÑÑÑÑ,Ð§ÐµÑÐ½ÑÐ²ÑÑ,×¦'×¨× ××××¥,ãã§ã«ããã,ì²´ë¥´ëì°ì¹,Chernivtsi", :latitude => "48.3", :longitude => "25.93333").save
City.new(:country_id => "230", :name => "Chernihiv", :aliases => "CHERNIGOV,Cernigiv,Cernigivo,Cernihivo,Chernigov,Chernihiv,Csernyihiv,Czernihovia,Czernihow,CzernihÃ³w,Tchernihiv,Tschernigow,Tschernihiw,Tsernihiv,Tsjernihiv,TÅ¡ernihiv,qie er ni ge fu,Äernigivo,Äernihivo,Ð§ÐÐ ÐÐÐÐÐ,Ð§ÐµÑÐ½Ð¸Ð³Ð¾Ð²,Ð§ÐµÑÐ½ÑÐ³ÑÐ²,åå°å°¼æå¤«,Chernihiv", :latitude => "51.5", :longitude => "31.3").save
City.new(:country_id => "230", :name => "Cherkasy", :aliases => "CHERKASSY,Cerkasy,Cherkasi,Cherkassi,Cherkassy,Cherkasy,Cserkaszi,Czerkasy,Tcherkassy,Tscherkassy,Tserkasso,Tserkasy,Tsjerkasy,TÅ¡erkassÃµ,TÅ¡erkasy,z'rqsy,Äerkasy,Ð§ÐÐ ÐÐÐ¡Ð¡Ð«,Ð§ÐµÑÐºÐ°ÑÐ¸,Ð§ÐµÑÐºÐ°ÑÑÑ,×¦'×¨×§×¡×,Cherkasy", :latitude => "49.43333", :longitude => "32.06667").save
City.new(:country_id => "230", :name => "Bucha", :aliases => "Bucha,Bychansk,Dachi Bucha,ÐÑÑÐ°,Bucha", :latitude => "50.56667", :longitude => "30.21667").save
City.new(:country_id => "230", :name => "Bryanka", :aliases => "BRJANKA,Bryanka,Bryanskiy,Bryanskiy Rudnik,ÐÐ Ð¯ÐÐÐ,Bryanka", :latitude => "48.50694", :longitude => "38.66167").save
City.new(:country_id => "230", :name => "Brovary", :aliases => "BROVARY,Brovari,Brovary,Browary,ÐÐ ÐÐÐÐ Ð«,ÐÑÐ¾Ð²Ð°ÑÐ¸,ÐÑÐ¾Ð²Ð°ÑÑ,Brovary", :latitude => "50.5", :longitude => "30.76667").save
City.new(:country_id => "230", :name => "Brody", :aliases => "Brody,brodi,brody,brwdy,burodi,ÐÑÐ¾Ð´Ð¸,ÐÑÐ¾Ð´Ñ,××¨×××,ãã­ãã£,Brody", :latitude => "50.08333", :longitude => "25.15").save
City.new(:country_id => "230", :name => "Boyarka", :aliases => "BOJARKA,Boyarka,Boyarka-Budayevka,Budayevka,ÐÐÐ¯Ð ÐÐ,Boyarka", :latitude => "50.31667", :longitude => "30.31667").save
City.new(:country_id => "230", :name => "Boryspil'", :aliases => "Borispilo,Borispol',Borispolâ,Boryspil,Boryspil',Boryspilâ,Boryspol,borisupiri,ÐÐ¾ÑÐ¸ÑÐ¿Ð¾Ð»Ñ,ÐÐ¾ÑÐ¸ÑÐ¿ÑÐ»Ñ,ããªã¹ããª,Boryspilâ", :latitude => "50.35", :longitude => "30.95").save
City.new(:country_id => "230", :name => "Boryslav", :aliases => "Borislav,Boryslav,Borysxaw,ÐÐ¾ÑÐ¸ÑÐ»Ð°Ð²,Boryslav", :latitude => "49.28333", :longitude => "23.41667").save
City.new(:country_id => "230", :name => "Bolhrad", :aliases => "Belgrad,Bolgrad,Bolhrad,ÐÐ¾Ð»Ð³ÑÐ°Ð´,Bolhrad", :latitude => "45.68333", :longitude => "28.61083").save
City.new(:country_id => "230", :name => "Bohuslav", :aliases => "BOGUSLAV,Boguslav,Boguslaw,Bohuslav,ÐÐÐÐ£Ð¡ÐÐÐ,Bohuslav", :latitude => "49.55", :longitude => "30.88333").save
City.new(:country_id => "230", :name => "Bohodukhiv", :aliases => "BOGODUKHOV,Bododukhov,Bogoduchow,Bogoduhiv,Bogodukhov,Bohodukhiv,ÐÐÐÐÐÐ£Ð¥ÐÐ,ÐÐ¾Ð³Ð¾Ð´ÑÑÑÐ²,Bohodukhiv", :latitude => "50.16083", :longitude => "35.51639").save
City.new(:country_id => "230", :name => "Bilhorod-Dnistrovs'kyy", :aliases => "Akkerman,Belgorod-Dnestrovskij,Belgorod-Dnestrovskiy,Bilgorod-Dnistrovs'kij,Bilhorod-Dnistrovs'kyy,Bilhorod-Dnistrovsâkyy,Byelogorod,Cetatea Alba,Cetatea AlbÄ,ÐÐµÐ»Ð³Ð¾ÑÐ¾Ð´-ÐÐ½ÐµÑÑÑÐ¾Ð²ÑÐºÐ¸Ð¹,ÐÑÐ»Ð³Ð¾ÑÐ¾Ð´-ÐÐ½ÑÑÑÑÐ¾Ð²ÑÑÐºÐ¸Ð¹,Bilhorod-Dnistrovsâkyy", :latitude => "46.2", :longitude => "30.35").save
City.new(:country_id => "230", :name => "Bila Tserkva", :aliases => "Belaja Cerkov',Belaja Zerkow,Belaya Tserkov',Belaya Tserkovâ,Biala Cerkiew,BiaÅa Cerkiew,Bila Cerkva,Bila Tserkva,Bila Zerkwa,ÐÐµÐ»Ð°Ñ Ð¦ÐµÑÐºÐ¾Ð²Ñ,ÐÑÐ»Ð° Ð¦ÐµÑÐºÐ²Ð°,××××××-×¦×¨×§××,ãã¼ã©ã»ãã§ã¼ã«ã¯ã´ã¡,Bila Tserkva", :latitude => "49.78333", :longitude => "30.11667").save
City.new(:country_id => "230", :name => "Berezhani", :aliases => "Berejani,Bereschany,Berezany,Berezhani,Berezhany,BereÅ¾any,Brzezany,Brzezhany,BrzeÅ¼any,ÐÐµÑÐµÐ¶Ð°Ð½Ð¸,ÐÐµÑÐµÐ¶Ð°Ð½Ñ,ÐÐµÑÐµÐ¶Ð°Ð½Ð¸", :latitude => "49.45", :longitude => "24.93333").save
City.new(:country_id => "230", :name => "Berehove", :aliases => "Beregove,Beregovo,Beregszasz,BeregszÃ¡sz,Berehove,Berehovo,Berehowe,Berekhovo,belehobe,ÐÐµÑÐµÐ³Ð¾Ð²Ðµ,ÐÐµÑÐµÐ³Ð¾Ð²Ð¾,ë² ë í¸ë² ,Berehove", :latitude => "48.21667", :longitude => "22.65").save
City.new(:country_id => "230", :name => "Berdychiv", :aliases => "Berdicev,Berdichen,Berdichev,Berdiciv,Berditchev,Berditschew,BerdiÄev,Berdychiv,Berdyczow,BerdyczÃ³w,Berdytschiw,berudichifu,brdyz'b,ÐÐµÑÐ´Ð¸ÑÐµÐ²,ÐÐµÑÐ´Ð¸ÑÑÐ²,××¨×××¦'×,ãã«ãã£ãã,Berdychiv", :latitude => "49.9", :longitude => "28.58333").save
City.new(:country_id => "230", :name => "Berdyans'k", :aliases => "BERDJANSK,Berdjansk,Berdyans'k,Berdyansâk,Osipenko,ÐÐÐ ÐÐ¯ÐÐ¡Ð,Berdyansâk", :latitude => "46.75028", :longitude => "36.79444").save
City.new(:country_id => "230", :name => "Bilopillya", :aliases => "BELOPOL'E,Belopol'ye,Belopolje,Belopolâye,Bilopilla,Bilopillya,ÐÐÐÐÐÐÐÐ¬Ð,ÐÑÐ»Ð¾Ð¿ÑÐ»Ð»Ñ,Bilopillya", :latitude => "51.14833", :longitude => "34.30083").save
City.new(:country_id => "230", :name => "Bilohirs'k", :aliases => "Belogorsk,Bilohirs'k,Bilohirsâk,Karassu Basar,Karasu,Karasubazar,Karasubozar,Bilohirsâk", :latitude => "45.0525", :longitude => "34.59596").save
City.new(:country_id => "230", :name => "Bar", :aliases => "Bar,ÐÐ°Ñ,Bar", :latitude => "49.06667", :longitude => "27.66667").save
City.new(:country_id => "230", :name => "Balta", :aliases => "Balta,ÐÐ°Ð»ÑÐ°,Balta", :latitude => "47.93722", :longitude => "29.61944").save
City.new(:country_id => "230", :name => "Balakliya", :aliases => "BALAKLEJA,Balakleya,Balaklia,Balakliya,ÐÐÐÐÐÐÐÐ¯,ÐÐ°Ð»Ð°ÐºÐ»ÑÑ,Balakliya", :latitude => "49.47", :longitude => "36.86389").save
City.new(:country_id => "230", :name => "Balaklava", :aliases => "Balaclava,Balaklava,Balaklavo,Balaklawa,Baliklava,BalÄ±klava,BaÅakÅawa,ÐÐ°Ð»Ð°ÐºÐ»Ð°Ð²Ð°,Balaklava", :latitude => "44.50618", :longitude => "33.60142").save
City.new(:country_id => "230", :name => "Bakhmach", :aliases => "Bachmatsch,Bakhmach,Bakhmach Romenskiy,ÐÐ°ÑÐ¼Ð°Ñ,Bakhmach", :latitude => "51.18333", :longitude => "32.78333").save
City.new(:country_id => "230", :name => "Bakhchysaray", :aliases => "Bachashisarai,Bachischissarai,Bachtjisaraj,Bachtschyssaraj,Bachtsjisaraj,Bahcesaray,Bahcisarajo,BahÃ§esaray,Bakczysaraj,Bakhchisaray,Bakhchysaray,Bakhehisaray,BaÄ¥Äisarajo,bafuchisarai,baheuchisalai,bakhchisaraj,ÐÐ°ÑÑÐ¸ÑÐ°ÑÐ°Ð¹,ããããµã©ã¤,ë°íì¹ì¬ë¼ì´,Bakhchysaray", :latitude => "44.75193", :longitude => "33.86667").save
City.new(:country_id => "230", :name => "Avdeyevka", :aliases => "AVDEEVKA,Avdeyevka,Avdiivka,Avdiyivka,Awdejewka,ÐÐÐÐÐÐÐÐ,ÐÐ²Ð´ÑÑÐ²ÐºÐ°,Avdeyevka", :latitude => "48.13833", :longitude => "37.73694").save
City.new(:country_id => "230", :name => "Artsyz", :aliases => "Archiz,Arcis,Arciz,Arsis,Arsiz,Artsis,Artsiz,Artsyz,ÐÑÑÐ¸Ð·,Artsyz", :latitude => "45.98333", :longitude => "29.41667").save
City.new(:country_id => "230", :name => "Artemivs'k", :aliases => "Artemivs'k,Artemivsâk,Artemovsk,Artemovskiy,Artemowsk,ArtÃ«movsk,Bakhmut,ÐÑÑÐµÐ¼Ð¾Ð²ÑÐº,Artemivsâk", :latitude => "48.59139", :longitude => "38.00806").save
City.new(:country_id => "230", :name => "Armyans'k", :aliases => "Armjansk,Armyans'k,Armyansk,Armyansâk,ÐÑÐ¼ÑÐ½ÑÐº,ÐÑÐ¼ÑÐ½ÑÑÐº,Armyansâk", :latitude => "46.1079", :longitude => "33.69387").save
City.new(:country_id => "230", :name => "Apostolove", :aliases => "Apostolove,Apostolovo,Apostolowo,ÐÐ¿Ð¾ÑÑÐ¾Ð»Ð¾Ð²Ðµ,Apostolove", :latitude => "47.66667", :longitude => "33.73333").save
City.new(:country_id => "230", :name => "Antratsit", :aliases => "Antracit,Antratsit,Bokovo-Antratsit,ÐÐ½ÑÑÐ°ÑÐ¸Ñ,Antratsit", :latitude => "48.11917", :longitude => "39.09").save
City.new(:country_id => "230", :name => "Amvrosiyivka", :aliases => "AMVROSIEVKA,Amvrosiivka,Amvrosiyevka,Amvrosiyivka,Donetsko Amerskevka,Donetsko-Amvrosiyevka,Donezko-Amwrossijewka,ÐÐÐÐ ÐÐ¡ÐÐÐÐÐ,ÐÐ¼Ð²ÑÐ¾ÑÑÑÐ²ÐºÐ°,Amvrosiyivka", :latitude => "47.79486", :longitude => "38.47722").save
City.new(:country_id => "230", :name => "Alushta", :aliases => "Aloushta,Alshta,Aluschta,Alushta,Alusta,Aluszta,AluÅta,AluÅ¡ta,AÅuszta,allusyuta,ÐÐ»ÑÑÑÐ°,ìë£¨ìí,Alushta", :latitude => "44.67471", :longitude => "34.40455").save
City.new(:country_id => "230", :name => "Alchevs'k", :aliases => "Alchevs'k,Alchevsk,Alchevskoe,Alchevsâk,Kommunarsk,Voroshilovsk,Woroschilowsk,ÐÐ»ÑÐµÐ²ÑÐº,Alchevsâk", :latitude => "48.47278", :longitude => "38.79972").save
City.new(:country_id => "230", :name => "Okhtyrka", :aliases => "AKHTYRKA,Achtyrka,Akhtirka,Akhtyrka,Okhtirka,Okhtyrka,ÐÐ¥Ð¢Ð«Ð ÐÐ,ÐÑÑÐ¸ÑÐºÐ°,Okhtyrka", :latitude => "50.30861", :longitude => "34.89417").save
City.new(:country_id => "230", :name => "Komsomolsk", :aliases => "Komsomol's'k,ÐÐ¾Ð¼ÑÐ¾Ð¼Ð¾Ð»ÑÑÑÐº,Komsomolsk", :latitude => "49.00973", :longitude => "33.64546").save
City.new(:country_id => "230", :name => "Slavutich", :aliases => "Slavutich,Ð¡Ð»Ð°Ð²ÑÑÐ¸Ñ,Ð¡Ð»Ð°Ð²ÑÑÐ¸Ñ", :latitude => "51.51964", :longitude => "30.73434").save
City.new(:country_id => "230", :name => "Yuzhnoukrains'k", :aliases => "Juzhnoukrains'k,Juzhnoukrainsk,Ð®Ð¶Ð½Ð¾ÑÐºÑÐ°Ð¸Ð½ÑÐº,Ð®Ð¶Ð½Ð¾ÑÐºÑÐ°ÑÐ½ÑÑÐº,Yuzhnoukrains'k", :latitude => "47.81777", :longitude => "31.18263").save
