City.new(:country_id => "241", :name => "Yen Vinh", :aliases => ",YÃªn Vinh", :latitude => "18.66667", :longitude => "105.66667").save
City.new(:country_id => "241", :name => "Yen Bai", :aliases => "Jenbaj,Yen Bai,Yen Bay,YÃªn BÃ¡i,ÐÐµÐ½Ð±Ð°Ð¹,YÃªn BÃ¡i", :latitude => "21.7", :longitude => "104.86667").save
City.new(:country_id => "241", :name => "Vung Tau", :aliases => "Cap-Saint-Jacques,Saint James,Ville du Cap,Vung Tau,VÅ©ng TÃ u,Xa Vung Tau,tou dun shi,é ­ é å¸,VÅ©ng TÃ u", :latitude => "10.35", :longitude => "107.06667").save
City.new(:country_id => "241", :name => "Vinh Yen", :aliases => "Vieh Yen,Vinh Yen,VÄ©nh YÃªn,Yen,VÄ©nh YÃªn", :latitude => "21.31", :longitude => "105.59667").save
City.new(:country_id => "241", :name => "Vinh Long", :aliases => "Vinh Long,VÄ©nh Long,VÄ©nh Long", :latitude => "10.25", :longitude => "105.96667").save
City.new(:country_id => "241", :name => "Vinh", :aliases => "Vin,Vinh,Vinh", :latitude => "18.66667", :longitude => "105.66667").save
City.new(:country_id => "241", :name => "Viet Tri", :aliases => "Viet Tri,Vietri,Viá»t TrÃ¬,Viá»t TrÃ¬", :latitude => "21.30194", :longitude => "105.43083").save
City.new(:country_id => "241", :name => "Uong Bi", :aliases => ",UÃ´ng BÃ­", :latitude => "21.03333", :longitude => "106.78333").save
City.new(:country_id => "241", :name => "Tuy Hoa", :aliases => "Chau Thanh,Thuy Hoa,Toy Hoa,Tuy Hoa,Tuy HÃ²a,Tuy HÃ²a", :latitude => "13.08333", :longitude => "109.3").save
City.new(:country_id => "241", :name => "Tuyen Quang", :aliases => "Tuyen Kang,Tuyen Kwang,Tuyen Quang,TuyÃªn Quang,TuyÃªn Quang", :latitude => "21.82333", :longitude => "105.21806").save
City.new(:country_id => "241", :name => "Tra Vinh", :aliases => "Phu Vinh,PhÃº Vinh,Tra Vin',Tra Vinh,Tra Vinâ,TrÃ  Vinh,TrÃ  Vinh", :latitude => "9.93472", :longitude => "106.34528").save
City.new(:country_id => "241", :name => "Thu Dau Mot", :aliases => "Phu Cuong,PhÃº CÆ°á»ng,Thu Dau Mot,Thá»§ Dáº§u Má»t,Thá»§ Dáº§u Má»t", :latitude => "10.96667", :longitude => "106.65").save
City.new(:country_id => "241", :name => "Thanh pho Ho Chi Minh", :aliases => "Cathair Ho Chi Minh,Cidade de Ho Chi Minh,Ciudad Ho Chi Minh,HCMC,HCMV,Ho Chi Minh,Ho Chi Minh City,Ho Chi Minh Ville,Ho Chi Minh borg,Ho Chi Minh-byen,Ho Chi Minhin kaupunki,Ho Chi Minhstad,Ho Si Minh-varos,Ho Si Minh-vÃ¡ros,Ho-Chi-Minh-Stadt,Ho-Chi-Minh-Ville,Ho-Ci-Min-Urbo,Ho-Äi-Min-Urbo,Hociminovo Mesto,Hosimina,Hosiminh,HoÄiminovo Mesto,HoÅ¡imina,HoÅ¡iminh,HÃ´ Chi Minh Ville,HÃ´-Chi-Minh-Ville,Kho Shi Min,Khoshimin,Kota Ho Chi Minh,Sai Gon,Saigon,SaÃ¯gon,SÃ i GÃ²n,TPHCM,Thanh pho Ho Chi Minh,ThÃ nh phá» Há» ChÃ­ Minh,hochimin,hochimin shi,hojjimin si,hu zhi ming shi,hw z'y myn syty,mdynt hwshy mnh,saigon,saygwn,Ð¥Ð¾ Ð¨Ð¸ ÐÐ¸Ð½,Ð¥Ð¾ÑÐ¸Ð¼Ð¸Ð½,×× ×¦'× ××× ×¡×××,Ø³Ø§ÙÚ¯ÙÙ,ÙØ¯ÙÙØ© ÙÙØ´Ù ÙÙÙ,ãµã¤ã´ã³,ãã¼ããã³,ãã¼ããã³å¸,è¡å¿æå¸,í¸ì°ë¯¼ ì,ThÃ nh phá» Há» ChÃ­ Minh", :latitude => "10.75", :longitude => "106.66667").save
City.new(:country_id => "241", :name => "Thanh Hoa", :aliases => "Than' Hoa,Thanh Hoa,Thanh HÃ³a,Thanâ Hoa,Thanh HÃ³a", :latitude => "19.8", :longitude => "105.76667").save
City.new(:country_id => "241", :name => "Thai Nguyen", :aliases => "Taj-Nguen,Thai Nguyen,ThÃ¡i NguyÃªn,Ð¢Ð°Ð¹-ÐÐ³ÑÐµÐ½,ThÃ¡i NguyÃªn", :latitude => "21.59278", :longitude => "105.84417").save
City.new(:country_id => "241", :name => "Thai Binh", :aliases => "Kua Loc,Taibinh,Thai Bin',Thai Binh,Thai Binâ,ThÃ¡i BÃ¬nh,ThÃ¡i BÃ¬nh", :latitude => "20.45", :longitude => "106.33333").save
City.new(:country_id => "241", :name => "Tay Ninh", :aliases => "Tai nin,Tay Ninh,Tei Nin,TÃ¢y Ninh,TÃ¢y Ninh", :latitude => "11.3", :longitude => "106.1").save
City.new(:country_id => "241", :name => "Tan An", :aliases => "Tan,Tan Am,Tan An,TÃ¢n An,Ð¢Ð°Ð½,TÃ¢n An", :latitude => "10.53333", :longitude => "106.41667").save
City.new(:country_id => "241", :name => "Tam Ky", :aliases => "Tam Ky,Tam Ká»³,Tanky,Tam Ká»³", :latitude => "15.56667", :longitude => "108.48333").save
City.new(:country_id => "241", :name => "Son Tay", :aliases => "Son Tay,Son-Taj,Sontai,SÆ¡n TÃ¢y,Ð¡Ð¾Ð½-Ð¢Ð°Ð¹,SÆ¡n TÃ¢y", :latitude => "21.13778", :longitude => "105.505").save
City.new(:country_id => "241", :name => "Son La", :aliases => "Son La,Son La Chau,Son Lu,Son-La,SÆ¡n La,Ð¡Ð¾Ð½-ÐÐ°,SÆ¡n La", :latitude => "21.31667", :longitude => "103.9").save
City.new(:country_id => "241", :name => "Song Cau", :aliases => "Bong Cau,BÃ´ng Cáº§u,Song Cau,Song Ka,Song Ko,Songkau,SÃ´ng Cáº§u,SÃ´ng Cáº§u", :latitude => "13.45", :longitude => "109.21667").save
City.new(:country_id => "241", :name => "Soc Trang", :aliases => "Khanh Hong,Khanh Hung,KhÃ¡nh HÆ°ng,Shokchang,Soc Trang,Sok Trang,SÃ³c TrÄng,Ð¨Ð¾ÐºÑÐ°Ð½Ð³,SÃ³c TrÄng", :latitude => "9.60333", :longitude => "105.98").save
City.new(:country_id => "241", :name => "Sa Pa", :aliases => "Chapa,Shapa,Ð¨Ð°Ð¿Ð°,Sa PÃ¡", :latitude => "22.34023", :longitude => "103.84415").save
City.new(:country_id => "241", :name => "Sa Dec", :aliases => "Sa Dec,Sa ÃÃ©c,Sadek,Sa ÃÃ©c", :latitude => "10.3", :longitude => "105.76667").save
City.new(:country_id => "241", :name => "Rach Gia", :aliases => "Rach Gia,Rach Zhia,Ráº¡ch GiÃ¡,Ráº¡ch GiÃ¡", :latitude => "10.01667", :longitude => "105.08333").save
City.new(:country_id => "241", :name => "Quy Nhon", :aliases => "Ki N'on,Ki Nâon,Kin-hon,Kwinhon,Qui Nhan,Qui Nhon,Qui NhÆ¡n,Quinn Yan,Quinton,Quy Nhon,Quy NhÆ¡n,Xa Qui Nhon,XÃ£ Qui NhÃ´n,Quy NhÆ¡n", :latitude => "13.76667", :longitude => "109.23333").save
City.new(:country_id => "241", :name => "Quang Ngai", :aliases => "Kang Ngei,Kuangngaj,Kwang Ngai,Quang Ngai,Quáº£ng NgÃ£i,Thanh pho Quang Ngai,ThÃ nh phá» Quáº£ng NgÃ£i,ÐÑÐ°Ð½Ð³Ð½Ð³Ð°Ð¹,Quáº£ng NgÃ£i", :latitude => "15.11667", :longitude => "108.8").save
City.new(:country_id => "241", :name => "Pleiku", :aliases => "Gia Lai,Play Cu,Play Ku,Plei Cu,Pleiku,Plejku,PlÃ¢y Cu,PlÃ¢y Ku,Tinh Pleiku,Tá»nh Pleiku,ÐÐ»ÐµÐ¹ÐºÑ,Pleiku", :latitude => "13.98333", :longitude => "108").save
City.new(:country_id => "241", :name => "Phu Ly", :aliases => "Fu Li,Ha-Nam,Phu Ly,Phu-li,Phá»§ LÃ½,Phá»§ LÃ½", :latitude => "20.54111", :longitude => "105.91389").save
City.new(:country_id => "241", :name => "Phu Khuong", :aliases => ",PhÃº KhÆ°Æ¡ng", :latitude => "11.28333", :longitude => "106.13333").save
City.new(:country_id => "241", :name => "Phan Thiet", :aliases => "Fan Thiet,Fant'et,Fanthit,Fantiet,Phan Thiet,Phan Thiáº¿t,Phan Tiet,Xa Phan Thiet,pan qie,Ð¤Ð°Ð½ÑÑÐµÑ,æ½å,Phan Thiáº¿t", :latitude => "10.93333", :longitude => "108.1").save
City.new(:country_id => "241", :name => "Phan Rang-Thap Cham", :aliases => "Phan Rang,Phan Rang- Thap Cham,Phan Rang-Thap Cham,Phan Rang-ThÃ¡p ChÃ m,Phan Ranh,Phan Rang-ThÃ¡p ChÃ m", :latitude => "11.56667", :longitude => "108.98333").save
City.new(:country_id => "241", :name => "Ninh Binh", :aliases => "Nin Bin',Nin Binâ,Ninbinh,Ninh Binh,Ninh BÃ¬nh,Ninh BÃ¬nh", :latitude => "20.25389", :longitude => "105.975").save
City.new(:country_id => "241", :name => "Nha Trang", :aliases => "Kanh-Hoa,Nha Trang,Njachang,nyachan,ÐÑÑÐ°Ð½Ð³,ãã£ãã£ã³,Nha Trang", :latitude => "12.25", :longitude => "109.18333").save
City.new(:country_id => "241", :name => "Nam Dinh", :aliases => "Nam Din',Nam Dinh,Nam Dinâ,Nam Ãá»nh,Namdin',ÐÐ°Ð¼Ð´Ð¸Ð½Ñ,Nam Ãá»nh", :latitude => "20.41667", :longitude => "106.16667").save
City.new(:country_id => "241", :name => "My Tho", :aliases => "Mitho,My Tho,Má»¹ Tho,Má»¹ Tho", :latitude => "10.35", :longitude => "106.35").save
City.new(:country_id => "241", :name => "Long Xuyen", :aliases => "Cholong Xuyen,ChÆ¡long Xuyen,Long Swiyen,Long Xuyen,Long XuyÃªn,Long-Shuyen,Long XuyÃªn", :latitude => "10.38333", :longitude => "105.41667").save
City.new(:country_id => "241", :name => "Lao Cai", :aliases => "Lao Kay,Laokai,Laokaj,ÐÐ°Ð¾ÐºÐ°Ð¹,LÃ o Cai", :latitude => "22.48333", :longitude => "103.95").save
City.new(:country_id => "241", :name => "Lang Son", :aliases => ",Láº¡ng SÆ¡n", :latitude => "21.83333", :longitude => "106.73333").save
City.new(:country_id => "241", :name => "Kon Tum", :aliases => "Cong Tum,CÃ´ng Tum,Kon Tum,Tinh Kontum,Tá»nh Kontum,Kon Tum", :latitude => "14.35", :longitude => "108").save
City.new(:country_id => "241", :name => "Hung Yen", :aliases => "Hong-Yen,Hung Yen,HÆ°ng YÃªn,HÆ°ng YÃªn", :latitude => "20.65", :longitude => "106.06667").save
City.new(:country_id => "241", :name => "Hue", :aliases => "Hue,HuÃ©,Huáº¿,Khjue,Khue,fue,shun hua,Ð¥ÑÐµ,Ð¥ÑÐµ,ãã¨,é å,é¡ºå,Huáº¿", :latitude => "16.46667", :longitude => "107.6").save
City.new(:country_id => "241", :name => "Ha Long", :aliases => "Ha Long,Hon Cay,Hon Gai,Hon Gay,Hon Goi,Hong Gai,Honggay,Háº¡ Long,Há»ng Gai,Khalong,xia long shi,Ð¥Ð°Ð»Ð¾Ð½Ð³,ä¸é¾å¸,Háº¡ Long", :latitude => "20.95111", :longitude => "107.08").save
City.new(:country_id => "241", :name => "Hoi An", :aliases => "Faifo,Faifoh,Faifoo,Feifu,Hoi An,HÃ´i An,Há»i An,Khoj,hoian,Ð¥Ð¾Ð¹,ãã¤ã¢ã³,Há»i An", :latitude => "15.87944", :longitude => "108.335").save
City.new(:country_id => "241", :name => "Hoa Binh", :aliases => "Hao Binh,Hoa Bin,Hoa Binh,HÃ²a BÃ¬nh,HÃ²a BÃ¬nh", :latitude => "20.81333", :longitude => "105.33833").save
City.new(:country_id => "241", :name => "Ha Tinh", :aliases => "Ha Tin',Ha Tinh,Ha Tinâ,HÃ  TÄ©nh,Khatin',Ð¥Ð°ÑÐ¸Ð½Ñ,HÃ  TÄ©nh", :latitude => "18.33333", :longitude => "105.9").save
City.new(:country_id => "241", :name => "Ha Tien", :aliases => "Ha Tien,HÃ  TiÃªn,Khat'en,Ð¥Ð°ÑÑÐµÐ½,HÃ  TiÃªn", :latitude => "10.38333", :longitude => "104.48333").save
City.new(:country_id => "241", :name => "Ha Noi", :aliases => "Anoi,Ha Noi,Hanoi,Hanoj,Hanojus,HanoÃ¯,HanÃ³i,HÃ  Ná»i,Keicho,Khanoj,hanoi,hanwy,hanxy,he nei,ÎÎ½ÏÎ¹,Ð¥Ð°Ð½Ð¾Ð¹,××× ××,ÙØ§ÙÙÙ,ÙØ§ÙÙÛ,à¸®à¸²à¸à¸­à¸¢,ááá­,ããã¤,æ²³å§,íë¸ì´,HÃ  Ná»i", :latitude => "21.0245", :longitude => "105.84117").save
City.new(:country_id => "241", :name => "Haiphong", :aliases => "Hai Phong,Haiphong,Hajfong,Háº£i PhÃ²ng,Khajfon,hai fang shi,haifon,hayfwngh,hi fxng,Ð¥Ð°Ð¹ÑÐ¾Ð½,ÙØ§ÙÙÙÙØº,à¹à¸®à¸à¸­à¸,ãã¤ãã©ã³,æµ·é²å¸,Haiphong", :latitude => "20.85611", :longitude => "106.68222").save
City.new(:country_id => "241", :name => "Hai Duong", :aliases => "Hai Doong,Hai Duong,Hai dzung,Hai-Doung,Haidong,HaidÃ¶ng,Háº£i DÆ°Æ¡ng,Khajzyong,Ð¥Ð°Ð¹Ð·ÑÐ¾Ð½Ð³,Háº£i DÆ°Æ¡ng", :latitude => "20.93333", :longitude => "106.31667").save
City.new(:country_id => "241", :name => "Ha Giang", :aliases => ",HÃ  Giang", :latitude => "22.83333", :longitude => "104.98333").save
City.new(:country_id => "241", :name => "Ha Dong", :aliases => ",HÃ  ÃÃ´ng", :latitude => "20.9725", :longitude => "105.77722").save
City.new(:country_id => "241", :name => "Dong Xoai", :aliases => "Ap Dong Xoai,Don Luan,Dong Xoa,Dong Xoai,Dong Xoi,Dá»ng XoÃ i,áº¤p Ãá»ng XoÃ i,Dá»ng XoÃ i", :latitude => "11.53333", :longitude => "106.91667").save
City.new(:country_id => "241", :name => "Dong Hoi", :aliases => "Dong Hoi,Dongkhoj,Kwang Binh,tong hai shi,Ãá»ng Há»i,Äá»ng Há»i,ÐÐ¾Ð½Ð³ÑÐ¾Ð¹,å æµ· å¸,Ãá»ng Há»i", :latitude => "17.48333", :longitude => "106.6").save
City.new(:country_id => "241", :name => "Dong Ha", :aliases => "Dong Ha,Dong Na,Thi Xa Dong Ha,Thi XÃ£ ÃÃ²ng HÃ ,ÃÃ´ng HÃ ,ÃÃ´ng HÃ ", :latitude => "16.81625", :longitude => "107.10031").save
City.new(:country_id => "241", :name => "Dien Bien Phu", :aliases => "D'en B'en Fu,Dien Bien,Dien Bien Phu,DiÃªn BiÃªn Phu,Opsada Äiá»n BiÃªn Phá»§a,dian bian fu,dienbienfu,dienbienpu,Ãiá»n BiÃªn,Ãiá»nÂ BiÃªnÂ Phá»§,Äiá»n BiÃªn Phá»§,ÐÑÐµÐ½ ÐÑÐµÐ½ Ð¤Ñ,ãã£ã¨ã³ãã¨ã³ãã¼,å¥ éåº,ëìë¹ìí¸,Diá»n BiÃªn Phá»§", :latitude => "21.38333", :longitude => "103.01667").save
City.new(:country_id => "241", :name => "Turan", :aliases => "Da Nang,Danang,Tourane,Turan,danan,xian gang,ÃÃ  Náºµng,ÄÃ  Náºµng,ÐÐ° ÐÐ°Ð½Ð³,ããã³,å²æ¸¯,å³´æ¸¯,Turan", :latitude => "16.06778", :longitude => "108.22083").save
City.new(:country_id => "241", :name => "Da Lat", :aliases => "Da Lat,Da lat,Dalat,ÃÃ  Láº¡t,ÐÐ°Ð»Ð°Ñ,ÃÃ  Láº¡t", :latitude => "11.94646", :longitude => "108.44193").save
City.new(:country_id => "241", :name => "Cu Chi", :aliases => "Cu Chi,Cá»§ Chi,Ku-Chi,ÐÑ-Ð§Ð¸,Cá»§ Chi", :latitude => "10.96667", :longitude => "106.46667").save
City.new(:country_id => "241", :name => "Chau Doc", :aliases => "Angiang,Chau Doc,Chau Phu,Chau PhÃº,Chaudok,Cho Dok,ChÃ¢u Ãá»c,ChÃ¢u Ãá»c", :latitude => "10.7", :longitude => "105.11667").save
City.new(:country_id => "241", :name => "Cao Lanh", :aliases => "Cao Lanh,Cao LÃ£nh,Phong Thanh,Cao LÃ£nh", :latitude => "10.45", :longitude => "105.63333").save
City.new(:country_id => "241", :name => "Cao Bang", :aliases => "Cao Bang,Cao Báº±ng,Cao Pang,Kao Bang,Kao banh,Kaobang,ÐÐ°Ð¾Ð±Ð°Ð½Ð³,Cao Báº±ng", :latitude => "22.66667", :longitude => "106.25").save
City.new(:country_id => "241", :name => "Can Tho", :aliases => "Can Tho,Cáº§n ThÆ¡,Kan Tho,kanto,qin ju shi,ã«ã³ãã¼,è¹è´å¸,Cáº§n ThÆ¡", :latitude => "10.03333", :longitude => "105.78333").save
City.new(:country_id => "241", :name => "Can Gio", :aliases => "Can Gio,Cáº§n Giá»,Cáº§n Giá»", :latitude => "10.41667", :longitude => "106.96667").save
City.new(:country_id => "241", :name => "Can Duoc", :aliases => "Can Duoc,Can Gioc,Can Giuoc,Cáº§n Duá»c,Cáº§n Giuá»c,Cáº§n Duá»c", :latitude => "10.61667", :longitude => "106.66667").save
City.new(:country_id => "241", :name => "Cam Ranh", :aliases => "Cam Linh,Cam Ranh Port,Kamran',Thon Cam Ranh,ThÃ´n Cam Ranh,ÐÐ°Ð¼ÑÐ°Ð½Ñ,Cam Ranh", :latitude => "11.92144", :longitude => "109.15913").save
City.new(:country_id => "241", :name => "Cam Pha Mines", :aliases => ",Cáº©m Pháº£ Mines", :latitude => "21.01667", :longitude => "107.3").save
City.new(:country_id => "241", :name => "Ca Mau", :aliases => "Ca Mau,Camo,Cu Mau,CÃ  Mau,Kamao,Kamau,Quan Long,Quang Long,Song Kualon,ÐÐ°Ð¼Ð°Ñ,CÃ  Mau", :latitude => "9.17694", :longitude => "105.15").save
City.new(:country_id => "241", :name => "Buon Ma Thuot", :aliases => "Ban Me Thaut,Ban Me Thnot,Ban Me Thot,Ban Me Thout,Ban Me Thuot,Ban MÃª Thuá»t,Ban-me-Thurt,Benmethout,Buon Ma Thuot,Buon Me Thuot,BuÃ´n Ma Thuá»t,BuÃ´n MÃª Thuá»t,Lac Giao,Láº¡c Giao,Me Thuot,BuÃ´n Ma Thuá»t", :latitude => "12.66667", :longitude => "108.05").save
City.new(:country_id => "241", :name => "Bim Son", :aliases => "Bien Son,Bim Son,BiÃªn SÆ¡n,Bá»m SÆ¡n,Bá»m SÆ¡n", :latitude => "20.07806", :longitude => "105.86028").save
City.new(:country_id => "241", :name => "Bien Hoa", :aliases => "Bia Hoa,Bien Hoa,BiÃªn HÃ²a,BiÃªn HÃ²a", :latitude => "10.95", :longitude => "106.81667").save
City.new(:country_id => "241", :name => "Ben Tre", :aliases => "Ben Tre,Báº¿n Tre,Truc Giang,TrÃºc Giang,Báº¿n Tre", :latitude => "10.23333", :longitude => "106.38333").save
City.new(:country_id => "241", :name => "Bac Ninh", :aliases => "Bac Ninh,Bacht Ninh,Bak Nin,Bak Ninh,Báº¯c Ninh,Báº¯c Ninh", :latitude => "21.18333", :longitude => "106.05").save
City.new(:country_id => "241", :name => "Bac Lieu", :aliases => "Bac Lieu,Bac-Lien,Bach Lieu,Bak Lieu,Báº¡c LiÃªu,Vinh Loi,VÄ©nh Lá»£i,Báº¡c LiÃªu", :latitude => "9.285", :longitude => "105.72444").save
City.new(:country_id => "241", :name => "Bac Giang", :aliases => "Bac Giang,Báº¯c Giang,Phu Lang Thong,Phu Lang Thuong,Phu Long Thuong,Thuong,Báº¯c Giang", :latitude => "21.26667", :longitude => "106.2").save
City.new(:country_id => "241", :name => "Bac Kan", :aliases => "Bac Can,Bac Kan,Bak Kan,Báº¯c Cáº¡n,Báº¯c Káº¡n,Báº¯c Káº¡n", :latitude => "22.13333", :longitude => "105.83333").save
