City.new(:country_id => "-1", :name => "Vushtrri", :aliases => "Vicianum,Vicitirin,Vuchitrn,Vucitern,Vuciterne,Vucitrn,Vushtrri,VuÃ§itÃ«rn,VuÃ§itÃ«rnÃ«,VuÄitrn,VÄ±Ã§Ä±tÄ±rÄ±n,ÐÑÑÐ¸ÑÑÐ½,Vushtrri", :latitude => "42.82306", :longitude => "20.9675").save
City.new(:country_id => "-1", :name => "Ferizaj", :aliases => "Ferezaj,Ferizaj,Ferizovik,Urosevac,Uroshevac,UroÅ¡evac,Ð£ÑÐ¾ÑÐµÐ²Ð°Ñ,Ferizaj", :latitude => "42.37056", :longitude => "21.15528").save
City.new(:country_id => "-1", :name => "Suva Reka", :aliases => "Lumthate,LumthatÃ«,Suha Reka,Suhareka,Suhareke,SuharekÃ«,Suharjeka,Sukareke,SukarekÃ«,Suva Reka,Suva Reki,Theranda,ThÃ«randa,Ð¡ÑÐ²Ð° Ð ÐµÐºÐ°,Suva Reka", :latitude => "42.35861", :longitude => "20.825").save
City.new(:country_id => "-1", :name => "Shtime", :aliases => "Shtime,Shtimle,Stimle,Stimlje,Åtimle,Å timlje,Ð¨ÑÐ¸Ð¼ÑÐµ,Shtime", :latitude => "42.43306", :longitude => "21.03972").save
City.new(:country_id => "-1", :name => "Prizren", :aliases => "Perzeren,Perzerin,Prizren,Prizrena,Prizrenas,Prizreni,PÃ«rzeren,bryzrn,ÐÑÐ¸Ð·ÑÐµÐ½,Ø¨Ø±ÙØ²Ø±Ù,Prizren", :latitude => "42.21389", :longitude => "20.73972").save
City.new(:country_id => "-1", :name => "Pristina", :aliases => "Prishhina,Prishtina,Prishtine,PrishtinÃ«,Prisjtina,Pristina,Prisztina,PriÅ¡tina,pu li shi ti na,purishutina,ÐÑÐ¸ÑÑÐ¸Ð½Ð°,ÐÑÐ¸ÑÐ¸Ð½Ð°,ããªã·ã¥ãã£ã,æ®éå£«æç´,Pristina", :latitude => "42.67272", :longitude => "21.16688").save
City.new(:country_id => "-1", :name => "Podujeva", :aliases => "Besiana,Besiane,BesianÃ«,Podjeve,PodjevÃ«,Podujeva,Podujeve,Podujevo,PodujevÃ«,PodujevÃ³,Podujeva", :latitude => "42.91056", :longitude => "21.19306").save
City.new(:country_id => "-1", :name => "Peje", :aliases => "Ipek,Pec,Pecas,Pech,Pegia,Peja,Peje,PejÃ«,PeÄ,PeÄas,Picaria,Î Î­Î³Î¹Î±,ÐÐµÑ,ÐÐµÑ,PejÃ«", :latitude => "42.65913", :longitude => "20.28828").save
City.new(:country_id => "-1", :name => "Orahovac", :aliases => "Orahovac,Orakhovac,Rahavec,Rahovec,Rahoveci,ÐÑÐ°ÑÐ¾Ð²Ð°Ñ,Orahovac", :latitude => "42.39944", :longitude => "20.65472").save
City.new(:country_id => "-1", :name => "Llazice", :aliases => "Llazice,LlazicÃ«,Llozice,LlozicÃ«,Lozica,LlazicÃ«", :latitude => "42.55528", :longitude => "20.76333").save
City.new(:country_id => "-1", :name => "Leposavic", :aliases => "Albaniku,Leposavic,Leposavici,Leposaviq,LeposaviÄ,LeposaviÄi,ÐÐµÐ¿Ð¾ÑÐ°Ð²Ð¸Ñ,LeposaviÄ", :latitude => "43.10389", :longitude => "20.80278").save
City.new(:country_id => "-1", :name => "Mitrovice", :aliases => "Kosovska Mitrovica,Mitrovica,Mitrovice,MitrovicÃ«,ÐÐ¾ÑÐ¾Ð²ÑÐºÐ° ÐÐ¸ÑÑÐ¾Ð²Ð¸ÑÐ°,MitrovicÃ«", :latitude => "42.88333", :longitude => "20.86667").save
City.new(:country_id => "-1", :name => "Kosovo Polje", :aliases => "Fushe Kosove,Fushe-Kosova,FushÃ« KosovÃ«,FushÃ«-Kosova,Kosovo,Kosovo Pole,Kosovo Polje,ÐÐ¾ÑÐ¾Ð²Ð¾ ÐÐ¾ÑÐµ,Kosovo Polje", :latitude => "42.63944", :longitude => "21.09611").save
City.new(:country_id => "-1", :name => "Istok", :aliases => "Burim,Burimi,Istog,Istogu,Istok,ÐÑÑÐ¾Ðº,Istok", :latitude => "42.78083", :longitude => "20.4875").save
City.new(:country_id => "-1", :name => "Gjilan", :aliases => "Gilan,Gjilan,Gjilani,Gnilane,Gniljane,Gnjilane,GnjilanÄ,Komuna e Gjilanit,ÐÑÐ¸Ð»Ð°Ð½Ðµ,Gjilan", :latitude => "42.46045", :longitude => "21.46986").save
City.new(:country_id => "-1", :name => "Dragash", :aliases => "Dagash,Dragas,Dragash,Dragashi,DragaÅ¡,Sharr,Sharri,ÐÑÐ°Ð³Ð°Ñ,Dragash", :latitude => "42.0625", :longitude => "20.65333").save
City.new(:country_id => "-1", :name => "Decan", :aliases => "Decan,Decani,Dekan,DeÃ§an,DeÃ§ani,ÐÐµÐºÐ°Ð½,DeÃ§an", :latitude => "42.54018", :longitude => "20.28793").save
