City.new(:country_id => "245", :name => "Zabid", :aliases => "Zabid,ZabÄ«d,Zebid,ÐÐ°Ð±Ð¸Ð´,ZabÄ«d", :latitude => "14.1951", :longitude => "43.31518").save
City.new(:country_id => "245", :name => "Yarim", :aliases => "Jarim,Yarim,YarÄ«m,Yerim,Ð¯ÑÐ¸Ð¼,YarÄ«m", :latitude => "14.29804", :longitude => "44.37795").save
City.new(:country_id => "245", :name => "Ta`izz", :aliases => "Ta'izz,Ta`izz,Taiz,Taizz,Taâizz,Ð¢Ð°Ð¸Ð·,ØªØ¹Ø²,Taâizz", :latitude => "13.57952", :longitude => "44.02091").save
City.new(:country_id => "245", :name => "Sayyan", :aliases => "Saiyan,SaiyÄn,Sayyan,SayyÄn,Seijan,SeijÃ¢n,Sian,Siryan,SiryÄn,SayyÄn", :latitude => "15.17177", :longitude => "44.32442").save
City.new(:country_id => "245", :name => "Sanaa", :aliases => "San'o,San'a,San'a',San'ah,San`a',Sana,Sana'a,Sanaa,SanaÃ ,SanaÃ¡,SanÃ¡,Sanâah,sa na,sana,sanua,ÅanâÄ',ÅanâÄâ,Î£Î¬Î½Î±,Ð¡Ð°Ð½Ð°,Ð¡Ð°Ð½ÑÐ¾,×¦× ×¢×,ØµÙØ¹Ø§Ø¡,á³á,ãµãã¢,è¨é£,ì¬ë,Sanaa", :latitude => "15.35472", :longitude => "44.20667").save
City.new(:country_id => "245", :name => "Sahar", :aliases => "Sahar,Saá¸©ar,Saá¸©ar", :latitude => "15.31586", :longitude => "44.30858").save
City.new(:country_id => "245", :name => "Lahij", :aliases => "Al Hawtah,Al á¸¨awÅ£ah,Lahaj,Lahej,Lahij,Lahj,Lakhydzh,Laá¸©ij,ÐÐ°ÑÑÐ´Ð¶,ÙØ­Ø¬,Laá¸©ij", :latitude => "13.05667", :longitude => "44.88194").save
City.new(:country_id => "245", :name => "Ibb", :aliases => ",Ibb", :latitude => "13.96667", :longitude => "44.18333").save
City.new(:country_id => "245", :name => "Hajjah", :aliases => "Hage,Haggah,Haggiah,Hajja,Hajjah,Hajje,Khadzh,Ð¥Ð°Ð´Ð¶,Ø­Ø¬Ø©,á¸¤age,á¸¤aggah,á¸¤aggiah,á¸¨ajjah,á¸¨ajjah", :latitude => "15.69425", :longitude => "43.60582").save
City.new(:country_id => "245", :name => "Dhi Sufal", :aliases => "Dhi Sifal,Dhi Sufal,Dhi as Sufal,Dhi es-Sifal,DhÄ« Sifal,DhÄ« SufÄl,DhÄ« as SufÄl,DhÄ« es-SifÄl,DhÄ« SufÄl", :latitude => "13.83446", :longitude => "44.11469").save
City.new(:country_id => "245", :name => "Bayt al Faqih", :aliases => "Bait al Faqih,Bait al FaqÄ«h,Bayt al Fakih Ibn `Udjayl,Bayt al Fakih al-Saghir,Bayt al FakÄ«h Ibn âUdjayl,Bayt al FakÄ«h al-SaghÄ«r,Bayt al Faqih,Bayt al FaqÄ«h,Bayt al-Fakih,Bayt al-FakÄ«h,Beit Faqih,Beit el-Faqih,Beit el-FaqÄ«h,Beit-el-Fakih,Bayt al FaqÄ«h", :latitude => "14.51635", :longitude => "43.32446").save
City.new(:country_id => "245", :name => "Bajil", :aliases => "Badjil,Bagil,Bajil,BÃ¢djil,BÄgil,BÄjil,BÄjil", :latitude => "15.05835", :longitude => "43.28506").save
City.new(:country_id => "245", :name => "Al Mukalla", :aliases => "Al Mukalla,Al MukallÄ,Al'-Mukalla,Al-Mukalla,Mukalla,ÐÐ»Ñ-ÐÑÐºÐ°Ð»Ð»Ð°,Ø§ÙÙÙÙØ§,Al MukallÄ", :latitude => "14.54248", :longitude => "49.12424").save
City.new(:country_id => "245", :name => "Al Hudaydah", :aliases => "Al Hudaydah,Al á¸¨udaydah,El-Hodeidah,El-á¸¤odeidah,Hodaidah,Hodeida,Hudaida,Hudaydah,hdydh,Ø§ÙØ­Ø¯ÙØ¯Ø©,Ø­Ø¯ÛØ¯Ù,á¸¨udaydah,Al á¸¨udaydah", :latitude => "14.79781", :longitude => "42.95452").save
City.new(:country_id => "245", :name => "Al Bayda'", :aliases => "Al Bayda',Al Bayá¸Äâ,Al Beidha,Al-Baida,Al-Baidhah,Al-BaidÄ,Beida,Beidha,Ø§ÙØ¨ÙØ¶Ø§Ø¡,Al Bayá¸Äâ", :latitude => "13.98278", :longitude => "45.575").save
City.new(:country_id => "245", :name => "Aden", :aliases => "Adem,Aden,Adeno,AdÃ©n,AdÃ©n - Ø¹Ø¯Ù,`Adan,aden,ya ding,Ãden,ÐÐ´ÐµÐ½,×¢××,Ø¹Ø¯Ù,âAdan,ã¢ãã³,äºä¸,ìë´,Aden", :latitude => "12.77944", :longitude => "45.03667").save
